language: cpp
complier:
  - gcc
  - clang
before_install:
  - echo "yes" | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get -qq update
  - sudo apt-get -qq install cmake build-essential libsdl2-dev libsdl2-ttf-dev bison flex libpng-dev
install:
  - cd $TRAVIS_BUILD_DIR
  - cmake .
script:
  - make
notifications:
  email: false
  irc:
    channels:
      - "irc.oftc.net#freerct"
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true
