FreeRCT: ast.h File Reference
ast.h File Reference
AST data structures.
#include <list>
#include <string>
#include <memory>
Classes
class Position
Position in a source file.
struct Symbol
A Symbol in a 'symbol table'.
class Expression
Base class of expressions.
class ExpressionList
A sequence of expressions.
class UnaryOperator
Unary operator expression.
class BinaryOperator
Binary operator expression.
class StringLiteral
String literal elementary expression node.
class IdentifierLiteral
Identifier elementary expression node.
class NumberLiteral
Number literal elementary expression node.
class BitSet
Bit set expression ('or' of '1 << arg').
class Name
Base class for labels of named values.
class SingleName
Label of a named value containing a single name.
class IdentifierLine
Somewhat generic class for storing an identifier and its position.
class NameRow
A row of identifiers.
class NameTable
A 2D table of identifiers.
class Group
Base class of the value part of a named value.
class NodeGroup
Value part consisting of a node.
class ExpressionGroup
Value part of a group consisting of an expression.
class BaseNamedValue
Base class for named values.
class NamedValue
A value with a name.
class ImportValue
Node to import another file.
class NamedValueList
Sequence of named values.
Functions
std::shared_ptr< NamedValueList > LoadFile (const char *filename, int line=0)
Load a file, and parse the contents.
Detailed Description
AST data structures.
Definition in file ast.h.
Function Documentation
std::shared_ptr<NamedValueList> LoadFile (const char * filename, int line)
Load a file, and parse the contents.
Parameters
filename Name of the file to load. nullptr means to read stdin.
line Line number of the current file.
Returns
The parsed node tree.
Definition at line 529 of file ast.cpp.
References _parsed_data, filename, lengthof, line, SetupScanner(), and yyparse().
Referenced by NamedValueList::HandleImports(), and main().