FreeRCT: ast.cpp File Reference
ast.cpp File Reference
AST data structure implementation.
#include "../stdafx.h"
#include "ast.h"
#include "scanner_funcs.h"
#include "utils.h"
Functions
std::shared_ptr< NamedValueList > LoadFile (const char *filename, int line)
Load a file, and parse the contents.
Variables
static const Position _dummy_position ("",-1)
Dummy position.
Detailed Description
AST data structure implementation.
Definition in file ast.cpp.
Function Documentation
std::shared_ptr<NamedValueList> LoadFile (const char * filename, int line)
Load a file, and parse the contents.
Parameters
filename Name of the file to load. nullptr means to read stdin.
line Line number of the current file.
Returns
The parsed node tree.
Definition at line 529 of file ast.cpp.
References _parsed_data, filename, lengthof, line, SetupScanner(), and yyparse().
Referenced by NamedValueList::HandleImports(), and main().