FreeRCT: bitmath.h File Reference
bitmath.h File Reference
Bit math functions.
Functions
template<typename T >
static uint GB (const T x, const uint8 s, const uint8 n)
Fetch n bits from x, started at bit s.
template<typename T , typename U >
static T SB (T &x, const uint8 s, const uint8 n, const U d)
Set n bits in x starting at bit s to d.
template<typename T >
static T ROL (const T x, const uint8 n)
ROtate x Left by n bits.
template<typename T >
static T ROL (const T x, const uint8 sz, const uint8 n)
ROtate the sz lower bits of x Left by n bits.
template<typename T >
static T ROR (const T x, const uint8 n)
ROtate x Right by n bits.
Detailed Description
Bit math functions.
Definition in file bitmath.h.
Function Documentation
template<typename T > static uint GB (const T x, const uint8 s, const uint8 n) inline static
Fetch n bits from x, started at bit s.
This function can be used to fetch n bits from the value x. The s value set the start position to read. The start position is count from the LSB and starts at 0. The result starts at a LSB, as this isn't just an and-bitmask but also some bit-shifting operations. GB(0xFF, 2, 1) will so return 0x01 (0000 0001) instead of 0x04 (0000 0100).
Parameters
x The value to read some bits.
s The start position to read some bits.
n The number of bits to read.
Returns
The selected bits, aligned to a LSB.
Definition at line 34 of file bitmath.h.
Referenced by RecolourEntry::AssignDest(), Recolouring::AssignRandomColours(), VideoSystem::BlitImages(), RideInstance::CanBeVisited(), SpriteCollector::CollectVoxel(), Guest::DecideMoveDirection(), RecolourDropdownWindow::DrawWidget(), TrackPiece::GetBanking(), TrackPiece::GetBend(), GetDesiredEdgeIndex(), Guest::GetExitDirections(), Voxel::GetFenceType(), Voxel::GetFoundationSlope(), Voxel::GetFoundationType(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), Voxel::GetGrowth(), GetImplodedPathSlope(), GetPathType(), ImageData::GetPixel(), TrackVoxel::GetPlatformDirection(), TrackPiece::GetSlope(), TrackPiece::GetStartDirection(), TrackVoxel::HasPlatform(), TrackPiece::IsStartingPiece(), Person::OnAnimate(), RecolourDropdownWindow::OnClick(), RideInstance::OpenRide(), and RecolourDropdownWindow::RecolourDropdownWindow().
template<typename T , typename U > static T SB (T & x, const uint8 s, const uint8 n, const U d) inline static
Set n bits in x starting at bit s to d.
This function sets n bits from x which started as bit s to the value of d. The parameters x, s and n works the same as the parameters of GB. The result is saved in x again. Unused bits in the window provided by n are set to 0 if the value of d isn't "big" enough. This is not a bug, its a feature.
Note
Parameter x must be a variable as the result is saved there.
To avoid unexpected results the value of d should not use more space as the provided space of n bits (log2)
Parameters
x The variable to change some bits
s The start position for the new bits
n The size/window for the new bits
d The actually new bits to save in the defined position.
Returns
The new value of x
Definition at line 58 of file bitmath.h.
Referenced by Guest::DecideMoveDirection(), Guest::GetExitDirections(), RideInstance::OnNewMonth(), RideInstance::OpenRide(), Voxel::SetFenceType(), Voxel::SetFoundationSlope(), Voxel::SetFoundationType(), Voxel::SetGroundSlope(), Voxel::SetGroundType(), Voxel::SetGrowth(), and SetImplodedPathSlope().
template<typename T > static T ROL (const T x, const uint8 n) inline static
ROtate x Left by n bits.
Note
Assumes a byte has 8 bits.
Template Parameters
T Type of x (deduced from the first argument).
Parameters
x The value which we want to rotate.
n The number how many we want to rotate.
Returns
The rotated number.
Definition at line 75 of file bitmath.h.
Referenced by ShopInstance::GetEntranceDirections().
template<typename T > static T ROL (const T x, const uint8 sz, const uint8 n) inline static
ROtate the sz lower bits of x Left by n bits.
Template Parameters
T Type of x (deduced from the first argument).
Parameters
x The value which we want to rotate.
sz Number of (low-end) bits containing the value to rotate.
n Number of bits to rotate (should be less than sz).
Returns
The rotated number.
Definition at line 90 of file bitmath.h.
template<typename T > static T ROR (const T x, const uint8 n) inline static
ROtate x Right by n bits.
Note
Assumes a byte has 8 bits.
Template Parameters
T Type of x (deduced from the first argument).
Parameters
x The value which we want to rotate.
n The number how many we want to rotate.
Returns
The rotated number.
Definition at line 111 of file bitmath.h.