FreeRCT: check_data.cpp File Reference
check_data.cpp File Reference
Check and simplify functions.
#include "../stdafx.h"
#include <map>
#include <vector>
#include <memory>
#include <string>
#include <ctime>
#include "ast.h"
#include "nodes.h"
#include "string_storage.h"
#include "string_names.h"
#include "utils.h"
Classes
class ValueInformation
All information that needs to be stored about a named value.
class Values
Class for storing found named values.
Functions
static std::shared_ptr< BlockNode > ConvertNodeGroup (std::shared_ptr< NodeGroup > ng)
Convert a node group.
static void ExpandExpressions (std::shared_ptr< ExpressionList > exprs, std::shared_ptr< Expression > out[], size_t expected, const Position &pos, const char *node)
Check the number of expressions given in exprs, and expand them into the out array for easier access.
static void ExpandNoExpression (std::shared_ptr< ExpressionList > exprs, const Position &pos, const char *node)
Check that there are no expressions provided in exprs.
static std::string GetString (std::shared_ptr< Expression > expr, int index, const char *node)
Extract a string from the given expression.
static std::shared_ptr< FileNode > ConvertFileNode (std::shared_ptr< NodeGroup > ng)
Convert a 'file' node (taking a string parameter for the filename, and a sequence of game blocks).
static void AssignNames (std::shared_ptr< BlockNode > bn, std::shared_ptr< NameTable > nt, std::vector< std::shared_ptr< ValueInformation >> &vis, int *length)
Assign sub-nodes to the names of a 2D table.
static std::shared_ptr< TSELBlock > ConvertTSELNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a TSEL game block.
static std::shared_ptr< SURFBlock > ConvertSURFNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a SURF game block.
static std::shared_ptr< FUNDBlock > ConvertFUNDNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a FUND game block.
static std::shared_ptr< PATHBlock > ConvertPATHNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a PATH game block.
static std::shared_ptr
< SpriteBlock > GetPDECSprite (const char *prefix, int dir, Values &vals)
Get a sprite of the PDEC block.
static void GetPDECPathSprites (std::shared_ptr< SpriteBlock > *dest, const char *name, Values &vals)
Look for sprites with the provided name, put at most 4 of them in the destination array.
static std::shared_ptr< PDECBlock > ConvertPDECNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a PDEC game block.
static std::shared_ptr< PLATBlock > ConvertPLATNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a PLAT game block.
static std::shared_ptr< SUPPBlock > ConvertSUPPNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a PLAT game block.
static std::shared_ptr< TCORBlock > ConvertTCORNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a TCOR game block.
static std::shared_ptr< PRSGBlock > ConvertPRSGNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a PRSG game block.
static std::shared_ptr< ANIMBlock > ConvertANIMNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to an ANIM game block.
static std::shared_ptr< ANSPBlock > ConvertANSPNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to an ANSP game block.
static std::shared_ptr< GBORBlock > ConvertGBORNode (std::shared_ptr< NodeGroup > ng)
Convert a GBOR game block.
static std::shared_ptr< GCHKBlock > ConvertGCHKNode (std::shared_ptr< NodeGroup > ng)
Convert a GCHK game block.
static std::shared_ptr< GSLIBlock > ConvertGSLINode (std::shared_ptr< NodeGroup > ng)
Convert a GSLI game block.
static std::shared_ptr< GSCLBlock > ConvertGSCLNode (std::shared_ptr< NodeGroup > ng)
Convert a GSCL game block.
static std::shared_ptr
< SheetBlock > ConvertSheetNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a sprite-sheet block.
static std::shared_ptr
< SpriteFilesBlock > ConvertSpriteFilesNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a 'spritefiles' node.
static std::shared_ptr
< SpriteBlock > ConvertSpriteNode (std::shared_ptr< NodeGroup > ng)
Convert a 'sprite' node.
static std::shared_ptr< BitMask > ConvertBitMaskNode (std::shared_ptr< NodeGroup > ng)
Convert a 'bitmask' node.
static std::shared_ptr
< PersonGraphics > ConvertPersonGraphicsNode (std::shared_ptr< NodeGroup > ng)
Convert a 'person_graphics' node.
static std::shared_ptr
< Recolouring > ConvertRecolourNode (std::shared_ptr< NodeGroup > ng)
Convert a 'recolour' node.
static std::shared_ptr< FrameData > ConvertFrameDataNode (std::shared_ptr< NodeGroup > ng)
Convert a 'frame_data' node.
static std::shared_ptr< BDIRBlock > ConvertBDIRNode (std::shared_ptr< NodeGroup > ng)
Convert a 'BDIR' game node.
static std::shared_ptr< SHOPBlock > ConvertSHOPNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a SHOP game block.
static void LoadNamedSprites (const char *names[], size_t count, Values &vals, std::shared_ptr< SpriteBlock > *dest)
Load a set of sprites by name.
static std::shared_ptr< GSLPBlock > ConvertGSLPNode (std::shared_ptr< NodeGroup > ng)
Convert a node group to a GSLP game block.
static std::shared_ptr
< StringsNode > ConvertStringsNode (std::shared_ptr< NodeGroup > ng)
Convert a 'strings' node.
static std::shared_ptr
< StringNode > ConvertStringNode (std::shared_ptr< NodeGroup > ng)
Convert a 'string' node.
static std::shared_ptr
< StringsNode > ConvertStringTextsNode (std::shared_ptr< NodeGroup > ng)
Convert the compact 'text: "...";' notation for string into a StringsNode.
static std::shared_ptr
< TrackVoxel > ConvertTrackVoxel (std::shared_ptr< NodeGroup > ng)
Convert a 'track_voxel' node.
static std::shared_ptr
< Connection > ConvertConnection (std::shared_ptr< NodeGroup > ng)
Convert a 'connection' node.
static std::shared_ptr
< TrackPieceNode > ConvertTrackPieceNode (std::shared_ptr< NodeGroup > ng)
Convert a 'track_piece' game node.
static std::shared_ptr< RCSTBlock > ConvertRCSTNode (std::shared_ptr< NodeGroup > ng)
Convert a 'RCST' node to a game block.
static std::shared_ptr< CARSBlock > ConvertCARSNode (std::shared_ptr< NodeGroup > ng)
Convert a 'CARS' node to a game block.
static std::shared_ptr< BlockNode > ConvertSplinesNode (std::shared_ptr< NodeGroup > ng)
Convert a 'splines' block to a node block.
static std::shared_ptr< BlockNode > ConvertCubicNode (std::shared_ptr< NodeGroup > ng)
Convert a 'cubic' node to a block node.
static std::shared_ptr< CSPLBlock > ConvertCSPLNode (std::shared_ptr< NodeGroup > ng)
Convert a 'CSPL' node to a game block.
static std::shared_ptr< FENCBlock > ConvertFENCNode (std::shared_ptr< NodeGroup > ng)
Convert a 'FENC' block.
static std::shared_ptr< INFOBlock > ConvertINFONode (std::shared_ptr< NodeGroup > ng)
Convert a 'INFO' block.
FileNodeList * CheckTree (std::shared_ptr< NamedValueList > values)
Check and convert the tree to nodes.
void GenerateStringsHeaderFile (const char *prefix, const char *base, const char *header)
Generate a header file with string names.
void GenerateStringsCodeFile (const char *prefix, const char *code)
Generate a code file with string names.
Variables
static const char * _surface_sprite []
Names of surface sprites in a single direction of view.
static const Symbol _surface_types []
Available types of surface.
static const char * _foundation_sprite []
Names of the foundation sprites.
static const Symbol _fund_symbols []
Numeric symbols of the foundation types.
static const Symbol _path_symbols []
Symbols for the PATH game block.
static const char * _path_sprites []
Names of the PATH sprites.
static const Symbol _platform_symbols []
Symbols for the platform game block.
static const char * _platform_sprites []
Sprite names of the platform game block.
static const Symbol _support_symbols []
Symbols for the support game block.
static const char * _support_sprites []
Sprite names of the support game block.
static const Symbol _anim_symbols []
Symbols for an ANIM and ANSP blocks.
static const Symbol _gbor_symbols []
Symbols of the GBOR block.
static const Symbol _gchk_symbols []
Symbols of the GCHK block.
static const Symbol _person_graphics_symbols []
Names of person types and colour ranges.
static const Symbol _recolour_symbols []
Colour ranges for the recolour node.
static const Symbol _shop_symbols []
Symbols of the shop game block.
static const char * compass_names []
Names of compass sprites.
static const char * weather_names []
Names of weather sprites.
static const char * light_rog_names []
Names of red/orange/green light sprites.
static const char * light_rg_names []
Names of red/green light sprites.
static const Symbol _track_voxel_symbols []
Symbols of a 'track_voxel' node.
static const Symbol _connection_symbols []
Direction symbols of the connection node.
static const Symbol _track_piece_symbols []
Available symbols for the track_piece node.
static const Symbol _coaster_platform_symbols []
Platform coaster type symbols.
static const Symbol _fence_symbols []
Fence symbols.
Detailed Description
Check and simplify functions.
Definition in file check_data.cpp.
Function Documentation
static std::shared_ptr< BlockNode > ConvertNodeGroup (std::shared_ptr< NodeGroup > ng) static
Convert a node group.
Parameters
ng Node group to convert.
Returns
The converted node.
Definition at line 2431 of file check_data.cpp.
References ConvertANIMNode(), ConvertANSPNode(), ConvertBDIRNode(), ConvertBitMaskNode(), ConvertCARSNode(), ConvertConnection(), ConvertCSPLNode(), ConvertCubicNode(), ConvertFENCNode(), ConvertFileNode(), ConvertFrameDataNode(), ConvertFUNDNode(), ConvertGBORNode(), ConvertGCHKNode(), ConvertGSCLNode(), ConvertGSLINode(), ConvertGSLPNode(), ConvertINFONode(), ConvertPATHNode(), ConvertPDECNode(), ConvertPersonGraphicsNode(), ConvertPLATNode(), ConvertPRSGNode(), ConvertRCSTNode(), ConvertRecolourNode(), ConvertSheetNode(), ConvertSHOPNode(), ConvertSplinesNode(), ConvertSpriteFilesNode(), ConvertSpriteNode(), ConvertStringNode(), ConvertStringsNode(), ConvertStringTextsNode(), ConvertSUPPNode(), ConvertSURFNode(), ConvertTCORNode(), ConvertTrackPieceNode(), ConvertTrackVoxel(), and ConvertTSELNode().
Referenced by ConvertFileNode(), and Values::PrepareNamedValues().
static void ExpandExpressions (std::shared_ptr< ExpressionList > exprs, std::shared_ptr< Expression > out[], size_t expected, const Position & pos, const char * node) static
Check the number of expressions given in exprs, and expand them into the out array for easier access.
Parameters
exprs Expression list containing parameters.
out [out] Output array for storing expected expressions from the list.
expected Expected number of expressions in exprs.
pos Position of the node (for reporting errors).
node Name of the node being checked and expanded.
Definition at line 34 of file check_data.cpp.
References Position::ToString().
Referenced by ConvertFileNode(), and ConvertStringTextsNode().
static void ExpandNoExpression (std::shared_ptr< ExpressionList > exprs, const Position & pos, const char * node) static
Check that there are no expressions provided in exprs.
Give an error otherwise.
Parameters
exprs Expression list containing parameters.
pos Position of the node (for reporting errors).
node Name of the node being checked and expanded.
Definition at line 55 of file check_data.cpp.
References Position::ToString().
Referenced by ConvertANIMNode(), ConvertANSPNode(), ConvertBDIRNode(), ConvertBitMaskNode(), ConvertCARSNode(), ConvertConnection(), ConvertCSPLNode(), ConvertCubicNode(), ConvertFENCNode(), ConvertFrameDataNode(), ConvertFUNDNode(), ConvertGBORNode(), ConvertGCHKNode(), ConvertGSCLNode(), ConvertGSLINode(), ConvertGSLPNode(), ConvertINFONode(), ConvertPATHNode(), ConvertPDECNode(), ConvertPersonGraphicsNode(), ConvertPLATNode(), ConvertPRSGNode(), ConvertRCSTNode(), ConvertRecolourNode(), ConvertSheetNode(), ConvertSHOPNode(), ConvertSplinesNode(), ConvertSpriteFilesNode(), ConvertSpriteNode(), ConvertStringNode(), ConvertStringsNode(), ConvertSUPPNode(), ConvertSURFNode(), ConvertTCORNode(), ConvertTrackPieceNode(), ConvertTrackVoxel(), and ConvertTSELNode().
static std::string GetString (std::shared_ptr< Expression > expr, int index, const char * node) static
Extract a string from the given expression.
Parameters
expr Expression to evaluate.
index Parameter number (0-based, for error reporting).
node Name of the node.
Returns
Value of the string (caller should release the memory after use).
Definition at line 70 of file check_data.cpp.
References StringLiteral::text.
Referenced by ConvertFileNode(), and ConvertStringTextsNode().
static std::shared_ptr<FileNode> ConvertFileNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'file' node (taking a string parameter for the filename, and a sequence of game blocks).
Parameters
ng Generic tree of nodes to convert to a 'file' node.
Returns
The converted file node.
Definition at line 116 of file check_data.cpp.
References ConvertNodeGroup(), ExpandExpressions(), filename, and GetString().
Referenced by ConvertNodeGroup().
static void AssignNames (std::shared_ptr< BlockNode > bn, std::shared_ptr< NameTable > nt, std::vector< std::shared_ptr< ValueInformation >> & vis, int * length) static
Assign sub-nodes to the names of a 2D table.
Parameters
bn Node to split in sub-nodes.
nt 2D name table.
vis Array being filled.
length [inout] Updated number of used entries in vis.
Definition at line 331 of file check_data.cpp.
References CheckIsSingleName(), ParameterizedName::DecodeName(), ParameterizedName::GetParmName(), ParameterizedName::hor_range, HV_NONE, ParameterizedNameRange::size(), ParameterizedNameRange::used, and ParameterizedName::vert_range.
Referenced by Values::PrepareNamedValues().
static std::shared_ptr<TSELBlock> ConvertTSELNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a TSEL game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created TSEL game block.
Definition at line 693 of file check_data.cpp.
References _surface_sprite, ExpandNoExpression(), and SURFACE_COUNT.
Referenced by ConvertNodeGroup().
static std::shared_ptr<SURFBlock> ConvertSURFNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a SURF game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created SURF game block.
Definition at line 735 of file check_data.cpp.
References _surface_sprite, ExpandNoExpression(), and SURFACE_COUNT.
Referenced by ConvertNodeGroup().
static std::shared_ptr<FUNDBlock> ConvertFUNDNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a FUND game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created FUND game block.
Definition at line 782 of file check_data.cpp.
References _foundation_sprite, ExpandNoExpression(), and FOUNDATION_COUNT.
Referenced by ConvertNodeGroup().
static std::shared_ptr<PATHBlock> ConvertPATHNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a PATH game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created PATH game block.
Definition at line 872 of file check_data.cpp.
References _path_sprites, ExpandNoExpression(), and PTS_COUNT.
Referenced by ConvertNodeGroup().
static std::shared_ptr<SpriteBlock> GetPDECSprite (const char * prefix, int dir, Values & vals) static
Get a sprite of the PDEC block.
Parameters
prefix Prefix of the name.
dir Requested direction.
vals Node values with the sprites.
Returns
The requested sprite.
Definition at line 899 of file check_data.cpp.
References Values::GetSprite(), and text.
Referenced by ConvertPDECNode().
static void GetPDECPathSprites (std::shared_ptr< SpriteBlock > * dest, const char * name, Values & vals) static
Look for sprites with the provided name, put at most 4 of them in the destination array.
Parameters
dest Pointer to the destination array (size 4).
name Name of the field to look for.
vals Node values with the sprites.
Definition at line 920 of file check_data.cpp.
References Values::named_count, and Values::named_values.
Referenced by ConvertPDECNode().
static std::shared_ptr<PDECBlock> ConvertPDECNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a PDEC game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created PDEC game block.
Definition at line 940 of file check_data.cpp.
References ExpandNoExpression(), GetPDECPathSprites(), and GetPDECSprite().
Referenced by ConvertNodeGroup().
static std::shared_ptr<PLATBlock> ConvertPLATNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a PLAT game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created PLAT game block.
Definition at line 1004 of file check_data.cpp.
References _platform_sprites, ExpandNoExpression(), and PLA_COUNT.
Referenced by ConvertNodeGroup().
static std::shared_ptr<SUPPBlock> ConvertSUPPNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a PLAT game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created PLAT game block.
Definition at line 1063 of file check_data.cpp.
References _support_sprites, ExpandNoExpression(), and SPP_COUNT.
Referenced by ConvertNodeGroup().
static std::shared_ptr<TCORBlock> ConvertTCORNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a TCOR game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created TCOR game block.
Definition at line 1088 of file check_data.cpp.
References _surface_sprite, ExpandNoExpression(), and SURFACE_COUNT.
Referenced by ConvertNodeGroup().
static std::shared_ptr<PRSGBlock> ConvertPRSGNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a PRSG game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created PRSG game block.
Definition at line 1127 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<ANIMBlock> ConvertANIMNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to an ANIM game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created ANIM game block.
Definition at line 1175 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<ANSPBlock> ConvertANSPNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to an ANSP game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created ANSP game block.
Definition at line 1212 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<GBORBlock> ConvertGBORNode (std::shared_ptr< NodeGroup > ng) static
Convert a GBOR game block.
Parameters
ng Node group to convert.
Returns
The created game block.
Definition at line 1264 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<GCHKBlock> ConvertGCHKNode (std::shared_ptr< NodeGroup > ng) static
Convert a GCHK game block.
Parameters
ng Node group to convert.
Returns
The created game block.
Definition at line 1307 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<GSLIBlock> ConvertGSLINode (std::shared_ptr< NodeGroup > ng) static
Convert a GSLI game block.
Parameters
ng Node group to convert.
Returns
The created game block.
Definition at line 1332 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<GSCLBlock> ConvertGSCLNode (std::shared_ptr< NodeGroup > ng) static
Convert a GSCL game block.
Parameters
ng Node group to convert.
Returns
The created game block.
Definition at line 1358 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<SheetBlock> ConvertSheetNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a sprite-sheet block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created sprite-sheet node.
Definition at line 1394 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<SpriteFilesBlock> ConvertSpriteFilesNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a 'spritefiles' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The created sprite-files node.
Definition at line 1443 of file check_data.cpp.
References ExpandNoExpression(), and Values::PrepareNamedValues().
Referenced by ConvertNodeGroup().
static std::shared_ptr<SpriteBlock> ConvertSpriteNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'sprite' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted sprite block.
Definition at line 1493 of file check_data.cpp.
References ExpandNoExpression(), ImageFile::Is8bpp(), ImageFile::LoadFile(), and Image32bpp::SetRecolourImage().
Referenced by ConvertNodeGroup().
static std::shared_ptr<BitMask> ConvertBitMaskNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'bitmask' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted bit mask node.
Definition at line 1573 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<PersonGraphics> ConvertPersonGraphicsNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'person_graphics' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted sprite block.
Definition at line 1645 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<Recolouring> ConvertRecolourNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'recolour' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted sprite block.
Definition at line 1679 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<FrameData> ConvertFrameDataNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'frame_data' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted sprite block.
Definition at line 1699 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<BDIRBlock> ConvertBDIRNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'BDIR' game node.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted BDIR game block.
Definition at line 1720 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<SHOPBlock> ConvertSHOPNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a SHOP game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created SHOP game block.
Definition at line 1763 of file check_data.cpp.
References _shops_string_names, ExpandNoExpression(), and lengthof.
Referenced by ConvertNodeGroup().
static void LoadNamedSprites (const char * names[], size_t count, Values & vals, std::shared_ptr< SpriteBlock > * dest) static
Load a set of sprites by name.
Parameters
names Array of names of the sprites.
count Number of expected sprites.
vals Value structures expected to contain the sprites.
dest Destination array to srite to.
Definition at line 1817 of file check_data.cpp.
References Values::GetSprite().
Referenced by ConvertGSLPNode().
static std::shared_ptr<GSLPBlock> ConvertGSLPNode (std::shared_ptr< NodeGroup > ng) static
Convert a node group to a GSLP game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The created GSLP game block.
Definition at line 1848 of file check_data.cpp.
References _gui_string_names, compass_names, ExpandNoExpression(), lengthof, light_rg_names, light_rog_names, LoadNamedSprites(), and weather_names.
Referenced by ConvertNodeGroup().
static std::shared_ptr<StringsNode> ConvertStringsNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'strings' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The created 'strings' node.
Definition at line 1916 of file check_data.cpp.
References StringsNode::Add(), ExpandNoExpression(), and GetLanguageIndex().
Referenced by ConvertNodeGroup().
static std::shared_ptr<StringNode> ConvertStringNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'string' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The created 'string' node.
Definition at line 2001 of file check_data.cpp.
References ExpandNoExpression(), and GetLanguageIndex().
Referenced by ConvertNodeGroup().
static std::shared_ptr<StringsNode> ConvertStringTextsNode (std::shared_ptr< NodeGroup > ng) static
Convert the compact 'text: "...";' notation for string into a StringsNode.
Parameters
ng Generic tree of nodes to convert.
Returns
The created 'strings' node.
Definition at line 2028 of file check_data.cpp.
References ExpandExpressions(), and GetString().
Referenced by ConvertNodeGroup().
static std::shared_ptr<TrackVoxel> ConvertTrackVoxel (std::shared_ptr< NodeGroup > ng) static
Convert a 'track_voxel' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The created 'track_voxel' node.
Definition at line 2074 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<Connection> ConvertConnection (std::shared_ptr< NodeGroup > ng) static
Convert a 'connection' node.
Parameters
ng Generic tree of nodes to convert.
Returns
The created 'connection' node.
Definition at line 2119 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<TrackPieceNode> ConvertTrackPieceNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'track_piece' game node.
Parameters
ng Generic tree of nodes to convert.
Returns
The created 'track_piece' node.
Definition at line 2147 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<RCSTBlock> ConvertRCSTNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'RCST' node to a game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted RCST game block.
Definition at line 2200 of file check_data.cpp.
References _coaster_string_names, ExpandNoExpression(), and lengthof.
Referenced by ConvertNodeGroup().
static std::shared_ptr<CARSBlock> ConvertCARSNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'CARS' node to a game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted CARS game block.
Definition at line 2238 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<BlockNode> ConvertSplinesNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'splines' block to a node block.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted splines node block.
Definition at line 2272 of file check_data.cpp.
References ExpandNoExpression(), and Values::PrepareNamedValues().
Referenced by ConvertNodeGroup().
static std::shared_ptr<BlockNode> ConvertCubicNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'cubic' node to a block node.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted cubic spline block.
Definition at line 2301 of file check_data.cpp.
References ExpandNoExpression(), and Values::PrepareNamedValues().
Referenced by ConvertNodeGroup().
static std::shared_ptr<CSPLBlock> ConvertCSPLNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'CSPL' node to a game block.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted CSPL game block.
Definition at line 2333 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<FENCBlock> ConvertFENCNode (std::shared_ptr< NodeGroup > ng) static
Convert a 'FENC' block.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted FENC game block.
Definition at line 2369 of file check_data.cpp.
References ExpandNoExpression().
Referenced by ConvertNodeGroup().
static std::shared_ptr<INFOBlock> ConvertINFONode (std::shared_ptr< NodeGroup > ng) static
Convert a 'INFO' block.
Parameters
ng Generic tree of nodes to convert.
Returns
The converted INFO eta block.
Definition at line 2400 of file check_data.cpp.
References ExpandNoExpression(), and lengthof.
Referenced by ConvertNodeGroup().
FileNodeList* CheckTree (std::shared_ptr< NamedValueList > values)
Check and convert the tree to nodes.
Parameters
values Root node of the tree.
Returns
The converted and checked sequence of file data to write.
Definition at line 2485 of file check_data.cpp.
References _foundation_sprite, _strings_storage, _surface_sprite, StringsStorage::AddStrings(), FileNodeList::files, FOUNDATION_COUNT, Values::PrepareNamedValues(), SURFACE_COUNT, Values::unnamed_count, Values::unnamed_values, and Values::VerifyUsage().
Referenced by main().
void GenerateStringsHeaderFile (const char * prefix, const char * base, const char * header)
Generate a header file with string names.
Parameters
prefix Kind of strings (either "GUI" or "SHOPS").
base Value of the first entry.
header Name of the output header file.
Definition at line 2523 of file check_data.cpp.
References _coaster_string_names, _gui_string_names, _shops_string_names, and lengthof.
Referenced by main().
void GenerateStringsCodeFile (const char * prefix, const char * code)
Generate a code file with string names.
Parameters
prefix Kind of strings (either "GUI" or "SHOPS").
code Name of the output code file.
Definition at line 2579 of file check_data.cpp.
References _coaster_string_names, _gui_string_names, _shops_string_names, and lengthof.
Referenced by main().
Variable Documentation
const char* _surface_sprite[] static
Initial value:
= {
        "#",
        "#n",
        "#e",
        "#ne",
        "#s",
        "#ns",
        "#es",
        "#nes",
        "#w",
        "#nw",
        "#ew",
        "#new",
        "#sw",
        "#nsw",
        "#esw",
        "#Nb",
        "#Eb",
        "#Sb",
        "#Wb",
        "#Nt",
        "#Et",
        "#St",
        "#Wt",
}
Names of surface sprites in a single direction of view.
Definition at line 662 of file check_data.cpp.
Referenced by CheckTree(), ConvertSURFNode(), ConvertTCORNode(), and ConvertTSELNode().
const Symbol _surface_types[] static
Initial value:
= {
        {"reserved",          0},
        {"the_green",        16},
        {"short_grass",      17},
        {"medium_grass",     18},
        {"long_grass",       19},
        {"semi_transparent", 20},
        {"sand",             32},
        {"cursor",           48},
        {"cursor_edge",      49},
        {nullptr, 0},
}
Available types of surface.
Definition at line 717 of file check_data.cpp.
const char* _foundation_sprite[] static
Initial value:
= {
        "se_e0",
        "se_0s",
        "se_es",
        "sw_s0",
        "sw_0w",
        "sw_sw",
}
Names of the foundation sprites.
Definition at line 759 of file check_data.cpp.
Referenced by CheckTree(), and ConvertFUNDNode().
const Symbol _fund_symbols[] static
Initial value:
= {
        {"reserved",  0},
        {"ground",   16},
        {"wood",     32},
        {"brick",    48},
        {nullptr, 0}
}
Numeric symbols of the foundation types.
Definition at line 769 of file check_data.cpp.
const Symbol _path_symbols[] static
Initial value:
= {
        {"wood", 4},
        {"tiled", 8},
        {"asphalt", 12},
        {"concrete", 16},
        {"queue", 0x8000},
        {nullptr, 0},
}
Symbols for the PATH game block.
Definition at line 803 of file check_data.cpp.
const char* _path_sprites[] static
Names of the PATH sprites.
Definition at line 813 of file check_data.cpp.
Referenced by ConvertPATHNode().
const Symbol _platform_symbols[] static
Initial value:
= {
        {"wood", 16},
        {nullptr, 0},
}
Symbols for the platform game block.
Definition at line 976 of file check_data.cpp.
const char* _platform_sprites[] static
Initial value:
= {
        "ns",
        "ew",
        "ramp_ne",
        "ramp_se",
        "ramp_sw",
        "ramp_nw",
        "right_ramp_ne",
        "right_ramp_se",
        "right_ramp_sw",
        "right_ramp_nw",
        "left_ramp_ne",
        "left_ramp_se",
        "left_ramp_sw",
        "left_ramp_nw",
}
Sprite names of the platform game block.
Definition at line 982 of file check_data.cpp.
Referenced by ConvertPLATNode().
const Symbol _support_symbols[] static
Initial value:
= {
        {"wood", 16},
        {nullptr, 0},
}
Symbols for the support game block.
Definition at line 1025 of file check_data.cpp.
const char* _support_sprites[] static
Initial value:
= {
        "s_ns",
        "s_ew",
        "d_ns",
        "d_ew",
        "p_ns",
        "p_ew",
        "n#n",
        "n#e",
        "n#ne",
        "n#s",
        "n#ns",
        "n#es",
        "n#nes",
        "n#w",
        "n#nw",
        "n#ew",
        "n#new",
        "n#sw",
        "n#nsw",
        "n#esw",
        "n#N",
        "n#E",
        "n#S",
        "n#W",
}
Sprite names of the support game block.
Definition at line 1031 of file check_data.cpp.
Referenced by ConvertSUPPNode().
const Symbol _anim_symbols[] static
Initial value:
= {
        {"guest",        8},
        {"handyman",    17},
        {"mechanic",    18},
        {"guard",       19},
        {"entertainer", 20},
        {"walk_ne",      1},
        {"walk_se",      2},
        {"walk_sw",      3},
        {"walk_nw",      4},
        {nullptr, 0}
}
Symbols for an ANIM and ANSP blocks.
Definition at line 1157 of file check_data.cpp.
const Symbol _gbor_symbols[] static
Initial value:
= {
        {"left_tabbar", 1},
        {"pressed_tab_tabbar", 2},
        {"tab_tabbar", 3},
        {"right_tabbar", 4},
        {"tabbar_panel", 5},
        {"titlebar", 6},
        {"button", 7},
        {"pressed_button", 8},
        {"panel", 9},
        {nullptr, 0}
}
Symbols of the GBOR block.
Definition at line 1246 of file check_data.cpp.
const Symbol _gchk_symbols[] static
Initial value:
= {
        {"check_box", 96},
        {"radio_button", 112},
        {nullptr, 0}
}
Symbols of the GCHK block.
Definition at line 1296 of file check_data.cpp.
const Symbol _person_graphics_symbols[] static
Initial value:
= {
        {"guest",        8},
        {"handyman",    17},
        {"mechanic",    18},
        {"guard",       19},
        {"entertainer", 20},
        {"grey",         COL_GREY},
        {"green_brown",  COL_GREEN_BROWN},
        {"orange_brown", COL_ORANGE_BROWN},
        {"yellow",       COL_YELLOW},
        {"dark_red",     COL_DARK_RED},
        {"dark_green",   COL_DARK_GREEN},
        {"light_green",  COL_LIGHT_GREEN},
        {"green",        COL_GREEN},
        {"pink_brown",   COL_PINK_BROWN},
        {"dark_purple",  COL_DARK_PURPLE},
        {"blue",         COL_BLUE},
        {"jade_green",   COL_DARK_JADE_GREEN},
        {"purple",       COL_PURPLE},
        {"red",          COL_RED},
        {"orange",       COL_ORANGE},
        {"sea_green",    COL_SEA_GREEN},
        {"pink",         COL_PINK},
        {"brown",        COL_BROWN},
        {nullptr, 0}
}
Names of person types and colour ranges.
Definition at line 1590 of file check_data.cpp.
const Symbol _recolour_symbols[] static
Initial value:
= {
        {"grey",         COL_GREY},
        {"green_brown",  COL_GREEN_BROWN},
        {"orange_brown", COL_ORANGE_BROWN},
        {"yellow",       COL_YELLOW},
        {"dark_red",     COL_DARK_RED},
        {"dark_green",   COL_DARK_GREEN},
        {"light_green",  COL_LIGHT_GREEN},
        {"green",        COL_GREEN},
        {"pink_brown",   COL_PINK_BROWN},
        {"dark_purple",  COL_DARK_PURPLE},
        {"blue",         COL_BLUE},
        {"jade_green",   COL_DARK_JADE_GREEN},
        {"purple",       COL_PURPLE},
        {"red",          COL_RED},
        {"orange",       COL_ORANGE},
        {"sea_green",    COL_SEA_GREEN},
        {"pink",         COL_PINK},
        {"brown",        COL_BROWN},
        {nullptr, 0}
}
Colour ranges for the recolour node.
Definition at line 1618 of file check_data.cpp.
const Symbol _shop_symbols[] static
Initial value:
= {
        {"ne_entrance", 0},
        {"se_entrance", 1},
        {"sw_entrance", 2},
        {"nw_entrance", 3},
        {"drink", 8},
        {"ice_cream", 9},
        {"non_salt_food", 16},
        {"salt_food", 24},
        {"umbrella", 32},
        {"balloon", 33},
        {"map", 40},
        {"souvenir", 41},
        {"money", 48},
        {"toilet", 49},
        {"first_aid", 50},
        {nullptr, 0},
}
Symbols of the shop game block.
Definition at line 1739 of file check_data.cpp.
const char* compass_names[] static
Initial value:
= {
        "compass_n", "compass_e", "compass_s", "compass_w", nullptr
}
Names of compass sprites.
Definition at line 1827 of file check_data.cpp.
Referenced by ConvertGSLPNode().
const char* weather_names[] static
Initial value:
= {
        "sunny", "light_cloud", "thick_cloud", "rain", "thunder", nullptr
}
Names of weather sprites.
Definition at line 1831 of file check_data.cpp.
Referenced by ConvertGSLPNode().
const char* light_rog_names[] static
Initial value:
= {
        "light_rog_red", "light_rog_orange", "light_rog_green", "light_rog_none", nullptr
}
Names of red/orange/green light sprites.
Definition at line 1835 of file check_data.cpp.
Referenced by ConvertGSLPNode().
const char* light_rg_names[] static
Initial value:
= {
        "light_rg_red", "light_rg_green", "light_rg_none", nullptr
}
Names of red/green light sprites.
Definition at line 1839 of file check_data.cpp.
Referenced by ConvertGSLPNode().
const Symbol _track_voxel_symbols[] static
Initial value:
= {
        {"north", 0},
        {"east",  1},
        {"south", 2},
        {"west",  3},
        {"nesw",  1 << 4},
        {"senw",  2 << 4},
        {"swne",  3 << 4},
        {"nwse",  4 << 4},
        {nullptr, 0}
}
Symbols of a 'track_voxel' node.
Definition at line 2057 of file check_data.cpp.
const Symbol _connection_symbols[] static
Initial value:
= {
        {"ne", 0},
        {"se", 1},
        {"sw", 2},
        {"nw", 3},
        {nullptr, 0}
}
Direction symbols of the connection node.
Definition at line 2106 of file check_data.cpp.
const Symbol _track_piece_symbols[] static
Initial value:
= {
        {"none",  0},
        {"left",  1},
        {"right", 2},
        {nullptr, 0}
}
Available symbols for the track_piece node.
Definition at line 2135 of file check_data.cpp.
const Symbol _coaster_platform_symbols[] static
Initial value:
= {
        {"wood", 1},
        {nullptr, 0}
}
Platform coaster type symbols.
Definition at line 2323 of file check_data.cpp.
const Symbol _fence_symbols[] static
Initial value:
= {
        {"border",  0},
        {"wood",    1},
        {"conifer", 2},
        {"bricks",  3},
        {nullptr,   0}
}
Fence symbols.
Definition at line 2356 of file check_data.cpp.