FreeRCT: EdgeCursor Class Reference
EdgeCursor Class Reference
%Window code » %Viewport (main display) code and data
Single tile edge cursor.
#include <viewport.h>
Public Member Functions
EdgeCursor (Viewport *vp)
Constructor of an edge cursor.
bool SetCursor (const XYZPoint16 &cursor_pos, CursorType type, const ImageData *sprite, uint8 yoffset, bool always=false)
Set a cursor.
void MarkDirty () override
Update the cursor at the screen.
CursorType GetCursor (const XYZPoint16 &cursor_pos) override
Get a cursor.
uint8 GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos) override
Get the maximum height of the xpos, ypos stack that needs to be examined.
void SetInvalid ()
Mark the cursor as being invalid, and update the viewport if necessary.
Public Attributes
XYZPoint16 cursor_pos
Voxel position of the cursor.
const ImageData * sprite
Cursor sprite.
uint8 yoffset
Y offset for where to render the sprite on the screen.
Viewport * vp
Parent viewport object.
CursorType type
Type of cursor.
Detailed Description
Single tile edge cursor.
Definition at line 198 of file viewport.h.
Constructor & Destructor Documentation
EdgeCursor::EdgeCursor (Viewport * vp)
Constructor of an edge cursor.
Parameters
vp Viewport displaying the cursor.
Definition at line 663 of file viewport.cpp.
References cursor_pos.
Member Function Documentation
bool EdgeCursor::SetCursor (const XYZPoint16 & cursor_pos, CursorType type, const ImageData * sprite, uint8 yoffset, bool always = false)
Set a cursor.
Parameters
cursor_pos Position of the voxel containing the cursor.
type Type of cursor to set.
sprite Sprite to display.
yoffset Offset in screen y coordinates for where to render the sprite related to given voxel.
always Always set the cursor (else, only set it if it changed).
Returns
Cursor has been set/changed.
Definition at line 700 of file viewport.cpp.
References cursor_pos, MarkDirty(), sprite, BaseCursor::type, and yoffset.
Referenced by FenceBuildManager::SetCursors().
void EdgeCursor::MarkDirty () override virtual
Update the cursor at the screen.
Implements BaseCursor.
Definition at line 668 of file viewport.cpp.
References CUR_TYPE_INVALID, cursor_pos, Viewport::MarkVoxelDirty(), BaseCursor::type, and BaseCursor::vp.
Referenced by SetCursor().
CursorType EdgeCursor::GetCursor (const XYZPoint16 & cursor_pos) override virtual
Get a cursor.
Parameters
cursor_pos Expected coordinate of the cursor.
Returns
The cursor sprite if the cursor exists and the coordinates are correct, else nullptr.
Implements BaseCursor.
Definition at line 678 of file viewport.cpp.
References CUR_TYPE_INVALID, and BaseCursor::type.
Referenced by Viewport::GetCursorAtPos().
uint8 EdgeCursor::GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos) override virtual
Get the maximum height of the xpos, ypos stack that needs to be examined.
Parameters
xpos X position of the voxel.
ypos Y position of the voxel.
zpos Top of the stack found so far.
Returns
Highest voxel to draw for this cursor.
Implements BaseCursor.
Definition at line 684 of file viewport.cpp.
References CUR_TYPE_INVALID, cursor_pos, BaseCursor::type, XYZPoint< CT >::x, and XYZPoint< CT >::z.
Referenced by Viewport::GetMaxCursorHeight().
void BaseCursor::SetInvalid () inherited
Mark the cursor as being invalid, and update the viewport if necessary.
Definition at line 483 of file viewport.cpp.
References CUR_TYPE_INVALID, BaseCursor::MarkDirty(), and BaseCursor::type.
Referenced by FenceBuildManager::LeaveMode(), TileTerraformMouseMode::LeaveMode(), TileTerraformMouseMode::SetCursors(), and PathBuildManager::UpdateState().
The documentation for this class was generated from the following files:
viewport.h
viewport.cpp