FreeRCT: MultiCursor Class Reference
MultiCursor Class Reference
Cursor consisting of one or more tiles.
#include <viewport.h>
Public Member Functions
MultiCursor (Viewport *vp)
Constructor of a cursor.
bool SetCursor (const Rectangle32 &rect, CursorType type, bool always=false)
Set the area covered by the area cursor.
void MarkDirty () override
Update the cursor at the screen.
CursorType GetCursor (const XYZPoint16 &cursor_pos) override
Get a cursor.
uint8 GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos) override
Get the maximum height of the xpos, ypos stack that needs to be examined.
void ClearZPositions ()
Clear the z-positions cache.
uint8 GetZpos (int xpos, int ypos)
Get the Z position of a tile within the cursor.
void ResetZPosition (const Point32 &pos)
Reset the cached height of a voxel in the area.
void SetInvalid ()
Mark the cursor as being invalid, and update the viewport if necessary.
Public Attributes
Rectangle32 rect
Rectangle with cursors.
int16 zpos [10][10]
Cached Z positions of the cursors (negative means not set).
Viewport * vp
Parent viewport object.
CursorType type
Type of cursor.
Detailed Description
Cursor consisting of one or more tiles.
The cursor at every tile is a tile cursor (CUR_TYPE_TILE).
Definition at line 176 of file viewport.h.
Constructor & Destructor Documentation
MultiCursor::MultiCursor (Viewport * vp)
Constructor of a cursor.
Parameters
vp Viewport displaying the cursor.
Definition at line 542 of file viewport.cpp.
References ClearZPositions().
Member Function Documentation
bool MultiCursor::SetCursor (const Rectangle32 & rect, CursorType type, bool always = false)
Set the area covered by the area cursor.
Parameters
rect Rectangle denoting the size and position of the area cursor.
type CUR_TYPE_TILE for stating a new tile cursor, CUR_TYPE_INVALID for disabling the cursor.
always Always set the cursor (else, only set it if it changed).
Returns
Whether the function has set the cursor.
Note
The rect should be non-empty, and less than 10x10 tiles.
Definition at line 626 of file viewport.cpp.
References _world, ClearZPositions(), CUR_TYPE_INVALID, CUR_TYPE_TILE, VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), Rectangle< PT, SZ >::height, MarkDirty(), Rectangle< PT, SZ >::RestrictTo(), BaseCursor::type, and Rectangle< PT, SZ >::width.
Referenced by TileTerraformMouseMode::SetCursors().
void MultiCursor::MarkDirty () override virtual
Update the cursor at the screen.
Implements BaseCursor.
Definition at line 587 of file viewport.cpp.
References Rectangle< PT, SZ >::base, CUR_TYPE_INVALID, Rectangle< PT, SZ >::height, Viewport::MarkVoxelDirty(), rect, BaseCursor::type, BaseCursor::vp, Rectangle< PT, SZ >::width, and Point< CT >::x.
Referenced by SetCursor().
CursorType MultiCursor::GetCursor (const XYZPoint16 & cursor_pos) override virtual
Get a cursor.
Parameters
cursor_pos Expected coordinate of the cursor.
Returns
The cursor sprite if the cursor exists and the coordinates are correct, else nullptr.
Implements BaseCursor.
Definition at line 599 of file viewport.cpp.
References CUR_TYPE_INVALID, CUR_TYPE_TILE, Rectangle< PT, SZ >::IsPointInside(), rect, BaseCursor::type, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by Viewport::GetCursorAtPos().
uint8 MultiCursor::GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos) override virtual
Get the maximum height of the xpos, ypos stack that needs to be examined.
Parameters
xpos X position of the voxel.
ypos Y position of the voxel.
zpos Top of the stack found so far.
Returns
Highest voxel to draw for this cursor.
Implements BaseCursor.
Definition at line 609 of file viewport.cpp.
References CUR_TYPE_INVALID, GetZpos(), Rectangle< PT, SZ >::IsPointInside(), rect, BaseCursor::type, and zpos.
Referenced by Viewport::GetMaxCursorHeight().
void MultiCursor::ClearZPositions ()
Clear the z-positions cache.
Definition at line 548 of file viewport.cpp.
References zpos.
Referenced by MultiCursor(), and SetCursor().
uint8 MultiCursor::GetZpos (int xpos, int ypos)
Get the Z position of a tile within the cursor.
Parameters
xpos Horizontal world position.
ypos Vertical world position.
Returns
Height of the ground (which is the z-position of the cursor at the position).
Precondition
World position is inside the cursor rectangle.
World position is inside the world boundaries.
Definition at line 576 of file viewport.cpp.
References _world, Rectangle< PT, SZ >::base, VoxelWorld::GetGroundHeight(), Rectangle< PT, SZ >::height, rect, Rectangle< PT, SZ >::width, Point< CT >::x, Point< CT >::y, and zpos.
Referenced by GetMaxCursorHeight().
void MultiCursor::ResetZPosition (const Point32 & pos)
Reset the cached height of a voxel in the area.
Parameters
pos Position to reset (may be outside the cursor).
Definition at line 561 of file viewport.cpp.
References Rectangle< PT, SZ >::base, Rectangle< PT, SZ >::IsPointInside(), rect, Point< CT >::x, Point< CT >::y, and zpos.
Referenced by ChangeAreaCursorMode().
void BaseCursor::SetInvalid () inherited
Mark the cursor as being invalid, and update the viewport if necessary.
Definition at line 483 of file viewport.cpp.
References CUR_TYPE_INVALID, BaseCursor::MarkDirty(), and BaseCursor::type.
Referenced by FenceBuildManager::LeaveMode(), TileTerraformMouseMode::LeaveMode(), TileTerraformMouseMode::SetCursors(), and PathBuildManager::UpdateState().
The documentation for this class was generated from the following files:
viewport.h
viewport.cpp