FreeRCT: FenceBuildManager Class Reference
FenceBuildManager Class Reference
Helper for storing data and state about the fence building process.
#include <fence_build.h>
Public Member Functions
FenceBuildManager ()
Default constructor.
void OpenWindow ()
Fence GUI window just opened.
void CloseWindow ()
Fence GUI window just closed.
void SetCursors ()
Set/modify the cursors of the viewport.
bool MayActivateMode () override
Query the mode whether it can be enabled.
void ActivateMode (const Point16 &pos) override
Restart the fence build interaction sequence.
void LeaveMode () override
Notification that the mouse mode has been disabled.
bool EnableCursors () override
Control display of cursors in the mouse mode.
void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) override
The mouse moved while in this mouse mode.
void OnMouseButtonEvent (Viewport *vp, uint8 state) override
A mouse click was detected.
void OnMouseWheelEvent (Viewport *vp, int direction) override
A mouse wheelie event has been detected.
void SelectFenceType (FenceType fence_type)
Set the selected fence type.
FenceType GetSelectedFenceType () const
Get the selected fence type.
Public Attributes
const WindowTypes wtype
Type of window associated with this mouse mode.
const ViewportMouseMode mode
Mouse mode implemented by the object.
Private Attributes
FenceBuildState state
Own state.
uint8 mouse_state
State of the mouse buttons.
uint16 xpos
X coordinate of the selected voxel.
uint16 xlong
X coordinate of the long fence destination voxel.
uint16 ypos
Y coordinate of the selected voxel.
uint16 ylong
Y coordinate of the long fence destination voxel.
uint8 zpos
Z coordinate of the selected voxel.
uint8 zlong
Z coordinate of the long fence destination voxel.
FenceType selected_fence_type
Selected fence type or FENCE_TYPE_INVALID if no fence type is selected.
Detailed Description
Helper for storing data and state about the fence building process.
Definition at line 29 of file fence_build.h.
Constructor & Destructor Documentation
FenceBuildManager::FenceBuildManager ()
Default constructor.
Definition at line 23 of file fence_build.cpp.
References FBS_OFF, FENCE_TYPE_INVALID, mouse_state, selected_fence_type, and state.
Member Function Documentation
void FenceBuildManager::OpenWindow ()
Fence GUI window just opened.
Definition at line 31 of file fence_build.cpp.
References _mouse_modes, FBS_NO_MOUSE, FBS_OFF, MouseMode::mode, MouseModes::SetMouseMode(), and state.
void FenceBuildManager::CloseWindow ()
Fence GUI window just closed.
Definition at line 40 of file fence_build.cpp.
References _mouse_modes, FBS_OFF, FBS_ON, MouseModes::SetViewportMousemode(), and state.
void FenceBuildManager::SetCursors ()
Set/modify the cursors of the viewport.
Definition at line 68 of file fence_build.cpp.
References _sprite_manager, _world, Viewport::ComputeCursorPosition(), CS_GROUND_EDGE, CS_NONE, CUR_TYPE_EDGE_NE, CUR_TYPE_EDGE_NW, FinderData::cursor, Viewport::edge_cursor, ExpandTileSlope(), FW_EDGE, VoxelWorld::GetCreateVoxel(), SpriteStorage::GetFenceSprite(), Voxel::GetGroundSlope(), SpriteManager::GetSprites(), GetViewport(), VoxelWorld::GetVoxel(), IsRaisedEdge(), Viewport::orientation, selected_fence_type, EdgeCursor::SetCursor(), Viewport::tile_height, Viewport::tile_width, TSB_STEEP, TSB_TOP, FinderData::xvoxel, FinderData::yvoxel, and FinderData::zvoxel.
Referenced by ActivateMode(), OnMouseMoveEvent(), and SelectFenceType().
bool FenceBuildManager::MayActivateMode () override virtual
Query the mode whether it can be enabled.
Method may be called at any moment (or more often than once). Answering true does not mean the mouse mode will be activated.
Returns
Whether the mode may be enabled.
Implements MouseMode.
Definition at line 49 of file fence_build.cpp.
References FBS_OFF, and state.
void FenceBuildManager::ActivateMode (const Point16 & pos) override virtual
Restart the fence build interaction sequence.
Parameters
pos New mouse position.
Returns
The mouse mode should be enabled.
Implements MouseMode.
Definition at line 59 of file fence_build.cpp.
References FBS_ON, mouse_state, SetCursors(), and state.
void FenceBuildManager::LeaveMode () override virtual
Notification that the mouse mode has been disabled.
Implements MouseMode.
Definition at line 106 of file fence_build.cpp.
References Viewport::area_cursor, FBS_NO_MOUSE, FBS_ON, GetViewport(), BaseCursor::SetInvalid(), state, and Viewport::tile_cursor.
bool FenceBuildManager::EnableCursors () override virtual
Control display of cursors in the mouse mode.
Returns
true when cursors should be displayed, false otherwise.
Implements MouseMode.
Definition at line 116 of file fence_build.cpp.
References FBS_OFF, and state.
void FenceBuildManager::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) override virtual
The mouse moved while in this mouse mode.
Parameters
vp Viewport object.
old_pos Previous position.
pos Current position.
Reimplemented from MouseMode.
Definition at line 125 of file fence_build.cpp.
References SetCursors().
void FenceBuildManager::OnMouseButtonEvent (Viewport * vp, uint8 state) override virtual
A mouse click was detected.
Parameters
vp Viewport object.
state State of the mouse buttons.
See also
MouseButtons
Reimplemented from MouseMode.
Definition at line 130 of file fence_build.cpp.
References _game_mode_mgr, _world, CUR_TYPE_EDGE_NE, Viewport::edge_cursor, ExpandTileSlope(), VoxelStack::GetCreate(), Voxel::GetGroundSlope(), VoxelWorld::GetModifyStack(), VoxelWorld::GetTileOwner(), GameModeManager::InPlayMode(), IsRaisedEdge(), Viewport::MarkVoxelDirty(), MB_CURRENT, MB_LEFT, mouse_state, OWN_PARK, selected_fence_type, Voxel::SetFenceType(), TSB_TOP, BaseCursor::type, EdgeCursor::xpos, EdgeCursor::ypos, and EdgeCursor::zpos.
void FenceBuildManager::OnMouseWheelEvent (Viewport * vp, int direction) override virtual
A mouse wheelie event has been detected.
Parameters
vp Viewport object.
direction Direction of movement.
Reimplemented from MouseMode.
Definition at line 121 of file fence_build.cpp.
void FenceBuildManager::SelectFenceType (FenceType fence_type)
Set the selected fence type.
Parameters
fence_type Fence type to select or FENCE_TYPE_INVALID.
Definition at line 158 of file fence_build.cpp.
References selected_fence_type, and SetCursors().
Referenced by FenceGui::OnChange(), and FenceGui::OnClickFence().
FenceType FenceBuildManager::GetSelectedFenceType () const inline
Get the selected fence type.
Returns
The selected fence type or FENCE_TYPE_INVALID if no fence type is selected.
Definition at line 69 of file fence_build.h.
References selected_fence_type.
The documentation for this class was generated from the following files:
fence_build.h
fence_build.cpp