FreeRCT: ConfigSection Class Reference
ConfigSection Class Reference
File IO
Section in a configuration file (a set of related items).
#include <config_reader.h>
Public Member Functions
ConfigSection (const char *sect_name)
Construct a named section.
const ConfigItem * GetItem (const char *key) const
Get an item from a section if it exists.
Public Attributes
const char * sect_name
Name of the section.
ConfigItemList items
Items of the section.
Detailed Description
Section in a configuration file (a set of related items).
Definition at line 42 of file config_reader.h.
Constructor & Destructor Documentation
ConfigSection::ConfigSection (const char * sect_name)
Construct a named section.
Parameters
sect_name Name of the new section.
Note
Section name gets copied during construction.
Definition at line 60 of file config_reader.cpp.
References items, and StrDup().
Member Function Documentation
const ConfigItem * ConfigSection::GetItem (const char * key) const
Get an item from a section if it exists.
Parameters
key Value of the key to look for (case sensitive).
Returns
The associated item if it exists, else nullptr.
Definition at line 76 of file config_reader.cpp.
References items.
Referenced by ConfigFile::GetNum(), and ConfigFile::GetValue().
The documentation for this class was generated from the following files:
config_reader.h
config_reader.cpp