FreeRCT: TrackVoxel Struct Reference
TrackVoxel Struct Reference
Class for storing the data of a single voxel in a track piece.
#include <nodes.h>
Public Member Functions
void Write (FileWriter *fw, FileBlock *fb, int rot)
Write a track voxel (after rotating it rot times first).
bool Load (RcdFileReader *rcd_file, size_t length, const ImageMap &sprites)
Load a track voxel.
bool HasPlatform () const
Does the track piece have a platform?
TileEdge GetPlatformDirection () const
Get the 'direction' of the platform (the edge used for entering the voxel).
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int dx
Relative X position of the voxel.
int dy
Relative Y position of the voxel.
int dz
Relative Z position of the voxel.
int flags
Flags of the voxel (space corners, platform direction).
std::array< std::shared_ptr
< SpriteBlock >, 4 > back
Back coaster sprites.
std::array< std::shared_ptr
< SpriteBlock >, 4 > front
Front coaster sprites.
ImageData * back [4]
Reference to the background tracks (N/E/S/W view).
ImageData * front [4]
Reference to the front tracks (N/E/S/W view).
XYZPoint16 dxyz
Relative position of the voxel.
uint8 flags
Flags of the voxel (space requirements, platform direction).
Detailed Description
Class for storing the data of a single voxel in a track piece.
Data of a voxel in a track piece.
Definition at line 799 of file nodes.h.
Member Function Documentation
void TrackVoxel::Write (FileWriter * fw, FileBlock * fb, int rot)
Write a track voxel (after rotating it rot times first).
Parameters
fw Output stream to write the graphics to.
fb File block to write to.
rot Number of -90 degrees rotation to apply first.
Definition at line 1256 of file nodes.cpp.
References back, dx, dy, dz, flags, front, RotateFlags(), RotateXY(), FileBlock::SaveInt8(), FileBlock::SaveUInt32(), and FileBlock::SaveUInt8().
bool TrackVoxel::Load (RcdFileReader * rcd_file, size_t length, const ImageMap & sprites)
Load a track voxel.
Parameters
rcd_file Data file being loaded.
length Length of the voxel (according to the file).
sprites Already loaded sprite blocks.
Returns
Loading was successful.
Definition at line 36 of file track_piece.cpp.
References back, dxyz, flags, front, RcdFileReader::GetInt8(), RcdFileReader::GetUInt8(), LoadSpriteFromFile(), XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
bool TrackVoxel::HasPlatform () const inline
Does the track piece have a platform?
Returns
Whether the track piece has a platform.
Definition at line 35 of file track_piece.h.
References flags, and GB().
TileEdge TrackVoxel::GetPlatformDirection () const inline
Get the 'direction' of the platform (the edge used for entering the voxel).
Returns
Direction of the tracks (and thus the platform).
Precondition
HasPlatform() holds.
Definition at line 45 of file track_piece.h.
References flags, and GB().
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this struct was generated from the following files:
nodes.h
track_piece.h
nodes.cpp
track_piece.cpp