FreeRCT: RcdFileReader Class Reference
RcdFileReader Class Reference
File IO
Class for reading an RCD file.
#include <fileio.h>
Public Member Functions
RcdFileReader (const char *fname)
RCD file reader constructor, loading data from a file.
~RcdFileReader ()
Destructor.
bool CheckFileHeader (const char *hdr_name, uint32 version)
Check whether the file header makes sense, and has the right version.
bool ReadBlockHeader ()
Starting at the first byte of a block, read the block information, and put it in name, version, and size.
bool SkipBytes (uint32 count)
Skip a number of bytes in the file.
bool GetBlob (void *address, size_t length)
Get a blob of data from the file.
uint8 GetUInt8 ()
Read an 8 bits unsigned number.
uint16 GetUInt16 ()
Read an 16 bits unsigned number.
uint32 GetUInt32 ()
Read an 32 bits unsigned number.
int8 GetInt8 ()
Read an 8 bits signed number.
int16 GetInt16 ()
Read an 16 bits signed number.
int32 GetInt32 ()
Read an 32 bits signed number.
size_t GetRemaining ()
Get length of data not yet read.
Public Attributes
char name [5]
Name of the last found block (with ReadBlockHeader).
uint32 version
Version number of the last found block (with ReadBlockHeader).
uint32 size
Data size of the last found block (with ReadBlockHeader).
Private Attributes
FILE * fp
File handle of the opened file.
size_t file_pos
Position in the opened file.
size_t file_size
Size of the opened file.
Detailed Description
Class for reading an RCD file.
Definition at line 47 of file fileio.h.
Constructor & Destructor Documentation
RcdFileReader::RcdFileReader (const char * fname)
RCD file reader constructor, loading data from a file.
Parameters
fname Name of the file to load.
Definition at line 119 of file fileio.cpp.
References file_pos, file_size, fp, and name.
RcdFileReader::~RcdFileReader ()
Destructor.
Definition at line 134 of file fileio.cpp.
References fp.
Member Function Documentation
bool RcdFileReader::CheckFileHeader (const char * hdr_name, uint32 version)
Check whether the file header makes sense, and has the right version.
Parameters
hdr_name Header name (should be 4 chars long).
version Header version.
Returns
The header seems correct.
Definition at line 219 of file fileio.cpp.
References fp, GetBlob(), GetRemaining(), GetUInt32(), name, and version.
Referenced by SpriteManager::Load(), and RcdFileCollection::ScanFileForMetaInfo().
bool RcdFileReader::ReadBlockHeader ()
Starting at the first byte of a block, read the block information, and put it in name, version, and size.
Returns
Whether a block was found. If so, data is in name, version, and size.
Definition at line 236 of file fileio.cpp.
References file_pos, file_size, GetBlob(), GetRemaining(), GetUInt32(), name, size, and version.
Referenced by SpriteManager::Load(), and RcdFileCollection::ScanFileForMetaInfo().
bool RcdFileReader::SkipBytes (uint32 count)
Skip a number of bytes in the file.
Parameters
count Number of bytes to move forward.
Returns
Skipping was successful.
Definition at line 250 of file fileio.cpp.
References file_pos, file_size, and fp.
Referenced by SpriteManager::Load().
bool RcdFileReader::GetBlob (void * address, size_t length)
Get a blob of data from the file.
Parameters
address Address to load into.
length Length of the data.
Returns
Loading was successful.
Definition at line 263 of file fileio.cpp.
References file_pos, and fp.
Referenced by CheckFileHeader(), ImageData::Load32bpp(), ImageData::Load8bpp(), ReadBlockHeader(), and ReadUtf8Text().
uint8 RcdFileReader::GetUInt8 ()
Read an 8 bits unsigned number.
Returns
Loaded number.
Precondition
File must be open, data must be available.
Definition at line 153 of file fileio.cpp.
References file_pos, and fp.
Referenced by GetInt16(), GetInt8(), GetString(), GetUInt16(), ShopType::Load(), TrackVoxel::Load(), TextData::Load(), CoasterType::Load(), TrackPiece::Load(), Animation::Load(), AnimationSprites::Load(), LoadCoasterPlatform(), GuiSprites::LoadGBOR(), GuiSprites::LoadGSCL(), GuiSprites::LoadGSLI(), LoadPRSG(), and LoadTrackCurve().
uint16 RcdFileReader::GetUInt16 ()
Read an 16 bits unsigned number.
Returns
Loaded number.
Precondition
File must be open, data must be available.
Definition at line 174 of file fileio.cpp.
References GetUInt8().
Referenced by GetInt32(), GetUInt32(), ShopType::Load(), CarType::Load(), TextData::Load(), CoasterType::Load(), Fence::Load(), TrackPiece::Load(), Animation::Load(), AnimationSprites::Load(), ImageData::Load32bpp(), ImageData::Load8bpp(), SpriteManager::LoadBDIR(), LoadCoasterPlatform(), SpriteManager::LoadFUND(), GuiSprites::LoadGBOR(), GuiSprites::LoadGCHK(), GuiSprites::LoadGSCL(), GuiSprites::LoadGSLI(), SpriteManager::LoadPATH(), SpriteManager::LoadPDEC(), SpriteManager::LoadPLAT(), SpriteManager::LoadSUPP(), SpriteManager::LoadSURF(), SpriteManager::LoadTCOR(), and SpriteManager::LoadTSEL().
uint32 RcdFileReader::GetUInt32 ()
Read an 32 bits unsigned number.
Returns
Loaded number.
Precondition
File must be open, data must be available.
Definition at line 196 of file fileio.cpp.
References GetUInt16().
Referenced by CheckFileHeader(), ShopType::Load(), CarType::Load(), CoasterType::Load(), TrackPiece::Load(), ImageData::Load8bpp(), LoadBezier(), LoadPRSG(), LoadSpriteFromFile(), LoadTextFromFile(), and ReadBlockHeader().
int8 RcdFileReader::GetInt8 ()
Read an 8 bits signed number.
Returns
Loaded number.
Precondition
File must be open, data must be available.
Definition at line 164 of file fileio.cpp.
References GetUInt8().
Referenced by TrackVoxel::Load(), and TrackPiece::Load().
int16 RcdFileReader::GetInt16 ()
Read an 16 bits signed number.
Returns
Loaded number.
Precondition
File must be open, data must be available.
Definition at line 185 of file fileio.cpp.
References GetUInt8().
Referenced by Animation::Load(), ImageData::Load32bpp(), ImageData::Load8bpp(), LoadBezier(), and LoadTrackCurve().
int32 RcdFileReader::GetInt32 ()
Read an 32 bits signed number.
Returns
Loaded number.
Precondition
File must be open, data must be available.
Definition at line 207 of file fileio.cpp.
References GetUInt16().
Referenced by ShopType::Load().
size_t RcdFileReader::GetRemaining ()
Get length of data not yet read.
Returns
Count of remaining data.
Definition at line 143 of file fileio.cpp.
References file_pos, and file_size.
Referenced by CheckFileHeader(), and ReadBlockHeader().
The documentation for this class was generated from the following files:
fileio.h
fileio.cpp