FreeRCT: GBORBlock Class Reference
GBORBlock Class Reference
GBOR game block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int widget_type
Widget type.
int border_top
Border width of the top edge.
int border_left
Border width of the left edge.
int border_right
Border width of the right edge.
int border_bottom
Border width of the bottom edge.
int min_width
Minimal width of the border.
int min_height
Minimal height of the border.
int h_stepsize
Horizontal stepsize of the border.
int v_stepsize
Vertical stepsize of the border.
std::shared_ptr< SpriteBlock > tl
Top-left sprite.
std::shared_ptr< SpriteBlock > tm
Top-middle sprite.
std::shared_ptr< SpriteBlock > tr
Top-right sprite.
std::shared_ptr< SpriteBlock > ml
Left sprite.
std::shared_ptr< SpriteBlock > mm
Middle sprite.
std::shared_ptr< SpriteBlock > mr
Right sprite.
std::shared_ptr< SpriteBlock > bl
Bottom-left sprite.
std::shared_ptr< SpriteBlock > bm
Bottom-middle sprite.
std::shared_ptr< SpriteBlock > br
Bottom-right sprite.
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
GBOR game block.
Definition at line 602 of file nodes.h.
Member Function Documentation
int GBORBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 981 of file nodes.cpp.
References FileWriter::AddBlock(), bl, NamedBlock::blk_name, bm, border_bottom, border_left, border_right, border_top, br, FileBlock::CheckEndSave(), h_stepsize, min_height, min_width, ml, mm, mr, FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), FileBlock::SaveUInt8(), FileBlock::StartSave(), tl, tm, tr, v_stepsize, NamedBlock::version, and widget_type.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp