FreeRCT: BackgroundWidget Class Reference
BackgroundWidget Class Reference
Widgets and supporting functions of the program
Base class for canvas-like widgets.
#include <widget.h>
Public Member Functions
BackgroundWidget (WidgetType wtype)
Base class background widget constructor.
void SetupMinimalSize (GuiWindow *w, BaseWidget **wid_array) override
Compute smallest size of the widget.
void SetSmallestSizePosition (const Rectangle16 &rect) override
Set the minimal size of the widget, and assign rect to the current position and size.
void Draw (const GuiWindow *w) override
Draw the widget.
BaseWidget * GetWidgetByPosition (const Point16 &pt) override
Get the widget at the given relative window position.
void AutoRaiseButtons (const Point32 &base) override
Raise all push buttons in the tree.
bool IsChecked () const
Is the 'checked' flag on?
bool IsPressed () const
Is the 'pressed' flag on?
bool IsShaded () const
Is the 'shaded' flag on?
void SetChecked (bool value)
Set the 'checked' flag to the new value.
void SetPressed (bool value)
Set the 'pressed' flag to the new value.
void SetShaded (bool value)
Set the 'shaded' flag to the new value.
void MarkDirty (const Point32 &base) const
Denote the widget as being needed to redraw.
Public Attributes
BaseWidget * child
Child widget displayed on top of the background widget.
uint8 flags
Flags of the leaf widget.
ColourRange colour
Colour of the widget.
StringID tooltip
Tool-tip of the widget.
WidgetType wtype
Widget type.
WidgetNumber number
Widget number.
uint16 smallest_x
Original horizontal size.
uint16 smallest_y
Original vertical size.
uint16 min_x
Minimal horizontal size.
uint16 min_y
Minimal vertical size.
Rectangle16 pos
Current position and size (relative to window top-left edge).
uint16 fill_x
Horizontal fill step.
uint16 fill_y
Vertical fill step.
uint16 resize_x
Horizontal resize step.
uint16 resize_y
Vertical resize step.
uint8 paddings [PAD_COUNT]
Padding.
Protected Member Functions
void SetWidget (BaseWidget **wid_array)
Add the widget to the widget array wid_array.
void InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert)
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
void InitMinimalSize (const BorderSpriteData *bsd, uint16 content_width, uint16 content_height)
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Detailed Description
Base class for canvas-like widgets.
Implements WT_PANEL
Definition at line 264 of file widget.h.
Constructor & Destructor Documentation
BackgroundWidget::BackgroundWidget (WidgetType wtype)
Base class background widget constructor.
Parameters
wtype Widget type.
Definition at line 887 of file widget.cpp.
References child.
Member Function Documentation
void BackgroundWidget::SetupMinimalSize (GuiWindow * w, BaseWidget ** wid_array) override virtual
Compute smallest size of the widget.
Parameters
w Window owning the widget.
wid_array [out] Array of widget pointers.
Reimplemented from LeafWidget.
Definition at line 902 of file widget.cpp.
References _gui_sprites, child, BaseWidget::fill_x, BaseWidget::fill_y, GuiWindow::initialized, BaseWidget::min_x, BaseWidget::min_y, BaseWidget::number, GuiSprites::panel, BaseWidget::resize_x, BaseWidget::resize_y, BaseWidget::SetupMinimalSize(), BaseWidget::SetWidget(), BaseWidget::smallest_x, BaseWidget::smallest_y, GuiSprites::tabbar_panel, GuiWindow::UpdateWidgetSize(), WT_PANEL, and BaseWidget::wtype.
void BackgroundWidget::SetSmallestSizePosition (const Rectangle16 & rect) override virtual
Set the minimal size of the widget, and assign rect to the current position and size.
Parameters
rect Smallest size, and suggested position of the (entire) widget.
Reimplemented from BaseWidget.
Definition at line 922 of file widget.cpp.
References _gui_sprites, Rectangle< PT, SZ >::base, BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, child, Rectangle< PT, SZ >::height, BaseWidget::min_x, BaseWidget::min_y, PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, BaseWidget::paddings, GuiSprites::panel, BaseWidget::pos, BaseWidget::SetSmallestSizePosition(), Rectangle< PT, SZ >::width, Point< CT >::x, and Point< CT >::y.
void BackgroundWidget::Draw (const GuiWindow * w) override virtual
Draw the widget.
Parameters
w Window being drawn.
Reimplemented from LeafWidget.
Definition at line 946 of file widget.cpp.
References _gui_sprites, BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, child, LeafWidget::colour, BaseWidget::Draw(), DrawBorderSprites(), GuiWindow::DrawWidget(), GuiWindow::GetWidgetScreenX(), GuiWindow::GetWidgetScreenY(), Rectangle< PT, SZ >::height, INVALID_WIDGET_INDEX, BaseWidget::number, PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, BaseWidget::paddings, GuiSprites::panel, BaseWidget::pos, GuiSprites::tabbar_panel, Rectangle< PT, SZ >::width, WT_PANEL, and BaseWidget::wtype.
BaseWidget * BackgroundWidget::GetWidgetByPosition (const Point16 & pt) override virtual
Get the widget at the given relative window position.
Parameters
pt Relative point.
Returns
The widget underneath the point, or nullptr.
Reimplemented from BaseWidget.
Definition at line 967 of file widget.cpp.
References child, BaseWidget::GetWidgetByPosition(), Rectangle< PT, SZ >::IsPointInside(), and BaseWidget::pos.
void BackgroundWidget::AutoRaiseButtons (const Point32 & base) override virtual
Raise all push buttons in the tree.
Parameters
base Base position of the window.
Reimplemented from LeafWidget.
Definition at line 979 of file widget.cpp.
References BaseWidget::AutoRaiseButtons(), and child.
bool LeafWidget::IsChecked () const inline inherited
Is the 'checked' flag on?
Returns
whether the 'checked' flag is set.
Definition at line 138 of file widget.h.
References LWF_CHECKED.
Referenced by GuiWindow::GetSelectedRadioButton(), and GuiWindow::SetWidgetChecked().
bool LeafWidget::IsPressed () const inline inherited
Is the 'pressed' flag on?
Returns
whether the 'pressed' flag is set.
Definition at line 147 of file widget.h.
References LWF_PRESSED.
Referenced by LeafWidget::AutoRaiseButtons(), DataWidget::Draw(), GuiWindow::GetSelectedRadioButton(), and GuiWindow::SetWidgetPressed().
bool LeafWidget::IsShaded () const inline inherited
Is the 'shaded' flag on?
Returns
whether the 'shaded' flag is set.
Definition at line 156 of file widget.h.
References LWF_SHADED.
Referenced by DataWidget::Draw(), ScrollbarWidget::Draw(), GuiWindow::GetSelectedRadioButton(), GuiWindow::OnMouseButtonEvent(), and GuiWindow::SetWidgetShaded().
void LeafWidget::SetChecked (bool value) inline inherited
Set the 'checked' flag to the new value.
Parameters
value New value of the 'checked' flag.
Definition at line 165 of file widget.h.
References LWF_CHECKED.
Referenced by GuiWindow::SetWidgetChecked().
void LeafWidget::SetPressed (bool value) inline inherited
Set the 'pressed' flag to the new value.
Parameters
value New value of the 'pressed' flag.
Definition at line 174 of file widget.h.
References LWF_PRESSED.
Referenced by LeafWidget::AutoRaiseButtons(), GuiWindow::OnMouseButtonEvent(), and GuiWindow::SetWidgetPressed().
void LeafWidget::SetShaded (bool value) inline inherited
Set the 'shaded' flag to the new value.
Parameters
value New value of the 'shaded' flag.
Definition at line 183 of file widget.h.
References LWF_SHADED.
Referenced by GuiWindow::SetWidgetShaded().
void BaseWidget::MarkDirty (const Point32 & base) const inherited
Denote the widget as being needed to redraw.
Parameters
base Window base coordinate.
Definition at line 212 of file widget.cpp.
References _video, VideoSystem::MarkDisplayDirty(), Point< CT >::x, and Point< CT >::y.
Referenced by LeafWidget::AutoRaiseButtons(), GuiWindow::MarkWidgetDirty(), ScrollbarWidget::OnClick(), GuiWindow::OnMouseButtonEvent(), GuiWindow::SetWidgetChecked(), GuiWindow::SetWidgetPressed(), and GuiWindow::SetWidgetShaded().
void BaseWidget::SetWidget (BaseWidget ** wid_array) protected inherited
Add the widget to the widget array wid_array.
Parameters
wid_array The widget array.
Definition at line 128 of file widget.cpp.
References BaseWidget::number.
Referenced by BaseWidget::SetupMinimalSize(), LeafWidget::SetupMinimalSize(), DataWidget::SetupMinimalSize(), ScrollbarWidget::SetupMinimalSize(), SetupMinimalSize(), and IntermediateWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
Parameters
content_width Minimal width of the content.
content_height Minimal height of the content.
border_hor Horizontal border space.
border_vert Vertical border space.
Definition at line 97 of file widget.cpp.
References BaseWidget::min_x, BaseWidget::min_y, PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, and BaseWidget::paddings.
Referenced by LeafWidget::SetupMinimalSize(), and DataWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (const BorderSpriteData * bsd, uint16 content_width, uint16 content_height) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Parameters
bsd Used border sprites.
content_width Minimal width of the content.
content_height Minimal height of the content.
Definition at line 109 of file widget.cpp.
References BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, BaseWidget::fill_x, BaseWidget::fill_y, BorderSpriteData::hor_stepsize, LeastCommonMultiple(), BorderSpriteData::min_height, BorderSpriteData::min_width, BaseWidget::resize_x, BaseWidget::resize_y, and BorderSpriteData::vert_stepsize.
Member Data Documentation
uint8 LeafWidget::flags inherited
Flags of the leaf widget.
See also
LeafWidgetFlags
Definition at line 188 of file widget.h.
Referenced by LeafWidget::Draw(), and LeafWidget::LeafWidget().
The documentation for this class was generated from the following files:
widget.h
widget.cpp