FreeRCT: MouseMode Class Reference
MouseMode Class Reference abstract
A single mouse mode.
#include <viewport.h>
Public Member Functions
MouseMode (WindowTypes wtype, ViewportMouseMode mode)
Constructor of a mouse mode.
virtual bool MayActivateMode ()=0
Query the mode whether it can be enabled.
virtual void ActivateMode (const Point16 &pos)=0
Activate the mouse mode.
virtual void LeaveMode ()=0
Notification that the mouse mode is about to be disabled.
virtual void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos)
The mouse moved while in this mouse mode.
virtual void OnMouseButtonEvent (Viewport *vp, uint8 state)
A mouse click was detected.
virtual void OnMouseWheelEvent (Viewport *vp, int direction)
A mouse wheelie event has been detected.
virtual bool EnableCursors ()=0
Control display of cursors in the mouse mode.
Public Attributes
const WindowTypes wtype
Type of window associated with this mouse mode.
const ViewportMouseMode mode
Mouse mode implemented by the object.
Detailed Description
A single mouse mode.
Definition at line 268 of file viewport.h.
Constructor & Destructor Documentation
MouseMode::MouseMode (WindowTypes p_wtype, ViewportMouseMode p_mode)
Constructor of a mouse mode.
Parameters
p_wtype Window associated with the mouse mode (use WC_NONE if no window).
p_mode Mouse mode implemented by the object.
Definition at line 1607 of file viewport.cpp.
Member Function Documentation
virtual bool MouseMode::MayActivateMode () pure virtual
Query the mode whether it can be enabled.
Method may be called at any moment (or more often than once). Answering true does not mean the mouse mode will be activated.
Returns
Whether the mode may be enabled.
Implemented in DefaultMouseMode, TileTerraformMouseMode, CoasterBuildMode, ShopPlacementManager, FenceBuildManager, PathBuildManager, and SelectMouseMode.
Referenced by MouseModes::SetMouseMode(), MouseModes::SetViewportMousemode(), and MouseModes::SwitchMode().
virtual void MouseMode::ActivateMode (const Point16 & pos) pure virtual
Activate the mouse mode.
Parameters
pos Last known mouse position.
Implemented in DefaultMouseMode, TileTerraformMouseMode, CoasterBuildMode, ShopPlacementManager, FenceBuildManager, PathBuildManager, and SelectMouseMode.
Referenced by MouseModes::SwitchMode().
virtual void MouseMode::LeaveMode () pure virtual
Notification that the mouse mode is about to be disabled.
Implemented in DefaultMouseMode, TileTerraformMouseMode, CoasterBuildMode, ShopPlacementManager, FenceBuildManager, PathBuildManager, and SelectMouseMode.
Referenced by MouseModes::SwitchMode().
void MouseMode::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) virtual
The mouse moved while in this mouse mode.
Parameters
vp Viewport object.
old_pos Previous position.
pos Current position.
Reimplemented in TileTerraformMouseMode, CoasterBuildMode, ShopPlacementManager, FenceBuildManager, PathBuildManager, and SelectMouseMode.
Definition at line 1621 of file viewport.cpp.
Referenced by Viewport::OnMouseMoveEvent().
void MouseMode::OnMouseButtonEvent (Viewport * vp, uint8 state) virtual
A mouse click was detected.
Parameters
vp Viewport object.
state State of the mouse buttons.
See also
MouseButtons
Reimplemented in TileTerraformMouseMode, CoasterBuildMode, ShopPlacementManager, FenceBuildManager, PathBuildManager, and SelectMouseMode.
Definition at line 1630 of file viewport.cpp.
Referenced by Viewport::OnMouseButtonEvent().
void MouseMode::OnMouseWheelEvent (Viewport * vp, int direction) virtual
A mouse wheelie event has been detected.
Parameters
vp Viewport object.
direction Direction of movement.
Reimplemented in TileTerraformMouseMode, and FenceBuildManager.
Definition at line 1639 of file viewport.cpp.
Referenced by Viewport::OnMouseWheelEvent().
virtual bool MouseMode::EnableCursors () pure virtual
Control display of cursors in the mouse mode.
Returns
true when cursors should be displayed, false otherwise.
Implemented in DefaultMouseMode, TileTerraformMouseMode, CoasterBuildMode, ShopPlacementManager, FenceBuildManager, PathBuildManager, and SelectMouseMode.
Referenced by Viewport::OnDraw().
The documentation for this class was generated from the following files:
viewport.h
viewport.cpp