FreeRCT: WorldAdditions Class Reference
WorldAdditions Class Reference
Proposed additions to _world.
#include <map.h>
Public Member Functions
void Clear ()
Remove all modifications.
void Commit ()
Move modifications to the 'real' _world.
VoxelStack * GetModifyStack (uint16 x, uint16 y)
Get a voxel stack with the purpose of modifying it.
const VoxelStack * GetStack (uint16 x, uint16 y) const
Get a voxel stack (read-only) either from the modifications, or from the 'real' _world.
const Voxel * GetVoxel (const XYZPoint16 &vox) const
Get a voxel in the world by voxel coordinate.
Voxel * GetCreateVoxel (const XYZPoint16 &vox, bool create)
Get a voxel in the world by voxel coordinate.
void MarkDirty (Viewport *vp)
Mark the additions in the display as outdated, so they get repainted.
Protected Attributes
VoxelStackMap modified_stacks
Modified voxel stacks.
Detailed Description
Proposed additions to _world.
Temporary buffer to make changes in the world, and show them to the user without having them really in the game until the user confirms.
Note
This world does not use the Voxel::voxel_objects list.
Definition at line 589 of file map.h.
Member Function Documentation
void WorldAdditions::Clear ()
Remove all modifications.
Definition at line 651 of file map.cpp.
References modified_stacks.
Referenced by CoasterBuildWindow::BuildTrackPiece(), ChangeAreaCursorMode(), ChangeTileCursorMode(), Commit(), PathBuildManager::ComputeNewLongPath(), TerrainChanges::ModifyWorld(), CoasterBuildWindow::OnClick(), ShopPlacementManager::PlaceShop(), PathBuildManager::SelectBuyRemove(), CoasterBuildMode::UpdateDisplay(), and PathBuildManager::UpdateState().
void WorldAdditions::Commit ()
Move modifications to the 'real' _world.
Definition at line 660 of file map.cpp.
References Clear(), modified_stacks, VoxelWorld::MoveStack(), Point< CT >::x, and Point< CT >::y.
Referenced by CoasterBuildWindow::BuildTrackPiece(), TerrainChanges::ModifyWorld(), CoasterBuildWindow::OnClick(), PathBuildManager::OnMouseButtonEvent(), ShopPlacementManager::OnMouseButtonEvent(), PathBuildManager::SelectBuyRemove(), and PathBuildManager::TileClicked().
VoxelStack * WorldAdditions::GetModifyStack (uint16 x, uint16 y)
Get a voxel stack with the purpose of modifying it.
If necessary, a copy from the _world stack is made.
Parameters
x X coordinate of the stack.
y Y coordinate of the stack.
Returns
The requested voxel stack.
Definition at line 675 of file map.cpp.
References VoxelStack::Copy(), VoxelWorld::GetStack(), and modified_stacks.
Referenced by BuildPathAtTile(), ChangePathAtTile(), GetCreateVoxel(), TerrainChanges::ModifyWorld(), RemovePathAtTile(), SetXFoundations(), and SetYFoundations().
const VoxelStack * WorldAdditions::GetStack (uint16 x, uint16 y) const
Get a voxel stack (read-only) either from the modifications, or from the 'real' _world.
Parameters
x X coordinate of the stack.
y Y coordinate of the stack.
Returns
The requested voxel stack.
Definition at line 692 of file map.cpp.
References VoxelWorld::GetStack(), and modified_stacks.
Referenced by VoxelCollector::Collect(), and GetVoxel().
const Voxel* WorldAdditions::GetVoxel (const XYZPoint16 & vox) const inline
Get a voxel in the world by voxel coordinate.
Parameters
vox Coordinate of the voxel.
Returns
Address of the voxel (if it exists).
Definition at line 605 of file map.h.
References VoxelStack::Get(), GetStack(), XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Voxel* WorldAdditions::GetCreateVoxel (const XYZPoint16 & vox, bool create) inline
Get a voxel in the world by voxel coordinate.
Parameters
vox Coordinate of the voxel.
create If the requested voxel does not exist, try to create it.
Returns
Address of the voxel (if it exists or could be created).
Definition at line 616 of file map.h.
References VoxelStack::GetCreate(), GetModifyStack(), XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by ExamineNeighbourPathEdge(), ShopPlacementManager::PlaceShop(), CoasterInstance::PlaceTrackPieceInAdditions(), and CoasterInstance::RemoveTrackPieceInAdditions().
void WorldAdditions::MarkDirty (Viewport * vp)
Mark the additions in the display as outdated, so they get repainted.
Parameters
vp Viewport displaying the world.
Definition at line 705 of file map.cpp.
References VoxelStack::base, VoxelStack::height, Viewport::MarkVoxelDirty(), modified_stacks, Point< CT >::x, and Point< CT >::y.
Referenced by Viewport::DisableWorldAdditions(), Viewport::EnableWorldAdditions(), Viewport::EnsureAdditionsAreVisible(), ShopPlacementManager::PlaceShop(), and Viewport::TimeoutCallback().
The documentation for this class was generated from the following files:
map.h
map.cpp