FreeRCT: Fence Class Reference
Fence Class Reference
Fence sprites.
#include <sprite_store.h>
Public Member Functions
bool Load (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a fence sprites block from a RCD file.
Public Attributes
uint8 type
Type of fence. (.
uint16 width
Width of a tile.
ImageData * sprites [FENCE_COUNT]
Fence sprites, may contain nullptr sprites.
RcdBlock * next
Pointer to next block.
Detailed Description
Fence sprites.
Definition at line 87 of file sprite_store.h.
Member Function Documentation
bool Fence::Load (RcdFileReader * rcd_file, const ImageMap & sprites)
Load a fence sprites block from a RCD file.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Definition at line 379 of file sprite_store.cpp.
References FENCE_TYPE_COUNT, RcdFileReader::GetUInt16(), LoadSpriteFromFile(), RcdFileReader::size, type, RcdFileReader::version, and width.
Referenced by SpriteManager::Load().
Member Data Documentation
uint8 Fence::type
Type of fence. (.
See also
FenceType)
Definition at line 94 of file sprite_store.h.
Referenced by SpriteStorage::AddFence(), Load(), and FenceGui::OnClickFence().
The documentation for this class was generated from the following files:
sprite_store.h
sprite_store.cpp