FreeRCT: OnRideGuests Class Reference
OnRideGuests Class Reference
Class holding the guests of a ride as a number of batches with a size.
#include <guest_batches.h>
Public Member Functions
OnRideGuests (int batch_size=0, int num_batches=0)
Constructor for storage of on-ride guests.
void Configure (int batch_size, int num_batches)
(Re)configure the ride for the given number of batches and batch size.
GuestBatch & GetBatch (int index)
Get a batch of guests.
int GetFreeBatch (int start=-1)
Get an empty batch.
int GetLoadingBatch (int start=-1)
Get a batch that is being loaded.
int GetFinishedBatch (int start=-1)
Get a batch that has finished the ride.
int GetUnloadingBatch (int start=-1)
Get a batch that is being unloaded.
void OnAnimate (int delay)
Time has passed, update the remaining times of the running batches.
Public Attributes
std::vector< GuestBatch > batches
Batches of guests.
int batch_size
Size of a batch of guests.
int num_batches
Number of batches in the ride.
Private Member Functions
int GetNextBatch (BatchState state, int start)
Get the index of the next batch with a given state.
Detailed Description
Class holding the guests of a ride as a number of batches with a size.
Definition at line 71 of file guest_batches.h.
Constructor & Destructor Documentation
OnRideGuests::OnRideGuests (int batch_size = 0, int num_batches = 0)
Constructor for storage of on-ride guests.
Parameters
batch_size Size of one group of guests.
num_batches Number of groups that can be on the ride at the same time.
Definition at line 115 of file guest_batches.cpp.
References Configure().
Member Function Documentation
void OnRideGuests::Configure (int batch_size, int num_batches)
(Re)configure the ride for the given number of batches and batch size.
Parameters
batch_size Size of one group of guests.
num_batches Number of groups that can be on the ride at the same time.
Note
The ride should be empty, as all guest information is destroyed.
Definition at line 126 of file guest_batches.cpp.
References batch_size, batches, and num_batches.
Referenced by OnRideGuests(), and ShopInstance::ShopInstance().
GuestBatch& OnRideGuests::GetBatch (int index) inline
Get a batch of guests.
Parameters
index Index number of the batch.
Returns
The requested batch.
Definition at line 82 of file guest_batches.h.
References batches.
Referenced by ShopInstance::EnterRide().
int OnRideGuests::GetFreeBatch (int start = -1) inline
Get an empty batch.
Parameters
start Index where the last search ended, or -1 to search from the start.
Returns
Index of a free batch, or -1 if no free batch exists.
Definition at line 92 of file guest_batches.h.
References BST_EMPTY, and GetNextBatch().
Referenced by ShopInstance::EnterRide().
int OnRideGuests::GetLoadingBatch (int start = -1) inline
Get a batch that is being loaded.
Parameters
start Index where the last search ended, or -1 to search from the start.
Returns
Index of a loading batch, or -1 if no loading batch exists.
Definition at line 102 of file guest_batches.h.
References BST_LOADING, and GetNextBatch().
int OnRideGuests::GetFinishedBatch (int start = -1) inline
Get a batch that has finished the ride.
Parameters
start Index where the last search ended, or -1 to search from the start.
Returns
Index of a finished batch, or -1 if no finished batch exists.
Definition at line 112 of file guest_batches.h.
References BST_FINISHED, and GetNextBatch().
Referenced by ShopInstance::OnAnimate().
int OnRideGuests::GetUnloadingBatch (int start = -1) inline
Get a batch that is being unloaded.
Parameters
start Index where the last search ended, or -1 to search from the start.
Returns
Index of an unloading batch, or -1 if no unloading batch exists.
Definition at line 122 of file guest_batches.h.
References BST_UNLOADING, and GetNextBatch().
void OnRideGuests::OnAnimate (int delay)
Time has passed, update the remaining times of the running batches.
Parameters
delay Amount of time that has passed (milli-seconds).
Definition at line 158 of file guest_batches.cpp.
References batches, BST_RUNNING, and GetNextBatch().
Referenced by ShopInstance::OnAnimate().
int OnRideGuests::GetNextBatch (BatchState state, int start) private
Get the index of the next batch with a given state.
Parameters
state State of the batch to look for.
start Last returned index number, or -1 to look from the first batch.
Returns
Index of the first batch with the given state after start, or -1 if no such batch exists.
Definition at line 142 of file guest_batches.cpp.
References batches, and GuestBatch::state.
Referenced by GetFinishedBatch(), GetFreeBatch(), GetLoadingBatch(), GetUnloadingBatch(), and OnAnimate().
The documentation for this class was generated from the following files:
guest_batches.h
guest_batches.cpp