FreeRCT: ShopInstance Class Reference
ShopInstance Class Reference
Shop 'ride'.
#include <shop_type.h>
Public Member Functions
ShopInstance (const ShopType *type)
Constructor of a shop 'ride'.
const ShopType * GetShopType () const
Get the shop type of the ride.
void GetSprites (uint16 voxel_number, uint8 orient, const ImageData *sprites[4]) const override
Get the sprites to display for the provided voxel number.
void SetRide (uint8 orientation, const XYZPoint16 &pos)
Update a ride instance with its position in the world.
uint8 GetEntranceDirections (const XYZPoint16 &vox) const override
Get the set edges with an entrance to the ride.
RideEntryResult EnterRide (int guest, TileEdge entry) override
The given guest tries to enter the ride.
XYZPoint32 GetExit (int guest, TileEdge entry_edge) override
Get the exit coordinates of the ride, is near the middle of a tile edge.
void RemoveAllPeople () override
Immediately remove all guests and staff which is inside the ride.
void OnAnimate (int delay) override
Some time has passed, update the state of the ride.
bool CanBeVisited (const XYZPoint16 &vox, TileEdge edge) const
Can the ride be visited, assuming it is approached from direction edge?
void SellItem (int item_index)
Sell an item to a customer.
ItemType GetSaleItemType (int item_index) const
Get the type of items sold by a ride.
Money GetSaleItemPrice (int item_index) const
Get the price of an item sold by a ride.
RideTypeKind GetKind () const
Get the kind of the ride.
const RideType * GetRideType () const
Get the ride type of the instance.
void OnNewMonth ()
Monthly update of the shop administration.
void OnNewDay ()
Daily update of breakages and maintenance.
void BuildRide ()
Switch the ride to being constructed.
void OpenRide ()
Open the ride for the public.
void CloseRide ()
Close the ride for the public.
void HandleBreakdown ()
Handle breakdowns of rides.
uint16 GetIndex () const
Get the ride instance index number.
Public Attributes
uint8 orientation
Orientation of the shop.
XYZPoint16 vox_pos
Position of the shop base voxel.
uint8 name [64]
Name of the ride, if it is instantiated.
uint8 state
State of the instance.
uint8 flags
Flags of the instance.
Recolouring recolours
Recolour map of the instance.
Money total_profit
Total profit of the ride.
Money total_sell_profit
Profit of selling items.
Money item_price [NUMBER_ITEM_TYPES_SOLD]
Selling price of each item type.
int64 item_count [NUMBER_ITEM_TYPES_SOLD]
Number of items sold for each type.
int16 breakdown_ctr
Breakdown counter.
uint16 reliability
Mean number of days in between breakdowns.
BreakdownState breakdown_state
Breakdown state for the ride.
Protected Attributes
const RideType * type
Ride type used.
Random rnd
Random number generator for determining ride breakage.
Private Attributes
OnRideGuests onride_guests
Guests in the ride.
Detailed Description
Shop 'ride'.
Definition at line 42 of file shop_type.h.
Constructor & Destructor Documentation
ShopInstance::ShopInstance (const ShopType * type)
Constructor of a shop 'ride'.
Parameters
type Kind of shop.
<
Todo:
Implement loading of guests into a batch.
Definition at line 140 of file shop_type.cpp.
References OnRideGuests::Configure(), ShopType::GetRideCapacity(), onride_guests, and orientation.
Member Function Documentation
const ShopType * ShopInstance::GetShopType () const
Get the shop type of the ride.
Returns
The shop type of the ride.
Definition at line 157 of file shop_type.cpp.
References RideType::kind, RTK_SHOP, and RideInstance::type.
Referenced by ShopPlacementManager::ComputeShopVoxel(), GetEntranceDirections(), Viewport::MarkVoxelDirty(), ShopManagerWindow::SetWidgetStringParameters(), and ShopManagerWindow::ShopManagerWindow().
void ShopInstance::GetSprites (uint16 voxel_number, uint8 orient, const ImageData * sprites[4]) const override virtual
Get the sprites to display for the provided voxel number.
Parameters
voxel_number Number of the voxel to draw (copied from the world voxel data).
orient View orientation.
sprites [out] Sprites to draw, from back to front, SO_PLATFORM_BACK, SO_RIDE, SO_RIDE_FRONT, and SO_PLATFORM_FRONT.
Implements RideInstance.
Definition at line 163 of file shop_type.cpp.
References RideType::GetView(), orientation, and RideInstance::type.
void ShopInstance::SetRide (uint8 orientation, const XYZPoint16 & pos)
Update a ride instance with its position in the world.
Parameters
orientation Orientation of the shop.
pos Position of the shop.
Definition at line 176 of file shop_type.cpp.
References _world, RideInstance::flags, VoxelWorld::GetTileOwner(), orientation, OWN_PARK, RIS_ALLOCATED, RideInstance::state, vox_pos, XYZPoint< CT >::x, and XYZPoint< CT >::y.
Referenced by ShopPlacementManager::ComputeShopVoxel().
uint8 ShopInstance::GetEntranceDirections (const XYZPoint16 & vox) const override virtual
Get the set edges with an entrance to the ride.
Parameters
vox Position of the voxel with the ride.
Returns
Bit set of TileEdge that allows entering the ride (seen from the ride).
Implements RideInstance.
Definition at line 186 of file shop_type.cpp.
References ShopType::flags, GetShopType(), orientation, ROL(), SHF_ENTRANCE_BITS, and vox_pos.
Referenced by ShopPlacementManager::PlaceShop().
RideEntryResult ShopInstance::EnterRide (int guest, TileEdge entry_edge) override virtual
The given guest tries to enter the ride.
Meaning and further handling of the ride visit depends on the return value.
If the call returns RER_REFUSED, the guest is not given entry (ride is full), it should be tried again at another time.
If the call returns RER_ENTERED, the guest is given access, and is now staying in the ride. The ride calls Guest::ExitRide when it is done.
If the call returns RER_DONE, the guest is given access, and the ride is also immediately visited (Guest::ExitRide is called before returning this answer).
Parameters
guest Number of the guest entering the ride.
entry_edge Edge of entering the ride. Value is passed back through Guest::ExitRide, to use as parameter in RideInstance::GetExit.
Returns
Whether the guest is accepted, and if so, if the guest is staying inside.
Implements RideInstance.
Definition at line 194 of file shop_type.cpp.
References _guests, GuestBatch::AddGuest(), Guest::ExitRide(), Guests::Get(), OnRideGuests::GetBatch(), OnRideGuests::GetFreeBatch(), OnRideGuests::num_batches, onride_guests, RER_DONE, RER_ENTERED, RER_REFUSED, GuestBatch::Start(), and TOILET_TIME.
XYZPoint32 ShopInstance::GetExit (int guest, TileEdge entry_edge) override virtual
Get the exit coordinates of the ride, is near the middle of a tile edge.
Parameters
guest Number of the guest querying the exit coordinates.
entry_edge Edge used for entering the ride.
Returns
World position of the exit.
Implements RideInstance.
Definition at line 214 of file shop_type.cpp.
References _exit_dxy, vox_pos, Point< CT >::x, XYZPoint< CT >::x, and Point< CT >::y.
void ShopInstance::OnAnimate (int delay) override virtual
Some time has passed, update the state of the ride.
Default implementation does nothing.
Parameters
delay Number of milliseconds that passed.
Reimplemented from RideInstance.
Definition at line 239 of file shop_type.cpp.
References _guests, OnRideGuests::batches, BST_EMPTY, GuestData::Clear(), GuestData::entry, Guest::ExitRide(), Guests::Get(), OnRideGuests::GetFinishedBatch(), GuestData::guest, GuestBatch::guests, GuestData::IsEmpty(), OnRideGuests::OnAnimate(), onride_guests, and GuestBatch::state.
bool RideInstance::CanBeVisited (const XYZPoint16 & vox, TileEdge edge) const inherited
Can the ride be visited, assuming it is approached from direction edge?
Parameters
vox Position of the voxel with the ride.
edge Direction of movement (exit direction of the neighbouring voxel).
Returns
Whether the ride can be visited.
Definition at line 230 of file ride_type.cpp.
References GB(), RideInstance::GetEntranceDirections(), RIS_OPEN, and RideInstance::state.
Referenced by Guest::ComputeExitDesire(), and Guest::VisitRideOnAnimate().
void RideInstance::SellItem (int item_index) inherited
Sell an item to a customer.
Parameters
item_index Index of the item being sold.
Definition at line 240 of file ride_type.cpp.
References _finances_manager, CHG_DISPLAY_OLD, FinancesManager::EarnShopSales(), RideInstance::GetIndex(), RideType::item_cost, RideInstance::item_count, RideInstance::item_price, NotifyChange(), NUMBER_ITEM_TYPES_SOLD, FinancesManager::PayShopStock(), RideInstance::total_profit, RideInstance::total_sell_profit, RideInstance::type, and WC_SHOP_MANAGER.
Referenced by Guest::BuyItem().
ItemType RideInstance::GetSaleItemType (int item_index) const inherited
Get the type of items sold by a ride.
Parameters
item_index Index in the items being sold (0 to NUMBER_ITEM_TYPES_SOLD).
Returns
Type of item sold.
Definition at line 259 of file ride_type.cpp.
References RideType::item_type, NUMBER_ITEM_TYPES_SOLD, and RideInstance::type.
Referenced by Guest::BuyItem(), Guest::SelectItem(), and Guest::WantToVisit().
Money RideInstance::GetSaleItemPrice (int item_index) const inherited
Get the price of an item sold by a ride.
Parameters
item_index Index in the items being sold (0 to NUMBER_ITEM_TYPES_SOLD).
Returns
Price to pay for the item.
Definition at line 270 of file ride_type.cpp.
References RideInstance::item_price, and NUMBER_ITEM_TYPES_SOLD.
Referenced by Guest::BuyItem(), Guest::SelectItem(), and ShopManagerWindow::SetWidgetStringParameters().
RideTypeKind RideInstance::GetKind () const inherited
Get the kind of the ride.
Returns
the kind of the ride.
Definition at line 171 of file ride_type.cpp.
References RideType::kind, and RideInstance::type.
Referenced by ShopPlacementManager::ComputeShopVoxel(), DrawRide(), Viewport::MarkVoxelDirty(), RidesManager::NewInstanceAdded(), SelectMouseMode::OnMouseButtonEvent(), ShopPlacementManager::PlaceShop(), ShowCoasterBuildGui(), ShowCoasterManagementGui(), and ShowShopManagementGui().
const RideType * RideInstance::GetRideType () const inherited
Get the ride type of the instance.
Returns
The ride type.
Definition at line 180 of file ride_type.cpp.
References RideInstance::type.
Referenced by RidesManager::NewInstanceAdded().
void RideInstance::OnNewMonth () inherited
Monthly update of the shop administration.
Definition at line 285 of file ride_type.cpp.
References _finances_manager, CHG_DISPLAY_OLD, RideInstance::flags, RideInstance::GetIndex(), RideType::monthly_cost, RideType::monthly_open_cost, NotifyChange(), FinancesManager::PayStaffWages(), RIF_MONTHLY_PAID, RIF_OPENED_PAID, RIS_OPEN, SB(), RideInstance::state, RideInstance::total_profit, RideInstance::type, and WC_SHOP_MANAGER.
Referenced by RidesManager::OnNewMonth().
void RideInstance::OnNewDay () inherited
Daily update of breakages and maintenance.
Definition at line 302 of file ride_type.cpp.
References RideInstance::HandleBreakdown().
Referenced by RidesManager::OnNewDay().
void RideInstance::BuildRide () inherited
Switch the ride to being constructed.
Precondition
The ride should not be open.
Definition at line 380 of file ride_type.cpp.
References RIS_BUILDING, RIS_OPEN, and RideInstance::state.
Referenced by RidesManager::NewInstanceAdded().
void RideInstance::OpenRide () inherited
Open the ride for the public.
Precondition
The ride is open.
Definition at line 340 of file ride_type.cpp.
References _finances_manager, BDS_UNOPENED, BDS_WILL_BREAK, RideInstance::breakdown_ctr, BREAKDOWN_GRACE_PERIOD, RideInstance::breakdown_state, CHG_DISPLAY_OLD, Random::Exponential(), RideInstance::flags, GB(), RideInstance::GetIndex(), RideType::monthly_cost, RideType::monthly_open_cost, NotifyChange(), FinancesManager::PayStaffWages(), RideInstance::reliability, RIF_MONTHLY_PAID, RIF_OPENED_PAID, RIS_CLOSED, RIS_OPEN, RideInstance::rnd, SB(), RideInstance::state, RideInstance::total_profit, RideInstance::type, and WC_SHOP_MANAGER.
Referenced by ShopManagerWindow::OnClick().
void RideInstance::CloseRide () inherited
Close the ride for the public.
Todo:
Currently closing is instantly, we may want to have a transition phase here.
Precondition
The ride is open.
Definition at line 371 of file ride_type.cpp.
References RIS_CLOSED, and RideInstance::state.
Referenced by RidesManager::NewInstanceAdded(), and ShopManagerWindow::OnClick().
void RideInstance::HandleBreakdown () inherited
Handle breakdowns of rides.
Definition at line 308 of file ride_type.cpp.
References BDS_BROKEN, BDS_NEEDS_NEW_CTR, BDS_UNOPENED, BDS_WILL_BREAK, RideInstance::breakdown_ctr, RideInstance::breakdown_state, Random::Exponential(), NOT_REACHED, RideInstance::reliability, RIS_OPEN, RideInstance::rnd, and RideInstance::state.
Referenced by RideInstance::OnNewDay().
uint16 RideInstance::GetIndex () const inherited
Get the ride instance index number.
Returns
Ride instance index.
Definition at line 459 of file ride_type.cpp.
References RidesManager::instances, lengthof, NOT_REACHED, and SRI_FULL_RIDES.
Referenced by CoasterBuildWindow::CoasterBuildWindow(), RideInstance::OnNewMonth(), RideInstance::OpenRide(), CoasterInstance::PlaceTrackPieceInAdditions(), CoasterInstance::RemoveTrackPieceInAdditions(), RideInstance::SellItem(), ShowCoasterBuildGui(), and ShowCoasterManagementGui().
Member Data Documentation
uint8 RideInstance::state inherited
State of the instance.
See also
RideInstanceState
Definition at line 164 of file ride_type.h.
Referenced by RideInstance::BuildRide(), RideInstance::CanBeVisited(), RideInstance::CloseRide(), Guest::ComputeExitDesire(), CoasterInstance::DecideRideState(), RideInstance::HandleBreakdown(), RidesManager::NewInstanceAdded(), ShopManagerWindow::OnClick(), RideInstance::OnNewMonth(), RideInstance::OpenRide(), RideInstance::RideInstance(), SetRide(), and ShopManagerWindow::SetShopToggleButtons().
uint8 RideInstance::flags inherited
Flags of the instance.
See also
RideInstanceFlags
Definition at line 165 of file ride_type.h.
Referenced by RideInstance::OnNewMonth(), RideInstance::OpenRide(), RideInstance::RideInstance(), and SetRide().
The documentation for this class was generated from the following files:
shop_type.h
shop_type.cpp