FreeRCT: TextString Class Reference
TextString Class Reference
A string with its name and its translations.
#include <language.h>
Public Member Functions
TextString ()
Default constructor of a TextString object.
void Clear ()
Drop all strings.
const uint8 * GetString () const
Get the string in the currently selected language.
Public Attributes
const char * name
Name of the string.
const uint8 * languages [LANGUAGE_COUNT]
The string in all languages.
Detailed Description
A string with its name and its translations.
Memory of the text is not owned by the class.
Definition at line 79 of file language.h.
Constructor & Destructor Documentation
TextString::TextString ()
Default constructor of a TextString object.
Definition at line 30 of file language.cpp.
References Clear().
Member Function Documentation
void TextString::Clear ()
Drop all strings.
Since the text is not owned by the class, no need to free the memory.
Definition at line 36 of file language.cpp.
References languages, lengthof, and name.
Referenced by TextString().
const uint8* TextString::GetString () const inline
Get the string in the currently selected language.
Returns
Text of this string in the currently selected language.
Definition at line 89 of file language.h.
References _current_language, LANG_EN_GB, LANGUAGE_COUNT, and languages.
Referenced by Language::GetText().
The documentation for this class was generated from the following files:
language.h
language.cpp