FreeRCT: ImageData Class Reference
ImageData Class Reference
Sprites and sprite handling
Image data of 8bpp images.
#include <sprite_data.h>
Public Member Functions
bool Load8bpp (RcdFileReader *rcd_file, size_t length)
Load image data from the RCD file.
bool Load32bpp (RcdFileReader *rcd_file, size_t length)
Load a 32bpp image.
uint32 GetPixel (uint16 xoffset, uint16 yoffset) const
Return the pixel-value of the provided position.
Public Attributes
uint32 flags
Flags of the image.
uint16 width
Width of the image.
uint16 height
Height of the image.
int16 xoffset
Horizontal offset of the image.
int16 yoffset
Vertical offset of the image.
uint32 * table
The jump table. For missing entries, INVALID_JUMP is used.
uint8 * data
The image data itself.
Detailed Description
Image data of 8bpp images.
Definition at line 28 of file sprite_data.h.
Member Function Documentation
bool ImageData::Load8bpp (RcdFileReader * rcd_file, size_t length)
Load image data from the RCD file.
Parameters
rcd_file File to load from.
length Length of the image data block.
Returns
Load was successful.
Precondition
File pointer is at first byte of the block.
Definition at line 45 of file sprite_data.cpp.
References data, RcdFileReader::GetBlob(), RcdFileReader::GetInt16(), RcdFileReader::GetUInt16(), RcdFileReader::GetUInt32(), height, INVALID_JUMP, table, width, xoffset, and yoffset.
Referenced by LoadImage().
bool ImageData::Load32bpp (RcdFileReader * rcd_file, size_t length)
Load a 32bpp image.
Parameters
rcd_file Input stream to read from.
length Length of the 32bpp block.
Returns
Exeit code, \0 means ok, every other number indicates an error.
Definition at line 110 of file sprite_data.cpp.
References data, RcdFileReader::GetBlob(), RcdFileReader::GetInt16(), RcdFileReader::GetUInt16(), height, width, xoffset, and yoffset.
Referenced by LoadImage().
uint32 ImageData::GetPixel (uint16 xoffset, uint16 yoffset) const
Return the pixel-value of the provided position.
Parameters
xoffset Horizontal offset in the sprite.
yoffset Vertical offset in the sprite.
Returns
Pixel value at the given position, or 0 if transparent.
Definition at line 181 of file sprite_data.cpp.
References _palette, data, flags, GB(), height, IFG_IS_8BPP, INVALID_JUMP, MakeRGBA(), OPAQUE, table, width, xoffset, and yoffset.
Referenced by PixelFinder::CollectVoxel().
Member Data Documentation
uint32 ImageData::flags
Flags of the image.
See also
ImageFlags
Definition at line 38 of file sprite_data.h.
Referenced by VideoSystem::BlitImages(), GetPixel(), and LoadImage().
The documentation for this class was generated from the following files:
sprite_data.h
sprite_data.cpp