FreeRCT: RideInstance Class Reference
RideInstance Class Reference abstract
A ride in the park.
#include <ride_type.h>
Public Member Functions
RideInstance (const RideType *rt)
Constructor of the base ride instance class.
virtual void GetSprites (uint16 voxel_number, uint8 orient, const ImageData *sprites[4]) const =0
Get the sprites to display for the provided voxel number.
virtual uint8 GetEntranceDirections (const XYZPoint16 &vox) const =0
Get the set edges with an entrance to the ride.
virtual RideEntryResult EnterRide (int guest, TileEdge entry_edge)=0
The given guest tries to enter the ride.
virtual XYZPoint32 GetExit (int guest, TileEdge entry_edge)=0
Get the exit coordinates of the ride, is near the middle of a tile edge.
virtual void RemoveAllPeople ()=0
Immediately remove all guests and staff which is inside the ride.
bool CanBeVisited (const XYZPoint16 &vox, TileEdge edge) const
Can the ride be visited, assuming it is approached from direction edge?
void SellItem (int item_index)
Sell an item to a customer.
ItemType GetSaleItemType (int item_index) const
Get the type of items sold by a ride.
Money GetSaleItemPrice (int item_index) const
Get the price of an item sold by a ride.
RideTypeKind GetKind () const
Get the kind of the ride.
const RideType * GetRideType () const
Get the ride type of the instance.
virtual void OnAnimate (int delay)
Some time has passed, update the state of the ride.
void OnNewMonth ()
Monthly update of the shop administration.
void OnNewDay ()
Daily update of breakages and maintenance.
void BuildRide ()
Switch the ride to being constructed.
void OpenRide ()
Open the ride for the public.
void CloseRide ()
Close the ride for the public.
void HandleBreakdown ()
Handle breakdowns of rides.
uint16 GetIndex () const
Get the ride instance index number.
Public Attributes
uint8 name [64]
Name of the ride, if it is instantiated.
uint8 state
State of the instance.
uint8 flags
Flags of the instance.
Recolouring recolours
Recolour map of the instance.
Money total_profit
Total profit of the ride.
Money total_sell_profit
Profit of selling items.
Money item_price [NUMBER_ITEM_TYPES_SOLD]
Selling price of each item type.
int64 item_count [NUMBER_ITEM_TYPES_SOLD]
Number of items sold for each type.
int16 breakdown_ctr
Breakdown counter.
uint16 reliability
Mean number of days in between breakdowns.
BreakdownState breakdown_state
Breakdown state for the ride.
Protected Attributes
const RideType * type
Ride type used.
Random rnd
Random number generator for determining ride breakage.
Detailed Description
A ride in the park.
Todo:
Add ride parts and other things that need to be stored with a ride.
Definition at line 134 of file ride_type.h.
Constructor & Destructor Documentation
RideInstance::RideInstance (const RideType * rt)
Constructor of the base ride instance class.
Parameters
rt Type of the ride instance.
Definition at line 146 of file ride_type.cpp.
References Recolouring::AssignRandomColours(), BDS_UNOPENED, breakdown_ctr, breakdown_state, flags, item_count, item_price, name, NUMBER_ITEM_TYPES_SOLD, RideType::recolours, recolours, reliability, RIS_ALLOCATED, state, and type.
Member Function Documentation
void RideInstance::GetSprites (uint16 voxel_number, uint8 orient, const ImageData * sprites[4]) const pure virtual
Get the sprites to display for the provided voxel number.
Parameters
voxel_number Number of the voxel to draw (copied from the world voxel data).
orient View orientation.
sprites [out] Sprites to draw, from back to front, SO_PLATFORM_BACK, SO_RIDE, SO_RIDE_FRONT, and SO_PLATFORM_FRONT.
Implemented in CoasterInstance, and ShopInstance.
Referenced by DrawRide().
uint8 RideInstance::GetEntranceDirections (const XYZPoint16 & vox) const pure virtual
Get the set edges with an entrance to the ride.
Parameters
vox Position of the voxel with the ride.
Returns
Bit set of TileEdge that allows entering the ride (seen from the ride).
Implemented in CoasterInstance, and ShopInstance.
Referenced by CanBeVisited().
RideEntryResult RideInstance::EnterRide (int guest, TileEdge entry_edge) pure virtual
The given guest tries to enter the ride.
Meaning and further handling of the ride visit depends on the return value.
If the call returns RER_REFUSED, the guest is not given entry (ride is full), it should be tried again at another time.
If the call returns RER_ENTERED, the guest is given access, and is now staying in the ride. The ride calls Guest::ExitRide when it is done.
If the call returns RER_DONE, the guest is given access, and the ride is also immediately visited (Guest::ExitRide is called before returning this answer).
Parameters
guest Number of the guest entering the ride.
entry_edge Edge of entering the ride. Value is passed back through Guest::ExitRide, to use as parameter in RideInstance::GetExit.
Returns
Whether the guest is accepted, and if so, if the guest is staying inside.
Implemented in CoasterInstance, and ShopInstance.
Referenced by Guest::VisitRideOnAnimate().
XYZPoint32 RideInstance::GetExit (int guest, TileEdge entry_edge) pure virtual
Get the exit coordinates of the ride, is near the middle of a tile edge.
Parameters
guest Number of the guest querying the exit coordinates.
entry_edge Edge used for entering the ride.
Returns
World position of the exit.
Implemented in CoasterInstance, and ShopInstance.
Referenced by Guest::ExitRide().
bool RideInstance::CanBeVisited (const XYZPoint16 & vox, TileEdge edge) const
Can the ride be visited, assuming it is approached from direction edge?
Parameters
vox Position of the voxel with the ride.
edge Direction of movement (exit direction of the neighbouring voxel).
Returns
Whether the ride can be visited.
Definition at line 230 of file ride_type.cpp.
References GB(), GetEntranceDirections(), RIS_OPEN, and state.
Referenced by Guest::ComputeExitDesire(), and Guest::VisitRideOnAnimate().
void RideInstance::SellItem (int item_index)
Sell an item to a customer.
Parameters
item_index Index of the item being sold.
Definition at line 240 of file ride_type.cpp.
References _finances_manager, CHG_DISPLAY_OLD, FinancesManager::EarnShopSales(), GetIndex(), RideType::item_cost, item_count, item_price, NotifyChange(), NUMBER_ITEM_TYPES_SOLD, FinancesManager::PayShopStock(), total_profit, total_sell_profit, type, and WC_SHOP_MANAGER.
Referenced by Guest::BuyItem().
ItemType RideInstance::GetSaleItemType (int item_index) const
Get the type of items sold by a ride.
Parameters
item_index Index in the items being sold (0 to NUMBER_ITEM_TYPES_SOLD).
Returns
Type of item sold.
Definition at line 259 of file ride_type.cpp.
References RideType::item_type, NUMBER_ITEM_TYPES_SOLD, and type.
Referenced by Guest::BuyItem(), Guest::SelectItem(), and Guest::WantToVisit().
Money RideInstance::GetSaleItemPrice (int item_index) const
Get the price of an item sold by a ride.
Parameters
item_index Index in the items being sold (0 to NUMBER_ITEM_TYPES_SOLD).
Returns
Price to pay for the item.
Definition at line 270 of file ride_type.cpp.
References item_price, and NUMBER_ITEM_TYPES_SOLD.
Referenced by Guest::BuyItem(), Guest::SelectItem(), and ShopManagerWindow::SetWidgetStringParameters().
RideTypeKind RideInstance::GetKind () const
Get the kind of the ride.
Returns
the kind of the ride.
Definition at line 171 of file ride_type.cpp.
References RideType::kind, and type.
Referenced by ShopPlacementManager::ComputeShopVoxel(), DrawRide(), Viewport::MarkVoxelDirty(), RidesManager::NewInstanceAdded(), SelectMouseMode::OnMouseButtonEvent(), ShopPlacementManager::PlaceShop(), ShowCoasterBuildGui(), ShowCoasterManagementGui(), and ShowShopManagementGui().
const RideType * RideInstance::GetRideType () const
Get the ride type of the instance.
Returns
The ride type.
Definition at line 180 of file ride_type.cpp.
References type.
Referenced by RidesManager::NewInstanceAdded().
void RideInstance::OnAnimate (int delay) virtual
Some time has passed, update the state of the ride.
Default implementation does nothing.
Parameters
delay Number of milliseconds that passed.
Reimplemented in CoasterInstance, and ShopInstance.
Definition at line 280 of file ride_type.cpp.
Referenced by RidesManager::OnAnimate().
void RideInstance::OnNewMonth ()
Monthly update of the shop administration.
Definition at line 285 of file ride_type.cpp.
References _finances_manager, CHG_DISPLAY_OLD, flags, GetIndex(), RideType::monthly_cost, RideType::monthly_open_cost, NotifyChange(), FinancesManager::PayStaffWages(), RIF_MONTHLY_PAID, RIF_OPENED_PAID, RIS_OPEN, SB(), state, total_profit, type, and WC_SHOP_MANAGER.
Referenced by RidesManager::OnNewMonth().
void RideInstance::OnNewDay ()
Daily update of breakages and maintenance.
Definition at line 302 of file ride_type.cpp.
References HandleBreakdown().
Referenced by RidesManager::OnNewDay().
void RideInstance::BuildRide ()
Switch the ride to being constructed.
Precondition
The ride should not be open.
Definition at line 380 of file ride_type.cpp.
References RIS_BUILDING, RIS_OPEN, and state.
Referenced by RidesManager::NewInstanceAdded().
void RideInstance::OpenRide ()
Open the ride for the public.
Precondition
The ride is open.
Definition at line 340 of file ride_type.cpp.
References _finances_manager, BDS_UNOPENED, BDS_WILL_BREAK, breakdown_ctr, BREAKDOWN_GRACE_PERIOD, breakdown_state, CHG_DISPLAY_OLD, Random::Exponential(), flags, GB(), GetIndex(), RideType::monthly_cost, RideType::monthly_open_cost, NotifyChange(), FinancesManager::PayStaffWages(), reliability, RIF_MONTHLY_PAID, RIF_OPENED_PAID, RIS_CLOSED, RIS_OPEN, rnd, SB(), state, total_profit, type, and WC_SHOP_MANAGER.
Referenced by ShopManagerWindow::OnClick().
void RideInstance::CloseRide ()
Close the ride for the public.
Todo:
Currently closing is instantly, we may want to have a transition phase here.
Precondition
The ride is open.
Definition at line 371 of file ride_type.cpp.
References RIS_CLOSED, and state.
Referenced by RidesManager::NewInstanceAdded(), and ShopManagerWindow::OnClick().
void RideInstance::HandleBreakdown ()
Handle breakdowns of rides.
Definition at line 308 of file ride_type.cpp.
References BDS_BROKEN, BDS_NEEDS_NEW_CTR, BDS_UNOPENED, BDS_WILL_BREAK, breakdown_ctr, breakdown_state, Random::Exponential(), NOT_REACHED, reliability, RIS_OPEN, rnd, and state.
Referenced by OnNewDay().
uint16 RideInstance::GetIndex () const
Get the ride instance index number.
Returns
Ride instance index.
Definition at line 459 of file ride_type.cpp.
References RidesManager::instances, lengthof, NOT_REACHED, and SRI_FULL_RIDES.
Referenced by CoasterBuildWindow::CoasterBuildWindow(), OnNewMonth(), OpenRide(), CoasterInstance::PlaceTrackPieceInAdditions(), CoasterInstance::RemoveTrackPieceInAdditions(), SellItem(), ShowCoasterBuildGui(), and ShowCoasterManagementGui().
Member Data Documentation
uint8 RideInstance::state
State of the instance.
See also
RideInstanceState
Definition at line 164 of file ride_type.h.
Referenced by BuildRide(), CanBeVisited(), CloseRide(), Guest::ComputeExitDesire(), CoasterInstance::DecideRideState(), HandleBreakdown(), RidesManager::NewInstanceAdded(), ShopManagerWindow::OnClick(), OnNewMonth(), OpenRide(), RideInstance(), ShopInstance::SetRide(), and ShopManagerWindow::SetShopToggleButtons().
uint8 RideInstance::flags
Flags of the instance.
See also
RideInstanceFlags
Definition at line 165 of file ride_type.h.
Referenced by OnNewMonth(), OpenRide(), RideInstance(), and ShopInstance::SetRide().
The documentation for this class was generated from the following files:
ride_type.h
ride_type.cpp