FreeRCT: FilePattern Class Reference
FilePattern Class Reference
Class for storage of a filename pattern of the form "prefix{seq(first..last,length)}suffix".
#include <nodes.h>
Public Member Functions
void SetFilename (const std::string &fname)
Store the filename in the file pattern class, and parse the name for the "{seq(first..last,length)}" pattern.
int GetCount () const
Get the number of filenames represented by the class.
std::string MakeFilename (int index) const
Construct the index-th filename.
Public Attributes
std::string prefix
Common prefix part of the name.
std::string suffix
Common suffix part of the name.
int first
First number to insert.
int last
Last number to insert.
int length
Length of the number part, 0 means no number and suffix available, -1 means no filename at all.
Detailed Description
Class for storage of a filename pattern of the form "prefix{seq(first..last,length)}suffix".
Definition at line 114 of file nodes.h.
Member Function Documentation
void FilePattern::SetFilename (const std::string & fname)
Store the filename in the file pattern class, and parse the name for the "{seq(first..last,length)}" pattern.
Parameters
fname Filename to store.
Definition at line 194 of file nodes.cpp.
References first, last, length, prefix, SkipChar(), SkipDotDot(), SkipNumber(), SkipSeq(), SkipToCurOpen(), and suffix.
int FilePattern::GetCount () const
Get the number of filenames represented by the class.
Returns
Number of unique filenames available in the class.
Definition at line 233 of file nodes.cpp.
References first, last, and length.
Referenced by SpriteFilesBlock::GetSubNode().
std::string FilePattern::MakeFilename (int index) const
Construct the index-th filename.
Parameters
index Index number of the filename to generate from the pattern.
Returns
The filename expressed by 'seq' at the provided index.
Definition at line 245 of file nodes.cpp.
References first, length, lengthof, prefix, and suffix.
Referenced by SpriteFilesBlock::GetSubNode().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp