FreeRCT: DefaultMouseMode Class Reference
DefaultMouseMode Class Reference
Default mouse mode, selected when no other mouse mode is available.
#include <viewport.h>
Public Member Functions
bool MayActivateMode () override
Query the mode whether it can be enabled.
void ActivateMode (const Point16 &pos) override
Activate the mouse mode.
void LeaveMode () override
Notification that the mouse mode is about to be disabled.
bool EnableCursors () override
Control display of cursors in the mouse mode.
virtual void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos)
The mouse moved while in this mouse mode.
virtual void OnMouseButtonEvent (Viewport *vp, uint8 state)
A mouse click was detected.
virtual void OnMouseWheelEvent (Viewport *vp, int direction)
A mouse wheelie event has been detected.
Public Attributes
const WindowTypes wtype
Type of window associated with this mouse mode.
const ViewportMouseMode mode
Mouse mode implemented by the object.
Detailed Description
Default mouse mode, selected when no other mouse mode is available.
Definition at line 310 of file viewport.h.
Member Function Documentation
bool DefaultMouseMode::MayActivateMode () override virtual
Query the mode whether it can be enabled.
Method may be called at any moment (or more often than once). Answering true does not mean the mouse mode will be activated.
Returns
Whether the mode may be enabled.
Implements MouseMode.
Definition at line 1663 of file viewport.cpp.
void DefaultMouseMode::ActivateMode (const Point16 & pos) override virtual
Activate the mouse mode.
Parameters
pos Last known mouse position.
Implements MouseMode.
Definition at line 1668 of file viewport.cpp.
void DefaultMouseMode::LeaveMode () override virtual
Notification that the mouse mode is about to be disabled.
Implements MouseMode.
Definition at line 1672 of file viewport.cpp.
bool DefaultMouseMode::EnableCursors () override virtual
Control display of cursors in the mouse mode.
Returns
true when cursors should be displayed, false otherwise.
Implements MouseMode.
Definition at line 1676 of file viewport.cpp.
void MouseMode::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) virtual inherited
The mouse moved while in this mouse mode.
Parameters
vp Viewport object.
old_pos Previous position.
pos Current position.
Reimplemented in TileTerraformMouseMode, CoasterBuildMode, ShopPlacementManager, FenceBuildManager, PathBuildManager, and SelectMouseMode.
Definition at line 1637 of file viewport.cpp.
Referenced by Viewport::OnMouseMoveEvent().
void MouseMode::OnMouseButtonEvent (Viewport * vp, uint8 state) virtual inherited
A mouse click was detected.
Parameters
vp Viewport object.
state State of the mouse buttons.
See also
MouseButtons
Reimplemented in TileTerraformMouseMode, CoasterBuildMode, ShopPlacementManager, FenceBuildManager, PathBuildManager, and SelectMouseMode.
Definition at line 1646 of file viewport.cpp.
Referenced by Viewport::OnMouseButtonEvent().
void MouseMode::OnMouseWheelEvent (Viewport * vp, int direction) virtual inherited
A mouse wheelie event has been detected.
Parameters
vp Viewport object.
direction Direction of movement.
Reimplemented in TileTerraformMouseMode, and FenceBuildManager.
Definition at line 1655 of file viewport.cpp.
Referenced by Viewport::OnMouseWheelEvent().
The documentation for this class was generated from the following files:
viewport.h
viewport.cpp