FreeRCT: CoasterInstance Class Reference
CoasterInstance Class Reference
A roller coaster in the world.
#include <coaster.h>
Public Member Functions
CoasterInstance (const CoasterType *rt, const CarType *car_type)
Constructor of a roller coaster instance.
bool IsAccessible ()
Can the user click in the world to re-open the coaster instance window for this coaster?
void OnAnimate (int delay) override
Some time has passed, update the state of the ride.
const CoasterType * GetCoasterType () const
Get the coaster type of this ride.
void GetSprites (uint16 voxel_number, uint8 orient, const ImageData *sprites[4]) const override
Get the sprites to display for the provided voxel number.
uint8 GetEntranceDirections (uint16 xvox, uint16 yvox, uint8 zvox) const override
Get the set edges with an entrance to the ride.
RideInstanceState DecideRideState ()
Check the state of the coaster ride, and set the state flag.
bool MakePositionedPiecesLooping (bool *modified)
Try to make a loop with the current set of positioned track pieces.
int GetFirstPlacedTrackPiece () const
Retrieve the first placed track piece, if available.
int AddPositionedPiece (const PositionedTrackPiece &placed)
Try to add a positioned track piece to the coaster instance.
void RemovePositionedPiece (PositionedTrackPiece &piece)
Try to remove a positioned track piece from the coaster instance.
int FindSuccessorPiece (uint16 x, uint16 y, uint8 z, uint8 entry_connect, int start=0, int end=MAX_PLACED_TRACK_PIECES)
Find the first placed track piece at a given position with a given entry connection.
int FindSuccessorPiece (const PositionedTrackPiece &placed)
Find the first placed track piece that follows a provided placed track piece.
int FindPredecessorPiece (const PositionedTrackPiece &placed)
Find the first placed track piece that precedes a provided placed track piece.
void PlaceTrackPieceInAdditions (const PositionedTrackPiece &piece)
Add the positioned track piece to _additions.
void RemoveTrackPieceInAdditions (const PositionedTrackPiece &piece)
Add 'removal' of the positioned track piece to _additions.
int GetMaxNumberOfTrains () const
Retrieve how many trains can be used at this roller coaster.
void SetNumberOfTrains (int number_trains)
Set the number of trains to use at this coaster.
int GetNumberOfTrains () const
Get the current number of trains that ride on the coaster.
int GetMaxNumberOfCars () const
Get the maximum number of cars of a train.
void SetNumberOfCars (int number_cars)
Set the number of cars in a single train.
int GetNumberOfCars () const
Retrieve the number of cars available in a single train of the coaster.
bool CanBeVisited (uint16 xvox, uint16 yvox, uint8 zvox, TileEdge edge) const
Can the ride be visited, assuming the shop is approached from direction edge?
void SellItem (int item_index)
Sell an item to a customer.
ItemType GetSaleItemType (int item_index) const
Get the type of items sold by a ride.
Money GetSaleItemPrice (int item_index) const
Get the price of an item sold by a ride.
RideTypeKind GetKind () const
Get the kind of the ride.
const RideType * GetRideType () const
Get the ride type of the instance.
void OnNewMonth ()
Monthly update of the shop administration.
void OnNewDay ()
Daily update of breakages and maintenance.
void BuildRide ()
Switch the ride to being constructed.
void OpenRide ()
Open the ride for the public.
void CloseRide ()
Close the ride for the public.
void HandleBreakdown ()
Handle breakdowns of rides.
uint16 GetIndex () const
Get the ride instance index number.
Public Attributes
PositionedTrackPiece * pieces
Positioned track pieces.
int capacity
Number of entries in the pieces.
uint32 coaster_length
Total length of the roller coaster track (in 1/256 pixels).
CoasterTrain trains [4]
Trains at the roller coaster (with an arbitrary max size). A train without cars means the train is not used.
const CarType * car_type
Type of cars running at the coaster.
uint8 name [64]
Name of the ride, if it is instantiated.
uint8 state
State of the instance.
uint8 flags
Flags of the instance.
Recolouring recolours
Recolour map of the instance.
Money total_profit
Total profit of the ride.
Money total_sell_profit
Profit of selling items.
Money item_price [NUMBER_ITEM_TYPES_SOLD]
Selling price of each item type.
int64 item_count [NUMBER_ITEM_TYPES_SOLD]
Number of items sold for each type.
int16 breakdown_ctr
Breakdown counter.
uint16 reliability
Mean number of days in between breakdowns.
BreakdownState breakdown_state
Breakdown state for the ride.
Protected Attributes
const RideType * type
Ride type used.
Random rnd
Random number generator for determining ride breakage.
Detailed Description
A roller coaster in the world.
Since roller coaster rides need to be constructed by the user first, an instance can exist without being able to open for public.
Definition at line 176 of file coaster.h.
Constructor & Destructor Documentation
CoasterInstance::CoasterInstance (const CoasterType * ct, const CarType * car_type)
Constructor of a roller coaster instance.
Parameters
ct Coaster type being built.
car_type Kind of cars used for the coaster.
Definition at line 524 of file coaster.cpp.
References capacity, car_type, CoasterTrain::coaster, CoasterTrain::cur_piece, RideType::item_cost, RideInstance::item_price, lengthof, MAX_PLACED_TRACK_PIECES, NUMBER_ITEM_TYPES_SOLD, pieces, and trains.
Member Function Documentation
bool CoasterInstance::IsAccessible ()
Can the user click in the world to re-open the coaster instance window for this coaster?
Returns
true if an object in the world exists, false otherwise.
Definition at line 546 of file coaster.cpp.
References GetFirstPlacedTrackPiece().
void CoasterInstance::OnAnimate (int delay) override virtual
Some time has passed, update the state of the ride.
Default implementation does nothing.
Parameters
delay Number of milliseconds that passed.
Reimplemented from RideInstance.
Definition at line 551 of file coaster.cpp.
References CoasterTrain::cars, lengthof, CoasterTrain::OnAnimate(), and trains.
const CoasterType* CoasterInstance::GetCoasterType () const inline
Get the coaster type of this ride.
Returns
The coaster type of this ride.
Definition at line 189 of file coaster.h.
References RideInstance::type.
Referenced by GetMaxNumberOfCars(), GetMaxNumberOfTrains(), GetSprites(), PlaceTrackPieceInAdditions(), and CoasterBuildWindow::SetupSelection().
void CoasterInstance::GetSprites (uint16 voxel_number, uint8 orient, const ImageData * sprites[4]) const override virtual
Get the sprites to display for the provided voxel number.
Parameters
voxel_number Number of the voxel to draw (copied from the world voxel data).
orient View orientation.
sprites [out] Sprites to draw, from back to front, SO_PLATFORM_BACK, SO_RIDE, SO_RIDE_FRONT, and SO_PLATFORM_FRONT.
Implements RideInstance.
Definition at line 560 of file coaster.cpp.
References TrackVoxel::back, CPT_COUNT, EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, TrackVoxel::front, GetCoasterType(), TrackVoxel::GetPlatformDirection(), TrackVoxel::HasPlatform(), CoasterPlatform::ne_sw_back, CoasterPlatform::ne_sw_front, NOT_REACHED, CoasterPlatform::nw_se_back, CoasterPlatform::nw_se_front, CoasterType::platform_type, CoasterPlatform::se_nw_back, CoasterPlatform::se_nw_front, CoasterPlatform::sw_ne_back, CoasterPlatform::sw_ne_front, and CoasterType::voxels.
uint8 CoasterInstance::GetEntranceDirections (uint16 xvox, uint16 yvox, uint8 zvox) const override virtual
Get the set edges with an entrance to the ride.
Parameters
xvox X position of the voxel with the ride.
yvox Y position of the voxel with the ride.
zvox Z position of the voxel with the ride.
Returns
Bit set of TileEdge that allows entering the ride (seen from the ride).
Todo:
add entrance bits for the coaster.
Implements RideInstance.
Definition at line 600 of file coaster.cpp.
RideInstanceState CoasterInstance::DecideRideState ()
Check the state of the coaster ride, and set the state flag.
Returns
The new coaster instance state.
Definition at line 609 of file coaster.cpp.
References GetNumberOfTrains(), MakePositionedPiecesLooping(), RIS_BUILDING, RIS_CLOSED, RIS_OPEN, RIS_TESTING, SetNumberOfCars(), SetNumberOfTrains(), and RideInstance::state.
Referenced by ShowCoasterManagementGui().
bool CoasterInstance::MakePositionedPiecesLooping (bool * modified)
Try to make a loop with the current set of positioned track pieces.
Parameters
modified [out] If not nullptr, false after the call denotes the pieces array was not modified (while true denotes it was changed).
Returns
Whether the current set of positioned track pieces can be used as a ride.
Note
May re-order positioned track pieces.
Definition at line 690 of file coaster.cpp.
References PositionedTrackPiece::CanBeSuccessor(), capacity, coaster_length, PositionedTrackPiece::distance_base, FindSuccessorPiece(), PositionedTrackPiece::GetEndX(), PositionedTrackPiece::GetEndY(), PositionedTrackPiece::GetEndZ(), PositionedTrackPiece::piece, and pieces.
Referenced by DecideRideState().
int CoasterInstance::GetFirstPlacedTrackPiece () const
Retrieve the first placed track piece, if available.
Returns
The index of the first placed track piece, or -1 if no such piece available.
Definition at line 630 of file coaster.cpp.
References capacity, and pieces.
Referenced by CoasterBuildWindow::CoasterBuildWindow(), and IsAccessible().
int CoasterInstance::AddPositionedPiece (const PositionedTrackPiece & placed)
Try to add a positioned track piece to the coaster instance.
Parameters
placed New positioned track piece to add.
Returns
If the new piece can be added, its index is returned, else -1.
Definition at line 743 of file coaster.cpp.
References capacity, PositionedTrackPiece::IsOnWorld(), PositionedTrackPiece::piece, and pieces.
Referenced by CoasterBuildWindow::BuildTrackPiece().
void CoasterInstance::RemovePositionedPiece (PositionedTrackPiece & piece)
Try to remove a positioned track piece from the coaster instance.
Parameters
piece Positioned track piece to remove.
Definition at line 760 of file coaster.cpp.
References PositionedTrackPiece::piece, and RemoveTrackPieceInAdditions().
Referenced by CoasterBuildWindow::OnClick().
int CoasterInstance::FindSuccessorPiece (uint16 x, uint16 y, uint8 z, uint8 entry_connect, int start = 0, int end = MAX_PLACED_TRACK_PIECES)
Find the first placed track piece at a given position with a given entry connection.
Parameters
x Required X position.
y Required Y position.
z Required Z position.
entry_connect Required entry connection.
start First index to search.
end End of the search (one beyond the last positioned track piece to search).
Returns
Index of the requested positioned track piece if it exists, else -1.
Definition at line 648 of file coaster.cpp.
References MAX_PLACED_TRACK_PIECES, and pieces.
Referenced by CoasterBuildWindow::CoasterBuildWindow(), FindSuccessorPiece(), MakePositionedPiecesLooping(), CoasterBuildWindow::OnChange(), and CoasterBuildWindow::OnClick().
int CoasterInstance::FindSuccessorPiece (const PositionedTrackPiece & placed)
Find the first placed track piece that follows a provided placed track piece.
Parameters
placed Already placed track piece.
Returns
Index of the requested positioned track piece if it exists, else -1.
Definition at line 663 of file coaster.cpp.
References FindSuccessorPiece(), PositionedTrackPiece::GetEndX(), PositionedTrackPiece::GetEndY(), PositionedTrackPiece::GetEndZ(), and PositionedTrackPiece::piece.
int CoasterInstance::FindPredecessorPiece (const PositionedTrackPiece & placed)
Find the first placed track piece that precedes a provided placed track piece.
Parameters
placed Already placed track piece.
Returns
Index of the requested positioned track piece if it exists, else -1.
Definition at line 673 of file coaster.cpp.
References PositionedTrackPiece::CanBeSuccessor(), and capacity.
Referenced by CoasterBuildWindow::OnClick().
void CoasterInstance::PlaceTrackPieceInAdditions (const PositionedTrackPiece & placed)
Add the positioned track piece to _additions.
Parameters
placed Track piece to place.
Precondition
placed->CanBePlaced() should hold.
Definition at line 772 of file coaster.cpp.
References _additions, PositionedTrackPiece::CanBePlaced(), TrackVoxel::dx, TrackVoxel::dy, TrackVoxel::dz, GetCoasterType(), WorldAdditions::GetCreateVoxel(), RideInstance::GetIndex(), CoasterType::GetTrackVoxelIndex(), PositionedTrackPiece::piece, Voxel::SetInstance(), Voxel::SetInstanceData(), SRI_FULL_RIDES, SRI_LAST, PositionedTrackPiece::x_base, PositionedTrackPiece::y_base, and PositionedTrackPiece::z_base.
Referenced by CoasterBuildWindow::BuildTrackPiece(), and CoasterBuildMode::UpdateDisplay().
void CoasterInstance::RemoveTrackPieceInAdditions (const PositionedTrackPiece & placed)
Add 'removal' of the positioned track piece to _additions.
Parameters
placed Track piece to be removed.
Definition at line 793 of file coaster.cpp.
References _additions, TrackVoxel::dx, TrackVoxel::dy, TrackVoxel::dz, WorldAdditions::GetCreateVoxel(), RideInstance::GetIndex(), Voxel::GetInstance(), PositionedTrackPiece::piece, Voxel::SetInstance(), Voxel::SetInstanceData(), SRI_FREE, PositionedTrackPiece::x_base, PositionedTrackPiece::y_base, and PositionedTrackPiece::z_base.
Referenced by RemovePositionedPiece().
int CoasterInstance::GetMaxNumberOfTrains () const
Retrieve how many trains can be used at this roller coaster.
Returns
The maximum number of trains at this coaster.
Todo:
Take the positioned track pieces of the coaster into account.
Definition at line 810 of file coaster.cpp.
References GetCoasterType(), lengthof, CoasterType::max_number_trains, and trains.
Referenced by SetNumberOfTrains().
void CoasterInstance::SetNumberOfTrains (int number_trains)
Set the number of trains to use at this coaster.
Parameters
number_trains Number of trains to use (0 means 'default').
Precondition
If not default, number_trains should be at least 1, and at most GetMaxNumberOfTrains.
Todo:
Needs a better value, coaster trains do not stack.
Definition at line 821 of file coaster.cpp.
References CoasterTrain::back_position, CoasterTrain::cur_piece, GetMaxNumberOfTrains(), GetNumberOfCars(), lengthof, pieces, CoasterTrain::SetLength(), CoasterTrain::speed, and trains.
Referenced by DecideRideState().
int CoasterInstance::GetNumberOfTrains () const
Get the current number of trains that ride on the coaster.
Returns
current number of trains on the coaster.
Definition at line 841 of file coaster.cpp.
References lengthof, and trains.
Referenced by DecideRideState().
int CoasterInstance::GetMaxNumberOfCars () const
Get the maximum number of cars of a train.
Returns
The maximum number of cars in a train.
Todo:
Take coaster length and number of trains into account.
Take car type into account.
Definition at line 857 of file coaster.cpp.
References GetCoasterType(), and CoasterType::max_number_cars.
Referenced by SetNumberOfCars().
void CoasterInstance::SetNumberOfCars (int number_cars)
Set the number of cars in a single train.
Parameters
number_cars Number of cars of a single train.
Precondition
number_cars should be at least 1 and at most GetMaxNumberOfCars.
Definition at line 868 of file coaster.cpp.
References CoasterTrain::cars, GetMaxNumberOfCars(), lengthof, CoasterTrain::SetLength(), and trains.
Referenced by DecideRideState().
int CoasterInstance::GetNumberOfCars () const
Retrieve the number of cars available in a single train of the coaster.
Returns
Number of cars in a train.
Definition at line 881 of file coaster.cpp.
References CoasterTrain::cars, and trains.
Referenced by SetNumberOfTrains().
bool RideInstance::CanBeVisited (uint16 xvox, uint16 yvox, uint8 zvox, TileEdge edge) const inherited
Can the ride be visited, assuming the shop is approached from direction edge?
Parameters
xvox X position of the voxel with the ride.
yvox Y position of the voxel with the ride.
zvox Z position of the voxel with the ride.
edge Direction of movement (exit direction of the neighbouring voxel).
Returns
Whether the ride can be visited.
Definition at line 208 of file ride_type.cpp.
References GB(), RideInstance::GetEntranceDirections(), RIS_OPEN, and RideInstance::state.
Referenced by Guest::ComputeExitDesire(), and Person::OnAnimate().
void RideInstance::SellItem (int item_index) inherited
Sell an item to a customer.
Parameters
item_index Index of the item being sold.
Definition at line 218 of file ride_type.cpp.
References _finances_manager, CHG_DISPLAY_OLD, FinancesManager::EarnShopSales(), RideInstance::GetIndex(), RideType::item_cost, RideInstance::item_count, RideInstance::item_price, NotifyChange(), NUMBER_ITEM_TYPES_SOLD, FinancesManager::PayShopStock(), RideInstance::total_profit, RideInstance::total_sell_profit, RideInstance::type, and WC_SHOP_MANAGER.
Referenced by Guest::VisitShop().
ItemType RideInstance::GetSaleItemType (int item_index) const inherited
Get the type of items sold by a ride.
Parameters
item_index Index in the items being sold (0 to NUMBER_ITEM_TYPES_SOLD).
Returns
Type of item sold.
Definition at line 237 of file ride_type.cpp.
References RideType::item_type, NUMBER_ITEM_TYPES_SOLD, and RideInstance::type.
Referenced by Guest::VisitShop(), and Guest::WantToVisit().
Money RideInstance::GetSaleItemPrice (int item_index) const inherited
Get the price of an item sold by a ride.
Parameters
item_index Index in the items being sold (0 to NUMBER_ITEM_TYPES_SOLD).
Returns
Price to pay for the item.
Definition at line 248 of file ride_type.cpp.
References RideInstance::item_price, and NUMBER_ITEM_TYPES_SOLD.
Referenced by ShopManagerWindow::SetWidgetStringParameters(), and Guest::VisitShop().
RideTypeKind RideInstance::GetKind () const inherited
Get the kind of the ride.
Returns
the kind of the ride.
Definition at line 169 of file ride_type.cpp.
References RideType::kind, and RideInstance::type.
Referenced by ShopPlacementManager::ComputeShopVoxel(), DrawRide(), Viewport::MarkVoxelDirty(), RidesManager::NewInstanceAdded(), SelectMouseMode::OnMouseButtonEvent(), ShopPlacementManager::PlaceShop(), ShowCoasterBuildGui(), ShowCoasterManagementGui(), and ShowShopManagementGui().
const RideType * RideInstance::GetRideType () const inherited
Get the ride type of the instance.
Returns
The ride type.
Definition at line 178 of file ride_type.cpp.
References RideInstance::type.
Referenced by RidesManager::NewInstanceAdded().
void RideInstance::OnNewMonth () inherited
Monthly update of the shop administration.
Definition at line 263 of file ride_type.cpp.
References _finances_manager, CHG_DISPLAY_OLD, RideInstance::flags, RideInstance::GetIndex(), RideType::monthly_cost, RideType::monthly_open_cost, NotifyChange(), FinancesManager::PayStaffWages(), RIF_MONTHLY_PAID, RIF_OPENED_PAID, RIS_OPEN, SB(), RideInstance::state, RideInstance::total_profit, RideInstance::type, and WC_SHOP_MANAGER.
Referenced by RidesManager::OnNewMonth().
void RideInstance::OnNewDay () inherited
Daily update of breakages and maintenance.
Definition at line 280 of file ride_type.cpp.
References RideInstance::HandleBreakdown().
Referenced by RidesManager::OnNewDay().
void RideInstance::BuildRide () inherited
Switch the ride to being constructed.
Precondition
The ride should not be open.
Definition at line 358 of file ride_type.cpp.
References RIS_BUILDING, RIS_OPEN, and RideInstance::state.
Referenced by RidesManager::NewInstanceAdded().
void RideInstance::OpenRide () inherited
Open the ride for the public.
Precondition
The ride is open.
Definition at line 318 of file ride_type.cpp.
References _finances_manager, BDS_UNOPENED, BDS_WILL_BREAK, RideInstance::breakdown_ctr, BREAKDOWN_GRACE_PERIOD, RideInstance::breakdown_state, CHG_DISPLAY_OLD, Random::Exponential(), RideInstance::flags, GB(), RideInstance::GetIndex(), RideType::monthly_cost, RideType::monthly_open_cost, NotifyChange(), FinancesManager::PayStaffWages(), RideInstance::reliability, RIF_MONTHLY_PAID, RIF_OPENED_PAID, RIS_CLOSED, RIS_OPEN, RideInstance::rnd, SB(), RideInstance::state, RideInstance::total_profit, RideInstance::type, and WC_SHOP_MANAGER.
Referenced by ShopManagerWindow::OnClick().
void RideInstance::CloseRide () inherited
Close the ride for the public.
Todo:
Currently closing is instantly, we may want to have a transition phase here.
Precondition
The ride is open.
Definition at line 349 of file ride_type.cpp.
References RIS_CLOSED, and RideInstance::state.
Referenced by RidesManager::NewInstanceAdded(), and ShopManagerWindow::OnClick().
void RideInstance::HandleBreakdown () inherited
Handle breakdowns of rides.
Definition at line 286 of file ride_type.cpp.
References BDS_BROKEN, BDS_NEEDS_NEW_CTR, BDS_UNOPENED, BDS_WILL_BREAK, RideInstance::breakdown_ctr, RideInstance::breakdown_state, Random::Exponential(), NOT_REACHED, RideInstance::reliability, RIS_OPEN, RideInstance::rnd, and RideInstance::state.
Referenced by RideInstance::OnNewDay().
uint16 RideInstance::GetIndex () const inherited
Get the ride instance index number.
Returns
Ride instance index.
Definition at line 437 of file ride_type.cpp.
References RidesManager::instances, lengthof, NOT_REACHED, and SRI_FULL_RIDES.
Referenced by CoasterBuildWindow::CoasterBuildWindow(), RideInstance::OnNewMonth(), RideInstance::OpenRide(), PlaceTrackPieceInAdditions(), RemoveTrackPieceInAdditions(), RideInstance::SellItem(), ShowCoasterBuildGui(), and ShowCoasterManagementGui().
Member Data Documentation
uint8 RideInstance::state inherited
State of the instance.
See also
RideInstanceState
Definition at line 149 of file ride_type.h.
Referenced by RideInstance::BuildRide(), RideInstance::CanBeVisited(), RideInstance::CloseRide(), Guest::ComputeExitDesire(), DecideRideState(), RideInstance::HandleBreakdown(), RidesManager::NewInstanceAdded(), ShopManagerWindow::OnClick(), RideInstance::OnNewMonth(), RideInstance::OpenRide(), RideInstance::RideInstance(), ShopInstance::SetRide(), and ShopManagerWindow::SetShopToggleButtons().
uint8 RideInstance::flags inherited
Flags of the instance.
See also
RideInstanceFlags
Definition at line 150 of file ride_type.h.
Referenced by RideInstance::OnNewMonth(), RideInstance::OpenRide(), RideInstance::RideInstance(), and ShopInstance::SetRide().
The documentation for this class was generated from the following files:
coaster.h
coaster.cpp