FreeRCT: DataWidget Class Reference
DataWidget Class Reference
Widgets and supporting functions of the program
Data widget.
#include <widget.h>
Public Member Functions
DataWidget (WidgetType wtype)
Data widget constructor.
void SetupMinimalSize (GuiWindow *w, BaseWidget **wid_array) override
Compute smallest size of the widget.
void Draw (const GuiWindow *w) override
Draw a DataWidget.
virtual void AutoRaiseButtons (const Point32 &base) override
Raise all push buttons in the tree.
bool IsChecked () const
Is the 'checked' flag on?
bool IsPressed () const
Is the 'pressed' flag on?
bool IsShaded () const
Is the 'shaded' flag on?
void SetChecked (bool value)
Set the 'checked' flag to the new value.
void SetPressed (bool value)
Set the 'pressed' flag to the new value.
void SetShaded (bool value)
Set the 'shaded' flag to the new value.
virtual void SetSmallestSizePosition (const Rectangle16 &rect)
Set the minimal size of the widget, and assign rect to the current position and size.
virtual BaseWidget * GetWidgetByPosition (const Point16 &pt)
Get the widget at the given relative window position.
void MarkDirty (const Point32 &base) const
Denote the widget as being needed to redraw.
Public Attributes
uint16 value
String number or sprite id.
int value_width
Width of the image or the string.
int value_height
Height of the image or the string.
uint8 flags
Flags of the leaf widget.
ColourRange colour
Colour of the widget.
StringID tooltip
Tool-tip of the widget.
WidgetType wtype
Widget type.
WidgetNumber number
Widget number.
uint16 smallest_x
Original horizontal size.
uint16 smallest_y
Original vertical size.
uint16 min_x
Minimal horizontal size.
uint16 min_y
Minimal vertical size.
Rectangle16 pos
Current position and size (relative to window top-left edge).
uint16 fill_x
Horizontal fill step.
uint16 fill_y
Vertical fill step.
uint16 resize_x
Horizontal resize step.
uint16 resize_y
Vertical resize step.
uint8 paddings [PAD_COUNT]
Padding.
Protected Member Functions
void SetWidget (BaseWidget **wid_array)
Add the widget to the widget array wid_array.
void InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert)
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
void InitMinimalSize (const BorderSpriteData *bsd, uint16 content_width, uint16 content_height)
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Detailed Description
Data widget.
Implements WT_TITLEBAR, WT_LEFT_TEXT, WT_CENTERED_TEXT, WT_RIGHT_TEXT, WT_TEXT_BUTTON, WT_IMAGE_BUTTON, WT_TEXT_PUSHBUTTON, WT_IMAGE_PUSHBUTTON and WT_DROPDOWN_BUTTON.
Definition at line 194 of file widget.h.
Constructor & Destructor Documentation
DataWidget::DataWidget (WidgetType wtype)
Data widget constructor.
Parameters
wtype Widget type.
Definition at line 324 of file widget.cpp.
References value, value_height, and value_width.
Member Function Documentation
void DataWidget::SetupMinimalSize (GuiWindow * w, BaseWidget ** wid_array) override virtual
Compute smallest size of the widget.
Parameters
w Window owning the widget.
wid_array [out] Array of widget pointers.
Reimplemented from LeafWidget.
Definition at line 336 of file widget.cpp.
References _gui_sprites, _sprite_manager, GuiSprites::button, SpriteManager::GetTableSpriteSize(), GetTextSize(), Rectangle< PT, SZ >::height, GuiWindow::initialized, BaseWidget::InitMinimalSize(), BaseWidget::min_x, BaseWidget::min_y, NOT_REACHED, BaseWidget::number, BaseWidget::SetWidget(), GuiWindow::SetWidgetStringParameters(), BaseWidget::smallest_x, BaseWidget::smallest_y, SPR_GUI_TRIANGLE_DOWN, STR_NULL, GuiSprites::titlebar, GuiWindow::TranslateStringNumber(), GuiWindow::UpdateWidgetSize(), value, value_height, value_width, Rectangle< PT, SZ >::width, WT_CENTERED_TEXT, WT_DROPDOWN_BUTTON, WT_IMAGE_BUTTON, WT_IMAGE_PUSHBUTTON, WT_LEFT_TEXT, WT_RIGHT_TEXT, WT_TEXT_BUTTON, WT_TEXT_PUSHBUTTON, WT_TITLEBAR, and BaseWidget::wtype.
void DataWidget::Draw (const GuiWindow * w) override virtual
Draw a DataWidget.
Parameters
w Window that the widget belongs to.
Todo:
Fix the hard-coded colour of the text.
Reimplemented from LeafWidget.
Definition at line 406 of file widget.cpp.
References _gui_sprites, _sprite_manager, _video, ALG_CENTER, ALG_LEFT, ALG_RIGHT, Rectangle< PT, SZ >::base, VideoSystem::BlitImage(), BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, GuiSprites::button, LeafWidget::colour, DrawBorderSprites(), DrawString(), GuiWindow::DrawWidget(), SpriteManager::GetTableSprite(), SpriteManager::GetTableSpriteSize(), GetTextSize(), GuiWindow::GetWidgetScreenX(), GuiWindow::GetWidgetScreenY(), GS_NORMAL, Rectangle< PT, SZ >::height, LeafWidget::IsPressed(), LeafWidget::IsShaded(), NOT_REACHED, BaseWidget::number, OverlayShaded(), PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, BaseWidget::paddings, BaseWidget::pos, GuiWindow::SetWidgetStringParameters(), SPR_GUI_TRIANGLE_DOWN, STR_NULL, TEXT_WHITE, GuiSprites::titlebar, GuiWindow::TranslateStringNumber(), value, value_height, value_width, Rectangle< PT, SZ >::width, WT_CENTERED_TEXT, WT_DROPDOWN_BUTTON, WT_IMAGE_BUTTON, WT_IMAGE_PUSHBUTTON, WT_LEFT_TEXT, WT_RIGHT_TEXT, WT_TEXT_BUTTON, WT_TEXT_PUSHBUTTON, WT_TITLEBAR, BaseWidget::wtype, Point< CT >::x, and Point< CT >::y.
void LeafWidget::AutoRaiseButtons (const Point32 & base) override virtual inherited
Raise all push buttons in the tree.
Parameters
base Base position of the window.
Reimplemented from BaseWidget.
Reimplemented in BackgroundWidget.
Definition at line 312 of file widget.cpp.
References LeafWidget::IsPressed(), BaseWidget::MarkDirty(), LeafWidget::SetPressed(), WT_IMAGE_PUSHBUTTON, WT_TEXT_PUSHBUTTON, and BaseWidget::wtype.
bool LeafWidget::IsChecked () const inline inherited
Is the 'checked' flag on?
Returns
whether the 'checked' flag is set.
Definition at line 133 of file widget.h.
References LWF_CHECKED.
Referenced by GuiWindow::GetSelectedRadioButton(), and GuiWindow::SetWidgetChecked().
bool LeafWidget::IsPressed () const inline inherited
Is the 'pressed' flag on?
Returns
whether the 'pressed' flag is set.
Definition at line 142 of file widget.h.
References LWF_PRESSED.
Referenced by LeafWidget::AutoRaiseButtons(), Draw(), GuiWindow::GetSelectedRadioButton(), and GuiWindow::SetWidgetPressed().
bool LeafWidget::IsShaded () const inline inherited
Is the 'shaded' flag on?
Returns
whether the 'shaded' flag is set.
Definition at line 151 of file widget.h.
References LWF_SHADED.
Referenced by Draw(), ScrollbarWidget::Draw(), GuiWindow::GetSelectedRadioButton(), GuiWindow::OnMouseButtonEvent(), and GuiWindow::SetWidgetShaded().
void LeafWidget::SetChecked (bool value) inline inherited
Set the 'checked' flag to the new value.
Parameters
value New value of the 'checked' flag.
Definition at line 160 of file widget.h.
References LWF_CHECKED.
Referenced by GuiWindow::SetWidgetChecked().
void LeafWidget::SetPressed (bool value) inline inherited
Set the 'pressed' flag to the new value.
Parameters
value New value of the 'pressed' flag.
Definition at line 169 of file widget.h.
References LWF_PRESSED.
Referenced by LeafWidget::AutoRaiseButtons(), GuiWindow::OnMouseButtonEvent(), and GuiWindow::SetWidgetPressed().
void LeafWidget::SetShaded (bool value) inline inherited
Set the 'shaded' flag to the new value.
Parameters
value New value of the 'shaded' flag.
Definition at line 178 of file widget.h.
References LWF_SHADED.
Referenced by GuiWindow::SetWidgetShaded().
void BaseWidget::SetSmallestSizePosition (const Rectangle16 & rect) virtual inherited
Set the minimal size of the widget, and assign rect to the current position and size.
Parameters
rect Smallest size, and suggested position of the (entire) widget.
Reimplemented in IntermediateWidget, and BackgroundWidget.
Definition at line 172 of file widget.cpp.
References Rectangle< PT, SZ >::height, BaseWidget::min_x, BaseWidget::min_y, BaseWidget::pos, and Rectangle< PT, SZ >::width.
Referenced by GuiWindow::ResetSize(), BackgroundWidget::SetSmallestSizePosition(), and IntermediateWidget::SetSmallestSizePosition().
BaseWidget * BaseWidget::GetWidgetByPosition (const Point16 & pt) virtual inherited
Get the widget at the given relative window position.
Parameters
pt Relative point.
Returns
The widget underneath the point, or nullptr.
Reimplemented in IntermediateWidget, and BackgroundWidget.
Definition at line 194 of file widget.cpp.
References Rectangle< PT, SZ >::IsPointInside(), and BaseWidget::pos.
Referenced by BackgroundWidget::GetWidgetByPosition(), IntermediateWidget::GetWidgetByPosition(), and GuiWindow::OnMouseButtonEvent().
void BaseWidget::MarkDirty (const Point32 & base) const inherited
Denote the widget as being needed to redraw.
Parameters
base Window base coordinate.
Definition at line 212 of file widget.cpp.
References _video, VideoSystem::MarkDisplayDirty(), Point< CT >::x, and Point< CT >::y.
Referenced by LeafWidget::AutoRaiseButtons(), GuiWindow::MarkWidgetDirty(), ScrollbarWidget::OnClick(), GuiWindow::OnMouseButtonEvent(), GuiWindow::SetWidgetChecked(), GuiWindow::SetWidgetPressed(), and GuiWindow::SetWidgetShaded().
void BaseWidget::SetWidget (BaseWidget ** wid_array) protected inherited
Add the widget to the widget array wid_array.
Parameters
wid_array The widget array.
Definition at line 128 of file widget.cpp.
References BaseWidget::number.
Referenced by BaseWidget::SetupMinimalSize(), LeafWidget::SetupMinimalSize(), SetupMinimalSize(), ScrollbarWidget::SetupMinimalSize(), BackgroundWidget::SetupMinimalSize(), and IntermediateWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
Parameters
content_width Minimal width of the content.
content_height Minimal height of the content.
border_hor Horizontal border space.
border_vert Vertical border space.
Definition at line 97 of file widget.cpp.
References BaseWidget::min_x, BaseWidget::min_y, PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, and BaseWidget::paddings.
Referenced by LeafWidget::SetupMinimalSize(), SetupMinimalSize(), and BackgroundWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (const BorderSpriteData * bsd, uint16 content_width, uint16 content_height) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Parameters
bsd Used border sprites.
content_width Minimal width of the content.
content_height Minimal height of the content.
Definition at line 109 of file widget.cpp.
References BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, BaseWidget::fill_x, BaseWidget::fill_y, BorderSpriteData::hor_stepsize, LeastCommonMultiple(), BorderSpriteData::min_height, BorderSpriteData::min_width, BaseWidget::resize_x, BaseWidget::resize_y, and BorderSpriteData::vert_stepsize.
Member Data Documentation
uint8 LeafWidget::flags inherited
Flags of the leaf widget.
See also
LeafWidgetFlags
Definition at line 183 of file widget.h.
Referenced by LeafWidget::Draw(), and LeafWidget::LeafWidget().
The documentation for this class was generated from the following files:
widget.h
widget.cpp