FreeRCT: GCHKBlock Class Reference
GCHKBlock Class Reference
GCHK game block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int widget_type
Widget type.
std::shared_ptr< SpriteBlock > empty
Empty sprite.
std::shared_ptr< SpriteBlock > filled
Filled.
std::shared_ptr< SpriteBlock > empty_pressed
Empty pressed.
std::shared_ptr< SpriteBlock > filled_pressed
Filled pressed.
std::shared_ptr< SpriteBlock > shaded_empty
Shaded empty button.
std::shared_ptr< SpriteBlock > shaded_filled
Shaded filled button.
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
GCHK game block.
Definition at line 630 of file nodes.h.
Member Function Documentation
int GCHKBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 1011 of file nodes.cpp.
References FileWriter::AddBlock(), NamedBlock::blk_name, FileBlock::CheckEndSave(), empty, empty_pressed, filled, filled_pressed, FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), shaded_empty, shaded_filled, FileBlock::StartSave(), NamedBlock::version, and widget_type.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp