FreeRCT: Animation Class Reference
Animation Class Reference
Data structure holding a single animation.
#include <sprite_store.h>
Public Member Functions
Animation ()
Animation default constructor.
~Animation ()
Animation destructor.
bool Load (RcdFileReader *rcd_file)
Load an animation.
Public Attributes
uint16 frame_count
Number of frames.
uint8 person_type
Type of persons supported by this animation.
AnimationType anim_type
Animation ID.
AnimationFrame * frames
Frames of the animation.
RcdBlock * next
Pointer to next block.
Detailed Description
Data structure holding a single animation.
Definition at line 208 of file sprite_store.h.
Constructor & Destructor Documentation
Animation::Animation ()
Animation default constructor.
Definition at line 699 of file sprite_store.cpp.
References ANIM_INVALID, anim_type, frame_count, frames, PERSON_INVALID, and person_type.
Animation::~Animation ()
Animation destructor.
Definition at line 708 of file sprite_store.cpp.
References frames.
Member Function Documentation
bool Animation::Load (RcdFileReader * rcd_file)
Load an animation.
Parameters
rcd_file RCD file used for loading.
Returns
Loading was successful.
Definition at line 737 of file sprite_store.cpp.
References ANIM_LAST, anim_type, DecodePersonType(), AnimationFrame::duration, AnimationFrame::dx, AnimationFrame::dy, frame_count, frames, RcdFileReader::GetInt16(), RcdFileReader::GetUInt16(), RcdFileReader::GetUInt8(), PERSON_INVALID, person_type, RcdFileReader::size, and RcdFileReader::version.
Referenced by SpriteManager::Load().
The documentation for this class was generated from the following files:
sprite_store.h
sprite_store.cpp