FreeRCT: Person Class Reference
Person Class Reference abstract
Class of a person in the world.
#include <person.h>
Public Member Functions
const ImageData * GetSprite (const SpriteStorage *sprites, ViewOrientation orient, const Recolouring **recolour) const override
Get the sprite to draw for the voxel object.
virtual AnimateResult OnAnimate (int delay)
Update the animation of a person.
virtual bool DailyUpdate ()=0
Daily ponderings of a person.
virtual void Activate (const Point16 &start, PersonType person_type)
Mark this person as 'in use'.
virtual void DeActivate (AnimateResult ar)
Mark this person as 'not in use'.
bool IsActive () const
Test whether this person is active in the game or not.
bool IsGuest () const
Test whether this person is a guest or not.
void SetName (const char *name)
Set the name of a guest.
const char * GetName () const
Query the name of the person.
void AddSelf (Voxel *v)
Add itself to the voxel objects chain.
void RemoveSelf (Voxel *v)
Remove itself from the voxel objects chain.
void MarkDirty ()
Mark the voxel containing the voxel object as dirty, so it is repainted.
Public Attributes
uint16 id
Unique id of the person.
PersonType type
Type of person.
int16 offset
Offset with respect to centre of paths walked on (0..100).
const WalkInformation * walk
Walk animation sequence being performed.
const AnimationFrame * frames
Animation frames of the current animation.
uint16 frame_count
Number of frames in frames.
uint16 frame_index
Currently displayed frame of frames.
int16 frame_time
Remaining display time of this frame.
Recolouring recolour
Person recolouring.
VoxelObject * next_object
Next voxel object in the linked list.
VoxelObject * prev_object
Previous voxel object in the linked list.
bool added
Whether the voxel object has been added to a voxel.
XYZPoint16 vox_pos
Voxel position of the object.
XYZPoint16 pix_pos
Position of the object inside the voxel (0..255, but may be outside).
Protected Member Functions
TileEdge GetCurrentEdge () const
Decide at which edge the person is.
uint8 GetInparkDirections ()
Get the directions to neighboring tiles that lead to or stay in the park.
virtual void DecideMoveDirection ()=0
Decide where to go from the current position.
void StartAnimation (const WalkInformation *walk)
Perform the animation sequence as provided.
virtual RideVisitDesire WantToVisit (const RideInstance *ri)
How much does the person desire to visit the given ride?
virtual AnimateResult EdgeOfWorldOnAnimate ()=0
Handle the case of a guest reaching the end of the game world.
virtual AnimateResult VisitRideOnAnimate (RideInstance *ri, TileEdge exit_edge)=0
Handle guest ride visiting.
Protected Attributes
Random rnd
Random number generator for deciding how the person reacts.
char * name
Name of the person. nullptr means it has a default name (like "Guest XYZ").
Detailed Description
Class of a person in the world.
Persons are stored in contiguous blocks of memory, which makes the constructor and destructor useless. Instead, Activate and DeActivate methods are used for this purpose. The type variable controls the state of the entry.
Definition at line 96 of file person.h.
Member Function Documentation
const ImageData * Person::GetSprite (const SpriteStorage * sprites, ViewOrientation orient, const Recolouring ** recolour) const override virtual
Get the sprite to draw for the voxel object.
Parameters
sprites Sprites at the right size for drawing.
orient Direction of view.
recolour [out] Recolour mapping if present, else nullptr.
Returns
Sprite to display for the voxel object.
Implements VoxelObject.
Definition at line 108 of file person.cpp.
References WalkInformation::anim_type, frame_index, SpriteStorage::GetAnimationSprite(), recolour, type, and walk.
AnimateResult Person::OnAnimate (int delay) virtual
Update the animation of a person.
Parameters
delay Amount of milliseconds since the last update.
Returns
Whether to keep the person active or how to deactivate him/her.
Result code of the visit.
Reimplemented in Guest.
Definition at line 809 of file person.cpp.
References _rides_manager, _world, VoxelObject::AddSelf(), ANIM_INVALID, DecideMoveDirection(), AnimationFrame::duration, AnimationFrame::dx, AnimationFrame::dy, EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, EdgeOfWorldOnAnimate(), frame_count, frame_index, frame_time, frames, GB(), VoxelWorld::GetCreateVoxel(), Voxel::GetInstance(), RidesManager::GetRideInstance(), GetZHeight(), HasValidPath(), INVALID_EDGE, WalkInformation::limit_type, VoxelObject::MarkDirty(), OAR_CONTINUE, OAR_DEACTIVATE, OAR_OK, OAR_REMOVE, offset, VoxelObject::pix_pos, VoxelObject::RemoveSelf(), sign(), SRI_FULL_RIDES, StartAnimation(), VisitRideOnAnimate(), VoxelObject::vox_pos, walk, WLM_CENTER, WLM_END_LIMIT, WLM_HIGH, WLM_LIMIT_LENGTH, WLM_LOW, WLM_MAXIMAL, WLM_MINIMAL, WLM_X_COND, WLM_X_START, WLM_Y_START, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by Guest::OnAnimate().
bool Person::DailyUpdate () pure virtual
Daily ponderings of a person.
Returns
If false, de-activate the person.
Implemented in Guest.
void Person::Activate (const Point16 & start, PersonType person_type) virtual
Mark this person as 'in use'.
Parameters
start Start x/y voxel stack for entering the world.
person_type Type of person getting activated.
Reimplemented in Guest.
Definition at line 174 of file person.cpp.
References _world, VoxelObject::AddSelf(), DecideMoveDirection(), VoxelWorld::GetCreateVoxel(), VoxelWorld::GetGroundHeight(), GetPersonTypeData(), VoxelWorld::GetXSize(), GetZHeight(), PersonTypeData::graphics, IsActive(), PersonTypeGraphics::MakeRecolouring(), name, offset, PERSON_INVALID, VoxelObject::pix_pos, recolour, type, VoxelObject::vox_pos, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by Guest::Activate().
void Person::DeActivate (AnimateResult ar) virtual
Mark this person as 'not in use'.
(Called by Guests.)
Parameters
ar How to de-activate the person.
Reimplemented in Guest.
Definition at line 789 of file person.cpp.
References _world, VoxelWorld::GetCreateVoxel(), IsActive(), name, OAR_REMOVE, PERSON_INVALID, VoxelObject::RemoveSelf(), type, and VoxelWorld::VoxelExists().
Referenced by Guest::DeActivate().
bool Person::IsActive () const inline
Test whether this person is active in the game or not.
Returns
Whether the person is active in the game.
Definition at line 113 of file person.h.
References PERSON_INVALID, and type.
Referenced by Activate(), Guests::CountActiveGuests(), DeActivate(), Guest::DeActivate(), Guests::DoTick(), Guests::FindNextFreeGuest(), Guests::NotifyRideDeletion(), and Guests::OnAnimate().
bool Person::IsGuest () const inline
Test whether this person is a guest or not.
Returns
Whether the person is a guest.
Definition at line 122 of file person.h.
References PERSON_GUEST, and type.
Referenced by Guest::DailyUpdate(), GetName(), and SetName().
void Person::SetName (const char * name)
Set the name of a guest.
Parameters
name New name of the guest.
Note
Currently unused.
Definition at line 120 of file person.cpp.
References IsGuest().
const char * Person::GetName () const
Query the name of the person.
The name is returned in memory owned by the person. Do not free this data. It may change on each call.
Returns
Static buffer containing the name of the person.
Definition at line 134 of file person.cpp.
References IsGuest(), and name.
Referenced by GuestInfoWindow::SetWidgetStringParameters().
TileEdge Person::GetCurrentEdge () const protected
Decide at which edge the person is.
Returns
Nearest edge of the person.
Definition at line 366 of file person.cpp.
References EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, VoxelObject::pix_pos, XYZPoint< CT >::x, and XYZPoint< CT >::y.
Referenced by Guest::DecideMoveDirection().
uint8 Person::GetInparkDirections () protected
Get the directions to neighboring tiles that lead to or stay in the park.
Returns
Exits from the current tile that stay or lead into the park in the low nibble.
Definition at line 714 of file person.cpp.
References _tile_dxy, _world, EDGE_BEGIN, EDGE_COUNT, VoxelWorld::GetTileOwner(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), OWN_PARK, SB(), VoxelObject::vox_pos, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, and XYZPoint< CT >::y.
Referenced by Guest::DecideMoveDirection().
void Person::StartAnimation (const WalkInformation * walk) protected
Perform the animation sequence as provided.
Parameters
walk Walk information describing the animations to perform.
Definition at line 772 of file person.cpp.
References _sprite_manager, WalkInformation::anim_type, AnimationFrame::duration, frame_count, Animation::frame_count, frame_index, frame_time, frames, Animation::frames, SpriteManager::GetAnimation(), VoxelObject::MarkDirty(), and walk.
Referenced by Guest::DecideMoveDirection(), and OnAnimate().
RideVisitDesire Person::WantToVisit (const RideInstance * ri) protected virtual
How much does the person desire to visit the given ride?
Parameters
ri Ride that can be visited.
Returns
Desire of the person to visit the ride.
Reimplemented in Guest.
Definition at line 970 of file person.cpp.
References RVD_NO_VISIT.
AnimateResult Person::EdgeOfWorldOnAnimate () protected pure virtual
Handle the case of a guest reaching the end of the game world.
Returns
Result code of the visit.
Implemented in Guest.
Referenced by OnAnimate().
AnimateResult Person::VisitRideOnAnimate (RideInstance * ri, TileEdge exit_edge) protected pure virtual
Handle guest ride visiting.
Parameters
ri Ride that can be visited.
exit_edge Exit edge being examined.
Returns
Result code of the visit.
Implemented in Guest.
Referenced by OnAnimate().
void VoxelObject::AddSelf (Voxel * v) inline inherited
Add itself to the voxel objects chain.
Parameters
v Voxel containing the object.
Definition at line 323 of file map.h.
References VoxelObject::added, VoxelObject::next_object, VoxelObject::prev_object, and Voxel::voxel_objects.
Referenced by Activate(), Guest::ExitRide(), OnAnimate(), and DisplayCoasterCar::Set().
void VoxelObject::RemoveSelf (Voxel * v) inline inherited
Remove itself from the voxel objects chain.
Parameters
v Voxel containing the object.
Definition at line 338 of file map.h.
References VoxelObject::added, VoxelObject::next_object, VoxelObject::prev_object, and Voxel::voxel_objects.
Referenced by DeActivate(), OnAnimate(), and DisplayCoasterCar::Set().
void VoxelObject::MarkDirty () inherited
Mark the voxel containing the voxel object as dirty, so it is repainted.
Definition at line 143 of file map.cpp.
References MarkVoxelDirty(), and VoxelObject::vox_pos.
Referenced by OnAnimate(), DisplayCoasterCar::PreRemove(), DisplayCoasterCar::Set(), and StartAnimation().
The documentation for this class was generated from the following files:
person.h
person.cpp