FreeRCT: Values Class Reference
Values Class Reference
Class for storing found named values.
Public Member Functions
Values (const char *node_name, const Position &pos)
Constructor of the values collection.
void PrepareNamedValues (std::shared_ptr< NamedValueList > values, bool allow_named, bool allow_unnamed, const Symbol *symbols=nullptr)
Prepare the named values for access by field name.
std::shared_ptr< ValueInformation > FindValue (const char *fld_name)
Find the value information named fld_name.
bool HasValue (const char *fld_name)
check whether a field with name fld_name exists.
long long GetNumber (const char *fld_name, const Symbol *symbols=nullptr)
Get a numeric value from the named expression with the provided name.
std::string GetString (const char *fld_name)
Get a string value from the named expression with the provided name.
std::shared_ptr< SpriteBlock > GetSprite (const char *fld_name)
Get a sprite (SpriteBlock) from the named value with the provided name.
std::shared_ptr< Connection > GetConnection (const char *fld_name)
Get a connection from the named value with the provided name.
std::shared_ptr< StringsNode > GetStrings (const char *fld_name)
Get a set of strings from the named value with the provided name.
std::shared_ptr< Curve > GetCurve (const char *fld_name)
Get a curve description from the named value with the provided name.
void VerifyUsage ()
Verify whether all named values were used in a node.
Public Attributes
const Position pos
Position of the node.
const char * node_name
Name of the node using the values (memory is not released).
int named_count
Number of found values with a name.
int unnamed_count
Number of found value without a name.
std::vector< std::shared_ptr
< ValueInformation > > named_values
Information about each named value.
std::vector< std::shared_ptr
< ValueInformation > > unnamed_values
Information about each unnamed value.
Private Member Functions
void CreateValues (int named_count, int unnamed_count)
Create space for the information of of the values.
Detailed Description
Class for storing found named values.
Definition at line 387 of file check_data.cpp.
Constructor & Destructor Documentation
Values::Values (const char * node_name, const Position & pos)
Constructor of the values collection.
Parameters
node_name Name of the node using the values (caller owns the memory).
pos Position of the node.
Definition at line 421 of file check_data.cpp.
References named_count, node_name, and unnamed_count.
Member Function Documentation
void Values::PrepareNamedValues (std::shared_ptr< NamedValueList > values, bool allow_named, bool allow_unnamed, const Symbol * symbols = nullptr)
Prepare the named values for access by field name.
Parameters
values Named value to prepare.
allow_named Allow named values.
allow_unnamed Allow unnamed values.
symbols Optional symbols that may be used in the values.
Definition at line 459 of file check_data.cpp.
References AssignNames(), ConvertNodeGroup(), CreateValues(), named_count, named_values, unnamed_count, and unnamed_values.
Referenced by CheckTree(), ConvertCubicNode(), ConvertSplinesNode(), and ConvertSpriteFilesNode().
std::shared_ptr< ValueInformation > Values::FindValue (const char * fld_name)
Find the value information named fld_name.
Parameters
fld_name Name of the field looking for.
Returns
Reference in the vis array.
Definition at line 556 of file check_data.cpp.
References named_count, named_values, node_name, pos, and Position::ToString().
Referenced by GetConnection(), GetCurve(), GetNumber(), GetSprite(), GetString(), and GetStrings().
bool Values::HasValue (const char * fld_name)
check whether a field with name fld_name exists.
Parameters
fld_name Name of the field looking for.
Returns
Whether the field exists (true means it exists, false means it does not exist).
Definition at line 574 of file check_data.cpp.
References named_count, and named_values.
long long Values::GetNumber (const char * fld_name, const Symbol * symbols = nullptr)
Get a numeric value from the named expression with the provided name.
Parameters
fld_name Name of the field to retrieve.
symbols Optional set of identifiers recognized as numeric value.
Returns
The numeric value of the expression.
Definition at line 589 of file check_data.cpp.
References FindValue(), node_name, and pos.
std::string Values::GetString (const char * fld_name)
Get a string value from the named expression with the provided name.
Parameters
fld_name Name of the field to retrieve.
Returns
The value of the string.
Definition at line 599 of file check_data.cpp.
References FindValue(), node_name, and pos.
std::shared_ptr< SpriteBlock > Values::GetSprite (const char * fld_name)
Get a sprite (SpriteBlock) from the named value with the provided name.
Parameters
fld_name Name of the field to retrieve.
Returns
The sprite.
Definition at line 609 of file check_data.cpp.
References FindValue(), node_name, and pos.
std::shared_ptr< Connection > Values::GetConnection (const char * fld_name)
Get a connection from the named value with the provided name.
Parameters
fld_name Name of the field to retrieve.
Returns
The connection.
Definition at line 619 of file check_data.cpp.
References FindValue(), node_name, and pos.
std::shared_ptr< StringsNode > Values::GetStrings (const char * fld_name)
Get a set of strings from the named value with the provided name.
Parameters
fld_name Name of the field to retrieve.
Returns
The set of strings.
Definition at line 629 of file check_data.cpp.
References FindValue(), node_name, and pos.
std::shared_ptr< Curve > Values::GetCurve (const char * fld_name)
Get a curve description from the named value with the provided name.
Parameters
fld_name Name of the field to retrieve.
Returns
The queried curve.
Definition at line 639 of file check_data.cpp.
References FindValue(), node_name, and pos.
void Values::VerifyUsage ()
Verify whether all named values were used in a node.
Definition at line 645 of file check_data.cpp.
References named_count, named_values, node_name, unnamed_count, and unnamed_values.
Referenced by CheckTree().
void Values::CreateValues (int named_count, int unnamed_count) private
Create space for the information of of the values.
Parameters
named_count Number of named values.
unnamed_count Number of unnamed valued.
Definition at line 434 of file check_data.cpp.
References named_count, named_values, unnamed_count, and unnamed_values.
Referenced by PrepareNamedValues().
The documentation for this class was generated from the following file:
check_data.cpp