FreeRCT: ImageFile Class Reference
ImageFile Class Reference
A PNG image file.
#include <image.h>
Public Member Functions
void Clear ()
Reset the object, to prepare it for loading another image file.
const char * LoadFile (const std::string &fname)
Load a .png file from the disk.
int GetWidth () const
Get the width of the image.
int GetHeight () const
Get the height of the image.
bool Is8bpp () const
Return whether the loaded image file can be interpreted as an 8bpp image.
Public Attributes
bool png_initialized
Whether the data structures below are initialized.
uint8 ** row_pointers
Pointers into the rows of the image.
int width
Width of the loaded image.
int height
Height of the loaded image.
int color_type
Type of image.
std::string fname
Name of the loaded file.
Private Attributes
png_structp png_ptr
Png image data.
png_infop info_ptr
Png information.
png_infop end_info
Png end information.
Detailed Description
A PNG image file.
Definition at line 29 of file image.h.
Member Function Documentation
void ImageFile::Clear ()
Reset the object, to prepare it for loading another image file.
Definition at line 66 of file image.cpp.
References end_info, fname, info_ptr, png_initialized, png_ptr, and row_pointers.
const char * ImageFile::LoadFile (const std::string & fname)
Load a .png file from the disk.
Parameters
fname Name of the .png file to load.
Returns
An error message if loading failed, or nullptr if loading succeeded.
Definition at line 81 of file image.cpp.
References color_type, end_info, fname, HEADER_SIZE, height, info_ptr, png_initialized, png_ptr, row_pointers, and width.
Referenced by ConvertSpriteNode(), SheetBlock::GetSheet(), and SpriteFilesBlock::GetSubNode().
int ImageFile::GetWidth () const
Get the width of the image.
Returns
Width of the loaded image, or -1.
Definition at line 151 of file image.cpp.
References png_initialized, and width.
Referenced by Image::GetWidth().
int ImageFile::GetHeight () const
Get the height of the image.
Returns
Height of the loaded image, or -1.
Definition at line 161 of file image.cpp.
References height, and png_initialized.
Referenced by Image::GetHeight().
bool ImageFile::Is8bpp () const
Return whether the loaded image file can be interpreted as an 8bpp image.
Returns
true if the file is an 8bpp image, else false (which means it is a 32bpp image).
Definition at line 171 of file image.cpp.
References color_type.
Referenced by ConvertSpriteNode(), SheetBlock::GetSheet(), and SpriteFilesBlock::GetSubNode().
The documentation for this class was generated from the following files:
image.h
image.cpp