FreeRCT: Date Class Reference
Date Class Reference
Date in the game.
#include <dates.h>
Public Member Functions
Date ()
Default constructor.
Date (int pday, int pmonth, int pyear, int pfrac=0)
Constructor for a specific date.
Date (CompressedDate cd)
Constructor od a date from a compressed date.
Date (const Date &d)
Copy constructor.
Date & operator= (const Date &d)
Assignment operator.
void Initialize ()
Initialize the date for the start of a game.
CompressedDate Compress () const
Compress the date to an integer number.
int GetNextMonth () const
Get the number of the next month that the park will be open.
int GetPreviousMonth () const
Get the number of the previous month that the park was open.
Public Attributes
int day
Day of the month, 1-based.
int month
Month of the year, 1-based.
int year
The current year, 1-based.
int frac
Day fraction, 0-based.
Detailed Description
Date in the game.
Definition at line 33 of file dates.h.
Constructor & Destructor Documentation
Date::Date ()
Default constructor.
Definition at line 40 of file dates.cpp.
Date::Date (int pday, int pmonth, int pyear, int pfrac = 0)
Constructor for a specific date.
Parameters
pday Day of the month (1-based).
pmonth Month (1-based).
pyear Year (1-based).
pfrac Day fraction (0-based).
Definition at line 31 of file dates.cpp.
References CDB_YEAR_LENGTH, and TICK_COUNT_PER_DAY.
Date::Date (CompressedDate cd)
Constructor od a date from a compressed date.
Parameters
cd Compressed date source.
Definition at line 56 of file dates.cpp.
References CDB_DAY_LENGTH, CDB_DAY_START, CDB_FRAC_LENGTH, CDB_FRAC_START, CDB_MONTH_LENGTH, CDB_MONTH_START, CDB_YEAR_LENGTH, CDB_YEAR_START, day, frac, month, TICK_COUNT_PER_DAY, and year.
Date::Date (const Date & d)
Copy constructor.
Parameters
d Existing date.
Definition at line 48 of file dates.cpp.
Member Function Documentation
Date & Date::operator= (const Date & d)
Assignment operator.
Parameters
d Existing date.
Returns
Assigned value.
Definition at line 79 of file dates.cpp.
References day, frac, month, and year.
void Date::Initialize ()
Initialize the date for the start of a game.
Definition at line 91 of file dates.cpp.
References day, FIRST_MONTH, frac, month, and year.
Referenced by StartNewGame().
CompressedDate Date::Compress () const
Compress the date to an integer number.
Returns
The compressed date.
Definition at line 103 of file dates.cpp.
References CDB_DAY_START, CDB_FRAC_START, CDB_MONTH_START, CDB_YEAR_START, day, frac, month, and year.
Referenced by SaveDate(), and StringParameters::SetDate().
int Date::GetNextMonth () const
Get the number of the next month that the park will be open.
Returns
Month number (1-based) for the next month.
Definition at line 122 of file dates.cpp.
References FIRST_MONTH, and month.
Referenced by Weather::OnNewDay(), and Weather::SetTemperature().
int Date::GetPreviousMonth () const
Get the number of the previous month that the park was open.
Returns
Month number (1-based) for the previous month.
Definition at line 112 of file dates.cpp.
References LAST_MONTH, and month.
Referenced by Weather::SetTemperature().
The documentation for this class was generated from the following files:
dates.h
dates.cpp