FreeRCT: SpriteBlock Class Reference
SpriteBlock Class Reference
Block containing a sprite.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw)
Write an 8PXL block.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
SpriteImage sprite_image
The stored sprite.
Detailed Description
Block containing a sprite.
Definition at line 104 of file nodes.h.
Member Function Documentation
int SpriteBlock::Write (FileWriter * fw)
Write an 8PXL block.
Parameters
fw File to write to.
Returns
Block number in the written file for this sprite.
Definition at line 96 of file nodes.cpp.
References FileWriter::AddBlock(), SpriteImage::block_name, FileBlock::CheckEndSave(), SpriteImage::data, SpriteImage::data_size, SpriteImage::height, FileBlock::SaveBytes(), FileBlock::SaveUInt16(), sprite_image, FileBlock::StartSave(), SpriteImage::width, SpriteImage::xoffset, and SpriteImage::yoffset.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp