FreeRCT: ValueInformation Class Reference
ValueInformation Class Reference
All information that needs to be stored about a named value.
Public Member Functions
ValueInformation ()
Default constructor.
ValueInformation (const std::string &name, const Position &pos)
Constructor of the class.
long long GetNumber (const Position &pos, const char *node, const Symbol *symbols=nullptr)
Extract a number from the given expression.
std::string GetString (const Position &pos, const char *node)
Extract a string from the given expression.
std::shared_ptr< SpriteBlock > GetSprite (const Position &pos, const char *node)
Get a sprite (SpriteBlock) from the given node value.
std::shared_ptr< Connection > GetConnection (const Position &pos, const char *node)
Get a connection from the given node value.
std::shared_ptr< StringsNode > GetStrings (const Position &pos, const char *node)
Get a set of strings from the given node value.
std::shared_ptr< Curve > GetCurve (const Position &pos, const char *node)
Get a curve description from the node value.
Public Attributes
std::string name
Name of the value.
Position pos
Position of the name.
bool used
Is the value used?
std::shared_ptr< const Expression > expr_value
Expression attached to it (if any).
std::shared_ptr< BlockNode > node_value
Node attached to it (if any).
Detailed Description
All information that needs to be stored about a named value.
Definition at line 160 of file check_data.cpp.
Constructor & Destructor Documentation
ValueInformation::ValueInformation ()
Default constructor.
Definition at line 181 of file check_data.cpp.
References expr_value, name, node_value, and used.
ValueInformation::ValueInformation (const std::string & name, const Position & pos)
Constructor of the class.
Parameters
name Name of the value.
pos Position of the name.
Definition at line 194 of file check_data.cpp.
References expr_value, name, node_value, and used.
Member Function Documentation
long long ValueInformation::GetNumber (const Position & pos, const char * node, const Symbol * symbols = nullptr)
Extract a number from the given expression.
Parameters
pos Position of the node (for reporting errors).
node Name of the node.
symbols Symbols available for use in the expression.
Returns
Numeric value.
Definition at line 209 of file check_data.cpp.
References expr_value, name, Position::ToString(), and NumberLiteral::value.
Referenced by GetCurve().
std::string ValueInformation::GetString (const Position & pos, const char * node)
Extract a string from the given expression.
Parameters
pos Position of the node (for reporting errors).
node Name of the node.
Returns
String value, should be freed by the user.
Definition at line 232 of file check_data.cpp.
References expr_value, name, StringLiteral::text, and Position::ToString().
std::shared_ptr< SpriteBlock > ValueInformation::GetSprite (const Position & pos, const char * node)
Get a sprite (SpriteBlock) from the given node value.
Parameters
pos Position of the node (for reporting errors).
node Name of the node.
Returns
The sprite.
Definition at line 255 of file check_data.cpp.
References name, node_value, and Position::ToString().
std::shared_ptr< Connection > ValueInformation::GetConnection (const Position & pos, const char * node)
Get a connection from the given node value.
Parameters
pos Position of the node (for reporting errors).
node Name of the node.
Returns
The connection.
Definition at line 272 of file check_data.cpp.
References name, node_value, and Position::ToString().
std::shared_ptr< StringsNode > ValueInformation::GetStrings (const Position & pos, const char * node)
Get a set of strings from the given node value.
Parameters
pos Position of the node (for reporting errors).
node Name of the node.
Returns
The set of strings.
Definition at line 289 of file check_data.cpp.
References name, node_value, and Position::ToString().
std::shared_ptr< Curve > ValueInformation::GetCurve (const Position & pos, const char * node)
Get a curve description from the node value.
Parameters
pos Position of the node (for reporting errors).
node Name of the node.
Returns
The requested curve.
Definition at line 306 of file check_data.cpp.
References expr_value, GetNumber(), name, node_value, and Position::ToString().
The documentation for this class was generated from the following file:
check_data.cpp