FreeRCT: ComputeInitialPosition Class Reference
ComputeInitialPosition Class Reference
Compute the initial position of a window.
Public Member Functions
Point32 FindPosition (Window *w)
Find an initial position for new window w.
bool IsScreenEmpty (const Rectangle32 &rect)
Is the screen empty below the rectangle?
Protected Attributes
int base_pos
Base position of a new window.
Window * skip
Window to skip in the search.
Static Protected Attributes
static const int GAP = 5
Gap between the old and the new window.
Detailed Description
Compute the initial position of a window.
Definition at line 107 of file window.cpp.
Member Function Documentation
Point32 ComputeInitialPosition::FindPosition (Window * new_w)
Find an initial position for new window w.
Parameters
new_w New window to position.
Returns
Best position of the window.
Precondition
Size of the window has been decided.
Definition at line 148 of file window.cpp.
References _video, base_pos, GAP, GetDistanceToMouse(), VideoSystem::GetYSize(), Rectangle< PT, SZ >::height, IsScreenEmpty(), lengthof, Window::lower, Window::rect, skip, WindowManager::top, Rectangle< PT, SZ >::width, Point< CT >::x, and Point< CT >::y.
Referenced by Window::OnInitialPosition().
bool ComputeInitialPosition::IsScreenEmpty (const Rectangle32 & rect)
Is the screen empty below the rectangle?
Parameters
rect Area to test.
Returns
Tested area is clear.
Definition at line 198 of file window.cpp.
References _video, Rectangle< PT, SZ >::base, GetWindowZPriority(), VideoSystem::GetXSize(), VideoSystem::GetYSize(), Rectangle< PT, SZ >::height, Window::lower, skip, WindowManager::top, Rectangle< PT, SZ >::width, Window::wtype, Point< CT >::x, and Point< CT >::y.
Referenced by FindPosition().
The documentation for this class was generated from the following file:
window.cpp