FreeRCT: CSPLBlock Class Reference
CSPLBlock Class Reference
'CSPL' game block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int tile_width
Zoom-width of a tile of the surface.
uint8 type
Type of platform.
std::shared_ptr< SpriteBlock > ne_sw_back
Background platform sprite of the NE to SW direction.
std::shared_ptr< SpriteBlock > ne_sw_front
Foreground platform sprite of the NE to SW direction.
std::shared_ptr< SpriteBlock > se_nw_back
Background platform sprite of the SE to NW direction.
std::shared_ptr< SpriteBlock > se_nw_front
Foreground platform sprite of the SE to NW direction.
std::shared_ptr< SpriteBlock > sw_ne_back
Background platform sprite of the SW to NE direction.
std::shared_ptr< SpriteBlock > sw_ne_front
Foreground platform sprite of the SW to NE direction.
std::shared_ptr< SpriteBlock > nw_se_back
Background platform sprite of the NW to SE direction.
std::shared_ptr< SpriteBlock > nw_se_front
Foreground platform sprite of the NW to SE direction.
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
'CSPL' game block.
Definition at line 905 of file nodes.h.
Member Function Documentation
int CSPLBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 1682 of file nodes.cpp.
References FileWriter::AddBlock(), NamedBlock::blk_name, FileBlock::CheckEndSave(), ne_sw_back, ne_sw_front, nw_se_back, nw_se_front, FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), FileBlock::SaveUInt8(), se_nw_back, se_nw_front, FileBlock::StartSave(), sw_ne_back, sw_ne_front, tile_width, type, and NamedBlock::version.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp