FreeRCT: Viewport Class Reference
Viewport Class Reference
%Window code » %Viewport (main display) code and data
Class for displaying parts of the world.
#include <viewport.h>
Public Member Functions
Viewport (uint32 xview, uint32 yview, uint32 zview)
Viewport constructor.
void MarkVoxelDirty (int16 xpos, int16 ypos, int16 zpos, int16 height=0)
Mark a voxel as in need of getting painted.
void OnDraw () override
Paint the window to the screen.
void Rotate (int direction)
Rotate 90 degrees clockwise or anti-clockwise.
void MoveViewport (int dx, int dy)
Move the viewport a number of screen pixels.
ClickableSprite ComputeCursorPosition (FinderData *fdata)
Compute position of the mouse cursor, and return the result.
CursorType GetCursorAtPos (uint16 xpos, uint16 ypos, uint8 zpos)
Get the cursor type at a given position.
uint8 GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos)
Get the highest voxel that should be examined in a voxel stack (since cursors may be placed above all voxels).
void EnableWorldAdditions ()
Enable flashing display of showing proposed game world additions to the player.
void DisableWorldAdditions ()
Disable flashing display of showing proposed game world additions to the player.
void EnsureAdditionsAreVisible ()
Reset the display state of the world additions, such that they become visible directly.
Point32 ComputeHorizontalTranslation (int dx, int dy)
Compute the horizontal translation in world coordinates of the viewing centre to move it dx / dy pixels.
int32 ComputeX (int32 xpos, int32 ypos)
Get relative X position of a point in the world (used for marking window parts dirty).
int32 ComputeY (int32 xpos, int32 ypos, int32 zpos)
Get relative Y position of a point in the world (used for marking window parts dirty).
virtual void SetSize (uint width, uint height)
Set the initial size of a window.
void SetPosition (int x, int y)
Set the position of the top-left corner of the window.
void SetPosition (Point32 pos)
Set the position of the top-left corner of the window.
virtual Point32 OnInitialPosition ()
Find a nice initial position for the new window.
void MarkDirty ()
Mark windows as being dirty (needing a repaint).
virtual void OnMouseEnterEvent ()
Mouse entered window.
virtual void OnMouseLeaveEvent ()
Mouse left window.
virtual void SetHighlight (bool value)
Enable or disable highlighting.
virtual void OnChange (ChangeCode code, uint32 parameter)
An important (window-specific) change has happened.
virtual void ResetSize ()
Reset the size of a window.
Public Attributes
int32 xview
X position of the centre point of the viewport.
int32 yview
Y position of the centre point of the viewport.
int32 zview
Z position of the centre point of the viewport.
uint16 tile_width
Width of a tile.
uint16 tile_height
Height of a tile.
ViewOrientation orientation
Direction of view.
Cursor tile_cursor
Cursor for selecting a tile (or tile corner).
Cursor arrow_cursor
Cursor for showing the path/track build direction.
MultiCursor area_cursor
Cursor for showing an area.
EdgeCursor edge_cursor
Cursor for showing an edge sprite.
Point16 mouse_pos
Last known position of the mouse.
bool additions_enabled
Flashing of world additions is enabled.
Rectangle32 rect
Screen area covered by the window.
const WindowTypes wtype
Window type.
const WindowNumber wnumber
Window number.
uint8 timeout
Timeout counter.
uint8 flags
Window flags.
Window * higher
Window above this window (managed by WindowManager).
Window * lower
Window below this window (managed by WindowManager).
Private Member Functions
void OnMouseMoveEvent (const Point16 &pos) override
Mouse moved to new position.
WmMouseEvent OnMouseButtonEvent (uint8 state) override
Mouse buttons changed state.
void OnMouseWheelEvent (int direction) override
Mousewheel rotated.
void TimeoutCallback ()
Toggle display of world additions (in _additions) if enabled.
Private Attributes
bool additions_displayed
Additions in _additions are displayed to the user.
Detailed Description
Class for displaying parts of the world.
Definition at line 226 of file viewport.h.
Constructor & Destructor Documentation
Viewport::Viewport (uint32 xview, uint32 yview, uint32 zview)
Viewport constructor.
Parameters
xview X pixel position of the center viewpoint of the main display.
yview Y pixel position of the center viewpoint of the main display.
zview Z pixel position of the center viewpoint of the main display.
Definition at line 1347 of file viewport.cpp.
References _video, additions_displayed, additions_enabled, VideoSystem::GetXSize(), VideoSystem::GetYSize(), MouseModes::main_display, mouse_pos, orientation, Window::SetPosition(), Window::SetSize(), tile_height, tile_width, VOR_NORTH, Point< CT >::x, xview, Point< CT >::y, yview, and zview.
Member Function Documentation
void Viewport::MarkVoxelDirty (int16 xpos, int16 ypos, int16 zpos, int16 height = 0)
Mark a voxel as in need of getting painted.
Parameters
xpos X position of the voxel.
ypos Y position of the voxel.
zpos Z position of the voxel.
height Number of voxels to mark above the specified coordinate (0 means inspect the voxel itself).
Definition at line 1431 of file viewport.cpp.
References _corner_dxy, _rides_manager, _video, _world, Rectangle< PT, SZ >::base, ComputeX(), ComputeY(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), Voxel::GetInstance(), RideInstance::GetKind(), RidesManager::GetRideInstance(), ShopInstance::GetShopType(), VoxelWorld::GetVoxel(), GTP_INVALID, ShopType::height, Rectangle< PT, SZ >::height, IsImplodedSteepSlope(), VideoSystem::MarkDisplayDirty(), orientation, Window::rect, RotateClockwise(), RotateCounterClockwise(), RTK_SHOP, SRI_FULL_RIDES, Rectangle< PT, SZ >::width, Point< CT >::x, xview, Point< CT >::y, yview, and zview.
Referenced by ChangeAreaCursorMode(), ChangeTileCursorMode(), Cursor::MarkDirty(), MultiCursor::MarkDirty(), EdgeCursor::MarkDirty(), WorldAdditions::MarkDirty(), MarkVoxelDirty(), and FenceBuildManager::OnMouseButtonEvent().
void Viewport::OnDraw () override virtual
Paint the window to the screen.
Note
The window manager already locked the surface.
Reimplemented from Window.
Definition at line 1400 of file viewport.cpp.
References _video, _weather, additions_displayed, additions_enabled, DrawData::base, Rectangle< PT, SZ >::base, VideoSystem::BlitImage(), MouseModes::current, MouseMode::EnableCursors(), VideoSystem::FillSurface(), VideoSystem::GetClippedRectangle(), Weather::GetWeatherType(), GS_LIGHT, MakeRGBA(), OPAQUE, DrawData::recolour, Window::rect, VideoSystem::SetClippedRectangle(), VoxelCollector::SetWindowSize(), DrawData::sprite, Rectangle< PT, SZ >::width, and Point< CT >::x.
void Viewport::Rotate (int direction)
Rotate 90 degrees clockwise or anti-clockwise.
Parameters
direction Direction of turn (positive means clockwise).
Definition at line 1534 of file viewport.cpp.
References ALL_WINDOWS_OF_TYPE, CHG_VIEWPORT_ROTATED, Window::MarkDirty(), mouse_pos, NotifyChange(), OnMouseMoveEvent(), orientation, VOR_NUM_ORIENT, and WC_PATH_BUILDER.
Referenced by VideoSystem::HandleEvent().
void Viewport::MoveViewport (int dx, int dy)
Move the viewport a number of screen pixels.
Parameters
dx Horizontal shift in screen pixels.
dy Vertical shift in screen pixels.
Definition at line 1585 of file viewport.cpp.
References _world, ComputeHorizontalTranslation(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), Window::MarkDirty(), Point< CT >::x, xview, Point< CT >::y, and yview.
Referenced by SelectMouseMode::OnMouseMoveEvent(), PathBuildManager::OnMouseMoveEvent(), CoasterBuildMode::OnMouseMoveEvent(), and TileTerraformMouseMode::OnMouseMoveEvent().
ClickableSprite Viewport::ComputeCursorPosition (FinderData * fdata)
Compute position of the mouse cursor, and return the result.
Parameters
fdata [inout] Parameters and results of the finding process.
Returns
Found type of sprite.
Definition at line 1491 of file viewport.cpp.
References _palette, AddOrientations(), VoxelCollector::Collect(), CS_GROUND, CS_GROUND_EDGE, CS_MASK, CS_NONE, CUR_TYPE_EDGE_NE, CUR_TYPE_TILE, FinderData::cursor, PixelFinder::data, EDGE_COUNT, EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, PixelFinder::found, FW_CORNER, FW_EDGE, Rectangle< PT, SZ >::height, mouse_pos, DrawData::order, orientation, PixelFinder::pixel, Window::rect, FinderData::select, VoxelCollector::SetWindowSize(), VOR_EAST, VOR_NORTH, VOR_SOUTH, VOR_WEST, Rectangle< PT, SZ >::width, Point< CT >::x, and Point< CT >::y.
Referenced by SelectMouseMode::OnMouseButtonEvent(), PathBuildManager::OnMouseButtonEvent(), PathBuildManager::OnMouseMoveEvent(), FenceBuildManager::SetCursors(), TileTerraformMouseMode::SetCursors(), and CoasterBuildMode::UpdateDisplay().
CursorType Viewport::GetCursorAtPos (uint16 xpos, uint16 ypos, uint8 zpos)
Get the cursor type at a given position.
Parameters
xpos X position of the voxel being drawn.
ypos Y position of the voxel being drawn.
zpos Z position of the voxel being drawn.
Returns
Cursor type at the position (CUR_TYPE_INVALID means no cursor available).
Definition at line 741 of file viewport.cpp.
References additions_displayed, additions_enabled, area_cursor, arrow_cursor, CUR_TYPE_INVALID, edge_cursor, Cursor::GetCursor(), MultiCursor::GetCursor(), EdgeCursor::GetCursor(), and tile_cursor.
Referenced by SpriteCollector::GetCursorSpriteAtPos().
uint8 Viewport::GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos)
Get the highest voxel that should be examined in a voxel stack (since cursors may be placed above all voxels).
Parameters
xpos X position of the voxel stack.
ypos Y position of the voxel stack.
zpos Z position of the top voxel.
Returns
Highest voxel to draw.
Definition at line 763 of file viewport.cpp.
References additions_displayed, additions_enabled, area_cursor, arrow_cursor, edge_cursor, Cursor::GetMaxCursorHeight(), MultiCursor::GetMaxCursorHeight(), EdgeCursor::GetMaxCursorHeight(), and tile_cursor.
Referenced by VoxelCollector::Collect().
void Viewport::EnableWorldAdditions ()
Enable flashing display of showing proposed game world additions to the player.
Definition at line 391 of file viewport.cpp.
References additions_displayed, additions_enabled, ADDITIONS_TIMEOUT_LENGTH, arrow_cursor, Cursor::MarkDirty(), WorldAdditions::MarkDirty(), and Window::timeout.
Referenced by PathBuildManager::ComputeNewLongPath(), EnableWorldAdditions(), and PathBuildManager::UpdateState().
void Viewport::DisableWorldAdditions ()
Disable flashing display of showing proposed game world additions to the player.
Definition at line 403 of file viewport.cpp.
References additions_displayed, additions_enabled, arrow_cursor, Cursor::MarkDirty(), WorldAdditions::MarkDirty(), and Window::timeout.
Referenced by DisableWorldAdditions(), and PathBuildManager::UpdateState().
void Viewport::EnsureAdditionsAreVisible ()
Reset the display state of the world additions, such that they become visible directly.
Precondition
World additions have to be enabled.
Definition at line 418 of file viewport.cpp.
References additions_displayed, additions_enabled, ADDITIONS_TIMEOUT_LENGTH, arrow_cursor, Cursor::MarkDirty(), WorldAdditions::MarkDirty(), and Window::timeout.
Referenced by PathBuildManager::ComputeNewLongPath(), ShopPlacementManager::PlaceShop(), and PathBuildManager::UpdateState().
Point32 Viewport::ComputeHorizontalTranslation (int dx, int dy)
Compute the horizontal translation in world coordinates of the viewing centre to move it dx / dy pixels.
Parameters
dx Horizontal shift in screen pixels.
dy Vertical shift in screen pixels.
Returns
New X and Y coordinates of the centre point.
Definition at line 1550 of file viewport.cpp.
References NOT_REACHED, orientation, tile_width, VOR_EAST, VOR_NORTH, VOR_SOUTH, VOR_WEST, Point< CT >::x, xview, Point< CT >::y, and yview.
Referenced by MoveViewport(), PathBuildManager::OnMouseMoveEvent(), and ShopPlacementManager::PlaceShop().
int32 Viewport::ComputeX (int32 xpos, int32 ypos)
Get relative X position of a point in the world (used for marking window parts dirty).
Parameters
xpos X world position.
ypos Y world position.
Returns
Relative X position.
Definition at line 1383 of file viewport.cpp.
References ComputeXFunction(), orientation, and tile_width.
Referenced by MarkVoxelDirty().
int32 Viewport::ComputeY (int32 xpos, int32 ypos, int32 zpos)
Get relative Y position of a point in the world (used for marking window parts dirty).
Parameters
xpos X world position.
ypos Y world position.
zpos Z world position.
Returns
Relative Y position.
Definition at line 1395 of file viewport.cpp.
References ComputeYFunction(), orientation, tile_height, and tile_width.
Referenced by MarkVoxelDirty().
void Viewport::OnMouseMoveEvent (const Point16 & pos) override private virtual
Mouse moved to new position.
Parameters
pos New position.
Reimplemented from Window.
Definition at line 1599 of file viewport.cpp.
References MouseModes::current, mouse_pos, and MouseMode::OnMouseMoveEvent().
Referenced by Rotate().
WmMouseEvent Viewport::OnMouseButtonEvent (uint8 state) override private virtual
Mouse buttons changed state.
Parameters
state Updated state.
See also
MouseButtons
Returns
Action to perform as a result of the event (use WMME_NONE if no special action needed).
Reimplemented from Window.
Definition at line 1607 of file viewport.cpp.
References MouseModes::current, MouseMode::OnMouseButtonEvent(), and WMME_NONE.
void Viewport::OnMouseWheelEvent (int direction) override private virtual
Mousewheel rotated.
Parameters
direction Direction of change (+1 or -1).
Reimplemented from Window.
Definition at line 1613 of file viewport.cpp.
References MouseModes::current, and MouseMode::OnMouseWheelEvent().
void Viewport::TimeoutCallback () private virtual
Toggle display of world additions (in _additions) if enabled.
Reimplemented from Window.
Definition at line 430 of file viewport.cpp.
References additions_displayed, additions_enabled, ADDITIONS_TIMEOUT_LENGTH, arrow_cursor, Cursor::MarkDirty(), WorldAdditions::MarkDirty(), and Window::timeout.
void Window::SetSize (uint width, uint height) virtual inherited
Set the initial size of a window.
Parameters
width Initial width of the new window.
height Initial height of the new window.
Reimplemented in GuiWindow.
Definition at line 81 of file window.cpp.
References Rectangle< PT, SZ >::height, Window::rect, and Rectangle< PT, SZ >::width.
Referenced by VideoSystem::SetResolution(), and Viewport().
void Window::SetPosition (int x, int y) inherited
Set the position of the top-left corner of the window.
Parameters
x X position.
y Y position.
Definition at line 92 of file window.cpp.
Referenced by DropdownMenuWindow::DropdownMenuWindow(), WindowManager::MouseMoveEvent(), RecolourDropdownWindow::RecolourDropdownWindow(), GuiWindow::SetupWidgetTree(), and Viewport().
void Window::SetPosition (Point32 pos) inherited
Set the position of the top-left corner of the window.
Parameters
pos Point to set to.
Definition at line 101 of file window.cpp.
References Rectangle< PT, SZ >::base, and Window::rect.
Point32 Window::OnInitialPosition () virtual inherited
Find a nice initial position for the new window.
Returns
Initial position of the window.
Reimplemented in QuitProgramWindow, BottomToolbarWindow, and ToolbarWindow.
Definition at line 217 of file window.cpp.
References ComputeInitialPosition::FindPosition().
Referenced by GuiWindow::SetupWidgetTree().
void Window::MarkDirty () inherited
Mark windows as being dirty (needing a repaint).
Todo:
Marking the whole display as needing a repaint is too crude.
Definition at line 228 of file window.cpp.
References _video, VideoSystem::MarkDisplayDirty(), and Window::rect.
Referenced by WindowManager::DeleteWindow(), WindowManager::MouseMoveEvent(), MoveViewport(), GuestInfoWindow::OnChange(), ShopManagerWindow::OnChange(), BottomToolbarWindow::OnChange(), RideSelectGui::OnClick(), WindowManager::RaiseWindow(), Rotate(), GuiWindow::SetHighlight(), and GuiWindow::SetupWidgetTree().
void Window::OnMouseEnterEvent () virtual inherited
Mouse entered window.
Definition at line 268 of file window.cpp.
Referenced by WindowManager::UpdateCurrentWindow().
void Window::OnMouseLeaveEvent () virtual inherited
Mouse left window.
Reimplemented in GuiWindow.
Definition at line 273 of file window.cpp.
Referenced by WindowManager::UpdateCurrentWindow().
void Window::SetHighlight (bool value) virtual inherited
Enable or disable highlighting.
Base class does nothing. If enabled, the timeout is used to automatically disable it again.
Parameters
value New highlight value.
Reimplemented in GuiWindow.
Definition at line 290 of file window.cpp.
Referenced by HighlightWindowByType().
void Window::OnChange (ChangeCode code, uint32 parameter) virtual inherited
An important (window-specific) change has happened.
Parameters
code Unique identification of the change.
parameter Parameter of the code.
Note
Meaning of number values are documented near this method in derived classes.
Reimplemented in CoasterBuildWindow, BottomToolbarWindow, ShopManagerWindow, GuestInfoWindow, RideSelectGui, ToolbarWindow, PathBuildGui, FenceGui, and SettingWindow.
Definition at line 300 of file window.cpp.
Referenced by NotifyChange().
void Window::ResetSize () virtual inherited
Reset the size of a window.
Note
Only if the window is a GuiWindow.
Reimplemented in GuiWindow.
Definition at line 308 of file window.cpp.
Member Data Documentation
uint8 Window::timeout inherited
Timeout counter.
Decremented on each iteration. When it reaches 0, TimeoutCallback is called.
Definition at line 131 of file window.h.
Referenced by DisableWorldAdditions(), EnableWorldAdditions(), EnsureAdditionsAreVisible(), GuiWindow::OnMouseButtonEvent(), GuiWindow::SetHighlight(), WindowManager::Tick(), TimeoutCallback(), and Window::Window().
uint8 Window::flags inherited
Window flags.
See also
WindowFlags
Definition at line 132 of file window.h.
Referenced by GuiWindow::OnDraw(), GuiWindow::SetHighlight(), GuiWindow::TimeoutCallback(), and Window::Window().
The documentation for this class was generated from the following files:
viewport.h
viewport.cpp