FreeRCT: DisplayCoasterCar Class Reference
DisplayCoasterCar Class Reference
Displayed car in a train.
#include <coaster.h>
Public Member Functions
virtual const ImageData * GetSprite (const SpriteStorage *sprites, ViewOrientation orient, const Recolouring **recolour) const override
Get the sprite to draw for the voxel object.
void Set (const XYZPoint16 &vox_pos, const XYZPoint16 &pix_pos, uint8 pitch, uint8 roll, uint8 yaw)
Set the position and orientation of the car.
void PreRemove ()
Displayed car is about to be removed from the train, clean up if necessary.
void AddSelf (Voxel *v)
Add itself to the voxel objects chain.
void RemoveSelf (Voxel *v)
Remove itself from the voxel objects chain.
void MarkDirty ()
Mark the voxel containing the voxel object as dirty, so it is repainted.
Public Attributes
const CarType * car_type
Car type data.
uint8 pitch
Pitch of the car.
uint8 roll
Roll of the car.
uint8 yaw
Yaw of the car (0xff means all data is invalid).
VoxelObject * next_object
Next voxel object in the linked list.
VoxelObject * prev_object
Previous voxel object in the linked list.
bool added
Whether the voxel object has been added to a voxel.
XYZPoint16 vox_pos
Voxel position of the object.
XYZPoint16 pix_pos
Position of the object inside the voxel (0..255, but may be outside).
Detailed Description
Displayed car in a train.
Note that yaw decides validness of the data.
Definition at line 119 of file coaster.h.
Member Function Documentation
const ImageData * DisplayCoasterCar::GetSprite (const SpriteStorage * sprites, ViewOrientation orient, const Recolouring ** recolour) const override virtual
Get the sprite to draw for the voxel object.
Parameters
sprites Sprites at the right size for drawing.
orient Direction of view.
recolour [out] Recolour mapping if present, else nullptr.
Returns
Sprite to display for the voxel object.
Implements VoxelObject.
Definition at line 221 of file coaster.cpp.
References car_type, CarType::GetCar(), pitch, roll, and yaw.
void DisplayCoasterCar::Set (const XYZPoint16 & vox_pos, const XYZPoint16 & pix_pos, uint8 pitch, uint8 roll, uint8 yaw)
Set the position and orientation of the car.
It requests repainting of voxels.
Parameters
vox_pos Voxel position of car.
pix_pos Position within the voxel (may be outside the 0..255 boundary).
pitch Pitch of the car.
roll Roll of the car.
yaw Yaw of the car.
Definition at line 235 of file coaster.cpp.
References _world, VoxelObject::AddSelf(), VoxelWorld::GetCreateVoxel(), VoxelObject::MarkDirty(), pitch, VoxelObject::pix_pos, VoxelObject::RemoveSelf(), roll, VoxelObject::vox_pos, and yaw.
Referenced by CoasterTrain::OnAnimate().
void DisplayCoasterCar::PreRemove ()
Displayed car is about to be removed from the train, clean up if necessary.
Definition at line 268 of file coaster.cpp.
References VoxelObject::MarkDirty(), and yaw.
Referenced by CoasterCar::PreRemove().
void VoxelObject::AddSelf (Voxel * v) inline inherited
Add itself to the voxel objects chain.
Parameters
v Voxel containing the object.
Definition at line 323 of file map.h.
References VoxelObject::added, VoxelObject::next_object, VoxelObject::prev_object, and Voxel::voxel_objects.
Referenced by Person::Activate(), Guest::ExitRide(), Person::OnAnimate(), and Set().
void VoxelObject::RemoveSelf (Voxel * v) inline inherited
Remove itself from the voxel objects chain.
Parameters
v Voxel containing the object.
Definition at line 338 of file map.h.
References VoxelObject::added, VoxelObject::next_object, VoxelObject::prev_object, and Voxel::voxel_objects.
Referenced by Person::DeActivate(), Person::OnAnimate(), and Set().
void VoxelObject::MarkDirty () inherited
Mark the voxel containing the voxel object as dirty, so it is repainted.
Definition at line 143 of file map.cpp.
References MarkVoxelDirty(), and VoxelObject::vox_pos.
Referenced by Person::OnAnimate(), PreRemove(), Set(), and Person::StartAnimation().
The documentation for this class was generated from the following files:
coaster.h
coaster.cpp