FreeRCT: FileWriter Class Reference
FileWriter Class Reference
RCD output file.
#include <file_writing.h>
Public Member Functions
int AddBlock (FileBlock *fb)
Add a block to the file.
void WriteFile (const std::string fname)
Write all blocks of the RCD file to the file.
Private Attributes
FileBlockPtrList blocks
Blocks stored in the file so far.
Detailed Description
RCD output file.
Definition at line 46 of file file_writing.h.
Member Function Documentation
int FileWriter::AddBlock (FileBlock * blk)
Add a block to the file.
Parameters
blk Block to add.
Returns
Block index number where the block is stored in the file.
Definition at line 158 of file file_writing.cpp.
References blocks.
Referenced by SpriteBlock::Write(), TSELBlock::Write(), TCORBlock::Write(), SURFBlock::Write(), FUNDBlock::Write(), PRSGBlock::Write(), ANIMBlock::Write(), ANSPBlock::Write(), PATHBlock::Write(), PLATBlock::Write(), SUPPBlock::Write(), StringBundle::Write(), SHOPBlock::Write(), GBORBlock::Write(), GCHKBlock::Write(), GSLIBlock::Write(), GSCLBlock::Write(), BDIRBlock::Write(), GSLPBlock::Write(), TrackPieceNode::Write(), RCSTBlock::Write(), CARSBlock::Write(), CSPLBlock::Write(), FENCBlock::Write(), and INFOBlock::Write().
void FileWriter::WriteFile (const std::string fname)
Write all blocks of the RCD file to the file.
Parameters
fname Filename to create.
Definition at line 177 of file file_writing.cpp.
References blocks.
Referenced by main().
The documentation for this class was generated from the following files:
file_writing.h
file_writing.cpp