FreeRCT: PositionedTrackPiece Class Reference
PositionedTrackPiece Class Reference
Track piece with a position.
#include <track_piece.h>
Public Member Functions
PositionedTrackPiece ()
Default constructor.
PositionedTrackPiece (uint16 xpos, uint16 ypos, uint8 zpos, ConstTrackPiecePtr piece)
Constructor taking values for all its fields.
bool IsOnWorld () const
Verify that all voxels of this track piece are within world boundaries.
bool CanBePlaced () const
Can this positioned track piece be placed in the world?
bool CanBeSuccessor (uint16 x, uint16 y, uint8 z, uint8 connect) const
Can this positioned track piece function as a successor for the given exit conditions?
bool CanBeSuccessor (const PositionedTrackPiece &pred) const
Can this positioned track piece function as a successor of piece pred?
uint16 GetEndX () const
Get the X position of the exit voxel.
uint16 GetEndY () const
Get the Y position of the exit voxel.
uint8 GetEndZ () const
Get the Z position of the exit voxel.
Public Attributes
uint16 x_base
X position of the entry point of the track piece.
uint16 y_base
Y position of the entry point of the track piece.
uint8 z_base
Z position of the entry point of the track piece.
uint32 distance_base
Base distance of this track piece in its roller coaster.
ConstTrackPiecePtr piece
Track piece placed at the given position, may be nullptr.
Detailed Description
Track piece with a position.
Used in roller coasters to define their path in the world.
Note
The piece value is owned by the coaster type, do not free it.
Definition at line 280 of file track_piece.h.
Constructor & Destructor Documentation
PositionedTrackPiece::PositionedTrackPiece ()
Default constructor.
Definition at line 230 of file track_piece.cpp.
References piece.
PositionedTrackPiece::PositionedTrackPiece (uint16 xpos, uint16 ypos, uint8 zpos, ConstTrackPiecePtr piece)
Constructor taking values for all its fields.
Parameters
xpos X position of the positioned track piece.
ypos Y position of the positioned track piece.
zpos Z position of the positioned track piece.
piece Track piece to use.
Definition at line 242 of file track_piece.cpp.
References piece, x_base, y_base, and z_base.
Member Function Documentation
bool PositionedTrackPiece::IsOnWorld () const
Verify that all voxels of this track piece are within world boundaries.
Returns
The positioned track piece is entirely within the world boundaries.
Precondition
Positioned track piece must have a piece.
Definition at line 255 of file track_piece.cpp.
References TrackVoxel::dx, TrackVoxel::dy, TrackVoxel::dz, IsVoxelInsideWorld(), piece, x_base, y_base, and z_base.
Referenced by CoasterInstance::AddPositionedPiece(), and CanBePlaced().
bool PositionedTrackPiece::CanBePlaced () const
Can this positioned track piece be placed in the world?
Returns
Positioned track piece can be placed.
Precondition
Positioned track piece must have a piece.
Definition at line 274 of file track_piece.cpp.
References _world, Voxel::CanPlaceInstance(), TrackVoxel::dx, TrackVoxel::dy, TrackVoxel::dz, VoxelWorld::GetGroundHeight(), VoxelWorld::GetVoxel(), IsOnWorld(), piece, x_base, and z_base.
Referenced by CoasterBuildWindow::BuildTrackPiece(), CoasterBuildStateMouse::OnMouseButtonEvent(), CoasterInstance::PlaceTrackPieceInAdditions(), and CoasterBuildMode::UpdateDisplay().
bool PositionedTrackPiece::CanBeSuccessor (uint16 x, uint16 y, uint8 z, uint8 connect) const
Can this positioned track piece function as a successor for the given exit conditions?
Parameters
x Required X position.
y Required Y position.
z Required Z position.
connect Required entry connection.
Returns
This positioned track piece can be used as successor.
Definition at line 295 of file track_piece.cpp.
References piece, x_base, y_base, and z_base.
Referenced by CanBeSuccessor(), CoasterInstance::FindPredecessorPiece(), and CoasterInstance::MakePositionedPiecesLooping().
bool PositionedTrackPiece::CanBeSuccessor (const PositionedTrackPiece & pred) const
Can this positioned track piece function as a successor of piece pred?
Parameters
pred Previous positioned track piece.
Returns
This positioned track piece can be used as successor.
Definition at line 305 of file track_piece.cpp.
References CanBeSuccessor(), GetEndX(), GetEndY(), GetEndZ(), and piece.
uint16 PositionedTrackPiece::GetEndX () const inline
Get the X position of the exit voxel.
Returns
The X position of the exit voxel.
Definition at line 294 of file track_piece.h.
References x_base.
Referenced by CanBeSuccessor(), CoasterInstance::FindSuccessorPiece(), CoasterInstance::MakePositionedPiecesLooping(), and CoasterBuildWindow::SetupSelection().
uint16 PositionedTrackPiece::GetEndY () const inline
Get the Y position of the exit voxel.
Returns
The Y position of the exit voxel.
Definition at line 303 of file track_piece.h.
References y_base.
Referenced by CanBeSuccessor(), CoasterInstance::FindSuccessorPiece(), CoasterInstance::MakePositionedPiecesLooping(), and CoasterBuildWindow::SetupSelection().
uint8 PositionedTrackPiece::GetEndZ () const inline
Get the Z position of the exit voxel.
Returns
The Z position of the exit voxel.
Definition at line 312 of file track_piece.h.
References z_base.
Referenced by CanBeSuccessor(), CoasterInstance::FindSuccessorPiece(), CoasterInstance::MakePositionedPiecesLooping(), and CoasterBuildWindow::SetupSelection().
The documentation for this class was generated from the following files:
track_piece.h
track_piece.cpp