FreeRCT: RCSTBlock Class Reference
RCSTBlock Class Reference
'RCST' game block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int coaster_type
Type of roller coaster.
int platform_type
Type of platform.
int number_trains
Maximum number of trains at the roller coaster.
int number_cars
Maximum number of cars in a train.
std::shared_ptr< StringBundle > text
Text of the coaster (reference to a TEXT block).
std::list< std::shared_ptr
< TrackPieceNode > > track_blocks
Track pieces of the roller coaster.
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
'RCST' game block.
Definition at line 837 of file nodes.h.
Member Function Documentation
int RCSTBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 1585 of file nodes.cpp.
References FileWriter::AddBlock(), NamedBlock::blk_name, FileBlock::CheckEndSave(), coaster_type, number_cars, number_trains, platform_type, FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), FileBlock::SaveUInt8(), FileBlock::StartSave(), text, track_blocks, and NamedBlock::version.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp