FreeRCT: CoasterBuildState Class Reference
CoasterBuildState Class Reference abstract
State in the coaster build mouse mode.
Public Member Functions
CoasterBuildState (CoasterBuildMode &mode)
Constructor of a build mouse mode state.
virtual void OpenWindow (uint16 instance) const =0
Notification to the mouse mode that a coaster construction window has been opened.
virtual void CloseWindow (uint16 instance) const =0
Notification to the mouse mode that a coaster construction window has been closed.
virtual bool MayActivateMode () const =0
Query from the viewport whether the mouse mode may be activated.
virtual void ActivateMode (const Point16 &pos) const =0
Notification from the viewport that the mouse mode has been activated.
virtual void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) const =0
Notification from the viewport that the mouse has moved.
virtual void OnMouseButtonEvent (Viewport *vp, uint8 state) const =0
Notification from the viewport that a mouse button has changed value.
virtual void LeaveMode () const =0
Notification from the viewport that the mouse mode has been de-activated.
virtual bool EnableCursors () const =0
Query from the viewport whether the mouse mode wants to have cursors displayed.
virtual void ShowNoPiece (uint16 instance) const =0
Notification from the construction window to display no track piece.
virtual void SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction) const =0
Notification from the construction window to display a track piece attached to the mouse cursor.
virtual void DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, const XYZPoint16 &vox, TileEdge direction) const =0
Notification from the construction window to display a track piece at a given position.
Public Attributes
CoasterBuildMode *const mode
Coaster build mouse mode.
Detailed Description
State in the coaster build mouse mode.
Definition at line 622 of file coaster_gui.cpp.
Constructor & Destructor Documentation
CoasterBuildState::CoasterBuildState (CoasterBuildMode & mode) inline
Constructor of a build mouse mode state.
Parameters
mode Mouse mode reference.
Definition at line 628 of file coaster_gui.cpp.
Member Function Documentation
virtual void CoasterBuildState::OpenWindow (uint16 instance) const pure virtual
Notification to the mouse mode that a coaster construction window has been opened.
Parameters
instance Ride number of the window.
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::OpenWindow().
virtual void CoasterBuildState::CloseWindow (uint16 instance) const pure virtual
Notification to the mouse mode that a coaster construction window has been closed.
Parameters
instance Ride number of the window.
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::CloseWindow().
virtual bool CoasterBuildState::MayActivateMode () const pure virtual
Query from the viewport whether the mouse mode may be activated.
Returns
The mouse mode may be activated.
See also
MouseMode::MayActivateMode
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::MayActivateMode().
virtual void CoasterBuildState::ActivateMode (const Point16 & pos) const pure virtual
Notification from the viewport that the mouse mode has been activated.
Parameters
pos Current mouse position.
See also
MouseMode::ActivateMode
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::ActivateMode().
virtual void CoasterBuildState::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) const pure virtual
Notification from the viewport that the mouse has moved.
Parameters
vp The viewport.
old_pos Previous position of the mouse.
pos Current mouse position.
See also
MouseMode::OnMouseMoveEvent
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::OnMouseMoveEvent().
virtual void CoasterBuildState::OnMouseButtonEvent (Viewport * vp, uint8 state) const pure virtual
Notification from the viewport that a mouse button has changed value.
Parameters
vp The viewport.
state Old and new state of the mouse buttons.
See also
MouseMode::OnMouseButtonEvent
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::OnMouseButtonEvent().
virtual void CoasterBuildState::LeaveMode () const pure virtual
Notification from the viewport that the mouse mode has been de-activated.
See also
MouseMode::LeaveMode
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::LeaveMode().
virtual bool CoasterBuildState::EnableCursors () const pure virtual
Query from the viewport whether the mouse mode wants to have cursors displayed.
Returns
Cursors should be enabled.
See also
MouseMode::EnableCursors
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::EnableCursors().
virtual void CoasterBuildState::ShowNoPiece (uint16 instance) const pure virtual
Notification from the construction window to display no track piece.
Parameters
instance Ride number of the window.
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::ShowNoPiece().
virtual void CoasterBuildState::SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction) const pure virtual
Notification from the construction window to display a track piece attached to the mouse cursor.
Parameters
instance Ride number of the window.
piece Track piece to display.
direction Direction of building (to use with a cursor).
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::SelectPosition().
virtual void CoasterBuildState::DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, const XYZPoint16 & vox, TileEdge direction) const pure virtual
Notification from the construction window to display a track piece at a given position.
Parameters
instance Ride number of the window.
piece Track piece to display.
vox Position of the piece.
direction Direction of building (to use with a cursor).
Implemented in CoasterBuildStateStopping, CoasterBuildStateFixed, CoasterBuildStateMouse, CoasterBuildStateOn, CoasterBuildStateStarting, and CoasterBuildStateOff.
Referenced by CoasterBuildMode::DisplayPiece().
The documentation for this class was generated from the following file:
coaster_gui.cpp