FreeRCT: Language Class Reference
Language Class Reference
Class for retrieving language strings.
#include <language.h>
Public Member Functions
void Clear ()
Clear all loaded data.
uint16 RegisterStrings (const TextData &td, const char *const names[], uint16 base=STR_GENERIC_END)
Register loaded strings of rides etc.
const uint8 * GetText (StringID number)
Get string number number.
const uint8 * GetLanguageName (int lang_index)
Get the (native) name of a language.
Private Attributes
const TextString * registered [2048]
Registered strings.
uint first_free
'First' string index that is not allocated yet.
Detailed Description
Class for retrieving language strings.
Todo:
Implement me.
Definition at line 145 of file language.h.
Member Function Documentation
void Language::Clear ()
Clear all loaded data.
Definition at line 197 of file language.cpp.
References first_free, lengthof, and registered.
Referenced by UninitLanguage().
uint16 Language::RegisterStrings (const TextData & td, const char *const names[], uint16 base = STR_GENERIC_END)
Register loaded strings of rides etc.
with the language system.
Parameters
td Text data wrapper containing the loaded strings.
names Array of names to register.
base Base address of the strings.
Returns
Base offset for the registered strings. Add the index value of the names table to get the real string number.
Definition at line 210 of file language.cpp.
References first_free, TextString::name, registered, TextData::string_count, and TextData::strings.
Referenced by ShopType::Load(), CoasterType::Load(), and GuiSprites::LoadGSLP().
const uint8 * Language::GetText (StringID number)
Get string number number.
Parameters
number string number to get.
Returns
String corresponding to the number (not owned by the caller, so don't free it).
Definition at line 256 of file language.cpp.
References TextString::GetString(), lengthof, registered, and text.
Referenced by DrawText(), GetDateString(), and MoneyStrFmt().
const uint8 * Language::GetLanguageName (int lang_index)
Get the (native) name of a language.
Parameters
lang_index The language to look in.
Returns
The language name.
Definition at line 280 of file language.cpp.
References LANGUAGE_COUNT, TextString::languages, and registered.
Referenced by SettingWindow::OnClick().
Member Data Documentation
const TextString* Language::registered[2048] private
Registered strings.
Entries may be nullptr for unregistered or non-existing strings.
Definition at line 158 of file language.h.
Referenced by Clear(), GetLanguageName(), GetText(), and RegisterStrings().
The documentation for this class was generated from the following files:
language.h
language.cpp