FreeRCT: ErrorMessageWindow Class Reference
ErrorMessageWindow Class Reference
GUI window for showing an error message.
Public Member Functions
ErrorMessageWindow (StringID strid)
Constructor of the error message window.
void SetWidgetStringParameters (WidgetNumber wid_num) const override
Set string parameters of the data string of the widget.
virtual void OnDraw () override
Paint the window to the screen.
virtual void UpdateWidgetSize (WidgetNumber wid_num, BaseWidget *wid)
Allow for last minute changes in the initial widget size.
virtual void DrawWidget (WidgetNumber wid_num, const BaseWidget *wid) const
Draw custom contents of the widget.
virtual void SetSize (uint width, uint height)
Set the size of the window.
StringID TranslateStringNumber (StringID str_id) const
Translate the string number if necessary.
virtual void ResetSize ()
Reset the size of a window.
virtual void OnMouseMoveEvent (const Point16 &pos) override
Mouse moved to new position.
virtual WmMouseEvent OnMouseButtonEvent (uint8 state) override
Mouse buttons changed state.
virtual void OnMouseLeaveEvent () override
Mouse left window.
virtual void TimeoutCallback () override
Timeout callback.
virtual void SetHighlight (bool value) override
Enable or disable highlighting.
int GetWidgetScreenX (const BaseWidget *wid) const
Get the horizontal position of the top-left corner of a widget (of this window) at the screen.
int GetWidgetScreenY (const BaseWidget *wid) const
Get the vertical position of the top-left corner of a widget (of this window) at the screen.
void MarkWidgetDirty (WidgetNumber wnum)
Mark the specified widget as dirty (in need of repainting).
template<>
BaseWidget * GetWidget (WidgetNumber wnum)
Specialized template for BaseWidget.
template<>
const BaseWidget * GetWidget (WidgetNumber wnum) const
Specialized template for BaseWidget.
void SetPosition (int x, int y)
Set the position of the top-left corner of the window.
void SetPosition (Point32 pos)
Set the position of the top-left corner of the window.
virtual Point32 OnInitialPosition ()
Find a nice initial position for the new window.
void MarkDirty ()
Mark windows as being dirty (needing a repaint).
virtual void OnMouseWheelEvent (int direction)
Mousewheel rotated.
virtual void OnMouseEnterEvent ()
Mouse entered window.
virtual void OnChange (ChangeCode code, uint32 parameter)
An important (window-specific) change has happened.
Public Attributes
bool initialized
Flag telling widgets whether the window has already been initialized.
Rectangle32 rect
Screen area covered by the window.
const WindowTypes wtype
Window type.
const WindowNumber wnumber
Window number.
uint8 timeout
Timeout counter.
uint8 flags
Window flags.
Window * higher
Window above this window (managed by WindowManager).
Window * lower
Window below this window (managed by WindowManager).
Protected Member Functions
void SetupWidgetTree (const WidgetPart *parts, int length)
Construct the widget tree of the window, and initialize the window with it.
void SetScrolledWidget (WidgetNumber scrolled, WidgetNumber scrollbar)
Connect a scrollbar and a scrolled window with each other.
template<typename WID >
WID * GetWidget (WidgetNumber wnum)
Get the widget.
template<typename WID >
const WID * GetWidget (WidgetNumber wnum) const
Get the widget.
void SetWidgetChecked (WidgetNumber widget, bool value)
Set the checked state of the given widget.
bool IsWidgetChecked (WidgetNumber widget) const
Is widget widget checked?
void SetWidgetPressed (WidgetNumber widget, bool value)
Set the pressed state of the given widget.
bool IsWidgetPressed (WidgetNumber widget) const
Is widget widget pressed?
void SetWidgetShaded (WidgetNumber widget, bool value)
Set the shaded state of the given widget.
bool IsWidgetShaded (WidgetNumber widget) const
Is widget widget shaded?
void SetRadioButtonsSelected (const WidgetNumber *wids, WidgetNumber selected)
Change the state of a set of radio buttons (WT_RADIOBUTTON or bi-stable button widgets).
WidgetNumber GetSelectedRadioButton (const WidgetNumber *wids)
Find the currently selected widget from a set of radio buttons (WT_RADIOBUTTON or bi-stable button widgets).
virtual void OnClick (WidgetNumber widget, const Point16 &pos)
A click with the left button at a widget has been detected.
void SetShopType (const RideType *ride_type)
Set the string translation base for the generic strings of this window.
void ShowDropdownMenu (WidgetNumber widnum, const DropdownList &items, int selected_index, ColourRange colour=COL_RANGE_INVALID)
Shows a Dropdown Menu.
void ShowRecolourDropdown (WidgetNumber widnum, RecolourEntry *entry, ColourRange colour=COL_RANGE_INVALID)
Open a recolour dropdown from widget widnum.
Protected Attributes
Point16 mouse_pos
Mouse position relative to the window (negative coordinates means 'out of window').
const RideType * ride_type
Ride type being used by this window, for translating its strings. May be nullptr.
Private Attributes
StringID strid
The error message to be displayed.
Detailed Description
GUI window for showing an error message.
Definition at line 37 of file error_gui.cpp.
Constructor & Destructor Documentation
ErrorMessageWindow::ErrorMessageWindow (StringID strid)
Constructor of the error message window.
Parameters
strid StringID to show.
Definition at line 51 of file error_gui.cpp.
References lengthof, GuiWindow::SetupWidgetTree(), and strid.
Member Function Documentation
void ErrorMessageWindow::SetWidgetStringParameters (WidgetNumber wid_num) const override virtual
Set string parameters of the data string of the widget.
Parameters
wid_num Widget number of the widget.
Reimplemented from GuiWindow.
Definition at line 57 of file error_gui.cpp.
References _str_params, EMW_ERROR_MESSAGE, StringParameters::SetStrID(), and strid.
void GuiWindow::OnDraw () override virtual inherited
Paint the window to the screen.
Note
The window manager already locked the surface.
Reimplemented from Window.
Definition at line 450 of file window.cpp.
References _video, BaseWidget::Draw(), VideoSystem::DrawRectangle(), Window::flags, MakeRGBA(), OPAQUE, Window::rect, GuiWindow::tree, and WF_HIGHLIGHT.
void GuiWindow::UpdateWidgetSize (WidgetNumber wid_num, BaseWidget * wid) virtual inherited
Allow for last minute changes in the initial widget size.
If the function does nothing, you'll get the default widgets. The values BaseWidget::min_x and BaseWidget::min_y may be altered, but it may be a bad idea to make them smaller. BaseWidget::fill_x, BaseWidget::fill_y, BaseWidget::resize_x, BaseWidget::resize_y may also be changed. Since this function is being called while the window is being constructed, there is not much else that has a sane value at this point.
Parameters
wid_num Widget number of the provided widget.
wid The widget itself.
Reimplemented in BottomToolbarWindow, ShopManagerWindow, ToolbarWindow, DropdownMenuWindow, RideSelectGui, FenceGui, and PathBuildGui.
Definition at line 425 of file window.cpp.
Referenced by BaseWidget::SetupMinimalSize(), DataWidget::SetupMinimalSize(), and BackgroundWidget::SetupMinimalSize().
void GuiWindow::DrawWidget (WidgetNumber wid_num, const BaseWidget * wid) const virtual inherited
Draw custom contents of the widget.
The code should not do anything else but render contents to the screen.
Parameters
wid_num Widget number of the widget being drawn.
wid The widget itself.
Reimplemented in BottomToolbarWindow, RecolourDropdownWindow, RideSelectGui, DropdownMenuWindow, FenceGui, PathBuildGui, and TerraformGui.
Definition at line 445 of file window.cpp.
Referenced by BaseWidget::Draw(), DataWidget::Draw(), and BackgroundWidget::Draw().
void GuiWindow::SetSize (uint width, uint height) virtual inherited
Set the size of the window.
Parameters
width Initial width of the new window.
height Initial height of the new window.
Reimplemented from Window.
Definition at line 341 of file window.cpp.
StringID GuiWindow::TranslateStringNumber (StringID str_id) const inherited
Translate the string number if necessary.
Parameters
str_id String number to translate.
Returns
Translated string number.
Definition at line 360 of file window.cpp.
References RideType::GetString(), GuiWindow::ride_type, STR_GENERIC_SHOP_START, and STR_INVALID.
Referenced by DataWidget::Draw(), and DataWidget::SetupMinimalSize().
void GuiWindow::ResetSize () virtual inherited
Reset the size of a window.
Note
Only if the window is a GuiWindow.
Reimplemented from Window.
Definition at line 368 of file window.cpp.
References Rectangle< PT, SZ >::base, BaseWidget::min_x, Window::rect, BaseWidget::SetSmallestSizePosition(), BaseWidget::SetupMinimalSize(), GuiWindow::tree, GuiWindow::widgets, and Point< CT >::x.
Referenced by GuiWindow::SetupWidgetTree().
void GuiWindow::OnMouseMoveEvent (const Point16 & pos) override virtual inherited
Mouse moved to new position.
Parameters
pos New position.
Reimplemented from Window.
Definition at line 456 of file window.cpp.
References GuiWindow::mouse_pos.
WmMouseEvent GuiWindow::OnMouseButtonEvent (uint8 state) override virtual inherited
Mouse buttons changed state.
Parameters
state Updated state.
See also
MouseButtons
Returns
Action to perform as a result of the event (use WMME_NONE if no special action needed).
Reimplemented from Window.
Definition at line 461 of file window.cpp.
References Rectangle< PT, SZ >::base, BaseWidget::GetWidgetByPosition(), IsLeftClick(), LeafWidget::IsShaded(), BaseWidget::MarkDirty(), GuiWindow::mouse_pos, BaseWidget::number, GuiWindow::OnClick(), ScrollbarWidget::OnClick(), BaseWidget::pos, Window::rect, LeafWidget::SetPressed(), Window::timeout, GuiWindow::tree, WMME_CLOSE_WINDOW, WMME_MOVE_WINDOW, WMME_NONE, WT_CLOSEBOX, WT_IMAGE_PUSHBUTTON, WT_TEXT_PUSHBUTTON, WT_TITLEBAR, BaseWidget::wtype, Point< CT >::x, and Point< CT >::y.
void GuiWindow::OnMouseLeaveEvent () override virtual inherited
Mouse left window.
Reimplemented from Window.
Definition at line 491 of file window.cpp.
References GuiWindow::mouse_pos, Point< CT >::x, and Point< CT >::y.
void GuiWindow::TimeoutCallback () override virtual inherited
Timeout callback.
Called when timeout decremented to 0.
Reimplemented from Window.
Definition at line 614 of file window.cpp.
References BaseWidget::AutoRaiseButtons(), Rectangle< PT, SZ >::base, Window::flags, Window::rect, GuiWindow::SetHighlight(), GuiWindow::tree, and WF_HIGHLIGHT.
void GuiWindow::SetHighlight (bool value) override virtual inherited
Enable or disable highlighting.
Base class does nothing. If enabled, the timeout is used to automatically disable it again.
Parameters
value New highlight value.
Reimplemented from Window.
Definition at line 620 of file window.cpp.
References Window::flags, Window::MarkDirty(), Window::timeout, and WF_HIGHLIGHT.
Referenced by GuiWindow::GuiWindow(), and GuiWindow::TimeoutCallback().
int GuiWindow::GetWidgetScreenX (const BaseWidget * wid) const inline inherited
Get the horizontal position of the top-left corner of a widget (of this window) at the screen.
Parameters
wid Widget to use.
Returns
Horizontal position of the top-left corner of the widget at the screen.
Definition at line 184 of file window.h.
References Rectangle< PT, SZ >::base, BaseWidget::pos, Window::rect, and Point< CT >::x.
Referenced by LeafWidget::Draw(), DataWidget::Draw(), ScrollbarWidget::Draw(), BackgroundWidget::Draw(), TerraformGui::DrawWidget(), PathBuildGui::DrawWidget(), FenceGui::DrawWidget(), RideSelectGui::DrawWidget(), RecolourDropdownWindow::DrawWidget(), BottomToolbarWindow::DrawWidget(), FenceGui::OnClick(), GuiWindow::ShowDropdownMenu(), and GuiWindow::ShowRecolourDropdown().
int GuiWindow::GetWidgetScreenY (const BaseWidget * wid) const inline inherited
Get the vertical position of the top-left corner of a widget (of this window) at the screen.
Parameters
wid Widget to use.
Returns
Vertical position of the top-left corner of the widget at the screen.
Definition at line 194 of file window.h.
References Rectangle< PT, SZ >::base, BaseWidget::pos, Window::rect, and Point< CT >::y.
Referenced by LeafWidget::Draw(), DataWidget::Draw(), ScrollbarWidget::Draw(), BackgroundWidget::Draw(), TerraformGui::DrawWidget(), PathBuildGui::DrawWidget(), FenceGui::DrawWidget(), RideSelectGui::DrawWidget(), RecolourDropdownWindow::DrawWidget(), BottomToolbarWindow::DrawWidget(), FenceGui::OnClick(), GuiWindow::ShowDropdownMenu(), and GuiWindow::ShowRecolourDropdown().
void GuiWindow::MarkWidgetDirty (WidgetNumber wnum) inline inherited
Mark the specified widget as dirty (in need of repainting).
Parameters
wnum Widget to use.
Definition at line 295 of file window.h.
References Rectangle< PT, SZ >::base, BaseWidget::MarkDirty(), and Window::rect.
Referenced by ToolbarWindow::OnChange(), RideSelectGui::OnClick(), TerraformGui::Setlevelling(), and TerraformGui::SetTerraformSize().
void GuiWindow::SetupWidgetTree (const WidgetPart * parts, int length) protected inherited
Construct the widget tree of the window, and initialize the window with it.
Parameters
parts Widget parts describing the window.
length Number of parts.
Precondition
The tree has not been setup before.
Definition at line 383 of file window.cpp.
References GuiWindow::initialized, MakeWidgetTree(), Window::MarkDirty(), GuiWindow::num_widgets, Window::OnInitialPosition(), GuiWindow::ResetSize(), Window::SetPosition(), GuiWindow::tree, GuiWindow::widgets, Point< CT >::x, and Point< CT >::y.
Referenced by CoasterBuildWindow::CoasterBuildWindow(), CoasterInstanceWindow::CoasterInstanceWindow(), DropdownMenuWindow::DropdownMenuWindow(), ErrorMessageWindow(), GuestInfoWindow::GuestInfoWindow(), QuitProgramWindow::QuitProgramWindow(), RecolourDropdownWindow::RecolourDropdownWindow(), and ShopManagerWindow::ShopManagerWindow().
void GuiWindow::SetScrolledWidget (WidgetNumber scrolled, WidgetNumber scrollbar) protected inherited
Connect a scrollbar and a scrolled window with each other.
Parameters
scrolled Widget number of the widget being scrolled by the scrollbar.
scrollbar Scrollbar controlling the scrolled widget.
Precondition
The widgets must have been initialized.
Definition at line 410 of file window.cpp.
References ScrollbarWidget::SetScrolled().
template<typename WID > WID * GuiWindow::GetWidget (WidgetNumber wnum) inline protected inherited
Get the widget.
Template Parameters
WID Widget class.
Parameters
wnum Widget number to get.
Returns
Address of the widget.
Definition at line 248 of file window.h.
References GuiWindow::num_widgets, and GuiWindow::widgets.
template<typename WID > const WID * GuiWindow::GetWidget (WidgetNumber wnum) const inline protected inherited
Get the widget.
Template Parameters
WID Widget class.
Parameters
wnum Widget number to get.
Returns
Address of the widget.
Definition at line 261 of file window.h.
References GuiWindow::num_widgets, and GuiWindow::widgets.
template<> BaseWidget* GuiWindow::GetWidget (WidgetNumber wnum) inline inherited
Specialized template for BaseWidget.
Parameters
wnum Widget number to get.
Returns
Address of the base widget.
Definition at line 273 of file window.h.
References GuiWindow::num_widgets, and GuiWindow::widgets.
template<> const BaseWidget* GuiWindow::GetWidget (WidgetNumber wnum) const inline inherited
Specialized template for BaseWidget.
Parameters
wnum Widget number to get.
Returns
Address of the base widget.
Definition at line 285 of file window.h.
References GuiWindow::num_widgets, and GuiWindow::widgets.
void GuiWindow::SetWidgetChecked (WidgetNumber widget, bool value) protected inherited
Set the checked state of the given widget.
Parameters
widget Widget number.
value New checked state value.
Definition at line 511 of file window.cpp.
References Rectangle< PT, SZ >::base, LeafWidget::IsChecked(), BaseWidget::MarkDirty(), Window::rect, and LeafWidget::SetChecked().
Referenced by TerraformGui::Setlevelling(), GuiWindow::SetRadioButtonsSelected(), and ShopManagerWindow::SetShopToggleButtons().
bool GuiWindow::IsWidgetChecked (WidgetNumber widget) const protected inherited
Is widget widget checked?
Parameters
widget Widget number to use.
Returns
Whether the widget is checked.
Definition at line 525 of file window.cpp.
void GuiWindow::SetWidgetPressed (WidgetNumber widget, bool value) protected inherited
Set the pressed state of the given widget.
Parameters
widget Widget number.
value New pressed state value.
Definition at line 535 of file window.cpp.
References Rectangle< PT, SZ >::base, LeafWidget::IsPressed(), BaseWidget::MarkDirty(), Window::rect, and LeafWidget::SetPressed().
Referenced by RideSelectGui::OnChange(), RideSelectGui::OnClick(), PathBuildGui::SetButtons(), CoasterBuildWindow::SetButtons(), TerraformGui::Setlevelling(), RideSelectGui::SetNewRide(), and GuiWindow::SetRadioButtonsSelected().
bool GuiWindow::IsWidgetPressed (WidgetNumber widget) const protected inherited
Is widget widget pressed?
Parameters
widget Widget number to use.
Returns
Whether the widget is pressed.
Definition at line 549 of file window.cpp.
Referenced by RideSelectGui::OnClick(), CoasterBuildWindow::OnClick(), and RideSelectGui::SetNewRide().
void GuiWindow::SetWidgetShaded (WidgetNumber widget, bool value) protected inherited
Set the shaded state of the given widget.
Parameters
widget Widget number.
value New shaded state value.
Definition at line 559 of file window.cpp.
References Rectangle< PT, SZ >::base, LeafWidget::IsShaded(), BaseWidget::MarkDirty(), Window::rect, and LeafWidget::SetShaded().
Referenced by PathBuildGui::SetButtons(), CoasterBuildWindow::SetButtons(), and CoasterBuildWindow::SetupSelection().
bool GuiWindow::IsWidgetShaded (WidgetNumber widget) const protected inherited
Is widget widget shaded?
Parameters
widget Widget number to use.
Returns
Whether the widget is shaded.
Definition at line 573 of file window.cpp.
void GuiWindow::SetRadioButtonsSelected (const WidgetNumber * wids, WidgetNumber selected) protected inherited
Change the state of a set of radio buttons (WT_RADIOBUTTON or bi-stable button widgets).
Parameters
wids Array of widgets, terminate with INVALID_WIDGET_INDEX.
selected Current selected widget of the radio buttons.
Definition at line 583 of file window.cpp.
References INVALID_WIDGET_INDEX, GuiWindow::SetWidgetChecked(), GuiWindow::SetWidgetPressed(), WT_RADIOBUTTON, and BaseWidget::wtype.
Referenced by RideSelectGui::SetNewRideKind().
WidgetNumber GuiWindow::GetSelectedRadioButton (const WidgetNumber * wids) protected inherited
Find the currently selected widget from a set of radio buttons (WT_RADIOBUTTON or bi-stable button widgets).
Parameters
wids Array of widgets, terminate with INVALID_WIDGET_INDEX.
Returns
Currently pressed widget, or INVALID_WIDGET_INDEX if none found.
Definition at line 601 of file window.cpp.
References INVALID_WIDGET_INDEX, LeafWidget::IsChecked(), LeafWidget::IsPressed(), LeafWidget::IsShaded(), WT_RADIOBUTTON, and BaseWidget::wtype.
void GuiWindow::OnClick (WidgetNumber widget, const Point16 & pos) protected virtual inherited
A click with the left button at a widget has been detected.
Parameters
widget Widget number.
pos Position in the widget.
Reimplemented in QuitProgramWindow, CoasterBuildWindow, RecolourDropdownWindow, ShopManagerWindow, RideSelectGui, ToolbarWindow, DropdownMenuWindow, PathBuildGui, FenceGui, TerraformGui, and SettingWindow.
Definition at line 502 of file window.cpp.
Referenced by GuiWindow::OnMouseButtonEvent().
void GuiWindow::SetShopType (const RideType * ride_type) protected inherited
Set the string translation base for the generic strings of this window.
Parameters
ride_type Ride type to use as base for the string translation.
Definition at line 350 of file window.cpp.
References GuiWindow::ride_type.
Referenced by ShopManagerWindow::ShopManagerWindow().
void GuiWindow::ShowDropdownMenu (WidgetNumber widnum, const DropdownList & items, int selected_index, ColourRange colour = COL_RANGE_INVALID) protected inherited
Shows a Dropdown Menu.
Parameters
widnum Associated dropdown button.
items List of items to show in the list.
selected_index Currently selected item in the list.
colour Requested colour of dropdown.
Definition at line 148 of file dropdown.cpp.
References _manager, ALL_WINDOWS_OF_TYPE, COL_RANGE_INVALID, LeafWidget::colour, WindowManager::DeleteWindow(), DropdownMenuWindow::DropdownMenuWindow(), GuiWindow::GetWidgetScreenX(), GuiWindow::GetWidgetScreenY(), GetWindowByType(), Rectangle< PT, SZ >::height, BaseWidget::min_x, BaseWidget::pos, WC_DROPDOWN, Window::wnumber, WT_DROPDOWN_BUTTON, BaseWidget::wtype, and Window::wtype.
Referenced by SettingWindow::OnClick().
void GuiWindow::ShowRecolourDropdown (WidgetNumber widnum, RecolourEntry * entry, ColourRange colour = COL_RANGE_INVALID) protected inherited
Open a recolour dropdown from widget widnum.
Parameters
widnum Associated dropdown button.
entry Recolour entry being changed (will be changed when clicked on a selectable different colour).
colour Requested colour of dropdown.
Definition at line 273 of file dropdown.cpp.
References _manager, ALL_WINDOWS_OF_TYPE, COL_RANGE_INVALID, LeafWidget::colour, WindowManager::DeleteWindow(), GuiWindow::GetWidgetScreenX(), GuiWindow::GetWidgetScreenY(), GetWindowByType(), Rectangle< PT, SZ >::height, BaseWidget::pos, WC_DROPDOWN, Window::wnumber, WT_DROPDOWN_BUTTON, BaseWidget::wtype, and Window::wtype.
Referenced by ShopManagerWindow::OnClick().
void Window::SetPosition (int x, int y) inherited
Set the position of the top-left corner of the window.
Parameters
x X position.
y Y position.
Definition at line 92 of file window.cpp.
Referenced by DropdownMenuWindow::DropdownMenuWindow(), WindowManager::MouseMoveEvent(), RecolourDropdownWindow::RecolourDropdownWindow(), GuiWindow::SetupWidgetTree(), and Viewport::Viewport().
void Window::SetPosition (Point32 pos) inherited
Set the position of the top-left corner of the window.
Parameters
pos Point to set to.
Definition at line 101 of file window.cpp.
References Rectangle< PT, SZ >::base, and Window::rect.
Point32 Window::OnInitialPosition () virtual inherited
Find a nice initial position for the new window.
Returns
Initial position of the window.
Reimplemented in QuitProgramWindow, BottomToolbarWindow, and ToolbarWindow.
Definition at line 217 of file window.cpp.
References ComputeInitialPosition::FindPosition().
Referenced by GuiWindow::SetupWidgetTree().
void Window::MarkDirty () inherited
Mark windows as being dirty (needing a repaint).
Todo:
Marking the whole display as needing a repaint is too crude.
Definition at line 228 of file window.cpp.
References _video, VideoSystem::MarkDisplayDirty(), and Window::rect.
Referenced by WindowManager::DeleteWindow(), WindowManager::MouseMoveEvent(), Viewport::MoveViewport(), GuestInfoWindow::OnChange(), ShopManagerWindow::OnChange(), BottomToolbarWindow::OnChange(), RideSelectGui::OnClick(), WindowManager::RaiseWindow(), Viewport::Rotate(), GuiWindow::SetHighlight(), and GuiWindow::SetupWidgetTree().
void Window::OnMouseWheelEvent (int direction) virtual inherited
Mousewheel rotated.
Parameters
direction Direction of change (+1 or -1).
Reimplemented in Viewport.
Definition at line 263 of file window.cpp.
Referenced by WindowManager::MouseWheelEvent().
void Window::OnMouseEnterEvent () virtual inherited
Mouse entered window.
Definition at line 268 of file window.cpp.
Referenced by WindowManager::UpdateCurrentWindow().
void Window::OnChange (ChangeCode code, uint32 parameter) virtual inherited
An important (window-specific) change has happened.
Parameters
code Unique identification of the change.
parameter Parameter of the code.
Note
Meaning of number values are documented near this method in derived classes.
Reimplemented in CoasterBuildWindow, BottomToolbarWindow, ShopManagerWindow, GuestInfoWindow, RideSelectGui, ToolbarWindow, PathBuildGui, FenceGui, and SettingWindow.
Definition at line 300 of file window.cpp.
Referenced by NotifyChange().
Member Data Documentation
uint8 Window::timeout inherited
Timeout counter.
Decremented on each iteration. When it reaches 0, TimeoutCallback is called.
Definition at line 131 of file window.h.
Referenced by Viewport::DisableWorldAdditions(), Viewport::EnableWorldAdditions(), Viewport::EnsureAdditionsAreVisible(), GuiWindow::OnMouseButtonEvent(), GuiWindow::SetHighlight(), WindowManager::Tick(), Viewport::TimeoutCallback(), and Window::Window().
uint8 Window::flags inherited
Window flags.
See also
WindowFlags
Definition at line 132 of file window.h.
Referenced by GuiWindow::OnDraw(), GuiWindow::SetHighlight(), GuiWindow::TimeoutCallback(), and Window::Window().
The documentation for this class was generated from the following file:
error_gui.cpp