FreeRCT: VoxelWorld Class Reference
VoxelWorld Class Reference
World map data and code
A world of voxels.
#include <map.h>
Public Member Functions
VoxelWorld ()
Default constructor of the voxel world.
void SetWorldSize (uint16 xs, uint16 ys)
Create a new world.
void MakeFlatWorld (int16 z)
Creates a world of flat tiles.
VoxelStack * GetModifyStack (uint16 x, uint16 y)
Get a voxel stack.
const VoxelStack * GetStack (uint16 x, uint16 y) const
Get a voxel stack (for read-only access).
uint8 GetGroundHeight (uint16 x, uint16 y) const
Return the base height of the ground at the given voxel stack.
void MoveStack (uint16 x, uint16 y, VoxelStack *old_stack)
Move a voxel stack to this world.
const Voxel * GetVoxel (const XYZPoint16 &vox) const
Get a voxel in the world by voxel coordinate.
Voxel * GetCreateVoxel (const XYZPoint16 &vox, bool create)
Get a voxel in the world by voxel coordinate.
uint16 GetXSize () const
Get X voxel size of the world.
uint16 GetYSize () const
Get Y voxel size of the world.
bool VoxelExists (const XYZPoint16 &vox) const
Does the provided voxel exist in the world?
TileOwner GetTileOwner (uint16 x, uint16 y)
Get the ownership of a tile.
void SetTileOwner (uint16 x, uint16 y, TileOwner owner)
Set the ownership of a tile.
void SetTileOwnerRect (uint16 x, uint16 y, uint16 width, uint16 height, TileOwner owner)
Set tile ownership for a rectangular area.
void SetTileOwnerGlobally (TileOwner owner)
Set an owner for all tiles in the world.
void Save (Saver &svr) const
Save the world to a file.
void Load (Loader &ldr)
Load the world from a file.
Private Attributes
uint16 x_size
Current max x size (in voxels).
uint16 y_size
Current max y size (in voxels).
VoxelStack stacks [WORLD_X_SIZE *WORLD_Y_SIZE]
All voxel stacks in the world.
Detailed Description
A world of voxels.
Definition at line 487 of file map.h.
Constructor & Destructor Documentation
VoxelWorld::VoxelWorld ()
Default constructor of the voxel world.
Definition at line 253 of file map.cpp.
References x_size, and y_size.
Member Function Documentation
void VoxelWorld::SetWorldSize (uint16 xs, uint16 ys)
Create a new world.
Everything gets cleared.
Parameters
xs X size of the world.
ys Y size of the world.
Definition at line 264 of file map.cpp.
References VoxelStack::Clear(), stacks, WORLD_X_SIZE, WORLD_Y_SIZE, x_size, and y_size.
Referenced by Load(), and StartNewGame().
void VoxelWorld::MakeFlatWorld (int16 z)
Creates a world of flat tiles.
Parameters
z Height of the tiles.
Definition at line 303 of file map.cpp.
References AddFoundations(), Voxel::ClearInstances(), FDT_INVALID, GetCreateVoxel(), GTP_GRASS0, ImplodeTileSlope(), Voxel::SetFoundationType(), Voxel::SetGroundSlope(), Voxel::SetGroundType(), SL_FLAT, x_size, and y_size.
Referenced by Load(), and StartNewGame().
VoxelStack * VoxelWorld::GetModifyStack (uint16 x, uint16 y)
Get a voxel stack.
Parameters
x X coordinate of the stack.
y Y coordinate of the stack.
Returns
The requested voxel stack.
Precondition
The coordinate must exist within the world.
Definition at line 439 of file map.cpp.
References stacks, WORLD_X_SIZE, WORLD_Y_SIZE, x_size, and y_size.
Referenced by GetCreateVoxel(), Load(), MoveStack(), FenceBuildManager::OnMouseButtonEvent(), SetTileOwner(), SetTileOwnerRect(), and UpdateLandBorderFence().
const VoxelStack * VoxelWorld::GetStack (uint16 x, uint16 y) const
Get a voxel stack (for read-only access).
Parameters
x X coordinate of the stack.
y Y coordinate of the stack.
Returns
The requested voxel stack.
Precondition
The coordinate must exist within the world.
Definition at line 454 of file map.cpp.
References stacks, WORLD_X_SIZE, WORLD_Y_SIZE, x_size, and y_size.
Referenced by BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), VoxelCollector::Collect(), Guest::DecideMoveDirection(), GetGroundHeight(), WorldAdditions::GetModifyStack(), GetParkEntryDirection(), WorldAdditions::GetStack(), GetTileOwner(), GetVoxel(), RemovePath(), Save(), and VoxelExists().
uint8 VoxelWorld::GetGroundHeight (uint16 x, uint16 y) const
Return the base height of the ground at the given voxel stack.
Parameters
x Horizontal position.
y Vertical position.
Returns
Height of the ground (for steep slopes, the base voxel height).
Definition at line 468 of file map.cpp.
References VoxelStack::base, VoxelStack::GetGroundOffset(), and GetStack().
Referenced by Person::Activate(), PositionedTrackPiece::CanBePlaced(), ChangeTileCursorMode(), GetGoHomeDirection(), TerrainChanges::GetGroundData(), MultiCursor::GetZpos(), and IsGoodEdgeRoad().
void VoxelWorld::MoveStack (uint16 x, uint16 y, VoxelStack * old_stack) inline
Move a voxel stack to this world.
May destroy the original stack in the process.
Parameters
x X coordinate of the stack.
y Y coordinate of the stack.
old_stack Source stack.
Definition at line 504 of file map.h.
References GetModifyStack(), and VoxelStack::MoveStack().
Referenced by WorldAdditions::Commit().
const Voxel* VoxelWorld::GetVoxel (const XYZPoint16 & vox) const inline
Get a voxel in the world by voxel coordinate.
Parameters
vox Coordinate of the voxel.
Returns
Address of the voxel (if it exists).
Definition at line 514 of file map.h.
References VoxelStack::Get(), GetStack(), XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by PositionedTrackPiece::CanBePlaced(), CanBuildPathFromEdge(), ShopPlacementManager::CanPlaceShop(), TerrainChanges::GetGroundData(), GetPathAttachPoints(), PathBuildManager::GetRemoveIsEnabled(), GetZHeight(), IsGoodEdgeRoad(), Viewport::MarkVoxelDirty(), PathBuildManager::MoveCursor(), PathExistsAtBottomEdge(), RideExistsAtBottom(), PathSearcher::Search(), PathBuildManager::SelectBuyRemove(), PathBuildManager::SelectMovement(), FenceBuildManager::SetCursors(), and TravelQueuePath().
Voxel* VoxelWorld::GetCreateVoxel (const XYZPoint16 & vox, bool create) inline
Get a voxel in the world by voxel coordinate.
Parameters
vox Coordinate of the voxel.
create If the requested voxel does not exist, try to create it.
Returns
Address of the voxel (if it exists or could be created).
Definition at line 525 of file map.h.
References VoxelStack::GetCreate(), GetModifyStack(), XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by Person::Activate(), AddFoundations(), Person::DeActivate(), ExamineNeighbourPathEdge(), Guest::ExitRide(), MakeFlatWorld(), Person::OnAnimate(), DisplayCoasterCar::Set(), FenceBuildManager::SetCursors(), and PathBuildManager::TileClicked().
uint16 VoxelWorld::GetXSize () const inline
Get X voxel size of the world.
Returns
Length of the world in X direction.
Definition at line 534 of file map.h.
References x_size.
Referenced by Person::Activate(), ChangeTileCursorMode(), VoxelCollector::Collect(), PathBuildManager::ComputeNewLongPath(), ShopPlacementManager::ComputeShopVoxel(), FindEdgeRoad(), Person::GetInparkDirections(), GetParkEntryDirection(), IsVoxelstackInsideWorld(), PathBuildManager::MoveCursor(), Viewport::MoveViewport(), Save(), PathSearcher::Search(), PathBuildManager::SelectLong(), MultiCursor::SetCursor(), SetTileOwnerGlobally(), SetXFoundations(), StartNewGame(), TerrainChanges::TerrainChanges(), and UpdateLandBorderFence().
uint16 VoxelWorld::GetYSize () const inline
Get Y voxel size of the world.
Returns
Length of the world in Y direction.
Definition at line 543 of file map.h.
References y_size.
Referenced by ChangeTileCursorMode(), VoxelCollector::Collect(), PathBuildManager::ComputeNewLongPath(), ShopPlacementManager::ComputeShopVoxel(), FindEdgeRoad(), Person::GetInparkDirections(), GetParkEntryDirection(), IsVoxelstackInsideWorld(), PathBuildManager::MoveCursor(), Viewport::MoveViewport(), Save(), PathSearcher::Search(), PathBuildManager::SelectLong(), MultiCursor::SetCursor(), SetTileOwnerGlobally(), SetYFoundations(), StartNewGame(), TerrainChanges::TerrainChanges(), UpdateLandBorderFence(), and VoxelExists().
bool VoxelWorld::VoxelExists (const XYZPoint16 & vox) const inline
Does the provided voxel exist in the world?
Parameters
vox Coordinate of the voxel.
Returns
Whether a voxel with content exists at the given position.
Definition at line 553 of file map.h.
References VoxelStack::base, GetStack(), GetYSize(), VoxelStack::height, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by Person::DeActivate().
TileOwner VoxelWorld::GetTileOwner (uint16 x, uint16 y)
Get the ownership of a tile.
Parameters
x X coordinate of the tile.
y Y coordinate of the tile.
Returns
Ownership of the tile.
Definition at line 482 of file map.cpp.
References GetStack(), and VoxelStack::owner.
Referenced by BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), CanBuildPathFromEdge(), ShopPlacementManager::CanPlaceShop(), ChangeAreaCursorMode(), TerrainChanges::ChangeCorner(), ChangeTileCursorMode(), Person::GetInparkDirections(), PathBuildManager::MoveCursor(), FenceBuildManager::OnMouseButtonEvent(), RemovePath(), ShopInstance::SetRide(), and UpdateLandBorderFence().
void VoxelWorld::SetTileOwner (uint16 x, uint16 y, TileOwner owner)
Set the ownership of a tile.
Parameters
x X coordinate of the tile.
y Y coordinate of the tile.
owner Ownership of the tile.
Definition at line 553 of file map.cpp.
References GetModifyStack(), VoxelStack::owner, and UpdateLandBorderFence().
void VoxelWorld::SetTileOwnerRect (uint16 x, uint16 y, uint16 width, uint16 height, TileOwner owner)
Set tile ownership for a rectangular area.
Parameters
x Base X coordinate of the rectangle.
y Base Y coordinate of the rectangle.
width Length in X direction of the rectangle.
height Length in Y direction of the rectangle.
owner New owner of all tiles in the rectangle.
Definition at line 568 of file map.cpp.
References GetModifyStack(), VoxelStack::owner, and UpdateLandBorderFence().
Referenced by SetTileOwnerGlobally(), and StartNewGame().
void VoxelWorld::SetTileOwnerGlobally (TileOwner owner)
Set an owner for all tiles in the world.
Parameters
owner New owner of all tiles.
Definition at line 583 of file map.cpp.
References GetXSize(), GetYSize(), and SetTileOwnerRect().
Referenced by StartNewGame().
void VoxelWorld::Save (Saver & svr) const
Save the world to a file.
Parameters
svr Output stream to save to.
Definition at line 626 of file map.cpp.
References Saver::EndBlock(), GetStack(), GetXSize(), GetYSize(), Saver::PutWord(), VoxelStack::Save(), and Saver::StartBlock().
Referenced by SaveElements().
void VoxelWorld::Load (Loader & ldr)
Load the world from a file.
Parameters
ldr Input stream to read from.
Definition at line 592 of file map.cpp.
References Loader::CloseBlock(), GetModifyStack(), Loader::GetWord(), Loader::IsFail(), VoxelStack::Load(), MakeFlatWorld(), Loader::OpenBlock(), Loader::SetFailMessage(), SetWorldSize(), WORLD_X_SIZE, and WORLD_Y_SIZE.
Referenced by LoadElements().
The documentation for this class was generated from the following files:
map.h
map.cpp