FreeRCT: MouseModes Class Reference
MouseModes Class Reference
All mouse modes.
#include <viewport.h>
Public Member Functions
void RegisterMode (MouseMode *mm)
Register a mouse mode.
void SetViewportMousemode ()
Decide the most appropriate mouse mode of the viewport, depending on available windows.
ViewportMouseMode GetMouseMode ()
Get the current mouse mode.
void SetMouseMode (ViewportMouseMode mode)
Try to switch to a given mouse mode.
void SwitchMode (MouseMode *new_mode)
Switch to a new mouse mode.
Public Attributes
Viewport * main_display
Main screen, managed by Viewport.
MouseMode * current
Current mouse mode.
MouseMode * modes [MM_COUNT]
Registered mouse modes.
Private Attributes
DefaultMouseMode default_mode
Dummy mouse mode (MM_INACTIVE mode).
Detailed Description
All mouse modes.
Definition at line 315 of file viewport.h.
Member Function Documentation
void MouseModes::RegisterMode (MouseMode * mm)
Register a mouse mode.
Parameters
mm Mouse mode to register.
Definition at line 1676 of file viewport.cpp.
References MM_COUNT, MouseMode::mode, and modes.
Referenced by InitMouseModes().
void MouseModes::SetViewportMousemode ()
Decide the most appropriate mouse mode of the viewport, depending on available windows.
Todo:
Perhaps force a redraw/recompute in some way to ensure the right state is displayed?
Perhaps switch mode when a window associated with a mode is raised?
Definition at line 1709 of file viewport.cpp.
References _window_manager, default_mode, lengthof, Window::lower, main_display, MouseMode::MayActivateMode(), modes, SwitchMode(), WindowManager::top, WC_NONE, Window::wtype, and MouseMode::wtype.
Referenced by FenceBuildManager::CloseWindow(), ShopPlacementManager::CloseWindow(), TileTerraformMouseMode::CloseWindow(), CoasterBuildStateOn::CloseWindow(), CoasterBuildStateMouse::CloseWindow(), CoasterBuildStateFixed::CloseWindow(), ShopPlacementManager::OnMouseButtonEvent(), PathBuildManager::SetPathGuiState(), ShopPlacementManager::SetSelection(), and ShowMainDisplay().
ViewportMouseMode MouseModes::GetMouseMode ()
Get the current mouse mode.
Returns
The current mouse mode.
Definition at line 1771 of file viewport.cpp.
References current, and MouseMode::mode.
Referenced by TerrainChanges::ModifyWorld(), and PathBuildManager::SetPathGuiState().
void MouseModes::SetMouseMode (ViewportMouseMode mode)
Try to switch to a given mouse mode.
Parameters
mode Mode to switch to.
Definition at line 1741 of file viewport.cpp.
References lengthof, MouseMode::MayActivateMode(), MouseMode::mode, modes, and SwitchMode().
Referenced by CoasterBuildWindow::CoasterBuildWindow(), FenceBuildManager::OpenWindow(), TileTerraformMouseMode::OpenWindow(), ShopPlacementManager::SetSelection(), and ShutdownGame().
void MouseModes::SwitchMode (MouseMode * new_mode)
Switch to a new mouse mode.
Parameters
new_mode Mode to switch to.
Precondition
New mode must allow activation of its mode.
Definition at line 1757 of file viewport.cpp.
References MouseMode::ActivateMode(), current, MouseMode::LeaveMode(), main_display, MouseMode::MayActivateMode(), and Viewport::mouse_pos.
Referenced by SetMouseMode(), and SetViewportMousemode().
The documentation for this class was generated from the following files:
viewport.h
viewport.cpp