FreeRCT: SheetBlock Class Reference
SheetBlock Class Reference
Block containing a sprite sheet.
#include <nodes.h>
Public Member Functions
SheetBlock (const Position &pos)
Constructor of a sprite sheet.
std::shared_ptr< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos) override
Get a subnode for the given row and col.
Image * GetSheet ()
Get the sprite sheet.
Public Attributes
Position pos
Line number defining the sheet.
std::string file
Name of the file containing the sprite sheet.
std::string recolour
Name of the file containing 32bpp recolour information ("" means no file).
int x_base
Horizontal base offset in the sheet.
int y_base
Vertical base offset in the sheet.
int x_step
Column step size.
int y_step
Row step size.
int x_count
Number of sprites horizontally (-1 means 'infinite').
int y_count
Number of sprites vertically (-1 means 'infinite').
int x_offset
Sprite offset (from the origin to the left edge of the sprite).
int y_offset
Sprite offset (from the origin to the top edge of the sprite).
int width
Width of a sprite.
int height
Height of a sprite.
bool crop
Crop sprite.
ImageFile * imf
Loaded image file.
Image * img_sheet
Sheet of images.
std::shared_ptr< BitMask > mask
Bit mask to apply first (if available).
ImageFile * rmf
Loaded recolour file.
Image8bpp * rim
Recolour image.
Detailed Description
Block containing a sprite sheet.
Definition at line 130 of file nodes.h.
Constructor & Destructor Documentation
SheetBlock::SheetBlock (const Position & pos)
Constructor of a sprite sheet.
Parameters
pos Position of the sheet node.
Definition at line 265 of file nodes.cpp.
References imf, img_sheet, rim, and rmf.
Member Function Documentation
std::shared_ptr< BlockNode > SheetBlock::GetSubNode (int row, int col, const char * name, const Position & pos) override virtual
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented from BlockNode.
Definition at line 320 of file nodes.cpp.
References crop, GetSheet(), height, Position::ToString(), width, x_base, x_count, x_offset, x_step, y_base, y_count, y_offset, and y_step.
Image * SheetBlock::GetSheet ()
Get the sprite sheet.
Loads the sheet from the disk on the first call.
Returns
The loaded image.
Definition at line 285 of file nodes.cpp.
References file, imf, img_sheet, ImageFile::Is8bpp(), ImageFile::LoadFile(), mask, pos, recolour, rim, rmf, Image32bpp::SetRecolourImage(), and Position::ToString().
Referenced by GetSubNode().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp