FreeRCT: Window Class Reference
Window Class Reference
%Window code
Window base class.
#include <window.h>
Public Member Functions
Window (WindowTypes wtype, WindowNumber wnumber)
Window constructor.
virtual ~Window ()
Destructor.
virtual void SetSize (uint width, uint height)
Set the initial size of a window.
void SetPosition (int x, int y)
Set the position of the top-left corner of the window.
void SetPosition (Point32 pos)
Set the position of the top-left corner of the window.
virtual Point32 OnInitialPosition ()
Find a nice initial position for the new window.
void MarkDirty ()
Mark windows as being dirty (needing a repaint).
virtual void OnDraw ()
Paint the window to the screen.
virtual void OnMouseMoveEvent (const Point16 &pos)
Mouse moved to new position.
virtual WmMouseEvent OnMouseButtonEvent (uint8 state)
Mouse buttons changed state.
virtual void OnMouseWheelEvent (int direction)
Mousewheel rotated.
virtual void OnMouseEnterEvent ()
Mouse entered window.
virtual void OnMouseLeaveEvent ()
Mouse left window.
virtual void TimeoutCallback ()
Timeout callback.
virtual void SetHighlight (bool value)
Enable or disable highlighting.
virtual void OnChange (ChangeCode code, uint32 parameter)
An important (window-specific) change has happened.
virtual void ResetSize ()
Reset the size of a window.
Public Attributes
Rectangle32 rect
Screen area covered by the window.
const WindowTypes wtype
Window type.
const WindowNumber wnumber
Window number.
uint8 timeout
Timeout counter.
uint8 flags
Window flags.
Window * higher
Window above this window (managed by WindowManager).
Window * lower
Window below this window (managed by WindowManager).
Detailed Description
Window base class.
Definition at line 134 of file window.h.
Constructor & Destructor Documentation
Window::Window (WindowTypes wtype, WindowNumber wnumber)
Window constructor.
It automatically adds the window to the window stack.
Parameters
wtype Window type Type of window.
wnumber Number of the window within the wtype.
Definition at line 57 of file window.cpp.
References WindowManager::AddToStack(), flags, higher, lower, and timeout.
Window::~Window () virtual
Destructor.
Do not call directly, use WindowManager::DeleteWindow instead.
Definition at line 71 of file window.cpp.
References WindowManager::HasWindow().
Member Function Documentation
void Window::SetSize (uint width, uint height) virtual
Set the initial size of a window.
Parameters
width Initial width of the new window.
height Initial height of the new window.
Reimplemented in GuiWindow.
Definition at line 81 of file window.cpp.
References Rectangle< PT, SZ >::height, rect, and Rectangle< PT, SZ >::width.
Referenced by VideoSystem::SetResolution(), and Viewport::Viewport().
void Window::SetPosition (int x, int y)
Set the position of the top-left corner of the window.
Parameters
x X position.
y Y position.
Definition at line 92 of file window.cpp.
Referenced by DropdownMenuWindow::DropdownMenuWindow(), WindowManager::MouseMoveEvent(), RecolourDropdownWindow::RecolourDropdownWindow(), GuiWindow::SetupWidgetTree(), and Viewport::Viewport().
void Window::SetPosition (Point32 pos)
Set the position of the top-left corner of the window.
Parameters
pos Point to set to.
Definition at line 101 of file window.cpp.
References Rectangle< PT, SZ >::base, and rect.
Point32 Window::OnInitialPosition () virtual
Find a nice initial position for the new window.
Returns
Initial position of the window.
Reimplemented in QuitProgramWindow, BottomToolbarWindow, and ToolbarWindow.
Definition at line 217 of file window.cpp.
References ComputeInitialPosition::FindPosition().
Referenced by GuiWindow::SetupWidgetTree().
void Window::MarkDirty ()
Mark windows as being dirty (needing a repaint).
Todo:
Marking the whole display as needing a repaint is too crude.
Definition at line 228 of file window.cpp.
References _video, VideoSystem::MarkDisplayDirty(), and rect.
Referenced by WindowManager::DeleteWindow(), WindowManager::MouseMoveEvent(), Viewport::MoveViewport(), GuestInfoWindow::OnChange(), ShopManagerWindow::OnChange(), BottomToolbarWindow::OnChange(), RideSelectGui::OnClick(), WindowManager::RaiseWindow(), Viewport::Rotate(), GuiWindow::SetHighlight(), Viewport::SetUndergroundMode(), GuiWindow::SetupWidgetTree(), and Viewport::ToggleUndergroundMode().
void Window::OnDraw () virtual
Paint the window to the screen.
Note
The window manager already locked the surface.
Reimplemented in Viewport, and GuiWindow.
Definition at line 237 of file window.cpp.
Referenced by UpdateWindows().
void Window::OnMouseMoveEvent (const Point16 & pos) virtual
Mouse moved to new position.
Parameters
pos New position.
Reimplemented in Viewport, and GuiWindow.
Definition at line 245 of file window.cpp.
Referenced by WindowManager::MouseMoveEvent().
WmMouseEvent Window::OnMouseButtonEvent (uint8 state) virtual
Mouse buttons changed state.
Parameters
state Updated state.
See also
MouseButtons
Returns
Action to perform as a result of the event (use WMME_NONE if no special action needed).
Reimplemented in Viewport, and GuiWindow.
Definition at line 254 of file window.cpp.
References WMME_NONE.
Referenced by WindowManager::MouseButtonEvent().
void Window::OnMouseWheelEvent (int direction) virtual
Mousewheel rotated.
Parameters
direction Direction of change (+1 or -1).
Reimplemented in Viewport.
Definition at line 263 of file window.cpp.
Referenced by WindowManager::MouseWheelEvent().
void Window::OnMouseEnterEvent () virtual
Mouse entered window.
Definition at line 268 of file window.cpp.
Referenced by WindowManager::UpdateCurrentWindow().
void Window::OnMouseLeaveEvent () virtual
Mouse left window.
Reimplemented in GuiWindow.
Definition at line 273 of file window.cpp.
Referenced by WindowManager::UpdateCurrentWindow().
void Window::TimeoutCallback () virtual
Timeout callback.
Called when timeout decremented to 0.
Reimplemented in Viewport, and GuiWindow.
Definition at line 281 of file window.cpp.
Referenced by WindowManager::Tick().
void Window::SetHighlight (bool value) virtual
Enable or disable highlighting.
Base class does nothing. If enabled, the timeout is used to automatically disable it again.
Parameters
value New highlight value.
Reimplemented in GuiWindow.
Definition at line 290 of file window.cpp.
Referenced by HighlightWindowByType().
void Window::OnChange (ChangeCode code, uint32 parameter) virtual
An important (window-specific) change has happened.
Parameters
code Unique identification of the change.
parameter Parameter of the code.
Note
Meaning of number values are documented near this method in derived classes.
Reimplemented in CoasterBuildWindow, BottomToolbarWindow, ShopManagerWindow, GuestInfoWindow, RideSelectGui, ToolbarWindow, PathBuildGui, FenceGui, and SettingWindow.
Definition at line 300 of file window.cpp.
Referenced by NotifyChange().
void Window::ResetSize () virtual
Reset the size of a window.
Note
Only if the window is a GuiWindow.
Reimplemented in GuiWindow.
Definition at line 308 of file window.cpp.
Member Data Documentation
uint8 Window::timeout
Timeout counter.
Decremented on each iteration. When it reaches 0, TimeoutCallback is called.
Definition at line 147 of file window.h.
Referenced by Viewport::DisableWorldAdditions(), Viewport::EnableWorldAdditions(), Viewport::EnsureAdditionsAreVisible(), GuiWindow::OnMouseButtonEvent(), GuiWindow::SetHighlight(), WindowManager::Tick(), Viewport::TimeoutCallback(), and Window().
uint8 Window::flags
Window flags.
See also
WindowFlags
Definition at line 148 of file window.h.
Referenced by GuiWindow::OnDraw(), GuiWindow::SetHighlight(), GuiWindow::TimeoutCallback(), and Window().
The documentation for this class was generated from the following files:
window.h
window.cpp