FreeRCT: GSLIBlock Class Reference
GSLIBlock Class Reference
GSLI game block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int min_length
Minimal length of the bar.
int step_size
Stepsize of the bar.
int width
Width of the slider button.
int widget_type
Widget type.
std::shared_ptr< SpriteBlock > left
Left sprite.
std::shared_ptr< SpriteBlock > middle
Middle sprite.
std::shared_ptr< SpriteBlock > right
Right sprite.
std::shared_ptr< SpriteBlock > slider
Slider button.
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
GSLI game block.
Definition at line 647 of file nodes.h.
Member Function Documentation
int GSLIBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 1030 of file nodes.cpp.
References FileWriter::AddBlock(), NamedBlock::blk_name, FileBlock::CheckEndSave(), left, middle, min_length, right, FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), FileBlock::SaveUInt8(), slider, FileBlock::StartSave(), step_size, NamedBlock::version, widget_type, and width.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp