FreeRCT: Saver Class Reference
Saver Class Reference
Class for saving a savegame.
#include <loadsave.h>
Public Member Functions
Saver (FILE *fp)
Constructor for the saver.
void StartBlock (const char *name, uint32 version)
Write the start of a block to the output.
void EndBlock ()
Write the end of the block to the output.
void PutByte (uint8 val)
Write a byte to the output stream.
void PutWord (uint16 val)
Write a word to the output stream.
void PutLong (uint32 val)
Write a long word to the output stream.
void PutLongLong (uint64 val)
Write a long long word to the output stream.
Private Attributes
FILE * fp
Output file stream.
const char * blk_name
Name of the current block.
Detailed Description
Class for saving a savegame.
Definition at line 44 of file loadsave.h.
Constructor & Destructor Documentation
Saver::Saver (FILE * fp)
Constructor for the saver.
Parameters
fp Output file stream to write to.
Definition at line 181 of file loadsave.cpp.
References blk_name, and fp.
Member Function Documentation
void Saver::StartBlock (const char * name, uint32 version)
Write the start of a block to the output.
Parameters
name Name of the block to write.
version Version number of the block.
Definition at line 192 of file loadsave.cpp.
References blk_name, PutByte(), PutLong(), and UINT32_MAX.
Referenced by Random::Save(), FinancesManager::Save(), VoxelStack::Save(), VoxelWorld::Save(), SaveDate(), and SaveElements().
void Saver::EndBlock ()
Write the end of the block to the output.
Definition at line 203 of file loadsave.cpp.
References blk_name, and PutByte().
Referenced by Random::Save(), FinancesManager::Save(), VoxelStack::Save(), VoxelWorld::Save(), SaveDate(), and SaveElements().
void Saver::PutByte (uint8 val)
Write a byte to the output stream.
Parameters
val Value to write.
Definition at line 214 of file loadsave.cpp.
References fp.
Referenced by EndBlock(), PutWord(), FinancesManager::Save(), Voxel::Save(), VoxelStack::Save(), and StartBlock().
void Saver::PutWord (uint16 val)
Write a word to the output stream.
Parameters
val Value to write.
Definition at line 223 of file loadsave.cpp.
References PutByte().
Referenced by PutLong(), Voxel::Save(), VoxelStack::Save(), and VoxelWorld::Save().
void Saver::PutLong (uint32 val)
Write a long word to the output stream.
Parameters
val Value to write.
Definition at line 233 of file loadsave.cpp.
References PutWord().
Referenced by PutLongLong(), Random::Save(), Voxel::Save(), SaveDate(), and StartBlock().
void Saver::PutLongLong (uint64 val)
Write a long long word to the output stream.
Parameters
val Value to write.
Definition at line 243 of file loadsave.cpp.
References PutLong().
Referenced by Finances::Save(), and FinancesManager::Save().
The documentation for this class was generated from the following files:
loadsave.h
loadsave.cpp