FreeRCT: PathBuildManager Class Reference
PathBuildManager Class Reference
Helper for storing data and state about the path building process.
#include <path_build.h>
Public Member Functions
PathBuildManager ()
Default constructor.
bool MayActivateMode () override
Query the mode whether it can be enabled.
void ActivateMode (const Point16 &pos) override
Restart the path build interaction sequence.
void LeaveMode () override
Notification that the mouse mode has been disabled.
bool EnableCursors () override
Control display of cursors in the mouse mode.
void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) override
The mouse moved while in this mouse mode.
void OnMouseButtonEvent (Viewport *vp, uint8 state) override
A mouse click was detected.
void SetPathGuiState (bool opened)
Set the state of the path build GUI.
void TileClicked (uint16 xpos, uint16 ypos, uint8 zpos)
User clicked somewhere.
void ComputeNewLongPath (const Point32 &mousexy)
Build a path from _path_builder xpos/ypos to the mouse cursor position.
void ConfirmLongPath ()
Confirm that the current long path is the selection to build.
void SelectArrow (TileEdge direction)
User selected a build direction.
void SelectPathType (PathType pt)
A new path type should be used for building paths.
void SelectSlope (TrackSlope slope)
Select a slope from the allowed slopes.
void SelectMovement (bool move_forward)
User clicked 'forward' or 'back'.
void SelectLong ()
Enter long path building mode.
void SelectBuyRemove (bool buy)
User selected 'buy' or 'remove'.
uint8 GetAllowedArrows () const
Get the allowed directions of building from the selected tile.
TileEdge GetSelectedArrow () const
Get the selected arrow, if available.
uint8 GetAllowedSlopes () const
Get the allowed directions of building from the selected tile.
TrackSlope GetSelectedSlope () const
Get the selected slope, if available.
bool GetBuyIsEnabled () const
Can the user press the 'buy' button at the path GUI?
bool GetRemoveIsEnabled () const
Can the user press the 'remove' button at the path GUI?
bool GetForwardIsEnabled () const
Can the user press the 'forward' button at the path GUI?
bool GetBackwardIsEnabled () const
Can the user press the 'back' button at the path GUI?
bool GetLongButtonIsEnabled () const
Is the 'long' mode button enabled?
bool GetLongButtonIsPressed () const
Is the 'long' mode button pressed?
virtual void OnMouseWheelEvent (Viewport *vp, int direction)
A mouse wheelie event has been detected.
Public Attributes
PathBuildState state
State of the path building process.
PathType path_type
Selected type of path to use for building.
const WindowTypes wtype
Type of window associated with this mouse mode.
const ViewportMouseMode mode
Mouse mode implemented by the object.
Private Member Functions
void ComputeArrowCursorPosition (uint16 *xpos, uint16 *ypos, uint8 *zpos)
Compute the voxel to display the arrow cursor.
void ComputeWorldAdditions ()
Compute the new contents of the voxel where the path should be added from the _world.
void MoveCursor (TileEdge edge, bool move_up)
Try to move the tile cursor to a new tile.
void UpdateState ()
Update the state of the path build process.
Private Attributes
uint8 mouse_state
State of the mouse buttons.
uint16 xpos
X coordinate of the selected voxel.
uint16 xlong
X coordinate of the long path destination voxel.
uint16 ypos
Y coordinate of the selected voxel.
uint16 ylong
Y coordinate of the long path destination voxel.
uint8 zpos
Z coordinate of the selected voxel.
uint8 zlong
Z coordinate of the long path destination voxel.
uint8 allowed_arrows
Allowed build directions from the voxel (bitset of TileEdge, lower 4 bits are at bottom, upper 4 bits at top).
TileEdge selected_arrow
Last selected build direction (INVALID_EDGE if none has been chosen).
uint8 allowed_slopes
Allowed slope directions for the build direction.
TrackSlope selected_slope
Last selected slope (TSL_INVALID if none has been chosen).
Detailed Description
Helper for storing data and state about the path building process.
Definition at line 33 of file path_build.h.
Constructor & Destructor Documentation
PathBuildManager::PathBuildManager ()
Default constructor.
Definition at line 357 of file path_build.cpp.
References DisableWorldAdditions(), INVALID_EDGE, PAT_INVALID, path_type, PBS_IDLE, selected_arrow, selected_slope, state, and TSL_INVALID.
Member Function Documentation
bool PathBuildManager::MayActivateMode () override virtual
Query the mode whether it can be enabled.
Method may be called at any moment (or more often than once). Answering true does not mean the mouse mode will be activated.
Returns
Whether the mode may be enabled.
Implements MouseMode.
Definition at line 366 of file path_build.cpp.
void PathBuildManager::ActivateMode (const Point16 & pos) override virtual
Restart the path build interaction sequence.
Parameters
pos New mouse position.
Returns
The mouse mode should be enabled.
Implements MouseMode.
Definition at line 376 of file path_build.cpp.
References INVALID_EDGE, mouse_state, PBS_IDLE, PBS_WAIT_VOXEL, selected_arrow, selected_slope, state, TSL_INVALID, and UpdateState().
void PathBuildManager::LeaveMode () override virtual
Notification that the mouse mode has been disabled.
Implements MouseMode.
Definition at line 387 of file path_build.cpp.
References DisableWorldAdditions().
bool PathBuildManager::EnableCursors () override virtual
Control display of cursors in the mouse mode.
Returns
true when cursors should be displayed, false otherwise.
Implements MouseMode.
Definition at line 392 of file path_build.cpp.
void PathBuildManager::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) override virtual
The mouse moved while in this mouse mode.
Parameters
vp Viewport object.
old_pos Previous position.
pos Current position.
Reimplemented from MouseMode.
Definition at line 397 of file path_build.cpp.
References Viewport::ComputeCursorPosition(), Viewport::ComputeHorizontalTranslation(), ComputeNewLongPath(), CS_GROUND, CS_NONE, CS_PATH, FinderData::cursor, FW_TILE, Rectangle< PT, SZ >::height, MB_RIGHT, mouse_state, Viewport::MoveViewport(), PBS_LONG_BUILD, PBS_WAIT_VOXEL, Window::rect, Cursor::SetCursor(), state, Viewport::tile_cursor, Rectangle< PT, SZ >::width, Point< CT >::x, FinderData::xvoxel, Point< CT >::y, FinderData::yvoxel, and FinderData::zvoxel.
void PathBuildManager::OnMouseButtonEvent (Viewport * vp, uint8 state) override virtual
A mouse click was detected.
Parameters
vp Viewport object.
state State of the mouse buttons.
See also
MouseButtons
Reimplemented from MouseMode.
Definition at line 415 of file path_build.cpp.
References Viewport::ComputeCursorPosition(), ConfirmLongPath(), CS_GROUND, CS_NONE, CS_PATH, FW_TILE, MB_CURRENT, MB_LEFT, mouse_state, PBS_LONG_BUILD, PBS_LONG_BUY, TileClicked(), FinderData::xvoxel, FinderData::yvoxel, and FinderData::zvoxel.
void PathBuildManager::SetPathGuiState (bool opened)
Set the state of the path build GUI.
Parameters
opened If true the path GUI just opened, else it closed.
Definition at line 435 of file path_build.cpp.
References _mouse_modes, MouseModes::GetMouseMode(), GetViewport(), MM_PATH_BUILDING, PBS_IDLE, PBS_WAIT_VOXEL, MouseModes::SetViewportMousemode(), state, and UpdateState().
void PathBuildManager::TileClicked (uint16 xpos, uint16 ypos, uint8 zpos)
User clicked somewhere.
Check whether it is a good tile or path, and if so, move the building process forward.
Parameters
xpos X coordinate of the voxel.
ypos Y coordinate of the voxel.
zpos Z coordinate of the voxel.
Definition at line 449 of file path_build.cpp.
References allowed_arrows, GetPathAttachPoints(), PBS_IDLE, PBS_WAIT_ARROW, PBS_WAIT_BUY, state, UpdateState(), xpos, ypos, and zpos.
Referenced by OnMouseButtonEvent().
void PathBuildManager::ComputeNewLongPath (const Point32 & mousexy)
Build a path from _path_builder xpos/ypos to the mouse cursor position.
Parameters
mousexy Mouse position.
Definition at line 791 of file path_build.cpp.
References _additions, _tile_dxy, _world, BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), CanBuildPathFromEdge(), WorldAdditions::Clear(), EDGE_BEGIN, EDGE_COUNT, Viewport::EnableWorldAdditions(), Viewport::EnsureAdditionsAreVisible(), GetViewport(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), GoodDirection(), NOT_REACHED, Viewport::orientation, path_type, TSL_DOWN, TSL_FLAT, TSL_INVALID, TSL_UP, VOR_EAST, VOR_NORTH, VOR_SOUTH, VOR_WEST, WORLD_Z_SIZE, Point< CT >::x, xlong, xpos, Point< CT >::y, ylong, ypos, zlong, zpos, and Viewport::zview.
Referenced by OnMouseMoveEvent().
void PathBuildManager::ConfirmLongPath ()
Confirm that the current long path is the selection to build.
Definition at line 881 of file path_build.cpp.
References PBS_LONG_BUILD, PBS_LONG_BUY, state, and UpdateState().
Referenced by OnMouseButtonEvent().
void PathBuildManager::SelectArrow (TileEdge direction)
User selected a build direction.
Check it, and if so, move the building process forward.
Parameters
direction Direction of build.
Definition at line 467 of file path_build.cpp.
References allowed_arrows, INVALID_EDGE, PBS_WAIT_BUY, PBS_WAIT_SLOPE, selected_arrow, state, and UpdateState().
Referenced by PathBuildGui::OnClick().
void PathBuildManager::SelectPathType (PathType pt)
A new path type should be used for building paths.
Parameters
pt New path type to use.
Definition at line 480 of file path_build.cpp.
References path_type, PBS_WAIT_BUY, state, and UpdateState().
Referenced by PathBuildGui::OnClick().
void PathBuildManager::SelectSlope (TrackSlope slope)
Select a slope from the allowed slopes.
Parameters
slope Slope to select.
Definition at line 744 of file path_build.cpp.
References allowed_slopes, PBS_WAIT_SLOPE, selected_slope, state, TSL_COUNT_GENTLE, and UpdateState().
Referenced by PathBuildGui::OnClick().
void PathBuildManager::SelectMovement (bool move_forward)
User clicked 'forward' or 'back'.
Figure out which direction to move in.
Parameters
move_forward Move forward (if false, move back).
Definition at line 556 of file path_build.cpp.
References _corners_at_edge, _path_down_from_edge, _world, ExpandTileSlope(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), GetImplodedPathSlope(), VoxelWorld::GetVoxel(), GTP_INVALID, HasValidPath(), MoveCursor(), PBS_WAIT_BUY, selected_arrow, state, TSB_STEEP, xpos, ypos, and zpos.
Referenced by PathBuildGui::OnClick(), and SelectBuyRemove().
void PathBuildManager::SelectLong ()
Enter long path building mode.
Definition at line 755 of file path_build.cpp.
References _world, VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), PBS_LONG_BUILD, PBS_LONG_BUY, PBS_WAIT_ARROW, state, UpdateState(), WORLD_Z_SIZE, xlong, ylong, and zlong.
Referenced by PathBuildGui::OnClick().
void PathBuildManager::SelectBuyRemove (bool buying)
User selected 'buy' or 'remove'.
Perform the action, and update the path build state.
Parameters
buying If true, user selected 'buy'.
Definition at line 892 of file path_build.cpp.
References _additions, _path_down_from_edge, _world, WorldAdditions::Clear(), WorldAdditions::Commit(), GetImplodedPathSlope(), VoxelWorld::GetVoxel(), HasValidPath(), MoveCursor(), PBS_LONG_BUY, PBS_WAIT_ARROW, PBS_WAIT_BUY, RemovePath(), selected_arrow, SelectMovement(), state, UpdateState(), xlong, xpos, ylong, ypos, zlong, and zpos.
Referenced by PathBuildGui::OnClick().
uint8 PathBuildManager::GetAllowedArrows () const inline
Get the allowed directions of building from the selected tile.
Returns
Allowed directions as a bitset of tile edges.
Definition at line 95 of file path_build.h.
References allowed_arrows, PBS_WAIT_BUY, and state.
Referenced by PathBuildGui::SetButtons().
TileEdge PathBuildManager::GetSelectedArrow () const inline
Get the selected arrow, if available.
Returns
The last selected arrow, or INVALID_EDGE if none is available.
Definition at line 105 of file path_build.h.
References INVALID_EDGE, PBS_WAIT_BUY, selected_arrow, and state.
Referenced by PathBuildGui::SetButtons().
uint8 PathBuildManager::GetAllowedSlopes () const inline
Get the allowed directions of building from the selected tile.
Returns
Allowed directions as a bitset of tile edges.
Definition at line 115 of file path_build.h.
References allowed_slopes, PBS_WAIT_BUY, and state.
Referenced by PathBuildGui::SetButtons().
TrackSlope PathBuildManager::GetSelectedSlope () const inline
Get the selected slope, if available.
Returns
The last selected slope, or TSL_INVALID if no valid slope is available.
Definition at line 125 of file path_build.h.
References PBS_WAIT_BUY, selected_slope, state, and TSL_INVALID.
Referenced by PathBuildGui::SetButtons().
bool PathBuildManager::GetBuyIsEnabled () const inline
Can the user press the 'buy' button at the path GUI?
Returns
Button is enabled.
Definition at line 135 of file path_build.h.
References PBS_LONG_BUY, PBS_WAIT_BUY, and state.
Referenced by PathBuildGui::SetButtons().
bool PathBuildManager::GetRemoveIsEnabled () const
Can the user press the 'remove' button at the path GUI?
Returns
Button is enabled.
Definition at line 731 of file path_build.cpp.
References _world, VoxelWorld::GetVoxel(), HasValidPath(), PBS_IDLE, PBS_WAIT_BUY, PBS_WAIT_VOXEL, state, xpos, ypos, and zpos.
Referenced by PathBuildGui::SetButtons().
bool PathBuildManager::GetForwardIsEnabled () const inline
Can the user press the 'forward' button at the path GUI?
Returns
Button is enabled.
Definition at line 144 of file path_build.h.
References PBS_WAIT_ARROW, PBS_WAIT_BUY, and state.
Referenced by PathBuildGui::SetButtons().
bool PathBuildManager::GetBackwardIsEnabled () const inline
Can the user press the 'back' button at the path GUI?
Returns
Button is enabled.
Definition at line 153 of file path_build.h.
References PBS_WAIT_ARROW, PBS_WAIT_BUY, and state.
Referenced by PathBuildGui::SetButtons().
bool PathBuildManager::GetLongButtonIsEnabled () const inline
Is the 'long' mode button enabled?
Returns
Button is enabled.
Definition at line 162 of file path_build.h.
References PBS_WAIT_VOXEL, and state.
Referenced by PathBuildGui::SetButtons().
bool PathBuildManager::GetLongButtonIsPressed () const inline
Is the 'long' mode button pressed?
Returns
Button is pressed.
Definition at line 171 of file path_build.h.
References PBS_LONG_BUILD, PBS_LONG_BUY, and state.
Referenced by PathBuildGui::SetButtons().
void PathBuildManager::ComputeArrowCursorPosition (uint16 * xpos, uint16 * ypos, uint8 * zpos) private
Compute the voxel to display the arrow cursor.
Parameters
xpos [out] Computed X position of the voxel that should contain the arrow cursor.
ypos [out] Computed Y position of the voxel that should contain the arrow cursor.
zpos [out] Computed Z position of the voxel that should contain the arrow cursor.
Definition at line 584 of file path_build.cpp.
References _tile_dxy, _world, allowed_arrows, VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), INVALID_EDGE, PBS_WAIT_ARROW, PBS_WAIT_BUY, selected_arrow, state, WORLD_Z_SIZE, Point< CT >::x, Point< CT >::y, and zpos.
Referenced by ComputeWorldAdditions(), and UpdateState().
void PathBuildManager::ComputeWorldAdditions () private
Compute the new contents of the voxel where the path should be added from the _world.
Definition at line 607 of file path_build.cpp.
References allowed_slopes, BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), ComputeArrowCursorPosition(), NOT_REACHED, path_type, PBS_WAIT_BUY, selected_arrow, selected_slope, state, TSL_DOWN, TSL_FLAT, TSL_INVALID, TSL_UP, xpos, ypos, and zpos.
Referenced by UpdateState().
void PathBuildManager::MoveCursor (TileEdge edge, bool move_up) private
Try to move the tile cursor to a new tile.
Parameters
edge Direction of movement.
move_up Current tile seems to move up.
Definition at line 494 of file path_build.cpp.
References _game_mode_mgr, _tile_dxy, _world, Voxel::GetGroundSlope(), Voxel::GetGroundType(), VoxelWorld::GetTileOwner(), VoxelWorld::GetVoxel(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), GTP_INVALID, HasValidPath(), GameModeManager::InPlayMode(), INVALID_EDGE, IsImplodedSteepSlope(), OWN_PARK, PBS_WAIT_ARROW, PBS_WAIT_BUY, state, UpdateState(), WORLD_Z_SIZE, Point< CT >::x, xpos, Point< CT >::y, ypos, and zpos.
Referenced by SelectBuyRemove(), and SelectMovement().
void PathBuildManager::UpdateState () private
Update the state of the path build process.
Definition at line 637 of file path_build.cpp.
References _additions, ALL_WINDOWS_OF_TYPE, allowed_arrows, allowed_slopes, Viewport::arrow_cursor, CanBuildPathFromEdge(), CHG_UPDATE_BUTTONS, WorldAdditions::Clear(), ComputeArrowCursorPosition(), ComputeWorldAdditions(), CUR_TYPE_ARROW_NE, CUR_TYPE_TILE, Viewport::DisableWorldAdditions(), EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, Viewport::EnableWorldAdditions(), Viewport::EnsureAdditionsAreVisible(), GetPathAttachPoints(), GetViewport(), INVALID_EDGE, NotifyChange(), PBS_IDLE, PBS_LONG_BUILD, PBS_LONG_BUY, PBS_WAIT_ARROW, PBS_WAIT_BUY, PBS_WAIT_SLOPE, PBS_WAIT_VOXEL, selected_arrow, selected_slope, Cursor::SetCursor(), BaseCursor::SetInvalid(), state, Viewport::tile_cursor, TSL_DOWN, TSL_FLAT, TSL_INVALID, TSL_UP, WC_PATH_BUILDER, xpos, ypos, and zpos.
Referenced by ActivateMode(), ConfirmLongPath(), MoveCursor(), SelectArrow(), SelectBuyRemove(), SelectLong(), SelectPathType(), SelectSlope(), SetPathGuiState(), and TileClicked().
void MouseMode::OnMouseWheelEvent (Viewport * vp, int direction) virtual inherited
A mouse wheelie event has been detected.
Parameters
vp Viewport object.
direction Direction of movement.
Reimplemented in TileTerraformMouseMode, and FenceBuildManager.
Definition at line 1655 of file viewport.cpp.
Referenced by Viewport::OnMouseWheelEvent().
The documentation for this class was generated from the following files:
path_build.h
path_build.cpp