FreeRCT: CoasterBuildStateOn Class Reference
CoasterBuildStateOn Class Reference
State for display a not-available track piece, or suppressing display of an available track piece.
Public Member Functions
CoasterBuildStateOn (CoasterBuildMode &mode)
Constructor of the CoasterBuildStateOn state.
void OpenWindow (uint16 instance) const override
Notification to the mouse mode that a coaster construction window has been opened.
void CloseWindow (uint16 instance) const override
Notification to the mouse mode that a coaster construction window has been closed.
bool MayActivateMode () const override
Query from the viewport whether the mouse mode may be activated.
void ActivateMode (const Point16 &pos) const override
Notification from the viewport that the mouse mode has been activated.
void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) const override
Notification from the viewport that the mouse has moved.
void OnMouseButtonEvent (Viewport *vp, uint8 state) const override
Notification from the viewport that a mouse button has changed value.
void LeaveMode () const override
Notification from the viewport that the mouse mode has been de-activated.
bool EnableCursors () const override
Query from the viewport whether the mouse mode wants to have cursors displayed.
void ShowNoPiece (uint16 instance) const override
Notification from the construction window to display no track piece.
void SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction) const override
Notification from the construction window to display a track piece attached to the mouse cursor.
void DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, int x, int y, int z, TileEdge direction) const override
Notification from the construction window to display a track piece at a given position.
Public Attributes
CoasterBuildMode *const mode
Coaster build mouse mode.
Detailed Description
State for display a not-available track piece, or suppressing display of an available track piece.
Definition at line 871 of file coaster_gui.cpp.
Constructor & Destructor Documentation
CoasterBuildStateOn::CoasterBuildStateOn (CoasterBuildMode & mode) inline
Constructor of the CoasterBuildStateOn state.
Parameters
mode Builder mode.
Definition at line 877 of file coaster_gui.cpp.
Member Function Documentation
void CoasterBuildStateOn::OpenWindow (uint16 instance) const inline override virtual
Notification to the mouse mode that a coaster construction window has been opened.
Parameters
instance Ride number of the window.
Implements CoasterBuildState.
Definition at line 881 of file coaster_gui.cpp.
void CoasterBuildStateOn::CloseWindow (uint16 instance) const inline override virtual
Notification to the mouse mode that a coaster construction window has been closed.
Parameters
instance Ride number of the window.
Implements CoasterBuildState.
Definition at line 885 of file coaster_gui.cpp.
References _mouse_modes, BS_STARTING, CoasterBuildMode::DisableDisplay(), CoasterBuildMode::instance, CoasterBuildState::mode, CoasterBuildMode::SetState(), MouseModes::SetViewportMousemode(), and CoasterBuildMode::UpdateDisplay().
bool CoasterBuildStateOn::MayActivateMode () const inline override virtual
Query from the viewport whether the mouse mode may be activated.
Returns
The mouse mode may be activated.
See also
MouseMode::MayActivateMode
Implements CoasterBuildState.
Definition at line 894 of file coaster_gui.cpp.
void CoasterBuildStateOn::ActivateMode (const Point16 & pos) const inline override virtual
Notification from the viewport that the mouse mode has been activated.
Parameters
pos Current mouse position.
See also
MouseMode::ActivateMode
Implements CoasterBuildState.
Definition at line 899 of file coaster_gui.cpp.
References CoasterBuildState::mode, and CoasterBuildMode::SetMousePosition().
void CoasterBuildStateOn::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) const inline override virtual
Notification from the viewport that the mouse has moved.
Parameters
vp The viewport.
old_pos Previous position of the mouse.
pos Current mouse position.
See also
MouseMode::OnMouseMoveEvent
Implements CoasterBuildState.
Definition at line 904 of file coaster_gui.cpp.
References CoasterBuildState::mode, and CoasterBuildMode::SetMousePosition().
void CoasterBuildStateOn::OnMouseButtonEvent (Viewport * vp, uint8 state) const inline override virtual
Notification from the viewport that a mouse button has changed value.
Parameters
vp The viewport.
state Old and new state of the mouse buttons.
See also
MouseMode::OnMouseButtonEvent
Implements CoasterBuildState.
Definition at line 909 of file coaster_gui.cpp.
void CoasterBuildStateOn::LeaveMode () const inline override virtual
Notification from the viewport that the mouse mode has been de-activated.
See also
MouseMode::LeaveMode
Implements CoasterBuildState.
Definition at line 914 of file coaster_gui.cpp.
References BS_STARTING, CoasterBuildMode::DisableDisplay(), CoasterBuildState::mode, CoasterBuildMode::SetState(), and CoasterBuildMode::UpdateDisplay().
bool CoasterBuildStateOn::EnableCursors () const inline override virtual
Query from the viewport whether the mouse mode wants to have cursors displayed.
Returns
Cursors should be enabled.
See also
MouseMode::EnableCursors
Implements CoasterBuildState.
Definition at line 921 of file coaster_gui.cpp.
void CoasterBuildStateOn::ShowNoPiece (uint16 instance) const inline override virtual
Notification from the construction window to display no track piece.
Parameters
instance Ride number of the window.
Implements CoasterBuildState.
Definition at line 926 of file coaster_gui.cpp.
References CoasterBuildMode::instance, CoasterBuildState::mode, and CoasterBuildMode::SetNoPiece().
void CoasterBuildStateOn::SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction) const inline override virtual
Notification from the construction window to display a track piece attached to the mouse cursor.
Parameters
instance Ride number of the window.
piece Track piece to display.
direction Direction of building (to use with a cursor).
Implements CoasterBuildState.
Definition at line 932 of file coaster_gui.cpp.
References BS_MOUSE, CoasterBuildMode::instance, CoasterBuildState::mode, CoasterBuildMode::SetSelectPosition(), CoasterBuildMode::SetState(), and CoasterBuildMode::UpdateDisplay().
void CoasterBuildStateOn::DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, int x, int y, int z, TileEdge direction) const inline override virtual
Notification from the construction window to display a track piece at a given position.
Parameters
instance Ride number of the window.
piece Track piece to display.
x X position of the piece.
y Y position of the piece.
z Z position of the piece.
direction Direction of building (to use with a cursor).
Implements CoasterBuildState.
Definition at line 940 of file coaster_gui.cpp.
References BS_FIXED, CoasterBuildMode::instance, CoasterBuildState::mode, CoasterBuildMode::SetFixedPiece(), CoasterBuildMode::SetState(), and CoasterBuildMode::UpdateDisplay().
The documentation for this class was generated from the following file:
coaster_gui.cpp