FreeRCT: Random Class Reference
Random Class Reference
A random generator class.
#include <random.h>
Public Member Functions
bool Success1024 (uint upper)
See whether we are lucky.
bool Success (int perc)
Try being successful for perc percent.
uint16 Uniform (uint16 incl_upper)
Draw a number from an uniform distribution.
uint16 Exponential (uint16 mean)
Draw a number from an exponential distribution.
Static Public Member Functions
static void Load (Loader &ldr)
Load random number for the game.
static void Save (Saver &svr)
Save random number of the game.
Private Member Functions
uint32 DrawNumber ()
Draw a random 32 bit number ('ranqd1' generator in Numerical Recipes).
Static Private Attributes
static uint32 seed = 0
Seed of the generators.
Detailed Description
A random generator class.
Definition at line 16 of file random.h.
Member Function Documentation
bool Random::Success1024 (uint upper)
See whether we are lucky.
Parameters
upper Upper bound on the value (exclusive), between 0 and 1024.
Returns
Drawn value is less then the upper limit.
Definition at line 24 of file random.cpp.
References DrawNumber().
Referenced by Guest::DailyUpdate(), Guest::NeedForItem(), Guests::OnNewDay(), and Success().
bool Random::Success (int perc)
Try being successful for perc percent.
Parameters
perc Percentage of success.
Returns
Whether we were lucky.
Definition at line 35 of file random.cpp.
References Success1024().
uint16 Random::Uniform (uint16 incl_upper)
Draw a number from an uniform distribution.
Lower bound is 0, upper bound is incl_upper (inclusive).
Parameters
incl_upper Inclusive upper bound.
Returns
Value drawn from the distribution within the set limits.
Definition at line 58 of file random.cpp.
References DrawNumber().
Referenced by Guest::Activate(), Recolouring::AssignRandomColours(), Guest::DecideMoveDirection(), AverageWeather::Draw(), and Guest::VisitShop().
uint16 Random::Exponential (uint16 mean)
Draw a number from an exponential distribution.
Parameters
mean The mean interval between events
Returns
An interval length drawn from the exponential distribution
Definition at line 46 of file random.cpp.
References DrawNumber().
Referenced by RideInstance::HandleBreakdown(), and RideInstance::OpenRide().
void Random::Load (Loader & ldr) static
Load random number for the game.
Parameters
ldr Source of the data.
Definition at line 91 of file random.cpp.
References Loader::CloseBlock(), Loader::GetLong(), Loader::OpenBlock(), and seed.
Referenced by LoadElements().
void Random::Save (Saver & svr) static
Save random number of the game.
Parameters
svr Destination of the data.
Definition at line 103 of file random.cpp.
References Saver::EndBlock(), Saver::PutLong(), seed, and Saver::StartBlock().
Referenced by SaveElements().
uint32 Random::DrawNumber () private
Draw a random 32 bit number ('ranqd1' generator in Numerical Recipes).
Returns
New random number on every call.
Note
Higher bits are more random than the low ones.
Definition at line 77 of file random.cpp.
References seed.
Referenced by Exponential(), Success1024(), and Uniform().
The documentation for this class was generated from the following files:
random.h
random.cpp