FreeRCT: Weather Class Reference
Weather Class Reference
The weather in the game.
#include <weather.h>
Public Member Functions
void Initialize ()
Initialize the weather for a new game.
void OnNewDay ()
Daily update of the weather.
WeatherType GetWeatherType () const
Get the current type of weather.
Public Attributes
int temperature
Current temperature, in 1/10 degrees Celcius.
int current
Current weather.
int next
Next weather type.
int change
speed of change in the weather.
Private Member Functions
void SetTemperature ()
Compute todays temperature in the park.
Detailed Description
The weather in the game.
Definition at line 27 of file weather.h.
Member Function Documentation
void Weather::Initialize ()
Initialize the weather for a new game.
Definition at line 124 of file weather.cpp.
References _date, change, current, AverageWeather::Draw(), Date::month, next, and OnNewDay().
Referenced by StartNewGame().
void Weather::OnNewDay ()
Daily update of the weather.
Definition at line 134 of file weather.cpp.
References _date, change, current, Date::day, AverageWeather::Draw(), Date::GetNextMonth(), Date::month, next, and SetTemperature().
Referenced by Initialize(), and OnNewDay().
WeatherType Weather::GetWeatherType () const
Get the current type of weather.
Returns
The type of weather of today.
Definition at line 158 of file weather.cpp.
References _date, current, AverageWeather::GetWeatherType(), and Date::month.
Referenced by Guest::DailyUpdate(), BottomToolbarWindow::DrawWidget(), and Viewport::OnDraw().
void Weather::SetTemperature () private
Compute todays temperature in the park.
Definition at line 164 of file weather.cpp.
References _date, _days_per_month, Date::day, Date::GetNextMonth(), Date::GetPreviousMonth(), Date::month, AverageWeather::temp, and temperature.
Referenced by OnNewDay().
The documentation for this class was generated from the following files:
weather.h
weather.cpp