FreeRCT: ScrollbarWidget Class Reference
ScrollbarWidget Class Reference
Widgets and supporting functions of the program
Scrollbar widget.
#include <widget.h>
Public Member Functions
ScrollbarWidget (WidgetType wtype)
Scrollbar widget constructor.
void SetScrolled (const BaseWidget *canvas)
Set the widget being controlled by the scrollbar.
void SetupMinimalSize (GuiWindow *w, BaseWidget **wid_array) override
Compute smallest size of the widget.
void Draw (const GuiWindow *w) override
Draw the widget.
void OnClick (const Point32 &base, const Point16 &pos)
Scrollbar got clicked, update its counters, and mark the associated scrolled widget as dirty.
void SetItemSize (uint size)
Set the height/width of an item in the scrolled widget.
void SetItemCount (uint count)
Set the number of items displayed in the scrolled widget.
void SetStart (uint offset)
Set the number of the first visible item in the scrolled widget.
uint GetItemSize () const
Get the height or width of an item.
uint GetVisibleCount () const
Get the number of items visible in the scrolled widget.
uint GetStart () const
Get the index of the first visible item in the scrolled widget.
void ScrollTo (uint offset)
Scroll the scrolled widget such that it shows item number offset.
uint GetClickedRow (const Point16 &pos) const
Which row was clicked in the scrolled widget?
virtual void AutoRaiseButtons (const Point32 &base) override
Raise all push buttons in the tree.
bool IsChecked () const
Is the 'checked' flag on?
bool IsPressed () const
Is the 'pressed' flag on?
bool IsShaded () const
Is the 'shaded' flag on?
void SetChecked (bool value)
Set the 'checked' flag to the new value.
void SetPressed (bool value)
Set the 'pressed' flag to the new value.
void SetShaded (bool value)
Set the 'shaded' flag to the new value.
virtual void SetSmallestSizePosition (const Rectangle16 &rect)
Set the minimal size of the widget, and assign rect to the current position and size.
virtual BaseWidget * GetWidgetByPosition (const Point16 &pt)
Get the widget at the given relative window position.
void MarkDirty (const Point32 &base) const
Denote the widget as being needed to redraw.
Public Attributes
uint8 flags
Flags of the leaf widget.
ColourRange colour
Colour of the widget.
StringID tooltip
Tool-tip of the widget.
WidgetType wtype
Widget type.
WidgetNumber number
Widget number.
uint16 smallest_x
Original horizontal size.
uint16 smallest_y
Original vertical size.
uint16 min_x
Minimal horizontal size.
uint16 min_y
Minimal vertical size.
Rectangle16 pos
Current position and size (relative to window top-left edge).
uint16 fill_x
Horizontal fill step.
uint16 fill_y
Vertical fill step.
uint16 resize_x
Horizontal resize step.
uint16 resize_y
Vertical resize step.
uint8 paddings [PAD_COUNT]
Padding.
Protected Member Functions
void SetWidget (BaseWidget **wid_array)
Add the widget to the widget array wid_array.
void InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert)
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
void InitMinimalSize (const BorderSpriteData *bsd, uint16 content_width, uint16 content_height)
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Private Member Functions
int GetDecrementButtonSize () const
Get the size of the left / top / decrement button in the direction of the scrollbar.
int GetIncrementButtonSize () const
Get the size of the right / bottom / increment button in the direction of the scrollbar.
void CalculateSliderPosition (int *start_edge, int *slider_length)
Calculate the position and sizes of the displayed scrollbar components.
ScrollbarComponent GetClickedComponent (const Point16 &pos)
Decide which part of the scrollbar was clicked.
Private Attributes
uint item_count
Number of items represented by the scroll bar.
uint start
Index of first visible item.
uint item_size
Size of an item if not 0, else use canvas.
const BaseWidget * canvas
Widget being scrolled.
Detailed Description
Scrollbar widget.
Implements WT_HOR_SCROLLBAR and WT_VERT_SCROLLBAR.
Definition at line 228 of file widget.h.
Constructor & Destructor Documentation
ScrollbarWidget::ScrollbarWidget (WidgetType wtype)
Scrollbar widget constructor.
Parameters
wtype Widget type.
Definition at line 536 of file widget.cpp.
References canvas, item_count, item_size, and start.
Member Function Documentation
void ScrollbarWidget::SetScrolled (const BaseWidget * canvas)
Set the widget being controlled by the scrollbar.
Parameters
canvas Widget being controlled by the scrollbar.
Definition at line 548 of file widget.cpp.
References canvas.
Referenced by GuiWindow::SetScrolledWidget().
void ScrollbarWidget::SetupMinimalSize (GuiWindow * w, BaseWidget ** wid_array) override virtual
Compute smallest size of the widget.
Parameters
w Window owning the widget.
wid_array [out] Array of widget pointers.
Reimplemented from LeafWidget.
Definition at line 558 of file widget.cpp.
References _gui_sprites, BaseWidget::fill_x, BaseWidget::fill_y, ScrollbarSpriteData::height, GuiSprites::hor_scroll, GuiWindow::initialized, ScrollbarSpriteData::min_length_all, BaseWidget::min_x, BaseWidget::min_y, BaseWidget::resize_x, BaseWidget::resize_y, BaseWidget::SetWidget(), ScrollbarSpriteData::stepsize_bar, GuiSprites::vert_scroll, WT_HOR_SCROLLBAR, and BaseWidget::wtype.
void ScrollbarWidget::Draw (const GuiWindow * w) override virtual
Draw the widget.
Parameters
w Window being drawn.
Reimplemented from LeafWidget.
Definition at line 579 of file widget.cpp.
References _gui_sprites, _video, VideoSystem::BlitHorizontal(), VideoSystem::BlitImage(), VideoSystem::BlitVertical(), CalculateSliderPosition(), LeafWidget::colour, GuiWindow::GetWidgetScreenX(), GuiWindow::GetWidgetScreenY(), GS_NORMAL, ImageData::height, Rectangle< PT, SZ >::height, GuiSprites::hor_scroll, ScrollbarSpriteData::IsLoaded(), LeafWidget::IsShaded(), ScrollbarSpriteData::normal, BaseWidget::pos, Recolouring::Set(), ScrollbarSpriteData::shaded, ScrollbarSpriteData::stepsize_bar, ScrollbarSpriteData::stepsize_slider, GuiSprites::vert_scroll, ImageData::width, Rectangle< PT, SZ >::width, WLS_LEFT_BED, WLS_LEFT_BUTTON, WLS_LEFT_SLIDER, WLS_MIDDLE_BED, WLS_MIDDLE_SLIDER, WLS_RIGHT_BED, WLS_RIGHT_BUTTON, WLS_RIGHT_SLIDER, WT_HOR_SCROLLBAR, and BaseWidget::wtype.
void ScrollbarWidget::OnClick (const Point32 & base, const Point16 & pos)
Scrollbar got clicked, update its counters, and mark the associated scrolled widget as dirty.
Parameters
base Base-coordinate of the window.
pos Position of the click in the scrollbar.
Todo:
Implement clicking above at the slider.
Definition at line 691 of file widget.cpp.
References canvas, GetClickedComponent(), GetVisibleCount(), BaseWidget::MarkDirty(), SBC_AFTER_SLIDER, SBC_BEFORE_SLIDER, SBC_DECREMENT_BUTTON, SBC_INCREMENT_BUTTON, SetStart(), and start.
Referenced by GuiWindow::OnMouseButtonEvent().
void ScrollbarWidget::SetItemSize (uint size)
Set the height/width of an item in the scrolled widget.
Parameters
size Height or width of an item.
Definition at line 730 of file widget.cpp.
References item_size.
void ScrollbarWidget::SetItemCount (uint count)
Set the number of items displayed in the scrolled widget.
Parameters
count Number of items.
Definition at line 739 of file widget.cpp.
References item_count, SetStart(), and start.
Referenced by RideSelectGui::SetNewRideKind().
void ScrollbarWidget::SetStart (uint offset)
Set the number of the first visible item in the scrolled widget.
Parameters
offset Suggested index.
Definition at line 802 of file widget.cpp.
References GetVisibleCount(), item_count, and start.
Referenced by OnClick(), ScrollTo(), and SetItemCount().
uint ScrollbarWidget::GetItemSize () const
Get the height or width of an item.
Returns
Size of an item in the list.
Definition at line 764 of file widget.cpp.
References canvas, item_size, BaseWidget::resize_x, BaseWidget::resize_y, WT_HOR_SCROLLBAR, and BaseWidget::wtype.
Referenced by GetClickedRow(), and GetVisibleCount().
uint ScrollbarWidget::GetVisibleCount () const
Get the number of items visible in the scrolled widget.
Returns
Number of visible items.
Definition at line 784 of file widget.cpp.
References canvas, GetItemSize(), Rectangle< PT, SZ >::height, BaseWidget::pos, Rectangle< PT, SZ >::width, WT_HOR_SCROLLBAR, and BaseWidget::wtype.
Referenced by CalculateSliderPosition(), RideSelectGui::DrawWidget(), OnClick(), ScrollTo(), and SetStart().
uint ScrollbarWidget::GetStart () const
Get the index of the first visible item in the scrolled widget.
Returns
Index of the first visible item in the list.
Definition at line 813 of file widget.cpp.
References start.
Referenced by RideSelectGui::DrawWidget(), and GetClickedRow().
void ScrollbarWidget::ScrollTo (uint offset)
Scroll the scrolled widget such that it shows item number offset.
Parameters
offset Item number that should be visible in the scrolled widget.
Definition at line 822 of file widget.cpp.
References GetVisibleCount(), item_count, SetStart(), and start.
uint ScrollbarWidget::GetClickedRow (const Point16 & pos) const
Which row was clicked in the scrolled widget?
Parameters
pos Clicked position in the scrolled widget (relative to top-left of the widget).
Returns
The index of the clicked item in the scrolled widget.
Definition at line 750 of file widget.cpp.
References GetItemSize(), GetStart(), WT_HOR_SCROLLBAR, BaseWidget::wtype, Point< CT >::x, and Point< CT >::y.
Referenced by RideSelectGui::OnClick().
int ScrollbarWidget::GetDecrementButtonSize () const private
Get the size of the left / top / decrement button in the direction of the scrollbar.
Returns
Size of the decrement button in the direction of the scrollbar.
Definition at line 838 of file widget.cpp.
References _gui_sprites, GuiSprites::hor_scroll, ScrollbarSpriteData::normal, ScrollbarSpriteData::shaded, GuiSprites::vert_scroll, ImageData::width, WLS_LEFT_BUTTON, WT_HOR_SCROLLBAR, and BaseWidget::wtype.
Referenced by CalculateSliderPosition(), and GetClickedComponent().
int ScrollbarWidget::GetIncrementButtonSize () const private
Get the size of the right / bottom / increment button in the direction of the scrollbar.
Returns
Size of the increment button in the direction of the scrollbar.
Definition at line 850 of file widget.cpp.
References _gui_sprites, GuiSprites::hor_scroll, ScrollbarSpriteData::normal, ScrollbarSpriteData::shaded, GuiSprites::vert_scroll, ImageData::width, WLS_RIGHT_BUTTON, WT_HOR_SCROLLBAR, and BaseWidget::wtype.
Referenced by CalculateSliderPosition(), and GetClickedComponent().
void ScrollbarWidget::CalculateSliderPosition (int * start_edge, int * slider_length) private
Calculate the position and sizes of the displayed scrollbar components.
Parameters
start_edge [out] Starting point of the slider in pixels, relative to the scrollbar top or left.
slider_length [out] Length of the slider in pixels, relative to the scrollbar top or left.
Definition at line 863 of file widget.cpp.
References GetDecrementButtonSize(), GetIncrementButtonSize(), GetVisibleCount(), item_count, BaseWidget::pos, start, Rectangle< PT, SZ >::width, WT_HOR_SCROLLBAR, and BaseWidget::wtype.
Referenced by Draw(), and GetClickedComponent().
ScrollbarComponent ScrollbarWidget::GetClickedComponent (const Point16 & pos) private
Decide which part of the scrollbar was clicked.
Parameters
pos Clicked position in the scrollbar widget.
Returns
Component being clicked.
Definition at line 664 of file widget.cpp.
References CalculateSliderPosition(), GetDecrementButtonSize(), GetIncrementButtonSize(), SBC_AFTER_SLIDER, SBC_BEFORE_SLIDER, SBC_DECREMENT_BUTTON, SBC_INCREMENT_BUTTON, SBC_SLIDER, WT_HOR_SCROLLBAR, BaseWidget::wtype, Point< CT >::x, and Point< CT >::y.
Referenced by OnClick().
void LeafWidget::AutoRaiseButtons (const Point32 & base) override virtual inherited
Raise all push buttons in the tree.
Parameters
base Base position of the window.
Reimplemented from BaseWidget.
Reimplemented in BackgroundWidget.
Definition at line 327 of file widget.cpp.
References LeafWidget::IsPressed(), BaseWidget::MarkDirty(), LeafWidget::SetPressed(), WT_IMAGE_PUSHBUTTON, WT_TEXT_PUSHBUTTON, and BaseWidget::wtype.
bool LeafWidget::IsChecked () const inline inherited
Is the 'checked' flag on?
Returns
whether the 'checked' flag is set.
Definition at line 138 of file widget.h.
References LWF_CHECKED.
Referenced by GuiWindow::GetSelectedRadioButton(), and GuiWindow::SetWidgetChecked().
bool LeafWidget::IsPressed () const inline inherited
Is the 'pressed' flag on?
Returns
whether the 'pressed' flag is set.
Definition at line 147 of file widget.h.
References LWF_PRESSED.
Referenced by LeafWidget::AutoRaiseButtons(), DataWidget::Draw(), GuiWindow::GetSelectedRadioButton(), and GuiWindow::SetWidgetPressed().
bool LeafWidget::IsShaded () const inline inherited
Is the 'shaded' flag on?
Returns
whether the 'shaded' flag is set.
Definition at line 156 of file widget.h.
References LWF_SHADED.
Referenced by DataWidget::Draw(), Draw(), GuiWindow::GetSelectedRadioButton(), GuiWindow::OnMouseButtonEvent(), and GuiWindow::SetWidgetShaded().
void LeafWidget::SetChecked (bool value) inline inherited
Set the 'checked' flag to the new value.
Parameters
value New value of the 'checked' flag.
Definition at line 165 of file widget.h.
References LWF_CHECKED.
Referenced by GuiWindow::SetWidgetChecked().
void LeafWidget::SetPressed (bool value) inline inherited
Set the 'pressed' flag to the new value.
Parameters
value New value of the 'pressed' flag.
Definition at line 174 of file widget.h.
References LWF_PRESSED.
Referenced by LeafWidget::AutoRaiseButtons(), GuiWindow::OnMouseButtonEvent(), and GuiWindow::SetWidgetPressed().
void LeafWidget::SetShaded (bool value) inline inherited
Set the 'shaded' flag to the new value.
Parameters
value New value of the 'shaded' flag.
Definition at line 183 of file widget.h.
References LWF_SHADED.
Referenced by GuiWindow::SetWidgetShaded().
void BaseWidget::SetSmallestSizePosition (const Rectangle16 & rect) virtual inherited
Set the minimal size of the widget, and assign rect to the current position and size.
Parameters
rect Smallest size, and suggested position of the (entire) widget.
Reimplemented in IntermediateWidget, and BackgroundWidget.
Definition at line 172 of file widget.cpp.
References Rectangle< PT, SZ >::height, BaseWidget::min_x, BaseWidget::min_y, BaseWidget::pos, and Rectangle< PT, SZ >::width.
Referenced by GuiWindow::ResetSize(), BackgroundWidget::SetSmallestSizePosition(), and IntermediateWidget::SetSmallestSizePosition().
BaseWidget * BaseWidget::GetWidgetByPosition (const Point16 & pt) virtual inherited
Get the widget at the given relative window position.
Parameters
pt Relative point.
Returns
The widget underneath the point, or nullptr.
Reimplemented in IntermediateWidget, and BackgroundWidget.
Definition at line 194 of file widget.cpp.
References Rectangle< PT, SZ >::IsPointInside(), and BaseWidget::pos.
Referenced by BackgroundWidget::GetWidgetByPosition(), IntermediateWidget::GetWidgetByPosition(), and GuiWindow::OnMouseButtonEvent().
void BaseWidget::MarkDirty (const Point32 & base) const inherited
Denote the widget as being needed to redraw.
Parameters
base Window base coordinate.
Definition at line 212 of file widget.cpp.
References _video, VideoSystem::MarkDisplayDirty(), Point< CT >::x, and Point< CT >::y.
Referenced by LeafWidget::AutoRaiseButtons(), GuiWindow::MarkWidgetDirty(), OnClick(), GuiWindow::OnMouseButtonEvent(), GuiWindow::SetWidgetChecked(), GuiWindow::SetWidgetPressed(), and GuiWindow::SetWidgetShaded().
void BaseWidget::SetWidget (BaseWidget ** wid_array) protected inherited
Add the widget to the widget array wid_array.
Parameters
wid_array The widget array.
Definition at line 128 of file widget.cpp.
References BaseWidget::number.
Referenced by BaseWidget::SetupMinimalSize(), LeafWidget::SetupMinimalSize(), DataWidget::SetupMinimalSize(), SetupMinimalSize(), BackgroundWidget::SetupMinimalSize(), and IntermediateWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
Parameters
content_width Minimal width of the content.
content_height Minimal height of the content.
border_hor Horizontal border space.
border_vert Vertical border space.
Definition at line 97 of file widget.cpp.
References BaseWidget::min_x, BaseWidget::min_y, PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, and BaseWidget::paddings.
Referenced by LeafWidget::SetupMinimalSize(), and DataWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (const BorderSpriteData * bsd, uint16 content_width, uint16 content_height) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Parameters
bsd Used border sprites.
content_width Minimal width of the content.
content_height Minimal height of the content.
Definition at line 109 of file widget.cpp.
References BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, BaseWidget::fill_x, BaseWidget::fill_y, BorderSpriteData::hor_stepsize, LeastCommonMultiple(), BorderSpriteData::min_height, BorderSpriteData::min_width, BaseWidget::resize_x, BaseWidget::resize_y, and BorderSpriteData::vert_stepsize.
Member Data Documentation
uint8 LeafWidget::flags inherited
Flags of the leaf widget.
See also
LeafWidgetFlags
Definition at line 188 of file widget.h.
Referenced by LeafWidget::Draw(), and LeafWidget::LeafWidget().
The documentation for this class was generated from the following files:
widget.h
widget.cpp