FreeRCT: SelectMouseMode Class Reference
SelectMouseMode Class Reference
Mouse mode to select objects with a mouse click.
#include <select_mode.h>
Public Member Functions
bool MayActivateMode () override
Query the mode whether it can be enabled.
void ActivateMode (const Point16 &pos) override
Activate the mouse mode.
void LeaveMode () override
Notification that the mouse mode is about to be disabled.
void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) override
The mouse moved while in this mouse mode.
void OnMouseButtonEvent (Viewport *vp, uint8 state) override
A mouse click was detected.
bool EnableCursors () override
Control display of cursors in the mouse mode.
virtual void OnMouseWheelEvent (Viewport *vp, int direction)
A mouse wheelie event has been detected.
Public Attributes
uint8 mouse_state
Last known mouse button state.
const WindowTypes wtype
Type of window associated with this mouse mode.
const ViewportMouseMode mode
Mouse mode implemented by the object.
Detailed Description
Mouse mode to select objects with a mouse click.
Definition at line 16 of file select_mode.h.
Member Function Documentation
bool SelectMouseMode::MayActivateMode () override virtual
Query the mode whether it can be enabled.
Method may be called at any moment (or more often than once). Answering true does not mean the mouse mode will be activated.
Returns
Whether the mode may be enabled.
Implements MouseMode.
Definition at line 28 of file select_mode.cpp.
void SelectMouseMode::ActivateMode (const Point16 & pos) override virtual
Activate the mouse mode.
Parameters
pos Last known mouse position.
Implements MouseMode.
Definition at line 33 of file select_mode.cpp.
References mouse_state.
void SelectMouseMode::LeaveMode () override virtual
Notification that the mouse mode is about to be disabled.
Implements MouseMode.
Definition at line 38 of file select_mode.cpp.
void SelectMouseMode::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) override virtual
The mouse moved while in this mouse mode.
Parameters
vp Viewport object.
old_pos Previous position.
pos Current position.
Reimplemented from MouseMode.
Definition at line 42 of file select_mode.cpp.
References MB_RIGHT, mouse_state, Viewport::MoveViewport(), Point< CT >::x, and Point< CT >::y.
void SelectMouseMode::OnMouseButtonEvent (Viewport * vp, uint8 state) override virtual
A mouse click was detected.
Parameters
vp Viewport object.
state State of the mouse buttons.
See also
MouseButtons
Reimplemented from MouseMode.
Definition at line 50 of file select_mode.cpp.
References _rides_manager, Viewport::ComputeCursorPosition(), CS_PERSON, CS_RIDE, FW_TILE, RideInstance::GetKind(), RidesManager::GetRideInstance(), MB_CURRENT, mouse_state, FinderData::person, FinderData::ride, RTK_COASTER, RTK_SHOP, ShowCoasterManagementGui(), ShowGuestInfoGui(), and ShowShopManagementGui().
bool SelectMouseMode::EnableCursors () override virtual
Control display of cursors in the mouse mode.
Returns
true when cursors should be displayed, false otherwise.
Implements MouseMode.
Definition at line 82 of file select_mode.cpp.
void MouseMode::OnMouseWheelEvent (Viewport * vp, int direction) virtual inherited
A mouse wheelie event has been detected.
Parameters
vp Viewport object.
direction Direction of movement.
Reimplemented in TileTerraformMouseMode, and FenceBuildManager.
Definition at line 1639 of file viewport.cpp.
Referenced by Viewport::OnMouseWheelEvent().
The documentation for this class was generated from the following files:
select_mode.h
select_mode.cpp