FreeRCT: DirectoryReader Class Reference
DirectoryReader Class Reference abstract
File IO
Base class for reading the contents of a directory.
#include <fileio.h>
Public Member Functions
DirectoryReader (const char dir_sep)
Base class implementation of a directory reader, never returning any content.
virtual ~DirectoryReader ()
Destructor.
virtual void OpenPath (const char *path)=0
Set up the directory reader object for reading a directory.
virtual const char * NextEntry ()=0
Get next entry of the directory contents.
virtual void ClosePath ()=0
Denote no further interest in reading the contents of the current directory.
const char * NextFile ()
Get the next file entry.
virtual const char * MakePath (const char *directory, const char *fname)=0
Construct a path from a directory and a file name.
virtual bool EntryIsFile ()=0
Test whether the last returned entry from NextEntry is a file.
virtual bool EntryIsDirectory ()=0
Test whether the last returned entry from NextEntry is a directory.
Public Attributes
const char dir_sep
Directory separator character.
Detailed Description
Base class for reading the contents of a directory.
Intended use:
After creation (with the MakeDirectoryReader function), call OpenPath to open the directory.
A new entry of the directory is returned with every call to NextEntry.
At the end, call ClosePath to allow the object to clean up, and get ready for a next use.
Alternatively, use MakePath to construct a path you want to examine.
Definition at line 25 of file fileio.h.
Constructor & Destructor Documentation
DirectoryReader::DirectoryReader (const char dir_sep)
Base class implementation of a directory reader, never returning any content.
Derive a new class for your operating system with more functionality.
Parameters
dir_sep Directory separator string of the operating system.
Definition at line 35 of file fileio.cpp.
DirectoryReader::~DirectoryReader () virtual
Destructor.
Definition at line 40 of file fileio.cpp.
Member Function Documentation
void DirectoryReader::OpenPath (const char * path) pure virtual
Set up the directory reader object for reading a directory.
Parameters
path Path to the directory.
Note
Failure is not reported here, but NextEntry will not return anything useful.
Implemented in WindowsDirectoryReader, and UnixDirectoryReader.
Referenced by RcdFileCollection::ScanDirectories().
const char * DirectoryReader::NextEntry () pure virtual
Get next entry of the directory contents.
Returns
Pointer to name of next entry (as a file path suitable for opening a file). Returns nullptr if not next entry exists.
Note
The memory returned is owned by the DirectoryReader object, and should not be released.
Implemented in WindowsDirectoryReader, and UnixDirectoryReader.
Referenced by NextFile().
const char * DirectoryReader::NextFile ()
Get the next file entry.
Pulls entries from NextEntry, until the end is reached or until a file is returned.
Returns
Next file entry, if available.
Definition at line 88 of file fileio.cpp.
References EntryIsFile(), and NextEntry().
Referenced by RcdFileCollection::ScanDirectories().
const char * DirectoryReader::MakePath (const char * directory, const char * fname) pure virtual
Construct a path from a directory and a file name.
Parameters
directory Directory part of the path.
fname File name part of the path.
Returns
The combined path to the file.
Implemented in WindowsDirectoryReader, and UnixDirectoryReader.
bool DirectoryReader::EntryIsFile () pure virtual
Test whether the last returned entry from NextEntry is a file.
Returns
Whether the entry is a file.
Implemented in WindowsDirectoryReader, and UnixDirectoryReader.
Referenced by NextFile().
bool DirectoryReader::EntryIsDirectory () pure virtual
Test whether the last returned entry from NextEntry is a directory.
Returns
Whether the entry is a directory.
Implemented in WindowsDirectoryReader, and UnixDirectoryReader.
The documentation for this class was generated from the following files:
fileio.h
fileio.cpp