FreeRCT: SpriteFilesBlock Class Reference
SpriteFilesBlock Class Reference
A 'spritefiles' block.
#include <nodes.h>
Public Member Functions
std::shared_ptr< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos) override
Get a subnode for the given row and col.
Public Attributes
Position pos
Line number defining the sheet.
FilePattern file
File pattern representing the files to load.
FilePattern recolour
File pattern representing the files containing 32bpp recolour information, if available.
int xbase
Horizontal base offset in the sheet.
int ybase
Vertical base offset in the sheet.
int xoffset
Sprite offset (from the origin to the left edge of the sprite).
int yoffset
Sprite offset (from the origin to the top edge of the sprite).
int width
Width of a sprite.
int height
Height of a sprite.
bool crop
Crop sprite.
std::shared_ptr< BitMask > mask
Bit mask to apply first (if available).
Detailed Description
A 'spritefiles' block.
Definition at line 162 of file nodes.h.
Member Function Documentation
std::shared_ptr< BlockNode > SpriteFilesBlock::GetSubNode (int row, int col, const char * name, const Position & pos) override virtual
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented from BlockNode.
Definition at line 338 of file nodes.cpp.
References crop, file, FilePattern::GetCount(), height, ImageFile::Is8bpp(), FilePattern::length, ImageFile::LoadFile(), FilePattern::MakeFilename(), mask, recolour, Image32bpp::SetRecolourImage(), Position::ToString(), width, xbase, xoffset, ybase, and yoffset.
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp