FreeRCT: CoasterBuildStateMouse Class Reference
CoasterBuildStateMouse Class Reference
State to display a track piece at the position of the mouse (at the ground).
Public Member Functions
CoasterBuildStateMouse (CoasterBuildMode &mode)
Constructor of the CoasterBuildStateMouse state.
void OpenWindow (uint16 instance) const override
Notification to the mouse mode that a coaster construction window has been opened.
void CloseWindow (uint16 instance) const override
Notification to the mouse mode that a coaster construction window has been closed.
bool MayActivateMode () const override
Query from the viewport whether the mouse mode may be activated.
void ActivateMode (const Point16 &pos) const override
Notification from the viewport that the mouse mode has been activated.
void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) const override
Notification from the viewport that the mouse has moved.
void OnMouseButtonEvent (Viewport *vp, uint8 state) const override
Notification from the viewport that a mouse button has changed value.
void LeaveMode () const override
Notification from the viewport that the mouse mode has been de-activated.
bool EnableCursors () const override
Query from the viewport whether the mouse mode wants to have cursors displayed.
void ShowNoPiece (uint16 instance) const override
Notification from the construction window to display no track piece.
void SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction) const override
Notification from the construction window to display a track piece attached to the mouse cursor.
void DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, const XYZPoint16 &vox, TileEdge direction) const override
Notification from the construction window to display a track piece at a given position.
Public Attributes
CoasterBuildMode *const mode
Coaster build mouse mode.
Detailed Description
State to display a track piece at the position of the mouse (at the ground).
Definition at line 937 of file coaster_gui.cpp.
Constructor & Destructor Documentation
CoasterBuildStateMouse::CoasterBuildStateMouse (CoasterBuildMode & mode) inline
Constructor of the CoasterBuildStateMouse state.
Parameters
mode Builder mode.
Definition at line 943 of file coaster_gui.cpp.
Member Function Documentation
void CoasterBuildStateMouse::OpenWindow (uint16 instance) const inline override virtual
Notification to the mouse mode that a coaster construction window has been opened.
Parameters
instance Ride number of the window.
Implements CoasterBuildState.
Definition at line 947 of file coaster_gui.cpp.
void CoasterBuildStateMouse::CloseWindow (uint16 instance) const inline override virtual
Notification to the mouse mode that a coaster construction window has been closed.
Parameters
instance Ride number of the window.
Implements CoasterBuildState.
Definition at line 951 of file coaster_gui.cpp.
References _mouse_modes, BS_DOWN, CoasterBuildMode::DisableDisplay(), CoasterBuildMode::instance, CoasterBuildState::mode, CoasterBuildMode::SetState(), MouseModes::SetViewportMousemode(), and CoasterBuildMode::UpdateDisplay().
bool CoasterBuildStateMouse::MayActivateMode () const inline override virtual
Query from the viewport whether the mouse mode may be activated.
Returns
The mouse mode may be activated.
See also
MouseMode::MayActivateMode
Implements CoasterBuildState.
Definition at line 960 of file coaster_gui.cpp.
void CoasterBuildStateMouse::ActivateMode (const Point16 & pos) const inline override virtual
Notification from the viewport that the mouse mode has been activated.
Parameters
pos Current mouse position.
See also
MouseMode::ActivateMode
Implements CoasterBuildState.
Definition at line 965 of file coaster_gui.cpp.
References CoasterBuildState::mode, CoasterBuildMode::SetMousePosition(), and CoasterBuildMode::UpdateDisplay().
void CoasterBuildStateMouse::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) const inline override virtual
Notification from the viewport that the mouse has moved.
Parameters
vp The viewport.
old_pos Previous position of the mouse.
pos Current mouse position.
See also
MouseMode::OnMouseMoveEvent
Implements CoasterBuildState.
Definition at line 971 of file coaster_gui.cpp.
References CoasterBuildState::mode, CoasterBuildMode::SetMousePosition(), and CoasterBuildMode::UpdateDisplay().
void CoasterBuildStateMouse::OnMouseButtonEvent (Viewport * vp, uint8 state) const inline override virtual
Notification from the viewport that a mouse button has changed value.
Parameters
vp The viewport.
state Old and new state of the mouse buttons.
See also
MouseMode::OnMouseButtonEvent
Implements CoasterBuildState.
Definition at line 977 of file coaster_gui.cpp.
References BS_ON, PositionedTrackPiece::CanBePlaced(), CHG_PIECE_POSITIONED, CoasterBuildMode::instance, CoasterBuildState::mode, NotifyChange(), CoasterBuildMode::SetNoPiece(), CoasterBuildMode::SetState(), CoasterBuildMode::track_pos, CoasterBuildMode::UpdateDisplay(), and WC_COASTER_BUILD.
void CoasterBuildStateMouse::LeaveMode () const inline override virtual
Notification from the viewport that the mouse mode has been de-activated.
See also
MouseMode::LeaveMode
Implements CoasterBuildState.
Definition at line 988 of file coaster_gui.cpp.
References BS_STARTING, CoasterBuildMode::DisableDisplay(), CoasterBuildState::mode, CoasterBuildMode::SetState(), and CoasterBuildMode::UpdateDisplay().
bool CoasterBuildStateMouse::EnableCursors () const inline override virtual
Query from the viewport whether the mouse mode wants to have cursors displayed.
Returns
Cursors should be enabled.
See also
MouseMode::EnableCursors
Implements CoasterBuildState.
Definition at line 995 of file coaster_gui.cpp.
void CoasterBuildStateMouse::ShowNoPiece (uint16 instance) const inline override virtual
Notification from the construction window to display no track piece.
Parameters
instance Ride number of the window.
Implements CoasterBuildState.
Definition at line 1000 of file coaster_gui.cpp.
References BS_ON, CoasterBuildMode::instance, CoasterBuildState::mode, CoasterBuildMode::SetNoPiece(), CoasterBuildMode::SetState(), and CoasterBuildMode::UpdateDisplay().
void CoasterBuildStateMouse::SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction) const inline override virtual
Notification from the construction window to display a track piece attached to the mouse cursor.
Parameters
instance Ride number of the window.
piece Track piece to display.
direction Direction of building (to use with a cursor).
Implements CoasterBuildState.
Definition at line 1008 of file coaster_gui.cpp.
References CoasterBuildMode::instance, CoasterBuildState::mode, CoasterBuildMode::SetSelectPosition(), and CoasterBuildMode::UpdateDisplay().
void CoasterBuildStateMouse::DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, const XYZPoint16 & vox, TileEdge direction) const inline override virtual
Notification from the construction window to display a track piece at a given position.
Parameters
instance Ride number of the window.
piece Track piece to display.
vox Position of the piece.
direction Direction of building (to use with a cursor).
Implements CoasterBuildState.
Definition at line 1015 of file coaster_gui.cpp.
References BS_FIXED, CoasterBuildMode::instance, CoasterBuildState::mode, CoasterBuildMode::SetFixedPiece(), CoasterBuildMode::SetState(), and CoasterBuildMode::UpdateDisplay().
The documentation for this class was generated from the following file:
coaster_gui.cpp