FreeRCT: Guests Class Reference
Guests Class Reference
All our guests.
#include <people.h>
Public Member Functions
void Initialize ()
After loading the RCD files, check what resources actually exist.
bool CanUsePersonType (PersonType ptype)
Can guests of the given person type be used for the level?
uint CountActiveGuests ()
Count the number of active guests.
void OnAnimate (int delay)
Some time has passed, update the animation.
void DoTick ()
A new frame arrived, perform the daily call for some of the guests.
void OnNewDay ()
A new day arrived, handle daily chores of the park.
Private Member Functions
bool FindNextFreeGuest ()
Update free_idx to the next free guest (if available).
bool FindNextFreeGuest () const
Update free_idx to the next free guest (if available).
bool HasFreeGuests () const
Return whether there are still non-active guests.
void AddFree (Guest *g)
Add a guest to the non-active list.
Guest * GetFree ()
Get a non-active guest.
Private Attributes
GuestBlock block
The data of all actual guests.
uint free_idx
All guests less than this index are active.
Random rnd
Random number generator for creating new guests.
Point16 start_voxel
Entry x/y coordinate of the voxel stack at the edge.
int daily_frac
Frame counter.
int next_daily_index
Index of the next guest to give daily service.
uint16 valid_ptypes
Person types that can be used.
Detailed Description
All our guests.
Todo:
Allow to have several blocks of guests.
Definition at line 64 of file people.h.
Member Function Documentation
void Guests::Initialize ()
After loading the RCD files, check what resources actually exist.
Definition at line 86 of file people.cpp.
References _sprite_manager, ANIM_BEGIN, ANIM_LAST, SpriteManager::GetAnimation(), PERSON_MAX_GUEST, PERSON_MIN_GUEST, and valid_ptypes.
Referenced by StartNewGame().
bool Guests::CanUsePersonType (PersonType ptype)
Can guests of the given person type be used for the level?
Parameters
ptype Person type to examine.
Returns
Whether the given person type can be used for playing a level.
Definition at line 106 of file people.cpp.
References PERSON_MAX_GUEST, PERSON_MIN_GUEST, and valid_ptypes.
Referenced by OnNewDay().
uint Guests::CountActiveGuests ()
Count the number of active guests.
Returns
The number of active guests.
Definition at line 145 of file people.cpp.
References block, free_idx, GuestBlock::Get(), GUEST_BLOCK_SIZE, and Person::IsActive().
Referenced by OnNewDay().
void Guests::OnAnimate (int delay)
Some time has passed, update the animation.
Parameters
delay Number of milliseconds time that have past since the last animation update.
Definition at line 159 of file people.cpp.
References AddFree(), block, Guest::DeActivate(), GuestBlock::Get(), GUEST_BLOCK_SIZE, Person::IsActive(), OAR_OK, and Person::OnAnimate().
Referenced by OnNewFrame().
void Guests::DoTick ()
A new frame arrived, perform the daily call for some of the guests.
Definition at line 174 of file people.cpp.
References AddFree(), block, daily_frac, Guest::DailyUpdate(), Guest::DeActivate(), GuestBlock::Get(), GUEST_BLOCK_SIZE, Person::IsActive(), next_daily_index, OAR_REMOVE, and TICK_COUNT_PER_DAY.
Referenced by OnNewFrame().
void Guests::OnNewDay ()
A new day arrived, handle daily chores of the park.
Todo:
Add popularity rating concept.
Person type should be configurable too.
Definition at line 197 of file people.cpp.
References _scenario, Guest::Activate(), CanUsePersonType(), CountActiveGuests(), FindEdgeRoad(), GetFree(), Scenario::GetSpawnProbability(), HasFreeGuests(), IsGoodEdgeRoad(), Scenario::max_guests, PERSON_PILLAR, rnd, start_voxel, Random::Success1024(), and Point< CT >::x.
Referenced by OnNewDay().
bool Guests::FindNextFreeGuest () private
Update free_idx to the next free guest (if available).
Returns
Whether a free guest was found.
Definition at line 116 of file people.cpp.
References block, free_idx, GuestBlock::Get(), GUEST_BLOCK_SIZE, and Person::IsActive().
Referenced by GetFree(), and HasFreeGuests().
bool Guests::FindNextFreeGuest () const private
Update free_idx to the next free guest (if available).
Returns
Whether a free guest was found.
Definition at line 130 of file people.cpp.
References block, free_idx, GuestBlock::Get(), GUEST_BLOCK_SIZE, and Person::IsActive().
bool Guests::HasFreeGuests () const private
Return whether there are still non-active guests.
Returns
true if there are non-active guests, else false.
Definition at line 220 of file people.cpp.
References FindNextFreeGuest().
Referenced by OnNewDay().
void Guests::AddFree (Guest * g) private
Add a guest to the non-active list.
Parameters
g Guest to add.
Definition at line 229 of file people.cpp.
References block, free_idx, and GuestBlock::Index().
Referenced by DoTick(), and OnAnimate().
Guest * Guests::GetFree () private
Get a non-active guest.
Returns
A non-active guest.
Precondition
HasFreeGuests() should hold.
Definition at line 239 of file people.cpp.
References block, FindNextFreeGuest(), free_idx, and GuestBlock::Get().
Referenced by OnNewDay().
The documentation for this class was generated from the following files:
people.h
people.cpp