FreeRCT: FENCBlock Class Reference
FENCBlock Class Reference
'FENC' game block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int tile_width
Zoom-width of a tile of the surface.
uint16 type
Type of fence.
std::shared_ptr< SpriteBlock > ne_hor
Horizontal fence graphics of the north-east edge.
std::shared_ptr< SpriteBlock > ne_n
Fence graphics of the north-east edge, north side raised.
std::shared_ptr< SpriteBlock > ne_e
Fence graphics of the north-east edge, east side raised.
std::shared_ptr< SpriteBlock > se_hor
Horizontal fence graphics of the south-east edge.
std::shared_ptr< SpriteBlock > se_e
Fence graphics of the south-east edge, east side raised.
std::shared_ptr< SpriteBlock > se_s
Fence graphics of the south-east edge, south side raised.
std::shared_ptr< SpriteBlock > sw_hor
Horizontal fence graphics of the south-west edge.
std::shared_ptr< SpriteBlock > sw_s
Fence graphics of the south-west edge, south side raised.
std::shared_ptr< SpriteBlock > sw_w
Fence graphics of the south-west edge, west side raised.
std::shared_ptr< SpriteBlock > nw_hor
Horizontal fence graphics of the north-west edge.
std::shared_ptr< SpriteBlock > nw_w
Fence graphics of the north-west edge, west side raised.
std::shared_ptr< SpriteBlock > nw_n
Fence graphics of the north-west edge, north side raised.
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
'FENC' game block.
Definition at line 924 of file nodes.h.
Member Function Documentation
int FENCBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 1728 of file nodes.cpp.
References FileWriter::AddBlock(), NamedBlock::blk_name, FileBlock::CheckEndSave(), ne_e, ne_hor, ne_n, nw_hor, nw_n, nw_w, FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), se_e, se_hor, se_s, FileBlock::StartSave(), sw_hor, sw_s, sw_w, tile_width, type, and NamedBlock::version.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp