FreeRCT: Position Class Reference
Position Class Reference
Position in a source file.
#include <ast.h>
Public Member Functions
Position (const char *filename, int line)
Constructor of a position.
Position (const std::string &filename, int line)
Constructor of a position.
Position (const Position &pos)
Constructor of a position.
Position & operator= (const Position &pos)
Assignment of a position.
const char * ToString () const
Construct a human-readable position string.
Public Attributes
std::string filename
File containing the line.
int line
Number of the line referred to.
Detailed Description
Position in a source file.
Definition at line 20 of file ast.h.
Constructor & Destructor Documentation
Position::Position (const char * filename, int line)
Constructor of a position.
Parameters
filename Name of the file containing the position.
line Line number in the file.
Definition at line 28 of file ast.cpp.
References line.
Position::Position (const std::string & filename, int line)
Constructor of a position.
Parameters
filename Name of the file containing the position.
line Line number in the file.
Definition at line 38 of file ast.cpp.
References line.
Position::Position (const Position & pos)
Constructor of a position.
Parameters
pos Position to copy.
Definition at line 47 of file ast.cpp.
References line.
Member Function Documentation
Position & Position::operator= (const Position & pos)
Assignment of a position.
Parameters
pos Position to copy.
Returns
The assigned object.
Definition at line 57 of file ast.cpp.
References filename, and line.
const char * Position::ToString () const
Construct a human-readable position string.
Returns
Human-readable indication of a position (filename and line number).
Note
Text is only temporary usable.
Definition at line 71 of file ast.cpp.
References filename, and line.
Referenced by StringsNode::Add(), StringsStorage::AddToBundle(), CheckBezierCount(), CheckSplineStepCount(), StringBundle::CheckTranslations(), TrackPieceNode::ComputeTrackLength(), UnaryOperator::Evaluate(), BinaryOperator::Evaluate(), IdentifierLiteral::Evaluate(), ExpandExpressions(), ExpandNoExpression(), StringBundle::Fill(), Values::FindValue(), ValueInformation::GetConnection(), ValueInformation::GetCurve(), GetLanguageIndex(), ValueInformation::GetNumber(), SheetBlock::GetSheet(), ValueInformation::GetSprite(), ValueInformation::GetString(), ValueInformation::GetStrings(), BlockNode::GetSubNode(), SheetBlock::GetSubNode(), SpriteFilesBlock::GetSubNode(), and StringsNode::SetKey().
The documentation for this class was generated from the following files:
ast.h
ast.cpp