FreeRCT: TileTerraformMouseMode Class Reference
TileTerraformMouseMode Class Reference
Tile terraforming mouse mode.
#include <terraform.h>
Public Member Functions
void OpenWindow ()
Terraform GUI window just opened.
void CloseWindow ()
Terraform GUI window just closed.
void SetSize (int xsize, int ysize)
Update the size of the terraform area.
void Setlevelling (bool level)
Set the 'levelling' mode.
void SetCursors ()
Set/modify the cursors of the viewport.
bool MayActivateMode () override
Query the mode whether it can be enabled.
void ActivateMode (const Point16 &pos) override
Activate the mouse mode.
void LeaveMode () override
Notification that the mouse mode is about to be disabled.
bool EnableCursors () override
Control display of cursors in the mouse mode.
void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) override
The mouse moved while in this mouse mode.
void OnMouseButtonEvent (Viewport *vp, uint8 state) override
A mouse click was detected.
void OnMouseWheelEvent (Viewport *vp, int direction) override
A mouse wheelie event has been detected.
Public Attributes
TerraformerState state
Own state.
uint8 mouse_state
Last known state of the mouse.
uint8 xsize
Horizontal size of the terraform area. May be 0, which means 'dot'.
uint8 ysize
Vertical size of the terraform area. May be 0, which means 'dot'.
signed char pixel_counter
Vertical mouse movement counter for LMB up/down terraforming.
bool levelling
For non-zero areas, true means 'level the area', and false means 'keep area as-is'.
const WindowTypes wtype
Type of window associated with this mouse mode.
const ViewportMouseMode mode
Mouse mode implemented by the object.
Detailed Description
Tile terraforming mouse mode.
Terraforms an area of the world. It has two modes, a non-zero size, meaning terraforming is limited to that area, or a zero-size (aka 'dot mode'), which means 'unlimited' (the entire world may get changed, if money (and world contents) permits.
The true 'levelling' setting means that the lowest parts are raised or the highest parts are lowered. A false 'levelling' value means that the entire area is moved up or down.
Definition at line 81 of file terraform.h.
Member Function Documentation
void TileTerraformMouseMode::OpenWindow ()
Terraform GUI window just opened.
Definition at line 591 of file terraform.cpp.
References _mouse_modes, MouseMode::mode, MouseModes::SetMouseMode(), state, TFS_NO_MOUSE, and TFS_OFF.
void TileTerraformMouseMode::CloseWindow ()
Terraform GUI window just closed.
Definition at line 600 of file terraform.cpp.
References _mouse_modes, MouseModes::SetViewportMousemode(), state, TFS_OFF, and TFS_ON.
void TileTerraformMouseMode::SetSize (int xsize, int ysize)
Update the size of the terraform area.
Parameters
xsize Horizontal length of the area. May be 0.
ysize Vertical length of the area. May be 0.
Definition at line 614 of file terraform.cpp.
References SetCursors(), state, TFS_ON, xsize, and ysize.
Referenced by TerraformGui::SetTerraformSize().
void TileTerraformMouseMode::Setlevelling (bool levelling)
Set the 'levelling' mode.
This has no further visible effect until a raise/lower action is performed.
Parameters
levelling The new levelling setting.
Definition at line 626 of file terraform.cpp.
References levelling.
Referenced by TerraformGui::Setlevelling().
void TileTerraformMouseMode::SetCursors ()
Set/modify the cursors of the viewport.
Definition at line 644 of file terraform.cpp.
References Viewport::area_cursor, Viewport::ComputeCursorPosition(), CS_GROUND, CS_NONE, CUR_TYPE_TILE, FinderData::cursor, FW_CORNER, FW_TILE, GetViewport(), Cursor::SetCursor(), MultiCursor::SetCursor(), BaseCursor::SetInvalid(), Viewport::tile_cursor, FinderData::voxel_pos, XYZPoint< CT >::x, xsize, XYZPoint< CT >::y, and ysize.
Referenced by ActivateMode(), OnMouseMoveEvent(), and SetSize().
bool TileTerraformMouseMode::MayActivateMode () override virtual
Query the mode whether it can be enabled.
Method may be called at any moment (or more often than once). Answering true does not mean the mouse mode will be activated.
Returns
Whether the mode may be enabled.
Implements MouseMode.
Definition at line 631 of file terraform.cpp.
References state, and TFS_OFF.
void TileTerraformMouseMode::ActivateMode (const Point16 & pos) override virtual
Activate the mouse mode.
Parameters
pos Last known mouse position.
Implements MouseMode.
Definition at line 636 of file terraform.cpp.
References mouse_state, SetCursors(), state, and TFS_ON.
void TileTerraformMouseMode::LeaveMode () override virtual
Notification that the mouse mode is about to be disabled.
Implements MouseMode.
Definition at line 663 of file terraform.cpp.
References Viewport::area_cursor, GetViewport(), BaseCursor::SetInvalid(), state, TFS_NO_MOUSE, TFS_ON, and Viewport::tile_cursor.
bool TileTerraformMouseMode::EnableCursors () override virtual
Control display of cursors in the mouse mode.
Returns
true when cursors should be displayed, false otherwise.
Implements MouseMode.
Definition at line 673 of file terraform.cpp.
References state, and TFS_OFF.
void TileTerraformMouseMode::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) override virtual
The mouse moved while in this mouse mode.
Parameters
vp Viewport object.
old_pos Previous position.
pos Current position.
Reimplemented from MouseMode.
Definition at line 807 of file terraform.cpp.
References ChangeAreaCursorMode(), ChangeTileCursorMode(), CUR_TYPE_INVALID, levelling, MB_LEFT, MB_RIGHT, mouse_state, Viewport::MoveViewport(), pixel_counter, SetCursors(), Viewport::tile_cursor, BaseCursor::type, Point< CT >::x, xsize, Point< CT >::y, and ysize.
void TileTerraformMouseMode::OnMouseButtonEvent (Viewport * vp, uint8 state) override virtual
A mouse click was detected.
Parameters
vp Viewport object.
state State of the mouse buttons.
See also
MouseButtons
Reimplemented from MouseMode.
Definition at line 678 of file terraform.cpp.
References MB_CURRENT, and mouse_state.
void TileTerraformMouseMode::OnMouseWheelEvent (Viewport * vp, int direction) override virtual
A mouse wheelie event has been detected.
Parameters
vp Viewport object.
direction Direction of movement.
Reimplemented from MouseMode.
Definition at line 798 of file terraform.cpp.
References ChangeAreaCursorMode(), ChangeTileCursorMode(), CUR_TYPE_INVALID, levelling, Viewport::tile_cursor, BaseCursor::type, xsize, and ysize.
The documentation for this class was generated from the following files:
terraform.h
terraform.cpp