FreeRCT: TextNode Class Reference
TextNode Class Reference
Texts (translations) of a single string.
#include <nodes.h>
Public Member Functions
TextNode (const std::string &name)
Constructor of a TextNode.
void MergeStorage (const TextNode &storage)
Merge text node from storage into this text node.
int GetSize () const
Compute the number of bytes needed to store this text node in an RCD file.
void Write (FileBlock *fb) const
Write the string and its translations into a file block.
Public Attributes
const std::string name
Name of the text node (used as key).
std::string texts [LNG_COUNT]
Text of the text node, in each language.
Position pos [LNG_COUNT]
Positions defining the text (negative lines means undefined).
Detailed Description
Texts (translations) of a single string.
Definition at line 526 of file nodes.h.
Constructor & Destructor Documentation
TextNode::TextNode (const std::string & name)
Constructor of a TextNode.
Parameters
name Name of the string stored in the text node.
Definition at line 714 of file nodes.cpp.
References LNG_COUNT, and pos.
Member Function Documentation
void TextNode::MergeStorage (const TextNode & storage)
Merge text node from storage into this text node.
Already present strings have precedence over storage strings.
Parameters
storage Text to merge.
Definition at line 723 of file nodes.cpp.
References line, Position::line, LNG_COUNT, name, pos, and texts.
int TextNode::GetSize () const
Compute the number of bytes needed to store this text node in an RCD file.
Returns
Size needed to store this string.
Definition at line 738 of file nodes.cpp.
References _languages, line, LNG_COUNT, name, pos, and texts.
Referenced by Write().
void TextNode::Write (FileBlock * fb) const
Write the string and its translations into a file block.
Parameters
fb File block to write to.
Definition at line 752 of file nodes.cpp.
References _languages, GetSize(), line, LNG_COUNT, LNG_EN_GB, name, pos, FileBlock::SaveBytes(), FileBlock::SaveUInt16(), FileBlock::SaveUInt8(), and texts.
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp