FreeRCT: IntermediateWidget Class Reference
IntermediateWidget Class Reference
Widgets and supporting functions of the program
Base class for intermediate (that is, non-leaf) widget.
#include <widget.h>
Public Member Functions
IntermediateWidget (uint8 num_rows, uint8 num_cols)
Constructor for intermediate widgets.
void SetupMinimalSize (GuiWindow *w, BaseWidget **wid_array) override
Compute smallest size of the widget.
void SetSmallestSizePosition (const Rectangle16 &rect) override
Set the smallest size of the intermediate widget (and all widgets under it).
void Draw (const GuiWindow *w) override
Draw the widget.
BaseWidget * GetWidgetByPosition (const Point16 &pt) override
Get the widget at the given relative window position.
void AutoRaiseButtons (const Point32 &base) override
Raise all push buttons in the tree.
void AddChild (uint8 col, uint8 row, BaseWidget *sub)
Add a child widget.
void ClaimMemory ()
Claim memory for child widgets 'manually'.
void MarkDirty (const Point32 &base) const
Denote the widget as being needed to redraw.
Public Attributes
BaseWidget ** childs
Grid of child widget pointers.
RowColData * rows
Row data.
RowColData * columns
Column data.
uint8 num_rows
Number of rows.
uint8 num_cols
Number of columns.
uint8 flags
Equal size flags.
WidgetType wtype
Widget type.
WidgetNumber number
Widget number.
uint16 smallest_x
Original horizontal size.
uint16 smallest_y
Original vertical size.
uint16 min_x
Minimal horizontal size.
uint16 min_y
Minimal vertical size.
Rectangle16 pos
Current position and size (relative to window top-left edge).
uint16 fill_x
Horizontal fill step.
uint16 fill_y
Vertical fill step.
uint16 resize_x
Horizontal resize step.
uint16 resize_y
Vertical resize step.
uint8 paddings [PAD_COUNT]
Padding.
Protected Member Functions
void SetWidget (BaseWidget **wid_array)
Add the widget to the widget array wid_array.
void InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert)
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
void InitMinimalSize (const BorderSpriteData *bsd, uint16 content_width, uint16 content_height)
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Detailed Description
Base class for intermediate (that is, non-leaf) widget.
Definition at line 299 of file widget.h.
Constructor & Destructor Documentation
IntermediateWidget::IntermediateWidget (uint8 num_rows, uint8 num_cols)
Constructor for intermediate widgets.
Parameters
num_rows Number of rows. Use 0 for 'manual' claiming.
num_cols Number of columns. Use 0 for 'manual' claiming.
See also
FillWidget
Definition at line 973 of file widget.cpp.
References childs, ClaimMemory(), columns, flags, num_cols, num_rows, and rows.
Member Function Documentation
void IntermediateWidget::SetupMinimalSize (GuiWindow * w, BaseWidget ** wid_array) override virtual
Compute smallest size of the widget.
Parameters
w Window owning the widget.
wid_array [out] Array of widget pointers.
Reimplemented from BaseWidget.
Definition at line 1037 of file widget.cpp.
References childs, columns, EQS_HORIZONTAL, EQS_VERTICAL, RowColData::fill, BaseWidget::fill_x, BaseWidget::fill_y, flags, GuiWindow::initialized, RowColData::InitRowColData(), lengthof, RowColData::Merge(), RowColData::min_size, BaseWidget::min_x, BaseWidget::min_y, num_cols, num_rows, PAD_BOTTOM, PAD_HORIZONTAL, PAD_LEFT, PAD_RIGHT, PAD_TOP, PAD_VERTICAL, BaseWidget::paddings, RowColData::resize, BaseWidget::resize_x, BaseWidget::resize_y, rows, BaseWidget::SetupMinimalSize(), BaseWidget::SetWidget(), BaseWidget::smallest_x, and BaseWidget::smallest_y.
void IntermediateWidget::SetSmallestSizePosition (const Rectangle16 & rect) override virtual
Set the smallest size of the intermediate widget (and all widgets under it).
Parameters
rect Smallest size to set.
Todo:
Handle RTL languages too.
Reimplemented from BaseWidget.
Definition at line 1188 of file widget.cpp.
References Rectangle< PT, SZ >::base, childs, columns, RowColData::fill, Rectangle< PT, SZ >::height, RowColData::min_size, num_cols, num_rows, PAD_BOTTOM, PAD_HORIZONTAL, PAD_LEFT, PAD_RIGHT, PAD_TOP, PAD_VERTICAL, BaseWidget::paddings, BaseWidget::pos, rows, BaseWidget::SetSmallestSizePosition(), Rectangle< PT, SZ >::width, Point< CT >::x, and Point< CT >::y.
void IntermediateWidget::Draw (const GuiWindow * w) override virtual
Draw the widget.
Parameters
w Window being drawn.
Reimplemented from BaseWidget.
Definition at line 1269 of file widget.cpp.
References childs, BaseWidget::Draw(), num_cols, and num_rows.
BaseWidget * IntermediateWidget::GetWidgetByPosition (const Point16 & pt) override virtual
Get the widget at the given relative window position.
Parameters
pt Relative point.
Returns
The widget underneath the point, or nullptr.
Reimplemented from BaseWidget.
Definition at line 1276 of file widget.cpp.
References childs, BaseWidget::GetWidgetByPosition(), Rectangle< PT, SZ >::IsPointInside(), num_cols, num_rows, and BaseWidget::pos.
void IntermediateWidget::AutoRaiseButtons (const Point32 & base) override virtual
Raise all push buttons in the tree.
Parameters
base Base position of the window.
Reimplemented from BaseWidget.
Definition at line 1288 of file widget.cpp.
References BaseWidget::AutoRaiseButtons(), childs, num_cols, and num_rows.
void IntermediateWidget::AddChild (uint8 x, uint8 y, BaseWidget * w)
Add a child widget.
Parameters
x Horizontal index of the child in the grid.
y Vertical index of the child in the grid.
w Child widget to add.
Definition at line 1025 of file widget.cpp.
References childs, num_cols, and num_rows.
Referenced by FillWidget().
void IntermediateWidget::ClaimMemory ()
Claim memory for child widgets 'manually'.
Precondition
Memory must not have been claimed, and num_cols and num_rows must be bigger than 0.
Definition at line 989 of file widget.cpp.
References childs, columns, num_cols, num_rows, and rows.
Referenced by FillWidget(), and IntermediateWidget().
void BaseWidget::MarkDirty (const Point32 & base) const inherited
Denote the widget as being needed to redraw.
Parameters
base Window base coordinate.
Definition at line 212 of file widget.cpp.
References _video, VideoSystem::MarkDisplayDirty(), Point< CT >::x, and Point< CT >::y.
Referenced by LeafWidget::AutoRaiseButtons(), GuiWindow::MarkWidgetDirty(), ScrollbarWidget::OnClick(), GuiWindow::OnMouseButtonEvent(), GuiWindow::SetWidgetChecked(), GuiWindow::SetWidgetPressed(), and GuiWindow::SetWidgetShaded().
void BaseWidget::SetWidget (BaseWidget ** wid_array) protected inherited
Add the widget to the widget array wid_array.
Parameters
wid_array The widget array.
Definition at line 128 of file widget.cpp.
References BaseWidget::number.
Referenced by BaseWidget::SetupMinimalSize(), LeafWidget::SetupMinimalSize(), DataWidget::SetupMinimalSize(), ScrollbarWidget::SetupMinimalSize(), BackgroundWidget::SetupMinimalSize(), and SetupMinimalSize().
void BaseWidget::InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
Parameters
content_width Minimal width of the content.
content_height Minimal height of the content.
border_hor Horizontal border space.
border_vert Vertical border space.
Definition at line 97 of file widget.cpp.
References BaseWidget::min_x, BaseWidget::min_y, PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, and BaseWidget::paddings.
Referenced by LeafWidget::SetupMinimalSize(), DataWidget::SetupMinimalSize(), and BackgroundWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (const BorderSpriteData * bsd, uint16 content_width, uint16 content_height) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Parameters
bsd Used border sprites.
content_width Minimal width of the content.
content_height Minimal height of the content.
Definition at line 109 of file widget.cpp.
References BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, BaseWidget::fill_x, BaseWidget::fill_y, BorderSpriteData::hor_stepsize, LeastCommonMultiple(), BorderSpriteData::min_height, BorderSpriteData::min_width, BaseWidget::resize_x, BaseWidget::resize_y, and BorderSpriteData::vert_stepsize.
The documentation for this class was generated from the following files:
widget.h
widget.cpp