FreeRCT: PDECBlock Class Reference
PDECBlock Class Reference
Path decoration PDEC block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int tile_width
Width of the tile.
std::shared_ptr< SpriteBlock > litter_bin [4]
Litter bin (4 edges).
std::shared_ptr< SpriteBlock > overflow_bin [4]
Overflowing litter bin (4 edges).
std::shared_ptr< SpriteBlock > demolished_bin [4]
Demolished litter bin (4 edges).
std::shared_ptr< SpriteBlock > lamp_post [4]
Lamp post (4 edges).
std::shared_ptr< SpriteBlock > demolished_post [4]
Demolished lamp post (4 edges).
std::shared_ptr< SpriteBlock > bench [4]
Benches (4 edges).
std::shared_ptr< SpriteBlock > demolished_bench [4]
Demolished benches (4 edges).
std::shared_ptr< SpriteBlock > litter_flat [4]
Litter at flat path (4 types).
std::shared_ptr< SpriteBlock > litter_ne [4]
Litter at ramp, NE edge up (4 types).
std::shared_ptr< SpriteBlock > litter_se [4]
Litter at ramp, SE edge up (4 types).
std::shared_ptr< SpriteBlock > litter_sw [4]
Litter at ramp, SW edge up (4 types).
std::shared_ptr< SpriteBlock > litter_nw [4]
Litter at ramp, NW edge up (4 types).
std::shared_ptr< SpriteBlock > vomit_flat [4]
Vomit at flat path (4 types).
std::shared_ptr< SpriteBlock > vomit_ne [4]
Vomit at ramp, NE edge up (4 types).
std::shared_ptr< SpriteBlock > vomit_se [4]
Vomit at ramp, SE edge up (4 types).
std::shared_ptr< SpriteBlock > vomit_sw [4]
Vomit at ramp, SW edge up (4 types).
std::shared_ptr< SpriteBlock > vomit_nw [4]
Vomit at ramp, NW edge up (4 types).
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
Path decoration PDEC block.
Definition at line 407 of file nodes.h.
Member Function Documentation
int PDECBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 588 of file nodes.cpp.
References FileWriter::AddBlock(), bench, NamedBlock::blk_name, FileBlock::CheckEndSave(), demolished_bench, demolished_bin, demolished_post, lamp_post, litter_bin, litter_flat, litter_ne, litter_nw, litter_se, litter_sw, overflow_bin, FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), FileBlock::StartSave(), tile_width, NamedBlock::version, vomit_flat, vomit_ne, vomit_nw, vomit_se, vomit_sw, and WriteSprite().
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp