FreeRCT: FileBlock Class Reference
FileBlock Class Reference
A block in an RCD file.
#include <file_writing.h>
Public Member Functions
void StartSave (const char *blk_name, int version, int data_length)
Set up storing of data to the file block.
void SaveUInt8 (uint8 d)
Save a 8 bit unsigned value into the file block.
void SaveInt8 (int8 d)
Save a 8 bit signed value into the file block.
void SaveUInt16 (uint16 d)
Save a 16 bit unsigned value into the file block.
void SaveInt16 (uint16 d)
Save a 16 bit signed value into the file block.
void SaveUInt32 (uint32 d)
Save a 32 bit unsigned value into the file block.
void SaveBytes (uint8 *data, int size)
Save a sequence of bytes in the file block.
void CheckEndSave ()
Check that all data has been written.
void Write (FILE *fp)
Write the file block to the output.
Public Attributes
uint8 * data
Data of the block.
int length
Length of the block.
int save_index
Index in data to write content into the file block.
Detailed Description
A block in an RCD file.
See StartSave for details on usage.
Definition at line 19 of file file_writing.h.
Member Function Documentation
void FileBlock::StartSave (const char * blk_name, int version, int data_length)
Set up storing of data to the file block.
Supply name of the block, version number, and expected data length (without the 12 byte header). After setting up, use SaveUInt8, SaveUInt16, SaveUInt32, and SaveBytes to store the data in the block. Afterwards, use CheckEndSave to verify the amount of actually written data matches with the expected length.
Parameters
blk_name Name of the block (a 4 character text string).
version Version of the block.
data_length Length of the data part (that is, excluding the header).
Definition at line 35 of file file_writing.cpp.
References data, length, save_index, SaveBytes(), and SaveUInt32().
Referenced by SpriteBlock::Write(), TSELBlock::Write(), TCORBlock::Write(), SURFBlock::Write(), FUNDBlock::Write(), PRSGBlock::Write(), ANIMBlock::Write(), ANSPBlock::Write(), PATHBlock::Write(), PDECBlock::Write(), PLATBlock::Write(), SUPPBlock::Write(), StringBundle::Write(), SHOPBlock::Write(), GBORBlock::Write(), GCHKBlock::Write(), GSLIBlock::Write(), GSCLBlock::Write(), BDIRBlock::Write(), GSLPBlock::Write(), TrackPieceNode::Write(), RCSTBlock::Write(), CARSBlock::Write(), CSPLBlock::Write(), FENCBlock::Write(), and INFOBlock::Write().
void FileBlock::SaveUInt8 (uint8 d)
Save a 8 bit unsigned value into the file block.
Parameters
d Value to write.
Definition at line 52 of file file_writing.cpp.
References data, length, and save_index.
Referenced by SaveBytes(), SaveCarEntry(), SaveInt16(), SaveInt8(), SaveUInt16(), PRSGBlock::Write(), ANIMBlock::Write(), ANSPBlock::Write(), TextNode::Write(), SHOPBlock::Write(), GBORBlock::Write(), GSLIBlock::Write(), GSCLBlock::Write(), TrackVoxel::Write(), TrackPieceNode::Write(), RCSTBlock::Write(), CSPLBlock::Write(), and INFOBlock::Write().
void FileBlock::SaveInt8 (int8 d)
Save a 8 bit signed value into the file block.
Parameters
d Value to write.
Definition at line 63 of file file_writing.cpp.
References SaveUInt8().
Referenced by TrackVoxel::Write(), and TrackPieceNode::Write().
void FileBlock::SaveUInt16 (uint16 d)
Save a 16 bit unsigned value into the file block.
Parameters
d Value to write.
Definition at line 72 of file file_writing.cpp.
References SaveUInt8().
Referenced by SaveCarEntry(), SaveUInt32(), SpriteBlock::Write(), TSELBlock::Write(), TCORBlock::Write(), SURFBlock::Write(), FUNDBlock::Write(), ANIMBlock::Write(), ANSPBlock::Write(), PATHBlock::Write(), PDECBlock::Write(), PLATBlock::Write(), SUPPBlock::Write(), TextNode::Write(), SHOPBlock::Write(), GBORBlock::Write(), GCHKBlock::Write(), GSLIBlock::Write(), GSCLBlock::Write(), BDIRBlock::Write(), TrackPieceNode::Write(), RCSTBlock::Write(), CARSBlock::Write(), CSPLBlock::Write(), and FENCBlock::Write().
void FileBlock::SaveInt16 (uint16 d)
Save a 16 bit signed value into the file block.
Parameters
d Value to write.
Definition at line 81 of file file_writing.cpp.
References SaveUInt8().
Referenced by SaveCarEntry(), and ANIMBlock::Write().
void FileBlock::SaveUInt32 (uint32 d)
Save a 32 bit unsigned value into the file block.
Parameters
d Value to write.
Definition at line 91 of file file_writing.cpp.
References SaveUInt16().
Referenced by SaveCarEntry(), StartSave(), TSELBlock::Write(), TCORBlock::Write(), SURFBlock::Write(), FUNDBlock::Write(), PRSGBlock::Write(), ANSPBlock::Write(), PATHBlock::Write(), PDECBlock::Write(), PLATBlock::Write(), SUPPBlock::Write(), SHOPBlock::Write(), GBORBlock::Write(), GCHKBlock::Write(), GSLIBlock::Write(), GSCLBlock::Write(), BDIRBlock::Write(), GSLPBlock::Write(), TrackVoxel::Write(), TrackPieceNode::Write(), RCSTBlock::Write(), CARSBlock::Write(), CSPLBlock::Write(), and FENCBlock::Write().
void FileBlock::SaveBytes (uint8 * data, int size)
Save a sequence of bytes in the file block.
Parameters
data Start address of the data.
size Length of the data.
Definition at line 102 of file file_writing.cpp.
References SaveUInt8().
Referenced by StartSave(), SpriteBlock::Write(), TextNode::Write(), and INFOBlock::Write().
void FileBlock::CheckEndSave ()
Check that all data has been written.
Definition at line 112 of file file_writing.cpp.
References length, and save_index.
Referenced by SpriteBlock::Write(), TSELBlock::Write(), TCORBlock::Write(), SURFBlock::Write(), FUNDBlock::Write(), PRSGBlock::Write(), ANIMBlock::Write(), ANSPBlock::Write(), PATHBlock::Write(), PDECBlock::Write(), PLATBlock::Write(), SUPPBlock::Write(), StringBundle::Write(), SHOPBlock::Write(), GBORBlock::Write(), GCHKBlock::Write(), GSLIBlock::Write(), GSCLBlock::Write(), BDIRBlock::Write(), GSLPBlock::Write(), TrackPieceNode::Write(), RCSTBlock::Write(), CARSBlock::Write(), CSPLBlock::Write(), FENCBlock::Write(), and INFOBlock::Write().
void FileBlock::Write (FILE * fp)
Write the file block to the output.
Parameters
fp File handle to write to.
Definition at line 121 of file file_writing.cpp.
References data, and length.
The documentation for this class was generated from the following files:
file_writing.h
file_writing.cpp