FreeRCT: RideType Class Reference
RideType Class Reference abstract
Base class of ride types.
#include <ride_type.h>
Public Member Functions
RideType (RideTypeKind rtk)
Ride type base class constructor.
virtual bool CanMakeInstance () const
Are all resources available for building an instance of this type? For example, are all sprites available? Default implementation always allows building an instance.
virtual RideInstance * CreateInstance () const =0
Construct a ride instance of the ride type.
void SetupStrings (TextData *text, StringID base, StringID start, StringID end, StringID name, StringID desc)
Setup the the strings of the ride type.
StringID GetString (uint16 number) const
Get the string instance for the generic ride string of number.
StringID GetTypeName () const
Retrieve the string with the name of this type of ride.
StringID GetTypeDescription () const
Retrieve the string with the description of this type of ride.
virtual const ImageData * GetView (uint8 orientation) const =0
Get a display of the ride type for the purchase screen.
virtual const StringID * GetInstanceNames () const =0
Get the instance base names of rides.
Public Attributes
const RideTypeKind kind
Kind of ride type.
Money monthly_cost
Monthly costs for owning a ride.
Money monthly_open_cost
Monthly extra costs if the ride is opened.
ItemType item_type [NUMBER_ITEM_TYPES_SOLD]
Type of items being sold.
Money item_cost [NUMBER_ITEM_TYPES_SOLD]
Cost of the items on sale.
Recolouring recolours
Sprite recolour map.
Protected Attributes
TextData * text
Strings of the ride type.
StringID str_base
Base offset of the string in the ride type.
StringID str_start
First string in the ride type.
StringID str_end
One beyond the last string in the ride type.
StringID str_name
String with the name of the ride type.
StringID str_description
String with the description of the ride type.
Detailed Description
Base class of ride types.
Definition at line 69 of file ride_type.h.
Constructor & Destructor Documentation
RideType::RideType (RideTypeKind rtk)
Ride type base class constructor.
Parameters
rtk Kind of ride.
Definition at line 51 of file ride_type.cpp.
References item_cost, item_type, ITP_NOTHING, monthly_cost, monthly_open_cost, NUMBER_ITEM_TYPES_SOLD, and SetupStrings().
Member Function Documentation
bool RideType::CanMakeInstance () const virtual
Are all resources available for building an instance of this type? For example, are all sprites available? Default implementation always allows building an instance.
Returns
Whether an instance of the ride type can be created.
Reimplemented in CoasterType.
Definition at line 69 of file ride_type.cpp.
Referenced by RidesManager::GetFreeInstance().
RideInstance * RideType::CreateInstance () const pure virtual
Construct a ride instance of the ride type.
Returns
An ride of its own type.
Implemented in CoasterType, and ShopType.
Referenced by RidesManager::CreateInstance().
void RideType::SetupStrings (TextData * text, StringID base, StringID start, StringID end, StringID name, StringID desc)
Setup the the strings of the ride type.
Parameters
text Strings from the RCD file.
base Assigned base number for strings of this type.
start First generic string number of this type.
end One beyond the last generic string number of this type.
name String containing the name of this ride type.
desc String containing the description of this ride type.
Definition at line 103 of file ride_type.cpp.
References str_base, str_description, str_end, str_name, str_start, and text.
Referenced by ShopType::Load(), CoasterType::Load(), and RideType().
StringID RideType::GetString (uint16 number) const
Get the string instance for the generic ride string of number.
Parameters
number Generic ride string number to retrieve.
Returns
The instantiated string for this ride type.
Definition at line 136 of file ride_type.cpp.
References str_base, str_end, and str_start.
Referenced by RideSelectGui::DrawWidget(), RidesManager::NewInstanceAdded(), GuiWindow::TranslateStringNumber(), and RideSelectGui::UpdateWidgetSize().
StringID RideType::GetTypeName () const
Retrieve the string with the name of this type of ride.
Returns
The name of this ride type.
Definition at line 117 of file ride_type.cpp.
References str_name.
Referenced by RideSelectGui::DrawWidget(), and RideSelectGui::UpdateWidgetSize().
StringID RideType::GetTypeDescription () const
Retrieve the string with the description of this type of ride.
Returns
The description of this ride type.
Definition at line 126 of file ride_type.cpp.
References str_description.
Referenced by RideSelectGui::DrawWidget(), and RideSelectGui::UpdateWidgetSize().
const ImageData * RideType::GetView (uint8 orientation) const pure virtual
Get a display of the ride type for the purchase screen.
Parameters
orientation Orientation of the ride type. Many ride types have 4 view orientations, but some types may have only a view for orientation 0.
Returns
An image to display in the purchase window, or nullptr if the queried orientation has no view.
Implemented in CoasterType, and ShopType.
Referenced by RideSelectGui::DrawWidget(), and ShopInstance::GetSprites().
const StringID * RideType::GetInstanceNames () const pure virtual
Get the instance base names of rides.
Returns
Array of proposed names, terminated with STR_INVALID.
Implemented in CoasterType, and ShopType.
Referenced by RidesManager::NewInstanceAdded().
The documentation for this class was generated from the following files:
ride_type.h
ride_type.cpp