FreeRCT: StringsNode Class Reference
StringsNode Class Reference
Collection of strings.
#include <nodes.h>
Public Member Functions
void Add (const StringNode &node, const Position &pos)
Add a string to the collection of strings.
void SetKey (const std::string &key, const Position &pos)
Set the key of the strings collection.
std::string GetKey () const
Retrieve the key from the stored strings.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
std::list< StringNode > strings
Collected strings.
Private Attributes
std::string key
Key associated with the strings, if any.
Detailed Description
Collection of strings.
Definition at line 511 of file nodes.h.
Member Function Documentation
void StringsNode::Add (const StringNode & node, const Position & pos)
Add a string to the collection of strings.
Parameters
node String to add.
pos Position of the string node, for error reporting.
Definition at line 644 of file nodes.cpp.
References StringNode::key, key, StringNode::lang_index, StringNode::name, strings, StringNode::text_pos, and Position::ToString().
Referenced by ConvertStringsNode().
void StringsNode::SetKey (const std::string & key, const Position & pos)
Set the key of the strings collection.
Can only be done if it is not set already.
Parameters
key New key of the bundle that the collection belongs to.
pos Position of setting.
Definition at line 672 of file nodes.cpp.
References key, strings, and Position::ToString().
std::string StringsNode::GetKey () const
Retrieve the key from the stored strings.
Returns
Key of all strings that have one,if available, else "".
Todo:
This looks like it could be moved to this->key.
Definition at line 692 of file nodes.cpp.
References key, and strings.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp