FreeRCT: VoxelObject Class Reference
VoxelObject Class Reference abstract
Base class for (moving) objects that are stored at a voxel position for easy retrieval during drawing.
#include <map.h>
Public Member Functions
virtual const ImageData * GetSprite (const SpriteStorage *sprites, ViewOrientation orient, const Recolouring **recolour) const =0
Get the sprite to draw for the voxel object.
void AddSelf (Voxel *v)
Add itself to the voxel objects chain.
void RemoveSelf (Voxel *v)
Remove itself from the voxel objects chain.
void MarkDirty ()
Mark the voxel containing the voxel object as dirty, so it is repainted.
Public Attributes
VoxelObject * next_object
Next voxel object in the linked list.
VoxelObject * prev_object
Previous voxel object in the linked list.
bool added
Whether the voxel object has been added to a voxel.
int16 x_vox
Voxel index in X direction of the voxel object.
int16 y_vox
Voxel index in Y direction of the voxel object.
int16 z_vox
Voxel index in Z direction of the voxel object.
int16 x_pos
X position of the person inside the voxel (0..255).
int16 y_pos
Y position of the person inside the voxel (0..255).
int16 z_pos
Z position of the person inside the voxel (0..255).
Detailed Description
Base class for (moving) objects that are stored at a voxel position for easy retrieval during drawing.
Definition at line 309 of file map.h.
Member Function Documentation
const ImageData * VoxelObject::GetSprite (const SpriteStorage * sprites, ViewOrientation orient, const Recolouring ** recolour) const pure virtual
Get the sprite to draw for the voxel object.
Parameters
sprites Sprites at the right size for drawing.
orient Direction of view.
recolour [out] Recolour mapping if present, else nullptr.
Returns
Sprite to display for the voxel object.
Implemented in DisplayCoasterCar, and Person.
Referenced by SpriteCollector::CollectVoxel().
void VoxelObject::AddSelf (Voxel * v) inline
Add itself to the voxel objects chain.
Parameters
v Voxel containing the object.
Definition at line 323 of file map.h.
References added, next_object, prev_object, and Voxel::voxel_objects.
Referenced by Person::Activate(), Person::OnAnimate(), and DisplayCoasterCar::Set().
void VoxelObject::RemoveSelf (Voxel * v) inline
Remove itself from the voxel objects chain.
Parameters
v Voxel containing the object.
Definition at line 338 of file map.h.
References added, next_object, prev_object, and Voxel::voxel_objects.
Referenced by Person::DeActivate(), Person::OnAnimate(), and DisplayCoasterCar::Set().
void VoxelObject::MarkDirty ()
Mark the voxel containing the voxel object as dirty, so it is repainted.
Definition at line 143 of file map.cpp.
References MarkVoxelDirty(), x_vox, y_vox, and z_vox.
Referenced by Person::OnAnimate(), DisplayCoasterCar::PreRemove(), DisplayCoasterCar::Set(), and Person::StartAnimation().
The documentation for this class was generated from the following files:
map.h
map.cpp