FreeRCT: GSLPBlock Class Reference
GSLPBlock Class Reference
GSLP Game block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
std::shared_ptr< SpriteBlock > vert_down
Slope going vertically down.
std::shared_ptr< SpriteBlock > steep_down
Slope going steeply down.
std::shared_ptr< SpriteBlock > gentle_down
Slope going gently down.
std::shared_ptr< SpriteBlock > level
Level slope.
std::shared_ptr< SpriteBlock > gentle_up
Slope going gently up.
std::shared_ptr< SpriteBlock > steep_up
Slope going steeply up.
std::shared_ptr< SpriteBlock > vert_up
Slope going vertically up.
std::shared_ptr< SpriteBlock > wide_left
Wide bend to the left.
std::shared_ptr< SpriteBlock > normal_left
Normal bend to the left.
std::shared_ptr< SpriteBlock > tight_left
Tight bend to the left.
std::shared_ptr< SpriteBlock > no_bend
No bends.
std::shared_ptr< SpriteBlock > tight_right
Tight bend to the right.
std::shared_ptr< SpriteBlock > normal_right
Normal bend to the right.
std::shared_ptr< SpriteBlock > wide_right
Wide bend to the right.
std::shared_ptr< SpriteBlock > no_banking
No banking.
std::shared_ptr< SpriteBlock > bank_left
Bank to the left.
std::shared_ptr< SpriteBlock > bank_right
Bank to the right.
std::shared_ptr< SpriteBlock > triangle_right
Arrow triangle to the right.
std::shared_ptr< SpriteBlock > triangle_left
Arrow triangle to the left.
std::shared_ptr< SpriteBlock > triangle_up
Arrow triangle upwards.
std::shared_ptr< SpriteBlock > triangle_bottom
Arrow triangle downwards.
std::shared_ptr< SpriteBlock > has_platform
Select button for tracks with platforms.
std::shared_ptr< SpriteBlock > no_platform
Select button for tracks without platforms.
std::shared_ptr< SpriteBlock > has_power
Select button for powered tracks.
std::shared_ptr< SpriteBlock > no_power
Select button for unpowered tracks.
std::shared_ptr< SpriteBlock > disabled
Pattern to overlay over disabled buttons.
std::shared_ptr< SpriteBlock > compass [4]
Compass sprites denoting viewing directions.
std::shared_ptr< SpriteBlock > bulldozer
Bulldoze/delete.
std::shared_ptr< SpriteBlock > weather [5]
Weather sprites (sunny -> thunder).
std::shared_ptr< SpriteBlock > rog_lights [4]
Red/orange/green lights (red, orange, green, none).
std::shared_ptr< SpriteBlock > rg_lights [3]
Red/green lights (red, green, none).
std::shared_ptr< SpriteBlock > pos_2d
Flat rotation positive direction (counter clock wise)
std::shared_ptr< SpriteBlock > neg_2d
Flat rotation negative direction (clock wise)
std::shared_ptr< SpriteBlock > pos_3d
Diametric rotation positive direction (counter clock wise)
std::shared_ptr< SpriteBlock > neg_3d
Diametric rotation negative direction (clock wise)
std::shared_ptr< SpriteBlock > close_button
Close Button.
std::shared_ptr< SpriteBlock > maxi_button
Maximise button.
std::shared_ptr< SpriteBlock > mini_button
Minimise button.
std::shared_ptr< SpriteBlock > terraform_dot
Terraform dot.
std::shared_ptr< StringBundle > gui_text
Text of the GUIs (reference to a TEXT block).
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
GSLP Game block.
Definition at line 708 of file nodes.h.
Member Function Documentation
int GSLPBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 1097 of file nodes.cpp.
References FileWriter::AddBlock(), bank_left, bank_right, NamedBlock::blk_name, bulldozer, FileBlock::CheckEndSave(), close_button, compass, disabled, gentle_down, gentle_up, gui_text, has_platform, has_power, lengthof, level, neg_2d, neg_3d, no_banking, no_bend, no_platform, no_power, normal_left, normal_right, pos_2d, pos_3d, rg_lights, rog_lights, FileBlock::SaveUInt32(), FileBlock::StartSave(), steep_down, steep_up, terraform_dot, tight_left, tight_right, triangle_bottom, triangle_left, triangle_right, triangle_up, NamedBlock::version, vert_down, vert_up, weather, wide_left, and wide_right.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp