FreeRCT: BaseCursor Class Reference
BaseCursor Class Reference abstract
%Window code » %Viewport (main display) code and data
Base class of a viewport cursor.
#include <viewport.h>
Public Member Functions
BaseCursor (Viewport *vp)
Constructor of a cursor.
virtual void MarkDirty ()=0
Update the cursor at the screen.
virtual CursorType GetCursor (const XYZPoint16 &cursor_pos)=0
Get a cursor.
virtual uint8 GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos)=0
Get the maximum height of the xpos, ypos stack that needs to be examined.
void SetInvalid ()
Mark the cursor as being invalid, and update the viewport if necessary.
Public Attributes
Viewport * vp
Parent viewport object.
CursorType type
Type of cursor.
Detailed Description
Base class of a viewport cursor.
Definition at line 125 of file viewport.h.
Constructor & Destructor Documentation
BaseCursor::BaseCursor (Viewport * vp)
Constructor of a cursor.
Parameters
vp Viewport displaying the cursor.
Definition at line 472 of file viewport.cpp.
References CUR_TYPE_INVALID, type, and vp.
Member Function Documentation
virtual void BaseCursor::MarkDirty () pure virtual
Update the cursor at the screen.
Implemented in EdgeCursor, MultiCursor, and Cursor.
Referenced by SetInvalid().
virtual CursorType BaseCursor::GetCursor (const XYZPoint16 & cursor_pos) pure virtual
Get a cursor.
Parameters
cursor_pos Expected coordinate of the cursor.
Returns
The cursor sprite if the cursor exists and the coordinates are correct, else nullptr.
Implemented in EdgeCursor, MultiCursor, and Cursor.
virtual uint8 BaseCursor::GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos) pure virtual
Get the maximum height of the xpos, ypos stack that needs to be examined.
Parameters
xpos X position of the voxel.
ypos Y position of the voxel.
zpos Top of the stack found so far.
Returns
Highest voxel to draw for this cursor.
Implemented in EdgeCursor, MultiCursor, and Cursor.
void BaseCursor::SetInvalid ()
Mark the cursor as being invalid, and update the viewport if necessary.
Definition at line 483 of file viewport.cpp.
References CUR_TYPE_INVALID, MarkDirty(), and type.
Referenced by FenceBuildManager::LeaveMode(), TileTerraformMouseMode::LeaveMode(), TileTerraformMouseMode::SetCursors(), and PathBuildManager::UpdateState().
The documentation for this class was generated from the following files:
viewport.h
viewport.cpp