FreeRCT: TCORBlock Class Reference
TCORBlock Class Reference
A 'TCOR' block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int tile_width
Zoom-width of a tile of the surface.
int z_height
Change in Z height (in pixels) when going up or down a tile level.
std::array< std::shared_ptr
< SpriteBlock >, SURFACE_COUNT > north
Corner select tiles while viewing to north.
std::array< std::shared_ptr
< SpriteBlock >, SURFACE_COUNT > east
Corner select tiles while viewing to east.
std::array< std::shared_ptr
< SpriteBlock >, SURFACE_COUNT > south
Corner select tiles while viewing to south.
std::array< std::shared_ptr
< SpriteBlock >, SURFACE_COUNT > west
Corner select tiles while viewing to west.
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
A 'TCOR' block.
Definition at line 194 of file nodes.h.
Member Function Documentation
int TCORBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 411 of file nodes.cpp.
References FileWriter::AddBlock(), NamedBlock::blk_name, FileBlock::CheckEndSave(), FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), FileBlock::StartSave(), SURFACE_COUNT, tile_width, NamedBlock::version, and z_height.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp