FreeRCT: CoasterBuildStateOff Class Reference
CoasterBuildStateOff Class Reference
State when no coaster construction window is opened.
Public Member Functions
CoasterBuildStateOff (CoasterBuildMode &mode)
Constructor of the CoasterBuildStateOff state.
void OpenWindow (uint16 instance) const override
Notification to the mouse mode that a coaster construction window has been opened.
void CloseWindow (uint16 instance) const override
Notification to the mouse mode that a coaster construction window has been closed.
bool MayActivateMode () const override
Query from the viewport whether the mouse mode may be activated.
void ActivateMode (const Point16 &pos) const override
Notification from the viewport that the mouse mode has been activated.
void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) const override
Notification from the viewport that the mouse has moved.
void OnMouseButtonEvent (Viewport *vp, uint8 state) const override
Notification from the viewport that a mouse button has changed value.
void LeaveMode () const override
Notification from the viewport that the mouse mode has been de-activated.
bool EnableCursors () const override
Query from the viewport whether the mouse mode wants to have cursors displayed.
void ShowNoPiece (uint16 instance) const override
Notification from the construction window to display no track piece.
void SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction) const override
Notification from the construction window to display a track piece attached to the mouse cursor.
void DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, const XYZPoint16 &vox, TileEdge direction) const override
Notification from the construction window to display a track piece at a given position.
Public Attributes
CoasterBuildMode *const mode
Coaster build mouse mode.
Detailed Description
State when no coaster construction window is opened.
Definition at line 715 of file coaster_gui.cpp.
Constructor & Destructor Documentation
CoasterBuildStateOff::CoasterBuildStateOff (CoasterBuildMode & mode) inline
Constructor of the CoasterBuildStateOff state.
Parameters
mode Builder mode.
Definition at line 721 of file coaster_gui.cpp.
Member Function Documentation
void CoasterBuildStateOff::OpenWindow (uint16 instance) const inline override virtual
Notification to the mouse mode that a coaster construction window has been opened.
Parameters
instance Ride number of the window.
Implements CoasterBuildState.
Definition at line 725 of file coaster_gui.cpp.
References BS_STARTING, CoasterBuildMode::DisableDisplay(), CoasterBuildMode::instance, CoasterBuildState::mode, CoasterBuildMode::SetNoPiece(), and CoasterBuildMode::SetState().
void CoasterBuildStateOff::CloseWindow (uint16 instance) const inline override virtual
Notification to the mouse mode that a coaster construction window has been closed.
Parameters
instance Ride number of the window.
Implements CoasterBuildState.
Definition at line 733 of file coaster_gui.cpp.
bool CoasterBuildStateOff::MayActivateMode () const inline override virtual
Query from the viewport whether the mouse mode may be activated.
Returns
The mouse mode may be activated.
See also
MouseMode::MayActivateMode
Implements CoasterBuildState.
Definition at line 737 of file coaster_gui.cpp.
void CoasterBuildStateOff::ActivateMode (const Point16 & pos) const inline override virtual
Notification from the viewport that the mouse mode has been activated.
Parameters
pos Current mouse position.
See also
MouseMode::ActivateMode
Implements CoasterBuildState.
Definition at line 742 of file coaster_gui.cpp.
References NOT_REACHED.
void CoasterBuildStateOff::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) const inline override virtual
Notification from the viewport that the mouse has moved.
Parameters
vp The viewport.
old_pos Previous position of the mouse.
pos Current mouse position.
See also
MouseMode::OnMouseMoveEvent
Implements CoasterBuildState.
Definition at line 747 of file coaster_gui.cpp.
void CoasterBuildStateOff::OnMouseButtonEvent (Viewport * vp, uint8 state) const inline override virtual
Notification from the viewport that a mouse button has changed value.
Parameters
vp The viewport.
state Old and new state of the mouse buttons.
See also
MouseMode::OnMouseButtonEvent
Implements CoasterBuildState.
Definition at line 751 of file coaster_gui.cpp.
void CoasterBuildStateOff::LeaveMode () const inline override virtual
Notification from the viewport that the mouse mode has been de-activated.
See also
MouseMode::LeaveMode
Implements CoasterBuildState.
Definition at line 755 of file coaster_gui.cpp.
bool CoasterBuildStateOff::EnableCursors () const inline override virtual
Query from the viewport whether the mouse mode wants to have cursors displayed.
Returns
Cursors should be enabled.
See also
MouseMode::EnableCursors
Implements CoasterBuildState.
Definition at line 759 of file coaster_gui.cpp.
void CoasterBuildStateOff::ShowNoPiece (uint16 instance) const inline override virtual
Notification from the construction window to display no track piece.
Parameters
instance Ride number of the window.
Implements CoasterBuildState.
Definition at line 764 of file coaster_gui.cpp.
void CoasterBuildStateOff::SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction) const inline override virtual
Notification from the construction window to display a track piece attached to the mouse cursor.
Parameters
instance Ride number of the window.
piece Track piece to display.
direction Direction of building (to use with a cursor).
Implements CoasterBuildState.
Definition at line 768 of file coaster_gui.cpp.
void CoasterBuildStateOff::DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, const XYZPoint16 & vox, TileEdge direction) const inline override virtual
Notification from the construction window to display a track piece at a given position.
Parameters
instance Ride number of the window.
piece Track piece to display.
vox Position of the piece.
direction Direction of building (to use with a cursor).
Implements CoasterBuildState.
Definition at line 772 of file coaster_gui.cpp.
The documentation for this class was generated from the following file:
coaster_gui.cpp