FreeRCT: TrackPieceNode Class Reference
TrackPieceNode Class Reference
A 'track_piece' block.
#include <nodes.h>
Public Member Functions
void UpdateConnectionMap (std::map< std::string, int > *connections)
Verify that the connection names of the track voxel are present in the connections.
void Write (const std::map< std::string, int > &connections, FileWriter *fw, FileBlock *fb)
Write a TRCK game node for all 4 orientations.
void ComputeTrackLength (const Position &pos)
Compute the length of the track from the car_xpos, car_ypos, and car_zpos curves and setup CubicSpline::first and CubicSpline::last values.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int track_flags
Flags of the track piece.
int banking
Banking (0=no, 1=left, 2=right).
int slope
Slope of the track piece (-3 vertically down to 3 vertically up).
int bend
Bend of the track piece (-3 wide-left to 3 wide right).
int cost
Cost of the track piece.
int exit_dx
Relative X position of the exit voxel.
int exit_dy
Relative Y position of the exit voxel.
int exit_dz
Relative Z position of the exit voxel.
int speed
If non-0, minimal speed of cars (with direction).
std::shared_ptr< Connection > entry
Entry connection code.
std::shared_ptr< Connection > exit
Exit connection code.
std::list< std::shared_ptr
< TrackVoxel > > track_voxels
Voxels in the track piece.
std::shared_ptr< Curve > car_xpos
Path for cars over the track piece in X direction.
std::shared_ptr< Curve > car_ypos
Path for cars over the track piece in Y direction.
std::shared_ptr< Curve > car_zpos
Path for cars over the track piece in Z direction.
std::shared_ptr< Curve > car_pitch
Pitch of cars over the tracks, may be NULL.
std::shared_ptr< Curve > car_roll
Roll of cars over the tracks.
std::shared_ptr< Curve > car_yaw
Yaw of cars over the tracks, may be NULL.
int total_distance
Total distance of the piece.
Private Member Functions
void CheckBezierCount (int count, const Position &pos)
Check the number of bezier splines against expectations for all possible curves in the track piece, and report an error if the count is incorrect.
void CheckSplineStepCount (int index, int steps, const Position &pos)
Check whether the length of the curved splines is the same for the given index number.
void SetStartEnd (int index, bool set_start, int value)
Set the start or the end of a bezier spline in all track piece curves.
Detailed Description
A 'track_piece' block.
Definition at line 829 of file nodes.h.
Member Function Documentation
void TrackPieceNode::UpdateConnectionMap (std::map< std::string, int > * connections)
Verify that the connection names of the track voxel are present in the connections.
If not, add them.
Parameters
connections [inout] Map of connection names to their id.
Definition at line 1341 of file nodes.cpp.
References entry, and exit.
void TrackPieceNode::Write (const std::map< std::string, int > & connections, FileWriter * fw, FileBlock * parent_fb)
Write a TRCK game node for all 4 orientations.
Parameters
connections Map of connection names to their id.
fw Output stream to write the blocks to.
parent_fb Parent file block to write the game block numbers to.
Definition at line 1576 of file nodes.cpp.
References FileWriter::AddBlock(), banking, bend, car_pitch, car_roll, car_xpos, car_yaw, car_ypos, car_zpos, FileBlock::CheckEndSave(), cost, entry, exit, exit_dx, exit_dy, exit_dz, GetCarEntrySize(), RotateXY(), SaveCarEntry(), FileBlock::SaveInt8(), FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), FileBlock::SaveUInt8(), slope, speed, FileBlock::StartSave(), total_distance, track_flags, and track_voxels.
void TrackPieceNode::ComputeTrackLength (const Position & pos)
Compute the length of the track from the car_xpos, car_ypos, and car_zpos curves and setup CubicSpline::first and CubicSpline::last values.
Parameters
pos Position of the track piece in the source file.
Definition at line 1455 of file nodes.cpp.
References car_xpos, car_ypos, car_zpos, CheckBezierCount(), CheckSplineStepCount(), exit, SetStartEnd(), Position::ToString(), and total_distance.
void TrackPieceNode::CheckBezierCount (int count, const Position & pos) private
Check the number of bezier splines against expectations for all possible curves in the track piece, and report an error if the count is incorrect.
Parameters
count Expected number of bezier splines.
pos Position of the track piece in the source file.
Definition at line 1407 of file nodes.cpp.
References car_pitch, car_roll, car_xpos, car_yaw, car_ypos, and car_zpos.
Referenced by ComputeTrackLength().
void TrackPieceNode::CheckSplineStepCount (int index, int steps, const Position & pos) private
Check whether the length of the curved splines is the same for the given index number.
Parameters
index Index in the curve denoting the bezier spline to check.
steps Expected number of steps in the bezier spline.
pos Position of the track piece in the source file.
Definition at line 1441 of file nodes.cpp.
References car_pitch, car_roll, car_xpos, car_yaw, car_ypos, and car_zpos.
Referenced by ComputeTrackLength().
void TrackPieceNode::SetStartEnd (int index, bool set_start, int value) private
Set the start or the end of a bezier spline in all track piece curves.
Parameters
index Index in the curve denoting the bezier spline to change.
set_start If set, set the start, else set the end.
value Value to set.
Definition at line 1378 of file nodes.cpp.
References car_pitch, car_roll, car_xpos, car_yaw, car_ypos, and car_zpos.
Referenced by ComputeTrackLength().
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp