FreeRCT: BaseWidget Class Reference
BaseWidget Class Reference
Widgets and supporting functions of the program
Base class for all widgets.
#include <widget.h>
Public Member Functions
BaseWidget (WidgetType wtype)
Base class widget constructor.
virtual void SetupMinimalSize (GuiWindow *w, BaseWidget **wid_array)
Set up minimal size (min_x and min_y), fill step (fill_x and fill_y) and resize step (resize_x and resize_y) of the widget.
virtual void SetSmallestSizePosition (const Rectangle16 &rect)
Set the minimal size of the widget, and assign rect to the current position and size.
virtual void Draw (const GuiWindow *w)
Draw the widget.
virtual BaseWidget * GetWidgetByPosition (const Point16 &pt)
Get the widget at the given relative window position.
virtual void AutoRaiseButtons (const Point32 &base)
Raise all push buttons in the tree.
void MarkDirty (const Point32 &base) const
Denote the widget as being needed to redraw.
Public Attributes
WidgetType wtype
Widget type.
WidgetNumber number
Widget number.
uint16 smallest_x
Original horizontal size.
uint16 smallest_y
Original vertical size.
uint16 min_x
Minimal horizontal size.
uint16 min_y
Minimal vertical size.
Rectangle16 pos
Current position and size (relative to window top-left edge).
uint16 fill_x
Horizontal fill step.
uint16 fill_y
Vertical fill step.
uint16 resize_x
Horizontal resize step.
uint16 resize_y
Vertical resize step.
uint8 paddings [PAD_COUNT]
Padding.
Protected Member Functions
void SetWidget (BaseWidget **wid_array)
Add the widget to the widget array wid_array.
void InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert)
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
void InitMinimalSize (const BorderSpriteData *bsd, uint16 content_width, uint16 content_height)
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Detailed Description
Base class for all widgets.
Also implements WT_EMPTY.
Definition at line 76 of file widget.h.
Constructor & Destructor Documentation
BaseWidget::BaseWidget (WidgetType wtype)
Base class widget constructor.
Parameters
wtype Widget type.
Definition at line 34 of file widget.cpp.
References Rectangle< PT, SZ >::base, fill_x, fill_y, Rectangle< PT, SZ >::height, INVALID_WIDGET_INDEX, min_x, min_y, number, PAD_COUNT, paddings, pos, resize_x, resize_y, smallest_x, smallest_y, Rectangle< PT, SZ >::width, WT_CENTERED_TEXT, WT_HOR_SCROLLBAR, WT_LEFT_TEXT, WT_RIGHT_TEXT, WT_TEXT_BUTTON, WT_TEXT_PUSHBUTTON, WT_TITLEBAR, WT_VERT_SCROLLBAR, wtype, Point< CT >::x, and Point< CT >::y.
Member Function Documentation
void BaseWidget::SetupMinimalSize (GuiWindow * w, BaseWidget ** wid_array) virtual
Set up minimal size (min_x and min_y), fill step (fill_x and fill_y) and resize step (resize_x and resize_y) of the widget.
In addition, if the widget has a non-negative widget number, add the widget to the wid_array after verifying the position is still empty.
Parameters
w Window owning the widget.
wid_array [out] Array of widget pointers.
Reimplemented in IntermediateWidget, BackgroundWidget, ScrollbarWidget, DataWidget, and LeafWidget.
Definition at line 141 of file widget.cpp.
References fill_x, fill_y, GuiWindow::initialized, min_x, min_y, NOT_REACHED, number, resize_x, resize_y, SetWidget(), smallest_x, smallest_y, GuiWindow::UpdateWidgetSize(), WT_EMPTY, WT_RESIZEBOX, and wtype.
Referenced by GuiWindow::ResetSize(), BackgroundWidget::SetupMinimalSize(), and IntermediateWidget::SetupMinimalSize().
void BaseWidget::SetSmallestSizePosition (const Rectangle16 & rect) virtual
Set the minimal size of the widget, and assign rect to the current position and size.
Parameters
rect Smallest size, and suggested position of the (entire) widget.
Reimplemented in IntermediateWidget, and BackgroundWidget.
Definition at line 172 of file widget.cpp.
References Rectangle< PT, SZ >::height, min_x, min_y, pos, and Rectangle< PT, SZ >::width.
Referenced by GuiWindow::ResetSize(), BackgroundWidget::SetSmallestSizePosition(), and IntermediateWidget::SetSmallestSizePosition().
void BaseWidget::Draw (const GuiWindow * w) virtual
Draw the widget.
Parameters
w Window being drawn.
Reimplemented in IntermediateWidget, BackgroundWidget, ScrollbarWidget, DataWidget, and LeafWidget.
Definition at line 183 of file widget.cpp.
References GuiWindow::DrawWidget(), INVALID_WIDGET_INDEX, and number.
Referenced by BackgroundWidget::Draw(), IntermediateWidget::Draw(), and GuiWindow::OnDraw().
BaseWidget * BaseWidget::GetWidgetByPosition (const Point16 & pt) virtual
Get the widget at the given relative window position.
Parameters
pt Relative point.
Returns
The widget underneath the point, or nullptr.
Reimplemented in IntermediateWidget, and BackgroundWidget.
Definition at line 194 of file widget.cpp.
References Rectangle< PT, SZ >::IsPointInside(), and pos.
Referenced by BackgroundWidget::GetWidgetByPosition(), IntermediateWidget::GetWidgetByPosition(), and GuiWindow::OnMouseButtonEvent().
void BaseWidget::AutoRaiseButtons (const Point32 & base) virtual
Raise all push buttons in the tree.
Parameters
base Base position of the window.
Reimplemented in IntermediateWidget, BackgroundWidget, and LeafWidget.
Definition at line 204 of file widget.cpp.
Referenced by BackgroundWidget::AutoRaiseButtons(), IntermediateWidget::AutoRaiseButtons(), and GuiWindow::TimeoutCallback().
void BaseWidget::MarkDirty (const Point32 & base) const
Denote the widget as being needed to redraw.
Parameters
base Window base coordinate.
Definition at line 212 of file widget.cpp.
References _video, VideoSystem::MarkDisplayDirty(), Point< CT >::x, and Point< CT >::y.
Referenced by LeafWidget::AutoRaiseButtons(), GuiWindow::MarkWidgetDirty(), ScrollbarWidget::OnClick(), GuiWindow::OnMouseButtonEvent(), GuiWindow::SetWidgetChecked(), GuiWindow::SetWidgetPressed(), and GuiWindow::SetWidgetShaded().
void BaseWidget::SetWidget (BaseWidget ** wid_array) protected
Add the widget to the widget array wid_array.
Parameters
wid_array The widget array.
Definition at line 128 of file widget.cpp.
References number.
Referenced by SetupMinimalSize(), LeafWidget::SetupMinimalSize(), DataWidget::SetupMinimalSize(), ScrollbarWidget::SetupMinimalSize(), BackgroundWidget::SetupMinimalSize(), and IntermediateWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert) protected
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
Parameters
content_width Minimal width of the content.
content_height Minimal height of the content.
border_hor Horizontal border space.
border_vert Vertical border space.
Definition at line 97 of file widget.cpp.
References min_x, min_y, PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, and paddings.
Referenced by LeafWidget::SetupMinimalSize(), and DataWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (const BorderSpriteData * bsd, uint16 content_width, uint16 content_height) protected
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Parameters
bsd Used border sprites.
content_width Minimal width of the content.
content_height Minimal height of the content.
Definition at line 109 of file widget.cpp.
References BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, fill_x, fill_y, BorderSpriteData::hor_stepsize, LeastCommonMultiple(), BorderSpriteData::min_height, BorderSpriteData::min_width, resize_x, resize_y, and BorderSpriteData::vert_stepsize.
The documentation for this class was generated from the following files:
widget.h
widget.cpp