FreeRCT: CoasterTrain Class Reference
CoasterTrain Class Reference
A 'train' of coaster cars at a roller coaster.
#include <coaster.h>
Public Member Functions
void SetLength (int length)
Change the length of the train.
void OnAnimate (int delay)
Time has passed, update the position of the train.
Public Attributes
const CoasterInstance * coaster
Roller coaster owning the train.
std::vector< CoasterCar > cars
Cars in the train. 0 means the train is not used.
uint32 back_position
Position of the back-end of the train (in 1/256 pixels).
int32 speed
Amount of forward motion / millisecond, in 1/256 pixels.
const PositionedTrackPiece * cur_piece
Track piece that has the back-end position of the train.
Detailed Description
A 'train' of coaster cars at a roller coaster.
It consists of one or more cars, each of length car_type->length. Trains drive in increasing distance, until they hit the upper bound of the coaster length (CoasterInstance::coaster_length).
Definition at line 155 of file coaster.h.
Member Function Documentation
void CoasterTrain::SetLength (int length)
Change the length of the train.
Parameters
length New length of the train.
Definition at line 286 of file coaster.cpp.
References CoasterInstance::car_type, cars, coaster, and CoasterCar::PreRemove().
Referenced by CoasterInstance::SetNumberOfCars(), and CoasterInstance::SetNumberOfTrains().
void CoasterTrain::OnAnimate (int delay)
Time has passed, update the position of the train.
Parameters
delay Amount of time passed, in milliseconds.
Todo:
Air and rail friction
Definition at line 331 of file coaster.cpp.
References CoasterCar::back, back_position, PositionedTrackPiece::base_voxel, CarType::car_length, CoasterInstance::car_type, cars, coaster, CoasterInstance::coaster_length, cur_piece, PositionedTrackPiece::distance_base, CoasterCar::front, CarType::inter_car_length, PositionedTrackPiece::piece, CoasterInstance::pieces, DisplayCoasterCar::Set(), speed, Unroll(), XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by CoasterInstance::OnAnimate().
The documentation for this class was generated from the following files:
coaster.h
coaster.cpp