FreeRCT: WindowsDirectoryReader Class Reference
WindowsDirectoryReader Class Reference
File IO
Directory reader for a Windows system.
#include <fileio_windows.h>
Public Member Functions
void OpenPath (const char *path) override
Set up the directory reader object for reading a directory.
const char * NextEntry () override
Get next entry of the directory contents.
void ClosePath () override
Denote no further interest in reading the contents of the current directory.
const char * MakePath (const char *directory, const char *fname) override
Construct a path from a directory and a file name.
bool EntryIsFile () override
Test whether the last returned entry from NextEntry is a file.
bool EntryIsDirectory () override
Test whether the last returned entry from NextEntry is a directory.
const char * NextFile ()
Get the next file entry.
Public Attributes
const char dir_sep
Directory separator character.
Private Attributes
WIN32_FIND_DATA find_file_data
Current directory entry.
HANDLE hfind
Handle from FirstFindFile.
std::string dpath
Directory path.
char fpath [MAX_PATH]
File path returned by NextEntry.
Detailed Description
Directory reader for a Windows system.
Definition at line 24 of file fileio_windows.h.
Member Function Documentation
void WindowsDirectoryReader::OpenPath (const char * path) override virtual
Set up the directory reader object for reading a directory.
Parameters
path Path to the directory.
Note
Failure is not reported here, but NextEntry will not return anything useful.
Implements DirectoryReader.
Definition at line 35 of file fileio_windows.cpp.
References ClosePath(), dpath, find_file_data, and hfind.
const char * WindowsDirectoryReader::NextEntry () override virtual
Get next entry of the directory contents.
Returns
Pointer to name of next entry (as a file path suitable for opening a file). Returns nullptr if not next entry exists.
Note
The memory returned is owned by the DirectoryReader object, and should not be released.
Implements DirectoryReader.
Definition at line 43 of file fileio_windows.cpp.
References ClosePath(), dpath, find_file_data, hfind, and MakePath().
const char * WindowsDirectoryReader::MakePath (const char * directory, const char * fname) override virtual
Construct a path from a directory and a file name.
Parameters
directory Directory part of the path.
fname File name part of the path.
Returns
The combined path to the file.
Implements DirectoryReader.
Definition at line 55 of file fileio_windows.cpp.
References DirectoryReader::dir_sep, and fpath.
Referenced by NextEntry().
bool WindowsDirectoryReader::EntryIsFile () override virtual
Test whether the last returned entry from NextEntry is a file.
Returns
Whether the entry is a file.
Implements DirectoryReader.
Definition at line 70 of file fileio_windows.cpp.
References find_file_data.
bool WindowsDirectoryReader::EntryIsDirectory () override virtual
Test whether the last returned entry from NextEntry is a directory.
Returns
Whether the entry is a directory.
Implements DirectoryReader.
Definition at line 75 of file fileio_windows.cpp.
References find_file_data.
const char * DirectoryReader::NextFile () inherited
Get the next file entry.
Pulls entries from NextEntry, until the end is reached or until a file is returned.
Returns
Next file entry, if available.
Definition at line 88 of file fileio.cpp.
References DirectoryReader::EntryIsFile(), and DirectoryReader::NextEntry().
Referenced by RcdFileCollection::ScanDirectories().
The documentation for this class was generated from the following files:
fileio_windows.h
fileio_windows.cpp