FreeRCT: Guest Class Reference
Guest Class Reference
Guests walking around in the world.
#include <person.h>
Public Member Functions
void Activate (const Point16 &start, PersonType person_type) override
Mark this person as 'in use'.
void DeActivate (AnimateResult ar) override
Mark this person as 'not in use'.
AnimateResult OnAnimate (int delay) override
Update the animation of a person.
bool DailyUpdate () override
Daily ponderings of a guest.
void ChangeHappiness (int16 amount)
Update the happiness of the guest.
ItemType SelectItem (const RideInstance *ri)
Select an item to buy from the ride.
void BuyItem (RideInstance *ri)
Buy an item from the ride.
void NotifyRideDeletion (const RideInstance *ri)
Notify the guest of removal of a ride.
void ExitRide (RideInstance *ri, TileEdge entry)
Exit the ride, and continue walking in the park.
const ImageData * GetSprite (const SpriteStorage *sprites, ViewOrientation orient, const Recolouring **recolour) const override
Get the sprite to draw for the voxel object.
bool IsActive () const
Test whether this person is active in the game or not.
bool IsGuest () const
Test whether this person is a guest or not.
void SetName (const char *name)
Set the name of a guest.
const char * GetName () const
Query the name of the person.
void AddSelf (Voxel *v)
Add itself to the voxel objects chain.
void RemoveSelf (Voxel *v)
Remove itself from the voxel objects chain.
void MarkDirty ()
Mark the voxel containing the voxel object as dirty, so it is repainted.
Public Attributes
GuestActivity activity
Activity being done by the guest currently.
int16 happiness
Happiness of the guest (values are 0-100). Use ChangeHappiness to change the guest happiness.
uint16 total_happiness
Sum of all good experiences (for evaluating the day after getting home, values are 0-1000).
Money cash
Amount of money carried by the guest (should be non-negative).
RideInstance * ride
Ride that the guest wants to visit or is visiting nullptr there is no favorite ride.
bool has_map
Whether guest has a park map.
bool has_umbrella
Whether guest has an umbrella.
bool has_wrapper
Guest has a wrapper for the food or drink.
bool has_balloon
Guest has a balloon.
bool salty_food
The food in food is salty.
uint8 souvenirs
Number of souvenirs bought by the guest.
int8 food
Amount of food in the hand (one unit/day).
int8 drink
Amount of drink in the hand (one unit/day).
uint8 hunger_level
Amount of hunger (higher means more hunger).
uint8 thirst_level
Amount of thirst (higher means more thirst).
uint8 stomach_level
Amount of food/drink in the stomach.
uint8 waste
Amount of food/drink waste that should be disposed.
uint8 nausea
Amount of nausea of the guest.
uint16 id
Unique id of the person.
PersonType type
Type of person.
int16 offset
Offset with respect to centre of paths walked on (0..100).
const WalkInformation * walk
Walk animation sequence being performed.
const AnimationFrame * frames
Animation frames of the current animation.
uint16 frame_count
Number of frames in frames.
uint16 frame_index
Currently displayed frame of frames.
int16 frame_time
Remaining display time of this frame.
Recolouring recolour
Person recolouring.
VoxelObject * next_object
Next voxel object in the linked list.
VoxelObject * prev_object
Previous voxel object in the linked list.
bool added
Whether the voxel object has been added to a voxel.
XYZPoint16 vox_pos
Voxel position of the object.
XYZPoint16 pix_pos
Position of the object inside the voxel (0..255, but may be outside).
Protected Member Functions
void DecideMoveDirection () override
Decide where to go from the current position.
RideVisitDesire ComputeExitDesire (TileEdge current_edge, XYZPoint16 cur_pos, TileEdge exit_edge, bool *seen_wanted_ride)
Decide whether visiting the exit edge is useful.
uint8 GetExitDirections (const Voxel *v, TileEdge start_edge, bool *seen_wanted_ride, bool *queue_mode)
Which way can the guest leave?
RideVisitDesire WantToVisit (const RideInstance *ri) override
How much does the person desire to visit the given ride?
AnimateResult EdgeOfWorldOnAnimate () override
Handle the case of a guest reaching the end of the game world.
AnimateResult VisitRideOnAnimate (RideInstance *ri, TileEdge exit_edge) override
Handle guest ride visiting.
const WalkInformation * WalkForActivity (const WalkInformation **walks, uint8 walk_count, uint8 exits)
Find new walk based on activity.
RideVisitDesire NeedForItem (enum ItemType it, bool use_random)
How useful is the item for the guest?
void AddItem (ItemType it)
Add an item to the possessions of the guest.
TileEdge GetCurrentEdge () const
Decide at which edge the person is.
uint8 GetInparkDirections ()
Get the directions to neighboring tiles that lead to or stay in the park.
void StartAnimation (const WalkInformation *walk)
Perform the animation sequence as provided.
Protected Attributes
Random rnd
Random number generator for deciding how the person reacts.
char * name
Name of the person. nullptr means it has a default name (like "Guest XYZ").
Detailed Description
Guests walking around in the world.
Definition at line 166 of file person.h.
Member Function Documentation
void Guest::Activate (const Point16 & start, PersonType person_type) override virtual
Mark this person as 'in use'.
Parameters
start Start x/y voxel stack for entering the world.
person_type Type of person getting activated.
Reimplemented from Person.
Definition at line 1003 of file person.cpp.
References Person::Activate(), activity, cash, drink, food, GA_ENTER_PARK, happiness, has_balloon, has_map, has_umbrella, has_wrapper, hunger_level, nausea, ride, Person::rnd, salty_food, souvenirs, stomach_level, thirst_level, total_happiness, Random::Uniform(), and waste.
Referenced by Guests::OnNewDay().
void Guest::DeActivate (AnimateResult ar) override virtual
Mark this person as 'not in use'.
(Called by Guests.)
Parameters
ar How to de-activate the person.
Todo:
Evaluate Guest::total_happiness against scenario requirements for evaluating the park value.
Reimplemented from Person.
Definition at line 1028 of file person.cpp.
References _window_manager, Person::DeActivate(), WindowManager::DeleteWindow(), GetWindowByType(), Person::IsActive(), and WC_GUEST_INFO.
Referenced by Guests::DoTick(), and Guests::OnAnimate().
AnimateResult Guest::OnAnimate (int delay) override virtual
Update the animation of a person.
Parameters
delay Amount of milliseconds since the last update.
Returns
Whether to keep the person active or how to deactivate him/her.
Result code of the visit.
Reimplemented from Person.
Definition at line 1043 of file person.cpp.
References activity, GA_ON_RIDE, OAR_OK, and Person::OnAnimate().
Referenced by Guests::OnAnimate().
bool Guest::DailyUpdate () override virtual
Daily ponderings of a guest.
Returns
If false, de-activate the guest.
Todo:
Make going home a bit more random.
Implement dropping litter (Guest::has_wrapper) to the path, and also drop the wrapper when passing a non-empty litter bin.
Implement nausea (Guest::nausea).
Implement energy (for tiredness of guests).
Implements Person.
Definition at line 1104 of file person.cpp.
References _weather, activity, ChangeHappiness(), drink, food, GA_GO_HOME, GA_WANDER, Weather::GetWeatherType(), happiness, has_umbrella, has_wrapper, hunger_level, Person::IsGuest(), NOT_REACHED, Person::rnd, salty_food, stomach_level, Random::Success1024(), thirst_level, waste, WTP_LIGHT_CLOUDS, WTP_RAINING, WTP_SUNNY, WTP_THICK_CLOUDS, and WTP_THUNDERSTORM.
Referenced by Guests::DoTick().
void Guest::ChangeHappiness (int16 amount)
Update the happiness of the guest.
Parameters
amount Amount of change.
Definition at line 1086 of file person.cpp.
References CHG_DISPLAY_OLD, Clamp(), happiness, NotifyChange(), total_happiness, and WC_GUEST_INFO.
Referenced by BuyItem(), and DailyUpdate().
ItemType Guest::SelectItem (const RideInstance * ri)
Select an item to buy from the ride.
Parameters
ri Ride instance to buy from.
Returns
Item to buy, or ITP_NOTHING if there is nothing of interest.
Definition at line 1301 of file person.cpp.
References cash, RideInstance::GetSaleItemPrice(), RideInstance::GetSaleItemType(), ITP_NOTHING, NeedForItem(), NUMBER_ITEM_TYPES_SOLD, Person::rnd, RVD_NO_VISIT, and Random::Uniform().
Referenced by BuyItem(), and VisitRideOnAnimate().
void Guest::BuyItem (RideInstance * ri)
Buy an item from the ride.
Parameters
ri Ride being visited.
Definition at line 1330 of file person.cpp.
References AddItem(), cash, ChangeHappiness(), RideInstance::GetSaleItemPrice(), RideInstance::GetSaleItemType(), ITP_NOTHING, NUMBER_ITEM_TYPES_SOLD, SelectItem(), and RideInstance::SellItem().
Referenced by VisitRideOnAnimate().
void Guest::NotifyRideDeletion (const RideInstance * ri)
Notify the guest of removal of a ride.
Parameters
ri Ride being deleted.
Definition at line 424 of file person.cpp.
References activity, GA_ON_RIDE, GA_QUEUING, GA_WANDER, NOT_REACHED, and ride.
Referenced by Guests::NotifyRideDeletion().
void Guest::ExitRide (RideInstance * ri, TileEdge entry)
Exit the ride, and continue walking in the park.
Parameters
ri Ride to exit.
entry Entry direction of the ride.
Definition at line 448 of file person.cpp.
References _world, activity, VoxelObject::AddSelf(), DecideMoveDirection(), GA_ON_RIDE, GA_WANDER, VoxelWorld::GetCreateVoxel(), RideInstance::GetExit(), VoxelObject::pix_pos, ride, VoxelObject::vox_pos, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by ShopInstance::EnterRide(), ShopInstance::OnAnimate(), and ShopInstance::RemoveAllPeople().
RideVisitDesire Guest::ComputeExitDesire (TileEdge current_edge, XYZPoint16 cur_pos, TileEdge exit_edge, bool * seen_wanted_ride) protected
Decide whether visiting the exit edge is useful.
Parameters
current_edge Edge at the current position.
cur_pos Coordinate of the current voxel.
exit_edge Exit edge being examined.
seen_wanted_ride [inout] Whether the wanted ride is seen.
Returns
Desire of the guest to visit the indicated edge.
Definition at line 389 of file person.cpp.
References _tile_dxy, RideInstance::CanBeVisited(), PathExistsAtBottomEdge(), ride, RideExistsAtBottom(), RIS_OPEN, RVD_MAY_VISIT, RVD_MUST_VISIT, RVD_NO_RIDE, RVD_NO_VISIT, RideInstance::state, TravelQueuePath(), WantToVisit(), Point< CT >::x, and Point< CT >::y.
Referenced by GetExitDirections().
uint8 Guest::GetExitDirections (const Voxel * v, TileEdge start_edge, bool * seen_wanted_ride, bool * queue_path) protected
Which way can the guest leave?
Parameters
v Voxel to cross next for the guest.
start_edge Edge where the person is currently (entry edge of the voxel).
seen_wanted_ride [out] Whether the wanted ride was seen.
queue_path [out] Whether the quest is walking on a queue path (that may or may not lead to a ride).
Returns
Possible exit directions in low nibble, exits with a shop in high nibble.
Precondition
v must have a path.
Definition at line 471 of file person.cpp.
References _sprite_manager, ComputeExitDesire(), EDGE_BEGIN, EDGE_COUNT, GB(), Voxel::GetInstanceData(), GetPathExits(), SpriteManager::GetPathStatus(), GetPathType(), HasValidPath(), NOT_REACHED, PAS_QUEUE_PATH, RVD_MAY_VISIT, RVD_MUST_VISIT, RVD_NO_RIDE, RVD_NO_VISIT, SB(), and VoxelObject::vox_pos.
Referenced by DecideMoveDirection().
RideVisitDesire Guest::WantToVisit (const RideInstance * ri) override protected virtual
How much does the person desire to visit the given ride?
Parameters
ri Ride that can be visited.
Returns
Desire of the person to visit the ride.
Reimplemented from Person.
Definition at line 1224 of file person.cpp.
References RideInstance::GetSaleItemType(), NeedForItem(), NUMBER_ITEM_TYPES_SOLD, RVD_MAY_VISIT, and RVD_NO_VISIT.
Referenced by ComputeExitDesire().
AnimateResult Guest::EdgeOfWorldOnAnimate () override protected virtual
Handle the case of a guest reaching the end of the game world.
Returns
Result code of the visit.
Implements Person.
Definition at line 1049 of file person.cpp.
References _guests, activity, GA_GO_HOME, IsVoxelstackInsideWorld(), OAR_CONTINUE, OAR_DEACTIVATE, Guests::start_voxel, VoxelObject::vox_pos, Point< CT >::x, XYZPoint< CT >::x, and Point< CT >::y.
AnimateResult Guest::VisitRideOnAnimate (RideInstance * ri, TileEdge exit_edge) override protected virtual
Handle guest ride visiting.
Parameters
ri Ride that can be visited.
exit_edge Exit edge being examined.
Returns
Result code of the visit.
Implements Person.
Definition at line 1062 of file person.cpp.
References activity, BuyItem(), RideInstance::CanBeVisited(), RideInstance::EnterRide(), GA_ON_RIDE, GA_WANDER, ITP_NOTHING, OAR_CONTINUE, OAR_OK, RER_REFUSED, ride, and SelectItem().
const WalkInformation * Guest::WalkForActivity (const WalkInformation ** walks, uint8 walk_count, uint8 exits) protected
Find new walk based on activity.
Parameters
walks Possible walks.
walk_count Number of available walks.
exits Valid exits for the walk.
Returns
Walk info for the activity.
Definition at line 738 of file person.cpp.
References activity, GA_ENTER_PARK, GA_GO_HOME, GA_ON_RIDE, GetDesiredEdgeIndex(), GetGoHomeDirection(), GetParkEntryDirection(), NOT_REACHED, Person::rnd, Random::Uniform(), and VoxelObject::vox_pos.
Referenced by DecideMoveDirection().
RideVisitDesire Guest::NeedForItem (enum ItemType it, bool use_random) protected
How useful is the item for the guest?
Parameters
it Item offered.
use_random May use random to reject an item (else it should be accepted).
Returns
Desire of getting the item.
Todo:
Make warm food attractive on cold days.
Todo:
Add some form or age? (just a "is_child" boolean would suffice)
Definition at line 1173 of file person.cpp.
References _weather, activity, cash, drink, food, GA_ENTER_PARK, GA_GO_HOME, has_balloon, has_map, has_umbrella, hunger_level, ITP_BALLOON, ITP_DRINK, ITP_FIRST_AID, ITP_ICE_CREAM, ITP_MONEY, ITP_NORMAL_FOOD, ITP_NOTHING, ITP_PARK_MAP, ITP_SALTY_FOOD, ITP_SOUVENIR, ITP_TOILET, ITP_UMBRELLA, nausea, NOT_REACHED, Person::rnd, RVD_MAY_VISIT, RVD_MUST_VISIT, RVD_NO_VISIT, souvenirs, stomach_level, Random::Success1024(), Weather::temperature, thirst_level, and waste.
Referenced by SelectItem(), and WantToVisit().
void Guest::AddItem (ItemType it) protected
Add an item to the possessions of the guest.
Parameters
it Item to add.
Definition at line 1236 of file person.cpp.
References cash, drink, food, has_balloon, has_map, has_umbrella, has_wrapper, ITP_BALLOON, ITP_DRINK, ITP_FIRST_AID, ITP_ICE_CREAM, ITP_MONEY, ITP_NORMAL_FOOD, ITP_NOTHING, ITP_PARK_MAP, ITP_SALTY_FOOD, ITP_SOUVENIR, ITP_TOILET, ITP_UMBRELLA, nausea, NOT_REACHED, salty_food, souvenirs, and waste.
Referenced by BuyItem().
const ImageData * Person::GetSprite (const SpriteStorage * sprites, ViewOrientation orient, const Recolouring ** recolour) const override virtual inherited
Get the sprite to draw for the voxel object.
Parameters
sprites Sprites at the right size for drawing.
orient Direction of view.
recolour [out] Recolour mapping if present, else nullptr.
Returns
Sprite to display for the voxel object.
Implements VoxelObject.
Definition at line 108 of file person.cpp.
References WalkInformation::anim_type, Person::frame_index, SpriteStorage::GetAnimationSprite(), Person::recolour, Person::type, and Person::walk.
bool Person::IsActive () const inline inherited
Test whether this person is active in the game or not.
Returns
Whether the person is active in the game.
Definition at line 113 of file person.h.
References PERSON_INVALID, and Person::type.
Referenced by Person::Activate(), Guests::CountActiveGuests(), Person::DeActivate(), DeActivate(), Guests::DoTick(), Guests::FindNextFreeGuest(), Guests::NotifyRideDeletion(), and Guests::OnAnimate().
bool Person::IsGuest () const inline inherited
Test whether this person is a guest or not.
Returns
Whether the person is a guest.
Definition at line 122 of file person.h.
References PERSON_GUEST, and Person::type.
Referenced by DailyUpdate(), Person::GetName(), and Person::SetName().
void Person::SetName (const char * name) inherited
Set the name of a guest.
Parameters
name New name of the guest.
Note
Currently unused.
Definition at line 120 of file person.cpp.
References Person::IsGuest().
const char * Person::GetName () const inherited
Query the name of the person.
The name is returned in memory owned by the person. Do not free this data. It may change on each call.
Returns
Static buffer containing the name of the person.
Definition at line 134 of file person.cpp.
References Person::IsGuest(), and Person::name.
Referenced by GuestInfoWindow::SetWidgetStringParameters().
TileEdge Person::GetCurrentEdge () const protected inherited
Decide at which edge the person is.
Returns
Nearest edge of the person.
Definition at line 366 of file person.cpp.
References EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, VoxelObject::pix_pos, XYZPoint< CT >::x, and XYZPoint< CT >::y.
Referenced by DecideMoveDirection().
uint8 Person::GetInparkDirections () protected inherited
Get the directions to neighboring tiles that lead to or stay in the park.
Returns
Exits from the current tile that stay or lead into the park in the low nibble.
Definition at line 714 of file person.cpp.
References _tile_dxy, _world, EDGE_BEGIN, EDGE_COUNT, VoxelWorld::GetTileOwner(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), OWN_PARK, SB(), VoxelObject::vox_pos, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, and XYZPoint< CT >::y.
Referenced by DecideMoveDirection().
void Person::StartAnimation (const WalkInformation * walk) protected inherited
Perform the animation sequence as provided.
Parameters
walk Walk information describing the animations to perform.
Definition at line 772 of file person.cpp.
References _sprite_manager, WalkInformation::anim_type, AnimationFrame::duration, Person::frame_count, Animation::frame_count, Person::frame_index, Person::frame_time, Person::frames, Animation::frames, SpriteManager::GetAnimation(), VoxelObject::MarkDirty(), and Person::walk.
Referenced by DecideMoveDirection(), and Person::OnAnimate().
void VoxelObject::AddSelf (Voxel * v) inline inherited
Add itself to the voxel objects chain.
Parameters
v Voxel containing the object.
Definition at line 323 of file map.h.
References VoxelObject::added, VoxelObject::next_object, VoxelObject::prev_object, and Voxel::voxel_objects.
Referenced by Person::Activate(), ExitRide(), Person::OnAnimate(), and DisplayCoasterCar::Set().
void VoxelObject::RemoveSelf (Voxel * v) inline inherited
Remove itself from the voxel objects chain.
Parameters
v Voxel containing the object.
Definition at line 338 of file map.h.
References VoxelObject::added, VoxelObject::next_object, VoxelObject::prev_object, and Voxel::voxel_objects.
Referenced by Person::DeActivate(), Person::OnAnimate(), and DisplayCoasterCar::Set().
void VoxelObject::MarkDirty () inherited
Mark the voxel containing the voxel object as dirty, so it is repainted.
Definition at line 143 of file map.cpp.
References MarkVoxelDirty(), and VoxelObject::vox_pos.
Referenced by Person::OnAnimate(), DisplayCoasterCar::PreRemove(), DisplayCoasterCar::Set(), and Person::StartAnimation().
The documentation for this class was generated from the following files:
person.h
person.cpp