FreeRCT: VideoSystem Class Reference
VideoSystem Class Reference
Class representing the video system.
#include <video.h>
Public Member Functions
VideoSystem ()
Default constructor, does nothing, never goes wrong.
~VideoSystem ()
Destructor.
std::string Initialize (const char *font_name, int font_size)
Initialize the video system, preparing it for use.
bool SetResolution (const Point32 &res)
Change the resolution of the game window, including reinitialising some screen-size related data structures.
void GetResolutions ()
Gets the available default resolutions that are supported by the graphics driver.
void MainLoop ()
Main loop.
void Shutdown ()
Close down the video system.
uint16 GetXSize () const
Get horizontal size of the screen.
uint16 GetYSize () const
Get vertical size of the screen.
bool DisplayNeedsRepaint ()
Query whether the display needs to be repainted.
void MarkDisplayDirty ()
Mark the entire display as being out of date (it needs the be repainted).
void MarkDisplayDirty (const Rectangle32 &rect)
Mark the stated area of the screen as being out of date.
void SetClippedRectangle (const ClippedRectangle &cr)
Set the clipped area.
ClippedRectangle GetClippedRectangle ()
Get the current clipped blitting area.
void FillSurface (uint32 colour, const Rectangle32 &rect)
Fill the rectangle with a single colour.
void BlitImage (const Point32 &img_base, const ImageData *spr, const Recolouring &recolour, GradientShift shift)
Blit pixels from the spr relative to blit_rect into the area.
void BlitImage (int x, int y, const ImageData *img, const Recolouring &recolour, GradientShift shift)
Blit an image at the specified position (top-left position) relative to blit_rect.
void BlitHorizontal (int32 xmin, uint16 numx, int32 y, const ImageData *spr, const Recolouring &recolour)
Blit a row of sprites.
void BlitVertical (int32 ymin, uint16 numy, int32 x, const ImageData *spr, const Recolouring &recolour)
Blit a column of sprites.
void BlitImages (int32 x_base, int32 y_base, const ImageData *spr, uint16 numx, uint16 numy, const Recolouring &recolour, GradientShift shift=GS_NORMAL)
Blit pixels from the spr relative to img_base into the area.
void FinishRepaint ()
Finish repainting, perform the final steps.
int GetTextHeight () const
Get the height of a line of text.
void GetTextSize (const uint8 *text, int *width, int *height)
Get the text-size of a string.
void GetNumberRangeSize (int64 smallest, int64 biggest, int *width, int *height)
Get the text-size of a number between smallest and biggest.
void BlitText (const uint8 *text, uint32 colour, int xpos, int ypos, int width=0x7FFF, Alignment align=ALG_LEFT)
Blit text to the screen.
void DrawLine (const Point16 &start, const Point16 &end, uint32 colour)
Draw a line from start to end using the specified colour.
void DrawRectangle (const Rectangle32 &rect, uint32 colour)
Draw a rectangle at the screen.
Public Attributes
bool missing_sprites
Indicates that some sprites cannot be drawn.
std::set< Point32 > resolutions
Set (for automatic sorting) of available resolutions.
Private Member Functions
bool HandleEvent ()
Handle an input event.
void MarkDisplayClean ()
Mark the display as being up-to-date.
Private Attributes
int vid_width
Width of the application window.
int vid_height
Height of the application window.
int font_height
Height of a line of text in pixels.
bool initialized
Video system is initialized.
bool dirty
Video display needs being repainted.
TTF_Font * font
Opened text font.
SDL_Window * window
Window of the application.
SDL_Renderer * renderer
GPU renderer to the application window.
SDL_Texture * texture
GPU Texture storage of the application window.
uint32 * mem
Memory used for blitting the application display.
ClippedRectangle blit_rect
Rectangle to blit in.
Point16 digit_size
Size of largest digit (initially a zero-size).
Friends
class ClippedRectangle
Detailed Description
Class representing the video system.
Definition at line 56 of file video.h.
Constructor & Destructor Documentation
VideoSystem::VideoSystem ()
Default constructor, does nothing, never goes wrong.
Call Initialize to initialize the system.
Definition at line 132 of file video.cpp.
References initialized.
VideoSystem::~VideoSystem ()
Destructor.
Definition at line 138 of file video.cpp.
References initialized, and Shutdown().
Member Function Documentation
std::string VideoSystem::Initialize (const char * font_name, int font_size)
Initialize the video system, preparing it for use.
Parameters
font_name Name of the font file to load.
font_size Size of the font.
Returns
Error message if initialization failed, else an empty text.
Definition at line 149 of file video.cpp.
References _freerct_revision, _icon_data, digit_size, dirty, font, font_height, GetResolutions(), initialized, mem, missing_sprites, SetResolution(), window, Point< CT >::x, and Point< CT >::y.
Referenced by freerct_main().
bool VideoSystem::SetResolution (const Point32 & res)
Change the resolution of the game window, including reinitialising some screen-size related data structures.
Parameters
res Resolution to set the screen to.
Returns
True if resolution was changed.
Definition at line 229 of file video.cpp.
References _manager, blit_rect, GetViewport(), GetXSize(), initialized, MarkDisplayDirty(), mem, renderer, WindowManager::RepositionAllWindows(), Window::SetSize(), texture, vid_height, vid_width, window, Point< CT >::x, and Point< CT >::y.
Referenced by HandleEvent(), Initialize(), and SettingWindow::OnChange().
void VideoSystem::GetResolutions ()
Gets the available default resolutions that are supported by the graphics driver.
Definition at line 278 of file video.cpp.
References resolutions.
Referenced by Initialize().
void VideoSystem::MainLoop ()
Main loop.
Loops until told not to.
Definition at line 424 of file video.cpp.
References _finish, HandleEvent(), missing_sprites, OnNewFrame(), and ShowGraphicsErrorMessage().
Referenced by freerct_main().
void VideoSystem::Shutdown ()
Close down the video system.
Definition at line 455 of file video.cpp.
References dirty, font, initialized, and mem.
Referenced by freerct_main(), and ~VideoSystem().
uint16 VideoSystem::GetXSize () const inline
Get horizontal size of the screen.
Returns
Number of pixels of the screen horizontally.
Definition at line 73 of file video.h.
References initialized, and vid_width.
Referenced by FinishRepaint(), ComputeInitialPosition::IsScreenEmpty(), SettingWindow::OnClick(), QuitProgramWindow::OnInitialPosition(), OverlayShaded(), SetResolution(), SettingWindow::SetWidgetStringParameters(), BottomToolbarWindow::UpdateWidgetSize(), UpdateWindows(), ClippedRectangle::ValidateAddress(), and Viewport::Viewport().
uint16 VideoSystem::GetYSize () const inline
Get vertical size of the screen.
Returns
Number of pixels of the screen vertically.
Definition at line 83 of file video.h.
References initialized, and vid_height.
Referenced by ComputeInitialPosition::FindPosition(), ComputeInitialPosition::IsScreenEmpty(), SettingWindow::OnClick(), BottomToolbarWindow::OnInitialPosition(), QuitProgramWindow::OnInitialPosition(), OverlayShaded(), SettingWindow::SetWidgetStringParameters(), UpdateWindows(), and Viewport::Viewport().
bool VideoSystem::DisplayNeedsRepaint () inline
Query whether the display needs to be repainted.
Returns
Display needs an update.
Definition at line 93 of file video.h.
References dirty.
Referenced by UpdateWindows().
void VideoSystem::MarkDisplayDirty ()
Mark the entire display as being out of date (it needs the be repainted).
Definition at line 292 of file video.cpp.
References dirty.
Referenced by HandleEvent(), BaseWidget::MarkDirty(), Window::MarkDirty(), Viewport::MarkVoxelDirty(), RecolourDropdownWindow::OnClick(), WindowManager::ResetAllWindows(), and SetResolution().
void VideoSystem::MarkDisplayDirty (const Rectangle32 & rect)
Mark the stated area of the screen as being out of date.
Parameters
rect Rectangle which is out of date.
Todo:
Keep an administration of the rectangle(s??) to update, and update just that part.
Definition at line 302 of file video.cpp.
References dirty.
void VideoSystem::SetClippedRectangle (const ClippedRectangle & cr)
Set the clipped area.
Parameters
cr New clipped blitting area.
Definition at line 317 of file video.cpp.
References blit_rect.
Referenced by Viewport::OnDraw(), and OverlayShaded().
ClippedRectangle VideoSystem::GetClippedRectangle ()
Get the current clipped blitting area.
Returns
Current clipped area.
Definition at line 326 of file video.cpp.
References blit_rect, and ClippedRectangle::ValidateAddress().
Referenced by FillSurface(), Viewport::OnDraw(), and OverlayShaded().
void VideoSystem::FillSurface (uint32 colour, const Rectangle32 & rect)
Fill the rectangle with a single colour.
Parameters
colour Colour to fill with.
rect Rectangle to fill.
Definition at line 486 of file video.cpp.
References ClippedRectangle::address, Rectangle< PT, SZ >::base, Clamp(), GetClippedRectangle(), ClippedRectangle::height, Rectangle< PT, SZ >::height, ClippedRectangle::pitch, ClippedRectangle::width, Rectangle< PT, SZ >::width, Point< CT >::x, and Point< CT >::y.
Referenced by DropdownMenuWindow::DrawWidget(), Viewport::OnDraw(), and UpdateWindows().
void VideoSystem::BlitImage (const Point32 & img_base, const ImageData * spr, const Recolouring & recolour, GradientShift shift)
Blit pixels from the spr relative to blit_rect into the area.
Parameters
img_base Coordinate of the sprite data.
spr The sprite to blit.
recolour Sprite recolouring definition.
shift Gradient shift.
Definition at line 515 of file video.cpp.
References Point< CT >::x, and Point< CT >::y.
Referenced by LeafWidget::Draw(), DataWidget::Draw(), ScrollbarWidget::Draw(), DrawBorderSprites(), TerraformGui::DrawWidget(), FenceGui::DrawWidget(), PathBuildGui::DrawWidget(), RideSelectGui::DrawWidget(), BottomToolbarWindow::DrawWidget(), and Viewport::OnDraw().
void VideoSystem::BlitImage (int x, int y, const ImageData * img, const Recolouring & recolour, GradientShift shift)
Blit an image at the specified position (top-left position) relative to blit_rect.
Parameters
x Horizontal position.
y Vertical position.
img The sprite image data to blit.
recolour Sprite recolouring definition.
shift Gradient shift.
Definition at line 642 of file video.cpp.
References BlitImages().
void VideoSystem::BlitHorizontal (int32 xmin, uint16 numx, int32 y, const ImageData * spr, const Recolouring & recolour) inline
Blit a row of sprites.
Parameters
xmin Start X position.
numx Number of sprites to draw.
y Y position.
spr Sprite to draw.
recolour Sprite recolouring definition.
Definition at line 116 of file video.h.
References BlitImages().
Referenced by ScrollbarWidget::Draw(), and DrawBorderSprites().
void VideoSystem::BlitVertical (int32 ymin, uint16 numy, int32 x, const ImageData * spr, const Recolouring & recolour) inline
Blit a column of sprites.
Parameters
ymin Start Y position.
numy Number of sprites to draw.
x X position.
spr Sprite to draw.
recolour Sprite recolouring definition.
Definition at line 129 of file video.h.
References BlitImages().
Referenced by ScrollbarWidget::Draw(), and DrawBorderSprites().
void VideoSystem::BlitImages (int32 x_base, int32 y_base, const ImageData * spr, uint16 numx, uint16 numy, const Recolouring & recolour, GradientShift shift = GS_NORMAL)
Blit pixels from the spr relative to img_base into the area.
Parameters
x_base Base X coordinate of the sprite data.
y_base Base Y coordinate of the sprite data.
spr The sprite to blit.
numx Number of sprites to draw in horizontal direction.
numy Number of sprites to draw in vertical direction.
recolour Sprite recolouring definition.
shift Gradient shift.
Definition at line 825 of file video.cpp.
References Blit32bppImages(), Blit8bppImages(), blit_rect, ImageData::flags, GB(), Recolouring::GetPalette(), ImageData::height, IFG_IS_8BPP, ClippedRectangle::ValidateAddress(), ImageData::width, ImageData::xoffset, and ImageData::yoffset.
Referenced by BlitHorizontal(), BlitImage(), BlitVertical(), DrawBorderSprites(), and OverlayShaded().
void VideoSystem::FinishRepaint ()
Finish repainting, perform the final steps.
Todo:
Implement partial window repainting.
Definition at line 471 of file video.cpp.
References GetXSize(), MarkDisplayClean(), mem, renderer, and texture.
Referenced by UpdateWindows().
int VideoSystem::GetTextHeight () const inline
Get the height of a line of text.
Returns
Height of the font.
Definition at line 142 of file video.h.
References font_height.
Referenced by DrawMultilineString(), GetMultilineTextSize(), and GetTextHeight().
void VideoSystem::GetTextSize (const uint8 * text, int * width, int * height)
Get the text-size of a string.
Parameters
text Text to calculate.
width [out] Resulting width.
height [out] Resulting height.
Definition at line 858 of file video.cpp.
References font.
Referenced by GetMaxDateSize(), GetMoneyStringSize(), GetNumberRangeSize(), GetSingleLine(), GetTextSize(), and DropdownMenuWindow::SetDropdownSize().
void VideoSystem::GetNumberRangeSize (int64 smallest, int64 biggest, int * width, int * height)
Get the text-size of a number between smallest and biggest.
Parameters
smallest Smallest possible number to display.
biggest Biggest possible number to display.
width [out] Resulting width.
height [out] Resulting height.
Definition at line 873 of file video.cpp.
References digit_size, GetTextSize(), Point< CT >::x, and Point< CT >::y.
Referenced by ShopManagerWindow::UpdateWidgetSize().
void VideoSystem::BlitText (const uint8 * text, uint32 colour, int xpos, int ypos, int width = 0x7FFF, Alignment align = ALG_LEFT)
Blit text to the screen.
Parameters
text Text to display.
colour Colour of the text.
xpos Absolute horizontal position at the display.
ypos Absolute vertical position at the display.
width Available width of the text (in pixels).
align Horizontal alignment of the string.
Definition at line 913 of file video.cpp.
References ClippedRectangle::address, ALG_CENTER, ALG_LEFT, ALG_RIGHT, blit_rect, font, ClippedRectangle::height, NOT_REACHED, ClippedRectangle::pitch, ClippedRectangle::ValidateAddress(), and ClippedRectangle::width.
Referenced by DrawMultilineString(), DrawString(), and DropdownMenuWindow::DrawWidget().
void VideoSystem::DrawLine (const Point16 & start, const Point16 & end, uint32 colour)
Draw a line from start to end using the specified colour.
Parameters
start Starting point at the screen.
end End point at the screen.
colour Colour to use.
Definition at line 990 of file video.cpp.
References ClippedRectangle::address, blit_rect, ClippedRectangle::height, ClippedRectangle::pitch, ClippedRectangle::ValidateAddress(), ClippedRectangle::width, Point< CT >::x, and Point< CT >::y.
Referenced by DrawRectangle(), and TerraformGui::DrawWidget().
void VideoSystem::DrawRectangle (const Rectangle32 & rect, uint32 colour)
Draw a rectangle at the screen.
Parameters
rect Rectangle to draw.
colour Colour to use.
Definition at line 1044 of file video.cpp.
References Rectangle< PT, SZ >::base, DrawLine(), Rectangle< PT, SZ >::height, Rectangle< PT, SZ >::width, Point< CT >::x, and Point< CT >::y.
Referenced by GuiWindow::OnDraw().
bool VideoSystem::HandleEvent () private
Handle an input event.
Returns
Game-ending event has happened.
Definition at line 346 of file video.cpp.
References _manager, GetViewport(), MarkDisplayDirty(), MB_LEFT, MB_MIDDLE, MB_RIGHT, WindowManager::MouseButtonEvent(), WindowManager::MouseWheelEvent(), QuitProgram(), Viewport::Rotate(), SetResolution(), UpdateMousePosition(), and UpdateWindows().
Referenced by MainLoop().
void VideoSystem::MarkDisplayClean () private
Mark the display as being up-to-date.
Definition at line 308 of file video.cpp.
References dirty.
Referenced by FinishRepaint().
The documentation for this class was generated from the following files:
video.h
video.cpp