FreeRCT: CoasterType Class Reference
CoasterType Class Reference
Coaster ride type.
#include <coaster.h>
Public Member Functions
bool CanMakeInstance () const override
Are all resources available for building an instance of this type? For example, are all sprites available? Default implementation always allows building an instance.
RideInstance * CreateInstance () const override
Construct a ride instance of the ride type.
const ImageData * GetView (uint8 orientation) const override
Get a display of the ride type for the purchase screen.
const StringID * GetInstanceNames () const override
Get the instance base names of rides.
bool Load (RcdFileReader *rcd_file, const TextMap &texts, const TrackPiecesMap &piece_map)
Load a coaster type.
int GetTrackVoxelIndex (const TrackVoxel *tvx) const
Get the index of the provided track voxel for use as instance data.
void SetupStrings (TextData *text, StringID base, StringID start, StringID end, StringID name, StringID desc)
Setup the the strings of the ride type.
StringID GetString (uint16 number) const
Get the string instance for the generic ride string of number.
StringID GetTypeName () const
Retrieve the string with the name of this type of ride.
StringID GetTypeDescription () const
Retrieve the string with the description of this type of ride.
Public Attributes
uint16 coaster_kind
Kind of coaster.
uint8 platform_type
Type of platform.
uint8 max_number_trains
Maximum number of trains at a roller coaster.
uint8 max_number_cars
Maximum number of cars in a train.
std::vector< const TrackVoxel * > voxels
All voxels of all track pieces (do not free the track voxels, pieces owns this data).
std::vector< ConstTrackPiecePtr > pieces
Track pieces of the coaster.
const RideTypeKind kind
Kind of ride type.
Money monthly_cost
Monthly costs for owning a ride.
Money monthly_open_cost
Monthly extra costs if the ride is opened.
ItemType item_type [NUMBER_ITEM_TYPES_SOLD]
Type of items being sold.
Money item_cost [NUMBER_ITEM_TYPES_SOLD]
Cost of the items on sale.
Recolouring recolours
Sprite recolour map.
Protected Attributes
TextData * text
Strings of the ride type.
StringID str_base
Base offset of the string in the ride type.
StringID str_start
First string in the ride type.
StringID str_end
One beyond the last string in the ride type.
StringID str_name
String with the name of the ride type.
StringID str_description
String with the description of the ride type.
Private Member Functions
const CarType * GetDefaultCarType () const
Select the default car type for this type of coaster.
Detailed Description
Coaster ride type.
Definition at line 70 of file coaster.h.
Member Function Documentation
bool CoasterType::CanMakeInstance () const override virtual
Are all resources available for building an instance of this type? For example, are all sprites available? Default implementation always allows building an instance.
Returns
Whether an instance of the ride type can be created.
Reimplemented from RideType.
Definition at line 138 of file coaster.cpp.
References GetDefaultCarType().
RideInstance * CoasterType::CreateInstance () const override virtual
Construct a ride instance of the ride type.
Returns
An ride of its own type.
Implements RideType.
Definition at line 143 of file coaster.cpp.
References GetDefaultCarType().
const ImageData * CoasterType::GetView (uint8 orientation) const override virtual
Get a display of the ride type for the purchase screen.
Parameters
orientation Orientation of the ride type. Many ride types have 4 view orientations, but some types may have only a view for orientation 0.
Returns
An image to display in the purchase window, or nullptr if the queried orientation has no view.
Implements RideType.
Definition at line 151 of file coaster.cpp.
const StringID * CoasterType::GetInstanceNames () const override virtual
Get the instance base names of rides.
Returns
Array of proposed names, terminated with STR_INVALID.
Implements RideType.
Definition at line 156 of file coaster.cpp.
References STR_INVALID.
bool CoasterType::Load (RcdFileReader * rcd_file, const TextMap & texts, const TrackPiecesMap & piece_map)
Load a coaster type.
Parameters
rcd_file Data file being loaded.
texts Already loaded text blocks.
piece_map Already loaded track pieces.
Returns
Loading was successful.
Definition at line 93 of file coaster.cpp.
References _language, coaster_kind, CPT_COUNT, CST_COUNT, RcdFileReader::GetUInt16(), RcdFileReader::GetUInt32(), RcdFileReader::GetUInt8(), LoadTextFromFile(), max_number_cars, max_number_trains, pieces, platform_type, Language::RegisterStrings(), RideType::SetupStrings(), RcdFileReader::size, STR_GENERIC_COASTER_START, RcdFileReader::version, and voxels.
Referenced by SpriteManager::Load().
int CoasterType::GetTrackVoxelIndex (const TrackVoxel * tvx) const
Get the index of the provided track voxel for use as instance data.
Parameters
tvx Track voxel to look for.
Returns
Index of the provided track voxel in this coaster type.
See also
Voxel::SetInstanceData
Definition at line 168 of file coaster.cpp.
References voxels.
Referenced by CoasterInstance::PlaceTrackPieceInAdditions().
const CarType * CoasterType::GetDefaultCarType () const private
Select the default car type for this type of coaster.
Returns
The default car type, or nullptr is no car type is available.
Todo:
Make a proper CarType selection.
Definition at line 132 of file coaster.cpp.
Referenced by CanMakeInstance(), and CreateInstance().
void RideType::SetupStrings (TextData * text, StringID base, StringID start, StringID end, StringID name, StringID desc) inherited
Setup the the strings of the ride type.
Parameters
text Strings from the RCD file.
base Assigned base number for strings of this type.
start First generic string number of this type.
end One beyond the last generic string number of this type.
name String containing the name of this ride type.
desc String containing the description of this ride type.
Definition at line 103 of file ride_type.cpp.
References RideType::str_base, RideType::str_description, RideType::str_end, RideType::str_name, RideType::str_start, and RideType::text.
Referenced by ShopType::Load(), Load(), and RideType::RideType().
StringID RideType::GetString (uint16 number) const inherited
Get the string instance for the generic ride string of number.
Parameters
number Generic ride string number to retrieve.
Returns
The instantiated string for this ride type.
Definition at line 136 of file ride_type.cpp.
References RideType::str_base, RideType::str_end, and RideType::str_start.
Referenced by RideSelectGui::DrawWidget(), RidesManager::NewInstanceAdded(), GuiWindow::TranslateStringNumber(), and RideSelectGui::UpdateWidgetSize().
StringID RideType::GetTypeName () const inherited
Retrieve the string with the name of this type of ride.
Returns
The name of this ride type.
Definition at line 117 of file ride_type.cpp.
References RideType::str_name.
Referenced by RideSelectGui::DrawWidget(), and RideSelectGui::UpdateWidgetSize().
StringID RideType::GetTypeDescription () const inherited
Retrieve the string with the description of this type of ride.
Returns
The description of this ride type.
Definition at line 126 of file ride_type.cpp.
References RideType::str_description.
Referenced by RideSelectGui::DrawWidget(), and RideSelectGui::UpdateWidgetSize().
Member Data Documentation
uint16 CoasterType::coaster_kind
Kind of coaster.
See also
CoasterKind
Definition at line 83 of file coaster.h.
Referenced by Load().
uint8 CoasterType::platform_type
Type of platform.
See also
CoasterPlatformType
Definition at line 84 of file coaster.h.
Referenced by CoasterInstance::GetSprites(), and Load().
The documentation for this class was generated from the following files:
coaster.h
coaster.cpp