FreeRCT: WindowManager Class Reference
WindowManager Class Reference
%Window code
Window manager class, manages the window stack.
#include <window.h>
Public Member Functions
WindowManager ()
Window manager default constructor.
~WindowManager ()
Window manager destructor.
bool HasWindow (Window *w)
Test whether a particular window exists in the window stack.
void AddToStack (Window *w)
Add a window to the window stack.
void RemoveFromStack (Window *w)
Remove a window from the list.
void DeleteWindow (Window *w)
Delete a window.
void RaiseWindow (Window *w)
Raise a window.
void CloseAllWindows ()
Close all windows at the display.
void ResetAllWindows ()
Reinitialize all windows in the display.
void RepositionAllWindows ()
Moves relevant windows if they've been moved offscreen by a window resize.
void MouseMoveEvent (const Point16 &pos)
Mouse moved to new coordinates.
void MouseButtonEvent (MouseButtons button, bool pressed)
A mouse button was pressed or released.
void MouseWheelEvent (int direction)
The mouse wheel has been turned.
bool KeyEvent (WmKeyCode key_code, const uint8 *symbol)
Process input from the keyboard.
void Tick ()
A tick has passed, update whatever must be updated.
Point16 GetMousePosition () const
Return the current mouse position.
Public Attributes
Window * top
Top-most window in the window stack.
Window * bottom
Lowest window in the window stack.
Private Member Functions
Window * FindWindowByPosition (const Point16 &pos) const
Find the window that covers a given position of the display.
void UpdateCurrentWindow ()
Update the current_window variable.
void StartWindowMove ()
Initiate a window movement operation.
Private Attributes
Point16 mouse_pos
Last reported mouse position.
Window * current_window
'Current' window under the mouse.
uint8 mouse_state
Last reported mouse button state (lower 4 bits).
uint8 mouse_mode
Mouse mode of the window manager.
Point16 move_offset
Offset from the top-left of the current_window being moved in WMMM_MOVE_WINDOW mode to the mouse position.
Detailed Description
Window manager class, manages the window stack.
Definition at line 321 of file window.h.
Constructor & Destructor Documentation
WindowManager::WindowManager ()
Window manager default constructor.
Todo:
Move this to a separate InitWindowSystem?
Definition at line 635 of file window.cpp.
References bottom, current_window, mouse_mode, mouse_pos, mouse_state, top, WMMM_PASS_THROUGH, Point< CT >::x, and Point< CT >::y.
WindowManager::~WindowManager ()
Window manager destructor.
Definition at line 649 of file window.cpp.
Member Function Documentation
bool WindowManager::HasWindow (Window * w)
Test whether a particular window exists in the window stack.
Parameters
w Window to look for.
Returns
Window exists in the window stack.
Note
Mainly used for paranoia checking.
Definition at line 795 of file window.cpp.
References Window::lower, and top.
Referenced by AddToStack(), RemoveFromStack(), UpdateCurrentWindow(), and Window::~Window().
void WindowManager::AddToStack (Window * w)
Add a window to the window stack.
Parameters
w Window to add.
Definition at line 712 of file window.cpp.
References bottom, GetWindowZPriority(), HasWindow(), Window::higher, Window::lower, top, and Window::wtype.
Referenced by RaiseWindow(), and Window::Window().
void WindowManager::RemoveFromStack (Window * w)
Remove a window from the list.
Parameters
w Window to remove.
Definition at line 745 of file window.cpp.
References bottom, HasWindow(), Window::higher, Window::lower, and top.
Referenced by DeleteWindow(), and RaiseWindow().
void WindowManager::DeleteWindow (Window * w)
Delete a window.
Parameters
w Window to remove.
Definition at line 769 of file window.cpp.
References Window::MarkDirty(), and RemoveFromStack().
Referenced by CloseAllWindows(), Guest::DeActivate(), MouseButtonEvent(), DropdownMenuWindow::OnClick(), RecolourDropdownWindow::OnClick(), QuitProgramWindow::OnClick(), GuiWindow::ShowDropdownMenu(), ShowQuitProgram(), and GuiWindow::ShowRecolourDropdown().
void WindowManager::RaiseWindow (Window * w)
Raise a window.
Parameters
w Window to raise.
Definition at line 780 of file window.cpp.
References AddToStack(), GetWindowZPriority(), Window::higher, Window::MarkDirty(), RemoveFromStack(), top, and Window::wtype.
Referenced by HighlightWindowByType(), and MouseButtonEvent().
void WindowManager::CloseAllWindows ()
Close all windows at the display.
Definition at line 654 of file window.cpp.
References DeleteWindow(), and top.
Referenced by ShutdownGame().
void WindowManager::ResetAllWindows ()
Reinitialize all windows in the display.
Todo:
This call should preserve the window size as much as possible.
Definition at line 662 of file window.cpp.
References _video, Window::lower, VideoSystem::MarkDisplayDirty(), and top.
Referenced by SettingWindow::OnChange().
void WindowManager::RepositionAllWindows ()
Moves relevant windows if they've been moved offscreen by a window resize.
Also forces the bottom toolbar to be moved, as that will always be in the wrong position.
Definition at line 674 of file window.cpp.
References GetViewport(), Rectangle< PT, SZ >::IsPointInside(), Window::lower, Window::rect, top, WC_BOTTOM_TOOLBAR, and WC_MAINDISPLAY.
Referenced by VideoSystem::SetResolution().
void WindowManager::MouseMoveEvent (const Point16 & pos)
Mouse moved to new coordinates.
Parameters
pos New position of the mouse.
Definition at line 833 of file window.cpp.
References Rectangle< PT, SZ >::base, current_window, Window::MarkDirty(), MB_LEFT, mouse_mode, mouse_pos, mouse_state, NOT_REACHED, Window::OnMouseMoveEvent(), Window::rect, Window::SetPosition(), UpdateCurrentWindow(), WC_MAINDISPLAY, WMMM_MOVE_WINDOW, WMMM_PASS_THROUGH, Window::wtype, Point< CT >::x, and Point< CT >::y.
Referenced by UpdateMousePosition().
void WindowManager::MouseButtonEvent (MouseButtons button, bool pressed)
A mouse button was pressed or released.
Parameters
button The button that changed state.
pressed The button was pressed (false means it was released instead).
Definition at line 912 of file window.cpp.
References ALL_WINDOWS_OF_TYPE, current_window, DeleteWindow(), GetWindowByType(), Rectangle< PT, SZ >::IsPointInside(), MB_LEFT, MB_MIDDLE, MB_RIGHT, mouse_mode, mouse_state, NOT_REACHED, Window::OnMouseButtonEvent(), RaiseWindow(), Window::rect, StartWindowMove(), UpdateCurrentWindow(), WC_DROPDOWN, WMME_CLOSE_WINDOW, WMME_MOVE_WINDOW, WMME_NONE, WMMM_MOVE_WINDOW, and WMMM_PASS_THROUGH.
Referenced by VideoSystem::HandleEvent().
void WindowManager::MouseWheelEvent (int direction)
The mouse wheel has been turned.
Parameters
direction Direction of the turn (either +1 or -1).
Definition at line 974 of file window.cpp.
References current_window, Window::OnMouseWheelEvent(), and UpdateCurrentWindow().
Referenced by VideoSystem::HandleEvent().
bool WindowManager::KeyEvent (WmKeyCode key_code, const uint8 * symbol)
Process input from the keyboard.
Parameters
key_code Kind of input.
symbol Entered symbol, if key_code is WMKC_SYMBOL. Utf-8 encoded.
Returns
Key event has been processed.
Definition at line 986 of file window.cpp.
Referenced by HandleKeyInput().
void WindowManager::Tick ()
A tick has passed, update whatever must be updated.
Definition at line 1016 of file window.cpp.
References Window::lower, Window::timeout, Window::TimeoutCallback(), top, and UpdateWindows().
Referenced by OnNewFrame().
Point16 WindowManager::GetMousePosition () const
Return the current mouse position.
Returns
The last reported mouse position.
Definition at line 824 of file window.cpp.
References mouse_pos.
Referenced by GetDistanceToMouse(), and FenceGui::OnClick().
Window * WindowManager::FindWindowByPosition (const Point16 & pos) const private
Find the window that covers a given position of the display.
Parameters
pos Position of the display.
Returns
The window displayed at the given position, or nullptr if no window.
Definition at line 810 of file window.cpp.
References Rectangle< PT, SZ >::IsPointInside(), Window::lower, Window::rect, and top.
Referenced by UpdateCurrentWindow().
void WindowManager::UpdateCurrentWindow () private
Update the current_window variable.
This may happen when the mouse has moved, but also because of a change in the window stack.
Todo:
Hook a call to this function into the window stack changing code.
Definition at line 875 of file window.cpp.
References current_window, FindWindowByPosition(), HasWindow(), mouse_pos, Window::OnMouseEnterEvent(), and Window::OnMouseLeaveEvent().
Referenced by MouseButtonEvent(), MouseMoveEvent(), and MouseWheelEvent().
Member Data Documentation
uint8 WindowManager::mouse_mode private
Mouse mode of the window manager.
See also
WmMouseModes
Definition at line 356 of file window.h.
Referenced by MouseButtonEvent(), MouseMoveEvent(), StartWindowMove(), and WindowManager().
The documentation for this class was generated from the following files:
window.h
window.cpp