FreeRCT: ParameterizedName Class Reference
ParameterizedName Class Reference
Data about parameterized names (identifiers with {hor(min..max)} and {vert(min..max)} in them.
#include <utils.h>
Public Member Functions
HorVert DecodeName (const char *name, const Position &pos)
Inspect name, and return the information about the parameters.
const char * GetParmName (int row, int col)
Expand the parameterized name for a given row and column.
Static Public Member Functions
static bool HasNoParameters (const std::string &name)
Quick check to verify that a give name does not have parameters (that is, it is a normal single name).
Public Attributes
char * name
The copied name;.
char * variant
The name with filled-in values for it parameters;.
HorVert result
Decoding result.
ParameterizedNameRange hor_range
Information about the horizontal range.
ParameterizedNameRange vert_range
Information about the vertical range.
Detailed Description
Data about parameterized names (identifiers with {hor(min..max)} and {vert(min..max)} in them.
The format supports at most one horizontal and one vertical parameter.
Definition at line 43 of file utils.h.
Member Function Documentation
HorVert ParameterizedName::DecodeName (const char * name, const Position & pos)
Inspect name, and return the information about the parameters.
Parameters
name Name to inspect.
pos Position to report in case of a found error.
Returns
The found parameter ranges.
Definition at line 108 of file utils.cpp.
References AddHor(), AddVert(), hor_range, HV_NONE, ParameterizedNameRange::length, Position::line, ParameterizedNameRange::max_value, ParameterizedNameRange::min_value, name, ParameterizedNameRange::offset, ReadNumber(), result, ParameterizedNameRange::used, variant, and vert_range.
Referenced by AssignNames(), and NameTable::GetNameCount().
const char * ParameterizedName::GetParmName (int row, int col)
Expand the parameterized name for a given row and column.
Parameters
row Row number.
col Column number.
Returns
Reference to the expanded name for the given parameter values. Do not free!
Definition at line 176 of file utils.cpp.
References hor_range, ParameterizedNameRange::length, ParameterizedNameRange::min_value, name, ParameterizedNameRange::offset, ParameterizedNameRange::used, variant, and vert_range.
Referenced by AssignNames().
bool ParameterizedName::HasNoParameters (const std::string & name) static
Quick check to verify that a give name does not have parameters (that is, it is a normal single name).
Parameters
name Name to inspect.
Returns
Returns true if no parameters are found, else false.
Definition at line 52 of file utils.cpp.
Referenced by CheckIsSingleName(), and IdentifierLine::IsValid().
The documentation for this class was generated from the following files:
utils.h
utils.cpp