FreeRCT: NameTable Class Reference
NameTable Class Reference
A 2D table of identifiers.
#include <ast.h>
Public Member Functions
bool HasSingleElement () const
Test whether the name table is actually just a single (possibly parameterized) name.
const Position & GetPosition () const override
Get a position representing the name (group).
int GetNameCount () const override
Get the number of names attached to the 'name' part.
Public Attributes
std::list< std::shared_ptr
< NameRow > > rows
Rows of the table.
Detailed Description
A 2D table of identifiers.
Names here may be parameterized, and represent many identifiers.
Definition at line 174 of file ast.h.
Member Function Documentation
bool NameTable::HasSingleElement () const
Test whether the name table is actually just a single (possibly parameterized) name.
Returns
Whether the table consists of a single (possibly parameterized) name.
Definition at line 363 of file ast.cpp.
References rows.
Referenced by GetNameCount().
const Position & NameTable::GetPosition () const override virtual
Get a position representing the name (group).
Returns
Position pointing to the name part.
Implements Name.
Definition at line 370 of file ast.cpp.
References _dummy_position, Position::line, and rows.
int NameTable::GetNameCount () const override virtual
Get the number of names attached to the 'name' part.
Returns
The number of names in this Name.
Implements Name.
Definition at line 379 of file ast.cpp.
References ParameterizedName::DecodeName(), HasSingleElement(), HV_BOTH, HV_HOR, HV_NONE, HV_VERT, NOT_REACHED, and rows.
The documentation for this class was generated from the following files:
ast.h
ast.cpp