FreeRCT: Recolouring Class Reference
Recolouring Class Reference
Sprite recolouring information.
#include <palette.h>
Public Member Functions
Recolouring ()
Default constructor.
Recolouring (const Recolouring &sr)
Copy constructor.
Recolouring & operator= (const Recolouring &sr)
Assignment operator.
void Reset ()
Reset the recolouring, removing all recolour entries.
void Set (int index, const RecolourEntry &entry)
Copy a recolour entry into the recolouring.
void AssignRandomColours ()
Select random destination colour ranges for the recolour entries.
const uint8 * GetPalette (GradientShift shift) const
Compute the palette of the Recolouring object from the entries and the gradient shift.
const uint32 * GetRecolourTable (uint8 layer) const
Get the table with recolouring of a layer.
uint32 Encode () const
Encode a colour range remapping.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
RecolourEntry entries [MAX_RECOLOUR]
Recolour entries, (one for each layer in 32bpp).
uint8 orig
Colour range to replace.
uint32 replace
Bitset of colour ranges that may be used as replacement.
Private Member Functions
void InvalidateColourMap ()
Invalidate the colour map used last time.
ColourRange GetReplacementRange (ColourRange src) const
Find the coloure range to use as replacement for the src colour range.
Private Attributes
uint8 colour_map [256]
Colour map used last time.
GradientShift shift
Gradient shift used last time, GS_INVALID if the colour_map is not valid.
Detailed Description
Sprite recolouring information.
Colour range remapping definition.
All information of a sprite recolouring. The gradient colour shift is handled separately, as it changes often.
Definition at line 299 of file palette.h.
Constructor & Destructor Documentation
Recolouring::Recolouring ()
Default constructor.
Definition at line 98 of file palette.cpp.
References InvalidateColourMap(), and Reset().
Recolouring::Recolouring (const Recolouring & rc)
Copy constructor.
Parameters
rc Recolouring to use as template.
Definition at line 108 of file palette.cpp.
References endof, and entries.
Member Function Documentation
Recolouring & Recolouring::operator= (const Recolouring & rc)
Assignment operator.
Parameters
rc Recolouring to use as template.
Returns
The assigned value.
Definition at line 118 of file palette.cpp.
References endof, and entries.
void Recolouring::Reset ()
Reset the recolouring, removing all recolour entries.
Definition at line 127 of file palette.cpp.
References COL_RANGE_INVALID, entries, and MAX_RECOLOUR.
Referenced by LoadPRSG(), and Recolouring().
void Recolouring::Set (int index, const RecolourEntry & entry)
Copy a recolour entry into the recolouring.
Parameters
index Entry number to set.
entry Entry to copy.
Definition at line 137 of file palette.cpp.
References entries, InvalidateColourMap(), and MAX_RECOLOUR.
Referenced by LeafWidget::Draw(), ScrollbarWidget::Draw(), DrawBorderSprites(), ShopType::Load(), and LoadPRSG().
void Recolouring::AssignRandomColours ()
Select random destination colour ranges for the recolour entries.
Definition at line 145 of file palette.cpp.
References RecolourEntry::AssignDest(), COL_RANGE_INVALID, CountBits(), RecolourEntry::dest, RecolourEntry::dest_set, entries, GB(), lengthof, RecolourEntry::source, and Random::Uniform().
Referenced by PersonTypeGraphics::MakeRecolouring(), and RideInstance::RideInstance().
const uint8 * Recolouring::GetPalette (GradientShift shift) const
Compute the palette of the Recolouring object from the entries and the gradient shift.
Parameters
shift Applied gradient shift.
Returns
8bpp palette, including recolouring.
Definition at line 176 of file palette.cpp.
References Clamp(), COL_RANGE_COUNT, COL_SERIES_END, COL_SERIES_LENGTH, COL_SERIES_START, colour_map, GetColourRangeBase(), GetReplacementRange(), GS_NORMAL, and shift.
Referenced by VideoSystem::BlitImages(), and ImageData::GetPixel().
const uint32* Recolouring::GetRecolourTable (uint8 layer) const inline
Get the table with recolouring of a layer.
Parameters
layer Layer to recolour.
Returns
Table to use for recolouring.
Todo:
Implement recolour layer check in the 32bpp sprite loading, so it can be asserted here.
Definition at line 317 of file palette.h.
References _recolour_palettes, COL_RANGE_COUNT, RecolourEntry::dest, entries, and MAX_RECOLOUR.
Referenced by Blit32bppImages(), and ImageData::GetPixel().
void Recolouring::InvalidateColourMap () inline private
Invalidate the colour map used last time.
Definition at line 333 of file palette.h.
References GS_INVALID.
Referenced by Recolouring(), and Set().
ColourRange Recolouring::GetReplacementRange (ColourRange src) const private
Find the coloure range to use as replacement for the src colour range.
Parameters
src Colour range to replace.
Returns
Colour range to use instead of src (may be src again).
Definition at line 198 of file palette.cpp.
References COL_RANGE_INVALID, RecolourEntry::dest, entries, and MAX_RECOLOUR.
Referenced by GetPalette().
uint32 Recolouring::Encode () const
Encode a colour range remapping.
Returns
The encoded colour range remapping.
Definition at line 471 of file nodes.cpp.
References orig, and replace.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
Member Data Documentation
RecolourEntry Recolouring::entries[MAX_RECOLOUR]
Recolour entries, (one for each layer in 32bpp).
Don't assign directly, use Set instead.
Definition at line 329 of file palette.h.
Referenced by AssignRandomColours(), GetRecolourTable(), GetReplacementRange(), ShopManagerWindow::OnClick(), operator=(), Recolouring(), Reset(), Set(), and ShopManagerWindow::ShopManagerWindow().
The documentation for this class was generated from the following files:
palette.h
nodes.h
palette.cpp
nodes.cpp