FreeRCT: Image8bpp Class Reference
Image8bpp Class Reference
An 8bpp image.
#include <image.h>
Public Member Functions
Image8bpp (const ImageFile *imf, BitMaskData *mask)
Enable making an 8bpp sprite.
uint8 GetPixel (int x, int y) const
Get a pixel from the image.
virtual bool IsTransparent (int xpos, int ypos) const override
Return whether the pixel at the given coordinate is fully transparent.
virtual uint8 * Encode (int xpos, int ypos, int width, int height, int *size) const override
Encode an 8bpp sprite from (a part of) the image.
int GetWidth () const
Get the width of the image.
int GetHeight () const
Get the height of the image.
bool IsEmpty (int xpos, int ypos, int dx, int dy, int length) const
Is the queried set of pixels empty?
bool IsMaskedOut (int xpos, int ypos) const
If the pixel at the given coordinate masked away?
Public Attributes
const char * block_name
Name of the block to write.
const int block_version
Version number of the block to write.
Protected Attributes
const ImageFile * imf
Image file (not owned by the object).
int mask_xpos
X position of the left of the mask.
int mask_ypos
Y position of the top of the mask.
const MaskInformation * mask
Information about the used bitmask (or nullptr).
Detailed Description
An 8bpp image.
Definition at line 84 of file image.h.
Constructor & Destructor Documentation
Image8bpp::Image8bpp (const ImageFile * imf, BitMaskData * mask)
Enable making an 8bpp sprite.
Parameters
imf Image file to use.
mask Bitmask to apply, or nullptr.
Definition at line 302 of file image.cpp.
Member Function Documentation
uint8 Image8bpp::GetPixel (int x, int y) const
Get a pixel from the image.
Parameters
x Horizontal position.
y Vertical position.
Returns
Value of the pixel (palette index, as it is an 8bpp indexed image).
Definition at line 312 of file image.cpp.
References ImageFile::height, Image::imf, Image::IsMaskedOut(), ImageFile::row_pointers, TRANSPARENT_INDEX, and ImageFile::width.
Referenced by Encode(), Image32bpp::GetCurrentRecolour(), and IsTransparent().
bool Image8bpp::IsTransparent (int xpos, int ypos) const override virtual
Return whether the pixel at the given coordinate is fully transparent.
Parameters
xpos Horizontal position of the pixel.
ypos Vertical position of the pixel.
Returns
Whether the pixel at the given coordinate is fully transparent.
Implements Image.
Definition at line 321 of file image.cpp.
References GetPixel(), and TRANSPARENT_INDEX.
Referenced by Encode().
uint8 * Image8bpp::Encode (int xpos, int ypos, int width, int height, int * size) const override virtual
Encode an 8bpp sprite from (a part of) the image.
Parameters
xpos Left position of the sprite in the image.
ypos Top position of the sprite in the image.
width Width of the sprite.
height Height of the sprite.
size [out] Number of bytes needed to store the sprite.
Returns
Memory of length size holding the sprite data. An empty sprite is return as nullptr with size /c 0. A nullptr with a non-zero size indicates a memory error.
Implements Image.
Definition at line 326 of file image.cpp.
References GetPixel(), IsTransparent(), and WriteUInt32().
int Image::GetWidth () const inherited
Get the width of the image.
Returns
Width of the loaded image, or -1.
Definition at line 230 of file image.cpp.
References ImageFile::GetWidth(), and Image::imf.
Referenced by SpriteImage::CopySprite(), and Image32bpp::SetRecolourImage().
int Image::GetHeight () const inherited
Get the height of the image.
Returns
Height of the loaded image, or -1.
Definition at line 221 of file image.cpp.
References ImageFile::GetHeight(), and Image::imf.
Referenced by SpriteImage::CopySprite(), and Image32bpp::SetRecolourImage().
bool Image::IsEmpty (int xpos, int ypos, int dx, int dy, int length) const inherited
Is the queried set of pixels empty?
Parameters
xpos Horizontal start position.
ypos Vertical start position.
dx Horizontal stepping size.
dy Vertical stepping size.
length Number of pixels to examine.
Returns
All examined pixels are empty (have colour 0).
Definition at line 244 of file image.cpp.
References Image::IsTransparent().
Referenced by SpriteImage::CopySprite().
bool Image::IsMaskedOut (int x, int y) const inherited
If the pixel at the given coordinate masked away?
Parameters
x Horizontal position.
y Vertical position.
Returns
Whether the pixel at the given coordinate is masked away.
Definition at line 261 of file image.cpp.
References MaskInformation::data, Image::mask, Image::mask_xpos, Image::mask_ypos, and MaskInformation::width.
Referenced by GetPixel(), and Image32bpp::GetPixel().
The documentation for this class was generated from the following files:
image.h
image.cpp