FreeRCT: ShopPlacementManager Class Reference
ShopPlacementManager Class Reference
Class interacting between RideSelectGui, and the Viewport mouse mode MM_SHOP_PLACEMENT.
#include <shop_placement.h>
Public Member Functions
ShopPlacementManager ()
Constructor of the shop placement coordinator.
bool MayActivateMode () override
Query the mode whether it can be enabled.
void ActivateMode (const Point16 &pos) override
Activate the mouse mode.
void LeaveMode () override
Notification that the mouse mode is about to be disabled.
bool EnableCursors () override
Control display of cursors in the mouse mode.
void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) override
The mouse moved while in this mouse mode.
void OnMouseButtonEvent (Viewport *vp, uint8 state) override
A mouse click was detected.
void OpenWindow ()
The user opened the window.
void CloseWindow ()
The user closed the window.
bool SetSelection (int ride_type)
User has selected a ride (or -1 for selecting no ride).
void Rotated ()
The shop was rotated; recompute position if needed.
virtual void OnMouseWheelEvent (Viewport *vp, int direction)
A mouse wheelie event has been detected.
Public Attributes
ShopPlacementState state
Current state of the shop placement manager.
TileEdge orientation
Orientation of the shop that will be placed.
int selected_ride
Selected type of ride (negative means nothing selected).
uint16 instance
Allocated ride instance, is INVALID_RIDE_INSTANCE if not active.
Point16 mouse_pos
Stored mouse position.
const WindowTypes wtype
Type of window associated with this mouse mode.
const ViewportMouseMode mode
Mouse mode implemented by the object.
Private Member Functions
bool CanPlaceShop (const ShopType *selected_shop, int xpos, int ypos, int zpos)
Can a shop be placed at the given voxel?
RidePlacementResult ComputeShopVoxel (int32 xworld, int32 yworld, int32 zworld)
Decide at which voxel to place a shop.
void PlaceShop (const Point16 &pos)
Place the shop at the indicated mouse position (if possible), and update the state to SPS_BAD_POS or SPS_GOOD_POS.
Detailed Description
Class interacting between RideSelectGui, and the Viewport mouse mode MM_SHOP_PLACEMENT.
Todo:
[low] Other rides will handle construction from their own instance window, perhaps the shop should do that too?
Definition at line 38 of file shop_placement.h.
Constructor & Destructor Documentation
ShopPlacementManager::ShopPlacementManager ()
Constructor of the shop placement coordinator.
Definition at line 507 of file ride_gui.cpp.
References instance, INVALID_RIDE_INSTANCE, selected_ride, SPS_OFF, and state.
Member Function Documentation
bool ShopPlacementManager::MayActivateMode () override virtual
Query the mode whether it can be enabled.
Method may be called at any moment (or more often than once). Answering true does not mean the mouse mode will be activated.
Returns
Whether the mode may be enabled.
Implements MouseMode.
Definition at line 519 of file ride_gui.cpp.
References selected_ride, SPS_BAD_POS, SPS_GOOD_POS, SPS_OPENED, and state.
void ShopPlacementManager::ActivateMode (const Point16 & pos) override virtual
Activate the mouse mode.
Parameters
pos Last known mouse position.
Implements MouseMode.
Definition at line 526 of file ride_gui.cpp.
References EnableWorldAdditions(), mouse_pos, PlaceShop(), selected_ride, SPS_OFF, SPS_OPENED, and state.
void ShopPlacementManager::LeaveMode () override virtual
Notification that the mouse mode is about to be disabled.
Implements MouseMode.
Definition at line 541 of file ride_gui.cpp.
References _rides_manager, ALL_WINDOWS_OF_TYPE, CHG_MOUSE_MODE_LOST, RidesManager::DeleteInstance(), DisableWorldAdditions(), instance, INVALID_RIDE_INSTANCE, NotifyChange(), selected_ride, SPS_BAD_POS, SPS_GOOD_POS, SPS_OPENED, state, and WC_RIDE_SELECT.
bool ShopPlacementManager::EnableCursors () override virtual
Control display of cursors in the mouse mode.
Returns
true when cursors should be displayed, false otherwise.
Implements MouseMode.
Definition at line 514 of file ride_gui.cpp.
void ShopPlacementManager::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) override virtual
The mouse moved while in this mouse mode.
Parameters
vp Viewport object.
old_pos Previous position.
pos Current position.
Reimplemented from MouseMode.
Definition at line 558 of file ride_gui.cpp.
References mouse_pos, PlaceShop(), SPS_OFF, SPS_OPENED, and state.
void ShopPlacementManager::OnMouseButtonEvent (Viewport * vp, uint8 state) override virtual
A mouse click was detected.
Parameters
vp Viewport object.
state State of the mouse buttons.
See also
MouseButtons
Reimplemented from MouseMode.
Definition at line 566 of file ride_gui.cpp.
References _additions, _mouse_modes, _rides_manager, ALL_WINDOWS_OF_TYPE, CHG_MOUSE_MODE_LOST, WorldAdditions::Commit(), DisableWorldAdditions(), instance, INVALID_RIDE_INSTANCE, MB_LEFT, RidesManager::NewInstanceAdded(), NotifyChange(), selected_ride, MouseModes::SetViewportMousemode(), SPS_GOOD_POS, SPS_OPENED, state, and WC_RIDE_SELECT.
void ShopPlacementManager::OpenWindow ()
The user opened the window.
Definition at line 588 of file ride_gui.cpp.
References EDGE_SE, instance, INVALID_RIDE_INSTANCE, orientation, selected_ride, SPS_OFF, SPS_OPENED, and state.
void ShopPlacementManager::CloseWindow ()
The user closed the window.
Definition at line 599 of file ride_gui.cpp.
References _mouse_modes, _rides_manager, RidesManager::DeleteInstance(), instance, INVALID_RIDE_INSTANCE, selected_ride, MouseModes::SetViewportMousemode(), SPS_BAD_POS, SPS_GOOD_POS, SPS_OFF, SPS_OPENED, and state.
bool ShopPlacementManager::SetSelection (int ride_type)
User has selected a ride (or -1 for selecting no ride).
Parameters
ride_type Selected type of ride (-1 means selection is disabled).
Returns
New ride type has been set successfully.
Definition at line 622 of file ride_gui.cpp.
References _mouse_modes, _rides_manager, RidesManager::CreateInstance(), RidesManager::DeleteInstance(), DisableWorldAdditions(), RidesManager::GetFreeInstance(), RidesManager::GetRideType(), instance, INVALID_RIDE_INSTANCE, MouseMode::mode, mouse_pos, PlaceShop(), selected_ride, MouseModes::SetMouseMode(), MouseModes::SetViewportMousemode(), SPS_OFF, SPS_OPENED, and state.
Referenced by RideSelectGui::OnClick(), and RideSelectGui::SetNewRide().
void ShopPlacementManager::Rotated ()
The shop was rotated; recompute position if needed.
Definition at line 673 of file ride_gui.cpp.
References mouse_pos, PlaceShop(), SPS_OFF, SPS_OPENED, and state.
Referenced by RideSelectGui::OnClick().
bool ShopPlacementManager::CanPlaceShop (const ShopType * selected_shop, int xpos, int ypos, int zpos) private
Can a shop be placed at the given voxel?
Parameters
selected_shop Shop to place.
xpos X coordinate of the voxel.
ypos Y coordinate of the voxel.
zpos Z coordinate of the voxel.
Precondition
voxel coordinate must be valid in the world.
selected_shop may not be nullptr.
Returns
Shop can be placed at the given position.
Definition at line 375 of file ride_gui.cpp.
References _world, Voxel::CanPlaceInstance(), EDGE_BEGIN, EDGE_COUNT, ShopType::flags, Voxel::GetGroundSlope(), Voxel::GetGroundType(), Voxel::GetInstance(), VoxelWorld::GetTileOwner(), GetViewport(), VoxelWorld::GetVoxel(), GTP_INVALID, Viewport::orientation, OWN_PARK, PathExistsAtBottomEdge(), SL_FLAT, and SRI_FREE.
Referenced by ComputeShopVoxel().
RidePlacementResult ShopPlacementManager::ComputeShopVoxel (int32 xworld, int32 yworld, int32 zworld) private
Decide at which voxel to place a shop.
It should be placed at a voxel intersecting with the view line through the given point in the world.
Parameters
xworld X coordinate of the point.
yworld Y coordinate of the point.
zworld Z coordinate of the point.
Returns
Result of the placement process.
Definition at line 410 of file ride_gui.cpp.
References _rides_manager, _world, CanPlaceShop(), RideInstance::GetKind(), RidesManager::GetRideInstance(), ShopInstance::GetShopType(), GetViewport(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), instance, IsVoxelstackInsideWorld(), NOT_REACHED, ShopInstance::orientation, orientation, Viewport::orientation, RPR_CHANGED, RPR_FAIL, RPR_SAMEPOS, RTK_SHOP, ShopInstance::SetRide(), VOR_EAST, VOR_NORTH, VOR_SOUTH, VOR_WEST, WORLD_Z_SIZE, ShopInstance::xpos, ShopInstance::ypos, and ShopInstance::zpos.
Referenced by PlaceShop().
void ShopPlacementManager::PlaceShop (const Point16 & pos) private
Place the shop at the indicated mouse position (if possible), and update the state to SPS_BAD_POS or SPS_GOOD_POS.
Parameters
pos Mouse position.
Precondition
World additions should be ours to use, and have been enabled.
Todo:
Let the shop do this.
Definition at line 465 of file ride_gui.cpp.
References _additions, _rides_manager, AddRemovePathEdges(), WorldAdditions::Clear(), Viewport::ComputeHorizontalTranslation(), ComputeShopVoxel(), Viewport::EnsureAdditionsAreVisible(), WorldAdditions::GetCreateVoxel(), ShopInstance::GetEntranceDirections(), RideInstance::GetKind(), RidesManager::GetRideInstance(), GetViewport(), Rectangle< PT, SZ >::height, instance, WorldAdditions::MarkDirty(), NOT_REACHED, PAS_QUEUE_PATH, PATH_EMPTY, Window::rect, RPR_CHANGED, RPR_FAIL, RPR_SAMEPOS, RTK_SHOP, SPS_BAD_POS, SPS_GOOD_POS, SRI_FULL_RIDES, SRI_LAST, state, Rectangle< PT, SZ >::width, Point< CT >::x, ShopInstance::xpos, Point< CT >::y, ShopInstance::ypos, ShopInstance::zpos, and Viewport::zview.
Referenced by ActivateMode(), OnMouseMoveEvent(), Rotated(), and SetSelection().
void MouseMode::OnMouseWheelEvent (Viewport * vp, int direction) virtual inherited
A mouse wheelie event has been detected.
Parameters
vp Viewport object.
direction Direction of movement.
Reimplemented in TileTerraformMouseMode, and FenceBuildManager.
Definition at line 1655 of file viewport.cpp.
Referenced by Viewport::OnMouseWheelEvent().
The documentation for this class was generated from the following files:
shop_placement.h
ride_gui.cpp