FreeRCT: TrackPiece Class Reference
TrackPiece Class Reference
One track piece (type) of a roller coaster track.
#include <track_piece.h>
Public Member Functions
bool Load (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a track piece.
bool HasPower () const
Check whether the track piece is powered.
bool HasPlatform () const
Check whether the track piece has a platform associated with it.
bool IsStartingPiece () const
Can the track piece be used as the first piece of a roller coaster?
TileEdge GetStartDirection () const
Get the direction of the initial track piece.
TrackPieceBanking GetBanking () const
Get banking of the track piece.
TrackSlope GetSlope () const
Get the slope of the track piece.
TrackBend GetBend () const
Get the bend of the track piece.
Public Attributes
uint8 entry_connect
Entry connection code.
uint8 exit_connect
Exit connection code.
XYZPoint16 exit_dxyz
Relative position of the exit voxel.
int8 speed
If non-zero, the minimal speed of cars at the track.
uint16 track_flags
Flags of the track piece.
Money cost
Cost of this track piece.
std::vector< TrackVoxel * > track_voxels
Track voxels of this piece.
uint32 piece_length
Length of the track piece for the cars, in 1/256 pixel.
TrackCurve * car_xpos
X position of cars over this track piece.
TrackCurve * car_ypos
Y position of cars over this track piece.
TrackCurve * car_zpos
Z position of cars over this track piece.
TrackCurve * car_pitch
Pitch of cars over this track piece, may be nullptr.
TrackCurve * car_roll
Roll of cars over this track piece.
TrackCurve * car_yaw
Yaw of cars over this track piece, may be null.
Detailed Description
One track piece (type) of a roller coaster track.
Definition at line 162 of file track_piece.h.
Member Function Documentation
bool TrackPiece::Load (RcdFileReader * rcd_file, const ImageMap & sprites)
Load a track piece.
Parameters
rcd_file Data file being loaded.
sprites Already loaded sprite blocks.
Returns
Loading was successful.
Definition at line 189 of file track_piece.cpp.
References car_pitch, car_roll, car_xpos, car_yaw, car_ypos, car_zpos, cost, entry_connect, exit_connect, exit_dxyz, RcdFileReader::GetInt8(), RcdFileReader::GetUInt16(), RcdFileReader::GetUInt32(), RcdFileReader::GetUInt8(), LoadTrackCurve(), piece_length, RcdFileReader::size, speed, track_flags, track_voxels, RcdFileReader::version, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
bool TrackPiece::HasPower () const inline
Check whether the track piece is powered.
Returns
Whether the track piece enforces a non-zero speed.
Definition at line 189 of file track_piece.h.
bool TrackPiece::HasPlatform () const inline
Check whether the track piece has a platform associated with it.
Returns
Whether a platform is available.
Definition at line 198 of file track_piece.h.
bool TrackPiece::IsStartingPiece () const inline
Can the track piece be used as the first piece of a roller coaster?
Returns
Whether the track piece can be used as the first piece of a roller coaster.
Definition at line 207 of file track_piece.h.
References GB().
TileEdge TrackPiece::GetStartDirection () const inline
Get the direction of the initial track piece.
Should be used to match with the build arrow direction.
Returns
Direction of the initial track piece.
Precondition
IsStartingPiece() holds.
Definition at line 217 of file track_piece.h.
References GB().
TrackPieceBanking TrackPiece::GetBanking () const inline
Get banking of the track piece.
Returns
Banking of the track piece.
Definition at line 226 of file track_piece.h.
References GB(), and TPB_COUNT.
TrackSlope TrackPiece::GetSlope () const inline
Get the slope of the track piece.
Returns
the bend of the track piece.
Definition at line 237 of file track_piece.h.
References GB(), TSL_DOWN, TSL_FLAT, TSL_STEEP_DOWN, TSL_STEEP_UP, TSL_STRAIGHT_DOWN, TSL_STRAIGHT_UP, and TSL_UP.
TrackBend TrackPiece::GetBend () const inline
Get the bend of the track piece.
Returns
the bend of the track piece.
Definition at line 257 of file track_piece.h.
References GB().
The documentation for this class was generated from the following files:
track_piece.h
track_piece.cpp