FreeRCT: ShopType Class Reference
ShopType Class Reference
A 'ride' where you can buy food, drinks, and other stuff you need for a visit.
#include <shop_type.h>
Public Member Functions
bool Load (RcdFileReader *rcf_file, const ImageMap &sprites, const TextMap &texts)
Load a type of shop from the RCD file.
int GetRideCapacity () const
Compute the capacity of onride guests in the shop.
const ImageData * GetView (uint8 orientation) const override
Get a display of the ride type for the purchase screen.
const StringID * GetInstanceNames () const override
Get the instance base names of rides.
RideInstance * CreateInstance () const override
Construct a ride instance of the ride type.
virtual bool CanMakeInstance () const
Are all resources available for building an instance of this type? For example, are all sprites available? Default implementation always allows building an instance.
void SetupStrings (TextData *text, StringID base, StringID start, StringID end, StringID name, StringID desc)
Setup the the strings of the ride type.
StringID GetString (uint16 number) const
Get the string instance for the generic ride string of number.
StringID GetTypeName () const
Retrieve the string with the name of this type of ride.
StringID GetTypeDescription () const
Retrieve the string with the description of this type of ride.
Public Attributes
int8 height
Number of voxels used by this shop.
uint8 flags
Shop flags.
const RideTypeKind kind
Kind of ride type.
Money monthly_cost
Monthly costs for owning a ride.
Money monthly_open_cost
Monthly extra costs if the ride is opened.
ItemType item_type [NUMBER_ITEM_TYPES_SOLD]
Type of items being sold.
Money item_cost [NUMBER_ITEM_TYPES_SOLD]
Cost of the items on sale.
Recolouring recolours
Sprite recolour map.
Protected Attributes
ImageData * views [4]
64 pixel wide shop graphics.
TextData * text
Strings of the ride type.
StringID str_base
Base offset of the string in the ride type.
StringID str_start
First string in the ride type.
StringID str_end
One beyond the last string in the ride type.
StringID str_name
String with the name of the ride type.
StringID str_description
String with the description of the ride type.
Detailed Description
A 'ride' where you can buy food, drinks, and other stuff you need for a visit.
Todo:
Allow for other sized sprites + different recolours.
Definition at line 22 of file shop_type.h.
Member Function Documentation
bool ShopType::Load (RcdFileReader * rcd_file, const ImageMap & sprites, const TextMap & texts)
Load a type of shop from the RCD file.
Parameters
rcd_file Rcd file being loaded.
sprites Already loaded sprites.
texts Already loaded texts.
Returns
Loading was successful.
Todo:
Widths other than 64.
Definition at line 79 of file shop_type.cpp.
References _language, flags, RcdFileReader::GetInt32(), RcdFileReader::GetUInt16(), RcdFileReader::GetUInt32(), RcdFileReader::GetUInt8(), height, IsValidItemType(), RideType::item_cost, RideType::item_type, LoadSpriteFromFile(), LoadTextFromFile(), RideType::monthly_cost, RideType::monthly_open_cost, RideType::recolours, Language::RegisterStrings(), Recolouring::Set(), RideType::SetupStrings(), RcdFileReader::size, STR_GENERIC_SHOP_START, RcdFileReader::version, and views.
Referenced by SpriteManager::Load().
int ShopType::GetRideCapacity () const
Compute the capacity of onride guests in the shop.
Returns
Size of a batch in bits 0..7, and number of batches in bits 8..14. 0 means guests don't stay in the ride.
Definition at line 122 of file shop_type.cpp.
References CAPACITY_TOILET, RideType::item_type, ITP_TOILET, and NUMBER_ITEM_TYPES_SOLD.
Referenced by ShopInstance::ShopInstance().
const ImageData * ShopType::GetView (uint8 orientation) const override virtual
Get a display of the ride type for the purchase screen.
Parameters
orientation Orientation of the ride type. Many ride types have 4 view orientations, but some types may have only a view for orientation 0.
Returns
An image to display in the purchase window, or nullptr if the queried orientation has no view.
Implements RideType.
Definition at line 35 of file shop_type.cpp.
References views.
const StringID * ShopType::GetInstanceNames () const override virtual
Get the instance base names of rides.
Returns
Array of proposed names, terminated with STR_INVALID.
Implements RideType.
Definition at line 130 of file shop_type.cpp.
References STR_INVALID.
RideInstance * ShopType::CreateInstance () const override virtual
Construct a ride instance of the ride type.
Returns
An ride of its own type.
Implements RideType.
Definition at line 40 of file shop_type.cpp.
bool RideType::CanMakeInstance () const virtual inherited
Are all resources available for building an instance of this type? For example, are all sprites available? Default implementation always allows building an instance.
Returns
Whether an instance of the ride type can be created.
Reimplemented in CoasterType.
Definition at line 69 of file ride_type.cpp.
Referenced by RidesManager::GetFreeInstance().
void RideType::SetupStrings (TextData * text, StringID base, StringID start, StringID end, StringID name, StringID desc) inherited
Setup the the strings of the ride type.
Parameters
text Strings from the RCD file.
base Assigned base number for strings of this type.
start First generic string number of this type.
end One beyond the last generic string number of this type.
name String containing the name of this ride type.
desc String containing the description of this ride type.
Definition at line 103 of file ride_type.cpp.
References RideType::str_base, RideType::str_description, RideType::str_end, RideType::str_name, RideType::str_start, and RideType::text.
Referenced by Load(), CoasterType::Load(), and RideType::RideType().
StringID RideType::GetString (uint16 number) const inherited
Get the string instance for the generic ride string of number.
Parameters
number Generic ride string number to retrieve.
Returns
The instantiated string for this ride type.
Definition at line 136 of file ride_type.cpp.
References RideType::str_base, RideType::str_end, and RideType::str_start.
Referenced by RideSelectGui::DrawWidget(), RidesManager::NewInstanceAdded(), GuiWindow::TranslateStringNumber(), and RideSelectGui::UpdateWidgetSize().
StringID RideType::GetTypeName () const inherited
Retrieve the string with the name of this type of ride.
Returns
The name of this ride type.
Definition at line 117 of file ride_type.cpp.
References RideType::str_name.
Referenced by RideSelectGui::DrawWidget(), and RideSelectGui::UpdateWidgetSize().
StringID RideType::GetTypeDescription () const inherited
Retrieve the string with the description of this type of ride.
Returns
The description of this ride type.
Definition at line 126 of file ride_type.cpp.
References RideType::str_description.
Referenced by RideSelectGui::DrawWidget(), and RideSelectGui::UpdateWidgetSize().
Member Data Documentation
uint8 ShopType::flags
Shop flags.
See also
ShopFlags
Definition at line 35 of file shop_type.h.
Referenced by ShopPlacementManager::CanPlaceShop(), ShopInstance::GetEntranceDirections(), and Load().
The documentation for this class was generated from the following files:
shop_type.h
shop_type.cpp