FreeRCT: CarType Class Reference
CarType Class Reference
A type of car riding at a track.
#include <coaster.h>
Public Member Functions
bool Load (RcdFileReader *rcdfile, const ImageMap &sprites)
Load the data of a CARS block from file.
const ImageData * GetCar (int pitch, int roll, int yaw) const
Retrieve an image of the car at a given pitch, roll, and yaw orientation.
Public Attributes
ImageData * cars [4096]
Images of the car, in all possible orientation (if available).
uint16 tile_width
Tile width of the images.
uint16 z_height
Change in z-height of the images.
uint32 car_length
Length of a car in 1/256 pixel.
uint32 inter_car_length
Length between two car in 1/256 pixel.
uint16 num_passengers
Number of passenger of a car.
uint16 num_entrances
Number of entrance rows of a car.
Detailed Description
A type of car riding at a track.
Definition at line 40 of file coaster.h.
Member Function Documentation
bool CarType::Load (RcdFileReader * rcdfile, const ImageMap & sprites)
Load the data of a CARS block from file.
Parameters
rcdfile Data file being loaded.
sprites Already loaded sprites.
Returns
Loading was a success.
Definition at line 51 of file coaster.cpp.
References car_length, cars, RcdFileReader::GetUInt16(), RcdFileReader::GetUInt32(), inter_car_length, LoadSpriteFromFile(), num_entrances, num_passengers, RcdFileReader::size, tile_width, RcdFileReader::version, and z_height.
Referenced by SpriteManager::Load().
const ImageData* CarType::GetCar (int pitch, int roll, int yaw) const inline
Retrieve an image of the car at a given pitch, roll, and yaw orientation.
Parameters
pitch Required pitch of the car.
roll Required roll of the car.
yaw Required yaw of the car.
Returns
Image of the car in the requested orientation, if available.
Definition at line 53 of file coaster.h.
References cars.
Referenced by DisplayCoasterCar::GetSprite().
The documentation for this class was generated from the following files:
coaster.h
coaster.cpp