FreeRCT: SpriteManager Class Reference
SpriteManager Class Reference
Sprites and sprite handling
Storage and management of all sprites.
#include <sprite_store.h>
Public Member Functions
SpriteManager ()
Sprite manager constructor.
~SpriteManager ()
Sprite manager destructor.
void LoadRcdFiles ()
Load all useful RCD files found by _rcd_collection, into the program.
void AddBlock (RcdBlock *block)
Add a RCD data block to the list of managed blocks.
const SpriteStorage * GetSprites (uint16 size) const
Get a sprite store of a given size.
void AddAnimation (Animation *anim)
Add an animation to the sprite manager.
const ImageData * GetTableSprite (uint16 number) const
Get the image data for the GUI according to the table in table/gui_sprites.h.
const Rectangle16 & GetTableSpriteSize (uint16 number)
Get the size of a GUI image according to the table in table/gui_sprites.h.
const Animation * GetAnimation (AnimationType anim_type, PersonType per_type) const
Get the animation frames of the requested animation for the provided type of person.
const Fence * GetFence (FenceType fence) const
Get the fence rcd data for a given fence type.
PathStatus GetPathStatus (PathType path_type)
Get the status of a path type.
Protected Member Functions
const char * Load (const char *fname)
Load sprites from the disk.
SpriteStorage * GetSpriteStore (uint16 width)
Get the sprite storage belonging to a given size of sprites.
Protected Attributes
RcdBlock * blocks
List of loaded RCD data blocks.
SpriteStorage store
Sprite storage of size 64.
AnimationsMap animations
Available animations.
Private Member Functions
bool LoadSURF (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a surface game block from a RCD file.
bool LoadTSEL (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a tile selection block from a RCD file.
bool LoadTCOR (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a path sprites block from a RCD file.
bool LoadFUND (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a path sprites block from a RCD file.
bool LoadPATH (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a path sprites block from a RCD file.
bool LoadPDEC (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a path decoration sprites block from a RCD file.
bool LoadBDIR (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a displayed object block.
bool LoadPLAT (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a platform sprites block from a RCD file.
bool LoadSUPP (RcdFileReader *rcd_file, const ImageMap &sprites)
Load a support sprites block from a RCD file.
void SetSpriteSize (uint16 start, uint16 end, Rectangle16 &rect)
Set the size of the rectangle for fitting a range of sprites.
Detailed Description
Storage and management of all sprites.
Definition at line 612 of file sprite_store.h.
Constructor & Destructor Documentation
SpriteManager::SpriteManager ()
Sprite manager constructor.
Definition at line 1289 of file sprite_store.cpp.
References blocks, and GuiSprites::Clear().
SpriteManager::~SpriteManager ()
Sprite manager destructor.
Definition at line 1296 of file sprite_store.cpp.
References animations, blocks, GuiSprites::Clear(), and RcdBlock::next.
Member Function Documentation
void SpriteManager::LoadRcdFiles ()
Load all useful RCD files found by _rcd_collection, into the program.
Definition at line 1533 of file sprite_store.cpp.
References _rcd_collection, Load(), and RcdFileCollection::rcdfiles.
Referenced by freerct_main().
void SpriteManager::AddBlock (RcdBlock * block)
Add a RCD data block to the list of managed blocks.
Parameters
block New block to add.
Definition at line 1546 of file sprite_store.cpp.
References blocks, and RcdBlock::next.
Referenced by Load().
const SpriteStorage * SpriteManager::GetSprites (uint16 size) const
Get a sprite store of a given size.
Parameters
size Requested size.
Returns
Sprite store with sprites of the requested size, if it exists, else nullptr.
Todo:
Add support for other sprite sizes as well.
Definition at line 1558 of file sprite_store.cpp.
References store.
Referenced by Viewport::IsUndergroundModeAvailable(), FenceBuildManager::SetCursors(), and VoxelCollector::VoxelCollector().
void SpriteManager::AddAnimation (Animation * anim)
Add an animation to the sprite manager.
Parameters
anim Animation object to add.
Definition at line 1568 of file sprite_store.cpp.
References Animation::anim_type, and animations.
Referenced by Load().
const ImageData * SpriteManager::GetTableSprite (uint16 number) const
Get the image data for the GUI according to the table in table/gui_sprites.h.
Parameters
number Number of the sprite to get.
Returns
The sprite if available, else nullptr.
Todo:
Add lots of missing sprites.
Make this more efficient; linearly trying every entry scales badly.
Definition at line 1683 of file sprite_store.cpp.
References GuiSprites::bank_select, GuiSprites::bend_select, GuiSprites::bulldozer, GuiSprites::compass, SpriteStorage::GetArrowSprite(), GuiSprites::lights_rg, GuiSprites::lights_rog, GuiSprites::platform_select, GuiSprites::power_select, GuiSprites::rot_2d_neg, GuiSprites::rot_2d_pos, GuiSprites::rot_3d_neg, GuiSprites::rot_3d_pos, GuiSprites::slope_select, SPR_GUI_BANK_END, SPR_GUI_BANK_START, SPR_GUI_BEND_END, SPR_GUI_BEND_START, SPR_GUI_BUILDARROW_END, SPR_GUI_BUILDARROW_START, SPR_GUI_BULLDOZER, SPR_GUI_COMPASS_END, SPR_GUI_COMPASS_START, SPR_GUI_HAS_PLATFORM, SPR_GUI_HAS_POWER, SPR_GUI_NO_PLATFORM, SPR_GUI_NO_POWER, SPR_GUI_RG_LIGHTS_END, SPR_GUI_RG_LIGHTS_START, SPR_GUI_ROG_LIGHTS_END, SPR_GUI_ROG_LIGHTS_START, SPR_GUI_ROT2D_NEG, SPR_GUI_ROT2D_POS, SPR_GUI_ROT3D_NEG, SPR_GUI_ROT3D_POS, SPR_GUI_SLOPES_END, SPR_GUI_SLOPES_START, SPR_GUI_TRIANGLE_DOWN, SPR_GUI_TRIANGLE_LEFT, SPR_GUI_TRIANGLE_RIGHT, SPR_GUI_TRIANGLE_UP, SPR_GUI_WEATHER_END, SPR_GUI_WEATHER_START, store, GuiSprites::triangle_down, GuiSprites::triangle_left, GuiSprites::triangle_right, GuiSprites::triangle_up, VOR_NORTH, and GuiSprites::weather.
Referenced by DataWidget::Draw(), BottomToolbarWindow::DrawWidget(), GetTableSpriteSize(), and SetSpriteSize().
const Rectangle16 & SpriteManager::GetTableSpriteSize (uint16 number)
Get the size of a GUI image according to the table in table/gui_sprites.h.
Parameters
number Number of the sprite to get.
Returns
The size of the sprite (which may be a default if there is no sprite).
Note
Return value is kept until the next call.
Definition at line 1610 of file sprite_store.cpp.
References Rectangle< PT, SZ >::base, GetSpriteSize(), GetTableSprite(), ImageData::height, Rectangle< PT, SZ >::height, SetSpriteSize(), SPR_GUI_BANK_END, SPR_GUI_BANK_START, SPR_GUI_BEND_END, SPR_GUI_BEND_START, SPR_GUI_BUILDARROW_END, SPR_GUI_BUILDARROW_START, SPR_GUI_COMPASS_END, SPR_GUI_COMPASS_START, SPR_GUI_HAS_PLATFORM, SPR_GUI_HAS_POWER, SPR_GUI_NO_PLATFORM, SPR_GUI_NO_POWER, SPR_GUI_RG_LIGHTS_END, SPR_GUI_RG_LIGHTS_START, SPR_GUI_ROG_LIGHTS_END, SPR_GUI_ROG_LIGHTS_START, SPR_GUI_SLOPES_END, SPR_GUI_SLOPES_START, SPR_GUI_WEATHER_END, SPR_GUI_WEATHER_START, ImageData::width, Rectangle< PT, SZ >::width, Point< CT >::x, and Point< CT >::y.
Referenced by DataWidget::Draw(), DataWidget::SetupMinimalSize(), and BottomToolbarWindow::UpdateWidgetSize().
const Animation * SpriteManager::GetAnimation (AnimationType anim_type, PersonType per_type) const
Get the animation frames of the requested animation for the provided type of person.
Parameters
anim_type Animation to retrieve.
per_type Animation should feature this type of person.
Returns
The requested animation if it is available, else nullptr is returned.
Todo:
Put this in a static array to make rendering people much cheaper.
Definition at line 1722 of file sprite_store.cpp.
References Animation::anim_type, animations, and Animation::person_type.
Referenced by Person::StartAnimation().
const Fence * SpriteManager::GetFence (FenceType fence_type) const
Get the fence rcd data for a given fence type.
Parameters
fence_type The fence type (
See also
FenceType)
Returns
Fence object or nullptr
Definition at line 1737 of file sprite_store.cpp.
References SpriteStorage::fence, FENCE_TYPE_COUNT, and store.
Referenced by FenceGui::DrawWidget(), FenceGui::OnClick(), and FenceGui::UpdateWidgetSize().
PathStatus SpriteManager::GetPathStatus (PathType path_type)
Get the status of a path type.
Parameters
path_type Path type to query.
Returns
Status of the path type.
Definition at line 1748 of file sprite_store.cpp.
References SpriteStorage::path_sprites, Path::status, and store.
Referenced by BuildPathAtTile(), ExamineNeighbourPathEdge(), Guest::GetExitDirections(), and TravelQueuePath().
const char * SpriteManager::Load (const char * filename) protected
Load sprites from the disk.
Parameters
filename Name of the RCD file to load.
Returns
Error message if load failed, else nullptr.
Todo:
Try to re-use already loaded blocks.
Code will use last loaded surface as grass.
Definition at line 1315 of file sprite_store.cpp.
References _rides_manager, AddAnimation(), SpriteStorage::AddAnimationSprites(), AddBlock(), SpriteStorage::AddFence(), RidesManager::AddRideType(), ANIM_INVALID, Animation::anim_type, AnimationSprites::anim_type, RcdFileReader::CheckFileHeader(), GetNewCarType(), ShopType::Load(), CarType::Load(), TextData::Load(), CoasterType::Load(), Fence::Load(), Animation::Load(), AnimationSprites::Load(), LoadBDIR(), LoadCoasterPlatform(), LoadFUND(), GuiSprites::LoadGBOR(), GuiSprites::LoadGCHK(), GuiSprites::LoadGSCL(), GuiSprites::LoadGSLI(), GuiSprites::LoadGSLP(), LoadImage(), LoadPATH(), LoadPDEC(), LoadPLAT(), LoadPRSG(), LoadSUPP(), LoadSURF(), LoadTCOR(), LoadTSEL(), RcdFileReader::name, PERSON_INVALID, Animation::person_type, AnimationSprites::person_type, RcdFileReader::ReadBlockHeader(), SpriteStorage::RemoveAnimations(), RcdFileReader::size, RcdFileReader::SkipBytes(), store, and RcdFileReader::version.
Referenced by LoadRcdFiles().
SpriteStorage * SpriteManager::GetSpriteStore (uint16 width) protected
Get the sprite storage belonging to a given size of sprites.
Parameters
width Tile width of the sprites.
Returns
Sprite storage object for the given width if it exists, else nullptr.
Definition at line 1526 of file sprite_store.cpp.
References store.
Referenced by LoadBDIR(), LoadFUND(), LoadPATH(), LoadPDEC(), LoadPLAT(), LoadSUPP(), LoadSURF(), LoadTCOR(), and LoadTSEL().
bool SpriteManager::LoadSURF (RcdFileReader * rcd_file, const ImageMap & sprites) private
Load a surface game block from a RCD file.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Todo:
Remove height from RCD block.
Definition at line 312 of file sprite_store.cpp.
References GetSpriteStore(), RcdFileReader::GetUInt16(), GTP_COUNT, GTP_CURSOR_EDGE_TEST, GTP_CURSOR_TEST, GTP_DESERT, GTP_GRASS0, GTP_GRASS1, GTP_GRASS2, GTP_GRASS3, GTP_INVALID, GTP_UNDERGROUND, LoadSpriteFromFile(), NUM_SLOPE_SPRITES, RcdFileReader::size, SurfaceData::surface, SpriteStorage::surface, and RcdFileReader::version.
Referenced by Load().
bool SpriteManager::LoadTSEL (RcdFileReader * rcd_file, const ImageMap & sprites) private
Load a tile selection block from a RCD file.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Todo:
Remove height from RCD block.
Definition at line 346 of file sprite_store.cpp.
References GetSpriteStore(), RcdFileReader::GetUInt16(), LoadSpriteFromFile(), NUM_SLOPE_SPRITES, RcdFileReader::size, SurfaceData::surface, SpriteStorage::tile_select, and RcdFileReader::version.
Referenced by Load().
bool SpriteManager::LoadTCOR (RcdFileReader * rcd_file, const ImageMap & sprites) private
Load a path sprites block from a RCD file.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Todo:
Remove height from RCD block.
Definition at line 553 of file sprite_store.cpp.
References GetSpriteStore(), RcdFileReader::GetUInt16(), LoadSpriteFromFile(), NUM_SLOPE_SPRITES, RcdFileReader::size, TileCorners::sprites, SpriteStorage::tile_corners, RcdFileReader::version, and VOR_NUM_ORIENT.
Referenced by Load().
bool SpriteManager::LoadFUND (RcdFileReader * rcd_file, const ImageMap & sprites) private
Load a path sprites block from a RCD file.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Todo:
Remove height from RCD block.
Definition at line 582 of file sprite_store.cpp.
References FDT_BRICK, FDT_COUNT, FDT_GROUND, FDT_INVALID, FDT_WOOD, SpriteStorage::foundation, GetSpriteStore(), RcdFileReader::GetUInt16(), lengthof, LoadSpriteFromFile(), RcdFileReader::size, Foundation::sprites, and RcdFileReader::version.
Referenced by Load().
bool SpriteManager::LoadPATH (RcdFileReader * rcd_file, const ImageMap & sprites) private
Load a path sprites block from a RCD file.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Todo:
Remove height from RCD block.
Definition at line 405 of file sprite_store.cpp.
References GetSpriteStore(), RcdFileReader::GetUInt16(), LoadSpriteFromFile(), PAS_NORMAL_PATH, PAS_QUEUE_PATH, PAT_ASPHALT, PAT_CONCRETE, PAT_INVALID, PAT_TILED, PAT_WOOD, PATH_COUNT, SpriteStorage::path_sprites, RcdFileReader::size, Path::sprites, Path::status, and RcdFileReader::version.
Referenced by Load().
bool SpriteManager::LoadPDEC (RcdFileReader * rcd_file, const ImageMap & sprites) private
Load a path decoration sprites block from a RCD file.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Definition at line 470 of file sprite_store.cpp.
References PathDecoration::bench, PathDecoration::demolished_bench, PathDecoration::demolished_bin, PathDecoration::demolished_lamp, EDGE_BEGIN, EDGE_COUNT, PathDecoration::flat_litter, PathDecoration::flat_litter_count, PathDecoration::flat_vomit, PathDecoration::flat_vomit_count, GetSpriteStore(), RcdFileReader::GetUInt16(), PathDecoration::lamp_post, PathDecoration::litterbin, LoadSpriteFromFile(), PathDecoration::overflow_bin, SpriteStorage::path_decoration, PathDecoration::ramp_litter, PathDecoration::ramp_litter_count, PathDecoration::ramp_vomit, PathDecoration::ramp_vomit_count, RcdFileReader::size, and RcdFileReader::version.
Referenced by Load().
bool SpriteManager::LoadBDIR (RcdFileReader * rcd_file, const ImageMap & sprites) private
Load a displayed object block.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Definition at line 683 of file sprite_store.cpp.
References SpriteStorage::build_arrows, GetSpriteStore(), RcdFileReader::GetUInt16(), lengthof, LoadSpriteFromFile(), RcdFileReader::size, DisplayedObject::sprites, and RcdFileReader::version.
Referenced by Load().
bool SpriteManager::LoadPLAT (RcdFileReader * rcd_file, const ImageMap & sprites) private
Load a platform sprites block from a RCD file.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Todo:
Remove height from RCD block.
Definition at line 617 of file sprite_store.cpp.
References Platform::flat, GetSpriteStore(), RcdFileReader::GetUInt16(), Platform::left_ramp, lengthof, LoadSpriteFromFile(), SpriteStorage::platform, Platform::ramp, Platform::right_ramp, RcdFileReader::size, and RcdFileReader::version.
Referenced by Load().
bool SpriteManager::LoadSUPP (RcdFileReader * rcd_file, const ImageMap & sprites) private
Load a support sprites block from a RCD file.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Todo:
Remove height from RCD block.
Definition at line 654 of file sprite_store.cpp.
References GetSpriteStore(), RcdFileReader::GetUInt16(), lengthof, LoadSpriteFromFile(), RcdFileReader::size, Support::sprites, SSP_COUNT, SpriteStorage::support, and RcdFileReader::version.
Referenced by Load().
void SpriteManager::SetSpriteSize (uint16 first, uint16 end, Rectangle16 & rect) private
Set the size of the rectangle for fitting a range of sprites.
Parameters
first First sprite number to fit.
end One beyond the last sprite number to fit.
rect [out] Size of the rectangle required for fitting all sprites.
Definition at line 1595 of file sprite_store.cpp.
References GetSpriteSize(), GetTableSprite(), ImageData::height, Rectangle< PT, SZ >::MergeArea(), and ImageData::width.
Referenced by GetTableSpriteSize().
The documentation for this class was generated from the following files:
sprite_store.h
sprite_store.cpp