FreeRCT: ConfigFile Class Reference
ConfigFile Class Reference
File IO
A configuration file.
#include <config_reader.h>
Public Member Functions
void Clear ()
Clean the config file.
bool Load (const char *fname)
Load a config file.
bool LoadFromDirectoryList (const char **dir_list, const char *fname)
Try to find the configuration file from the list of directories, and load it if found.
const ConfigSection * GetSection (const char *name) const
Get a section from the configuration file.
const char * GetValue (const char *sect_name, const char *key) const
Get an item value from the configuration file.
int GetNum (const char *sect_name, const char *key) const
Get a number from the configuration file.
Public Attributes
ConfigSectionList sections
Sections of the configuration file.
Detailed Description
A configuration file.
Definition at line 63 of file config_reader.h.
Member Function Documentation
void ConfigFile::Clear ()
Clean the config file.
Definition at line 95 of file config_reader.cpp.
References sections.
Referenced by Load().
bool ConfigFile::Load (const char * fname)
Load a config file.
Parameters
fname Filename to load.
Returns
Loading succeeded.
Todo:
[easy] Eliminate duplicate config sections.
[easy] Strip whitespace around section names.
Definition at line 159 of file config_reader.cpp.
References Clear(), IsSpace(), ConfigSection::items, lengthof, line, sections, and StripWhitespace().
Referenced by freerct_main(), and LoadFromDirectoryList().
bool ConfigFile::LoadFromDirectoryList (const char ** dir_list, const char * fname)
Try to find the configuration file from the list of directories, and load it if found.
Parameters
dir_list nullptr terminated list of directories to try.
fname Filename to look for.
Returns
Loading succeeded.
Definition at line 140 of file config_reader.cpp.
References Load(), and PathIsFile().
const ConfigSection * ConfigFile::GetSection (const char * sect_name) const
Get a section from the configuration file.
Parameters
sect_name Name of the section (case sensitive).
Returns
The section with the give name if it exists, else nullptr.
Definition at line 213 of file config_reader.cpp.
References sections.
Referenced by GetNum(), and GetValue().
const char * ConfigFile::GetValue (const char * sect_name, const char * key) const
Get an item value from the configuration file.
Parameters
sect_name Name of the section (case sensitive).
key Name of the key (case sensitive).
Returns
The associated value if it exists, else nullptr.
Definition at line 227 of file config_reader.cpp.
References ConfigSection::GetItem(), GetSection(), and ConfigItem::value.
Referenced by freerct_main().
int ConfigFile::GetNum (const char * sect_name, const char * key) const
Get a number from the configuration file.
Parameters
sect_name Name of the section (case sensitive).
key Name of the key (case sensitive).
Returns
The associated number if it exists, else -1.
Definition at line 243 of file config_reader.cpp.
References ConfigSection::GetItem(), ConfigItem::GetNum(), and GetSection().
Referenced by freerct_main().
The documentation for this class was generated from the following files:
config_reader.h
config_reader.cpp