FreeRCT: AverageWeather Class Reference
AverageWeather Class Reference
Average weather of a month.
Public Member Functions
AverageWeather (int temp, int sun, int light_cloud, int thick_cloud, int rain, int thunder)
Construct an average weather object.
int TotalAmount () const
Get the sum of all amounts of weather.
WeatherType GetWeatherType (int amount) const
Get the type of weather from a given sum of amounts.
int Draw () const
Draw a random weather.
Public Attributes
int temp
Average temperature this month in 1/10 degrees Celcius.
int sun
Average amount of sunny weather this month.
int light_cloud
Average amount of sun + clouds weather this month.
int thick_cloud
Average amount of of only clouds weather this month.
int rain
Average amount of rain this month.
int thunder
Average amount of thunder storm this month.
Detailed Description
Average weather of a month.
Sum of all amounts should be equal for all months.
Definition at line 23 of file weather.cpp.
Constructor & Destructor Documentation
AverageWeather::AverageWeather (int temp, int sun, int light_cloud, int thick_cloud, int rain, int thunder)
Construct an average weather object.
Parameters
temp Average temperature this month in 1/10 degrees Celcius.
sun Average amount of sunny weather this month.
light_cloud Average amount of sun + clouds weather this month.
thick_cloud Average amount of of only clouds weather this month.
rain Average amount of rain this month.
thunder Average amount of thunder storm this month.
Note
sun + light_cloud + thick_cloud + rain + thunder should the same for every object.
Definition at line 49 of file weather.cpp.
Member Function Documentation
int AverageWeather::TotalAmount () const
Get the sum of all amounts of weather.
Returns
The sum of all amounts of weathers.
Definition at line 58 of file weather.cpp.
References light_cloud, rain, sun, thick_cloud, and thunder.
Referenced by Draw().
WeatherType AverageWeather::GetWeatherType (int amount) const
Get the type of weather from a given sum of amounts.
Parameters
amount (Partial) sum to convert.
Returns
Type of weather.
Definition at line 68 of file weather.cpp.
References light_cloud, rain, sun, thick_cloud, WTP_LIGHT_CLOUDS, WTP_RAINING, WTP_SUNNY, WTP_THICK_CLOUDS, and WTP_THUNDERSTORM.
Referenced by Weather::GetWeatherType().
int AverageWeather::Draw () const
Draw a random weather.
Returns
Amount representing the weather.
Definition at line 84 of file weather.cpp.
References TotalAmount(), and Random::Uniform().
Referenced by Weather::Initialize(), and Weather::OnNewDay().
The documentation for this class was generated from the following file:
weather.cpp