FreeRCT: FinancesManager Class Reference
FinancesManager Class Reference
Finances data and code.
A manager of finance objects.
#include <finances.h>
Public Member Functions
FinancesManager ()
Default constructor.
~FinancesManager ()
Destructor.
const Finances & GetFinances ()
Get the finance object for the current month.
void AdvanceMonth ()
Complete the current month and transition to new finances object.
void CashToStrParams ()
Transfers cash into _str_params.
void SetScenario (const Scenario &s)
Initialize finances with scenario configuration.
void DoTransaction (const Money &income)
Access method for actually changing amount of money and notifying GUI.
void Load (Loader &ldr)
Load financial data from the save game.
void Save (Saver &svr)
Save financial data to the save game.
void PayRideConstruct (const Money &m)
Access method for monthly transactions.
void PayRideRunning (const Money &m)
Access method for monthly transactions.
void PayLandPurchase (const Money &m)
Access method for monthly transactions.
void PayLandscaping (const Money &m)
Access method for monthly transactions.
void PayShopStock (const Money &m)
Access method for monthly transactions.
void PayFoodStock (const Money &m)
Access method for monthly transactions.
void PayStaffWages (const Money &m)
Access method for monthly transactions.
void PayMarketing (const Money &m)
Access method for monthly transactions.
void PayResearch (const Money &m)
Access method for monthly transactions.
void PayLoanInterest (const Money &m)
Access method for monthly transactions.
void EarnParkTickets (const Money &m)
Access method for monthly transactions.
void EarnRideTickets (const Money &m)
Access method for monthly transactions.
void EarnShopSales (const Money &m)
Access method for monthly transactions.
void EarnFoodSales (const Money &m)
Access method for monthly transactions.
Protected Attributes
Finances finances [NUM_FINANCE_HISTORY]
All finance objects needed for statistics.
int num_used
Number of Finances objects that have history.
int current
Index for the current month's Finances object.
Money cash
The user's current cash.
Private Member Functions
void Reset ()
Reset all finances to initial state.
void NotifyGui ()
Let the Gui know the financial data has changed.
Detailed Description
A manager of finance objects.
Definition at line 55 of file finances.h.
Constructor & Destructor Documentation
FinancesManager::FinancesManager ()
Default constructor.
Definition at line 125 of file finances.cpp.
References Reset().
FinancesManager::~FinancesManager ()
Destructor.
Definition at line 131 of file finances.cpp.
Member Function Documentation
const Finances & FinancesManager::GetFinances ()
Get the finance object for the current month.
Returns
Current finances object.
Definition at line 148 of file finances.cpp.
References current, finances, and num_used.
Referenced by FinancesGui::SetWidgetStringParameters().
void FinancesManager::AdvanceMonth ()
Complete the current month and transition to new finances object.
Definition at line 155 of file finances.cpp.
References current, finances, NUM_FINANCE_HISTORY, num_used, and Finances::Reset().
Referenced by OnNewMonth().
void FinancesManager::CashToStrParams ()
Transfers cash into _str_params.
Definition at line 163 of file finances.cpp.
References _str_params, cash, and StringParameters::SetMoney().
Referenced by BottomToolbarWindow::SetWidgetStringParameters().
void FinancesManager::SetScenario (const Scenario & s)
Initialize finances with scenario configuration.
Parameters
s Scenario to use for initialization.
Definition at line 172 of file finances.cpp.
References cash, and Scenario::inital_money.
Referenced by StartNewGame().
void FinancesManager::DoTransaction (const Money & income)
Access method for actually changing amount of money and notifying GUI.
Parameters
income How much money to change total by.
Note
Pass a negative number for a loss of money.
Definition at line 182 of file finances.cpp.
References cash, and NotifyGui().
Referenced by EarnFoodSales(), EarnParkTickets(), EarnRideTickets(), EarnShopSales(), PayFoodStock(), PayLandPurchase(), PayLandscaping(), PayLoanInterest(), PayMarketing(), PayResearch(), PayRideConstruct(), PayRideRunning(), PayShopStock(), and PayStaffWages().
void FinancesManager::Load (Loader & ldr)
Load financial data from the save game.
Parameters
ldr Input stream to load from.
Definition at line 199 of file finances.cpp.
References cash, Loader::CloseBlock(), current, finances, Loader::GetByte(), Loader::GetLongLong(), NotifyGui(), num_used, Loader::OpenBlock(), Reset(), and Loader::SetFailMessage().
Referenced by LoadElements().
void FinancesManager::Save (Saver & svr)
Save financial data to the save game.
Parameters
svr Output stream to save to.
Definition at line 220 of file finances.cpp.
References cash, current, Saver::EndBlock(), finances, num_used, Saver::PutByte(), Saver::PutLongLong(), and Saver::StartBlock().
Referenced by SaveElements().
void FinancesManager::PayRideConstruct (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 80 of file finances.h.
References current, DoTransaction(), and Finances::ride_construct.
void FinancesManager::PayRideRunning (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 90 of file finances.h.
References current, DoTransaction(), and Finances::ride_running.
void FinancesManager::PayLandPurchase (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 100 of file finances.h.
References current, DoTransaction(), and Finances::land_purchase.
void FinancesManager::PayLandscaping (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 110 of file finances.h.
References current, DoTransaction(), and Finances::landscaping.
void FinancesManager::PayShopStock (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 120 of file finances.h.
References current, DoTransaction(), and Finances::shop_stock.
Referenced by RideInstance::SellItem().
void FinancesManager::PayFoodStock (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 130 of file finances.h.
References current, DoTransaction(), and Finances::food_stock.
void FinancesManager::PayStaffWages (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 140 of file finances.h.
References current, DoTransaction(), and Finances::staff_wages.
Referenced by RideInstance::OnNewMonth(), and RideInstance::OpenRide().
void FinancesManager::PayMarketing (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 150 of file finances.h.
References current, DoTransaction(), and Finances::marketing.
void FinancesManager::PayResearch (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 160 of file finances.h.
References current, DoTransaction(), and Finances::research.
void FinancesManager::PayLoanInterest (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to pay.
Definition at line 170 of file finances.h.
References current, DoTransaction(), and Finances::loan_interest.
void FinancesManager::EarnParkTickets (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to earn.
Definition at line 180 of file finances.h.
References current, DoTransaction(), and Finances::park_tickets.
void FinancesManager::EarnRideTickets (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to earn.
Definition at line 190 of file finances.h.
References current, DoTransaction(), and Finances::ride_tickets.
void FinancesManager::EarnShopSales (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to earn.
Definition at line 200 of file finances.h.
References current, DoTransaction(), and Finances::shop_sales.
Referenced by RideInstance::SellItem().
void FinancesManager::EarnFoodSales (const Money & m) inline
Access method for monthly transactions.
Parameters
m how much money to earn.
Definition at line 210 of file finances.h.
References current, DoTransaction(), and Finances::food_sales.
void FinancesManager::Reset () private
Reset all finances to initial state.
Definition at line 136 of file finances.cpp.
References cash, current, finances, num_used, and Finances::Reset().
Referenced by FinancesManager(), and Load().
void FinancesManager::NotifyGui () private
Let the Gui know the financial data has changed.
Definition at line 189 of file finances.cpp.
References ALL_WINDOWS_OF_TYPE, CHG_DISPLAY_OLD, NotifyChange(), WC_BOTTOM_TOOLBAR, and WC_FINANCES.
Referenced by DoTransaction(), and Load().
The documentation for this class was generated from the following files:
finances.h
finances.cpp