FreeRCT: AnimationSprites Class Reference
AnimationSprites Class Reference
Data structure holding sprite of an animation.
#include <sprite_store.h>
Public Member Functions
AnimationSprites ()
Animation sprites default constructor.
~AnimationSprites ()
Animation sprites destructor.
bool Load (RcdFileReader *rcd_file, const ImageMap &sprites)
Load the sprites of an animation.
Public Attributes
uint16 width
Width of the tile.
uint8 person_type
Type of persons supported by this animation.
AnimationType anim_type
Animation ID.
uint16 frame_count
Number of frames.
ImageData ** sprites
Sprites of the animation.
RcdBlock * next
Pointer to next block.
Detailed Description
Data structure holding sprite of an animation.
Definition at line 225 of file sprite_store.h.
Constructor & Destructor Documentation
AnimationSprites::AnimationSprites ()
Animation sprites default constructor.
Definition at line 771 of file sprite_store.cpp.
References ANIM_INVALID, anim_type, frame_count, PERSON_INVALID, person_type, sprites, and width.
AnimationSprites::~AnimationSprites ()
Animation sprites destructor.
Definition at line 781 of file sprite_store.cpp.
References sprites.
Member Function Documentation
bool AnimationSprites::Load (RcdFileReader * rcd_file, const ImageMap & sprites)
Load the sprites of an animation.
Parameters
rcd_file RCD file used for loading.
sprites Map of already loaded sprites.
Returns
Loading was successful.
Definition at line 792 of file sprite_store.cpp.
References ANIM_LAST, anim_type, DecodePersonType(), frame_count, RcdFileReader::GetUInt16(), RcdFileReader::GetUInt8(), LoadSpriteFromFile(), PERSON_INVALID, person_type, RcdFileReader::size, RcdFileReader::version, and width.
Referenced by SpriteManager::Load().
The documentation for this class was generated from the following files:
sprite_store.h
sprite_store.cpp