FreeRCT: Image32bpp Class Reference
Image32bpp Class Reference
A 32bpp image.
#include <image.h>
Public Member Functions
Image32bpp (const ImageFile *imf, BitMaskData *mask)
Enable making a 32bpp sprite.
void SetRecolourImage (Image8bpp *recolour)
Setup a recolour image.
uint32 GetPixel (int x, int y) const
Get a pixel from the image.
virtual bool IsTransparent (int xpos, int ypos) const override
Return whether the pixel at the given coordinate is fully transparent.
virtual uint8 * Encode (int xpos, int ypos, int width, int height, int *size) const override
Encode an 8bpp sprite from (a part of) the image.
int GetWidth () const
Get the width of the image.
int GetHeight () const
Get the height of the image.
bool IsEmpty (int xpos, int ypos, int dx, int dy, int length) const
Is the queried set of pixels empty?
bool IsMaskedOut (int xpos, int ypos) const
If the pixel at the given coordinate masked away?
Public Attributes
const char * block_name
Name of the block to write.
const int block_version
Version number of the block to write.
Protected Member Functions
uint8 GetCurrentRecolour (int x, int y, int max_length, int *count) const
Find out how many pixels at the line have the same recolour information.
uint8 GetSameOpaqueness (int x, int y, int max_length, int *count) const
Find how many pixels at a line from the given position, have the same opaqueness value.
Protected Attributes
Image8bpp * recolour
Recolour information (not owned by this class).
const ImageFile * imf
Image file (not owned by the object).
int mask_xpos
X position of the left of the mask.
int mask_ypos
Y position of the top of the mask.
const MaskInformation * mask
Information about the used bitmask (or nullptr).
Detailed Description
A 32bpp image.
Definition at line 94 of file image.h.
Constructor & Destructor Documentation
Image32bpp::Image32bpp (const ImageFile * imf, BitMaskData * mask)
Enable making a 32bpp sprite.
Parameters
imf Image file to use.
mask Bitmask to apply, or nullptr.
Definition at line 493 of file image.cpp.
References recolour.
Member Function Documentation
void Image32bpp::SetRecolourImage (Image8bpp * recolour)
Setup a recolour image.
Parameters
recolour Recolour image to use.
Note
Recolour image is not owned by the 32bpp sprite creation class.
Definition at line 503 of file image.cpp.
References Image::GetHeight(), Image::GetWidth(), and recolour.
Referenced by ConvertSpriteNode(), SheetBlock::GetSheet(), and SpriteFilesBlock::GetSubNode().
uint32 Image32bpp::GetPixel (int x, int y) const
Get a pixel from the image.
Parameters
x Horizontal position.
y Vertical position.
Returns
Value of the pixel (32 bit full colour with alpha channel).
Definition at line 516 of file image.cpp.
References FULLY_TRANSPARENT, ImageFile::height, Image::imf, Image::IsMaskedOut(), MakeRGBA(), ImageFile::row_pointers, and ImageFile::width.
Referenced by Encode(), GetSameOpaqueness(), and IsTransparent().
bool Image32bpp::IsTransparent (int xpos, int ypos) const override virtual
Return whether the pixel at the given coordinate is fully transparent.
Parameters
xpos Horizontal position of the pixel.
ypos Vertical position of the pixel.
Returns
Whether the pixel at the given coordinate is fully transparent.
Implements Image.
Definition at line 528 of file image.cpp.
References FULLY_TRANSPARENT, GetA(), and GetPixel().
uint8 * Image32bpp::Encode (int xpos, int ypos, int width, int height, int * size) const override virtual
Encode an 8bpp sprite from (a part of) the image.
Parameters
xpos Left position of the sprite in the image.
ypos Top position of the sprite in the image.
width Width of the sprite.
height Height of the sprite.
size [out] Number of bytes needed to store the sprite.
Returns
Memory of length size holding the sprite data. An empty sprite is return as nullptr with size /c 0. A nullptr with a non-zero size indicates a memory error.
Todo:
Add recolouring image handling.
Implements Image.
Definition at line 586 of file image.cpp.
References FULLY_OPAQUE, FULLY_TRANSPARENT, GetB(), GetCurrentRecolour(), GetG(), GetPixel(), GetR(), GetSameOpaqueness(), and recolour.
uint8 Image32bpp::GetCurrentRecolour (int x, int y, int max_length, int * count) const protected
Find out how many pixels at the line have the same recolour information.
Parameters
x X position of the first pixel in the image to examine.
y Y position of the first pixel in the image to examine.
max_length Maximum number of pixels to test (should be at least 1).
count [out] Number of pixels with the same recolour information.
Returns
Value of the recolour information (at x, y).
Definition at line 541 of file image.cpp.
References Image8bpp::GetPixel(), and recolour.
Referenced by Encode().
uint8 Image32bpp::GetSameOpaqueness (int x, int y, int max_length, int * count) const protected
Find how many pixels at a line from the given position, have the same opaqueness value.
Parameters
x X position of the first pixel in the image to examine.
y Y position of the first pixel in the image to examine.
max_length Maximum number of pixels to test (should be at least 1).
count [out] Number of pixels with the same opaqueness value.
Returns
Value of the opaqueness (at x, y).
Definition at line 570 of file image.cpp.
References GetA(), and GetPixel().
Referenced by Encode().
int Image::GetWidth () const inherited
Get the width of the image.
Returns
Width of the loaded image, or -1.
Definition at line 230 of file image.cpp.
References ImageFile::GetWidth(), and Image::imf.
Referenced by SpriteImage::CopySprite(), and SetRecolourImage().
int Image::GetHeight () const inherited
Get the height of the image.
Returns
Height of the loaded image, or -1.
Definition at line 221 of file image.cpp.
References ImageFile::GetHeight(), and Image::imf.
Referenced by SpriteImage::CopySprite(), and SetRecolourImage().
bool Image::IsEmpty (int xpos, int ypos, int dx, int dy, int length) const inherited
Is the queried set of pixels empty?
Parameters
xpos Horizontal start position.
ypos Vertical start position.
dx Horizontal stepping size.
dy Vertical stepping size.
length Number of pixels to examine.
Returns
All examined pixels are empty (have colour 0).
Definition at line 244 of file image.cpp.
References Image::IsTransparent().
Referenced by SpriteImage::CopySprite().
bool Image::IsMaskedOut (int x, int y) const inherited
If the pixel at the given coordinate masked away?
Parameters
x Horizontal position.
y Vertical position.
Returns
Whether the pixel at the given coordinate is masked away.
Definition at line 261 of file image.cpp.
References MaskInformation::data, Image::mask, Image::mask_xpos, Image::mask_ypos, and MaskInformation::width.
Referenced by Image8bpp::GetPixel(), and GetPixel().
The documentation for this class was generated from the following files:
image.h
image.cpp