FreeRCT: Cursor Class Reference
Cursor Class Reference
%Window code » %Viewport (main display) code and data
Single tile cursor.
#include <viewport.h>
Public Member Functions
Cursor (Viewport *vp)
Constructor of a cursor.
bool SetCursor (uint16 xpos, uint16 ypos, uint8 zpos, CursorType type, bool always=false)
Set a cursor.
void MarkDirty () override
Update the cursor at the screen.
CursorType GetCursor (uint16 xpos, uint16 ypos, uint8 zpos) override
Get a cursor.
uint8 GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos) override
Get the maximum height of the xpos, ypos stack that needs to be examined.
void SetInvalid ()
Mark the cursor as being invalid, and update the viewport if necessary.
Public Attributes
uint16 xpos
Voxel x position of the cursor.
uint16 ypos
Voxel y position of the cursor.
uint8 zpos
Voxel z position of the cursor.
Viewport * vp
Parent viewport object.
CursorType type
Type of cursor.
Detailed Description
Single tile cursor.
Definition at line 163 of file viewport.h.
Constructor & Destructor Documentation
Cursor::Cursor (Viewport * vp)
Constructor of a cursor.
Parameters
vp Viewport displaying the cursor.
Definition at line 498 of file viewport.cpp.
References xpos, ypos, and zpos.
Member Function Documentation
bool Cursor::SetCursor (uint16 xpos, uint16 ypos, uint8 zpos, CursorType type, bool always = false)
Set a cursor.
Parameters
xpos X position of the voxel containing the cursor.
ypos Y position of the voxel containing the cursor.
zpos Z position of the voxel containing the cursor.
type Type of cursor to set.
always Always set the cursor (else, only set it if it changed).
Returns
Cursor has been set/changed.
Definition at line 539 of file viewport.cpp.
References MarkDirty(), BaseCursor::type, xpos, ypos, and zpos.
Referenced by PathBuildManager::OnMouseMoveEvent(), TileTerraformMouseMode::SetCursors(), CoasterBuildMode::UpdateDisplay(), and PathBuildManager::UpdateState().
void Cursor::MarkDirty () override virtual
Update the cursor at the screen.
Implements BaseCursor.
Definition at line 505 of file viewport.cpp.
References CUR_TYPE_INVALID, Viewport::MarkVoxelDirty(), BaseCursor::type, BaseCursor::vp, xpos, ypos, and zpos.
Referenced by Viewport::DisableWorldAdditions(), Viewport::EnableWorldAdditions(), Viewport::EnsureAdditionsAreVisible(), SetCursor(), and Viewport::TimeoutCallback().
CursorType Cursor::GetCursor (uint16 xpos, uint16 ypos, uint8 zpos) override virtual
Get a cursor.
Parameters
xpos Expected x coordinate of the cursor.
ypos Expected y coordinate of the cursor.
zpos Expected z coordinate of the cursor.
Returns
The cursor sprite if the cursor exists and the coordinates are correct, else nullptr.
Implements BaseCursor.
Definition at line 517 of file viewport.cpp.
References CUR_TYPE_INVALID, and BaseCursor::type.
Referenced by Viewport::GetCursorAtPos().
uint8 Cursor::GetMaxCursorHeight (uint16 xpos, uint16 ypos, uint8 zpos) override virtual
Get the maximum height of the xpos, ypos stack that needs to be examined.
Parameters
xpos X position of the voxel.
ypos Y position of the voxel.
zpos Top of the stack found so far.
Returns
Highest voxel to draw for this cursor.
Implements BaseCursor.
Definition at line 523 of file viewport.cpp.
References CUR_TYPE_INVALID, BaseCursor::type, and zpos.
Referenced by Viewport::GetMaxCursorHeight().
void BaseCursor::SetInvalid () inherited
Mark the cursor as being invalid, and update the viewport if necessary.
Definition at line 488 of file viewport.cpp.
References CUR_TYPE_INVALID, BaseCursor::MarkDirty(), and BaseCursor::type.
Referenced by FenceBuildManager::LeaveMode(), TileTerraformMouseMode::LeaveMode(), TileTerraformMouseMode::SetCursors(), and PathBuildManager::UpdateState().
The documentation for this class was generated from the following files:
viewport.h
viewport.cpp