FreeRCT: TerrainChanges Class Reference
TerrainChanges Class Reference
World map data and code
Store and manage terrain changes.
#include <terraform.h>
Public Member Functions
TerrainChanges (const Point32 &base, uint16 xsize, uint16 ysize)
Terrain changes storage constructor.
~TerrainChanges ()
Destructor.
void UpdatelevellingHeight (const Point32 &pos, int direction, uint8 *height)
Test every corner of the given voxel for its original height, and find the extreme value.
bool ChangeVoxel (const Point32 &pos, uint8 height, int direction)
Change corners of a voxel if they are within the height constraint.
bool ChangeCorner (const Point32 &pos, TileCorner corner, int direction)
Change the height of a corner.
bool ModifyWorld (int direction)
Perform the proposed changes in _additions (and committing them afterwards).
Public Attributes
GroundModificationMap changes
Registered changes.
Private Member Functions
GroundData * GetGroundData (const Point32 &pos)
Get ground data of a voxel stack.
Private Attributes
Point32 base
Base position of the smooth changing world.
uint16 xsize
Horizontal size of the smooth changing world.
uint16 ysize
Vertical size of the smooth changing world.
Detailed Description
Store and manage terrain changes.
Todo:
Enable pulling the screen min/max coordinates from it, so we can give a good estimate of the area to redraw.
Definition at line 44 of file terraform.h.
Constructor & Destructor Documentation
TerrainChanges::TerrainChanges (const Point32 & base, uint16 xsize, uint16 ysize)
Terrain changes storage constructor.
Parameters
base Base coordinate of the part of the world which is smoothly updated.
xsize Horizontal size of the world part.
ysize Vertical size of the world part.
Definition at line 114 of file terraform.cpp.
References _world, base, VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), Point< CT >::x, xsize, Point< CT >::y, and ysize.
TerrainChanges::~TerrainChanges ()
Destructor.
Definition at line 124 of file terraform.cpp.
Member Function Documentation
void TerrainChanges::UpdatelevellingHeight (const Point32 & pos, int direction, uint8 * height)
Test every corner of the given voxel for its original height, and find the extreme value.
Parameters
pos Voxel position.
direction Levelling direction (decides whether to find the lowest or highest corner).
height [inout] Extremest height found so far.
Definition at line 155 of file terraform.cpp.
References GetGroundData(), GroundData::GetOrigHeight(), TC_EAST, TC_NORTH, TC_SOUTH, and TC_WEST.
Referenced by ChangeAreaCursorMode(), and ChangeTileCursorMode().
bool TerrainChanges::ChangeVoxel (const Point32 & pos, uint8 height, int direction)
Change corners of a voxel if they are within the height constraint.
Parameters
pos Voxel position.
height Minimum or maximum height of the corners to modify.
direction Levelling direction (decides what constraint to use).
Returns
Change is OK for the map.
Definition at line 179 of file terraform.cpp.
References ChangeCorner(), GetGroundData(), GroundData::GetOrigHeight(), TC_EAST, TC_NORTH, TC_SOUTH, and TC_WEST.
Referenced by ChangeAreaCursorMode(), and ChangeTileCursorMode().
bool TerrainChanges::ChangeCorner (const Point32 & pos, TileCorner corner, int direction)
Change the height of a corner.
Call this function for every corner you want to change.
Parameters
pos Position of the voxel stack.
corner Corner to change.
direction Direction of change.
Returns
Change is OK for the map.
Definition at line 204 of file terraform.cpp.
References _game_mode_mgr, _world, VoxelCorner::corner, GroundData::GetCornerModified(), GetGroundData(), GroundData::GetOrigHeight(), VoxelWorld::GetTileOwner(), GameModeManager::InPlayMode(), CornerNeighbours::neighbour_tiles, OWN_PARK, VoxelCorner::rel_xy, GroundData::SetCornerModified(), TC_END, TC_NORTH, WORLD_Z_SIZE, Point< CT >::x, and Point< CT >::y.
Referenced by ChangeTileCursorMode(), and ChangeVoxel().
bool TerrainChanges::ModifyWorld (int direction)
Perform the proposed changes in _additions (and committing them afterwards).
Parameters
direction Direction of change.
Returns
Whether the change could actually be performed (else nothing is changed).
Definition at line 442 of file terraform.cpp.
References _additions, _mouse_modes, changes, WorldAdditions::Clear(), WorldAdditions::Commit(), ComputeCornerHeight(), ComputeSlopeAndHeight(), ExpandTileSlope(), FDT_INVALID, FENCE_TYPE_INVALID, VoxelStack::Get(), VoxelStack::GetCreate(), Voxel::GetFenceType(), Voxel::GetFoundationType(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), WorldAdditions::GetModifyStack(), MouseModes::GetMouseMode(), GTP_INVALID, GroundData::height, lengthof, MayHaveGroundFenceInVoxelAbove(), MM_TILE_TERRAFORM, GroundData::modified, GroundData::orig_slope, Voxel::SetFenceType(), Voxel::SetFoundationSlope(), Voxel::SetFoundationType(), Voxel::SetGroundSlope(), Voxel::SetGroundType(), SetUpperBoundary(), SetXFoundations(), SetYFoundations(), StoreFenceInUpperVoxel(), TC_END, TC_NORTH, TSB_STEEP, WORLD_Z_SIZE, Point< CT >::x, and Point< CT >::y.
Referenced by ChangeAreaCursorMode(), and ChangeTileCursorMode().
GroundData * TerrainChanges::GetGroundData (const Point32 & pos) private
Get ground data of a voxel stack.
Parameters
pos Voxel stack position.
Returns
Pointer to the ground data, or nullptr if outside the world.
Definition at line 133 of file terraform.cpp.
References _world, changes, ExpandTileSlope(), VoxelWorld::GetGroundHeight(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), VoxelWorld::GetVoxel(), GTP_INVALID, Point< CT >::x, and Point< CT >::y.
Referenced by ChangeCorner(), ChangeVoxel(), and UpdatelevellingHeight().
The documentation for this class was generated from the following files:
terraform.h
terraform.cpp