FreeRCT: PixelFinder Class Reference
PixelFinder Class Reference
%Window code » %Viewport (main display) code and data
Find the sprite and pixel under the mouse cursor.
Public Member Functions
PixelFinder (Viewport *vp, FinderData *fdata)
Constructor of the tile position finder.
void SetWindowSize (int16 xpos, int16 ypos, uint16 width, uint16 height)
Set screen area of interest (relative to the (xview, yview, and zview position).
void Collect (bool use_additions)
Perform the collecting cycle.
int32 ComputeX (int32 x, int32 y)
Convert 3D position to the horizontal 2D position.
int32 ComputeY (int32 x, int32 y, int32 z)
Convert 3D position to the vertical 2D position.
Public Attributes
ClickableSprite allowed
Sprite types looking for.
bool found
Found a match.
DrawData data
Drawing data of the match found so far.
uint32 pixel
Pixel colour of the closest sprite.
FinderData * fdata
Finder data to return.
int32 xview
X position of the centre point of the display.
int32 yview
Y position of the centre point of the display.
int32 zview
Z position of the centre point of the display.
uint16 tile_width
Width of a tile.
uint16 tile_height
Height of a tile.
ViewOrientation orient
Direction of view.
const SpriteStorage * sprites
Sprite collection of the right size.
Viewport * vp
Parent viewport for accessing the cursors if not nullptr.
bool draw_above_stack
Also draw voxels above the voxel stack (for cursors).
Rectangle32 rect
Screen area of interest.
Protected Member Functions
void CollectVoxel (const Voxel *vx, int xpos, int ypos, int zpos, int32 xnorth, int32 ynorth) override
Find the closest sprite.
virtual void SetupSupports (const VoxelStack *stack, uint xpos, uint ypos)
Decide where supports should be raised.
Detailed Description
Find the sprite and pixel under the mouse cursor.
Definition at line 292 of file viewport.cpp.
Constructor & Destructor Documentation
PixelFinder::PixelFinder (Viewport * vp, FinderData * fdata)
Constructor of the tile position finder.
Parameters
vp Viewport that needs the tile position.
fdata Finder data.
Definition at line 1177 of file viewport.cpp.
References _palette, FinderData::allowed, allowed, fdata, found, INVALID_RIDE_INSTANCE, FinderData::person, pixel, FinderData::ride, FinderData::xvoxel, FinderData::yvoxel, and FinderData::zvoxel.
Member Function Documentation
void PixelFinder::CollectVoxel (const Voxel * voxel, int xpos, int ypos, int zpos, int32 xnorth, int32 ynorth) override protected virtual
Find the closest sprite.
Parameters
voxel Voxel to examine, nullptr means 'cursor above stack'.
xpos X world position.
ypos Y world position.
zpos Z world position.
xnorth X coordinate of the north corner at the display.
ynorth y coordinate of the north corner at the display.
Implements VoxelCollector.
Definition at line 1204 of file viewport.cpp.
References allowed, WalkInformation::anim_type, DrawData::base, Rectangle< PT, SZ >::base, VoxelCollector::ComputeX(), VoxelCollector::ComputeY(), CS_GROUND, CS_PATH, CS_PERSON, CS_RIDE, data, DrawRide(), fdata, found, Person::frame_index, GetA(), SpriteStorage::GetAnimationSprite(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), GetImplodedPathSlope(), Voxel::GetInstance(), Voxel::GetInstanceData(), SpriteStorage::GetPathSprite(), GetPathType(), ImageData::GetPixel(), SpriteStorage::GetSurfaceSprite(), GTP_CURSOR_EDGE_TEST, GTP_CURSOR_TEST, GTP_INVALID, HasValidPath(), DrawData::level, VoxelObject::next_object, NOT_REACHED, DrawData::order, VoxelCollector::orient, FinderData::person, pixel, DrawData::recolour, VoxelCollector::rect, FinderData::ride, SO_GROUND, SO_GROUND_EDGE, SO_PATH, SO_PERSON, DrawData::sprite, VoxelCollector::sprites, SRI_FULL_RIDES, TRANSPARENT, Person::type, Voxel::voxel_objects, Person::walk, Point< CT >::x, VoxelObject::x_pos, ImageData::xoffset, FinderData::xvoxel, Point< CT >::y, VoxelObject::y_pos, ImageData::yoffset, FinderData::yvoxel, DrawData::z_height, VoxelObject::z_pos, and FinderData::zvoxel.
void VoxelCollector::SetWindowSize (int16 xpos, int16 ypos, uint16 width, uint16 height) inherited
Set screen area of interest (relative to the (xview, yview, and zview position).
Parameters
xpos Horizontal position of the top-left corner.
ypos Vertical position of the top-left corner.
width Width of the area.
height Height of the area.
Definition at line 340 of file viewport.cpp.
References Rectangle< PT, SZ >::base, VoxelCollector::ComputeX(), VoxelCollector::ComputeY(), Rectangle< PT, SZ >::height, VoxelCollector::rect, Rectangle< PT, SZ >::width, Point< CT >::x, VoxelCollector::xview, Point< CT >::y, VoxelCollector::yview, and VoxelCollector::zview.
Referenced by Viewport::ComputeCursorPosition(), and Viewport::OnDraw().
void VoxelCollector::Collect (bool use_additions) inherited
Perform the collecting cycle.
This part walks over the voxels, and call CollectVoxel for each useful voxel. A derived class may then inspect the voxel in more detail.
Parameters
use_additions Use the _additions voxels for drawing.
Todo:
Do this less stupid. Walking the whole world is not going to work in general.
Definition at line 355 of file viewport.cpp.
References _world, Rectangle< PT, SZ >::base, VoxelStack::base, VoxelCollector::CollectVoxel(), VoxelCollector::ComputeX(), VoxelCollector::ComputeY(), VoxelCollector::draw_above_stack, Viewport::GetMaxCursorHeight(), VoxelWorld::GetStack(), WorldAdditions::GetStack(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), VoxelStack::height, VoxelCollector::orient, VoxelCollector::rect, VoxelCollector::SetupSupports(), VoxelCollector::tile_height, VoxelCollector::tile_width, VOR_EAST, VOR_SOUTH, VOR_WEST, VoxelStack::voxels, VoxelCollector::vp, Point< CT >::x, and Point< CT >::y.
Referenced by Viewport::ComputeCursorPosition().
int32 VoxelCollector::ComputeX (int32 x, int32 y) inline inherited
Convert 3D position to the horizontal 2D position.
Parameters
x X position in the game world.
y Y position in the game world.
Returns
X position in 2D.
Definition at line 173 of file viewport.cpp.
References ComputeXFunction(), VoxelCollector::orient, and VoxelCollector::tile_width.
Referenced by VoxelCollector::Collect(), SpriteCollector::CollectVoxel(), CollectVoxel(), and VoxelCollector::SetWindowSize().
int32 VoxelCollector::ComputeY (int32 x, int32 y, int32 z) inline inherited
Convert 3D position to the vertical 2D position.
Parameters
x X position in the game world.
y Y position in the game world.
z Z position in the game world.
Returns
Y position in 2D.
Definition at line 185 of file viewport.cpp.
References ComputeYFunction(), VoxelCollector::orient, VoxelCollector::tile_height, and VoxelCollector::tile_width.
Referenced by VoxelCollector::Collect(), SpriteCollector::CollectVoxel(), CollectVoxel(), and VoxelCollector::SetWindowSize().
virtual void VoxelCollector::SetupSupports (const VoxelStack * stack, uint xpos, uint ypos) inline protected virtual inherited
Decide where supports should be raised.
Parameters
stack Voxel stack to examine.
xpos X position of the voxel stack.
ypos Y position of the voxel stack.
Reimplemented in SpriteCollector.
Definition at line 210 of file viewport.cpp.
Referenced by VoxelCollector::Collect().
The documentation for this class was generated from the following file:
viewport.cpp