FreeRCT: StringsStorage Class Reference
StringsStorage Class Reference
Storage of translation strings for future use.
#include <string_storage.h>
Public Member Functions
void AddStrings (std::shared_ptr< StringsNode > strs, const Position &pos)
Add a collection of strings to the storage.
void AddToBundle (std::shared_ptr< StringsNode > strs, const Position &pos)
Add strings belonging to one bundle to storage.
const StringBundle * GetBundle (const std::string &key)
Retrieve the stored bundle of string by key name.
Public Attributes
std::map< std::string,
StringBundle > bundles
Available bundles, ordered by key.
Detailed Description
Storage of translation strings for future use.
Definition at line 16 of file string_storage.h.
Member Function Documentation
void StringsStorage::AddStrings (std::shared_ptr< StringsNode > strs, const Position & pos)
Add a collection of strings to the storage.
Parameters
strs String collection to add.
pos Position of the collection.
Definition at line 49 of file string_storage.cpp.
References AddToBundle(), and NeedsSplit().
Referenced by CheckTree().
void StringsStorage::AddToBundle (std::shared_ptr< StringsNode > strs, const Position & pos)
Add strings belonging to one bundle to storage.
Parameters
strs Strings to add
pos Position of the collection.
Definition at line 89 of file string_storage.cpp.
References bundles, StringBundle::Fill(), and Position::ToString().
Referenced by AddStrings().
const StringBundle * StringsStorage::GetBundle (const std::string & key)
Retrieve the stored bundle of string by key name.
Parameters
key Key to retrieve.
Returns
Pointer to the bundle, or nullptr if not found.
Definition at line 110 of file string_storage.cpp.
References bundles.
Referenced by StringBundle::CheckTranslations().
The documentation for this class was generated from the following files:
string_storage.h
string_storage.cpp