FreeRCT: RidesManager Class Reference
RidesManager Class Reference
Storage of available ride types.
#include <ride_type.h>
Public Member Functions
RidesManager ()
Default constructor of the rides manager.
RideInstance * GetRideInstance (uint16 num)
Get the requested ride instance.
const RideInstance * GetRideInstance (uint16 num) const
Get the requested ride instance (read-only).
RideInstance * FindRideByName (const uint8 *name)
Check whether a ride exists with the given name.
bool AddRideType (RideType *type)
Add a new ride type to the manager.
uint16 GetFreeInstance (const RideType *type)
Check whether the ride type can actually be created.
RideInstance * CreateInstance (const RideType *type, uint16 num)
Create a new ride instance.
void NewInstanceAdded (uint16 num)
A new ride instance was added.
void DeleteInstance (uint16 num)
Destroy the indicated instance.
void CheckNoAllocatedRides () const
Check that no rides are under construction at the moment of calling.
void OnAnimate (int delay)
Some time has passed, update the state of the rides.
void OnNewMonth ()
A new month has started; perform monthly payments.
void OnNewDay ()
A new day has started; break rides randomly.
const RideType * GetRideType (uint16 number) const
Get a ride type from the class.
Public Attributes
const RideType * ride_types [MAX_NUMBER_OF_RIDE_TYPES]
Loaded types of rides.
RideInstance * instances [MAX_NUMBER_OF_RIDE_INSTANCES]
Rides available in the park.
Detailed Description
Storage of available ride types.
Definition at line 184 of file ride_type.h.
Constructor & Destructor Documentation
RidesManager::RidesManager ()
Default constructor of the rides manager.
Definition at line 387 of file ride_type.cpp.
References instances, lengthof, and ride_types.
Member Function Documentation
RideInstance * RidesManager::GetRideInstance (uint16 num)
Get the requested ride instance.
Parameters
num Ride number to retrieve.
Returns
The requested ride, or nullptr if not available.
Definition at line 434 of file ride_type.cpp.
References instances, lengthof, SRI_FULL_RIDES, and SRI_LAST.
Referenced by ShopPlacementManager::ComputeShopVoxel(), DrawRide(), Viewport::MarkVoxelDirty(), NewInstanceAdded(), Person::OnAnimate(), SelectMouseMode::OnMouseButtonEvent(), ShopPlacementManager::PlaceShop(), RideExistsAtBottom(), ShowShopManagementGui(), and CoasterBuildMode::UpdateDisplay().
const RideInstance * RidesManager::GetRideInstance (uint16 num) const
Get the requested ride instance (read-only).
Parameters
num Ride instance to retrieve.
Returns
The requested ride, or nullptr if not available.
Definition at line 447 of file ride_type.cpp.
References instances, lengthof, SRI_FULL_RIDES, and SRI_LAST.
RideInstance * RidesManager::FindRideByName (const uint8 * name)
Check whether a ride exists with the given name.
Parameters
name Name of the ride to find.
Returns
The ride with the given name, or nullptr if no such ride exists.
Definition at line 518 of file ride_type.cpp.
References instances, lengthof, RIS_ALLOCATED, and StrEqual().
Referenced by NewInstanceAdded().
bool RidesManager::AddRideType (RideType * type)
Add a new ride type to the manager.
Parameters
type New ride type to add.
Returns
true if the addition was successful, else false.
Definition at line 472 of file ride_type.cpp.
References lengthof, and ride_types.
Referenced by SpriteManager::Load().
uint16 RidesManager::GetFreeInstance (const RideType * type)
Check whether the ride type can actually be created.
Parameters
type Ride type that should be created.
Returns
Index of a free instance if it exists (claim it immediately using CreateInstance), or INVALID_RIDE_INSTANCE if all instances are used.
Definition at line 488 of file ride_type.cpp.
References RideType::CanMakeInstance(), instances, INVALID_RIDE_INSTANCE, lengthof, and SRI_FULL_RIDES.
Referenced by RideSelectGui::OnClick(), and ShopPlacementManager::SetSelection().
RideInstance * RidesManager::CreateInstance (const RideType * type, uint16 num)
Create a new ride instance.
Parameters
type Type of ride to construct.
num Ride number.
Returns
The created ride.
Definition at line 503 of file ride_type.cpp.
References RideType::CreateInstance(), instances, lengthof, SRI_FULL_RIDES, and SRI_LAST.
Referenced by RideSelectGui::OnClick(), and ShopPlacementManager::SetSelection().
void RidesManager::NewInstanceAdded (uint16 num)
A new ride instance was added.
Initialize it further.
Parameters
num Ride number of the new ride.
Todo:
Add other ride types.
Definition at line 531 of file ride_type.cpp.
References _str_params, RideInstance::BuildRide(), RideInstance::CloseRide(), DrawText(), FindRideByName(), RideType::GetInstanceNames(), RideInstance::GetKind(), GetRideInstance(), RideInstance::GetRideType(), RideType::GetString(), RideType::item_cost, RideInstance::item_count, RideInstance::item_price, lengthof, RideInstance::name, NOT_REACHED, NUMBER_ITEM_TYPES_SOLD, RIS_ALLOCATED, RTK_COASTER, RTK_SHOP, StringParameters::SetNumber(), StringParameters::SetStrID(), RideInstance::state, STR_INVALID, RideInstance::total_profit, and RideInstance::total_sell_profit.
Referenced by RideSelectGui::OnClick(), and ShopPlacementManager::OnMouseButtonEvent().
void RidesManager::DeleteInstance (uint16 num)
Destroy the indicated instance.
Parameters
num The ride number to destroy.
Todo:
The small matter of cleaning up in the world map.
Precondition
Instance must be closed.
Definition at line 590 of file ride_type.cpp.
References _guests, instances, lengthof, Guests::NotifyRideDeletion(), RideInstance::RemoveAllPeople(), SRI_FULL_RIDES, and SRI_LAST.
Referenced by ShopPlacementManager::CloseWindow(), ShopPlacementManager::LeaveMode(), and ShopPlacementManager::SetSelection().
void RidesManager::CheckNoAllocatedRides () const
Check that no rides are under construction at the moment of calling.
Note
This is just a checking function, perhaps eventually remove it?
Definition at line 605 of file ride_type.cpp.
References instances, lengthof, and RIS_ALLOCATED.
void RidesManager::OnAnimate (int delay)
Some time has passed, update the state of the rides.
Parameters
delay Number of milliseconds that passed.
Definition at line 403 of file ride_type.cpp.
References instances, lengthof, RideInstance::OnAnimate(), and RIS_ALLOCATED.
Referenced by OnNewFrame().
void RidesManager::OnNewMonth ()
A new month has started; perform monthly payments.
Definition at line 412 of file ride_type.cpp.
References instances, lengthof, RideInstance::OnNewMonth(), and RIS_ALLOCATED.
Referenced by OnNewMonth().
void RidesManager::OnNewDay ()
A new day has started; break rides randomly.
Definition at line 421 of file ride_type.cpp.
References instances, lengthof, RideInstance::OnNewDay(), and RIS_ALLOCATED.
Referenced by OnNewDay().
const RideType* RidesManager::GetRideType (uint16 number) const inline
Get a ride type from the class.
Parameters
number Index of the ride type to retrieve.
Returns
The ride type, or nullptr if it does not exist.
Definition at line 210 of file ride_type.h.
References lengthof, and ride_types.
Referenced by RideSelectGui::DrawWidget(), RideSelectGui::OnClick(), RideSelectGui::SetNewRide(), ShopPlacementManager::SetSelection(), and RideSelectGui::UpdateWidgetSize().
The documentation for this class was generated from the following files:
ride_type.h
ride_type.cpp