FreeRCT: RcdFileCollection Class Reference
RcdFileCollection Class Reference
Collected RCD files.
#include <rcdfile.h>
Public Member Functions
void ScanDirectories ()
Scan directories, looking for RCD files to add.
void AddFile (const RcdFileInfo &rcd)
Check whether the new file is useful to store in the available RCD files.
Public Attributes
std::map< std::string,
RcdFileInfo > rcdfiles
Found unique RCD files, mapping of uri to the Rcd file information.
Private Member Functions
const char * ScanFileForMetaInfo (const char *fname)
Scan a file for Rcd meta-data, and add it to the collection if all is well.
Detailed Description
Collected RCD files.
Definition at line 31 of file rcdfile.h.
Member Function Documentation
void RcdFileCollection::ScanDirectories ()
Scan directories, looking for RCD files to add.
Definition at line 81 of file rcdfile.cpp.
References _rcd_paths, DirectoryReader::ClosePath(), MakeDirectoryReader(), DirectoryReader::NextFile(), DirectoryReader::OpenPath(), ScanFileForMetaInfo(), and StrEndsWith().
Referenced by freerct_main().
void RcdFileCollection::AddFile (const RcdFileInfo & rcd)
Check whether the new file is useful to store in the available RCD files.
Parameters
rcd New file to consider adding.
Definition at line 61 of file rcdfile.cpp.
References RcdFileInfo::build, rcdfiles, and RcdFileInfo::uri.
Referenced by ScanFileForMetaInfo().
const char * RcdFileCollection::ScanFileForMetaInfo (const char * fname) private
Scan a file for Rcd meta-data, and add it to the collection if all is well.
Parameters
fname Filename of the file to scan.
Returns
Error message, or nullptr if no error found.
Definition at line 139 of file rcdfile.cpp.
References AddFile(), RcdFileReader::CheckFileHeader(), GetString(), RcdFileReader::name, RcdFileReader::ReadBlockHeader(), RcdFileReader::size, and RcdFileReader::version.
Referenced by ScanDirectories().
The documentation for this class was generated from the following files:
rcdfile.h
rcdfile.cpp