FreeRCT: SpriteStorage Class Reference
SpriteStorage Class Reference
Sprites and sprite handling
Storage of all sprites for a single tile size.
#include <sprite_store.h>
Public Member Functions
SpriteStorage (uint16 size)
Storage constructor for a single size.
void RemoveAnimations (AnimationType anim_type, PersonType pers_type)
Remove any sprites that were loaded for the provided animation.
void AddAnimationSprites (AnimationSprites *an_spr)
Add an animation to the sprite manager.
void AddFence (Fence *fnc)
Add fence sprites.
const ImageData * GetSurfaceSprite (uint8 type, uint8 surf_spr, ViewOrientation orient) const
Get a ground sprite.
const ImageData * GetFenceSprite (FenceType type, TileEdge edge, TileSlope slope, ViewOrientation orient) const
Get a fence sprite.
const ImageData * GetPathSprite (uint8 type, uint8 slope, ViewOrientation orient) const
Get a path tile sprite.
const ImageData * GetCursorSprite (uint8 surf_spr, ViewOrientation orient) const
Get a mouse tile cursor sprite.
const ImageData * GetCornerSprite (uint8 surf_spr, ViewOrientation orient, ViewOrientation cursor) const
Get a mouse tile corner sprite.
const ImageData * GetArrowSprite (uint8 spr_num, ViewOrientation orient) const
Get an arrow for indicating the build direction of paths and tracks.
const ImageData * GetAnimationSprite (AnimationType anim_type, uint16 frame_index, PersonType pers_type, ViewOrientation view) const
Get a sprite of an animation.
Public Attributes
const uint16 size
Width of the tile.
SurfaceData surface [GTP_COUNT]
Surface data.
Foundation foundation [FDT_COUNT]
Foundation.
Platform platform
Platform block.
Support support
Support block.
TileSelection tile_select
Tile selection sprites.
TileCorners tile_corners
Tile corner sprites.
Fence * fence [FENCE_COUNT]
Available fence types.
Path path_sprites [PAT_COUNT]
Path sprites.
DisplayedObject build_arrows
Arrows displaying build direction of paths and tracks.
AnimationSpritesMap animations
Animation sprites ordered by animation type.
Protected Member Functions
void Clear ()
Clear all data from the storage.
Detailed Description
Storage of all sprites for a single tile size.
Note
The data does not belong to this class, it is managed by SpriteManager instead.
Definition at line 447 of file sprite_store.h.
Constructor & Destructor Documentation
SpriteStorage::SpriteStorage (uint16 _size)
Storage constructor for a single size.
Parameters
_size Width of the tile stored in this object.
Definition at line 1100 of file sprite_store.cpp.
References Clear(), fence, and FENCE_TYPE_COUNT.
Member Function Documentation
void SpriteStorage::RemoveAnimations (AnimationType anim_type, PersonType pers_type)
Remove any sprites that were loaded for the provided animation.
Parameters
anim_type Animation type to remove.
pers_type Person type to remove.
Definition at line 1122 of file sprite_store.cpp.
References AnimationSprites::anim_type, animations, and AnimationSprites::person_type.
Referenced by SpriteManager::Load().
void SpriteStorage::AddAnimationSprites (AnimationSprites * an_spr)
Add an animation to the sprite manager.
Parameters
an_spr Animation sprites to add.
Definition at line 1140 of file sprite_store.cpp.
References AnimationSprites::anim_type, animations, and AnimationSprites::width.
Referenced by SpriteManager::Load().
void SpriteStorage::AddFence (Fence * fnc)
Add fence sprites.
Parameters
fnc New fence sprites.
Precondition
Width of the fence sprites must match with size.
Definition at line 1151 of file sprite_store.cpp.
References fence, FENCE_TYPE_COUNT, Fence::type, and Fence::width.
Referenced by SpriteManager::Load().
const ImageData* SpriteStorage::GetSurfaceSprite (uint8 type, uint8 surf_spr, ViewOrientation orient) const inline
Get a ground sprite.
Parameters
type Type of surface.
surf_spr Surface sprite index.
orient Orientation.
Returns
Requested sprite if available.
Definition at line 463 of file sprite_store.h.
References _slope_rotation, SurfaceData::surface, and surface.
Referenced by SpriteCollector::CollectVoxel(), and PixelFinder::CollectVoxel().
const ImageData* SpriteStorage::GetFenceSprite (FenceType type, TileEdge edge, TileSlope slope, ViewOrientation orient) const inline
Get a fence sprite.
Parameters
type FenceType of fence.
edge The edge of the voxel.
slope The exploded slope of the voxel.
orient Orientation.
Returns
Requested sprite if available.
Definition at line 476 of file sprite_store.h.
References ComputeCornerHeight(), fence, Fence::sprites, and TSB_TOP.
Referenced by SpriteCollector::CollectVoxel(), and FenceBuildManager::SetCursors().
const ImageData* SpriteStorage::GetPathSprite (uint8 type, uint8 slope, ViewOrientation orient) const inline
Get a path tile sprite.
Parameters
type Type of path.
See also
PathType
Parameters
slope Slope of the path (in VOR_NORTH orientation).
orient Display orientation.
Returns
Requested sprite if available.
Todo:
[low] type is not used due to lack of other path types (sprites).
Definition at line 503 of file sprite_store.h.
References _path_rotation, path_sprites, and Path::sprites.
Referenced by SpriteCollector::CollectVoxel(), and PixelFinder::CollectVoxel().
const ImageData* SpriteStorage::GetCursorSprite (uint8 surf_spr, ViewOrientation orient) const inline
Get a mouse tile cursor sprite.
Parameters
surf_spr Surface sprite index.
orient Orientation.
Returns
Requested sprite if available.
Definition at line 514 of file sprite_store.h.
References _slope_rotation, TileSelection::surface, and tile_select.
Referenced by SpriteCollector::GetCursorSpriteAtPos().
const ImageData* SpriteStorage::GetCornerSprite (uint8 surf_spr, ViewOrientation orient, ViewOrientation cursor) const inline
Get a mouse tile corner sprite.
Parameters
surf_spr Surface sprite index.
orient Orientation (selected corner).
cursor Ground cursor orientation.
Returns
Requested sprite if available.
Definition at line 526 of file sprite_store.h.
References _slope_rotation, TileCorners::sprites, and tile_corners.
Referenced by SpriteCollector::GetCursorSpriteAtPos().
const ImageData* SpriteStorage::GetArrowSprite (uint8 spr_num, ViewOrientation orient) const inline
Get an arrow for indicating the build direction of paths and tracks.
Parameters
spr_num Sprite index.
orient Orientation of the view.
Returns
Requested arrow sprite if available.
Definition at line 537 of file sprite_store.h.
References build_arrows, and DisplayedObject::sprites.
Referenced by SpriteCollector::GetCursorSpriteAtPos(), and SpriteManager::GetTableSprite().
const ImageData* SpriteStorage::GetAnimationSprite (AnimationType anim_type, uint16 frame_index, PersonType pers_type, ViewOrientation view) const inline
Get a sprite of an animation.
Parameters
anim_type Type of animation to retrieve.
pers_type Type of person to retrieve.
frame_index Index of the frame to display.
view Orientation of the view.
Returns
The sprite, if it is available.
Todo:
[high] Pulling animations from a map for drawing sprites is too expensive.
Definition at line 551 of file sprite_store.h.
References AnimationSprites::anim_type, animations, AnimationSprites::person_type, and AnimationSprites::sprites.
Referenced by PixelFinder::CollectVoxel(), and Person::GetSprite().
void SpriteStorage::Clear () protected
Clear all data from the storage.
Definition at line 1112 of file sprite_store.cpp.
References animations.
Referenced by SpriteStorage().
The documentation for this class was generated from the following files:
sprite_store.h
sprite_store.cpp