FreeRCT: SpriteImage Class Reference
SpriteImage Class Reference
A Sprite.
#include <image.h>
Public Member Functions
const char * CopySprite (Image *img, int xoffset, int yoffset, int xpos, int ypos, int xsize, int ysize, bool crop)
Copy a part of the image as a sprite.
Public Attributes
int xoffset
Horizontal offset from the origin to the top-left pixel of the sprite image.
int yoffset
Vertical offset from the origin to the top-left pixel of the sprite image.
int width
Width of the image.
int height
Number of rows of the image.
const char * block_name
Name of the block to write.
int block_version
Version number of the block to write.
uint8 * data
Compressed image data.
int data_size
Size of the data field.
Detailed Description
A Sprite.
Definition at line 112 of file image.h.
Member Function Documentation
const char * SpriteImage::CopySprite (Image * img, int xoffset, int yoffset, int xpos, int ypos, int xsize, int ysize, bool crop)
Copy a part of the image as a sprite.
Parameters
img Image source.
xoffset Horizontal offset of the origin to the top-left pixel of the sprite.
yoffset Vertical offset of the origin to the top-left pixel of the sprite.
xpos Left position of the sprite in the image.
ypos Top position of the sprite in the image.
xsize Width of the sprite in the image.
ysize Height of the sprite in the image.
crop Perform cropping of the sprite.
Returns
Error message if the conversion failed, else nullptr.
Definition at line 732 of file image.cpp.
References Image::block_name, block_name, Image::block_version, block_version, data, data_size, Image::Encode(), Image::GetHeight(), Image::GetWidth(), height, Image::IsEmpty(), width, xoffset, and yoffset.
The documentation for this class was generated from the following files:
image.h
image.cpp