FreeRCT: GameModeManager Class Reference
GameModeManager Class Reference
Class managing the game mode of the program.
#include <gamemode.h>
Public Member Functions
void SetGameMode (GameMode new_mode)
Change game mode of the program.
GameMode GetGameMode () const
Get current game mode.
bool InPlayMode () const
Checks if the current game mode is GM_PLAY.
bool InEditorMode () const
Checks if the current game mode is GM_EDITOR.
Private Attributes
GameMode game_mode
Current game mode of the program.
Detailed Description
Class managing the game mode of the program.
Definition at line 27 of file gamemode.h.
Member Function Documentation
void GameModeManager::SetGameMode (GameMode new_mode)
Change game mode of the program.
Parameters
new_mode New mode to use.
Definition at line 31 of file gamemode.cpp.
References CHG_UPDATE_BUTTONS, game_mode, NotifyChange(), and WC_TOOLBAR.
Referenced by ToolbarWindow::OnClick(), ShutdownGame(), and StartNewGame().
GameMode GameModeManager::GetGameMode () const inline
Get current game mode.
Returns
Current game mode.
Definition at line 45 of file gamemode.h.
References game_mode.
Referenced by GetSwitchGameModeString().
bool GameModeManager::InPlayMode () const inline
Checks if the current game mode is GM_PLAY.
Returns
true if current game mode is GM_PLAY.
Definition at line 54 of file gamemode.h.
References game_mode, and GM_PLAY.
Referenced by BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), CanBuildPathFromEdge(), TerrainChanges::ChangeCorner(), ChangeTileCursorMode(), PathBuildManager::MoveCursor(), FenceBuildManager::OnMouseButtonEvent(), and RemovePath().
bool GameModeManager::InEditorMode () const inline
Checks if the current game mode is GM_EDITOR.
Returns
true if current game mode is GM_EDITOR.
Definition at line 63 of file gamemode.h.
References game_mode, and GM_EDITOR.
Referenced by ChangeAreaCursorMode(), and ToolbarWindow::OnClick().
The documentation for this class was generated from the following files:
gamemode.h
gamemode.cpp