FreeRCT: VoxelCollector Class Reference
VoxelCollector Class Reference abstract
%Window code » %Viewport (main display) code and data
Search the world for voxels to render.
Public Member Functions
VoxelCollector (Viewport *vp, bool draw_above_stack)
Base class constructor.
void SetWindowSize (int16 xpos, int16 ypos, uint16 width, uint16 height)
Set screen area of interest (relative to the (xview, yview, and zview position).
void Collect (bool use_additions)
Perform the collecting cycle.
int32 ComputeX (int32 x, int32 y)
Convert 3D position to the horizontal 2D position.
int32 ComputeY (int32 x, int32 y, int32 z)
Convert 3D position to the vertical 2D position.
Public Attributes
int32 xview
X position of the centre point of the display.
int32 yview
Y position of the centre point of the display.
int32 zview
Z position of the centre point of the display.
uint16 tile_width
Width of a tile.
uint16 tile_height
Height of a tile.
ViewOrientation orient
Direction of view.
const SpriteStorage * sprites
Sprite collection of the right size.
Viewport * vp
Parent viewport for accessing the cursors if not nullptr.
bool draw_above_stack
Also draw voxels above the voxel stack (for cursors).
Rectangle32 rect
Screen area of interest.
Protected Member Functions
virtual void SetupSupports (const VoxelStack *stack, uint xpos, uint ypos)
Decide where supports should be raised.
virtual void CollectVoxel (const Voxel *vx, int xpos, int ypos, int zpos, int32 xnorth, int32 ynorth)=0
Handle a voxel that should be collected.
Detailed Description
Search the world for voxels to render.
Definition at line 158 of file viewport.cpp.
Constructor & Destructor Documentation
VoxelCollector::VoxelCollector (Viewport * vp, bool draw_above_stack)
Base class constructor.
Parameters
vp Viewport querying the voxel information.
draw_above_stack Also visit the cursors above a voxel stack.
Todo:
Can we remove some variables, as vp is stored now as well?
Definition at line 313 of file viewport.cpp.
References _sprite_manager, draw_above_stack, SpriteManager::GetSprites(), orient, Viewport::orientation, sprites, tile_height, Viewport::tile_height, tile_width, Viewport::tile_width, vp, xview, Viewport::xview, yview, Viewport::yview, zview, and Viewport::zview.
Member Function Documentation
void VoxelCollector::SetWindowSize (int16 xpos, int16 ypos, uint16 width, uint16 height)
Set screen area of interest (relative to the (xview, yview, and zview position).
Parameters
xpos Horizontal position of the top-left corner.
ypos Vertical position of the top-left corner.
width Width of the area.
height Height of the area.
Definition at line 340 of file viewport.cpp.
References Rectangle< PT, SZ >::base, ComputeX(), ComputeY(), Rectangle< PT, SZ >::height, rect, Rectangle< PT, SZ >::width, Point< CT >::x, xview, Point< CT >::y, yview, and zview.
Referenced by Viewport::ComputeCursorPosition(), and Viewport::OnDraw().
void VoxelCollector::Collect (bool use_additions)
Perform the collecting cycle.
This part walks over the voxels, and call CollectVoxel for each useful voxel. A derived class may then inspect the voxel in more detail.
Parameters
use_additions Use the _additions voxels for drawing.
Todo:
Do this less stupid. Walking the whole world is not going to work in general.
Definition at line 355 of file viewport.cpp.
References _world, Rectangle< PT, SZ >::base, VoxelStack::base, CollectVoxel(), ComputeX(), ComputeY(), draw_above_stack, Viewport::GetMaxCursorHeight(), VoxelWorld::GetStack(), WorldAdditions::GetStack(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), VoxelStack::height, orient, rect, SetupSupports(), tile_height, tile_width, VOR_EAST, VOR_SOUTH, VOR_WEST, VoxelStack::voxels, vp, Point< CT >::x, and Point< CT >::y.
Referenced by Viewport::ComputeCursorPosition().
int32 VoxelCollector::ComputeX (int32 x, int32 y) inline
Convert 3D position to the horizontal 2D position.
Parameters
x X position in the game world.
y Y position in the game world.
Returns
X position in 2D.
Definition at line 173 of file viewport.cpp.
References ComputeXFunction(), orient, and tile_width.
Referenced by Collect(), SpriteCollector::CollectVoxel(), PixelFinder::CollectVoxel(), and SetWindowSize().
int32 VoxelCollector::ComputeY (int32 x, int32 y, int32 z) inline
Convert 3D position to the vertical 2D position.
Parameters
x X position in the game world.
y Y position in the game world.
z Z position in the game world.
Returns
Y position in 2D.
Definition at line 185 of file viewport.cpp.
References ComputeYFunction(), orient, tile_height, and tile_width.
Referenced by Collect(), SpriteCollector::CollectVoxel(), PixelFinder::CollectVoxel(), and SetWindowSize().
virtual void VoxelCollector::SetupSupports (const VoxelStack * stack, uint xpos, uint ypos) inline protected virtual
Decide where supports should be raised.
Parameters
stack Voxel stack to examine.
xpos X position of the voxel stack.
ypos Y position of the voxel stack.
Reimplemented in SpriteCollector.
Definition at line 210 of file viewport.cpp.
Referenced by Collect().
virtual void VoxelCollector::CollectVoxel (const Voxel * vx, int xpos, int ypos, int zpos, int32 xnorth, int32 ynorth) protected pure virtual
Handle a voxel that should be collected.
Parameters
vx Voxel to add, nullptr means 'cursor above stack'.
xpos X world position.
ypos Y world position.
zpos Z world position.
xnorth X coordinate of the north corner at the display.
ynorth y coordinate of the north corner at the display.
Note
Implement in a derived class.
Implemented in PixelFinder, and SpriteCollector.
Referenced by Collect().
The documentation for this class was generated from the following file:
viewport.cpp