FreeRCT: VoxelStack Class Reference
VoxelStack Class Reference
World map data and code
One column of voxels.
#include <map.h>
Public Member Functions
VoxelStack ()
Default constructor.
~VoxelStack ()
Destructor.
void Clear ()
Remove the stack.
const Voxel * Get (int16 z) const
Get a voxel in the world by voxel coordinate.
Voxel * GetCreate (int16 z, bool create)
Get a voxel in the world by voxel coordinate.
VoxelStack * Copy (bool copyPersons) const
Make a copy of self.
void MoveStack (VoxelStack *old_stack)
Move a voxel stack to this world.
int GetGroundOffset () const
Get the offset of ground in the voxel stack.
void Save (Saver &svr) const
Save a voxel stack to the save game file.
void Load (Loader &ldr)
Load a voxel stack from the save game file.
Public Attributes
Voxel * voxels
Voxel array at this stack.
int16 base
Height of the bottom voxel.
uint16 height
Number of voxels in the stack.
TileOwner owner
Ownership of the base tile of this voxel stack.
Protected Member Functions
bool MakeVoxelStack (int16 new_base, uint16 new_height)
(Re)Allocate a voxel stack.
Detailed Description
One column of voxels.
Definition at line 462 of file map.h.
Constructor & Destructor Documentation
VoxelStack::VoxelStack ()
Default constructor.
Definition at line 149 of file map.cpp.
References base, height, and voxels.
Referenced by Copy().
VoxelStack::~VoxelStack ()
Destructor.
Definition at line 157 of file map.cpp.
References voxels.
Member Function Documentation
void VoxelStack::Clear ()
Remove the stack.
Definition at line 163 of file map.cpp.
References base, height, OWN_NONE, owner, and voxels.
Referenced by Load(), and VoxelWorld::SetWorldSize().
const Voxel * VoxelStack::Get (int16 z) const
Get a voxel in the world by voxel coordinate.
Parameters
z Z coordinate of the voxel.
Returns
Address of the voxel (if it exists or could be created).
Definition at line 216 of file map.cpp.
References base, height, voxels, and WORLD_Z_SIZE.
Referenced by BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), Guest::DecideMoveDirection(), VoxelWorld::GetVoxel(), WorldAdditions::GetVoxel(), TerrainChanges::ModifyWorld(), and RemovePath().
Voxel * VoxelStack::GetCreate (int16 z, bool create)
Get a voxel in the world by voxel coordinate.
Create one if needed.
Parameters
z Z coordinate of the voxel.
create If the requested voxel does not exist, try to create it.
Returns
Address of the voxel (if it exists or could be created).
Definition at line 234 of file map.cpp.
References base, height, MakeVoxelStack(), voxels, and WORLD_Z_SIZE.
Referenced by BuildPathAtTile(), VoxelWorld::GetCreateVoxel(), WorldAdditions::GetCreateVoxel(), TerrainChanges::ModifyWorld(), FenceBuildManager::OnMouseButtonEvent(), RemovePathAtTile(), SetFoundations(), and UpdateLandBorderFence().
VoxelStack * VoxelStack::Copy (bool copyPersons) const
Make a copy of self.
Parameters
copyPersons Copy the person list too.
Returns
The copied structure.
Definition at line 201 of file map.cpp.
References base, CopyStackData(), height, MakeVoxelStack(), voxels, and VoxelStack().
Referenced by WorldAdditions::GetModifyStack().
void VoxelStack::MoveStack (VoxelStack * vs)
Move a voxel stack to this world.
May destroy the original stack in the process.
Parameters
vs Source stack.
Definition at line 328 of file map.cpp.
References base, CopyStackData(), CopyVoxelObjectList(), Voxel::HasVoxelObjects(), height, Voxel::IsEmpty(), MakeNewVoxels(), and voxels.
Referenced by VoxelWorld::MoveStack().
int VoxelStack::GetGroundOffset () const
Get the offset of ground in the voxel stack.
Returns
Index in the voxel array for the voxel containing the ground.
Definition at line 383 of file map.cpp.
References Voxel::GetGroundSlope(), Voxel::GetGroundType(), GTP_INVALID, height, IsImplodedSteepSlopeTop(), NOT_REACHED, and voxels.
Referenced by VoxelWorld::GetGroundHeight(), and GetParkEntryDirection().
void VoxelStack::Save (Saver & svr) const
Save a voxel stack to the save game file.
Parameters
svr Output stream to write.
Definition at line 422 of file map.cpp.
References base, Saver::EndBlock(), height, owner, Saver::PutByte(), Saver::PutWord(), Saver::StartBlock(), and voxels.
Referenced by VoxelWorld::Save().
void VoxelStack::Load (Loader & ldr)
Load a voxel stack from the save game file.
Parameters
ldr Input stream to read.
Definition at line 396 of file map.cpp.
References base, Clear(), Loader::CloseBlock(), Loader::GetByte(), Loader::GetWord(), height, MakeNewVoxels(), Loader::OpenBlock(), OWN_COUNT, owner, Loader::SetFailMessage(), voxels, and WORLD_Z_SIZE.
Referenced by VoxelWorld::Load().
bool VoxelStack::MakeVoxelStack (int16 new_base, uint16 new_height) protected
(Re)Allocate a voxel stack.
Parameters
new_base New base voxel height.
new_height New number of voxels in the stack.
Returns
New stack could be created.
Note
The old stack must fit in the new stack.
Todo:
If contents of a voxel is cleared, it might be released from the stack. Currently that is never done.
Definition at line 180 of file map.cpp.
References base, CopyStackData(), height, MakeNewVoxels(), voxels, and WORLD_Z_SIZE.
Referenced by Copy(), and GetCreate().
The documentation for this class was generated from the following files:
map.h
map.cpp