FreeRCT: PathSearcher Class Reference
PathSearcher Class Reference
Class for searching (and hopefully finding) a path between tiles.
#include <path_finding.h>
Public Member Functions
PathSearcher (int dest_x, int dest_y, int dest_z)
Constructor, find a path to (dest_x, dest_y, dest_z).
void AddStart (int start_x, int start_y, int start_z)
Add a starting point to the searcher.
bool Search ()
Search for a path to the destination.
void Clear ()
Clear the used data structures of the path searcher.
Public Attributes
int dest_x
X coordinate of the desired destination voxel.
int dest_y
Y coordinate of the desired destination voxel.
int dest_z
Z coordinate of the desired destination voxel.
const WalkedPosition * dest_pos
If path was found, this points to the end-point of the walk.
Protected Member Functions
uint32 GetEstimate (int x, int y, int z)
Get an (optimistic) estimate of the path length to go to the destination voxel.
void AddOpen (int x, int y, int z, uint32 traveled, const WalkedPosition *prev_pos)
Add a new open position to the set of open points, if it is better than already available.
Protected Attributes
PositionSet positions
Examined positions.
OpenPoints open_points
Open points to examine further.
Detailed Description
Class for searching (and hopefully finding) a path between tiles.
Definition at line 44 of file path_finding.h.
Constructor & Destructor Documentation
PathSearcher::PathSearcher (int dest_x, int dest_y, int dest_z)
Constructor, find a path to (dest_x, dest_y, dest_z).
Give starting points through PathSearcher::AddStart.
Parameters
dest_x X coordinate of the destination voxel.
dest_y Y coordinate of the destination voxel.
dest_z Z coordinate of the destination voxel.
Definition at line 73 of file path_finding.cpp.
References dest_pos, dest_x, dest_y, and dest_z.
Member Function Documentation
void PathSearcher::AddStart (int start_x, int start_y, int start_z)
Add a starting point to the searcher.
Parameters
start_x X coordinate of the start voxel.
start_y Y coordinate of the start voxel.
start_z Z coordinate of the start voxel.
Definition at line 87 of file path_finding.cpp.
References AddOpen().
Referenced by GetParkEntryDirection().
bool PathSearcher::Search ()
Search for a path to the destination.
Returns
Whether a path has been found.
Definition at line 141 of file path_finding.cpp.
References _tile_dxy, _world, AddOpen(), dest_pos, EDGE_BEGIN, EDGE_COUNT, WalkedPosition::estimate, WalkedDistance::estimate, GetPathExits(), VoxelWorld::GetVoxel(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), open_points, WalkedDistance::pos, WalkedPosition::traveled, WalkedDistance::traveled, WORLD_Z_SIZE, WalkedPosition::x, Point< CT >::x, WalkedPosition::y, Point< CT >::y, and WalkedPosition::z.
Referenced by GetParkEntryDirection().
void PathSearcher::Clear ()
Clear the used data structures of the path searcher.
Definition at line 196 of file path_finding.cpp.
References dest_pos, open_points, and positions.
uint32 PathSearcher::GetEstimate (int x, int y, int z) inline protected
Get an (optimistic) estimate of the path length to go to the destination voxel.
Parameters
x Current x position in voxels.
y Current y position in voxels.
z Current z position in voxels.
Returns
Estimate of the length of path still to go.
Definition at line 99 of file path_finding.cpp.
References dest_x, dest_y, and dest_z.
Referenced by AddOpen().
void PathSearcher::AddOpen (int x, int y, int z, uint32 traveled, const WalkedPosition * prev_pos) protected
Add a new open position to the set of open points, if it is better than already available.
Parameters
x X position of the current position.
y Y position of the current position.
z Z position of the current position.
traveled Distance traveled to get to the current position.
prev_pos Previous position (nullptr for the start position).
Definition at line 114 of file path_finding.cpp.
References WalkedPosition::estimate, GetEstimate(), open_points, positions, WalkedPosition::prev_pos, and WalkedPosition::traveled.
Referenced by AddStart(), and Search().
The documentation for this class was generated from the following files:
path_finding.h
path_finding.cpp