FreeRCT: Loader Class Reference
Loader Class Reference
Class for loading a save game.
#include <loadsave.h>
Public Member Functions
Loader (FILE *fp)
Constructor of the loader class.
uint32 OpenBlock (const char *name, bool may_fail=false)
Test whether a block with the given name is being opened.
void CloseBlock ()
Test whether the current block is closed.
uint8 GetByte ()
Get the next byte from the stream (or the cache).
uint16 GetWord ()
Get the next word from the stream (or the cache).
uint32 GetLong ()
Get the next long word from the stream (or the cache).
uint64 GetLongLong ()
Get the next long long word from the stream (or the cache).
void SetFailMessage (const char *fail_msg)
Denote loading as being failed.
const char * GetFailMessage () const
Get the failure message of the loader.
bool IsFail () const
Has loading failed?
Private Member Functions
void PutByte (uint8 val)
Put a byte in the temporary cache.
Private Attributes
const char * fail_msg
If not nullptr, message of failure.
const char * blk_name
Name of the current block.
FILE * fp
Data stream being loaded.
int cache_count
Number of values in cache.
uint8 cache [8]
Stack with temporary values to return on next read.
Detailed Description
Class for loading a save game.
Definition at line 16 of file loadsave.h.
Constructor & Destructor Documentation
Loader::Loader (FILE * fp)
Constructor of the loader class.
Parameters
fp Input file stream. Use nullptr for initialization to default.
Definition at line 22 of file loadsave.cpp.
References blk_name, cache_count, fail_msg, and fp.
Member Function Documentation
uint32 Loader::OpenBlock (const char * name, bool may_fail = false)
Test whether a block with the given name is being opened.
Parameters
name Name of the expected block.
may_fail Whether it is allowed not to find the expected block.
Returns
Version number of the found block, 0 for default initialization, UINT32_MAX for failing to find the block (only if may_fail was set).
Note
If the block was not found, bytes already read of the block name are pushed back onto the stream.
Definition at line 37 of file loadsave.cpp.
References blk_name, fp, GetByte(), GetLong(), IsFail(), PutByte(), SetFailMessage(), and UINT32_MAX.
Referenced by Random::Load(), FinancesManager::Load(), VoxelStack::Load(), VoxelWorld::Load(), LoadDate(), and LoadElements().
void Loader::CloseBlock ()
Test whether the current block is closed.
Definition at line 70 of file loadsave.cpp.
References blk_name, fp, GetByte(), IsFail(), and SetFailMessage().
Referenced by Random::Load(), FinancesManager::Load(), VoxelStack::Load(), VoxelWorld::Load(), LoadDate(), and LoadElements().
uint8 Loader::GetByte ()
Get the next byte from the stream (or the cache).
Returns
The read next byte.
Definition at line 86 of file loadsave.cpp.
References cache, cache_count, fp, IsFail(), and SetFailMessage().
Referenced by CloseBlock(), GetWord(), FinancesManager::Load(), Voxel::Load(), VoxelStack::Load(), and OpenBlock().
uint16 Loader::GetWord ()
Get the next word from the stream (or the cache).
Returns
The read next word.
Definition at line 118 of file loadsave.cpp.
References GetByte().
Referenced by GetLong(), Voxel::Load(), VoxelStack::Load(), and VoxelWorld::Load().
uint32 Loader::GetLong ()
Get the next long word from the stream (or the cache).
Returns
The read next long word.
Definition at line 129 of file loadsave.cpp.
References GetWord().
Referenced by GetLongLong(), Random::Load(), Voxel::Load(), LoadDate(), and OpenBlock().
uint64 Loader::GetLongLong ()
Get the next long long word from the stream (or the cache).
Returns
The read next long long word.
Definition at line 140 of file loadsave.cpp.
References GetLong().
Referenced by Finances::Load(), and FinancesManager::Load().
void Loader::SetFailMessage (const char * fail_msg)
Denote loading as being failed.
Parameters
fail_msg Message to explain what failed. Caller must preserve the message text.
Note
Message is mostly for internal and debugging use.
Definition at line 152 of file loadsave.cpp.
References fail_msg, and IsFail().
Referenced by CloseBlock(), GetByte(), Finances::Load(), FinancesManager::Load(), Voxel::Load(), VoxelStack::Load(), VoxelWorld::Load(), LoadDate(), LoadElements(), and OpenBlock().
const char * Loader::GetFailMessage () const
Get the failure message of the loader.
Returns
Message why loading failed.
Note
Message is mostly for internal and debugging use.
Definition at line 163 of file loadsave.cpp.
References fail_msg.
bool Loader::IsFail () const
Has loading failed?
Returns
Whether loading has failed.
Definition at line 172 of file loadsave.cpp.
References fail_msg.
Referenced by CloseBlock(), GetByte(), VoxelWorld::Load(), LoadGame(), OpenBlock(), PutByte(), and SetFailMessage().
void Loader::PutByte (uint8 val) private
Put a byte in the temporary cache.
Parameters
val Value to save.
Definition at line 106 of file loadsave.cpp.
References cache, cache_count, IsFail(), and lengthof.
Referenced by OpenBlock().
The documentation for this class was generated from the following files:
loadsave.h
loadsave.cpp