FreeRCT: SpriteCollector Class Reference
SpriteCollector Class Reference
%Window code » %Viewport (main display) code and data
Collect sprites to draw in a viewport.
Public Member Functions
SpriteCollector (Viewport *vp, bool enable_cursors)
Constructor of sprites collector.
void SetXYOffset (int16 xoffset, int16 yoffset)
Set the offset of the top-left coordinate of the collect window to the top-left of the display.
void SetWindowSize (int16 xpos, int16 ypos, uint16 width, uint16 height)
Set screen area of interest (relative to the (Viewport::view_pos position).
void Collect (bool use_additions)
Perform the collecting cycle.
int32 ComputeX (int32 x, int32 y)
Convert 3D position to the horizontal 2D position.
int32 ComputeY (int32 x, int32 y, int32 z)
Convert 3D position to the vertical 2D position.
Public Attributes
DrawImages draw_images
Sprites to draw ordered by viewing distance.
int16 xoffset
Horizontal offset of the top-left coordinate to the top-left of the display.
int16 yoffset
Vertical offset of the top-left coordinate to the top-left of the display.
bool enable_cursors
Enable cursor drawing.
XYZPoint32 view_pos
Position of the centre point of the display.
uint16 tile_width
Width of a tile.
uint16 tile_height
Height of a tile.
ViewOrientation orient
Direction of view.
const SpriteStorage * sprites
Sprite collection of the right size.
Viewport * vp
Parent viewport for accessing the cursors if not nullptr.
bool draw_above_stack
Also draw voxels above the voxel stack (for cursors).
bool underground_mode
Whether to draw underground mode sprites (else draw normal surface sprites).
Rectangle32 rect
Screen area of interest.
Protected Member Functions
void CollectVoxel (const Voxel *vx, const XYZPoint16 &voxel_pos, int32 xnorth, int32 ynorth) override
Add all sprites of the voxel to the set of sprites to draw.
void SetupSupports (const VoxelStack *stack, uint xpos, uint ypos) override
Decide where supports should be raised.
const ImageData * GetCursorSpriteAtPos (const XYZPoint16 &voxel_pos, uint8 tslope, uint8 &yoffset)
Get the cursor sprite at a given voxel.
Protected Attributes
Point16 north_offsets [4]
For each orientation the location of the real northern corner of a tile relative to the northern displayed corner.
uint16 ground_height
The height of the ground in the current voxel stack. -1 means no valid ground found.
uint8 ground_slope
Imploded ground slope if ground_height is valid.
Detailed Description
Collect sprites to draw in a viewport.
Definition at line 260 of file viewport.cpp.
Constructor & Destructor Documentation
SpriteCollector::SpriteCollector (Viewport * vp, bool enable_cursors)
Constructor of sprites collector.
Parameters
vp Viewport that needs the sprites.
enable_cursors Also collect cursors.
Definition at line 440 of file viewport.cpp.
References draw_images, enable_cursors, north_offsets, VoxelCollector::tile_width, VOR_EAST, VOR_NORTH, VOR_SOUTH, VOR_WEST, Point< CT >::x, xoffset, Point< CT >::y, and yoffset.
Member Function Documentation
void SpriteCollector::SetXYOffset (int16 xoffset, int16 yoffset)
Set the offset of the top-left coordinate of the collect window to the top-left of the display.
Parameters
xoffset Horizontal offset.
yoffset Vertical offset.
Definition at line 462 of file viewport.cpp.
References xoffset, and yoffset.
void SpriteCollector::CollectVoxel (const Voxel * voxel, const XYZPoint16 & voxel_pos, int32 xnorth, int32 ynorth) override protected virtual
Add all sprites of the voxel to the set of sprites to draw.
Parameters
voxel Voxel to add, nullptr means 'cursor above stack'.
voxel_pos World position.
xnorth X coordinate of the north corner at the display.
ynorth y coordinate of the north corner at the display.
Todo:
Can we gain time by checking for cursors once at every voxel stack, and only test every zpos when there is one in a stack?
Implements VoxelCollector.
Definition at line 864 of file viewport.cpp.
References _path_rotation, DrawData::base, Rectangle< PT, SZ >::base, ComputeCornerHeight(), VoxelCollector::ComputeX(), VoxelCollector::ComputeY(), draw_images, DrawRide(), EDGE_BEGIN, EDGE_COUNT, EDGE_SW, ExpandTileSlope(), FDT_GROUND, FDT_INVALID, FENCE_TYPE_INVALID, Platform::flat, SpriteStorage::foundation, GB(), GetCursorSpriteAtPos(), SpriteStorage::GetFenceSprite(), Voxel::GetFenceType(), Voxel::GetFoundationSlope(), Voxel::GetFoundationType(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), GetImplodedPathSlope(), Voxel::GetInstance(), Voxel::GetInstanceData(), SpriteStorage::GetPathSprite(), GetPathType(), VoxelObject::GetSprite(), SpriteStorage::GetSurfaceSprite(), ground_height, ground_slope, GTP_INVALID, GTP_UNDERGROUND, HasValidPath(), DrawData::level, VoxelObject::next_object, north_offsets, NOT_REACHED, DrawData::order, VoxelCollector::orient, PATH_FLAT_COUNT, PATH_INVALID, PATH_RAMP_NE, PATH_RAMP_NW, PATH_RAMP_SE, PATH_RAMP_SW, VoxelObject::pix_pos, SpriteStorage::platform, Platform::ramp, DrawData::recolour, VoxelCollector::rect, SL_FLAT, SO_CURSOR, SO_FENCE_BACK, SO_FENCE_FRONT, SO_FOUNDATION, SO_GROUND, SO_PATH, SO_PERSON, SO_PLATFORM, SO_SUPPORT, DrawData::sprite, Foundation::sprites, Support::sprites, VoxelCollector::sprites, SRI_FULL_RIDES, SRI_PATH, SSP_FLAT_DOUBLE_NS, SSP_FLAT_SINGLE_NS, SSP_NONFLAT_BASE, SSP_STEEP_N, SpriteStorage::support, VoxelCollector::tile_height, Viewport::tile_height, TSB_NORTHEAST, TSB_NORTHWEST, TSB_SOUTHEAST, TSB_SOUTHWEST, TSB_STEEP, TSB_TOP, VoxelCollector::underground_mode, VOR_EAST, VOR_NORTH, VOR_SOUTH, VOR_WEST, Voxel::voxel_objects, VoxelCollector::vp, Point< CT >::x, XYZPoint< CT >::x, xoffset, Point< CT >::y, XYZPoint< CT >::y, yoffset, XYZPoint< CT >::z, and DrawData::z_height.
void SpriteCollector::SetupSupports (const VoxelStack * stack, uint xpos, uint ypos) override protected virtual
Decide where supports should be raised.
Parameters
stack Voxel stack to examine.
xpos X position of the voxel stack.
ypos Y position of the voxel stack.
Reimplemented from VoxelCollector.
Definition at line 800 of file viewport.cpp.
References _slope_rotation, VoxelStack::base, Voxel::GetGroundSlope(), Voxel::GetGroundType(), Voxel::GetInstance(), ground_height, ground_slope, GTP_INVALID, VoxelStack::height, VoxelCollector::orient, SRI_FREE, and VoxelStack::voxels.
const ImageData * SpriteCollector::GetCursorSpriteAtPos (const XYZPoint16 & voxel_pos, uint8 tslope, uint8 & yoffset) protected
Get the cursor sprite at a given voxel.
Parameters
voxel_pos Position of the voxel being drawn.
tslope Slope of the tile.
yoffset Offset in screen y coordinates for where to render the sprite related to given voxel.
Returns
Pointer to the cursor sprite, or nullptr if no cursor available.
Definition at line 759 of file viewport.cpp.
References CUR_TYPE_ARROW_NE, CUR_TYPE_ARROW_NW, CUR_TYPE_ARROW_SE, CUR_TYPE_ARROW_SW, CUR_TYPE_EAST, CUR_TYPE_EDGE_NE, CUR_TYPE_EDGE_NW, CUR_TYPE_EDGE_SE, CUR_TYPE_EDGE_SW, CUR_TYPE_NORTH, CUR_TYPE_SOUTH, CUR_TYPE_TILE, CUR_TYPE_WEST, Viewport::edge_cursor, enable_cursors, SpriteStorage::GetArrowSprite(), SpriteStorage::GetCornerSprite(), Viewport::GetCursorAtPos(), SpriteStorage::GetCursorSprite(), GetViewport(), VoxelCollector::orient, EdgeCursor::sprite, VoxelCollector::sprites, SubtractOrientations(), VoxelCollector::vp, and EdgeCursor::yoffset.
Referenced by CollectVoxel().
void VoxelCollector::SetWindowSize (int16 xpos, int16 ypos, uint16 width, uint16 height) inherited
Set screen area of interest (relative to the (Viewport::view_pos position).
Parameters
xpos Horizontal position of the top-left corner.
ypos Vertical position of the top-left corner.
width Width of the area.
height Height of the area.
Definition at line 335 of file viewport.cpp.
References Rectangle< PT, SZ >::base, VoxelCollector::ComputeX(), VoxelCollector::ComputeY(), Rectangle< PT, SZ >::height, VoxelCollector::rect, VoxelCollector::view_pos, Rectangle< PT, SZ >::width, Point< CT >::x, XYZPoint< CT >::x, and Point< CT >::y.
Referenced by Viewport::ComputeCursorPosition(), and Viewport::OnDraw().
void VoxelCollector::Collect (bool use_additions) inherited
Perform the collecting cycle.
This part walks over the voxels, and call CollectVoxel for each useful voxel. A derived class may then inspect the voxel in more detail.
Parameters
use_additions Use the _additions voxels for drawing.
Todo:
Do this less stupid. Walking the whole world is not going to work in general.
Definition at line 350 of file viewport.cpp.
References _world, Rectangle< PT, SZ >::base, VoxelStack::base, VoxelCollector::CollectVoxel(), VoxelCollector::ComputeX(), VoxelCollector::ComputeY(), VoxelCollector::draw_above_stack, Viewport::GetMaxCursorHeight(), VoxelWorld::GetStack(), WorldAdditions::GetStack(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), VoxelStack::height, VoxelCollector::orient, VoxelCollector::rect, VoxelCollector::SetupSupports(), VoxelCollector::tile_height, VoxelCollector::tile_width, VOR_EAST, VOR_SOUTH, VOR_WEST, VoxelStack::voxels, VoxelCollector::vp, Point< CT >::x, and Point< CT >::y.
Referenced by Viewport::ComputeCursorPosition().
int32 VoxelCollector::ComputeX (int32 x, int32 y) inline inherited
Convert 3D position to the horizontal 2D position.
Parameters
x X position in the game world.
y Y position in the game world.
Returns
X position in 2D.
Definition at line 173 of file viewport.cpp.
References ComputeXFunction(), VoxelCollector::orient, and VoxelCollector::tile_width.
Referenced by VoxelCollector::Collect(), CollectVoxel(), PixelFinder::CollectVoxel(), and VoxelCollector::SetWindowSize().
int32 VoxelCollector::ComputeY (int32 x, int32 y, int32 z) inline inherited
Convert 3D position to the vertical 2D position.
Parameters
x X position in the game world.
y Y position in the game world.
z Z position in the game world.
Returns
Y position in 2D.
Definition at line 185 of file viewport.cpp.
References ComputeYFunction(), VoxelCollector::orient, VoxelCollector::tile_height, and VoxelCollector::tile_width.
Referenced by VoxelCollector::Collect(), CollectVoxel(), PixelFinder::CollectVoxel(), and VoxelCollector::SetWindowSize().
Member Data Documentation
Point16 SpriteCollector::north_offsets[4] protected
For each orientation the location of the real northern corner of a tile relative to the northern displayed corner.
Definition at line 278 of file viewport.cpp.
Referenced by CollectVoxel(), and SpriteCollector().
The documentation for this class was generated from the following file:
viewport.cpp