FreeRCT: Finances Class Reference
Finances Class Reference
Finances data and code.
Tracking monthly finances.
#include <finances.h>
Public Member Functions
Finances ()
Default constructor.
~Finances ()
Destructor.
void Reset ()
Resets the finance categories to 0.
Money GetTotal () const
Total the categories.
void Load (Loader &ldr, uint32 version)
Load all monies of one month.
void Save (Saver &svr)
Save all monies of one month.
Public Attributes
Money ride_construct
Monthly expenditures for ride construction (value is negative).
Money ride_running
Monthly expenditures for ride running costs (value is negative).
Money land_purchase
Monthly expenditures for land purchase (value is negative).
Money landscaping
Monthly expenditures for landscaping (value is negative).
Money park_tickets
Monthly earnings for park tickets.
Money ride_tickets
Monthly earnings for ride tickets.
Money shop_sales
Monthly earnings for shop sales.
Money shop_stock
Monthly expenditures for shop stock (value is negative).
Money food_sales
Monthly earnings for food sales.
Money food_stock
Monthly expenditures for food stock (value is negative).
Money staff_wages
Monthly expenditures for staff wages (value is negative).
Money marketing
Monthly expenditures for marketing (value is negative).
Money research
Monthly expenditures for research (value is negative).
Money loan_interest
Monthly expenditures for loan interest (value is negative).
Detailed Description
Tracking monthly finances.
Definition at line 24 of file finances.h.
Constructor & Destructor Documentation
Finances::Finances ()
Default constructor.
Definition at line 24 of file finances.cpp.
References Reset().
Finances::~Finances ()
Destructor.
Definition at line 30 of file finances.cpp.
Member Function Documentation
void Finances::Reset ()
Resets the finance categories to 0.
Definition at line 35 of file finances.cpp.
References food_sales, food_stock, land_purchase, landscaping, loan_interest, marketing, park_tickets, research, ride_construct, ride_running, ride_tickets, shop_sales, shop_stock, and staff_wages.
Referenced by FinancesManager::AdvanceMonth(), Finances(), Load(), and FinancesManager::Reset().
Money Finances::GetTotal () const
Total the categories.
Returns
Total amount of transferred money.
Definition at line 57 of file finances.cpp.
References food_sales, food_stock, land_purchase, landscaping, loan_interest, marketing, park_tickets, research, ride_construct, ride_running, ride_tickets, shop_sales, shop_stock, and staff_wages.
Referenced by FinancesGui::SetWidgetStringParameters().
void Finances::Load (Loader & ldr, uint32 version)
Load all monies of one month.
Parameters
ldr Input stream to load from.
version Version of the data to load.
Definition at line 71 of file finances.cpp.
References food_sales, food_stock, Loader::GetLongLong(), land_purchase, landscaping, loan_interest, marketing, park_tickets, research, Reset(), ride_construct, ride_running, ride_tickets, Loader::SetFailMessage(), shop_sales, shop_stock, and staff_wages.
void Finances::Save (Saver & svr)
Save all monies of one month.
Parameters
svr Output stream to save to.
Definition at line 106 of file finances.cpp.
References food_sales, food_stock, land_purchase, landscaping, loan_interest, marketing, park_tickets, Saver::PutLongLong(), research, ride_construct, ride_running, ride_tickets, shop_sales, shop_stock, and staff_wages.
The documentation for this class was generated from the following files:
finances.h
finances.cpp