FreeRCT: GSCLBlock Class Reference
GSCLBlock Class Reference
GSCL game block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
int min_length
Minimal length scrollbar.
int step_back
Stepsize of background.
int min_bar_length
Minimal length bar.
int bar_step
Stepsize of bar.
int widget_type
Widget type.
std::shared_ptr< SpriteBlock > left_button
Left/up button.
std::shared_ptr< SpriteBlock > right_button
Right/down button.
std::shared_ptr< SpriteBlock > left_pressed
Left/up pressed button.
std::shared_ptr< SpriteBlock > right_pressed
Right/down pressed button.
std::shared_ptr< SpriteBlock > left_bottom
Left/top bar bottom (the background).
std::shared_ptr< SpriteBlock > middle_bottom
Middle bar bottom (the background).
std::shared_ptr< SpriteBlock > right_bottom
Right/down bar bottom (the background).
std::shared_ptr< SpriteBlock > left_top
Left/top bar top.
std::shared_ptr< SpriteBlock > middle_top
Middle bar top.
std::shared_ptr< SpriteBlock > right_top
Right/down bar top.
std::shared_ptr< SpriteBlock > left_top_pressed
Left/top pressed bar top.
std::shared_ptr< SpriteBlock > middle_top_pressed
Middle pressed bar top.
std::shared_ptr< SpriteBlock > right_top_pressed
Right/down pressed bar top.
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
GSCL game block.
Definition at line 665 of file nodes.h.
Member Function Documentation
int GSCLBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 1050 of file nodes.cpp.
References FileWriter::AddBlock(), bar_step, NamedBlock::blk_name, FileBlock::CheckEndSave(), left_bottom, left_button, left_pressed, left_top, left_top_pressed, middle_bottom, middle_top, middle_top_pressed, min_bar_length, min_length, right_bottom, right_button, right_pressed, right_top, right_top_pressed, FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), FileBlock::SaveUInt8(), FileBlock::StartSave(), step_back, NamedBlock::version, and widget_type.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp