FreeRCT: TextData Class Reference
TextData Class Reference
Texts of objects.
#include <sprite_store.h>
Public Member Functions
bool Load (RcdFileReader *rcd_file)
Load a TEXT data block into the object.
Public Attributes
uint string_count
Number of strings in strings.
TextString * strings
Strings of the text.
uint8 * text_data
Text data (UTF-8) itself.
RcdBlock * next
Pointer to next block.
Detailed Description
Texts of objects.
Definition at line 45 of file sprite_store.h.
Member Function Documentation
bool TextData::Load (RcdFileReader * rcd_file)
Load a TEXT data block into the object.
Parameters
rcd_file Input file.
Returns
Load was successful.
Definition at line 170 of file sprite_store.cpp.
References GetLanguageIndex(), RcdFileReader::GetUInt16(), RcdFileReader::GetUInt8(), LANGUAGE_COUNT, TextString::languages, lengthof, MAX_NUM_TEXT_STRINGS, TextString::name, ReadUtf8Text(), RcdFileReader::size, string_count, strings, text_data, and RcdFileReader::version.
Referenced by SpriteManager::Load().
The documentation for this class was generated from the following files:
sprite_store.h
sprite_store.cpp