FreeRCT: INFOBlock Class Reference
INFOBlock Class Reference
'INFO' eta block.
#include <nodes.h>
Public Member Functions
int Write (FileWriter *fw) override
Write the block to the file.
virtual std::shared_ptr
< BlockNode > GetSubNode (int row, int col, const char *name, const Position &pos)
Get a subnode for the given row and col.
Public Attributes
std::string name
Name of the work.
std::string uri
Technical unique identification of compatible versions of the worl.
std::string build
Build number or date.
std::string website
Optional website url.
std::string description
Optional description of the work.
const char * blk_name
Name of the block.
int version
Version of the block.
Detailed Description
'INFO' eta block.
Definition at line 918 of file nodes.h.
Member Function Documentation
int INFOBlock::Write (FileWriter * fw) override virtual
Write the block to the file.
Parameters
fw File to write to.
Returns
Block number of this named block in the file.
Implements NamedBlock.
Definition at line 1656 of file nodes.cpp.
References FileWriter::AddBlock(), NamedBlock::blk_name, build, FileBlock::CheckEndSave(), description, name, FileBlock::SaveBytes(), FileBlock::SaveUInt8(), FileBlock::StartSave(), uri, NamedBlock::version, and website.
std::shared_ptr< BlockNode > BlockNode::GetSubNode (int row, int col, const char * name, const Position & pos) virtual inherited
Get a subnode for the given row and col.
Parameters
row Row of the sub node.
col Column of the sub node.
name Variable name to receive the sub node (for error reporting only).
pos Position containing the variable name (for error reporting only).
Returns
The requested sub node.
Note
The default implementation always fails, override to get the feature.
Reimplemented in SpriteFilesBlock, and SheetBlock.
Definition at line 28 of file nodes.cpp.
References Position::ToString().
The documentation for this class was generated from the following files:
nodes.h
nodes.cpp