FreeRCT: LeafWidget Class Reference
LeafWidget Class Reference
Widgets and supporting functions of the program
Base class for a (visible) leaf widget.
#include <widget.h>
Public Member Functions
LeafWidget (WidgetType wtype)
Base class leaf widget constructor.
virtual void SetupMinimalSize (GuiWindow *w, BaseWidget **wid_array) override
Compute smallest size of the widget.
virtual void Draw (const GuiWindow *w) override
Draw the widget.
virtual void AutoRaiseButtons (const Point32 &base) override
Raise all push buttons in the tree.
bool IsChecked () const
Is the 'checked' flag on?
bool IsPressed () const
Is the 'pressed' flag on?
bool IsShaded () const
Is the 'shaded' flag on?
void SetChecked (bool value)
Set the 'checked' flag to the new value.
void SetPressed (bool value)
Set the 'pressed' flag to the new value.
void SetShaded (bool value)
Set the 'shaded' flag to the new value.
virtual void SetSmallestSizePosition (const Rectangle16 &rect)
Set the minimal size of the widget, and assign rect to the current position and size.
virtual BaseWidget * GetWidgetByPosition (const Point16 &pt)
Get the widget at the given relative window position.
void MarkDirty (const Point32 &base) const
Denote the widget as being needed to redraw.
Public Attributes
uint8 flags
Flags of the leaf widget.
ColourRange colour
Colour of the widget.
StringID tooltip
Tool-tip of the widget.
WidgetType wtype
Widget type.
WidgetNumber number
Widget number.
uint16 smallest_x
Original horizontal size.
uint16 smallest_y
Original vertical size.
uint16 min_x
Minimal horizontal size.
uint16 min_y
Minimal vertical size.
Rectangle16 pos
Current position and size (relative to window top-left edge).
uint16 fill_x
Horizontal fill step.
uint16 fill_y
Vertical fill step.
uint16 resize_x
Horizontal resize step.
uint16 resize_y
Vertical resize step.
uint8 paddings [PAD_COUNT]
Padding.
Protected Member Functions
void SetWidget (BaseWidget **wid_array)
Add the widget to the widget array wid_array.
void InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert)
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
void InitMinimalSize (const BorderSpriteData *bsd, uint16 content_width, uint16 content_height)
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Detailed Description
Base class for a (visible) leaf widget.
Implements WT_RADIOBUTTON, WT_CLOSEBOX, WT_RESIZEBOX.
Definition at line 121 of file widget.h.
Constructor & Destructor Documentation
LeafWidget::LeafWidget (WidgetType wtype)
Base class leaf widget constructor.
Parameters
wtype Widget type.
Definition at line 222 of file widget.cpp.
References COL_RANGE_INVALID, colour, flags, STR_NULL, and tooltip.
Member Function Documentation
void LeafWidget::SetupMinimalSize (GuiWindow * w, BaseWidget ** wid_array) override virtual
Compute smallest size of the widget.
Parameters
w Window owning the widget.
wid_array [out] Array of widget pointers.
Todo:
Add support for WT_RESIZEBOX.
Reimplemented from BaseWidget.
Reimplemented in BackgroundWidget, ScrollbarWidget, and DataWidget.
Definition at line 235 of file widget.cpp.
References _gui_sprites, GuiSprites::close_sprite, BaseWidget::fill_x, BaseWidget::fill_y, ImageData::height, CheckableWidgetSpriteData::height, GuiWindow::initialized, BaseWidget::InitMinimalSize(), BaseWidget::min_x, BaseWidget::min_y, NOT_REACHED, GuiSprites::panel, GuiSprites::radio_button, BaseWidget::resize_x, BaseWidget::resize_y, BaseWidget::SetWidget(), BaseWidget::smallest_x, BaseWidget::smallest_y, ImageData::width, CheckableWidgetSpriteData::width, WT_CLOSEBOX, WT_RADIOBUTTON, and BaseWidget::wtype.
void LeafWidget::Draw (const GuiWindow * w) override virtual
Draw the widget.
Parameters
w Window being drawn.
Reimplemented from BaseWidget.
Reimplemented in BackgroundWidget, ScrollbarWidget, and DataWidget.
Definition at line 269 of file widget.cpp.
References _gui_sprites, _video, VideoSystem::BlitImage(), BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, GuiSprites::close_sprite, colour, DrawBorderSprites(), flags, GuiWindow::GetWidgetScreenX(), GuiWindow::GetWidgetScreenY(), GS_NORMAL, ImageData::height, Rectangle< PT, SZ >::height, LWF_CHECKED, LWF_PRESSED, LWF_SHADED, PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, BaseWidget::paddings, GuiSprites::panel, BaseWidget::pos, GuiSprites::radio_button, Recolouring::Set(), CheckableWidgetSpriteData::sprites, WCS_CHECKED, WCS_EMPTY, WCS_EMPTY_PRESSED, WCS_SHADED_EMPTY, ImageData::width, Rectangle< PT, SZ >::width, WT_CLOSEBOX, WT_RADIOBUTTON, WT_RESIZEBOX, and BaseWidget::wtype.
void LeafWidget::AutoRaiseButtons (const Point32 & base) override virtual
Raise all push buttons in the tree.
Parameters
base Base position of the window.
Reimplemented from BaseWidget.
Reimplemented in BackgroundWidget.
Definition at line 312 of file widget.cpp.
References IsPressed(), BaseWidget::MarkDirty(), SetPressed(), WT_IMAGE_PUSHBUTTON, WT_TEXT_PUSHBUTTON, and BaseWidget::wtype.
bool LeafWidget::IsChecked () const inline
Is the 'checked' flag on?
Returns
whether the 'checked' flag is set.
Definition at line 133 of file widget.h.
References LWF_CHECKED.
Referenced by GuiWindow::GetSelectedRadioButton(), and GuiWindow::SetWidgetChecked().
bool LeafWidget::IsPressed () const inline
Is the 'pressed' flag on?
Returns
whether the 'pressed' flag is set.
Definition at line 142 of file widget.h.
References LWF_PRESSED.
Referenced by AutoRaiseButtons(), DataWidget::Draw(), GuiWindow::GetSelectedRadioButton(), and GuiWindow::SetWidgetPressed().
bool LeafWidget::IsShaded () const inline
Is the 'shaded' flag on?
Returns
whether the 'shaded' flag is set.
Definition at line 151 of file widget.h.
References LWF_SHADED.
Referenced by DataWidget::Draw(), ScrollbarWidget::Draw(), GuiWindow::GetSelectedRadioButton(), GuiWindow::OnMouseButtonEvent(), and GuiWindow::SetWidgetShaded().
void LeafWidget::SetChecked (bool value) inline
Set the 'checked' flag to the new value.
Parameters
value New value of the 'checked' flag.
Definition at line 160 of file widget.h.
References LWF_CHECKED.
Referenced by GuiWindow::SetWidgetChecked().
void LeafWidget::SetPressed (bool value) inline
Set the 'pressed' flag to the new value.
Parameters
value New value of the 'pressed' flag.
Definition at line 169 of file widget.h.
References LWF_PRESSED.
Referenced by AutoRaiseButtons(), GuiWindow::OnMouseButtonEvent(), and GuiWindow::SetWidgetPressed().
void LeafWidget::SetShaded (bool value) inline
Set the 'shaded' flag to the new value.
Parameters
value New value of the 'shaded' flag.
Definition at line 178 of file widget.h.
References LWF_SHADED.
Referenced by GuiWindow::SetWidgetShaded().
void BaseWidget::SetSmallestSizePosition (const Rectangle16 & rect) virtual inherited
Set the minimal size of the widget, and assign rect to the current position and size.
Parameters
rect Smallest size, and suggested position of the (entire) widget.
Reimplemented in IntermediateWidget, and BackgroundWidget.
Definition at line 172 of file widget.cpp.
References Rectangle< PT, SZ >::height, BaseWidget::min_x, BaseWidget::min_y, BaseWidget::pos, and Rectangle< PT, SZ >::width.
Referenced by GuiWindow::ResetSize(), BackgroundWidget::SetSmallestSizePosition(), and IntermediateWidget::SetSmallestSizePosition().
BaseWidget * BaseWidget::GetWidgetByPosition (const Point16 & pt) virtual inherited
Get the widget at the given relative window position.
Parameters
pt Relative point.
Returns
The widget underneath the point, or nullptr.
Reimplemented in IntermediateWidget, and BackgroundWidget.
Definition at line 194 of file widget.cpp.
References Rectangle< PT, SZ >::IsPointInside(), and BaseWidget::pos.
Referenced by BackgroundWidget::GetWidgetByPosition(), IntermediateWidget::GetWidgetByPosition(), and GuiWindow::OnMouseButtonEvent().
void BaseWidget::MarkDirty (const Point32 & base) const inherited
Denote the widget as being needed to redraw.
Parameters
base Window base coordinate.
Definition at line 212 of file widget.cpp.
References _video, VideoSystem::MarkDisplayDirty(), Point< CT >::x, and Point< CT >::y.
Referenced by AutoRaiseButtons(), GuiWindow::MarkWidgetDirty(), ScrollbarWidget::OnClick(), GuiWindow::OnMouseButtonEvent(), GuiWindow::SetWidgetChecked(), GuiWindow::SetWidgetPressed(), and GuiWindow::SetWidgetShaded().
void BaseWidget::SetWidget (BaseWidget ** wid_array) protected inherited
Add the widget to the widget array wid_array.
Parameters
wid_array The widget array.
Definition at line 128 of file widget.cpp.
References BaseWidget::number.
Referenced by BaseWidget::SetupMinimalSize(), SetupMinimalSize(), DataWidget::SetupMinimalSize(), ScrollbarWidget::SetupMinimalSize(), BackgroundWidget::SetupMinimalSize(), and IntermediateWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (uint16 content_width, uint16 content_height, uint16 border_hor, uint16 border_vert) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the necessary border space.
Parameters
content_width Minimal width of the content.
content_height Minimal height of the content.
border_hor Horizontal border space.
border_vert Vertical border space.
Definition at line 97 of file widget.cpp.
References BaseWidget::min_x, BaseWidget::min_y, PAD_BOTTOM, PAD_LEFT, PAD_RIGHT, PAD_TOP, and BaseWidget::paddings.
Referenced by SetupMinimalSize(), DataWidget::SetupMinimalSize(), and BackgroundWidget::SetupMinimalSize().
void BaseWidget::InitMinimalSize (const BorderSpriteData * bsd, uint16 content_width, uint16 content_height) protected inherited
Initialize the minimal size of the widget based on the width and height of the content, and the border sprites.
Parameters
bsd Used border sprites.
content_width Minimal width of the content.
content_height Minimal height of the content.
Definition at line 109 of file widget.cpp.
References BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, BaseWidget::fill_x, BaseWidget::fill_y, BorderSpriteData::hor_stepsize, LeastCommonMultiple(), BorderSpriteData::min_height, BorderSpriteData::min_width, BaseWidget::resize_x, BaseWidget::resize_y, and BorderSpriteData::vert_stepsize.
Member Data Documentation
uint8 LeafWidget::flags
Flags of the leaf widget.
See also
LeafWidgetFlags
Definition at line 183 of file widget.h.
Referenced by Draw(), and LeafWidget().
The documentation for this class was generated from the following files:
widget.h
widget.cpp