FreeRCT: CoasterBuildMode Class Reference
CoasterBuildMode Class Reference
Mouse mode for building/editing a roller coaster.
#include <coaster_build.h>
Public Member Functions
void OpenWindow (uint16 instance)
Notification to the mouse mode that a coaster construction window has been opened.
void CloseWindow (uint16 instance)
Notification to the mouse mode that a coaster construction window has been closed.
void ShowNoPiece (uint16 instance)
Notification from the construction window to display no track piece.
void SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction)
Notification from the construction window to display a track piece attached to the mouse cursor.
void DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, int x, int y, int z, TileEdge direction)
Notification from the construction window to display a track piece at a given position.
bool MayActivateMode () override
Query from the viewport whether the mouse mode may be activated.
void ActivateMode (const Point16 &pos) override
Notification from the viewport that the mouse mode has been activated.
void LeaveMode () override
Notification from the viewport that the mouse mode has been de-activated.
void OnMouseMoveEvent (Viewport *vp, const Point16 &old_pos, const Point16 &pos) override
Notification from the viewport that the mouse has moved.
void OnMouseButtonEvent (Viewport *vp, uint8 state) override
Notification from the viewport that a mouse button has changed value.
bool EnableCursors () override
Query from the viewport whether the mouse mode wants to have cursors displayed.
void SetState (BuilderState state)
Select a new state in the builder mouse mode.
void SetNoPiece ()
Do not display a track piece.
void SetMousePosition (const Point16 &pos)
Update the mouse position of the builder mouse mode.
void SetSelectPosition (ConstTrackPiecePtr piece, TileEdge direction)
Denote to the mouse mode handler to attach a track piece to the mouse cursor.
void SetFixedPiece (ConstTrackPiecePtr piece, int x, int y, int z, TileEdge direction)
Denote to the mouse mode handler to display a track piece at the given position.
void EnableDisplay ()
Enable display of a track piece (that is, show it if there is one to show).
void DisableDisplay ()
Suppress display of a track piece (that is, hide it if there is one to show).
void UpdateDisplay (bool mousepos_changed)
Update the displayed position.
virtual void OnMouseWheelEvent (Viewport *vp, int direction)
A mouse wheelie event has been detected.
Public Attributes
uint16 instance
Instance number of the current coaster.
BuilderState state
State of the CoasterBuildMode mouse mode.
ConstTrackPiecePtr cur_piece
Current selected track piece. nullptr if no piece is selected currently.
TileEdge direction
Orientation of the build cursor.
uint8 mouse_state
Stored state of the mouse buttons.
Point16 mouse_pos
Stored mouse position.
uint16 track_xpos
Entry X position of the selected track piece.
uint16 track_ypos
Entry Y position of the selected track piece.
uint8 track_zpos
Entry Z position of the selected track piece.
bool suppress_display
Suppress display of a track piece.
bool use_mousepos
Use mouse position to derive the position of the track piece.
const WindowTypes wtype
Type of window associated with this mouse mode.
const ViewportMouseMode mode
Mouse mode implemented by the object.
Detailed Description
Mouse mode for building/editing a roller coaster.
Co-operates with CoasterBuildWindow.
There may exist several partially build coasters. The instance number refers to the 'current' coaster.
The mouse mode has 6 states:
BS_OFF Nobody needs the mouse mode.
BS_STARTING The mouse mode is needed, but another mode is active at the moment.
BS_ON Mouse mode is on, but there is nothing to display at the moment.
BS_MOUSE Mouse mode is on, and a track piece is displayed at the mouse position (and moved along with the mouse).
BS_FIXED Mouse mode is on, and a track piece is displayed at a fixed position.
BS_DOWN Mouse mode in on, there is nothing to display, and it wants to go off.
Definition at line 44 of file coaster_build.h.
Member Function Documentation
void CoasterBuildMode::OpenWindow (uint16 instance)
Notification to the mouse mode that a coaster construction window has been opened.
Parameters
instance Ride number of the window.
Definition at line 1208 of file coaster_gui.cpp.
References CoasterBuildState::OpenWindow(), and state.
Referenced by CoasterBuildWindow::CoasterBuildWindow().
void CoasterBuildMode::CloseWindow (uint16 instance)
Notification to the mouse mode that a coaster construction window has been closed.
Parameters
instance Ride number of the window.
Definition at line 1217 of file coaster_gui.cpp.
References CoasterBuildState::CloseWindow(), and state.
void CoasterBuildMode::ShowNoPiece (uint16 instance)
Notification from the construction window to display no track piece.
Parameters
instance Ride number of the window.
Definition at line 1226 of file coaster_gui.cpp.
References CoasterBuildState::ShowNoPiece(), and state.
Referenced by CoasterBuildWindow::SetupSelection().
void CoasterBuildMode::SelectPosition (uint16 instance, ConstTrackPiecePtr piece, TileEdge direction)
Notification from the construction window to display a track piece attached to the mouse cursor.
Parameters
instance Ride number of the window.
piece Track piece to display.
direction Direction of building (to use with a cursor).
Definition at line 1237 of file coaster_gui.cpp.
References CoasterBuildState::SelectPosition(), and state.
Referenced by CoasterBuildWindow::SetupSelection().
void CoasterBuildMode::DisplayPiece (uint16 instance, ConstTrackPiecePtr piece, int x, int y, int z, TileEdge direction)
Notification from the construction window to display a track piece at a given position.
Parameters
instance Ride number of the window.
piece Track piece to display.
x X position of the piece.
y Y position of the piece.
z Z position of the piece.
direction Direction of building (to use with a cursor).
Definition at line 1251 of file coaster_gui.cpp.
References CoasterBuildState::DisplayPiece(), and state.
Referenced by CoasterBuildWindow::SetupSelection().
bool CoasterBuildMode::MayActivateMode () override virtual
Query from the viewport whether the mouse mode may be activated.
Returns
The mouse mode may be activated.
See also
MouseMode::MayActivateMode
Implements MouseMode.
Definition at line 1261 of file coaster_gui.cpp.
References CoasterBuildState::MayActivateMode(), and state.
void CoasterBuildMode::ActivateMode (const Point16 & pos) override virtual
Notification from the viewport that the mouse mode has been activated.
Parameters
pos Current mouse position.
See also
MouseMode::ActivateMode
Implements MouseMode.
Definition at line 1271 of file coaster_gui.cpp.
References CoasterBuildState::ActivateMode(), and state.
void CoasterBuildMode::LeaveMode () override virtual
Notification from the viewport that the mouse mode has been de-activated.
See also
MouseMode::LeaveMode
Implements MouseMode.
Definition at line 1280 of file coaster_gui.cpp.
References CoasterBuildState::LeaveMode(), and state.
void CoasterBuildMode::OnMouseMoveEvent (Viewport * vp, const Point16 & old_pos, const Point16 & pos) override virtual
Notification from the viewport that the mouse has moved.
Parameters
vp The viewport.
old_pos Previous position of the mouse.
pos Current mouse position.
See also
MouseMode::OnMouseMoveEvent
Reimplemented from MouseMode.
Definition at line 1292 of file coaster_gui.cpp.
References GetViewport(), MB_RIGHT, mouse_state, Viewport::MoveViewport(), CoasterBuildState::OnMouseMoveEvent(), state, Point< CT >::x, and Point< CT >::y.
void CoasterBuildMode::OnMouseButtonEvent (Viewport * vp, uint8 state) override virtual
Notification from the viewport that a mouse button has changed value.
Parameters
vp The viewport.
state Old and new state of the mouse buttons.
See also
MouseMode::OnMouseButtonEvent
Reimplemented from MouseMode.
Definition at line 1308 of file coaster_gui.cpp.
References MB_CURRENT, mouse_state, CoasterBuildState::OnMouseButtonEvent(), and state.
bool CoasterBuildMode::EnableCursors () override virtual
Query from the viewport whether the mouse mode wants to have cursors displayed.
Returns
Cursors should be enabled.
See also
MouseMode::EnableCursors
Implements MouseMode.
Definition at line 1319 of file coaster_gui.cpp.
References CoasterBuildState::EnableCursors(), and state.
void CoasterBuildMode::SetState (BuilderState state) inline
Select a new state in the builder mouse mode.
Parameters
state New state to select.
Definition at line 77 of file coaster_build.h.
References BS_COUNT, BS_OFF, and state.
Referenced by CoasterBuildStateStarting::ActivateMode(), CoasterBuildStateStarting::CloseWindow(), CoasterBuildStateOn::CloseWindow(), CoasterBuildStateMouse::CloseWindow(), CoasterBuildStateFixed::CloseWindow(), CoasterBuildStateOn::DisplayPiece(), CoasterBuildStateMouse::DisplayPiece(), CoasterBuildStateOn::LeaveMode(), CoasterBuildStateMouse::LeaveMode(), CoasterBuildStateFixed::LeaveMode(), CoasterBuildStateStopping::LeaveMode(), CoasterBuildStateMouse::OnMouseButtonEvent(), CoasterBuildStateOff::OpenWindow(), CoasterBuildStateStopping::OpenWindow(), CoasterBuildStateOn::SelectPosition(), CoasterBuildStateFixed::SelectPosition(), CoasterBuildStateMouse::ShowNoPiece(), and CoasterBuildStateFixed::ShowNoPiece().
void CoasterBuildMode::SetNoPiece () inline
Do not display a track piece.
Definition at line 84 of file coaster_build.h.
Referenced by CoasterBuildStateMouse::OnMouseButtonEvent(), CoasterBuildStateOff::OpenWindow(), CoasterBuildStateStopping::OpenWindow(), CoasterBuildStateStarting::ShowNoPiece(), CoasterBuildStateOn::ShowNoPiece(), CoasterBuildStateMouse::ShowNoPiece(), and CoasterBuildStateFixed::ShowNoPiece().
void CoasterBuildMode::SetMousePosition (const Point16 & pos) inline
Update the mouse position of the builder mouse mode.
Parameters
pos New mouse position.
Todo:
Is this data actually used?
Definition at line 94 of file coaster_build.h.
Referenced by CoasterBuildStateOn::ActivateMode(), CoasterBuildStateMouse::ActivateMode(), CoasterBuildStateStopping::ActivateMode(), CoasterBuildStateOn::OnMouseMoveEvent(), and CoasterBuildStateMouse::OnMouseMoveEvent().
void CoasterBuildMode::SetSelectPosition (ConstTrackPiecePtr piece, TileEdge direction) inline
Denote to the mouse mode handler to attach a track piece to the mouse cursor.
Parameters
piece Selected track piece to attach.
direction Direction of building (to use with a cursor).
Definition at line 104 of file coaster_build.h.
References direction.
Referenced by CoasterBuildStateStarting::SelectPosition(), CoasterBuildStateOn::SelectPosition(), CoasterBuildStateMouse::SelectPosition(), and CoasterBuildStateFixed::SelectPosition().
void CoasterBuildMode::SetFixedPiece (ConstTrackPiecePtr piece, int x, int y, int z, TileEdge direction) inline
Denote to the mouse mode handler to display a track piece at the given position.
Parameters
piece Selected track piece to attach.
x X position of the piece.
y Y position of the piece.
z Z position of the piece.
direction Direction of building (to use with a cursor).
Definition at line 119 of file coaster_build.h.
References direction.
Referenced by CoasterBuildStateStarting::DisplayPiece(), CoasterBuildStateOn::DisplayPiece(), CoasterBuildStateMouse::DisplayPiece(), and CoasterBuildStateFixed::DisplayPiece().
void CoasterBuildMode::EnableDisplay () inline
Enable display of a track piece (that is, show it if there is one to show).
Definition at line 130 of file coaster_build.h.
Referenced by CoasterBuildStateStarting::ActivateMode(), and CoasterBuildStateStopping::OpenWindow().
void CoasterBuildMode::DisableDisplay () inline
Suppress display of a track piece (that is, hide it if there is one to show).
Definition at line 136 of file coaster_build.h.
Referenced by CoasterBuildStateOn::CloseWindow(), CoasterBuildStateMouse::CloseWindow(), CoasterBuildStateFixed::CloseWindow(), CoasterBuildStateOn::LeaveMode(), CoasterBuildStateMouse::LeaveMode(), CoasterBuildStateFixed::LeaveMode(), and CoasterBuildStateOff::OpenWindow().
void CoasterBuildMode::UpdateDisplay (bool mousepos_changed)
Update the displayed position.
Parameters
mousepos_changed If set, check the mouse position to x/y/z again (and only update the display if it is different).
Definition at line 1328 of file coaster_gui.cpp.
References _additions, _rides_manager, Viewport::arrow_cursor, PositionedTrackPiece::CanBePlaced(), WorldAdditions::Clear(), Viewport::ComputeCursorPosition(), CS_GROUND, cur_piece, CUR_TYPE_ARROW_NE, direction, DisableWorldAdditions(), EnableWorldAdditions(), FW_TILE, RidesManager::GetRideInstance(), GetViewport(), instance, CoasterInstance::PlaceTrackPieceInAdditions(), Cursor::SetCursor(), suppress_display, track_xpos, track_ypos, track_zpos, use_mousepos, FinderData::xvoxel, FinderData::yvoxel, and FinderData::zvoxel.
Referenced by CoasterBuildStateStarting::ActivateMode(), CoasterBuildStateMouse::ActivateMode(), CoasterBuildStateOn::CloseWindow(), CoasterBuildStateMouse::CloseWindow(), CoasterBuildStateFixed::CloseWindow(), CoasterBuildStateOn::DisplayPiece(), CoasterBuildStateMouse::DisplayPiece(), CoasterBuildStateFixed::DisplayPiece(), CoasterBuildStateOn::LeaveMode(), CoasterBuildStateMouse::LeaveMode(), CoasterBuildStateFixed::LeaveMode(), CoasterBuildStateMouse::OnMouseButtonEvent(), CoasterBuildStateMouse::OnMouseMoveEvent(), CoasterBuildStateStopping::OpenWindow(), CoasterBuildStateOn::SelectPosition(), CoasterBuildStateMouse::SelectPosition(), CoasterBuildStateFixed::SelectPosition(), CoasterBuildStateMouse::ShowNoPiece(), and CoasterBuildStateFixed::ShowNoPiece().
void MouseMode::OnMouseWheelEvent (Viewport * vp, int direction) virtual inherited
A mouse wheelie event has been detected.
Parameters
vp Viewport object.
direction Direction of movement.
Reimplemented in TileTerraformMouseMode, and FenceBuildManager.
Definition at line 1655 of file viewport.cpp.
Referenced by Viewport::OnMouseWheelEvent().
The documentation for this class was generated from the following files:
coaster_build.h
coaster_gui.cpp