FreeRCT: GuestBlock Class Reference
GuestBlock Class Reference
A block of guests.
#include <people.h>
Public Member Functions
GuestBlock (uint16 base_id)
Guest block constructor.
Guest * Get (uint i)
Get a guest from the array.
const Guest * Get (uint i) const
Get a guest from the array.
uint Index (Guest *g)
Get the index associated with a guest.
Protected Attributes
Guest guests [GUEST_BLOCK_SIZE]
Persons in the block.
Detailed Description
A block of guests.
Definition at line 18 of file people.h.
Constructor & Destructor Documentation
GuestBlock::GuestBlock (uint16 base_id)
Guest block constructor.
Fills the id of the persons with an incrementing number.
Parameters
base_id Id number of the first person in this block.
Definition at line 29 of file people.cpp.
References guests, Person::id, and lengthof.
Member Function Documentation
Guest* GuestBlock::Get (uint i) inline
Get a guest from the array.
Parameters
i Index of the person (should be between 0 and GUEST_BLOCK_SIZE).
Returns
The requested person.
Definition at line 27 of file people.h.
References guests, and lengthof.
Referenced by Guests::CountActiveGuests(), Guests::DoTick(), Guests::FindNextFreeGuest(), Guests::Get(), Guests::GetFree(), Guests::NotifyRideDeletion(), and Guests::OnAnimate().
const Guest* GuestBlock::Get (uint i) const inline
Get a guest from the array.
Parameters
i Index of the person (should be between 0 and GUEST_BLOCK_SIZE).
Returns
The requested person.
Definition at line 38 of file people.h.
References guests, and lengthof.
uint GuestBlock::Index (Guest * g) inline
Get the index associated with a guest.
Parameters
g Guest object to query.
Returns
Index of the guest in the block.
Definition at line 49 of file people.h.
References guests, and lengthof.
Referenced by Guests::AddFree().
The documentation for this class was generated from the following files:
people.h
people.cpp