FreeRCT: coaster.h File Reference
coaster.h File Reference
Coaster data.
#include <map>
#include <vector>
#include "map.h"
#include "ride_type.h"
#include "track_piece.h"
Classes
class CarType
A type of car riding at a track.
class CoasterType
Coaster ride type.
class CoasterPlatform
Platforms of the coaster.
class DisplayCoasterCar
Displayed car in a train.
class CoasterCar
Coaster car drawn at the front and the back position.
class CoasterTrain
A 'train' of coaster cars at a roller coaster.
class CoasterInstance
A roller coaster in the world.
Typedefs
typedef std::map< uint32,
ConstTrackPiecePtr > TrackPiecesMap
Map of loaded track pieces.
Enumerations
enum CoasterKind { CST_SIMPLE = 1, CST_COUNT }
Kinds of coasters.
enum CoasterPlatformType { CPT_WOOD = 1, CPT_COUNT }
Platform types of coasters.
Functions
CarType * GetNewCarType ()
Get a new car type.
bool LoadCoasterPlatform (RcdFileReader *rcdfile, const ImageMap &sprites)
Load a coaster platform (CSPL) block.
Variables
static const int MAX_PLACED_TRACK_PIECES = 1024
Maximum number of track pieces in a single roller coaster.
Detailed Description
Coaster data.
Definition in file coaster.h.
Enumeration Type Documentation
enum CoasterKind
Kinds of coasters.
Enumerator
CST_SIMPLE
'Simple' coaster type.
CST_COUNT
Number of coaster types.
Definition at line 26 of file coaster.h.
enum CoasterPlatformType
Platform types of coasters.
Enumerator
CPT_WOOD
Wooden platform type.
CPT_COUNT
Number of platform types with coasters.
Definition at line 33 of file coaster.h.
Function Documentation
CarType* GetNewCarType ()
Get a new car type.
Returns
A free car type, or nullptr if no free car type available.
Definition at line 32 of file coaster.cpp.
References _used_types, and lengthof.
Referenced by SpriteManager::Load().
bool LoadCoasterPlatform (RcdFileReader * rcdfile, const ImageMap & sprites)
Load a coaster platform (CSPL) block.
Parameters
rcdfile Data file being loaded.
sprites Sprites already loaded from the RCD file.
Returns
Loading the CSPL block succeeded.
Definition at line 206 of file coaster.cpp.
References CPT_COUNT, RcdFileReader::GetUInt16(), RcdFileReader::GetUInt8(), LoadSpriteFromFile(), CoasterPlatform::ne_sw_back, CoasterPlatform::ne_sw_front, CoasterPlatform::nw_se_back, CoasterPlatform::nw_se_front, CoasterPlatform::se_nw_back, CoasterPlatform::se_nw_front, RcdFileReader::size, CoasterPlatform::sw_ne_back, CoasterPlatform::sw_ne_front, CoasterPlatform::tile_width, CoasterPlatform::type, and RcdFileReader::version.
Referenced by SpriteManager::Load().