FreeRCT: coaster.cpp File Reference
coaster.cpp File Reference
Coaster type data.
#include <cmath>
#include "stdafx.h"
#include "sprite_store.h"
#include "coaster.h"
#include "fileio.h"
#include "memory.h"
#include "map.h"
#include "viewport.h"
#include "generated/coasters_strings.cpp"
Functions
CarType * GetNewCarType ()
Get a new car type.
bool LoadCoasterPlatform (RcdFileReader *rcdfile, const ImageMap &sprites)
Load a coaster platform (CSPL) block.
static void Unroll (uint roll, int32 *dy, int32 *dz)
Revert the roll of the coaster car in the direction vector.
Variables
CoasterPlatform _coaster_platforms [CPT_COUNT]
Sprites for the coaster platforms.
static CarType _car_types [16]
Car types available to the program (arbitrary limit).
static uint _used_types = 0
First free car type in _car_types.
static const float _sin_cos_table [20]
Combined sin/cos table for 16 roll positions.
Detailed Description
Coaster type data.
Definition in file coaster.cpp.
Function Documentation
CarType* GetNewCarType ()
Get a new car type.
Returns
A free car type, or nullptr if no free car type available.
Definition at line 32 of file coaster.cpp.
References _used_types, and lengthof.
Referenced by SpriteManager::Load().
bool LoadCoasterPlatform (RcdFileReader * rcdfile, const ImageMap & sprites)
Load a coaster platform (CSPL) block.
Parameters
rcdfile Data file being loaded.
sprites Sprites already loaded from the RCD file.
Returns
Loading the CSPL block succeeded.
Definition at line 206 of file coaster.cpp.
References CPT_COUNT, RcdFileReader::GetUInt16(), RcdFileReader::GetUInt8(), LoadSpriteFromFile(), CoasterPlatform::ne_sw_back, CoasterPlatform::ne_sw_front, CoasterPlatform::nw_se_back, CoasterPlatform::nw_se_front, CoasterPlatform::se_nw_back, CoasterPlatform::se_nw_front, RcdFileReader::size, CoasterPlatform::sw_ne_back, CoasterPlatform::sw_ne_front, CoasterPlatform::tile_width, CoasterPlatform::type, and RcdFileReader::version.
Referenced by SpriteManager::Load().
static void Unroll (uint roll, int32 * dy, int32 * dz) inline static
Revert the roll of the coaster car in the direction vector.
Parameters
roll Amount of roll of the car.
dy [inout] Derivative of Y position.
dz [inout] Derivative of Z position.
Definition at line 339 of file coaster.cpp.
Referenced by CoasterTrain::OnAnimate().
Variable Documentation
const float _sin_cos_table[20] static
Initial value:
= {
        0.00, 0.38, 0.71, 0.92,
        1.00, 0.92, 0.71, 0.38, 0.00, -0.38, -0.71, -0.92, -1.00, -0.92, -0.71, -0.38,
        0.00, 0.38, 0.71, 0.92
}
Combined sin/cos table for 16 roll positions.
sin table starts at 0, cos table start at 4.
Definition at line 327 of file coaster.cpp.