FreeRCT: coaster_gui.cpp File Reference
coaster_gui.cpp File Reference
Roller coaster windows.
#include "stdafx.h"
#include "math_func.h"
#include "memory.h"
#include "window.h"
#include "sprite_store.h"
#include "ride_type.h"
#include "coaster.h"
#include "coaster_build.h"
#include "map.h"
#include "gui_sprites.h"
Classes
class CoasterInstanceWindow
Window to display and setup a roller coaster.
class CoasterBuildWindow
Window to build or edit a roller coaster.
class CoasterBuildState
State in the coaster build mouse mode.
class CoasterBuildStateOff
State when no coaster construction window is opened.
class CoasterBuildStateStarting
State with opened window, but no active mouse mode yet.
class CoasterBuildStateOn
State for display a not-available track piece, or suppressing display of an available track piece.
class CoasterBuildStateMouse
State to display a track piece at the position of the mouse (at the ground).
class CoasterBuildStateFixed
Display a track piece at a fixed position in the world.
class CoasterBuildStateStopping
Stopping state, mouse mode wants to deactivate, but has to wait until it gets permission to do so.
Enumerations
enum CoasterInstanceWidgets { CIW_TITLEBAR }
Widget numbers of the roller coaster instance window.
enum CoasterConstructionWidgets {
CCW_TITLEBAR, CCW_BEND_WIDE_LEFT, CCW_BEND_NORMAL_LEFT, CCW_BEND_TIGHT_LEFT,
CCW_BEND_NONE, CCW_BEND_TIGHT_RIGHT, CCW_BEND_NORMAL_RIGHT, CCW_BEND_WIDE_RIGHT,
CCW_BANK_NONE, CCW_BANK_LEFT, CCW_BANK_RIGHT, CCW_NO_PLATFORM,
CCW_PLATFORM, CCW_NOT_POWERED, CCW_POWERED, CCW_SLOPE_DOWN,
CCW_SLOPE_FLAT, CCW_SLOPE_UP, CCW_SLOPE_STEEP_DOWN, CCW_SLOPE_STEEP_UP,
CCW_SLOPE_VERTICAL_DOWN, CCW_SLOPE_VERTICAL_UP, CCW_DISPLAY_PIECE, CCW_REMOVE,
CCW_BACKWARD, CCW_FORWARD, CCW_ROT_NEG, CCW_ROT_POS
}
Widgets of the coaster construction window.
enum BoolSelect { BSL_FALSE, BSL_TRUE, BSL_NONE }
Three-valued boolean.
Functions
void ShowCoasterManagementGui (RideInstance *coaster)
Open a roller coaster management window for the given roller coaster ride.
static BoolSelect GetPlatform (ConstTrackPiecePtr piece)
Find out whether the provided track piece has a platform.
static BoolSelect GetPower (ConstTrackPiecePtr piece)
Find out whether the provided track piece has is powered.
void ShowCoasterBuildGui (CoasterInstance *coaster)
Open a roller coaster build/edit window for the given roller coaster.
Variables
CoasterBuildMode _coaster_builder
Coaster build mouse mode handler.
static const WidgetPart _coaster_instance_gui_parts []
Widget parts of the CoasterInstanceWindow.
static const WidgetPart _coaster_construction_gui_parts []
Widget parts of the CoasterBuildWindow.
static const CoasterBuildStateOff _coaster_build_state_off (_coaster_builder)
Off state of the coaster build mouse mode.
static const
CoasterBuildStateStarting _coaster_build_state_starting (_coaster_builder)
Starting state of the coaster build mouse mode.
static const CoasterBuildStateOn _coaster_build_state_on (_coaster_builder)
On state of the coaster build mouse mode.
static const CoasterBuildStateMouse _coaster_build_state_mouse (_coaster_builder)
Select position state of the coaster build mouse mode.
static const CoasterBuildStateFixed _coaster_build_state_fixed (_coaster_builder)
Show fixed position state of the coaster build mouse mode.
static const
CoasterBuildStateStopping _coaster_build_state_stopping (_coaster_builder)
Stopping state of the coaster build mouse mode.
static const CoasterBuildState * _coaster_build_states []
Available states of the coaster build mouse mode.
Detailed Description
Roller coaster windows.
Definition in file coaster_gui.cpp.
Enumeration Type Documentation
enum CoasterInstanceWidgets
Widget numbers of the roller coaster instance window.
Enumerator
CIW_TITLEBAR
Titlebar widget.
Definition at line 26 of file coaster_gui.cpp.
enum CoasterConstructionWidgets
Widgets of the coaster construction window.
Enumerator
CCW_TITLEBAR
Titlebar widget.
CCW_BEND_WIDE_LEFT
Button for selecting wide left turn. Same order as TrackBend.
CCW_BEND_NORMAL_LEFT
Button for selecting normal left turn.
CCW_BEND_TIGHT_LEFT
Button for selecting tight left turn.
CCW_BEND_NONE
Button for selecting straight ahead (no turn).
CCW_BEND_TIGHT_RIGHT
Button for selecting tight right turn.
CCW_BEND_NORMAL_RIGHT
Button for selecting normal right turn.
CCW_BEND_WIDE_RIGHT
Button for selecting wide right turn.
CCW_BANK_NONE
Button for selecting no banking. Same order as TrackPieceBanking.
CCW_BANK_LEFT
Button for selecting banking to the left.
CCW_BANK_RIGHT
Button for selecting banking to the right.
CCW_NO_PLATFORM
Button for selecting tracks without platform.
CCW_PLATFORM
Button for selecting tracks with platform.
CCW_NOT_POWERED
Button for selecting unpowered tracks.
CCW_POWERED
Button for selecting powered tracks.
CCW_SLOPE_DOWN
Button for selecting gentle down slope. Same order as TrackSlope.
CCW_SLOPE_FLAT
Button for selecting level slope.
CCW_SLOPE_UP
Button for selecting gentle up slope.
CCW_SLOPE_STEEP_DOWN
Button for selecting steep down slope.
CCW_SLOPE_STEEP_UP
Button for selecting steep up slope.
CCW_SLOPE_VERTICAL_DOWN
Button for selecting vertically down slope.
CCW_SLOPE_VERTICAL_UP
Button for selecting vertically up slope.
CCW_DISPLAY_PIECE
Display space for a track piece.
CCW_REMOVE
Remove track piece button.
CCW_BACKWARD
Move backward.
CCW_FORWARD
Move forward.
CCW_ROT_NEG
Rotate in negative direction.
CCW_ROT_POS
Rotate in positive direction.
Definition at line 103 of file coaster_gui.cpp.
enum BoolSelect
Three-valued boolean.
Enumerator
BSL_FALSE
Selected boolean is false.
BSL_TRUE
Selected boolean is true.
BSL_NONE
Boolean is not selectable.
Definition at line 215 of file coaster_gui.cpp.
Function Documentation
void ShowCoasterManagementGui (RideInstance * coaster)
Open a roller coaster management window for the given roller coaster ride.
Parameters
coaster Coaster instance to display.
Definition at line 86 of file coaster_gui.cpp.
References CoasterInstance::DecideRideState(), RideInstance::GetIndex(), RideInstance::GetKind(), HighlightWindowByType(), RIS_CLOSED, RIS_OPEN, RIS_TESTING, RTK_COASTER, ShowCoasterBuildGui(), and WC_COASTER_MANAGER.
Referenced by RideSelectGui::OnClick(), and SelectMouseMode::OnMouseButtonEvent().
static BoolSelect GetPlatform (ConstTrackPiecePtr piece) static
Find out whether the provided track piece has a platform.
Parameters
piece Track piece to examine.
Returns
BSL_TRUE if the track piece has a platform, else BSL_FALSE.
Definition at line 418 of file coaster_gui.cpp.
References BSL_FALSE, and BSL_TRUE.
Referenced by CoasterBuildWindow::SetupSelection().
static BoolSelect GetPower (ConstTrackPiecePtr piece) static
Find out whether the provided track piece has is powered.
Parameters
piece Track piece to examine.
Returns
BSL_TRUE if the track piece is powered, else BSL_FALSE.
Definition at line 428 of file coaster_gui.cpp.
References BSL_FALSE, and BSL_TRUE.
Referenced by CoasterBuildWindow::SetupSelection().
void ShowCoasterBuildGui (CoasterInstance * coaster)
Open a roller coaster build/edit window for the given roller coaster.
Parameters
coaster Coaster instance to modify.
Definition at line 613 of file coaster_gui.cpp.
References RideInstance::GetIndex(), RideInstance::GetKind(), HighlightWindowByType(), RTK_COASTER, and WC_COASTER_BUILD.
Referenced by ShowCoasterManagementGui().
Variable Documentation
const WidgetPart _coaster_instance_gui_parts[] static
Initial value:
= {
        Intermediate(0, 1),
                Intermediate(1, 0),
                        Widget(WT_TITLEBAR, CIW_TITLEBAR, COL_RANGE_DARK_RED), SetData(STR_ARG1, GUI_TITLEBAR_TIP),
                        Widget(WT_CLOSEBOX, INVALID_WIDGET_INDEX, COL_RANGE_DARK_RED),
                EndContainer(),
                Widget(WT_PANEL, INVALID_WIDGET_INDEX, COL_RANGE_DARK_RED),
                        Widget(WT_EMPTY, INVALID_WIDGET_INDEX, COL_RANGE_DARK_RED), SetMinimalSize(100, 100),
        EndContainer(),
}
Widget parts of the CoasterInstanceWindow.
Definition at line 31 of file coaster_gui.cpp.
const WidgetPart _coaster_construction_gui_parts[] static
Widget parts of the CoasterBuildWindow.
Definition at line 135 of file coaster_gui.cpp.
const CoasterBuildState* _coaster_build_states[] static
Initial value:
= {
        &_coaster_build_state_off,
        &_coaster_build_state_starting,
        &_coaster_build_state_on,
        &_coaster_build_state_mouse,
        &_coaster_build_state_fixed,
        &_coaster_build_state_stopping,
}
Available states of the coaster build mouse mode.
Definition at line 1174 of file coaster_gui.cpp.