FreeRCT: dates.h File Reference
dates.h File Reference
Declarations for dates in the game.
Classes
class Date
Date in the game.
Typedefs
typedef uint32 CompressedDate
Compressed date for easy transfer/storage.
Enumerations
enum CompressedDateBits {
CDB_DAY_LENGTH = 5, CDB_MONTH_LENGTH = 4, CDB_YEAR_LENGTH = 7, CDB_FRAC_LENGTH = 10,
CDB_DAY_START = 0, CDB_MONTH_START = CDB_DAY_START + CDB_DAY_LENGTH, CDB_YEAR_START = CDB_MONTH_START + CDB_MONTH_LENGTH, CDB_FRAC_START = CDB_YEAR_START + CDB_YEAR_LENGTH
}
Bits and sizes of the compressed date format.
Functions
void DateOnTick ()
Update the day.
void LoadDate (Loader &ldr)
Load the current date from the save game.
void SaveDate (Saver &svr)
Save the current date to the save game.
Variables
static const int TICK_COUNT_PER_DAY = 300
Number of ticks in a day (stored in Date::frac).
Date _date
Date in the program.
const int _days_per_month [13]
Numbers of days in each 1-based month (in a non-leap year).
Detailed Description
Declarations for dates in the game.
Definition in file dates.h.
Enumeration Type Documentation
enum CompressedDateBits
Bits and sizes of the compressed date format.
Enumerator
CDB_DAY_LENGTH
Length of the 'day' field in the compressed date.
CDB_MONTH_LENGTH
Length of the 'month' field in the compressed date.
CDB_YEAR_LENGTH
Length of the 'year' field in the compressed date.
CDB_FRAC_LENGTH
Length of the 'fraction' field in the compressed date.
CDB_DAY_START
Start bit of the 'day' field.
CDB_MONTH_START
Start bit of the 'month' field.
CDB_YEAR_START
Start bit of the 'year' field.
CDB_FRAC_START
Start bit of the 'fraction' field.
Definition at line 20 of file dates.h.
Function Documentation
void DateOnTick ()
Update the day.
Todo:
Care about leap years.
Definition at line 132 of file dates.cpp.
References Date::day, FIRST_MONTH, Date::frac, LAST_MONTH, Date::month, OnNewDay(), OnNewMonth(), OnNewYear(), TICK_COUNT_PER_DAY, and Date::year.
Referenced by OnNewFrame().
void LoadDate (Loader & ldr)
Load the current date from the save game.
Parameters
ldr Input stream to load from.
Definition at line 169 of file dates.cpp.
References Loader::CloseBlock(), Loader::GetLong(), Loader::OpenBlock(), and Loader::SetFailMessage().
Referenced by LoadElements().
void SaveDate (Saver & svr)
Save the current date to the save game.
Parameters
svr Output stream to save to.
Definition at line 185 of file dates.cpp.
References Date::Compress(), Saver::EndBlock(), Saver::PutLong(), and Saver::StartBlock().
Referenced by SaveElements().