FreeRCT: dates.cpp File Reference
dates.cpp File Reference
Days and years in the program.
#include "stdafx.h"
#include "dates.h"
#include "gamecontrol.h"
Functions
assert_compile (TICK_COUNT_PER_DAY< (1<< CDB_FRAC_LENGTH))
Day length should stay within the fraction limit.
void DateOnTick ()
Update the day.
void LoadDate (Loader &ldr)
Load the current date from the save game.
void SaveDate (Saver &svr)
Save the current date to the save game.
Variables
const int _days_per_month [13] = {0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}
Numbers of days in each 1-based month (in a non-leap year).
static const int FIRST_MONTH = 3
First month in the year that the park is open, 1-based.
static const int LAST_MONTH = 9
Last month in the year that the park is open, 1-based.
Date _date
Date in the program.
Detailed Description
Days and years in the program.
Definition in file dates.cpp.
Function Documentation
assert_compile ()
Day length should stay within the fraction limit.
Ensure there are not too many shops strings.
void DateOnTick ()
Update the day.
Todo:
Care about leap years.
Definition at line 132 of file dates.cpp.
References Date::day, FIRST_MONTH, Date::frac, LAST_MONTH, Date::month, OnNewDay(), OnNewMonth(), OnNewYear(), TICK_COUNT_PER_DAY, and Date::year.
Referenced by OnNewFrame().
void LoadDate (Loader & ldr)
Load the current date from the save game.
Parameters
ldr Input stream to load from.
Definition at line 169 of file dates.cpp.
References Loader::CloseBlock(), Loader::GetLong(), Loader::OpenBlock(), and Loader::SetFailMessage().
Referenced by LoadElements().
void SaveDate (Saver & svr)
Save the current date to the save game.
Parameters
svr Output stream to save to.
Definition at line 185 of file dates.cpp.
References Date::Compress(), Saver::EndBlock(), Saver::PutLong(), and Saver::StartBlock().
Referenced by SaveElements().