FreeRCT: fileio.h File Reference
fileio.h File Reference
File IO declarations.
Classes
class DirectoryReader
Base class for reading the contents of a directory.
class RcdFileReader
Class for reading an RCD file.
Functions
bool PathIsFile (const char *path)
Test whether the given path points to a normal file.
bool PathIsDirectory (const char *path)
Test whether the given path points to a directory.
DirectoryReader * MakeDirectoryReader ()
Construct a directory reader object (specific for the operating system).
bool ChangeWorkingDirectoryToExecutable (const char *exe)
Attempts to change the working directory to one in which the executable resides in.
Detailed Description
File IO declarations.
Definition in file fileio.h.
Function Documentation
bool PathIsFile (const char * path)
Test whether the given path points to a normal file.
Parameters
path Path to investigate.
Returns
Whether the given path points to a normal file.
Definition at line 84 of file fileio_unix.cpp.
Referenced by UnixDirectoryReader::EntryIsFile(), and ConfigFile::LoadFromDirectoryList().
bool PathIsDirectory (const char * path)
Test whether the given path points to a directory.
Parameters
path Path to investigate.
Returns
Whether the given path points to a directory.
Definition at line 97 of file fileio_unix.cpp.
Referenced by UnixDirectoryReader::EntryIsDirectory().
bool ChangeWorkingDirectoryToExecutable (const char * exe)
Attempts to change the working directory to one in which the executable resides in.
Parameters
exe "Path" to the executable (from argv[0]).
Returns
If the working directory was changed successfully.
Definition at line 273 of file fileio.cpp.
References DirectoryReader::dir_sep, and MakeDirectoryReader().
Referenced by freerct_main().