FreeRCT: freerct.cpp File Reference
freerct.cpp File Reference
Main program.
#include "stdafx.h"
#include "freerct.h"
#include "video.h"
#include "viewport.h"
#include "rcdfile.h"
#include "sprite_data.h"
#include "sprite_store.h"
#include "window.h"
#include "config_reader.h"
#include "language.h"
#include "getoptdata.h"
#include "fileio.h"
#include "gamecontrol.h"
Functions
void InitMouseModes ()
Initialize the mouse modes.
void error (const char *str,...)
Error handling for fatal non-user errors.
static void PrintUsage ()
Output command-line help.
void ShowGraphicsErrorMessage ()
Show that there are missing sprites.
int freerct_main (int argc, char **argv)
Main entry point of our FreeRCT game.
Variables
static const OptionData _options []
Command-line options of the program.
Detailed Description
Main program.
Main program for windows.
Main program for unix.
Definition in file freerct.cpp.
Function Documentation
void InitMouseModes ()
Initialize the mouse modes.
Definition at line 1788 of file viewport.cpp.
References _coaster_builder, _fence_builder, _path_builder, _select_mousemode, _shop_placer, _terraformer, and MouseModes::RegisterMode().
Referenced by freerct_main().
void error (const char * str, ...)
Error handling for fatal non-user errors.
Parameters
str the string to print.
Note
Never returns.
Definition at line 33 of file freerct.cpp.
static void PrintUsage () static
Output command-line help.
Definition at line 51 of file freerct.cpp.
Referenced by freerct_main().
void ShowGraphicsErrorMessage ()
Show that there are missing sprites.
Definition at line 59 of file freerct.cpp.
References ShowErrorMessage().
Referenced by VideoSystem::MainLoop().
int freerct_main (int argc, char ** argv)
Main entry point of our FreeRCT game.
Parameters
argc Argument count.
argv Argument vector.
Returns
The exit code of the program.
Definition at line 72 of file freerct.cpp.
References _gui_sprites, _rcd_collection, _sprite_manager, _video, ChangeWorkingDirectoryToExecutable(), DestroyImageStorage(), ConfigFile::GetNum(), GetOptData::GetOpt(), ConfigFile::GetValue(), GuiSprites::HasSufficientGraphics(), VideoSystem::Initialize(), InitImageStorage(), InitLanguage(), InitMouseModes(), ConfigFile::Load(), SpriteManager::LoadRcdFiles(), VideoSystem::MainLoop(), PrintUsage(), RcdFileCollection::ScanDirectories(), VideoSystem::Shutdown(), ShutdownGame(), StartNewGame(), and UninitLanguage().
Variable Documentation
const OptionData _options[] static
Initial value:
= {
        GETOPT_NOVAL('h', "--help"),
}
Command-line options of the program.
Definition at line 45 of file freerct.cpp.