FreeRCT: freerct.h File Reference
freerct.h File Reference
FreeRCT declarations.
Functions
int freerct_main (int argc, char **argv)
Main entry point of our FreeRCT game.
void ShowGraphicsErrorMessage ()
Show that there are missing sprites.
Detailed Description
FreeRCT declarations.
Definition in file freerct.h.
Function Documentation
int freerct_main (int argc, char ** argv)
Main entry point of our FreeRCT game.
Parameters
argc Argument count.
argv Argument vector.
Returns
The exit code of the program.
Definition at line 72 of file freerct.cpp.
References _gui_sprites, _rcd_collection, _sprite_manager, _video, ChangeWorkingDirectoryToExecutable(), DestroyImageStorage(), ConfigFile::GetNum(), GetOptData::GetOpt(), ConfigFile::GetValue(), GuiSprites::HasSufficientGraphics(), VideoSystem::Initialize(), InitImageStorage(), InitLanguage(), InitMouseModes(), ConfigFile::Load(), SpriteManager::LoadRcdFiles(), VideoSystem::MainLoop(), PrintUsage(), RcdFileCollection::ScanDirectories(), VideoSystem::Shutdown(), ShutdownGame(), StartNewGame(), and UninitLanguage().
void ShowGraphicsErrorMessage ()
Show that there are missing sprites.
Definition at line 59 of file freerct.cpp.
References ShowErrorMessage().
Referenced by VideoSystem::MainLoop().