FreeRCT: gamecontrol.h File Reference
gamecontrol.h File Reference
High level game control functions.
Functions
void StartNewGame ()
Initialize all game data structures for playing a new game.
void ShutdownGame ()
Shutdown the game interaction.
void OnNewDay ()
Runs various procedures that have to be done daily.
void OnNewMonth ()
Runs various procedures that have to be done monthly.
void OnNewYear ()
Runs various procedures that have to be done yearly.
void OnNewFrame (uint32 frame_delay)
For every frame do...
Detailed Description
High level game control functions.
Definition in file gamecontrol.h.
Function Documentation
void StartNewGame ()
Initialize all game data structures for playing a new game.
Todo:
We blindly assume game data structures are all clean.
Definition at line 27 of file gamecontrol.cpp.
References _date, _finances_manager, _game_mode_mgr, _scenario, _weather, _world, VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), GM_PLAY, Weather::Initialize(), Date::Initialize(), VoxelWorld::MakeFlatWorld(), OWN_FOR_SALE, OWN_NONE, OWN_PARK, GameModeManager::SetGameMode(), FinancesManager::SetScenario(), VoxelWorld::SetTileOwnerGlobally(), VoxelWorld::SetTileOwnerRect(), VoxelWorld::SetWorldSize(), ShowBottomToolbar(), ShowMainDisplay(), and ShowToolbar().
Referenced by freerct_main().
void ShutdownGame ()
Shutdown the game interaction.
Todo:
Clean out the game data structures.
Definition at line 50 of file gamecontrol.cpp.
References _game_mode_mgr, _mouse_modes, _window_manager, WindowManager::CloseAllWindows(), GM_NONE, MM_INACTIVE, GameModeManager::SetGameMode(), and MouseModes::SetMouseMode().
Referenced by freerct_main().
void OnNewDay ()
Runs various procedures that have to be done daily.
Definition at line 73 of file gamecontrol.cpp.
References _guests, _rides_manager, _weather, ALL_WINDOWS_OF_TYPE, CHG_DISPLAY_OLD, NotifyChange(), Weather::OnNewDay(), Guests::OnNewDay(), RidesManager::OnNewDay(), and WC_BOTTOM_TOOLBAR.
Referenced by DateOnTick().
void OnNewMonth ()
Runs various procedures that have to be done monthly.
Definition at line 66 of file gamecontrol.cpp.
References _finances_manager, _rides_manager, FinancesManager::AdvanceMonth(), and RidesManager::OnNewMonth().
Referenced by DateOnTick().
void OnNewYear ()
Runs various procedures that have to be done yearly.
Definition at line 60 of file gamecontrol.cpp.
Referenced by DateOnTick().
void OnNewFrame (uint32 frame_delay)
For every frame do...
Parameters
frame_delay Number of milliseconds between two frames.
Definition at line 85 of file gamecontrol.cpp.
References _guests, _rides_manager, _window_manager, DateOnTick(), Guests::DoTick(), Guests::OnAnimate(), RidesManager::OnAnimate(), and WindowManager::Tick().
Referenced by VideoSystem::MainLoop().