FreeRCT: World map data and code
World map data and code
Classes
struct Voxel
One voxel cell in the world.
class VoxelStack
One column of voxels.
class VoxelWorld
A world of voxels.
struct VoxelCorner
Structure describing a corner at a voxel stack.
struct CornerNeighbours
Description of neighbouring corners of a corner at a ground tile.
struct GroundData
Ground data + modification storage.
class TerrainChanges
Store and manage terrain changes.
Typedefs
typedef std::map< Point32,
VoxelStack * > VoxelStackMap
Map of x/y positions to voxel stacks.
typedef std::map< Point32,
GroundData > GroundModificationMap
Map of voxels to ground modification data.
Enumerations
enum FenceType {
FENCE_TYPE_LAND_BORDER, FENCE_TYPE_BUILDABLE_BEGIN, FENCE_TYPE_WOODEN = FENCE_TYPE_BUILDABLE_BEGIN, FENCE_TYPE_CONIFER_HEDGE,
FENCE_TYPE_BRICK_WALL, FENCE_TYPE_COUNT, FENCE_TYPE_INVALID = 0xF
}
Available fence types.
enum ViewOrientation {
VOR_NORTH = TC_NORTH, VOR_EAST = TC_EAST, VOR_SOUTH = TC_SOUTH, VOR_WEST = TC_WEST,
VOR_NUM_ORIENT = 4, VOR_INVALID = 0xFF
}
Direction of view.
enum PathSprites {
PATH_EMPTY, PATH_NE, PATH_SE, PATH_NE_SE,
PATH_NE_SE_E, PATH_SW, PATH_NE_SW, PATH_SE_SW,
PATH_SE_SW_S, PATH_NE_SE_SW, PATH_NE_SE_SW_E, PATH_NE_SE_SW_S,
PATH_NE_SE_SW_E_S, PATH_NW, PATH_NE_NW, PATH_NE_NW_N,
PATH_NW_SE, PATH_NE_NW_SE, PATH_NE_NW_SE_N, PATH_NE_NW_SE_E,
PATH_NE_NW_SE_N_E, PATH_NW_SW, PATH_NW_SW_W, PATH_NE_NW_SW,
PATH_NE_NW_SW_N, PATH_NE_NW_SW_W, PATH_NE_NW_SW_N_W, PATH_NW_SE_SW,
PATH_NW_SE_SW_S, PATH_NW_SE_SW_W, PATH_NW_SE_SW_S_W, PATH_NE_NW_SE_SW,
PATH_NE_NW_SE_SW_N, PATH_NE_NW_SE_SW_E, PATH_NE_NW_SE_SW_N_E, PATH_NE_NW_SE_SW_S,
PATH_NE_NW_SE_SW_N_S, PATH_NE_NW_SE_SW_E_S, PATH_NE_NW_SE_SW_N_E_S, PATH_NE_NW_SE_SW_W,
PATH_NE_NW_SE_SW_N_W, PATH_NE_NW_SE_SW_E_W, PATH_NE_NW_SE_SW_N_E_W, PATH_NE_NW_SE_SW_S_W,
PATH_NE_NW_SE_SW_N_S_W, PATH_NE_NW_SE_SW_E_S_W, PATH_NE_NW_SE_SW_N_E_S_W, PATH_FLAT_COUNT,
PATH_RAMP_NE = PATH_FLAT_COUNT, PATH_RAMP_NW, PATH_RAMP_SE, PATH_RAMP_SW,
PATH_COUNT, PATH_INVALID = 63, PATHBIT_N = 0, PATHBIT_E = 1,
PATHBIT_S = 2, PATHBIT_W = 3, PATHBIT_NE = 4, PATHBIT_SE = 5,
PATHBIT_SW = 6, PATHBIT_NW = 7, PATHMASK_NE = 1 << PATHBIT_NE, PATHMASK_SE = 1 << PATHBIT_SE,
PATHMASK_SW = 1 << PATHBIT_SW, PATHMASK_NW = 1 << PATHBIT_NW, PATHMASK_EDGES = PATHMASK_NE | PATHMASK_SE | PATHMASK_SW | PATHMASK_NW, PTS_EMPTY,
PTS_NE, PTS_SE, PTS_NE_SE, PTS_NE_SE_E,
PTS_SW, PTS_NE_SW, PTS_SE_SW, PTS_SE_SW_S,
PTS_NE_SE_SW, PTS_NE_SE_SW_E, PTS_NE_SE_SW_S, PTS_NE_SE_SW_E_S,
PTS_NW, PTS_NE_NW, PTS_NE_NW_N, PTS_NW_SE,
PTS_NE_NW_SE, PTS_NE_NW_SE_N, PTS_NE_NW_SE_E, PTS_NE_NW_SE_N_E,
PTS_NW_SW, PTS_NW_SW_W, PTS_NE_NW_SW, PTS_NE_NW_SW_N,
PTS_NE_NW_SW_W, PTS_NE_NW_SW_N_W, PTS_NW_SE_SW, PTS_NW_SE_SW_S,
PTS_NW_SE_SW_W, PTS_NW_SE_SW_S_W, PTS_NE_NW_SE_SW, PTS_NE_NW_SE_SW_N,
PTS_NE_NW_SE_SW_E, PTS_NE_NW_SE_SW_N_E, PTS_NE_NW_SE_SW_S, PTS_NE_NW_SE_SW_N_S,
PTS_NE_NW_SE_SW_E_S, PTS_NE_NW_SE_SW_N_E_S, PTS_NE_NW_SE_SW_W, PTS_NE_NW_SE_SW_N_W,
PTS_NE_NW_SE_SW_E_W, PTS_NE_NW_SE_SW_N_E_W, PTS_NE_NW_SE_SW_S_W, PTS_NE_NW_SE_SW_N_S_W,
PTS_NE_NW_SE_SW_E_S_W, PTS_NE_NW_SE_SW_N_E_S_W, PTS_NE_EDGE_UP, PTS_NW_EDGE_UP,
PTS_SE_EDGE_UP, PTS_SW_EDGE_UP, PTS_COUNT
}
Available path sprites.
enum TileSlope {
SL_FLAT = 0, TS_NORTH = TC_NORTH, TS_EAST = TC_EAST, TS_SOUTH = TC_SOUTH,
TS_WEST = TC_WEST, TS_STEEP = TC_END, TS_TOP = TC_END + 1, TSB_NORTH = 1 << TS_NORTH,
TSB_EAST = 1 << TS_EAST, TSB_SOUTH = 1 << TS_SOUTH, TSB_WEST = 1 << TS_WEST, TSB_STEEP = 1 << TS_STEEP,
TSB_TOP = 1 << TS_TOP, TSB_NORTHEAST = TSB_NORTH | TSB_EAST, TSB_NORTHWEST = TSB_NORTH | TSB_WEST, TSB_SOUTHEAST = TSB_SOUTH | TSB_EAST,
TSB_SOUTHWEST = TSB_SOUTH | TSB_WEST
}
Slope description of a surface tile.
enum TileEdge {
EDGE_BEGIN, EDGE_NE = EDGE_BEGIN, EDGE_SE, EDGE_SW,
EDGE_NW, EDGE_COUNT, EDGE_ALL = 0xF, INVALID_EDGE = 0xFF
}
Edges of a tile, starts at NE direction, and rotates clockwise.
enum GroundType {
GTP_GRASS0, GTP_GRASS1, GTP_GRASS2, GTP_GRASS3,
GTP_UNDERGROUND, GTP_DESERT, GTP_CURSOR_TEST, GTP_CURSOR_EDGE_TEST,
GTP_COUNT, GTP_INVALID = 0xF
}
Available ground types.
enum FoundationType {
FDT_GROUND, FDT_WOOD, FDT_BRICK, FDT_COUNT,
FDT_INVALID = 0xF
}
Types of foundations.
enum TrackSlope {
TSL_BEGIN, TSL_DOWN = TSL_BEGIN, TSL_FLAT, TSL_UP,
TSL_COUNT_GENTLE, TSL_STEEP_DOWN = TSL_COUNT_GENTLE, TSL_STEEP_UP, TSL_COUNT_STEEP,
TSL_STRAIGHT_DOWN = TSL_COUNT_STEEP, TSL_STRAIGHT_UP, TSL_COUNT_VERTICAL, TSL_INVALID = 0xFF
}
Path and track slopes.
Functions
static ViewOrientation RotateClockwise (const ViewOrientation &vor)
Rotate view 90 degrees clockwise.
static ViewOrientation RotateCounterClockwise (const ViewOrientation &vor)
Rotate view 90 degrees counter clockwise.
static ViewOrientation AddOrientations (const ViewOrientation &vor1, const ViewOrientation &vor2)
Add two view orientations together.
static ViewOrientation SubtractOrientations (const ViewOrientation &vor1, const ViewOrientation &vor2)
Subtract two view orientations from each other.
static TileSlope ExpandTileSlope (uint8 v)
Expand a slope sprite number to its bit-encoded form for easier manipulating.
static uint8 ImplodeTileSlope (TileSlope s)
Implode an expanded slope back to its sprite number.
Variables
VoxelWorld _world
The game world.
const uint8 _path_expand []
Expansion of path sprite number to a value using path bits (PATHBIT_N, PATHBIT_E, PATHBIT_S, PATHBIT_W, PATHBIT_NE, PATHBIT_SE, PATHBIT_SW, and PATHBIT_NW).
const uint8 _path_implode [256]
Inverse operation of _path_expand.
static const CornerNeighbours neighbours [4]
Neighbouring corners of each corner.
Detailed Description
Enumeration Type Documentation
enum FenceType
Available fence types.
Enumerator
FENCE_TYPE_LAND_BORDER
Special fence for the border of owned land.
FENCE_TYPE_BUILDABLE_BEGIN
Fence types >= this value can be built in the game.
FENCE_TYPE_WOODEN
Wooden fence.
FENCE_TYPE_CONIFER_HEDGE
Conifer hedge.
FENCE_TYPE_BRICK_WALL
Brick wall.
FENCE_TYPE_COUNT
Number of fence types.
FENCE_TYPE_INVALID
Value representing an invalid/non-existing fence type.
Definition at line 30 of file fence.h.
enum ViewOrientation
Direction of view.
Enumerator
VOR_NORTH
View with top of the world to the north.
VOR_EAST
View with top of the world to the east.
VOR_SOUTH
View with top of the world to the south.
VOR_WEST
View with top of the world to the west.
VOR_NUM_ORIENT
Number of orientations.
VOR_INVALID
Invalid orientation.
Definition at line 21 of file orientation.h.
enum PathSprites
Available path sprites.
The list of sprites for drawing a path cover. Conceptually, a path can connect to each of the four edges (NE, NW, SE, and SW). If both edges of a corner are present, the corner itself may also be covered (N, E, S, W). This leads to PATH_FLAT_COUNT sprites listed below.
This list is good for drawing and listing sprites, but is hard for editing path coverage. For this reason _path_expand and its reverse operation _path_implode exist. They translate the sprite number to/from a bitwise representation which is easier for manipulation.
Todo:
Have ramps with path sprites without edges.
Enumerator
PATH_EMPTY
Path without edges or corners.
PATH_FLAT_COUNT
Number of flat path sprites.
PATH_RAMP_NE
Ramp from NE up to SW.
PATH_RAMP_NW
Ramp from NW up to SE.
PATH_RAMP_SE
Ramp from SE up to NW.
PATH_RAMP_SW
Ramp from SW up to NE.
PATH_COUNT
Number of path sprites.
PATH_INVALID
Invalid path. Also used to indicate reserved voxels above paths.
PATHBIT_N
Bit number for north corner in expanded notation.
PATHBIT_E
Bit number for east corner in expanded notation.
PATHBIT_S
Bit number for south corner in expanded notation.
PATHBIT_W
Bit number for west corner in expanded notation.
PATHBIT_NE
Bit number for north-east edge in expanded notation.
PATHBIT_SE
Bit number for south-east edge in expanded notation.
PATHBIT_SW
Bit number for south-west edge in expanded notation.
PATHBIT_NW
Bit number for north-west edge in expanded notation.
PATHMASK_NE
Mask for masking PATHBIT_NE.
PATHMASK_SE
Mask for masking PATHBIT_SE.
PATHMASK_SW
Mask for masking PATHBIT_SW.
PATHMASK_NW
Mask for masking PATHBIT_NW.
PATHMASK_EDGES
Mask for masking the expanded path edges.
PTS_EMPTY
EMPTY.
PTS_NE
NE.
PTS_SE
SE.
PTS_NE_SE
NE_SE.
PTS_NE_SE_E
NE_SE_E.
PTS_SW
SW.
PTS_NE_SW
NE_SW.
PTS_SE_SW
SE_SW.
PTS_SE_SW_S
SE_SW_S.
PTS_NE_SE_SW
NE_SE_SW.
PTS_NE_SE_SW_E
NE_SE_SW_E.
PTS_NE_SE_SW_S
NE_SE_SW_S.
PTS_NE_SE_SW_E_S
NE_SE_SW_E_S.
PTS_NW
NW.
PTS_NE_NW
NE_NW.
PTS_NE_NW_N
NE_NW_N.
PTS_NW_SE
NW_SE.
PTS_NE_NW_SE
NE_NW_SE.
PTS_NE_NW_SE_N
NE_NW_SE_N.
PTS_NE_NW_SE_E
NE_NW_SE_E.
PTS_NE_NW_SE_N_E
NE_NW_SE_N_E.
PTS_NW_SW
NW_SW.
PTS_NW_SW_W
NW_SW_W.
PTS_NE_NW_SW
NE_NW_SW.
PTS_NE_NW_SW_N
NE_NW_SW_N.
PTS_NE_NW_SW_W
NE_NW_SW_W.
PTS_NE_NW_SW_N_W
NE_NW_SW_N_W.
PTS_NW_SE_SW
NW_SE_SW.
PTS_NW_SE_SW_S
NW_SE_SW_S.
PTS_NW_SE_SW_W
NW_SE_SW_W.
PTS_NW_SE_SW_S_W
NW_SE_SW_S_W.
PTS_NE_NW_SE_SW
NE_NW_SE_SW.
PTS_NE_NW_SE_SW_N
NE_NW_SE_SW_N.
PTS_NE_NW_SE_SW_E
NE_NW_SE_SW_E.
PTS_NE_NW_SE_SW_N_E
NE_NW_SE_SW_N_E.
PTS_NE_NW_SE_SW_S
NE_NW_SE_SW_S.
PTS_NE_NW_SE_SW_N_S
NE_NW_SE_SW_N_S.
PTS_NE_NW_SE_SW_E_S
NE_NW_SE_SW_E_S.
PTS_NE_NW_SE_SW_N_E_S
NE_NW_SE_SW_N_E_S.
PTS_NE_NW_SE_SW_W
NE_NW_SE_SW_W.
PTS_NE_NW_SE_SW_N_W
NE_NW_SE_SW_N_W.
PTS_NE_NW_SE_SW_E_W
NE_NW_SE_SW_E_W.
PTS_NE_NW_SE_SW_N_E_W
NE_NW_SE_SW_N_E_W.
PTS_NE_NW_SE_SW_S_W
NE_NW_SE_SW_S_W.
PTS_NE_NW_SE_SW_N_S_W
NE_NW_SE_SW_N_S_W.
PTS_NE_NW_SE_SW_E_S_W
NE_NW_SE_SW_E_S_W.
PTS_NE_NW_SE_SW_N_E_S_W
NE_NW_SE_SW_N_E_S_W.
PTS_NE_EDGE_UP
NE_EDGE_UP.
PTS_NW_EDGE_UP
NW_EDGE_UP.
PTS_SE_EDGE_UP
SE_EDGE_UP.
PTS_SW_EDGE_UP
SW_EDGE_UP.
PTS_COUNT
Number of path sprites.
Definition at line 29 of file path.h.
enum TileSlope
Slope description of a surface tile.
If not TSB_STEEP, at most three of the four TSB_NORTH, TSB_EAST, * TSB_SOUTH, and TSB_WEST may be set.
If TSB_STEEP, the top corner is indicated by a corner bit. Note that steep slopes have 2 sprites. The TSB_TOP bit differentiates between both.
Enumerator
SL_FLAT
Flat slope.
TS_NORTH
North corner bit number.
TS_EAST
East corner bit number.
TS_SOUTH
South corner bit number.
TS_WEST
West corner bit number.
TS_STEEP
Steep slope bit number.
TS_TOP
Top-part of a steep slope bit number.
TSB_NORTH
Bit denoting north corner is raised.
TSB_EAST
Bit denoting east corner is raised.
TSB_SOUTH
Bit denoting south corner is raised.
TSB_WEST
Bit denoting west corner is raised.
TSB_STEEP
Bit denoting it is a steep slope.
TSB_TOP
Bit denoting it is the top of a steep slope.
TSB_NORTHEAST
Both north and east corners are raised.
TSB_NORTHWEST
Both north and west corners are raised.
TSB_SOUTHEAST
Both south and east corners are raised.
TSB_SOUTHWEST
Both south and west corners are raised.
Definition at line 54 of file tile.h.
enum TileEdge
Edges of a tile, starts at NE direction, and rotates clockwise.
Enumerator
EDGE_BEGIN
First valid edge.
EDGE_NE
North-east edge.
EDGE_SE
South-east edge.
EDGE_SW
South-west edge.
EDGE_NW
North-west edge.
EDGE_COUNT
Number of edges.
EDGE_ALL
Bit set of all edges.
INVALID_EDGE
Invalid edge (to denote lack of an edge).
Definition at line 117 of file tile.h.
enum GroundType
Available ground types.
Enumerator
GTP_GRASS0
Short grass type.
GTP_GRASS1
Normal grass type.
GTP_GRASS2
Long grass type.
GTP_GRASS3
Rough grass type.
GTP_UNDERGROUND
Underground view.
GTP_DESERT
Desert ground type.
GTP_CURSOR_TEST
Test tile for hit-testing of ground-tiles. (tile, corner)
GTP_CURSOR_EDGE_TEST
Test tile for hit-testing of ground-tiles. (edge)
GTP_COUNT
Number of ground types.
GTP_INVALID
Invalid ground type.
Definition at line 186 of file tile.h.
enum FoundationType
Types of foundations.
Enumerator
FDT_GROUND
Bare (ground) foundation type.
FDT_WOOD
Foundation is covered with wood.
FDT_BRICK
Foundation is made of bricks.
FDT_COUNT
Number of foundation types.
FDT_INVALID
Invalid foundation type.
Definition at line 205 of file tile.h.
enum TrackSlope
Path and track slopes.
Enumerator
TSL_BEGIN
First track slope.
TSL_DOWN
Gently down.
TSL_FLAT
Horizontal slope.
TSL_UP
Gently up.
TSL_COUNT_GENTLE
Number of gentle slopes.
TSL_STEEP_DOWN
Steeply downwards.
TSL_STEEP_UP
Steeply upwards.
TSL_COUNT_STEEP
Number of gentle and steep slopes.
TSL_STRAIGHT_DOWN
Vertically down.
TSL_STRAIGHT_UP
Vertically up.
TSL_COUNT_VERTICAL
Number of slopes if also going straight up and down.
TSL_INVALID
Invalid track slope.
Definition at line 219 of file tile.h.
Function Documentation
static ViewOrientation RotateClockwise (const ViewOrientation & vor) inline static
Rotate view 90 degrees clockwise.
Parameters
vor Input view orientation.
Returns
Rotated view orientation.
Definition at line 37 of file orientation.h.
Referenced by Viewport::MarkVoxelDirty().
static ViewOrientation RotateCounterClockwise (const ViewOrientation & vor) inline static
Rotate view 90 degrees counter clockwise.
Parameters
vor Input view orientation.
Returns
Rotated view orientation.
Definition at line 48 of file orientation.h.
Referenced by Viewport::MarkVoxelDirty().
static ViewOrientation AddOrientations (const ViewOrientation & vor1, const ViewOrientation & vor2) inline static
Add two view orientations together.
Parameters
vor1 First orientation.
vor2 Second orientation.
Returns
Summed orientation.
Definition at line 60 of file orientation.h.
Referenced by Viewport::ComputeCursorPosition(), and PathBuildGui::OnClick().
static ViewOrientation SubtractOrientations (const ViewOrientation & vor1, const ViewOrientation & vor2) inline static
Subtract two view orientations from each other.
Parameters
vor1 First orientation.
vor2 Second orientation.
Returns
Resulting orientation.
Definition at line 72 of file orientation.h.
Referenced by SpriteCollector::GetCursorSpriteAtPos(), and PathBuildGui::SetButtons().
static TileSlope ExpandTileSlope (uint8 v) inline static
Expand a slope sprite number to its bit-encoded form for easier manipulating.
Parameters
v Sprite slope number.
Returns
Expanded slope.
Definition at line 158 of file tile.h.
References TSB_STEEP, and TSB_TOP.
Referenced by BuildDownwardPath(), BuildUpwardPath(), SpriteCollector::CollectVoxel(), TerrainChanges::GetGroundData(), GetPathAttachPoints(), TerrainChanges::ModifyWorld(), FenceBuildManager::OnMouseButtonEvent(), PathBuildManager::SelectMovement(), FenceBuildManager::SetCursors(), SetXFoundations(), SetYFoundations(), PathBuildManager::TileClicked(), and UpdateLandBorderFence().
static uint8 ImplodeTileSlope (TileSlope s) inline static
Implode an expanded slope back to its sprite number.
Parameters
s Expanded slope to implode.
Returns
Equivalent sprite number.
Definition at line 171 of file tile.h.
References TSB_EAST, TSB_NORTH, TSB_SOUTH, TSB_STEEP, and TSB_TOP.
Referenced by ComputeSlopeAndHeight(), and VoxelWorld::MakeFlatWorld().
Variable Documentation
const uint8 _path_implode[256]
Inverse operation of _path_expand.
PATH_INVALID means there is no sprite defined for this combination. Note that even if a sprite is defined in this table, a particular path type may not have a sprite for every combination (for example, queue paths have no corner bits at all).
Definition at line 94 of file path.cpp.
Referenced by SetPathEdge().
const CornerNeighbours neighbours[4] static
Initial value:
= {
        {TC_EAST,  TC_WEST,  { {{-1, -1}, TC_SOUTH}, {{-1,  0}, TC_WEST }, {{ 0, -1}, TC_EAST }} },
        {TC_NORTH, TC_SOUTH, { {{-1,  0}, TC_SOUTH}, {{-1,  1}, TC_WEST }, {{ 0,  1}, TC_NORTH}} },
        {TC_EAST,  TC_WEST,  { {{ 0,  1}, TC_WEST }, {{ 1,  1}, TC_NORTH}, {{ 1,  0}, TC_EAST }} },
        {TC_SOUTH, TC_NORTH, { {{ 0, -1}, TC_SOUTH}, {{ 1, -1}, TC_EAST }, {{ 1,  0}, TC_NORTH}} },
}
Neighbouring corners of each corner.
Definition at line 48 of file terraform.cpp.