FreeRCT: Window code
Window code
Modules
%Viewport (main display) code and data
Actual windows
Classes
class Window
Window base class.
class GuiWindow
Base class for windows with a widget tree.
class WindowManager
Window manager class, manages the window stack.
Enumerations
enum WindowTypes {
WC_MAINDISPLAY, WC_TOOLBAR, WC_BOTTOM_TOOLBAR, WC_QUIT,
WC_ERROR_MESSAGE, WC_GUEST_INFO, WC_COASTER_MANAGER, WC_COASTER_BUILD,
WC_PATH_BUILDER, WC_RIDE_SELECT, WC_SHOP_MANAGER, WC_FENCE,
WC_TERRAFORM, WC_FINANCES, WC_SETTING, WC_DROPDOWN,
WC_NONE
}
Available types of windows.
enum MouseButtons {
MB_LEFT = 1, MB_MIDDLE = 2, MB_RIGHT = 4, MB_CURRENT = 0x07,
MB_PREVIOUS = 0x70, MB_PREV_SHIFT = 4
}
Known mouse buttons.
enum WmMouseEvent { WMME_NONE, WMME_CLOSE_WINDOW, WMME_MOVE_WINDOW }
Mouse events of the window manager.
enum WmMouseModes { WMMM_PASS_THROUGH, WMMM_MOVE_WINDOW }
Available mouse modes of the window manager.
Functions
bool IsLeftClick (uint8 state)
Does the mouse button state express a left-click?
static uint GetWindowZPriority (WindowTypes wt)
Get the z-priority of a window type (higher number means further up in the window stack).
void UpdateWindows ()
Redraw (parts of) the windows.
Window * GetWindowByType (WindowTypes wtype, WindowNumber wnumber)
Find an opened window by window type.
bool HighlightWindowByType (WindowTypes wtype, WindowNumber wnumber)
Highlight and raise a window of a given type.
Variables
WindowManager _manager
Window manager.
Detailed Description
Enumeration Type Documentation
enum WindowTypes
Available types of windows.
Enumerator
WC_MAINDISPLAY
Main display of the world.
WC_TOOLBAR
Main toolbar.
WC_BOTTOM_TOOLBAR
Bottom toolbar.
WC_QUIT
Quit program window.
WC_ERROR_MESSAGE
Error message window.
WC_GUEST_INFO
Person window.
WC_COASTER_MANAGER
Roller coaster manager window.
WC_COASTER_BUILD
Roller coaster build/edit window.
WC_PATH_BUILDER
Path build GUI.
WC_RIDE_SELECT
Ride selection window.
WC_SHOP_MANAGER
Management window of a shop.
WC_FENCE
Fence window.
WC_TERRAFORM
Terraform window.
WC_FINANCES
Finance management window.
WC_SETTING
Setting window.
WC_DROPDOWN
Dropdown window.
WC_NONE
Invalid window type.
Definition at line 40 of file window.h.
enum MouseButtons
Known mouse buttons.
Enumerator
MB_LEFT
Left button down.
MB_MIDDLE
Middle button down.
MB_RIGHT
Right button down.
MB_CURRENT
Bitmask for current mouse state.
MB_PREVIOUS
Bitmask for previous mouse state.
MB_PREV_SHIFT
Amount of shifting to get previous mouse state.
Definition at line 80 of file window.h.
enum WmMouseEvent
Mouse events of the window manager.
Value is returned from the Window::OnMouseButtonEvent.
Enumerator
WMME_NONE
Do nothing special.
WMME_CLOSE_WINDOW
Close the window.
WMME_MOVE_WINDOW
Initiate a window move.
Definition at line 95 of file window.h.
enum WmMouseModes
Available mouse modes of the window manager.
Enumerator
WMMM_PASS_THROUGH
No special mode, pass events on to the windows.
WMMM_MOVE_WINDOW
Move the current window.
Definition at line 105 of file window.h.
Function Documentation
bool IsLeftClick (uint8 state)
Does the mouse button state express a left-click?
Parameters
state Mouse button state (as given in Window::OnMouseButtonEvent).
Returns
The state expresses a left button click down event.
Definition at line 47 of file window.cpp.
References MB_LEFT, and MB_PREV_SHIFT.
Referenced by GuiWindow::OnMouseButtonEvent().
static uint GetWindowZPriority (WindowTypes wt) static
Get the z-priority of a window type (higher number means further up in the window stack).
Parameters
wt Window type.
Returns
Z-priority of the provided type.
Definition at line 695 of file window.cpp.
References NOT_REACHED, WC_BOTTOM_TOOLBAR, WC_DROPDOWN, WC_ERROR_MESSAGE, WC_MAINDISPLAY, and WC_TOOLBAR.
Referenced by WindowManager::AddToStack(), ComputeInitialPosition::IsScreenEmpty(), and WindowManager::RaiseWindow().
void UpdateWindows ()
Redraw (parts of) the windows.
Todo:
[medium/difficult] Do this much less stupid.
Definition at line 985 of file window.cpp.
References _video, WindowManager::bottom, VideoSystem::DisplayNeedsRepaint(), VideoSystem::FillSurface(), VideoSystem::FinishRepaint(), VideoSystem::GetXSize(), VideoSystem::GetYSize(), Window::higher, MakeRGBA(), Window::OnDraw(), and OPAQUE.
Referenced by VideoSystem::HandleEvent(), and WindowManager::Tick().
Window* GetWindowByType (WindowTypes wtype, WindowNumber wnumber)
Find an opened window by window type.
Parameters
wtype Window type to look for.
wnumber Window number to look for (use ALL_WINDOWS_OF_TYPE for any window of type wtype).
Returns
The window with the requested type if it is opened, else nullptr.
Definition at line 1026 of file window.cpp.
References ALL_WINDOWS_OF_TYPE, Window::lower, WindowManager::top, Window::wnumber, and Window::wtype.
Referenced by Guest::DeActivate(), HighlightWindowByType(), WindowManager::MouseButtonEvent(), NotifyChange(), GuiWindow::ShowDropdownMenu(), ShowQuitProgram(), and GuiWindow::ShowRecolourDropdown().
bool HighlightWindowByType (WindowTypes wtype, WindowNumber wnumber)
Highlight and raise a window of a given type.
Parameters
wtype Window type to look for.
wnumber Window number to look for (use ALL_WINDOWS_OF_TYPE for any window of type wtype).
Returns
A window has been highlighted and raised.
Definition at line 1056 of file window.cpp.
References GetWindowByType(), WindowManager::RaiseWindow(), and Window::SetHighlight().
Referenced by ShowCoasterBuildGui(), ShowCoasterManagementGui(), ShowErrorMessage(), ShowFenceGui(), ShowFinancesGui(), ShowGuestInfoGui(), ShowPathBuildGui(), ShowRideSelectGui(), ShowSettingGui(), ShowShopManagementGui(), and ShowTerraformGui().