FreeRCT: File IO
File IO
Classes
class ConfigItem
Item in a configuration file (a key/value pair).
class ConfigSection
Section in a configuration file (a set of related items).
class ConfigFile
A configuration file.
class DirectoryReader
Base class for reading the contents of a directory.
class RcdFileReader
Class for reading an RCD file.
class UnixDirectoryReader
Directory reader for a Unix system.
class WindowsDirectoryReader
Directory reader for a Windows system.
Typedefs
typedef std::forward_list
< ConfigItem * > ConfigItemList
A list of items.
typedef std::forward_list
< ConfigSection * > ConfigSectionList
A list of sections.
Functions
static bool IsSpace (char k)
Is the given character a white space character?
static char * StripWhitespace (char *first, char *last=nullptr)
Strip white space from the start and end of the line.
DirectoryReader * MakeDirectoryReader ()
Construct a directory reader object (specific for the operating system).
Detailed Description
Function Documentation
static bool IsSpace (char k) static
Is the given character a white space character?
Parameters
k Provided character.
Returns
The provided character is a white space character.
Definition at line 109 of file config_reader.cpp.
Referenced by ConfigFile::Load(), and StripWhitespace().
static char* StripWhitespace (char * first, char * last = nullptr) static
Strip white space from the start and end of the line.
Parameters
first Start of the line.
last If supplied, the terminator of the string, nullptr means only the start is supplied.
Returns
Line with stripped front and end.
Note
Supplied line may be modified.
Definition at line 122 of file config_reader.cpp.
References IsSpace().
Referenced by ConfigFile::Load().
DirectoryReader* MakeDirectoryReader ()
Construct a directory reader object (specific for the operating system).
Returns
A directory reader.
Definition at line 104 of file fileio.cpp.
References assert_compile.
Referenced by ChangeWorkingDirectoryToExecutable(), and RcdFileCollection::ScanDirectories().