FreeRCT: Widgets and supporting functions of the program
Widgets and supporting functions of the program
Modules
%Widget parts for specifying windows
Classes
class BaseWidget
Base class for all widgets.
class LeafWidget
Base class for a (visible) leaf widget.
class DataWidget
Data widget.
class ScrollbarWidget
Scrollbar widget.
class BackgroundWidget
Base class for canvas-like widgets.
struct RowColData
Data about a row or a column.
class IntermediateWidget
Base class for intermediate (that is, non-leaf) widget.
Enumerations
enum WidgetType {
WT_EMPTY, WT_TITLEBAR, WT_CLOSEBOX, WT_RESIZEBOX,
WT_LEFT_TEXT, WT_CENTERED_TEXT, WT_RIGHT_TEXT, WT_PANEL,
WT_TEXT_BUTTON, WT_IMAGE_BUTTON, WT_TEXT_PUSHBUTTON, WT_IMAGE_PUSHBUTTON,
WT_RADIOBUTTON, WT_HOR_SCROLLBAR, WT_VERT_SCROLLBAR, WT_DROPDOWN_BUTTON,
WT_GRID
}
Available widget types.
enum PaddingDirection {
PAD_TOP, PAD_LEFT, PAD_RIGHT, PAD_BOTTOM,
PAD_VERTICAL, PAD_HORIZONTAL, PAD_COUNT
}
Padding space around widgets.
enum LeafWidgetFlags { LWF_CHECKED = 1, LWF_PRESSED = 2, LWF_SHADED = 4 }
Flags of the LeafWidget widget.
enum ScrollbarComponent {
SBC_DECREMENT_BUTTON, SBC_INCREMENT_BUTTON, SBC_SLIDER, SBC_BEFORE_SLIDER,
SBC_AFTER_SLIDER
}
Components of the scroll bar.
enum EqualSize { EQS_HORIZONTAL = 1, EQS_VERTICAL = 2 }
Equal size settings of child widgets.
Functions
void DrawBorderSprites (const BorderSpriteData &bsd, bool pressed, const Rectangle32 &rect, ColourRange colour)
Draw border sprites around some contents.
Detailed Description
Enumeration Type Documentation
enum WidgetType
Available widget types.
Enumerator
WT_EMPTY
Empty widget (used for creating empty space and/or centring).
WT_TITLEBAR
Title of the window.
WT_CLOSEBOX
Close box.
WT_RESIZEBOX
Resize box.
WT_LEFT_TEXT
Text label with left-aligned text.
WT_CENTERED_TEXT
Text label with centred text.
WT_RIGHT_TEXT
Text label with right-aligned text.
WT_PANEL
Panel.
WT_TEXT_BUTTON
Button with text (bi-stable).
WT_IMAGE_BUTTON
Button with a sprite (bi-stable).
WT_TEXT_PUSHBUTTON
Button with text (mono-stable).
WT_IMAGE_PUSHBUTTON
Button with a sprite (mono-stable).
WT_RADIOBUTTON
Radio button widget.
WT_HOR_SCROLLBAR
Scrollbar widget.
WT_VERT_SCROLLBAR
Scrollbar widget.
WT_DROPDOWN_BUTTON
Dropdown widget.
WT_GRID
Intermediate widget.
Definition at line 31 of file widget.h.
enum PaddingDirection
Padding space around widgets.
Enumerator
PAD_TOP
Padding at the top.
PAD_LEFT
Padding at the left.
PAD_RIGHT
Padding at the right.
PAD_BOTTOM
Padding at the bottom.
PAD_VERTICAL
Inter-child vertical padding space.
PAD_HORIZONTAL
Inter-child horizontal padding space.
PAD_COUNT
Number of paddings.
Definition at line 55 of file widget.h.
enum LeafWidgetFlags
Flags of the LeafWidget widget.
Enumerator
LWF_CHECKED
Widget is checked (on/off).
LWF_PRESSED
Widget is pressed (button up/down).
LWF_SHADED
Widget is shaded (enabled/disabled).
Definition at line 109 of file widget.h.
enum ScrollbarComponent
Components of the scroll bar.
Enumerator
SBC_DECREMENT_BUTTON
Top (or left) button.
SBC_INCREMENT_BUTTON
Bottom (or right) button.
SBC_SLIDER
Repositionable slider.
SBC_BEFORE_SLIDER
Region between decrement-button and slider.
SBC_AFTER_SLIDER
Region between increment-button and slider.
Definition at line 210 of file widget.h.
enum EqualSize
Equal size settings of child widgets.
Enumerator
EQS_HORIZONTAL
Try to keep equal size for all widgets in horizontal direction.
EQS_VERTICAL
Try to keep equal size for all widgets in vertical direction.
Definition at line 277 of file widget.h.
Function Documentation
void DrawBorderSprites (const BorderSpriteData & bsd, bool pressed, const Rectangle32 & rect, ColourRange colour)
Draw border sprites around some contents.
Parameters
bsd Border sprites to use.
pressed Draw pressed down sprites.
rect Content rectangle to draw around.
colour Colour range to use.
Definition at line 26 of file gui_graphics.cpp.
References _video, Rectangle< PT, SZ >::base, VideoSystem::BlitHorizontal(), VideoSystem::BlitImage(), VideoSystem::BlitImages(), VideoSystem::BlitVertical(), GS_NORMAL, ImageData::height, Rectangle< PT, SZ >::height, BorderSpriteData::normal, BorderSpriteData::pressed, Recolouring::Set(), WBS_BOTTOM_LEFT, WBS_BOTTOM_MIDDLE, WBS_BOTTOM_RIGHT, WBS_MIDDLE_LEFT, WBS_MIDDLE_MIDDLE, WBS_MIDDLE_RIGHT, WBS_TOP_LEFT, WBS_TOP_MIDDLE, WBS_TOP_RIGHT, ImageData::width, Rectangle< PT, SZ >::width, Point< CT >::x, ImageData::xoffset, Point< CT >::y, and ImageData::yoffset.
Referenced by LeafWidget::Draw(), DataWidget::Draw(), and BackgroundWidget::Draw().