FreeRCT: Widget parts for specifying windows
Widget parts for specifying windows
Widgets and supporting functions of the program
Classes
class WidgetPart
Class for describing a widget-tree in linear source code.
Enumerations
enum WidgetPartType {
WPT_NEW_WIDGET, WPT_NEW_INTERMEDIATE, WPT_MIN_SIZE, WPT_FILL,
WPT_RESIZE, WPT_PADDING, WPT_HOR_PIP, WPT_VERT_PIP,
WPT_DATA, WPT_EQUAL_SIZE, WPT_END_CON
}
Available widget parts.
Functions
WidgetPart Intermediate (uint8 num_rows, uint8 num_cols)
Create a new WT_GRID widget.
WidgetPart Widget (WidgetType wtype, WidgetNumber number, ColourRange colour)
Create a new widget.
WidgetPart SetMinimalSize (int16 x, int16 y)
Set minimal size.
WidgetPart SetFill (uint8 x, uint8 y)
Set fill step.
WidgetPart SetResize (uint8 x, uint8 y)
Set resize step.
WidgetPart SetPadding (uint8 top, uint8 right, uint8 bottom, uint8 left)
Set padding around a widget (start upwards, and then around with the clock).
WidgetPart SetHorPIP (uint8 pre, uint8 inter, uint8 post)
Set padding of a horizontal bar.
WidgetPart SetVertPIP (uint8 pre, uint8 inter, uint8 post)
Set padding of a vertical bar.
WidgetPart SetData (uint16 value, uint16 tip)
Set data and tool tip of the widget.
WidgetPart SetEqualSize (bool hor_equal, bool vert_equal)
Define equal size of child widgets for intermediate widgets (in both directions).
WidgetPart EndContainer ()
Denote the end of a container.
static int MakeWidget (const WidgetPart *parts, int remaining, BaseWidget **dest)
Construct a widget from widget parts.
static int FillWidgetRow (const WidgetPart *parts, int remaining_parts, BaseWidget **widgets, int remaining_widgets, uint8 *cols, int16 *biggest)
Fill a row of an intermediate widget with its children.
static int FillWidget (const WidgetPart *parts, int remaining_parts, IntermediateWidget *wid, int16 *biggest)
Fill an intermediate widget with its children.
static int MakeWidgetSubTree (const WidgetPart *parts, int remaining, BaseWidget **dest, int16 *biggest)
Build a (sub) tree of widgets.
BaseWidget * MakeWidgetTree (const WidgetPart *parts, int length, int16 *biggest)
Construct a widget tree from its parts.
Detailed Description
Enumeration Type Documentation
enum WidgetPartType
Available widget parts.
Enumerator
WPT_NEW_WIDGET
Start a new widget.
WPT_NEW_INTERMEDIATE
Start a new widget.
WPT_MIN_SIZE
Set minimal size.
WPT_FILL
Set fill sizes.
WPT_RESIZE
Set resize sizes.
WPT_PADDING
Set padding.
WPT_HOR_PIP
Set horizontal PIP.
WPT_VERT_PIP
Set vertical PIP.
WPT_DATA
Additional data values.
WPT_EQUAL_SIZE
Define how sizing of child widgets behaves.
WPT_END_CON
End of container or row.
Definition at line 330 of file widget.h.
Function Documentation
WidgetPart Intermediate (uint8 num_rows, uint8 num_cols)
Create a new WT_GRID widget.
Parameters
num_rows Number of rows.
num_cols Number of columns.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1340 of file widget.cpp.
References WidgetPart::data, WidgetPart::new_intermediate, WidgetPart::type, and WPT_NEW_INTERMEDIATE.
WidgetPart Widget (WidgetType wtype, WidgetNumber number, ColourRange colour)
Create a new widget.
Parameters
wtype Widget type.
number Widget number.
colour Widget colour.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1358 of file widget.cpp.
References WidgetPart::data, WidgetPart::new_widget, WidgetPart::type, and WPT_NEW_WIDGET.
WidgetPart SetMinimalSize (int16 x, int16 y)
Set minimal size.
Parameters
x Horizontal minimal size.
y Vertical minimal size.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1376 of file widget.cpp.
References WidgetPart::data, WidgetPart::size, WidgetPart::type, WPT_MIN_SIZE, Point< CT >::x, and Point< CT >::y.
WidgetPart SetFill (uint8 x, uint8 y)
Set fill step.
Parameters
x Horizontal fill step.
y Vertical fill step.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1394 of file widget.cpp.
References WidgetPart::data, WidgetPart::size, WidgetPart::type, WPT_FILL, Point< CT >::x, and Point< CT >::y.
WidgetPart SetResize (uint8 x, uint8 y)
Set resize step.
Parameters
x Horizontal resize step.
y Vertical resize step.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1411 of file widget.cpp.
References WidgetPart::data, WidgetPart::size, WidgetPart::type, WPT_RESIZE, Point< CT >::x, and Point< CT >::y.
WidgetPart SetPadding (uint8 top, uint8 right, uint8 bottom, uint8 left)
Set padding around a widget (start upwards, and then around with the clock).
Parameters
top Padding at the top.
right Padding at the right.
bottom Padding at the bottom.
left Padding at the left.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1430 of file widget.cpp.
References WidgetPart::data, PAD_BOTTOM, PAD_COUNT, PAD_LEFT, PAD_RIGHT, PAD_TOP, WidgetPart::padding, WidgetPart::type, and WPT_PADDING.
WidgetPart SetHorPIP (uint8 pre, uint8 inter, uint8 post)
Set padding of a horizontal bar.
Parameters
pre Padding at the left.
inter Vertical padding between elements.
post Padding at the right.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1451 of file widget.cpp.
References WidgetPart::data, PAD_COUNT, PAD_LEFT, PAD_RIGHT, PAD_VERTICAL, WidgetPart::padding, WidgetPart::type, and WPT_HOR_PIP.
WidgetPart SetVertPIP (uint8 pre, uint8 inter, uint8 post)
Set padding of a vertical bar.
Parameters
pre Padding at the top.
inter Horizontal padding between elements.
post Padding at the bottom.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1471 of file widget.cpp.
References WidgetPart::data, PAD_BOTTOM, PAD_COUNT, PAD_HORIZONTAL, PAD_TOP, WidgetPart::padding, WidgetPart::type, and WPT_VERT_PIP.
WidgetPart SetData (uint16 value, uint16 tip)
Set data and tool tip of the widget.
Parameters
value Additional data of the widget (string or sprite id).
tip Tool tip text.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1490 of file widget.cpp.
References WidgetPart::dat, WidgetPart::data, WidgetPart::type, and WPT_DATA.
WidgetPart SetEqualSize (bool hor_equal, bool vert_equal)
Define equal size of child widgets for intermediate widgets (in both directions).
Parameters
hor_equal Try to keep all child widgets equally wide.
vert_equal Try to keep all child widgets equally high.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1507 of file widget.cpp.
References WidgetPart::data, EQS_HORIZONTAL, EQS_VERTICAL, WidgetPart::flags, WidgetPart::type, and WPT_EQUAL_SIZE.
WidgetPart EndContainer ()
Denote the end of a container.
Returns
Widget part containing the provided data for storage in an array.
Definition at line 1521 of file widget.cpp.
References WidgetPart::type, and WPT_END_CON.
static int MakeWidget (const WidgetPart * parts, int remaining, BaseWidget ** dest) static
Construct a widget from widget parts.
Parameters
parts Base of parts array.
remaining Number of parts still available.
dest Pointer for storing the constructed widget.
Returns
Read number of parts.
Definition at line 1537 of file widget.cpp.
References LeafWidget::colour, WidgetPart::dat, WidgetPart::data, BaseWidget::fill_x, BaseWidget::fill_y, IntermediateWidget::flags, WidgetPart::flags, WidgetPart::new_intermediate, WidgetPart::new_widget, NOT_REACHED, PAD_COUNT, WidgetPart::padding, BaseWidget::paddings, BaseWidget::resize_x, BaseWidget::resize_y, WidgetPart::size, BaseWidget::smallest_x, BaseWidget::smallest_y, LeafWidget::tooltip, WidgetPart::type, DataWidget::value, WPT_DATA, WPT_END_CON, WPT_EQUAL_SIZE, WPT_FILL, WPT_HOR_PIP, WPT_MIN_SIZE, WPT_NEW_INTERMEDIATE, WPT_NEW_WIDGET, WPT_PADDING, WPT_RESIZE, WPT_VERT_PIP, WT_CENTERED_TEXT, WT_CLOSEBOX, WT_DROPDOWN_BUTTON, WT_EMPTY, WT_HOR_SCROLLBAR, WT_IMAGE_BUTTON, WT_IMAGE_PUSHBUTTON, WT_IMAGE_TAB, WT_LEFT_FILLER_TAB, WT_LEFT_TEXT, WT_PANEL, WT_RADIOBUTTON, WT_RESIZEBOX, WT_RIGHT_FILLER_TAB, WT_RIGHT_TEXT, WT_TEXT_BUTTON, WT_TEXT_PUSHBUTTON, WT_TEXT_TAB, WT_TITLEBAR, WT_VERT_SCROLLBAR, Point< CT >::x, and Point< CT >::y.
Referenced by MakeWidgetSubTree().
static int FillWidgetRow (const WidgetPart * parts, int remaining_parts, BaseWidget ** widgets, int remaining_widgets, uint8 * cols, int16 * biggest) static
Fill a row of an intermediate widget with its children.
Parameters
parts Parts to assemble into child widgets of the row.
remaining_parts Number of parts still available.
widgets Temporary storage for the child widgets.
remaining_widgets Amount of space left for the child widgets.
cols [inout] Number of elements of a row. 0 means it is not known.
biggest [out] Pointer to stored biggest widget index number.
Returns
Number of used parts.
Definition at line 1677 of file widget.cpp.
References MakeWidgetSubTree(), WidgetPart::type, and WPT_END_CON.
Referenced by FillWidget().
static int FillWidget (const WidgetPart * parts, int remaining_parts, IntermediateWidget * wid, int16 * biggest) static
Fill an intermediate widget with its children.
Parameters
parts Parts to assemble into children of the widget.
remaining_parts Number of parts still available.
wid Intermediate widget to fill.
biggest [out] Pointer to stored biggest widget index number.
Returns
Number of used parts for the children.
Definition at line 1717 of file widget.cpp.
References IntermediateWidget::AddChild(), IntermediateWidget::ClaimMemory(), FillWidgetRow(), IntermediateWidget::num_cols, IntermediateWidget::num_rows, WidgetPart::type, and WPT_END_CON.
Referenced by MakeWidgetSubTree().
static int MakeWidgetSubTree (const WidgetPart * parts, int remaining, BaseWidget ** dest, int16 * biggest) static
Build a (sub) tree of widgets.
Parameters
parts Parts to assemble into a tree.
remaining Number of parts still available.
dest Pointer for storing the constructed widget tree.
biggest [out] Pointer to stored biggest widget index number.
Returns
Number of used parts for the tree.
Definition at line 1775 of file widget.cpp.
References BackgroundWidget::child, FillWidget(), MakeWidget(), WidgetPart::type, WPT_END_CON, WT_GRID, and WT_PANEL.
Referenced by FillWidgetRow(), and MakeWidgetTree().
BaseWidget* MakeWidgetTree (const WidgetPart * parts, int length, int16 * biggest)
Construct a widget tree from its parts.
Parameters
parts Parts to assemble into a tree.
length Number of parts available.
biggest [out] Pointer to stored biggest widget index number.
Returns
Constructed widget tree.
Definition at line 1815 of file widget.cpp.
References INVALID_WIDGET_INDEX, and MakeWidgetSubTree().
Referenced by GuiWindow::SetupWidgetTree().