FreeRCT: gui_graphics.cpp File Reference
gui_graphics.cpp File Reference
Code for drawing GUI elements and contents.
#include "stdafx.h"
#include "sprite_store.h"
#include "palette.h"
#include "sprite_data.h"
#include "math_func.h"
#include "video.h"
Functions
static void DrawRepeatedSprites (int32 x_base, int32 y_base, const ImageData *spr, uint16 numx, uint16 numy, const Recolouring &recolour)
Draw the same sprite repeatedly over a (potentially) large area.
void DrawBorderSprites (const BorderSpriteData &bsd, bool pressed, const Rectangle32 &rect, ColourRange colour)
Draw border sprites around some contents.
void OverlayShaded (const Rectangle32 &rect)
Draw overlay sprite to mark a button as being shaded.
void DrawString (StringID strid, uint8 colour, int x, int y, int width, Alignment align, bool outline)
Draw a string to the screen.
static uint8 * GetSingleLine (uint8 *text, int max_width, int *width)
Get the text of a single line with an upper limit of the line length.
void GetMultilineTextSize (StringID strid, int max_width, int *width, int *height)
Get the size of a text when printed in multi-line format.
bool DrawMultilineString (StringID strid, int x, int y, int max_width, int max_height, uint8 colour)
Draw a string to the screen using several lines.
Detailed Description
Code for drawing GUI elements and contents.
Definition in file gui_graphics.cpp.
Function Documentation
static void DrawRepeatedSprites (int32 x_base, int32 y_base, const ImageData * spr, uint16 numx, uint16 numy, const Recolouring & recolour) static
Draw the same sprite repeatedly over a (potentially) large area.
The function recognizes a single-pixel sprite as a special case, and converts it to a VideoSystem::FillRectangle call.
Parameters
x_base Left edge coordinate to start drawing.
y_base Top edge coordinate to start drawing.
spr Sprite to draw.
numx Number of horizontal repeats of the sprite.
numy Number of vertical repeats of the sprite.
recolour Recolouring information.
Definition at line 29 of file gui_graphics.cpp.
References _video, VideoSystem::BlitImages(), VideoSystem::FillRectangle(), ImageData::GetPixel(), and ImageData::IsSinglePixel().
Referenced by DrawBorderSprites().
void OverlayShaded (const Rectangle32 & rect)
Draw overlay sprite to mark a button as being shaded.
Parameters
rect Area at the screen containing the button.
Todo:
Alignment can be done much faster if we may assume a sprite size. Perhaps add some special cases for common sizes?
Definition at line 111 of file gui_graphics.cpp.
References _gui_sprites, _video, Rectangle< PT, SZ >::base, VideoSystem::BlitImages(), GuiSprites::disabled, VideoSystem::GetClippedRectangle(), VideoSystem::GetXSize(), VideoSystem::GetYSize(), ImageData::height, Rectangle< PT, SZ >::height, Rectangle< PT, SZ >::RestrictTo(), VideoSystem::SetClippedRectangle(), ImageData::width, Rectangle< PT, SZ >::width, Point< CT >::x, and Point< CT >::y.
Referenced by DataWidget::Draw(), and RecolourDropdownWindow::DrawWidget().
void DrawString (StringID strid, uint8 colour, int x, int y, int width, Alignment align, bool outline)
Draw a string to the screen.
Parameters
strid String to draw.
colour Colour of the text.
x X position at the screen.
y Y position at the screen.
width Maximal width of the text.
align Horizontal alignment of the string.
outline Whether to make the string "bold" (default false).
Todo:
Reduce the naiviness of this.
Definition at line 147 of file gui_graphics.cpp.
References _palette, _video, VideoSystem::BlitText(), DrawText(), lengthof, MakeRGBA(), and OPAQUE.
Referenced by DataWidget::Draw(), and RideSelectGui::DrawWidget().
static uint8* GetSingleLine (uint8 * text, int max_width, int * width) static
Get the text of a single line with an upper limit of the line length.
Text may get split on SPACE. NL implies a line-break, and NUL terminates. Note that in UTF-8, explicit tests on these characters works as expected, since the other code points all have bit 7 set of every byte they use.
Parameters
text Text to search and split.
max_width Longest allowed length of a line.
width [out] Actual width of the text.
Returns
Pointer to the end of the line, points to either a NL or a NUL.
Definition at line 171 of file gui_graphics.cpp.
References _video, VideoSystem::GetTextSize(), and text.
Referenced by DrawMultilineString(), and GetMultilineTextSize().
void GetMultilineTextSize (StringID strid, int max_width, int * width, int * height)
Get the size of a text when printed in multi-line format.
Parameters
strid Text to 'print'.
max_width Longest allowed length of a line.
width [out] Actual width of the text.
height [out] Actual height of the text.
Note
After the call, NL characters have been inserted at line break points.
Actual width (returned in *width) may be larger than max_width in case of long words.
Definition at line 222 of file gui_graphics.cpp.
References _video, DrawText(), GetSingleLine(), VideoSystem::GetTextHeight(), lengthof, and text.
Referenced by RideSelectGui::UpdateWidgetSize().
bool DrawMultilineString (StringID strid, int x, int y, int max_width, int max_height, uint8 colour)
Draw a string to the screen using several lines.
Parameters
strid String to draw.
x X position at the screen.
y Y position at the screen.
max_width Available width of the text.
max_height Available height of the text.
colour Colour of the text.
Returns
The height was sufficient to output all lines.
Definition at line 253 of file gui_graphics.cpp.
References _palette, _video, VideoSystem::BlitText(), DrawText(), GetSingleLine(), VideoSystem::GetTextHeight(), lengthof, and text.
Referenced by RideSelectGui::DrawWidget().