FreeRCT: image.cpp File Reference
image.cpp File Reference
Image loading, cutting, and saving the sprites.
#include "../stdafx.h"
#include <vector>
#include "image.h"
#include "mask64.xbm"
Classes
struct MaskInformation
Information about available bit masks.
Functions
static const MaskInformation * GetMask (const std::string &name)
Retrieve a bitmask by its name.
static void WriteUInt32 (uint32 value, uint8 *ptr)
Write an unsigned 32 bit value into a byte array (little endian format).
static uint32 MakeRGBA (uint8 r, uint8 g, uint8 b, uint8 a)
Construct a 32bpp pixel value from its components.
static uint8 GetR (uint32 rgba)
Get the red colour component of a 32bpp pixel value.
static uint8 GetG (uint32 rgba)
Get the green colour component of a 32bpp pixel value.
static uint8 GetB (uint32 rgba)
Get the blue colour component of a 32bpp pixel value.
static uint8 GetA (uint32 rgba)
Get the opacity component of a 32bpp pixel value.
Variables
static const size_t HEADER_SIZE = 4
Number of bytes to read to decide whether a provided file is indeed a PNG file.
static const int TRANSPARENT_INDEX = 0
Colour index of 'transparent' in the 8bpp image.
static const uint8 FULLY_TRANSPARENT = 0
Opacity value of a fully transparent pixel.
static const uint8 FULLY_OPAQUE = 255
Opacity value of a fully opaque pixel.
static const MaskInformation _masks []
List of bit masks.
Detailed Description
Image loading, cutting, and saving the sprites.
Definition in file image.cpp.
Function Documentation
static const MaskInformation* GetMask (const std::string & name) static
Retrieve a bitmask by its name.
Parameters
name Name of the bitmask to retrieve.
Returns
The bitmask and its meta-information (static reference, do not free).
Definition at line 42 of file image.cpp.
References _masks, and MaskInformation::name.
Referenced by Image::Image().
static void WriteUInt32 (uint32 value, uint8 * ptr) static
Write an unsigned 32 bit value into a byte array (little endian format).
Parameters
value Value to write.
ptr Starting point for writing in the array.
Definition at line 181 of file image.cpp.
Referenced by Image8bpp::Encode().
static uint32 MakeRGBA (uint8 r, uint8 g, uint8 b, uint8 a) inline static
Construct a 32bpp pixel value from its components.
Parameters
r Intensity of the red colour component.
g Intensity of the green colour component.
b Intensity of the blue colour component.
a Opacity of the pixel.
Returns
Pixel value of the given combination of components.
Definition at line 438 of file image.cpp.
Referenced by Image32bpp::GetPixel().
static uint8 GetR (uint32 rgba) inline static
Get the red colour component of a 32bpp pixel value.
Parameters
rgba Pixel value to use.
Returns
Value of the red colour component.
Definition at line 453 of file image.cpp.
Referenced by Image32bpp::Encode().
static uint8 GetG (uint32 rgba) inline static
Get the green colour component of a 32bpp pixel value.
Parameters
rgba Pixel value to use.
Returns
Value of the green colour component.
Definition at line 463 of file image.cpp.
Referenced by Image32bpp::Encode().
static uint8 GetB (uint32 rgba) inline static
Get the blue colour component of a 32bpp pixel value.
Parameters
rgba Pixel value to use.
Returns
Value of the blue colour component.
Definition at line 473 of file image.cpp.
Referenced by Image32bpp::Encode().
static uint8 GetA (uint32 rgba) inline static
Get the opacity component of a 32bpp pixel value.
Parameters
rgba Pixel value to use.
Returns
Value of the opacity component.
Definition at line 483 of file image.cpp.
Referenced by Image32bpp::GetSameOpaqueness(), and Image32bpp::IsTransparent().
Variable Documentation
const MaskInformation _masks[] static
Initial value:
= {
        {mask64_width, mask64_height, mask64_bits, "voxel64"},
        {0, 0, nullptr, nullptr}
}
List of bit masks.
Definition at line 32 of file image.cpp.
Referenced by GetMask().