FreeRCT: language.cpp File Reference
language.cpp File Reference
Language support code.
#include "stdafx.h"
#include "language.h"
#include "fileio.h"
#include "sprite_store.h"
#include "video.h"
#include "string_func.h"
#include "math_func.h"
#include "dates.h"
#include "money.h"
Functions
assert_compile ((int) GUI_STRING_TABLE_END< STR_END_FREE_SPACE)
Ensure there are not too many GUI strings.
assert_compile (lengthof(_lang_names)==LANGUAGE_COUNT)
Ensure number of language matches with array sizes.
int GetLanguageIndex (const char *lang_name)
Get the index number of a given language.
static uint8 * CopyString (uint8 *dest, const uint8 *last, const uint8 *src)
Copy a source string to the destination, if it fits.
static void MoneyStrFmt (uint8 *dest, size_t size, double amt)
Converts a double value into a utf-8 string with the appropriate separators.
static void TemperatureStrFormat (uint8 *dest, size_t size, int temp)
Convert a temperature in 1/10 degrees Celcius to text.
void DrawText (StringID strid, uint8 *buffer, uint length, StringParameters *params)
Draw the string into the supplied buffer.
StringID GetMonthName (int month)
Get the name of a month or the current month.
void GetTextSize (StringID strid, int *width, int *height)
Get the text-size of a string.
const uint8 * GetDateString (const Date &d, const char *format)
Convert the date to a Unicode string.
Point32 GetMaxDateSize ()
Get the maximum size a formatted string can take.
Point32 GetMoneyStringSize (const Money &amount)
Get size of a formatted money string.
void InitLanguage ()
Initialize language support.
void UninitLanguage ()
Clean up the language.
Variables
Language _language
Language strings.
StringParameters _str_params
Default string parameters.
int _current_language = LANG_EN_GB
Index of the current translation.
const char *const _lang_names []
Known languages.
Detailed Description
Language support code.
Definition in file language.cpp.
Function Documentation
assert_compile ()
Ensure there are not too many GUI strings.
Ensure there are not too many shops strings.
int GetLanguageIndex (const char * lang_name)
Get the index number of a given language.
Parameters
lang_name Name of the language.
Returns
Index of the language with the provided name, or -1 if not recognized.
Definition at line 59 of file language.cpp.
References LANGUAGE_COUNT.
Referenced by ConvertStringNode(), ConvertStringsNode(), and TextData::Load().
static uint8* CopyString (uint8 * dest, const uint8 * last, const uint8 * src) static
Copy a source string to the destination, if it fits.
Parameters
dest [out] Destination address.
last Last byte of the destination (not written).
src Source string.
Returns
Updated destination.
Definition at line 293 of file language.cpp.
Referenced by DrawText().
static void MoneyStrFmt (uint8 * dest, size_t size, double amt) static
Converts a double value into a utf-8 string with the appropriate separators.
Parameters
dest [out] A provided buffer to write the output into.
size The size of the provided buffer.
amt The double value to be converted.
Definition at line 310 of file language.cpp.
References Language::GetText(), SafeStrncpy(), and StrBytesLength().
Referenced by DrawText(), and GetMoneyStringSize().
static void TemperatureStrFormat (uint8 * dest, size_t size, int temp) static
Convert a temperature in 1/10 degrees Celcius to text.
Parameters
dest [out] A provided buffer to write the output into.
size The size of the provided buffer.
temp Temperature in 1/10 degrees Celcius to convert.
Definition at line 375 of file language.cpp.
References lengthof, and StrECpy().
Referenced by DrawText().
void DrawText (StringID strid, uint8 * buffer, uint length, StringParameters * params)
Draw the string into the supplied buffer.
Parameters
strid String number to 'draw'.
buffer [out] Destination buffer.
length Length of buffer in bytes.
params String parameter values for the "%n%" patterns.
Definition at line 393 of file language.cpp.
References CopyString(), StringParameterData::dmy, GetDateString(), Language::GetText(), lengthof, MoneyStrFmt(), NOT_REACHED, StringParameterData::number, StringParameterData::parm_type, StringParameters::parms, StringParameters::set_mode, SPT_DATE, SPT_MONEY, SPT_NONE, SPT_NUMBER, SPT_STRID, SPT_TEMPERATURE, SPT_UINT8, StringParameterData::str, TemperatureStrFormat(), StringParameterData::text, and StringParameterData::u.
Referenced by DrawMultilineString(), DrawString(), DropdownItem::DropdownItem(), GetMultilineTextSize(), GetTextSize(), and RidesManager::NewInstanceAdded().
StringID GetMonthName (int month)
Get the name of a month or the current month.
Parameters
month Month number (1-based). Use 0 to get the name of the current month.
Returns
String number containing the month name.
Definition at line 471 of file language.cpp.
References _date, and Date::month.
Referenced by GetDateString().
void GetTextSize (StringID strid, int * width, int * height)
Get the text-size of a string.
Parameters
strid Text to calculate.
width [out] Resulting width.
height [out] Resulting height.
Definition at line 499 of file language.cpp.
References _video, DrawText(), VideoSystem::GetTextSize(), and lengthof.
Referenced by DataWidget::Draw(), DataWidget::SetupMinimalSize(), RideSelectGui::UpdateWidgetSize(), ToolbarWindow::UpdateWidgetSize(), and BottomToolbarWindow::UpdateWidgetSize().
const uint8* GetDateString (const Date & d, const char * format)
Convert the date to a Unicode string.
Parameters
d Date to format.
format C-Style format code.
Returns
The formatted string.
Todo:
Allow variable number of format parameters, e.g. "mm-yy".
Definition at line 513 of file language.cpp.
References Date::day, GetMonthName(), Language::GetText(), lengthof, Date::month, and Date::year.
Referenced by DrawText(), and GetMaxDateSize().
Point32 GetMaxDateSize ()
Get the maximum size a formatted string can take.
Returns
A 2D size representing the maximum size of the date string.
Todo:
Allow different format of date.
Definition at line 526 of file language.cpp.
References _video, GetDateString(), VideoSystem::GetTextSize(), Date::month, Point< CT >::x, and Point< CT >::y.
Referenced by BottomToolbarWindow::UpdateWidgetSize().
Point32 GetMoneyStringSize (const Money & amount)
Get size of a formatted money string.
Parameters
amount Amount of money.
Returns
A 2D size representing size of the money string.
Definition at line 547 of file language.cpp.
References _video, VideoSystem::GetTextSize(), lengthof, MoneyStrFmt(), Point< CT >::x, and Point< CT >::y.
Referenced by BottomToolbarWindow::UpdateWidgetSize().
void UninitLanguage ()
Clean up the language.
Definition at line 564 of file language.cpp.
References Language::Clear().
Referenced by freerct_main().
Variable Documentation
const char* const _lang_names[]
Initial value:
= {
        "da_DK",
        "de_DE",
        "en_GB",
        "es_ES",
        "fr_FR",
        "nl_NL",
}
Known languages.
Definition at line 43 of file language.cpp.