FreeRCT: language.h File Reference
language.h File Reference
Language support.
#include "geometry.h"
#include "generated/gui_strings.h"
#include "generated/shops_strings.h"
#include "generated/coasters_strings.h"
Classes
class TextString
A string with its name and its translations.
struct StringParameterData
Data of one string parameter.
struct StringParameters
All string parameters.
class Language
Class for retrieving language strings.
Typedefs
typedef uint16 StringID
Type of a string value.
Enumerations
enum StringTable {
STR_NULL = 0, STR_EMPTY, STR_ARG1, STR_GUI_START,
STR_END_FREE_SPACE = 0xF800, STR_GENERIC_SHOP_START = STR_END_FREE_SPACE, STR_GENERIC_COASTER_START = STR_GENERIC_SHOP_START + 256, STR_GENERIC_END = 0xFFFF,
STR_INVALID = STR_GENERIC_END
}
Table of string-parts in the game.
enum Languages {
LANG_DA_DK, LANG_DE_DE, LANG_EN_GB, LANG_ES_ES,
LANG_FR_FR, LANG_NL_NL, LANGUAGE_COUNT, LNG_DA_DK,
LNG_DE_DE, LNG_EN_GB, LNG_ES_ES, LNG_FR_FR,
LNG_NL_NL, LNG_COUNT
}
Languages known by the program.
enum StringParamType {
SPT_NONE, SPT_STRID, SPT_NUMBER, SPT_MONEY,
SPT_DATE, SPT_TEMPERATURE, SPT_UINT8
}
Types of parameters for string parameters.
Functions
int GetLanguageIndex (const char *lang_name)
Get the index number of a given language.
void InitLanguage ()
Initialize language support.
void UninitLanguage ()
Clean up the language.
StringID GetMonthName (int month=0)
Get the name of a month or the current month.
void GetTextSize (StringID num, int *width, int *height)
Get the text-size of a string.
void DrawText (StringID num, uint8 *buffer, uint length, StringParameters *params=&_str_params)
Draw the string into the supplied buffer.
const uint8 * GetDateString (const Date &d, const char *format="%02d-%s-%02d")
Convert the date to a Unicode string.
Point32 GetMaxDateSize ()
Get the maximum size a formatted string can take.
Point32 GetMoneyStringSize (const Money &amount)
Get size of a formatted money string.
Variables
int _current_language
Index of the current translation.
Language _language
Language strings.
StringParameters _str_params
Default string parameters.
Detailed Description
Language support.
Definition in file language.h.
Enumeration Type Documentation
enum StringTable
Table of string-parts in the game.
The largest part of the string space is allocated for 'simple' strings that exist only once, mostly in the GUI.
For rides, such as shops, this does not work since there are several shop types loaded. Instead, such strings are allocated at StringTable::STR_GENERIC_SHOP_START, while the strings of each type are elsewhere created. By using the RideType::GetString, the real string number of the queried shop type is returned.
Enumerator
STR_NULL
nullptr string.
STR_EMPTY
Empty string.
STR_ARG1
Argument 1 "%1%".
STR_GUI_START
Start of the GUI strings.
STR_GENERIC_SHOP_START
Generic shop strings, translated to 'real' string numbers by each shop type object by means of the RideType::GetString function.
STR_GENERIC_COASTER_START
Generic coaster strings, translated to 'real' string numbers by each coaster type object by means of the RideType::GetString function.
STR_INVALID
Invalid string.
Definition at line 33 of file language.h.
enum Languages
Languages known by the program.
Enumerator
LANG_DA_DK
Danish.
LANG_DE_DE
German.
LANG_EN_GB
British English.
LANG_ES_ES
Spanish.
LANG_FR_FR
French.
LANG_NL_NL
Dutch.
LANGUAGE_COUNT
Number of available languages.
LNG_DA_DK
da_DK language.
LNG_DE_DE
de_DE language.
LNG_EN_GB
en_GB language (default).
LNG_ES_ES
es_ES language.
LNG_FR_FR
fr_FR language.
LNG_NL_NL
nl_NL language.
LNG_COUNT
Number of known languages.
Definition at line 65 of file language.h.
enum StringParamType
Types of parameters for string parameters.
Enumerator
SPT_NONE
Parameter contains nothing (and should not be used thus).
SPT_STRID
Parameter is another StringID.
SPT_NUMBER
Parameter is a number.
SPT_MONEY
Parameter is an amount of money.
SPT_DATE
Parameter is a date.
SPT_TEMPERATURE
Parameter is a temperature.
SPT_UINT8
Parameter is a C text string.
Definition at line 102 of file language.h.
Function Documentation
int GetLanguageIndex (const char * lang_name)
Get the index number of a given language.
Parameters
lang_name Name of the language.
Returns
Index of the language with the provided name, or -1 if not recognized.
Definition at line 59 of file language.cpp.
References LANGUAGE_COUNT.
Referenced by ConvertStringNode(), ConvertStringsNode(), and TextData::Load().
void UninitLanguage ()
Clean up the language.
Definition at line 564 of file language.cpp.
References Language::Clear().
Referenced by freerct_main().
StringID GetMonthName (int month)
Get the name of a month or the current month.
Parameters
month Month number (1-based). Use 0 to get the name of the current month.
Returns
String number containing the month name.
Definition at line 471 of file language.cpp.
References _date, and Date::month.
Referenced by GetDateString().
void GetTextSize (StringID strid, int * width, int * height)
Get the text-size of a string.
Parameters
strid Text to calculate.
width [out] Resulting width.
height [out] Resulting height.
Definition at line 499 of file language.cpp.
References _video, DrawText(), VideoSystem::GetTextSize(), and lengthof.
Referenced by DataWidget::Draw(), DataWidget::SetupMinimalSize(), RideSelectGui::UpdateWidgetSize(), ToolbarWindow::UpdateWidgetSize(), and BottomToolbarWindow::UpdateWidgetSize().
void DrawText (StringID strid, uint8 * buffer, uint length, StringParameters * params)
Draw the string into the supplied buffer.
Parameters
strid String number to 'draw'.
buffer [out] Destination buffer.
length Length of buffer in bytes.
params String parameter values for the "%n%" patterns.
Definition at line 393 of file language.cpp.
References CopyString(), StringParameterData::dmy, GetDateString(), Language::GetText(), lengthof, MoneyStrFmt(), NOT_REACHED, StringParameterData::number, StringParameterData::parm_type, StringParameters::parms, StringParameters::set_mode, SPT_DATE, SPT_MONEY, SPT_NONE, SPT_NUMBER, SPT_STRID, SPT_TEMPERATURE, SPT_UINT8, StringParameterData::str, TemperatureStrFormat(), StringParameterData::text, and StringParameterData::u.
Referenced by DrawMultilineString(), DrawString(), DropdownItem::DropdownItem(), GetMultilineTextSize(), GetTextSize(), and RidesManager::NewInstanceAdded().
const uint8* GetDateString (const Date & d, const char * format)
Convert the date to a Unicode string.
Parameters
d Date to format.
format C-Style format code.
Returns
The formatted string.
Todo:
Allow variable number of format parameters, e.g. "mm-yy".
Definition at line 513 of file language.cpp.
References Date::day, GetMonthName(), Language::GetText(), lengthof, Date::month, and Date::year.
Referenced by DrawText(), and GetMaxDateSize().
Point32 GetMaxDateSize ()
Get the maximum size a formatted string can take.
Returns
A 2D size representing the maximum size of the date string.
Todo:
Allow different format of date.
Definition at line 526 of file language.cpp.
References _video, GetDateString(), VideoSystem::GetTextSize(), Date::month, Point< CT >::x, and Point< CT >::y.
Referenced by BottomToolbarWindow::UpdateWidgetSize().
Point32 GetMoneyStringSize (const Money & amount)
Get size of a formatted money string.
Parameters
amount Amount of money.
Returns
A 2D size representing size of the money string.
Definition at line 547 of file language.cpp.
References _video, VideoSystem::GetTextSize(), lengthof, MoneyStrFmt(), Point< CT >::x, and Point< CT >::y.
Referenced by BottomToolbarWindow::UpdateWidgetSize().