FreeRCT: map.cpp File Reference
map.cpp File Reference
Voxels of the world.
#include "stdafx.h"
#include "map.h"
#include "memory.h"
#include "viewport.h"
#include "math_func.h"
#include "sprite_store.h"
Functions
static void CopyVoxelObjectList (Voxel *dest, Voxel *src)
Move the list animated voxel objects to the destination.
static void CopyVoxel (Voxel *dest, Voxel *src, bool copy_voxel_objects)
Copy a voxel.
static void CopyStackData (Voxel *dest, Voxel *src, int count, bool copy_voxel_objects)
Copy a stack of voxels.
static Voxel * MakeNewVoxels (int height)
Make a new array of voxels, and initialize it.
static void AddFoundations (VoxelWorld *world, uint16 xpos, uint16 ypos, int16 z, uint8 bits)
Add foundation bits from the bottom up to the given voxel.
void UpdateLandBorderFence (uint16 x, uint16 y, uint16 width, uint16 height)
Add/remove land border fence based on current land ownership for the given tile rectangle.
Variables
VoxelWorld _world
The game world.
Detailed Description
Voxels of the world.
Definition in file map.cpp.
Function Documentation
static void CopyVoxelObjectList (Voxel * dest, Voxel * src) inline static
Move the list animated voxel objects to the destination.
Parameters
dest Destination of the voxel object list.
src Source voxel objects.
Definition at line 34 of file map.cpp.
References Voxel::voxel_objects.
Referenced by CopyVoxel(), and VoxelStack::MoveStack().
static void CopyVoxel (Voxel * dest, Voxel * src, bool copy_voxel_objects) inline static
Copy a voxel.
Parameters
dest Destination address.
src Source address.
copy_voxel_objects Copy/move the voxel objects too.
Definition at line 46 of file map.cpp.
References CopyVoxelObjectList(), Voxel::fence, Voxel::ground, Voxel::instance, and Voxel::instance_data.
Referenced by CopyStackData().
static void CopyStackData (Voxel * dest, Voxel * src, int count, bool copy_voxel_objects) static
Copy a stack of voxels.
Parameters
dest Destination address.
src Source address.
count Number of voxels to copy.
copy_voxel_objects Copy the voxel object list too.
Definition at line 62 of file map.cpp.
References CopyVoxel().
Referenced by VoxelStack::Copy(), VoxelStack::MakeVoxelStack(), and VoxelStack::MoveStack().
static Voxel* MakeNewVoxels (int height) static
Make a new array of voxels, and initialize it.
Parameters
height Desired height of the new voxel array.
Returns
New and initialized to 'empty' voxels. Caller should delete[] the memory after use.
Definition at line 116 of file map.cpp.
Referenced by VoxelStack::Load(), VoxelStack::MakeVoxelStack(), and VoxelStack::MoveStack().
static void AddFoundations (VoxelWorld * world, uint16 xpos, uint16 ypos, int16 z, uint8 bits) static
Add foundation bits from the bottom up to the given voxel.
Parameters
world Voxel storage.
xpos X position of the voxel stack.
ypos Y position of the voxel stack.
z Height of the ground.
bits Foundation bits to add.
Definition at line 286 of file map.cpp.
References FDT_GROUND, FDT_INVALID, VoxelWorld::GetCreateVoxel(), Voxel::GetFoundationSlope(), Voxel::GetFoundationType(), Voxel::SetFoundationSlope(), and Voxel::SetFoundationType().
Referenced by VoxelWorld::MakeFlatWorld().
void UpdateLandBorderFence (uint16 x, uint16 y, uint16 width, uint16 height)
Add/remove land border fence based on current land ownership for the given tile rectangle.
Parameters
x Base X coordinate of the rectangle.
y Base Y coordinate of the rectangle.
width Length in X direction of the rectangle.
height Length in Y direction of the rectangle.
Definition at line 495 of file map.cpp.
References _tile_dxy, EDGE_BEGIN, EDGE_COUNT, ExpandTileSlope(), FENCE_TYPE_INVALID, FENCE_TYPE_LAND_BORDER, VoxelStack::GetCreate(), Voxel::GetFenceType(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), VoxelWorld::GetModifyStack(), VoxelWorld::GetTileOwner(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), GTP_INVALID, VoxelStack::height, OWN_PARK, VoxelStack::owner, Voxel::SetFenceType(), StoreFenceInUpperVoxel(), TSB_TOP, VoxelStack::voxels, Point< CT >::x, and Point< CT >::y.
Referenced by VoxelWorld::SetTileOwner(), and VoxelWorld::SetTileOwnerRect().