FreeRCT: map.h File Reference
map.h File Reference
Definition of voxels in the world.
#include "tile.h"
#include "path.h"
#include "geometry.h"
#include "sprite_store.h"
#include "bitmath.h"
#include <map>
Classes
struct Voxel
One voxel cell in the world.
class VoxelObject
Base class for (moving) objects that are stored at a voxel position for easy retrieval during drawing.
class VoxelStack
One column of voxels.
class VoxelWorld
A world of voxels.
class WorldAdditions
Proposed additions to _world.
Typedefs
typedef std::map< Point32,
VoxelStack * > VoxelStackMap
Map of x/y positions to voxel stacks.
Enumerations
enum SmallRideInstance {
SRI_FREE, SRI_SAME_AS_NORTH, SRI_SAME_AS_EAST, SRI_SAME_AS_SOUTH,
SRI_RIDES_START, SRI_PATH = SRI_RIDES_START, SRI_FULL_RIDES, SRI_LAST = 255
}
In general, ride instances are stored in the RidesManager, where there is room to store all the detailed information carried by the ride instance.
enum TileOwner { OWN_NONE, OWN_FOR_SALE, OWN_PARK, OWN_COUNT }
Possible ownerships of a tile.
Functions
static bool HasValidPath (uint16 instance_data)
Does the instance data indicate a valid path (that is, a voxel with an actual path tile)?
static bool HasValidPath (const Voxel *v)
Does the given voxel contain a valid path?
static PathSprites GetImplodedPathSlope (uint16 instance_data)
Extract the imploded path slope from the instance data.
static uint16 SetImplodedPathSlope (uint16 instance_data, uint8 slope)
Change the path slope in the path instance data.
static PathSprites GetImplodedPathSlope (const Voxel *v)
Get the slope of the path (imploded value).
static PathType GetPathType (uint16 instance_data)
Get the path type from the path voxel instance data.
static uint16 MakePathInstanceData (uint8 slope, PathType path_type)
Construct instance data for a valid path.
void EnableWorldAdditions ()
Enable flashing display of showing proposed game world additions to the player.
void DisableWorldAdditions ()
Disable flashing display of showing proposed game world additions to the player.
static bool IsVoxelstackInsideWorld (int x, int y)
Is the given world voxelstack coordinate within the world boundaries?
static bool IsVoxelInsideWorld (int x, int y, int z)
Is the given world voxel coordinate within the world boundaries?
static bool IsRaisedEdge (TileEdge edge, TileSlope slope)
Is both corners of given edge raised of a voxel with the given non-steep slope?
Variables
static const int WORLD_X_SIZE = 128
Maximal length of the X side (North-West side) of the world.
static const int WORLD_Y_SIZE = 128
Maximal length of the Y side (North-East side) of the world.
static const int WORLD_Z_SIZE = 64
Maximal height of the world.
VoxelWorld _world
The game world.
WorldAdditions _additions
Proposed additions to the game world.
Detailed Description
Definition of voxels in the world.
Definition in file map.h.
Enumeration Type Documentation
enum SmallRideInstance
In general, ride instances are stored in the RidesManager, where there is room to store all the detailed information carried by the ride instance.
Scenery and paths however so small that the instance does not actually carry state information, which means the instance can be shared, greatly reducing memory requirements. These rides are given a fixed ride instance number below to make them easy to handle. The graphics engine still considers them to be rides, and queries the rides manager for their definition and (graphic) representation.
Enumerator
SRI_FREE
Ride instance is not used.
SRI_SAME_AS_NORTH
Ride instance is the same as at the northern part.
SRI_SAME_AS_EAST
Ride instance is the same as at the eastern part.
SRI_SAME_AS_SOUTH
Ride instance is the same as at the southern part.
SRI_RIDES_START
First ride instance.
SRI_PATH
Path.
SRI_FULL_RIDES
First ride instance number for normal rides (created and stored in RidesManager).
Todo:
Add other scenery objects, like trees and flower beds.
SRI_LAST
Biggest possible ride number.
Definition at line 36 of file map.h.
enum TileOwner
Possible ownerships of a tile.
Enumerator
OWN_NONE
Tile not owned by the park and not for sale.
OWN_FOR_SALE
Tile not owned by the park, but can be bought.
OWN_PARK
Tile owned by the park.
OWN_COUNT
Number of valid tile ownership values.
Definition at line 450 of file map.h.
Function Documentation
static bool HasValidPath (uint16 instance_data) inline static
Does the instance data indicate a valid path (that is, a voxel with an actual path tile)?
Parameters
instance_data Instance data to examine.
Returns
Whether the instance data indicates a valid path.
Precondition
The instance must be SRI_PATH
Definition at line 372 of file map.h.
References PATH_INVALID.
Referenced by CanBuildPathFromEdge(), SpriteCollector::CollectVoxel(), PixelFinder::CollectVoxel(), Guest::DecideMoveDirection(), ExamineNeighbourPathEdge(), Guest::GetExitDirections(), GetImplodedPathSlope(), GetParkEntryDirection(), GetPathAttachPoints(), GetPathExits(), PathBuildManager::GetRemoveIsEnabled(), GetZHeight(), HasValidPath(), IsGoodEdgeRoad(), PathBuildManager::MoveCursor(), Person::OnAnimate(), PathExistsAtBottomEdge(), RemovePath(), PathBuildManager::SelectBuyRemove(), PathBuildManager::SelectMovement(), SetUpperBoundary(), and TravelQueuePath().
static bool HasValidPath (const Voxel * v) inline static
Does the given voxel contain a valid path?
Parameters
v Voxel to examine.
Returns
true if the voxel contains a valid path, else false.
Todo:
Extend with acceptable types of path (plain path, queueing path, etc.)
Definition at line 383 of file map.h.
References HasValidPath(), Voxel::instance, Voxel::instance_data, and SRI_PATH.
static PathSprites GetImplodedPathSlope (uint16 instance_data) inline static
Extract the imploded path slope from the instance data.
Parameters
instance_data Instance data to examine.
Returns
Imploded slope of the path.
Precondition
instance data must be a valid path.
Definition at line 394 of file map.h.
References GB().
Referenced by CanBuildPathFromEdge(), SpriteCollector::CollectVoxel(), PixelFinder::CollectVoxel(), ExamineNeighbourPathEdge(), Guest::GetExitDirections(), GetImplodedPathSlope(), GetParkEntryDirection(), GetPathAttachPoints(), GetPathExits(), GetZHeight(), IsGoodEdgeRoad(), PathExistsAtBottomEdge(), RemovePath(), PathBuildManager::SelectBuyRemove(), PathBuildManager::SelectMovement(), and SetUpperBoundary().
static uint16 SetImplodedPathSlope (uint16 instance_data, uint8 slope) inline static
Change the path slope in the path instance data.
Parameters
instance_data Previous instance data.
slope New imploded path slope.
Returns
New instance data of a path.
Precondition
instance data must be a valid path.
Definition at line 406 of file map.h.
References SB().
Referenced by ExamineNeighbourPathEdge().
static PathSprites GetImplodedPathSlope (const Voxel * v) inline static
Get the slope of the path (imploded value).
Parameters
v Voxel to examine.
Returns
Imploded slope of the path.
Precondition
Voxel should have a valid path.
Definition at line 418 of file map.h.
References GetImplodedPathSlope(), HasValidPath(), Voxel::instance_data, and PATH_COUNT.
static PathType GetPathType (uint16 instance_data) inline static
Get the path type from the path voxel instance data.
Parameters
instance_data Instance data to examine.
Returns
Type of path.
Precondition
instance data must be a valid path.
Definition at line 433 of file map.h.
References GB().
Referenced by SpriteCollector::CollectVoxel(), PixelFinder::CollectVoxel(), ExamineNeighbourPathEdge(), Guest::GetExitDirections(), and TravelQueuePath().
static uint16 MakePathInstanceData (uint8 slope, PathType path_type) inline static
Construct instance data for a valid path.
Parameters
slope Imploded slope of the path.
path_type Type of the path.
Returns
Instance data of a valid path.
Definition at line 444 of file map.h.
Referenced by BuildPathAtTile().
void EnableWorldAdditions ()
Enable flashing display of showing proposed game world additions to the player.
Definition at line 101 of file viewport.cpp.
Referenced by ShopPlacementManager::ActivateMode(), and CoasterBuildMode::UpdateDisplay().
void DisableWorldAdditions ()
Disable flashing display of showing proposed game world additions to the player.
Definition at line 108 of file viewport.cpp.
Referenced by PathBuildManager::LeaveMode(), ShopPlacementManager::LeaveMode(), ShopPlacementManager::OnMouseButtonEvent(), PathBuildManager::PathBuildManager(), ShopPlacementManager::SetSelection(), and CoasterBuildMode::UpdateDisplay().
static bool IsVoxelstackInsideWorld (int x, int y) inline static
Is the given world voxelstack coordinate within the world boundaries?
Parameters
x X position of the voxelstack.
y Y position of the voxelstack.
Returns
Voxelstack coordinate is within world boundaries.
Definition at line 653 of file map.h.
References VoxelWorld::GetXSize(), and VoxelWorld::GetYSize().
Referenced by BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), CanBuildPathFromEdge(), ShopPlacementManager::ComputeShopVoxel(), GetPathAttachPoints(), GetPathExits(), IsVoxelInsideWorld(), PathExistsAtBottomEdge(), RemovePath(), RideExistsAtBottom(), and TravelQueuePath().
static bool IsVoxelInsideWorld (int x, int y, int z) inline static
Is the given world voxel coordinate within the world boundaries?
Parameters
x X position of the voxel.
y Y position of the voxel.
z Z position of the voxel.
Returns
Voxel coordinate is within world boundaries.
Definition at line 665 of file map.h.
References IsVoxelstackInsideWorld(), and WORLD_Z_SIZE.
Referenced by PositionedTrackPiece::IsOnWorld().
static bool IsRaisedEdge (TileEdge edge, TileSlope slope) inline static
Is both corners of given edge raised of a voxel with the given non-steep slope?
Parameters
edge The edge to check
slope The slope of a voxel.
Precondition
(slope & TSB_STEEP) == 0
Returns
True if both corners of given edge are raised, otherwise false.
Definition at line 678 of file map.h.
References TSB_STEEP.
Referenced by FenceBuildManager::OnMouseButtonEvent(), and FenceBuildManager::SetCursors().
Variable Documentation
WorldAdditions _additions
Proposed additions to the game world.
Not part of the game itself, but they are displayed by calling EnableWorldAdditions (and stopped being displayed with DisableWorldAdditions). The additions will flash on and off to show they are not decided yet.
Definition at line 95 of file viewport.cpp.
Referenced by BuildPathAtTile(), CoasterBuildWindow::BuildTrackPiece(), ChangeAreaCursorMode(), ChangeTileCursorMode(), PathBuildManager::ComputeNewLongPath(), ExamineNeighbourPathEdge(), TerrainChanges::ModifyWorld(), CoasterBuildWindow::OnClick(), ShopPlacementManager::OnMouseButtonEvent(), ShopPlacementManager::PlaceShop(), CoasterInstance::PlaceTrackPieceInAdditions(), RemovePathAtTile(), CoasterInstance::RemoveTrackPieceInAdditions(), PathBuildManager::SelectBuyRemove(), SetXFoundations(), SetYFoundations(), CoasterBuildMode::UpdateDisplay(), and PathBuildManager::UpdateState().