FreeRCT: math_func.cpp File Reference
math_func.cpp File Reference
Math functions.
#include "stdafx.h"
Functions
int GreatestCommonDivisor (int a, int b)
Compute greatest common divisor (gcd) of a and b.
int LeastCommonMultiple (int a, int b)
Compute least common multiple (lcm) of arguments a and b, the smallest integer value that is a multiple of both a and b.
int CountBits (uint value)
Get the number of bits set in the given value.
Detailed Description
Math functions.
Definition in file math_func.cpp.
Function Documentation
int GreatestCommonDivisor (int a, int b)
Compute greatest common divisor (gcd) of a and b.
Parameters
a First number.
b second number.
Returns
Greatest common divisor of a and b.
Definition at line 20 of file math_func.cpp.
Referenced by LeastCommonMultiple().
int LeastCommonMultiple (int a, int b)
Compute least common multiple (lcm) of arguments a and b, the smallest integer value that is a multiple of both a and b.
Parameters
a First number.
b second number.
Returns
Least common multiple of values a and b.
Note
This function only works for non-negative values of a and b.
Definition at line 39 of file math_func.cpp.
References GreatestCommonDivisor().
Referenced by BaseWidget::InitMinimalSize(), and RowColData::Merge().
int CountBits (uint value)
Get the number of bits set in the given value.
Parameters
value Value to inspect.
Returns
Number of set bits in the value.
Definition at line 53 of file math_func.cpp.
Referenced by Recolouring::AssignRandomColours(), CoasterBuildWindow::SetButtons(), and CoasterBuildWindow::SetupSelection().