FreeRCT: math_func.h File Reference
math_func.h File Reference
Generic computation functions.
Functions
template<typename T >
static T Clamp (const T a, const T lower, const T upper)
Clamp a value between an interval.
static int sign (int val)
Compute the sign of the argument val.
int GreatestCommonDivisor (int a, int b)
Compute greatest common divisor (gcd) of a and b.
int LeastCommonMultiple (int a, int b)
Compute least common multiple (lcm) of arguments a and b, the smallest integer value that is a multiple of both a and b.
int CountBits (uint num)
Get the number of bits set in the given value.
Detailed Description
Generic computation functions.
Definition in file math_func.h.
Function Documentation
template<typename T > static T Clamp (const T a, const T lower, const T upper) inline static
Clamp a value between an interval.
This function returns a value which is between the given interval of lower and upper. If the given value is in this interval the value itself is returned otherwise the border of the interval is returned, according which side of the interval was 'left'.
Note
The lower value must be less or equal of upper or you get some unexpected results.
Parameters
a The value to clamp/truncate.
lower The minimum of the interval.
upper the maximum of the interval.
Returns
A value between lower and upper which is closest to a.
Definition at line 33 of file math_func.h.
Referenced by Guest::ChangeHappiness(), VideoSystem::FillRectangle(), and Recolouring::GetPalette().
static int sign (int val) inline static
Compute the sign of the argument val.
Parameters
val Provided value.
Returns
The sign of the argument (-1, 0, +1).
Definition at line 46 of file math_func.h.
Referenced by Person::OnAnimate().
int GreatestCommonDivisor (int a, int b)
Compute greatest common divisor (gcd) of a and b.
Parameters
a First number.
b second number.
Returns
Greatest common divisor of a and b.
Definition at line 20 of file math_func.cpp.
Referenced by LeastCommonMultiple().
int LeastCommonMultiple (int a, int b)
Compute least common multiple (lcm) of arguments a and b, the smallest integer value that is a multiple of both a and b.
Parameters
a First number.
b second number.
Returns
Least common multiple of values a and b.
Note
This function only works for non-negative values of a and b.
Definition at line 39 of file math_func.cpp.
References GreatestCommonDivisor().
Referenced by BaseWidget::InitMinimalSize(), and RowColData::Merge().
int CountBits (uint value)
Get the number of bits set in the given value.
Parameters
value Value to inspect.
Returns
Number of set bits in the value.
Definition at line 53 of file math_func.cpp.
Referenced by Recolouring::AssignRandomColours(), CoasterBuildWindow::SetButtons(), and CoasterBuildWindow::SetupSelection().