FreeRCT: nodes.cpp File Reference
nodes.cpp File Reference
Code of the RCD file nodes.
#include "../stdafx.h"
#include <cmath>
#include "ast.h"
#include "nodes.h"
#include "string_storage.h"
#include "file_writing.h"
Functions
static const char * SkipToCurOpen (const char *p)
Find the next '{' character in the provided and return a pointer to it.
static const char * SkipSeq (const char *p)
Advance the pointer over white space, and the word "seq".
static const char * SkipChar (const char *p, char q)
Advance the pointer over white space, and the provided character q.
static const char * SkipNumber (const char *p, int *num)
Advance the pointer over white space, and read the number behind it.
static const char * SkipDotDot (const char *p)
Advance the pointer over white space, and the word "..".
static uint32 WriteSprite (std::shared_ptr< SpriteBlock > &spr, FileWriter *fw)
Write the sprite if available.
int GetLanguageIndex (const char *lname, const Position &pos)
Get the index of a language from its name.
static void RotateXY (int *dx, int *dy, int count)
Rotate relative coordinate (dx, dy) count times -90 degrees.
static int RotateFlags (int flags, int count)
Rotate the track voxel flags.
static void SetStartEnd (int index, std::shared_ptr< CubicSplines > splines, bool set_start, int value)
Set the start or the end of a bezier spline.
static void CheckBezierCount (int count, const std::shared_ptr< CubicSplines > splines, const char *name, const Position &pos)
Check the number of bezier splines against expectations, and report an error if the count is incorrect.
static void CheckSplineStepCount (int index, int steps, const std::shared_ptr< CubicSplines > splines, const char *name, const Position &pos)
Check whether the number of steps in a bezier spline matches with the expected count.
static int GetCarEntrySize (std::shared_ptr< Curve > entry)
Get the number of bytes needed for saving a curve entry.
static void RotateArray (int *abcd, int rot, int type)
Rotate the abcd array rot times, given its type.
static void SaveCarEntry (FileBlock *fb, std::shared_ptr< Curve > entry, int rot, int type)
Save a curve entry.
Variables
static const char * _languages []
Names of the known languages.
Detailed Description
Code of the RCD file nodes.
Definition in file nodes.cpp.
Function Documentation
static const char* SkipToCurOpen (const char * p) static
Find the next '{' character in the provided and return a pointer to it.
If not available, return nullptr.
Parameters
p String to search.
Returns
Pointer to '{' or nullptr.
Definition at line 123 of file nodes.cpp.
Referenced by FilePattern::SetFilename().
static const char* SkipSeq (const char * p) static
Advance the pointer over white space, and the word "seq".
Return nullptr if the word is not available.
Parameters
p String to search.
Returns
Pointer into the string, behind the "seq" word, or nullptr
Definition at line 137 of file nodes.cpp.
Referenced by FilePattern::SetFilename().
static const char* SkipChar (const char * p, char q) static
Advance the pointer over white space, and the provided character q.
Return nullptr if the character is not available.
Parameters
p String to search.
q Character to match.
Returns
Pointer into the string, behind the q character, or nullptr
Definition at line 150 of file nodes.cpp.
Referenced by FilePattern::SetFilename().
static const char* SkipNumber (const char * p, int * num) static
Advance the pointer over white space, and read the number behind it.
Return nullptr if no number is available.
Parameters
p String to search.
num [out] Value of the read number, if any.
Returns
Pointer into the string, behind the number, or nullptr
Definition at line 163 of file nodes.cpp.
Referenced by FilePattern::SetFilename().
static const char* SkipDotDot (const char * p) static
Advance the pointer over white space, and the word "..".
Return nullptr if the word is not available.
Parameters
p String to search.
Returns
Pointer into the string, behind the ".." word, or nullptr
Definition at line 183 of file nodes.cpp.
Referenced by FilePattern::SetFilename().
static uint32 WriteSprite (std::shared_ptr< SpriteBlock > & spr, FileWriter * fw) static
Write the sprite if available.
Parameters
spr Sprite to wite (if not nullptr).
fw File to write to.
Returns
0 if no sprite available, else the block number of the written sprite.
Definition at line 582 of file nodes.cpp.
Referenced by PDECBlock::Write().
int GetLanguageIndex (const char * lname, const Position & pos)
Get the index of a language from its name.
Parameters
lname Name of the language.
pos Position stating the name.
Returns
Index of the given language.
Definition at line 662 of file nodes.cpp.
References _languages, LNG_COUNT, and Position::ToString().
static void RotateXY (int * dx, int * dy, int count) static
Rotate relative coordinate (dx, dy) count times -90 degrees.
Parameters
dx [inout] X coordinate to rotate.
dy [inout] Y coordinate to rotate.
count Number of quarter rotations.
Definition at line 1219 of file nodes.cpp.
Referenced by TrackVoxel::Write(), and TrackPieceNode::Write().
static int RotateFlags (int flags, int count) static
Rotate the track voxel flags.
Parameters
flags Original flags.
count Number of quarter rotations.
Returns
The rotated flags.
Definition at line 1234 of file nodes.cpp.
Referenced by TrackVoxel::Write().
static void SetStartEnd (int index, std::shared_ptr< CubicSplines > splines, bool set_start, int value) static
Set the start or the end of a bezier spline.
Parameters
index Index in the curve denoting the bezier spline to change.
splines Curve that may be contain bezier splines, nullptr is that is not the case.
set_start If set, set the start, else set the end.
value Value to set.
Definition at line 1361 of file nodes.cpp.
static void CheckBezierCount (int count, const std::shared_ptr< CubicSplines > splines, const char * name, const Position & pos) static
Check the number of bezier splines against expectations, and report an error if the count is incorrect.
Parameters
count Expected number of bezier splines.
splines Curve that may be contain bezier splines, nullptr is that is not the case.
name Name of the curve to check.
pos Position of the track piece in the source file.
Definition at line 1395 of file nodes.cpp.
References Position::ToString().
static void CheckSplineStepCount (int index, int steps, const std::shared_ptr< CubicSplines > splines, const char * name, const Position & pos) static
Check whether the number of steps in a bezier spline matches with the expected count.
Parameters
index Index in the curve denoting the bezier spline to check.
steps Expected number of steps in the bezier spline.
splines Curve that may be contain bezier splines, nullptr is that is not the case.
name Name of the curve to check.
pos Position of the track piece in the source file.
Definition at line 1425 of file nodes.cpp.
References Position::ToString().
static int GetCarEntrySize (std::shared_ptr< Curve > entry) static
Get the number of bytes needed for saving a curve entry.
Parameters
entry Entry to save.
Returns
Number of bytes needed.
Definition at line 1508 of file nodes.cpp.
References CubicSplines::curve.
Referenced by TrackPieceNode::Write().
static void RotateArray (int * abcd, int rot, int type) static
Rotate the abcd array rot times, given its type.
Parameters
abcd [inout] Array to rotate.
rot Number of rotations to perform.
type Type of data (either 'x' or 'y').
Definition at line 1524 of file nodes.cpp.
Referenced by SaveCarEntry().
static void SaveCarEntry (FileBlock * fb, std::shared_ptr< Curve > entry, int rot, int type) static
Save a curve entry.
Parameters
fb Block to save in.
entry Entry to save.
rot Number of rotations.
type of this entry ('x' or 'y', or '-'.
Definition at line 1543 of file nodes.cpp.
References RotateArray(), FileBlock::SaveInt16(), FileBlock::SaveUInt16(), FileBlock::SaveUInt32(), and FileBlock::SaveUInt8().
Referenced by TrackPieceNode::Write().
Variable Documentation
const char* _languages[] static
Initial value:
= {
        "da_DK",
        "de_DE",
        "en_GB",
        "es_ES",
        "fr_FR",
        "nl_NL",
}
Names of the known languages.
Definition at line 647 of file nodes.cpp.
Referenced by StringBundle::CheckTranslations(), StringBundle::Fill(), GetLanguageIndex(), TextNode::GetSize(), and TextNode::Write().