FreeRCT: nodes.h File Reference
nodes.h File Reference
Declarations of the RCD nodes.
#include <string>
#include <list>
#include <vector>
#include <set>
#include <map>
#include <memory>
#include <array>
#include "image.h"
Classes
class BlockNode
Base class for all nodes.
class NamedBlock
Base class for named blocks.
class GameBlock
Base class for game blocks.
class MetaBlock
Base class for meta blocks.
class FileNode
Node representing an RCD file.
class FileNodeList
A sequence of file nodes.
class SpriteBlock
Block containing a sprite.
class FilePattern
Class for storage of a filename pattern of the form "prefix{seq(first..last,length)}suffix".
class SheetBlock
Block containing a sprite sheet.
class SpriteFilesBlock
A 'spritefiles' block.
class TSELBlock
A 'TSEL' block.
class TCORBlock
A 'TCOR' block.
class SURFBlock
Ground surface block SURF.
class FUNDBlock
Foundation game block FUND.
class Recolouring
Sprite recolouring information.
class PersonGraphics
Definition of graphics of one type of person.
class PRSGBlock
Person graphics game block.
class FrameData
ANIM frame data for a single frame.
class ANIMBlock
ANIM game block.
class ANSPBlock
ANSP game block.
class PATHBlock
PATH game block.
class PDECBlock
Path decoration PDEC block.
class PLATBlock
PLAT game block.
class SUPPBlock
SUPP game block.
class StringNode
Storage of a single string (name + text + language if present).
class StringsNode
Collection of strings.
class TextNode
Texts (translations) of a single string.
class StringBundle
Collection of translated strings for a game object.
class SHOPBlock
Class for describing a SHOP game block.
class GBORBlock
GBOR game block.
class GCHKBlock
GCHK game block.
class GSLIBlock
GSLI game block.
class GSCLBlock
GSCL game block.
class BDIRBlock
BDIR game block.
class GSLPBlock
GSLP Game block.
class CubicSpline
Class for storing a cubic bezier spline, as (part of) a path in a track piece.
class Curve
Base class of a curved path for a coaster car.
class CubicSplines
Curve described by a segmented cubic bezier spline.
class FixedTable
Curve that is always the same value.
struct TrackVoxel
Class for storing the data of a single voxel in a track piece.
class Connection
Class for storing a 'connection' between track pieces.
class TrackPieceNode
A 'track_piece' block.
class RCSTBlock
'RCST' game block.
class CARSBlock
'CARS' game block.
class BitMask
Node block containing a bitmask.
class CSPLBlock
'CSPL' game block.
class FENCBlock
'FENC' game block.
class INFOBlock
'INFO' eta block.
Enumerations
enum SurfaceSprites {
SF_FLAT, SF_N, SF_E, SF_NE,
SF_S, SF_NS, SF_ES, SF_NES,
SF_W, SF_WN, SF_WE, SF_WNE,
SF_WS, SF_WNS, SF_WES, SF_STEEP_NB,
SF_STEEP_EB, SF_STEEP_SB, SF_STEEP_WB, SF_STEEP_NT,
SF_STEEP_ET, SF_STEEP_ST, SF_STEEP_WT, SURFACE_COUNT
}
Sprites of a surface.
enum FoundationSprites {
FND_SE_E0, FND_SE_0S, FND_SE_ES, FND_SW_S0,
FND_SW_0W, FND_SW_SW, FOUNDATION_COUNT
}
Sprites of a foundation.
enum ColourRange {
COL_RANGE_GREY, COL_RANGE_GREEN_BROWN, COL_RANGE_ORANGE_BROWN, COL_RANGE_YELLOW,
COL_RANGE_DARK_RED, COL_RANGE_DARK_GREEN, COL_RANGE_LIGHT_GREEN, COL_RANGE_GREEN,
COL_RANGE_PINK_BROWN, COL_RANGE_DARK_PURPLE, COL_RANGE_BLUE, COL_RANGE_DARK_JADE_GREEN,
COL_RANGE_PURPLE, COL_RANGE_RED, COL_RANGE_ORANGE, COL_RANGE_SEA_GREEN,
COL_RANGE_PINK, COL_RANGE_BROWN, COL_RANGE_COUNT, COL_RANGE_INVALID = 0xff,
COL_GREY, COL_GREEN_BROWN, COL_ORANGE_BROWN, COL_YELLOW,
COL_DARK_RED, COL_DARK_GREEN, COL_LIGHT_GREEN, COL_GREEN,
COL_PINK_BROWN, COL_DARK_PURPLE, COL_BLUE, COL_DARK_JADE_GREEN,
COL_PURPLE, COL_RED, COL_ORANGE, COL_SEA_GREEN,
COL_PINK, COL_BROWN, COLOUR_COUNT
}
Colour ranges.
enum PathSprites {
PATH_EMPTY, PATH_NE, PATH_SE, PATH_NE_SE,
PATH_NE_SE_E, PATH_SW, PATH_NE_SW, PATH_SE_SW,
PATH_SE_SW_S, PATH_NE_SE_SW, PATH_NE_SE_SW_E, PATH_NE_SE_SW_S,
PATH_NE_SE_SW_E_S, PATH_NW, PATH_NE_NW, PATH_NE_NW_N,
PATH_NW_SE, PATH_NE_NW_SE, PATH_NE_NW_SE_N, PATH_NE_NW_SE_E,
PATH_NE_NW_SE_N_E, PATH_NW_SW, PATH_NW_SW_W, PATH_NE_NW_SW,
PATH_NE_NW_SW_N, PATH_NE_NW_SW_W, PATH_NE_NW_SW_N_W, PATH_NW_SE_SW,
PATH_NW_SE_SW_S, PATH_NW_SE_SW_W, PATH_NW_SE_SW_S_W, PATH_NE_NW_SE_SW,
PATH_NE_NW_SE_SW_N, PATH_NE_NW_SE_SW_E, PATH_NE_NW_SE_SW_N_E, PATH_NE_NW_SE_SW_S,
PATH_NE_NW_SE_SW_N_S, PATH_NE_NW_SE_SW_E_S, PATH_NE_NW_SE_SW_N_E_S, PATH_NE_NW_SE_SW_W,
PATH_NE_NW_SE_SW_N_W, PATH_NE_NW_SE_SW_E_W, PATH_NE_NW_SE_SW_N_E_W, PATH_NE_NW_SE_SW_S_W,
PATH_NE_NW_SE_SW_N_S_W, PATH_NE_NW_SE_SW_E_S_W, PATH_NE_NW_SE_SW_N_E_S_W, PATH_FLAT_COUNT,
PATH_RAMP_NE = PATH_FLAT_COUNT, PATH_RAMP_NW, PATH_RAMP_SE, PATH_RAMP_SW,
PATH_COUNT, PATH_INVALID = 63, PATHBIT_N = 0, PATHBIT_E = 1,
PATHBIT_S = 2, PATHBIT_W = 3, PATHBIT_NE = 4, PATHBIT_SE = 5,
PATHBIT_SW = 6, PATHBIT_NW = 7, PATHMASK_NE = 1 << PATHBIT_NE, PATHMASK_SE = 1 << PATHBIT_SE,
PATHMASK_SW = 1 << PATHBIT_SW, PATHMASK_NW = 1 << PATHBIT_NW, PATHMASK_EDGES = PATHMASK_NE | PATHMASK_SE | PATHMASK_SW | PATHMASK_NW, PTS_EMPTY,
PTS_NE, PTS_SE, PTS_NE_SE, PTS_NE_SE_E,
PTS_SW, PTS_NE_SW, PTS_SE_SW, PTS_SE_SW_S,
PTS_NE_SE_SW, PTS_NE_SE_SW_E, PTS_NE_SE_SW_S, PTS_NE_SE_SW_E_S,
PTS_NW, PTS_NE_NW, PTS_NE_NW_N, PTS_NW_SE,
PTS_NE_NW_SE, PTS_NE_NW_SE_N, PTS_NE_NW_SE_E, PTS_NE_NW_SE_N_E,
PTS_NW_SW, PTS_NW_SW_W, PTS_NE_NW_SW, PTS_NE_NW_SW_N,
PTS_NE_NW_SW_W, PTS_NE_NW_SW_N_W, PTS_NW_SE_SW, PTS_NW_SE_SW_S,
PTS_NW_SE_SW_W, PTS_NW_SE_SW_S_W, PTS_NE_NW_SE_SW, PTS_NE_NW_SE_SW_N,
PTS_NE_NW_SE_SW_E, PTS_NE_NW_SE_SW_N_E, PTS_NE_NW_SE_SW_S, PTS_NE_NW_SE_SW_N_S,
PTS_NE_NW_SE_SW_E_S, PTS_NE_NW_SE_SW_N_E_S, PTS_NE_NW_SE_SW_W, PTS_NE_NW_SE_SW_N_W,
PTS_NE_NW_SE_SW_E_W, PTS_NE_NW_SE_SW_N_E_W, PTS_NE_NW_SE_SW_S_W, PTS_NE_NW_SE_SW_N_S_W,
PTS_NE_NW_SE_SW_E_S_W, PTS_NE_NW_SE_SW_N_E_S_W, PTS_NE_EDGE_UP, PTS_NW_EDGE_UP,
PTS_SE_EDGE_UP, PTS_SW_EDGE_UP, PTS_COUNT
}
Path sprites.
enum PlatformSprites {
PLA_NS, PLA_EW, PLA_RAMP_NE, PLA_RAMP_SE,
PLA_RAMP_SW, PLA_RAMP_NW, PLA_RIGHT_RAMP_NE, PLA_RIGHT_RAMP_SE,
PLA_RIGHT_RAMP_SW, PLA_RIGHT_RAMP_NW, PLA_LEFT_RAMP_NE, PLA_LEFT_RAMP_SE,
PLA_LEFT_RAMP_SW, PLA_LEFT_RAMP_NW, PLA_COUNT
}
Platform sprites.
enum SupportSprites {
SPP_S_NS, SPP_S_EW, SPP_D_NS, SPP_D_EW,
SPP_P_NS, SPP_P_EW, SPP_N, SPP_E,
SPP_NE, SPP_S, SPP_NS, SPP_ES,
SPP_NES, SPP_W, SPP_NW, SPP_EW,
SPP_NEW, SPP_SW, SPP_NSW, SPP_ESW,
SPP_STEEP_N, SPP_STEEP_E, SPP_STEEP_S, SPP_STEEP_W,
SPP_COUNT, SSP_FLAT_SINGLE_NS, SSP_FLAT_SINGLE_EW, SSP_FLAT_DOUBLE_NS,
SSP_FLAT_DOUBLE_EW, SSP_FLAT_PATH_NS, SSP_FLAT_PATH_EW, SSP_N,
SSP_E, SSP_NE, SSP_S, SSP_NS,
SSP_ES, SSP_NES, SSP_W, SSP_NW,
SSP_EW, SSP_NEW, SSP_SW, SSP_NSW,
SSP_ESW, SSP_STEEP_N, SSP_STEEP_E, SSP_STEEP_S,
SSP_STEEP_W, SSP_COUNT, SSP_NONFLAT_BASE = SSP_FLAT_PATH_EW
}
Sprites of the supports.
enum Languages {
LANG_DA_DK, LANG_DE_DE, LANG_EN_GB, LANG_ES_ES,
LANG_FR_FR, LANG_NL_NL, LANGUAGE_COUNT, LNG_DA_DK,
LNG_DE_DE, LNG_EN_GB, LNG_ES_ES, LNG_FR_FR,
LNG_NL_NL, LNG_COUNT
}
Known languages.
Functions
int GetLanguageIndex (const char *lname, const Position &pos)
Get the index of a language from its name.
FileNodeList * CheckTree (std::shared_ptr< NamedValueList > values)
Check and convert the tree to nodes.
void GenerateStringsHeaderFile (const char *prefix, const char *base, const char *header)
Generate a header file with string names.
void GenerateStringsCodeFile (const char *prefix, const char *code)
Generate a code file with string names.
Detailed Description
Declarations of the RCD nodes.
Definition in file nodes.h.
Enumeration Type Documentation
enum SurfaceSprites
Sprites of a surface.
Enumerator
SF_FLAT
Flat surface tile.
SF_N
North corner up.
SF_E
East corner up.
SF_NE
North, east corners up.
SF_S
South corner up.
SF_NS
North, south corners up.
SF_ES
East, south corners up.
SF_NES
North, east, south corners up.
SF_W
West corner up.
SF_WN
West, north corners up.
SF_WE
West, east corners up.
SF_WNE
West, north, east corners up.
SF_WS
West, south corners up.
SF_WNS
West, north, south corners up.
SF_WES
West, east, south corners up.
SF_STEEP_NB
Steep north slope bottom.
SF_STEEP_EB
Steep east slope bottom.
SF_STEEP_SB
Steep south slope bottom.
SF_STEEP_WB
Steep west slope bottom.
SF_STEEP_NT
Steep north slope top.
SF_STEEP_ET
Steep east slope top.
SF_STEEP_ST
Steep south slope top.
SF_STEEP_WT
Steep west slope top.
SURFACE_COUNT
Number of tiles in a surface.
Definition at line 76 of file nodes.h.
enum FoundationSprites
Sprites of a foundation.
Enumerator
FND_SE_E0
Vertical south-east foundation, east visible, south down.
FND_SE_0S
Vertical south-east foundation, east down, south visible.
FND_SE_ES
Vertical south-east foundation, east visible, south visible.
FND_SW_S0
Vertical south-west foundation, south visible, west down.
FND_SW_0W
Vertical south-west foundation, south down, west visible.
FND_SW_SW
Vertical south-west foundation, south visible, west visible.
FOUNDATION_COUNT
Number of foundation sprites.
Definition at line 222 of file nodes.h.
enum ColourRange
Colour ranges.
Enumerator
COL_RANGE_COUNT
Number of colour ranges.
COL_RANGE_INVALID
Number denoting an invalid colour range.
COL_GREY
Colour range for grey.
COL_GREEN_BROWN
Colour range for green_brown.
COL_ORANGE_BROWN
Colour range for orange_brown.
COL_YELLOW
Colour range for yellow.
COL_DARK_RED
Colour range for dark_red.
COL_DARK_GREEN
Colour range for dark_green.
COL_LIGHT_GREEN
Colour range for light_green.
COL_GREEN
Colour range for green.
COL_PINK_BROWN
Colour range for pink_brown.
COL_DARK_PURPLE
Colour range for dark_purple.
COL_BLUE
Colour range for blue.
COL_DARK_JADE_GREEN
Colour range for jade_green.
COL_PURPLE
Colour range for purple.
COL_RED
Colour range for red.
COL_ORANGE
Colour range for orange.
COL_SEA_GREEN
Colour range for sea_green.
COL_PINK
Colour range for pink.
COL_BROWN
Colour range for brown.
COLOUR_COUNT
Number of colour ranges.
Definition at line 247 of file nodes.h.
enum PathSprites
Path sprites.
Enumerator
PATH_EMPTY
Path without edges or corners.
PATH_FLAT_COUNT
Number of flat path sprites.
PATH_RAMP_NE
Ramp from NE up to SW.
PATH_RAMP_NW
Ramp from NW up to SE.
PATH_RAMP_SE
Ramp from SE up to NW.
PATH_RAMP_SW
Ramp from SW up to NE.
PATH_COUNT
Number of path sprites.
PATH_INVALID
Invalid path. Also used to indicate reserved voxels above paths.
PATHBIT_N
Bit number for north corner in expanded notation.
PATHBIT_E
Bit number for east corner in expanded notation.
PATHBIT_S
Bit number for south corner in expanded notation.
PATHBIT_W
Bit number for west corner in expanded notation.
PATHBIT_NE
Bit number for north-east edge in expanded notation.
PATHBIT_SE
Bit number for south-east edge in expanded notation.
PATHBIT_SW
Bit number for south-west edge in expanded notation.
PATHBIT_NW
Bit number for north-west edge in expanded notation.
PATHMASK_NE
Mask for masking PATHBIT_NE.
PATHMASK_SE
Mask for masking PATHBIT_SE.
PATHMASK_SW
Mask for masking PATHBIT_SW.
PATHMASK_NW
Mask for masking PATHBIT_NW.
PATHMASK_EDGES
Mask for masking the expanded path edges.
PTS_EMPTY
EMPTY.
PTS_NE
NE.
PTS_SE
SE.
PTS_NE_SE
NE_SE.
PTS_NE_SE_E
NE_SE_E.
PTS_SW
SW.
PTS_NE_SW
NE_SW.
PTS_SE_SW
SE_SW.
PTS_SE_SW_S
SE_SW_S.
PTS_NE_SE_SW
NE_SE_SW.
PTS_NE_SE_SW_E
NE_SE_SW_E.
PTS_NE_SE_SW_S
NE_SE_SW_S.
PTS_NE_SE_SW_E_S
NE_SE_SW_E_S.
PTS_NW
NW.
PTS_NE_NW
NE_NW.
PTS_NE_NW_N
NE_NW_N.
PTS_NW_SE
NW_SE.
PTS_NE_NW_SE
NE_NW_SE.
PTS_NE_NW_SE_N
NE_NW_SE_N.
PTS_NE_NW_SE_E
NE_NW_SE_E.
PTS_NE_NW_SE_N_E
NE_NW_SE_N_E.
PTS_NW_SW
NW_SW.
PTS_NW_SW_W
NW_SW_W.
PTS_NE_NW_SW
NE_NW_SW.
PTS_NE_NW_SW_N
NE_NW_SW_N.
PTS_NE_NW_SW_W
NE_NW_SW_W.
PTS_NE_NW_SW_N_W
NE_NW_SW_N_W.
PTS_NW_SE_SW
NW_SE_SW.
PTS_NW_SE_SW_S
NW_SE_SW_S.
PTS_NW_SE_SW_W
NW_SE_SW_W.
PTS_NW_SE_SW_S_W
NW_SE_SW_S_W.
PTS_NE_NW_SE_SW
NE_NW_SE_SW.
PTS_NE_NW_SE_SW_N
NE_NW_SE_SW_N.
PTS_NE_NW_SE_SW_E
NE_NW_SE_SW_E.
PTS_NE_NW_SE_SW_N_E
NE_NW_SE_SW_N_E.
PTS_NE_NW_SE_SW_S
NE_NW_SE_SW_S.
PTS_NE_NW_SE_SW_N_S
NE_NW_SE_SW_N_S.
PTS_NE_NW_SE_SW_E_S
NE_NW_SE_SW_E_S.
PTS_NE_NW_SE_SW_N_E_S
NE_NW_SE_SW_N_E_S.
PTS_NE_NW_SE_SW_W
NE_NW_SE_SW_W.
PTS_NE_NW_SE_SW_N_W
NE_NW_SE_SW_N_W.
PTS_NE_NW_SE_SW_E_W
NE_NW_SE_SW_E_W.
PTS_NE_NW_SE_SW_N_E_W
NE_NW_SE_SW_N_E_W.
PTS_NE_NW_SE_SW_S_W
NE_NW_SE_SW_S_W.
PTS_NE_NW_SE_SW_N_S_W
NE_NW_SE_SW_N_S_W.
PTS_NE_NW_SE_SW_E_S_W
NE_NW_SE_SW_E_S_W.
PTS_NE_NW_SE_SW_N_E_S_W
NE_NW_SE_SW_N_E_S_W.
PTS_NE_EDGE_UP
NE_EDGE_UP.
PTS_NW_EDGE_UP
NW_EDGE_UP.
PTS_SE_EDGE_UP
SE_EDGE_UP.
PTS_SW_EDGE_UP
SW_EDGE_UP.
PTS_COUNT
Number of path sprites.
Definition at line 336 of file nodes.h.
enum PlatformSprites
Platform sprites.
Enumerator
PLA_NS
Flat platform for north and south view.
PLA_EW
Flat platform for east and west view.
PLA_RAMP_NE
Platform with two legs is raised at the NE edge.
PLA_RAMP_SE
Platform with two legs is raised at the SE edge.
PLA_RAMP_SW
Platform with two legs is raised at the SW edge.
PLA_RAMP_NW
Platform with two legs is raised at the NW edge.
PLA_RIGHT_RAMP_NE
Platform with right leg is raised at the NE edge.
PLA_RIGHT_RAMP_SE
Platform with right leg is raised at the SE edge.
PLA_RIGHT_RAMP_SW
Platform with right leg is raised at the SW edge.
PLA_RIGHT_RAMP_NW
Platform with right leg is raised at the NW edge.
PLA_LEFT_RAMP_NE
Platform with left leg is raised at the NE edge.
PLA_LEFT_RAMP_SE
Platform with left leg is raised at the SE edge.
PLA_LEFT_RAMP_SW
Platform with left leg is raised at the SW edge.
PLA_LEFT_RAMP_NW
Platform with left leg is raised at the NW edge.
PLA_COUNT
Number of platform sprites.
Definition at line 434 of file nodes.h.
enum SupportSprites
Sprites of the supports.
Enumerator
SPP_S_NS
Single height for flat terrain, north and south view.
SPP_S_EW
Single height for flat terrain, east and west view.
SPP_D_NS
Double height for flat terrain, north and south view.Double height for flat terrain, east and west view.
SPP_D_EW
Double height for flat terrain, east and west view.
SPP_P_NS
Double height for paths, north and south view.
SPP_P_EW
Double height for paths, east and west view.
SPP_N
Single height, north leg up.
SPP_E
Single height, east leg up.
SPP_NE
Single height, north, east legs up.
SPP_S
Single height, south leg up.
SPP_NS
Single height, north, south legs up.
SPP_ES
Single height, east, south legs up.
SPP_NES
Single height, north, east, south legs up.
SPP_W
Single height, west leg up.
SPP_NW
Single height, west, north legs up.
SPP_EW
Single height, west, east legs up.
SPP_NEW
Single height, west, north, east legs up.
SPP_SW
Single height, west, south legs up.
SPP_NSW
Single height, west, north, south legs up.
SPP_ESW
Single height, west, east, south legs up.
SPP_STEEP_N
Double height for steep north slope.
SPP_STEEP_E
Double height for steep east slope.
SPP_STEEP_S
Double height for steep south slope.
SPP_STEEP_W
Double height for steep west slope.
SPP_COUNT
Number of support sprites.
SSP_FLAT_SINGLE_NS
Single height for flat terrain, north and south view.
SSP_FLAT_SINGLE_EW
Single height for flat terrain, east and west view.
SSP_FLAT_DOUBLE_NS
Double height for flat terrain, north and south view.
SSP_FLAT_DOUBLE_EW
Double height for flat terrain, east and west view.
SSP_FLAT_PATH_NS
Double height for paths, north and south view.
SSP_FLAT_PATH_EW
Double height for paths, east and west view.
SSP_N
Single height, north leg up.
SSP_E
Single height, east leg up.
SSP_NE
Single height, north, east legs up.
SSP_S
Single height, south leg up.
SSP_NS
Single height, north, south legs up.
SSP_ES
Single height, east, south legs up.
SSP_NES
Single height, north, east, south legs up.
SSP_W
Single height, west leg up.
SSP_NW
Single height, west, north legs up.
SSP_EW
Single height, west, east legs up.
SSP_NEW
Single height, west, north, east legs up.
SSP_SW
Single height, west, south legs up.
SSP_NSW
Single height, west, north, south legs up.
SSP_ESW
Single height, west, east, south legs up.
SSP_STEEP_N
Double height for steep north slope.
SSP_STEEP_E
Double height for steep east slope.
SSP_STEEP_S
Double height for steep south slope.
SSP_STEEP_W
Double height for steep west slope.
SSP_COUNT
Number of support sprites.
SSP_NONFLAT_BASE
Base sprite for non-flat ground slopes.
Definition at line 468 of file nodes.h.
enum Languages
Known languages.
Enumerator
LANG_DA_DK
Danish.
LANG_DE_DE
German.
LANG_EN_GB
British English.
LANG_ES_ES
Spanish.
LANG_FR_FR
French.
LANG_NL_NL
Dutch.
LANGUAGE_COUNT
Number of available languages.
LNG_DA_DK
da_DK language.
LNG_DE_DE
de_DE language.
LNG_EN_GB
en_GB language (default).
LNG_ES_ES
es_ES language.
LNG_FR_FR
fr_FR language.
LNG_NL_NL
nl_NL language.
LNG_COUNT
Number of known languages.
Definition at line 512 of file nodes.h.
Function Documentation
int GetLanguageIndex (const char * lname, const Position & pos)
Get the index of a language from its name.
Parameters
lname Name of the language.
pos Position stating the name.
Returns
Index of the given language.
Definition at line 662 of file nodes.cpp.
References _languages, LNG_COUNT, and Position::ToString().
FileNodeList* CheckTree (std::shared_ptr< NamedValueList > values)
Check and convert the tree to nodes.
Parameters
values Root node of the tree.
Returns
The converted and checked sequence of file data to write.
Definition at line 2485 of file check_data.cpp.
References _foundation_sprite, _strings_storage, _surface_sprite, StringsStorage::AddStrings(), FileNodeList::files, FOUNDATION_COUNT, Values::PrepareNamedValues(), SURFACE_COUNT, Values::unnamed_count, Values::unnamed_values, and Values::VerifyUsage().
Referenced by main().
void GenerateStringsHeaderFile (const char * prefix, const char * base, const char * header)
Generate a header file with string names.
Parameters
prefix Kind of strings (either "GUI" or "SHOPS").
base Value of the first entry.
header Name of the output header file.
Definition at line 2523 of file check_data.cpp.
References _coaster_string_names, _gui_string_names, _shops_string_names, and lengthof.
Referenced by main().
void GenerateStringsCodeFile (const char * prefix, const char * code)
Generate a code file with string names.
Parameters
prefix Kind of strings (either "GUI" or "SHOPS").
code Name of the output code file.
Definition at line 2579 of file check_data.cpp.
References _coaster_string_names, _gui_string_names, _shops_string_names, and lengthof.
Referenced by main().