FreeRCT: palette.h File Reference
palette.h File Reference
8bpp palette definitions.
Classes
struct RecolourEntry
A recolour entry, defining a source colour range to replace with the dest colour range, where dest must be in dest_set.
class Recolouring
Sprite recolouring information.
Typedefs
typedef uint8(* ShiftFunc)(uint8)
Type of the gradient shift function.
Enumerations
enum ColourRange {
COL_RANGE_GREY, COL_RANGE_GREEN_BROWN, COL_RANGE_ORANGE_BROWN, COL_RANGE_YELLOW,
COL_RANGE_DARK_RED, COL_RANGE_DARK_GREEN, COL_RANGE_LIGHT_GREEN, COL_RANGE_GREEN,
COL_RANGE_PINK_BROWN, COL_RANGE_DARK_PURPLE, COL_RANGE_BLUE, COL_RANGE_DARK_JADE_GREEN,
COL_RANGE_PURPLE, COL_RANGE_RED, COL_RANGE_ORANGE, COL_RANGE_SEA_GREEN,
COL_RANGE_PINK, COL_RANGE_BROWN, COL_RANGE_COUNT, COL_RANGE_INVALID = 0xff,
COL_GREY, COL_GREEN_BROWN, COL_ORANGE_BROWN, COL_YELLOW,
COL_DARK_RED, COL_DARK_GREEN, COL_LIGHT_GREEN, COL_GREEN,
COL_PINK_BROWN, COL_DARK_PURPLE, COL_BLUE, COL_DARK_JADE_GREEN,
COL_PURPLE, COL_RED, COL_ORANGE, COL_SEA_GREEN,
COL_PINK, COL_BROWN, COLOUR_COUNT
}
Names of colour ranges.
enum GuiTextColours { TEXT_BLACK = 0, TEXT_WHITE = 1 }
Gui text colours.
enum PaletteColours {
COL_BACKGROUND = 0, COL_HIGHLIGHT = 1, COL_SERIES_START = 10, COL_SERIES_LENGTH = 12,
COL_SERIES_END = COL_SERIES_START + COL_RANGE_COUNT * COL_SERIES_LENGTH
}
Colours.
enum GradientShift {
GS_NIGHT, GS_VERY_DARK, GS_DARK, GS_SLIGHTLY_DARK,
GS_NORMAL, GS_SLIGHTLY_LIGHT, GS_LIGHT, GS_VERY_LIGHT,
GS_DAY, GS_COUNT, GS_INVALID = 0xff
}
Shifting of the gradient to make the sprite lighter or darker.
Functions
static uint32 MakeRGBA (uint8 r, uint8 g, uint8 b, uint8 a)
Construct a 32bpp pixel value from its components.
static uint8 GetR (uint32 rgba)
Retrieve the redness of the provided pixel value.
static uint8 GetG (uint32 rgba)
Retrieve the greenness of the provided pixel value.
static uint8 GetB (uint32 rgba)
Retrieve the blueness of the provided pixel value.
static uint8 GetA (uint32 rgba)
Retrieve the opaqueness of the provided pixel value.
static uint32 SetA (uint32 rgba, uint8 opacity)
Set the opaqueness of the provided colour.
static uint8 ShiftGradientNight (uint8 col)
Gradient shift function for GS_NIGHT.
static uint8 ShiftGradientVeryDark (uint8 col)
Gradient shift function for GS_VERY_DARK.
static uint8 ShiftGradientDark (uint8 col)
Gradient shift function for GS_DARK.
static uint8 ShiftGradientSlightlyDark (uint8 col)
Gradient shift function for GS_SLIGHTLY_DARK.
static uint8 ShiftGradientNormal (uint8 col)
Gradient shift function for GS_NORMAL.
static uint8 ShiftGradientSlightlyLight (uint8 col)
Gradient shift function for GS_SLIGHTLY_LIGHT.
static uint8 ShiftGradientLight (uint8 col)
Gradient shift function for GS_LIGHT.
static uint8 ShiftGradientVeryLight (uint8 col)
Gradient shift function for GS_VERY_LIGHT.
static uint8 ShiftGradientDay (uint8 col)
Gradient shift function for GS_DAY.
static ShiftFunc GetGradientShiftFunc (GradientShift shift)
Select gradient shift function based on the shift.
uint8 GetColourRangeBase (ColourRange cr)
Get the index of the base colour of a colour range.
Variables
const uint32 _palette [256]
The 8bpp FreeRCT palette.
const uint32 *const _recolour_palettes [18]
32bpp recolour tables.
static const uint8 TRANSPARENT = 0
Opacity value of a fully transparent pixel.
static const uint8 OPAQUE = 255
Opacity value of a fully opaque pixel.
static const int MAX_RECOLOUR = 4
Maximum number of recolourings that can be defined in a Recolouring class.
static const int STEP_SIZE = 18
Amount of colour shift for each gradient step.
Detailed Description
8bpp palette definitions.
Definition in file palette.h.
Enumeration Type Documentation
enum ColourRange
Names of colour ranges.
Enumerator
COL_RANGE_COUNT
Number of colour ranges.
COL_RANGE_INVALID
Number denoting an invalid colour range.
COL_GREY
Colour range for grey.
COL_GREEN_BROWN
Colour range for green_brown.
COL_ORANGE_BROWN
Colour range for orange_brown.
COL_YELLOW
Colour range for yellow.
COL_DARK_RED
Colour range for dark_red.
COL_DARK_GREEN
Colour range for dark_green.
COL_LIGHT_GREEN
Colour range for light_green.
COL_GREEN
Colour range for green.
COL_PINK_BROWN
Colour range for pink_brown.
COL_DARK_PURPLE
Colour range for dark_purple.
COL_BLUE
Colour range for blue.
COL_DARK_JADE_GREEN
Colour range for jade_green.
COL_PURPLE
Colour range for purple.
COL_RED
Colour range for red.
COL_ORANGE
Colour range for orange.
COL_SEA_GREEN
Colour range for sea_green.
COL_PINK
Colour range for pink.
COL_BROWN
Colour range for brown.
COLOUR_COUNT
Number of colour ranges.
Definition at line 90 of file palette.h.
enum GuiTextColours
Gui text colours.
Enumerator
TEXT_BLACK
Black text colour.
TEXT_WHITE
White text colour.
Definition at line 115 of file palette.h.
enum PaletteColours
Colours.
Enumerator
COL_BACKGROUND
Index of background behind the world display.
COL_HIGHLIGHT
Index of window highlighting edge colour when (re)opening.
COL_SERIES_START
Index of the first series.
COL_SERIES_LENGTH
Number of shades in a single run.
COL_SERIES_END
First colour after the series.
Definition at line 121 of file palette.h.
enum GradientShift
Shifting of the gradient to make the sprite lighter or darker.
Enumerator
GS_NIGHT
Shift gradient four steps darker.
GS_VERY_DARK
Shift gradient three steps darker.
GS_DARK
Shift gradient two steps darker.
GS_SLIGHTLY_DARK
Shift gradient one step darker.
GS_NORMAL
No change in gradient.
GS_SLIGHTLY_LIGHT
Shift gradient one step lighter.
GS_LIGHT
Shift gradient two steps lighter.
GS_VERY_LIGHT
Shift gradient three steps lighter.
GS_DAY
Shift gradient four steps lighter.
GS_COUNT
Number of gradient shifts.
GS_INVALID
Invalid gradient shift.
Definition at line 131 of file palette.h.
Function Documentation
static uint32 MakeRGBA (uint8 r, uint8 g, uint8 b, uint8 a) inline static
Construct a 32bpp pixel value from its components.
Parameters
r Intensity of the red colour component.
g Intensity of the green colour component.
b Intensity of the blue colour component.
a Opacity of the pixel.
Returns
Pixel value of the given combination of colour components.
Definition at line 33 of file palette.h.
Referenced by Blit32bppImages(), DrawString(), TerraformGui::DrawWidget(), DropdownMenuWindow::DrawWidget(), ImageData::GetPixel(), GuiWindow::OnDraw(), Viewport::OnDraw(), and UpdateWindows().
static uint8 GetR (uint32 rgba) inline static
Retrieve the redness of the provided pixel value.
Parameters
rgba Pixel value to examine.
Returns
Redness of the examined pixel.
Definition at line 43 of file palette.h.
Referenced by Blit32bppImages(), and ImageData::GetPixel().
static uint8 GetG (uint32 rgba) inline static
Retrieve the greenness of the provided pixel value.
Parameters
rgba Pixel value to examine.
Returns
Greenness of the examined pixel.
Definition at line 53 of file palette.h.
Referenced by Blit32bppImages(), and ImageData::GetPixel().
static uint8 GetB (uint32 rgba) inline static
Retrieve the blueness of the provided pixel value.
Parameters
rgba Pixel value to examine.
Returns
Blueness of the examined pixel.
Definition at line 63 of file palette.h.
Referenced by Blit32bppImages(), and ImageData::GetPixel().
static uint8 GetA (uint32 rgba) inline static
Retrieve the opaqueness of the provided pixel value.
Parameters
rgba Pixel value to examine.
Returns
Opaqueness of the examined pixel.
Definition at line 73 of file palette.h.
Referenced by PixelFinder::CollectVoxel().
static uint32 SetA (uint32 rgba, uint8 opacity) inline static
Set the opaqueness of the provided colour.
Parameters
rgba Colour value to change.
opacity Opaqueness to set.
Returns
The combined pixel value.
Definition at line 84 of file palette.h.
static uint8 ShiftGradientNight (uint8 col) inline static
Gradient shift function for GS_NIGHT.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 154 of file palette.h.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientVeryDark (uint8 col) inline static
Gradient shift function for GS_VERY_DARK.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 164 of file palette.h.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientDark (uint8 col) inline static
Gradient shift function for GS_DARK.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 174 of file palette.h.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientSlightlyDark (uint8 col) inline static
Gradient shift function for GS_SLIGHTLY_DARK.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 184 of file palette.h.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientNormal (uint8 col) inline static
Gradient shift function for GS_NORMAL.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 194 of file palette.h.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientSlightlyLight (uint8 col) inline static
Gradient shift function for GS_SLIGHTLY_LIGHT.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 204 of file palette.h.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientLight (uint8 col) inline static
Gradient shift function for GS_LIGHT.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 214 of file palette.h.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientVeryLight (uint8 col) inline static
Gradient shift function for GS_VERY_LIGHT.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 224 of file palette.h.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientDay (uint8 col) inline static
Gradient shift function for GS_DAY.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 234 of file palette.h.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static ShiftFunc GetGradientShiftFunc (GradientShift shift) inline static
Select gradient shift function based on the shift.
Parameters
shift Desired amount of gradient shift.
Returns
Recolour function implementing the shift.
Definition at line 244 of file palette.h.
References GS_DARK, GS_DAY, GS_LIGHT, GS_NIGHT, GS_NORMAL, GS_SLIGHTLY_DARK, GS_SLIGHTLY_LIGHT, GS_VERY_DARK, GS_VERY_LIGHT, NOT_REACHED, ShiftGradientDark(), ShiftGradientDay(), ShiftGradientLight(), ShiftGradientNight(), ShiftGradientNormal(), ShiftGradientSlightlyDark(), ShiftGradientSlightlyLight(), ShiftGradientVeryDark(), and ShiftGradientVeryLight().
Referenced by Blit32bppImages(), and ImageData::GetPixel().
uint8 GetColourRangeBase (ColourRange cr) inline
Get the index of the base colour of a colour range.
Parameters
cr Colour range to use.
Returns
Palette index of the first colour of the given colour range.
Definition at line 265 of file palette.h.
References COL_SERIES_LENGTH, and COL_SERIES_START.
Referenced by DropdownMenuWindow::DrawWidget(), and Recolouring::GetPalette().