FreeRCT: path.h File Reference
path.h File Reference
Path definitions.
#include "tile.h"
Enumerations
enum PathSprites {
PATH_EMPTY, PATH_NE, PATH_SE, PATH_NE_SE,
PATH_NE_SE_E, PATH_SW, PATH_NE_SW, PATH_SE_SW,
PATH_SE_SW_S, PATH_NE_SE_SW, PATH_NE_SE_SW_E, PATH_NE_SE_SW_S,
PATH_NE_SE_SW_E_S, PATH_NW, PATH_NE_NW, PATH_NE_NW_N,
PATH_NW_SE, PATH_NE_NW_SE, PATH_NE_NW_SE_N, PATH_NE_NW_SE_E,
PATH_NE_NW_SE_N_E, PATH_NW_SW, PATH_NW_SW_W, PATH_NE_NW_SW,
PATH_NE_NW_SW_N, PATH_NE_NW_SW_W, PATH_NE_NW_SW_N_W, PATH_NW_SE_SW,
PATH_NW_SE_SW_S, PATH_NW_SE_SW_W, PATH_NW_SE_SW_S_W, PATH_NE_NW_SE_SW,
PATH_NE_NW_SE_SW_N, PATH_NE_NW_SE_SW_E, PATH_NE_NW_SE_SW_N_E, PATH_NE_NW_SE_SW_S,
PATH_NE_NW_SE_SW_N_S, PATH_NE_NW_SE_SW_E_S, PATH_NE_NW_SE_SW_N_E_S, PATH_NE_NW_SE_SW_W,
PATH_NE_NW_SE_SW_N_W, PATH_NE_NW_SE_SW_E_W, PATH_NE_NW_SE_SW_N_E_W, PATH_NE_NW_SE_SW_S_W,
PATH_NE_NW_SE_SW_N_S_W, PATH_NE_NW_SE_SW_E_S_W, PATH_NE_NW_SE_SW_N_E_S_W, PATH_FLAT_COUNT,
PATH_RAMP_NE = PATH_FLAT_COUNT, PATH_RAMP_NW, PATH_RAMP_SE, PATH_RAMP_SW,
PATH_COUNT, PATH_INVALID = 63, PATHBIT_N = 0, PATHBIT_E = 1,
PATHBIT_S = 2, PATHBIT_W = 3, PATHBIT_NE = 4, PATHBIT_SE = 5,
PATHBIT_SW = 6, PATHBIT_NW = 7, PATHMASK_NE = 1 << PATHBIT_NE, PATHMASK_SE = 1 << PATHBIT_SE,
PATHMASK_SW = 1 << PATHBIT_SW, PATHMASK_NW = 1 << PATHBIT_NW, PATHMASK_EDGES = PATHMASK_NE | PATHMASK_SE | PATHMASK_SW | PATHMASK_NW, PTS_EMPTY,
PTS_NE, PTS_SE, PTS_NE_SE, PTS_NE_SE_E,
PTS_SW, PTS_NE_SW, PTS_SE_SW, PTS_SE_SW_S,
PTS_NE_SE_SW, PTS_NE_SE_SW_E, PTS_NE_SE_SW_S, PTS_NE_SE_SW_E_S,
PTS_NW, PTS_NE_NW, PTS_NE_NW_N, PTS_NW_SE,
PTS_NE_NW_SE, PTS_NE_NW_SE_N, PTS_NE_NW_SE_E, PTS_NE_NW_SE_N_E,
PTS_NW_SW, PTS_NW_SW_W, PTS_NE_NW_SW, PTS_NE_NW_SW_N,
PTS_NE_NW_SW_W, PTS_NE_NW_SW_N_W, PTS_NW_SE_SW, PTS_NW_SE_SW_S,
PTS_NW_SE_SW_W, PTS_NW_SE_SW_S_W, PTS_NE_NW_SE_SW, PTS_NE_NW_SE_SW_N,
PTS_NE_NW_SE_SW_E, PTS_NE_NW_SE_SW_N_E, PTS_NE_NW_SE_SW_S, PTS_NE_NW_SE_SW_N_S,
PTS_NE_NW_SE_SW_E_S, PTS_NE_NW_SE_SW_N_E_S, PTS_NE_NW_SE_SW_W, PTS_NE_NW_SE_SW_N_W,
PTS_NE_NW_SE_SW_E_W, PTS_NE_NW_SE_SW_N_E_W, PTS_NE_NW_SE_SW_S_W, PTS_NE_NW_SE_SW_N_S_W,
PTS_NE_NW_SE_SW_E_S_W, PTS_NE_NW_SE_SW_N_E_S_W, PTS_NE_EDGE_UP, PTS_NW_EDGE_UP,
PTS_SE_EDGE_UP, PTS_SW_EDGE_UP, PTS_COUNT
}
Available path sprites.
enum PathType {
PAT_WOOD, PAT_TILED, PAT_ASPHALT, PAT_CONCRETE,
PAT_COUNT, PAT_INVALID = 0xff
}
Available types of paths.
enum PathStatus { PAS_UNUSED, PAS_NORMAL_PATH, PAS_QUEUE_PATH }
Path status.
Functions
uint8 GetPathExits (const Voxel *v)
Find all edges that are an exit for a path in the given voxel.
bool TravelQueuePath (XYZPoint16 *voxel_pos, TileEdge *entry)
Walk over a queue path from the given entry edge at the given position.
bool PathExistsAtBottomEdge (XYZPoint16 voxel_pos, TileEdge edge)
Does a path run at/to the bottom the given voxel in the neighbouring voxel?
uint8 SetPathEdge (uint8 slope, TileEdge edge, bool connect)
Set the edge of a path sprite.
uint8 AddRemovePathEdges (const XYZPoint16 &voxel_pos, uint8 slope, uint8 dirs, bool use_additions, PathStatus status)
Add edges of the neighbouring path tiles.
Variables
const PathSprites _path_up_from_edge [EDGE_COUNT]
Imploded path tile sprite number to use for an 'up' slope from a given edge.
const PathSprites _path_down_from_edge [EDGE_COUNT]
Imploded path tile sprite number to use for an 'down' slope from a given edge.
const uint8 _path_expand []
Expansion of path sprite number to a value using path bits (PATHBIT_N, PATHBIT_E, PATHBIT_S, PATHBIT_W, PATHBIT_NE, PATHBIT_SE, PATHBIT_SW, and PATHBIT_NW).
const uint8 _path_implode [256]
Inverse operation of _path_expand.
const uint8 _path_rotation [PATH_COUNT][4]
Path sprites to use when rotating the world view.
Detailed Description
Path definitions.
Definition in file path.h.
Enumeration Type Documentation
enum PathType
Available types of paths.
Enumerator
PAT_WOOD
Wood path.
PAT_TILED
Tiled path.
PAT_ASPHALT
Asphalt path.
PAT_CONCRETE
Concrete path.
PAT_COUNT
Number of path types.
PAT_INVALID
Invalid path type.
Definition at line 104 of file path.h.
enum PathStatus
Path status.
Enumerator
PAS_UNUSED
Path is not loaded.
PAS_NORMAL_PATH
Path to walk on.
PAS_QUEUE_PATH
Path to queue on.
Definition at line 115 of file path.h.
Function Documentation
uint8 GetPathExits (const Voxel * v)
Find all edges that are an exit for a path in the given voxel.
No investigation is performed whether the exits connect to anything.
Parameters
v Voxel to investigate.
Returns
Exits for a path in the queried voxel. Lower 4 bits are exits at the bottom; upper 4 bits are exits at the top.
Definition at line 221 of file path.cpp.
References _path_expand, EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, GetImplodedPathSlope(), Voxel::GetInstance(), Voxel::GetInstanceData(), HasValidPath(), NOT_REACHED, PATH_FLAT_COUNT, PATH_RAMP_NE, PATH_RAMP_NW, PATH_RAMP_SE, PATH_RAMP_SW, PATHBIT_NE, and SRI_PATH.
Referenced by Guest::GetExitDirections(), GetParkEntryDirection(), PathSearcher::Search(), and TravelQueuePath().
bool TravelQueuePath (XYZPoint16 * voxel_pos, TileEdge * entry)
Walk over a queue path from the given entry edge at the given position.
If it leads to a new voxel edge, the provided position and edge is update with the exit point.
Parameters
voxel_pos [inout] Start voxel position before the queue path, updated to last voxel position.
entry Direction used for entry to the path, updated to last edge exit direction.
Returns
Whether a (possibly) new last voxel could be found, false means the path leads to nowhere.
Note
Parameter values may get changed during the call, do not rely on their values except when true is returned.
Definition at line 250 of file path.cpp.
References _sprite_manager, _tile_dxy, _world, EDGE_BEGIN, EDGE_COUNT, Voxel::GetInstanceData(), GetPathExits(), SpriteManager::GetPathStatus(), GetPathType(), VoxelWorld::GetVoxel(), HasValidPath(), IsVoxelstackInsideWorld(), PAS_QUEUE_PATH, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by Guest::ComputeExitDesire().
bool PathExistsAtBottomEdge (XYZPoint16 voxel_pos, TileEdge edge)
Does a path run at/to the bottom the given voxel in the neighbouring voxel?
Parameters
voxel_pos Coordinate of the voxel.
edge Direction to move to get the neighbouring voxel.
Returns
Whether a path exists at the bottom of the neighbouring voxel.
Precondition
voxel coordinate must be valid in the world.
Todo:
Merge with path computations in the path placement.
Definition at line 110 of file path_build.cpp.
References _path_down_from_edge, _path_up_from_edge, _tile_dxy, _world, GetImplodedPathSlope(), VoxelWorld::GetVoxel(), HasValidPath(), IsVoxelstackInsideWorld(), PATH_FLAT_COUNT, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by ShopPlacementManager::CanPlaceShop(), and Guest::ComputeExitDesire().
uint8 SetPathEdge (uint8 slope, TileEdge edge, bool connect)
Set the edge of a path sprite.
Also updates the corner pieces of the flat path tiles.
Parameters
slope Current path slope (imploded).
edge Edge to set or unset.
connect If true, connect to the edge, else remove the connection.
Returns
(Possibly) updated path slope.
Definition at line 315 of file path.cpp.
References _path_expand, _path_implode, EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, NOT_REACHED, PATH_FLAT_COUNT, PATHBIT_E, PATHBIT_N, PATHBIT_NE, PATHBIT_NW, PATHBIT_S, PATHBIT_SE, PATHBIT_SW, and PATHBIT_W.
Referenced by AddRemovePathEdges(), and ExamineNeighbourPathEdge().
uint8 AddRemovePathEdges (const XYZPoint16 & voxel_pos, uint8 slope, uint8 dirs, bool use_additions, PathStatus status)
Add edges of the neighbouring path tiles.
Parameters
voxel_pos Coordinate of the central voxel with a path tile.
slope Imploded path slope of the central voxel.
dirs Edge directions to change (bitset of TileEdge), usually EDGE_ALL.
use_additions Use _additions rather than _world.
status Status of the path. PAS_UNUSED means to remove the edges.
Returns
Updated (imploded) slope at the central voxel.
Definition at line 431 of file path.cpp.
References _path_down_from_edge, _path_up_from_edge, _tile_dxy, EDGE_BEGIN, EDGE_COUNT, ExamineNeighbourPathEdge(), GetQuePathEdgeConnectCount(), IsVoxelstackInsideWorld(), lengthof, MarkVoxelDirty(), NOT_REACHED, PAS_NORMAL_PATH, PAS_QUEUE_PATH, PAS_UNUSED, PATH_FLAT_COUNT, Voxel::SetInstanceData(), SetPathEdge(), WORLD_Z_SIZE, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by BuildPathAtTile(), ChangePathAtTile(), ShopPlacementManager::PlaceShop(), and RemovePathAtTile().
Variable Documentation
const PathSprites _path_up_from_edge[EDGE_COUNT]
Imploded path tile sprite number to use for an 'up' slope from a given edge.
Definition at line 18 of file path.cpp.
Referenced by AddRemovePathEdges(), BuildUpwardPath(), CanBuildPathFromEdge(), ExamineNeighbourPathEdge(), GetPathAttachPoints(), and PathExistsAtBottomEdge().
const PathSprites _path_down_from_edge[EDGE_COUNT]
Imploded path tile sprite number to use for an 'down' slope from a given edge.
Definition at line 26 of file path.cpp.
Referenced by AddRemovePathEdges(), BuildDownwardPath(), CanBuildPathFromEdge(), ExamineNeighbourPathEdge(), GetPathAttachPoints(), PathExistsAtBottomEdge(), PathBuildManager::SelectBuyRemove(), and PathBuildManager::SelectMovement().
const uint8 _path_rotation[PATH_COUNT][4]
Path sprites to use when rotating the world view.
Definition at line 162 of file path.cpp.
Referenced by SpriteCollector::CollectVoxel(), and SpriteStorage::GetPathSprite().