FreeRCT: path_build.cpp File Reference
path_build.cpp File Reference
Path building manager code.
#include "stdafx.h"
#include "path_build.h"
#include "map.h"
#include "gamemode.h"
#include "window.h"
#include "math_func.h"
Functions
static void BuildPathAtTile (const XYZPoint16 &voxel_pos, PathType path_type, uint8 path_spr)
Build a path at a tile, and claim the voxels above it as well.
static void RemovePathAtTile (const XYZPoint16 &voxel_pos, uint8 path_spr)
Remove a path from a tile, and free the voxels above it as well.
static void ChangePathAtTile (const XYZPoint16 &voxel_pos, PathType path_type, uint8 path_spr)
Change the path type of a currently existing path.
bool PathExistsAtBottomEdge (XYZPoint16 voxel_pos, TileEdge edge)
Does a path run at/to the bottom the given voxel in the neighbouring voxel?
static bool BuildUpwardPath (const XYZPoint16 &voxel_pos, TileEdge edge, PathType path_type, bool test_only)
In the given voxel, can an upward path be build in the voxel from the bottom at the given edge?
static bool BuildFlatPath (const XYZPoint16 &voxel_pos, PathType path_type, bool test_only)
In the given voxel, can a flat path be build in the voxel?
static bool BuildDownwardPath (XYZPoint16 voxel_pos, TileEdge edge, PathType path_type, bool test_only)
In the given voxel, can an downward path be build in the voxel from the bottom at the given edge?
static bool RemovePath (const XYZPoint16 &voxel_pos, bool test_only)
(Try to) remove a path from the given voxel.
static bool ChangePath (const XYZPoint16 &voxel_pos, PathType path_type, bool test_only)
(Try to) change the path type of the current path at the given voxel.
static uint8 CanBuildPathFromEdge (const XYZPoint16 &voxel_pos, TileEdge edge)
In the given voxel, can a path be build in the voxel from the bottom at the given edge?
static uint8 GetPathAttachPoints (const XYZPoint16 &voxel_pos)
Compute the attach points of a path in a voxel.
static bool GoodDirection (int16 change, uint16 src, uint16 dst)
Is the change a good direction to get from src to dst?
Variables
PathBuildManager _path_builder
Path build manager.
Detailed Description
Path building manager code.
Definition in file path_build.cpp.
Function Documentation
static void BuildPathAtTile (const XYZPoint16 & voxel_pos, PathType path_type, uint8 path_spr) static
Build a path at a tile, and claim the voxels above it as well.
Parameters
voxel_pos Coordinate of the voxel.
path_type The type of path to build.
path_spr Imploded sprite number.
See also
RemovePathAtTile
Definition at line 28 of file path_build.cpp.
References _additions, _sprite_manager, AddRemovePathEdges(), Voxel::ClearVoxel(), EDGE_ALL, VoxelStack::GetCreate(), WorldAdditions::GetModifyStack(), SpriteManager::GetPathStatus(), MakePathInstanceData(), MarkVoxelDirty(), PATH_FLAT_COUNT, PATH_INVALID, Voxel::SetInstance(), Voxel::SetInstanceData(), SRI_PATH, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by BuildDownwardPath(), BuildFlatPath(), and BuildUpwardPath().
static void RemovePathAtTile (const XYZPoint16 & voxel_pos, uint8 path_spr) static
Remove a path from a tile, and free the voxels above it as well.
Parameters
voxel_pos Coordinate of the voxel.
path_spr Imploded sprite number.
See also
BuildPathAtTile
Definition at line 58 of file path_build.cpp.
References _additions, AddRemovePathEdges(), EDGE_ALL, VoxelStack::GetCreate(), WorldAdditions::GetModifyStack(), MarkVoxelDirty(), PAS_UNUSED, PATH_FLAT_COUNT, Voxel::SetInstance(), Voxel::SetInstanceData(), SRI_FREE, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by RemovePath().
static void ChangePathAtTile (const XYZPoint16 & voxel_pos, PathType path_type, uint8 path_spr) static
Change the path type of a currently existing path.
Parameters
voxel_pos Coordinate of the voxel.
path_type The type of path to change to.
path_spr Imploded sprite number.
Definition at line 85 of file path_build.cpp.
References _additions, _sprite_manager, AddRemovePathEdges(), EDGE_ALL, VoxelStack::GetCreate(), WorldAdditions::GetModifyStack(), SpriteManager::GetPathStatus(), MakePathInstanceData(), MarkVoxelDirty(), PAS_UNUSED, PATH_EMPTY, PATH_FLAT_COUNT, Voxel::SetInstanceData(), XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by ChangePath().
bool PathExistsAtBottomEdge (XYZPoint16 voxel_pos, TileEdge edge)
Does a path run at/to the bottom the given voxel in the neighbouring voxel?
Parameters
voxel_pos Coordinate of the voxel.
edge Direction to move to get the neighbouring voxel.
Returns
Whether a path exists at the bottom of the neighbouring voxel.
Precondition
voxel coordinate must be valid in the world.
Todo:
Merge with path computations in the path placement.
Definition at line 110 of file path_build.cpp.
References _path_down_from_edge, _path_up_from_edge, _tile_dxy, _world, GetImplodedPathSlope(), VoxelWorld::GetVoxel(), HasValidPath(), IsVoxelstackInsideWorld(), PATH_FLAT_COUNT, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by ShopPlacementManager::CanPlaceShop(), and Guest::ComputeExitDesire().
static bool BuildUpwardPath (const XYZPoint16 & voxel_pos, TileEdge edge, PathType path_type, bool test_only) static
In the given voxel, can an upward path be build in the voxel from the bottom at the given edge?
Parameters
voxel_pos Coordinate of the voxel.
edge Entry edge.
path_type For building (ie not test_only), the type of path to build.
test_only Only test whether it could be created.
Returns
Whether the path is or could be built.
Definition at line 138 of file path_build.cpp.
References _corners_at_edge, _game_mode_mgr, _path_up_from_edge, _world, BuildPathAtTile(), ExpandTileSlope(), FDT_INVALID, VoxelStack::Get(), Voxel::GetFoundationType(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), Voxel::GetInstance(), VoxelWorld::GetStack(), VoxelWorld::GetTileOwner(), GTP_INVALID, GameModeManager::InPlayMode(), Voxel::IsEmpty(), IsVoxelstackInsideWorld(), OWN_PARK, SRI_FREE, TSB_STEEP, TSB_TOP, WORLD_Z_SIZE, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by CanBuildPathFromEdge(), PathBuildManager::ComputeNewLongPath(), PathBuildManager::ComputeWorldAdditions(), and PathBuildManager::TileClicked().
static bool BuildFlatPath (const XYZPoint16 & voxel_pos, PathType path_type, bool test_only) static
In the given voxel, can a flat path be build in the voxel?
Parameters
voxel_pos Coordinate of the voxel.
path_type For building (ie not test_only), the type of path to build.
test_only Only test whether it could be created.
Returns
Whether the path is or could be built.
Definition at line 179 of file path_build.cpp.
References _game_mode_mgr, _world, BuildPathAtTile(), FDT_INVALID, VoxelStack::Get(), Voxel::GetFoundationType(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), Voxel::GetInstance(), VoxelWorld::GetStack(), VoxelWorld::GetTileOwner(), GTP_INVALID, GameModeManager::InPlayMode(), Voxel::IsEmpty(), IsVoxelstackInsideWorld(), OWN_PARK, PATH_EMPTY, PATH_FLAT_COUNT, SRI_FREE, WORLD_Z_SIZE, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by CanBuildPathFromEdge(), PathBuildManager::ComputeNewLongPath(), PathBuildManager::ComputeWorldAdditions(), and PathBuildManager::TileClicked().
static bool BuildDownwardPath (XYZPoint16 voxel_pos, TileEdge edge, PathType path_type, bool test_only) static
In the given voxel, can an downward path be build in the voxel from the bottom at the given edge?
Parameters
voxel_pos Coordinate of the voxel.
edge Entry edge.
path_type For building (ie not test_only), the type of path to build.
test_only Only test whether it could be created.
Returns
Whether the path is or could be built.
Definition at line 215 of file path_build.cpp.
References _corners_at_edge, _game_mode_mgr, _path_down_from_edge, _world, BuildPathAtTile(), ExpandTileSlope(), FDT_INVALID, VoxelStack::Get(), Voxel::GetFoundationType(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), Voxel::GetInstance(), VoxelWorld::GetStack(), VoxelWorld::GetTileOwner(), GTP_INVALID, GameModeManager::InPlayMode(), Voxel::IsEmpty(), IsVoxelstackInsideWorld(), OWN_PARK, SRI_FREE, TSB_STEEP, TSB_TOP, WORLD_Z_SIZE, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by CanBuildPathFromEdge(), PathBuildManager::ComputeNewLongPath(), and PathBuildManager::ComputeWorldAdditions().
static bool RemovePath (const XYZPoint16 & voxel_pos, bool test_only) static
(Try to) remove a path from the given voxel.
Parameters
voxel_pos Coordinate of the voxel.
test_only Only test whether it could be removed.
Returns
Whether the path is or could be removed.
Definition at line 258 of file path_build.cpp.
References _game_mode_mgr, _world, VoxelStack::Get(), GetImplodedPathSlope(), Voxel::GetInstance(), Voxel::GetInstanceData(), VoxelWorld::GetStack(), VoxelWorld::GetTileOwner(), HasValidPath(), GameModeManager::InPlayMode(), IsVoxelstackInsideWorld(), OWN_PARK, PATH_COUNT, PATH_FLAT_COUNT, RemovePathAtTile(), SRI_PATH, WORLD_Z_SIZE, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by PathBuildManager::OnMouseButtonEvent(), and PathBuildManager::SelectBuyRemove().
static bool ChangePath (const XYZPoint16 & voxel_pos, PathType path_type, bool test_only) static
(Try to) change the path type of the current path at the given voxel.
Parameters
voxel_pos Coordinate of the voxel.
path_type For changing (ie not test_only), the type of path to change to.
test_only Only test whether it could be changed.
Returns
Whether the path's type could be changed.
Definition at line 290 of file path_build.cpp.
References _world, ChangePathAtTile(), VoxelStack::Get(), GetImplodedPathSlope(), Voxel::GetInstance(), Voxel::GetInstanceData(), VoxelWorld::GetStack(), HasValidPath(), PATH_COUNT, PATH_FLAT_COUNT, SRI_PATH, XYZPoint< CT >::x, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by PathBuildManager::ComputeNewLongPath(), PathBuildManager::ComputeWorldAdditions(), and PathBuildManager::TileClicked().
static uint8 CanBuildPathFromEdge (const XYZPoint16 & voxel_pos, TileEdge edge) static
In the given voxel, can a path be build in the voxel from the bottom at the given edge?
Parameters
voxel_pos Coordinate of the voxel.
edge Entry edge.
Returns
Bit-set of track slopes, indicating the directions of building paths.
Definition at line 315 of file path_build.cpp.
References _game_mode_mgr, _path_down_from_edge, _path_up_from_edge, _tile_dxy, _world, BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), GetImplodedPathSlope(), VoxelWorld::GetTileOwner(), VoxelWorld::GetVoxel(), HasValidPath(), GameModeManager::InPlayMode(), IsVoxelstackInsideWorld(), OWN_PARK, PAT_INVALID, PATH_FLAT_COUNT, TSL_DOWN, TSL_FLAT, TSL_UP, WORLD_Z_SIZE, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by PathBuildManager::ComputeNewLongPath(), GetPathAttachPoints(), and PathBuildManager::UpdateState().
static uint8 GetPathAttachPoints (const XYZPoint16 & voxel_pos) static
Compute the attach points of a path in a voxel.
Parameters
voxel_pos Coordinate of the voxel.
Returns
Attach points for paths starting from the given voxel coordinates. Upper 4 bits are the edges at the top of the voxel, lower 4 bits are the attach points for the bottom of the voxel.
Definition at line 350 of file path_build.cpp.
References _corners_at_edge, _path_down_from_edge, _path_up_from_edge, _tile_dxy, _world, CanBuildPathFromEdge(), EDGE_BEGIN, EDGE_COUNT, ExpandTileSlope(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), GetImplodedPathSlope(), VoxelWorld::GetVoxel(), GTP_INVALID, HasValidPath(), IsVoxelstackInsideWorld(), PATH_FLAT_COUNT, TSB_STEEP, WORLD_Z_SIZE, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by PathBuildManager::TileClicked(), and PathBuildManager::UpdateState().
static bool GoodDirection (int16 change, uint16 src, uint16 dst) static
Is the change a good direction to get from src to dst?
Parameters
change Direction of change (-1, 0, or +1).
src Starting point.
dst Destination.
Returns
The change direction is good.
Definition at line 867 of file path_build.cpp.
Referenced by PathBuildManager::ComputeNewLongPath().