FreeRCT: path.cpp File Reference
path.cpp File Reference
Path definitions.
#include "stdafx.h"
#include "path.h"
#include "map.h"
#include "viewport.h"
Functions
uint8 GetPathExits (const Voxel *v)
Find all edges that are an exit for a path in the given voxel.
uint8 GetPathExits (int xpos, int ypos, int zpos)
Find all edges that are an exit for a path in the given voxel.
bool TravelQueuePath (int *xp, int *yp, int *zp, TileEdge *entry)
Walk over a queue path from the given entry edge at the given position.
uint8 SetPathEdge (uint8 slope, TileEdge edge, bool connect)
Set the edge of a path sprite.
static int GetQuePathEdgeConnectCount (uint8 impl_slope)
Get number of edge connections (0, 1, many) of an imploded slope.
static bool ExamineNeighbourPathEdge (uint16 xpos, uint16 ypos, uint8 zpos, bool use_additions, TileEdge edge, bool add_edges, bool at_bottom, Voxel **dest_voxel, uint16 *dest_inst_data, PathStatus *dest_status)
Examine, and perhaps modify a neighbouring path edge or ride connection, to make it connect (or not if not add_edges) to the centre examined tile.
uint8 AddRemovePathEdges (uint16 xpos, uint16 ypos, uint8 zpos, uint8 slope, uint8 dirs, bool use_additions, PathStatus status)
Add edges of the neighbouring path tiles.
Variables
const PathSprites _path_up_from_edge [EDGE_COUNT]
Imploded path tile sprite number to use for an 'up' slope from a given edge.
const PathSprites _path_down_from_edge [EDGE_COUNT]
Imploded path tile sprite number to use for an 'down' slope from a given edge.
const uint8 _path_expand []
Expansion of path sprite number to a value using path bits (PATHBIT_N, PATHBIT_E, PATHBIT_S, PATHBIT_W, PATHBIT_NE, PATHBIT_SE, PATHBIT_SW, and PATHBIT_NW).
const uint8 _path_implode [256]
Inverse operation of _path_expand.
const uint8 _path_rotation [PATH_COUNT][4]
Path sprites to use when rotating the world view.
Detailed Description
Path definitions.
Definition in file path.cpp.
Function Documentation
uint8 GetPathExits (const Voxel * v)
Find all edges that are an exit for a path in the given voxel.
No investigation is performed whether the exits connect to anything.
Parameters
v Voxel to investigate.
Returns
Exits for a path in the queried voxel. Lower 4 bits are exits at the bottom; upper 4 bits are exits at the top.
Definition at line 221 of file path.cpp.
References _path_expand, EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, GetImplodedPathSlope(), Voxel::GetInstance(), Voxel::GetInstanceData(), HasValidPath(), NOT_REACHED, PATH_FLAT_COUNT, PATH_RAMP_NE, PATH_RAMP_NW, PATH_RAMP_SE, PATH_RAMP_SW, PATHBIT_NE, and SRI_PATH.
Referenced by GetParkEntryDirection(), GetPathExits(), PathSearcher::Search(), and TravelQueuePath().
uint8 GetPathExits (int xpos, int ypos, int zpos)
Find all edges that are an exit for a path in the given voxel.
No investigation is performed whether the exits connect to anything.
Parameters
xpos X position of the voxel.
ypos Y position of the voxel.
zpos Z position of the voxel.
Returns
Exits for a path in the queried voxel. Lower 4 bits are exits at the bottom; upper 4 bits are exits at the top.
Definition at line 249 of file path.cpp.
References _world, GetPathExits(), VoxelWorld::GetVoxel(), and IsVoxelstackInsideWorld().
bool TravelQueuePath (int * xp, int * yp, int * zp, TileEdge * entry)
Walk over a queue path from the given entry edge at the given position.
If it leads to a new voxel edge, the provided position and edge is update with the exit point.
Parameters
xp [inout] Start voxel X position before the queue path, updated to last voxel position.
yp [inout] Start voxel Y position before the queue path, updated to last voxel position.
zp [inout] Start voxel Z position before the queue path, updated to last voxel position.
entry Direction used for entry to the path, updated to last edge exit direction.
Returns
Whether a (possibly) new last voxel could be found, false means the path leads to nowhere.
Note
Parameter values may get changed during the call, do not rely on their values except when true is returned.
Definition at line 267 of file path.cpp.
References _sprite_manager, _tile_dxy, _world, EDGE_BEGIN, EDGE_COUNT, Voxel::GetInstanceData(), GetPathExits(), SpriteManager::GetPathStatus(), GetPathType(), VoxelWorld::GetVoxel(), HasValidPath(), IsVoxelstackInsideWorld(), PAS_QUEUE_PATH, Point< CT >::x, and Point< CT >::y.
Referenced by Guest::ComputeExitDesire().
uint8 SetPathEdge (uint8 slope, TileEdge edge, bool connect)
Set the edge of a path sprite.
Also updates the corner pieces of the flat path tiles.
Parameters
slope Current path slope (imploded).
edge Edge to set or unset.
connect If true, connect to the edge, else remove the connection.
Returns
(Possibly) updated path slope.
Definition at line 340 of file path.cpp.
References _path_expand, _path_implode, EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, NOT_REACHED, PATH_FLAT_COUNT, PATHBIT_E, PATHBIT_N, PATHBIT_NE, PATHBIT_NW, PATHBIT_S, PATHBIT_SE, PATHBIT_SW, and PATHBIT_W.
Referenced by AddRemovePathEdges(), and ExamineNeighbourPathEdge().
static int GetQuePathEdgeConnectCount (uint8 impl_slope) static
Get number of edge connections (0, 1, many) of an imploded slope.
Parameters
impl_slope Slope to check (imploded number).
Returns
Exact count of edges for 0 and 1, else 2 which means 'more than 1'.
Definition at line 377 of file path.cpp.
References _path_expand, PATHMASK_EDGES, PATHMASK_NE, PATHMASK_NW, PATHMASK_SE, and PATHMASK_SW.
Referenced by AddRemovePathEdges(), and ExamineNeighbourPathEdge().
static bool ExamineNeighbourPathEdge (uint16 xpos, uint16 ypos, uint8 zpos, bool use_additions, TileEdge edge, bool add_edges, bool at_bottom, Voxel ** dest_voxel, uint16 * dest_inst_data, PathStatus * dest_status) static
Examine, and perhaps modify a neighbouring path edge or ride connection, to make it connect (or not if not add_edges) to the centre examined tile.
Parameters
xpos X coordinate of the neighbouring voxel.
ypos Y coordinate of the neighbouring voxel.
zpos Z coordinate of the neighbouring voxel.
use_additions Use _additions rather than _world.
edge Edge to examine, and/or connected to.
add_edges If set, add edges (else, remove them).
at_bottom Whether a path connection is expected at the bottom (if false, it should be at the top).
dest_voxel [out] Voxel containing the neighbouring path, or nullptr.
dest_inst_data [out] New instance of the voxel. Only valid if dest_voxel is not nullptr.
dest_status [out] Status of the neighbouring path.
Returns
Neighbouring voxel was (logically) connected to the centre tile.
Definition at line 400 of file path.cpp.
References _additions, _path_down_from_edge, _path_up_from_edge, _sprite_manager, _world, VoxelWorld::GetCreateVoxel(), WorldAdditions::GetCreateVoxel(), GetImplodedPathSlope(), Voxel::GetInstance(), Voxel::GetInstanceData(), SpriteManager::GetPathStatus(), GetPathType(), GetQuePathEdgeConnectCount(), HasValidPath(), PAS_QUEUE_PATH, PAS_UNUSED, PATH_FLAT_COUNT, PATH_INVALID, SetImplodedPathSlope(), SetPathEdge(), SRI_FULL_RIDES, and SRI_PATH.
Referenced by AddRemovePathEdges().
uint8 AddRemovePathEdges (uint16 xpos, uint16 ypos, uint8 zpos, uint8 slope, uint8 dirs, bool use_additions, PathStatus status)
Add edges of the neighbouring path tiles.
Parameters
xpos X coordinate of the central voxel with a path tile.
ypos Y coordinate of the central voxel with a path tile.
zpos Z coordinate of the central voxel with a path tile.
slope Imploded path slope of the central voxel.
dirs Edge directions to change (bitset of TileEdge), usually EDGE_ALL.
use_additions Use _additions rather than _world.
status Status of the path. PAS_UNUSED means to remove the edges.
Returns
Updated (imploded) slope at the central voxel.
Definition at line 460 of file path.cpp.
References _path_down_from_edge, _path_up_from_edge, _tile_dxy, _world, EDGE_BEGIN, EDGE_COUNT, ExamineNeighbourPathEdge(), GetQuePathEdgeConnectCount(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), lengthof, MarkVoxelDirty(), NOT_REACHED, PAS_NORMAL_PATH, PAS_QUEUE_PATH, PAS_UNUSED, PATH_FLAT_COUNT, Voxel::SetInstanceData(), SetPathEdge(), WORLD_Z_SIZE, Point< CT >::x, and Point< CT >::y.
Referenced by BuildPathAtTile(), ShopPlacementManager::PlaceShop(), and RemovePathAtTile().
Variable Documentation
const PathSprites _path_up_from_edge[EDGE_COUNT]
Initial value:
= {
        PATH_RAMP_NE,
        PATH_RAMP_SE,
        PATH_RAMP_SW,
        PATH_RAMP_NW,
}
Imploded path tile sprite number to use for an 'up' slope from a given edge.
Definition at line 18 of file path.cpp.
Referenced by AddRemovePathEdges(), BuildUpwardPath(), CanBuildPathFromEdge(), ExamineNeighbourPathEdge(), GetPathAttachPoints(), and PathExistsAtBottomEdge().
const PathSprites _path_down_from_edge[EDGE_COUNT]
Initial value:
= {
        PATH_RAMP_SW,
        PATH_RAMP_NW,
        PATH_RAMP_NE,
        PATH_RAMP_SE,
}
Imploded path tile sprite number to use for an 'down' slope from a given edge.
Definition at line 26 of file path.cpp.
Referenced by AddRemovePathEdges(), BuildDownwardPath(), CanBuildPathFromEdge(), ExamineNeighbourPathEdge(), GetPathAttachPoints(), PathExistsAtBottomEdge(), PathBuildManager::SelectBuyRemove(), and PathBuildManager::SelectMovement().
const uint8 _path_rotation[PATH_COUNT][4]
Path sprites to use when rotating the world view.
Definition at line 162 of file path.cpp.
Referenced by SpriteCollector::CollectVoxel(), and SpriteStorage::GetPathSprite().