FreeRCT: people.cpp File Reference
people.cpp File Reference
People in the world.
#include "stdafx.h"
#include "map.h"
#include "dates.h"
#include "math_func.h"
#include "geometry.h"
#include "person_type.h"
#include "ride_type.h"
#include "person.h"
#include "people.h"
#include "gamelevel.h"
Functions
static bool IsGoodEdgeRoad (int16 x, int16 y)
Check that the voxel stack at the given coordinate is a good spot to use as entry point for new guests.
static Point16 FindEdgeRoad ()
Try to find a voxel at the edge of the world that can be used as entry point for guests.
Variables
Guests _guests
Guests in the world/park.
Detailed Description
People in the world.
Definition in file people.cpp.
Function Documentation
static bool IsGoodEdgeRoad (int16 x, int16 y) static
Check that the voxel stack at the given coordinate is a good spot to use as entry point for new guests.
Parameters
x X position at the edge.
y Y position at the edge.
Returns
The given position is a good starting point.
Definition at line 43 of file people.cpp.
References _world, VoxelWorld::GetGroundHeight(), GetImplodedPathSlope(), VoxelWorld::GetVoxel(), HasValidPath(), and PATH_FLAT_COUNT.
Referenced by FindEdgeRoad(), and Guests::OnNewDay().
static Point16 FindEdgeRoad () static
Try to find a voxel at the edge of the world that can be used as entry point for guests.
Returns
The x/y coordinate at the edge of the world of a usable voxelstack, else an off-world coordinate.
Definition at line 55 of file people.cpp.
References _world, VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), and IsGoodEdgeRoad().
Referenced by Guests::OnNewDay().