FreeRCT: person_type.h File Reference
person_type.h File Reference
Declaration of person types.
#include "palette.h"
Classes
struct PersonTypeGraphics
Graphics definition of a person type.
struct PersonTypeData
Collection of data for each person type.
Enumerations
enum PersonType {
PERSON_ANY = 0, PERSON_PILLAR = 1, PERSON_EARTH = 2, PERSON_TYPE_COUNT,
PERSON_INVALID = 0xFF, PERSON_MIN_GUEST = PERSON_ANY, PERSON_MAX_GUEST = PERSON_EARTH
}
Types of persons.
Functions
PersonTypeData & ModifyPersonTypeData (PersonType pt)
Get the data about a person type with the intention to change it.
const PersonTypeData & GetPersonTypeData (PersonType pt)
Get the data about a person type for reading.
static bool PersonIsAGuest (uint8 type)
Function to decide whether a person type is a guest or not.
bool LoadPRSG (RcdFileReader *rcd_file)
Load graphics settings of person types from an RCD file.
Detailed Description
Declaration of person types.
Definition in file person_type.h.
Enumeration Type Documentation
enum PersonType
Types of persons.
Enumerator
PERSON_ANY
No people displayed in the animation.
PERSON_PILLAR
Guests from the planet of Pillars (test graphics).
PERSON_EARTH
Earth-bound guests.
PERSON_TYPE_COUNT
Number of known types of persons.
PERSON_INVALID
Invalid person type.
PERSON_MIN_GUEST
First value of a guest.
PERSON_MAX_GUEST
Last value of a guest.
Definition at line 21 of file person_type.h.
Function Documentation
PersonTypeData& ModifyPersonTypeData (PersonType pt)
Get the data about a person type with the intention to change it.
Parameters
pt Type of person queried.
Returns
Reference to the data of the queried person type.
Parameters
pt Type of person queried.
Returns
Reference to the data of the queried person type.
Note
Use GetPersonTypeData if the data is only read.
Definition at line 46 of file person.cpp.
References lengthof.
Referenced by GetPersonTypeData(), and LoadPRSG().
const PersonTypeData& GetPersonTypeData (PersonType pt) inline
Get the data about a person type for reading.
Parameters
pt Type of person queried.
Returns
Reference to the data of the queried person type.
Definition at line 58 of file person_type.h.
References ModifyPersonTypeData().
Referenced by Person::Activate().
static bool PersonIsAGuest (uint8 type) inline static
Function to decide whether a person type is a guest or not.
Parameters
type Person type to test.
Returns
Whether the given person type is a guest.
Definition at line 68 of file person_type.h.
References PERSON_MAX_GUEST, and PERSON_MIN_GUEST.
Referenced by Guest::DailyUpdate(), Person::GetName(), and Person::SetName().
bool LoadPRSG (RcdFileReader * rcd_file)
Load graphics settings of person types from an RCD file.
Parameters
rcd_file RCD file to read, pointing at the start of the PRSG block data (behind the header information).
Returns
Loading was a success.
Definition at line 57 of file person.cpp.
References RcdFileReader::GetUInt32(), RcdFileReader::GetUInt8(), PersonTypeData::graphics, ModifyPersonTypeData(), PERSON_EARTH, PERSON_INVALID, PERSON_PILLAR, PersonTypeGraphics::recolours, Recolouring::Reset(), Recolouring::Set(), RcdFileReader::size, and RcdFileReader::version.
Referenced by SpriteManager::Load().