FreeRCT: person.cpp File Reference
person.cpp File Reference
Person-related functions.
#include "stdafx.h"
#include "enum_type.h"
#include "geometry.h"
#include "math_func.h"
#include "person_type.h"
#include "sprite_store.h"
#include "ride_type.h"
#include "person.h"
#include "people.h"
#include "fileio.h"
#include "map.h"
#include "path_finding.h"
#include "viewport.h"
#include "weather.h"
Functions
PersonTypeData & ModifyPersonTypeData (PersonType pt)
Get the data about a person type with the intention to change it.
bool LoadPRSG (RcdFileReader *rcd_file)
Load graphics settings of person types from an RCD file.
static int16 GetZHeight (const XYZPoint16 &vox, int16 x_pos, int16 y_pos)
Compute the height of the path in the given voxel, at the given x/y position.
static TileEdge GetParkEntryDirection (const XYZPoint16 &pos)
From a junction, find the direction that leads to an entrance of the park.
static TileEdge GetGoHomeDirection (const XYZPoint16 &pos)
From a junction, find the direction that leads to the 'go home' tile.
static int GetDesiredEdgeIndex (TileEdge desired_edge, uint8 exits)
Get the index of the exit edge to use.
assert_compile (WASTE_STOP_BUYING_FOOD > WASTE_MAY_TOILET)
Ensure that guests have a desire to visit a toilet before stopping to buy more food (and thus stop raising the waste level).
Variables
static PersonTypeData _person_type_datas [PERSON_TYPE_COUNT]
Data about each type of person.
static const WalkInformation _walk_ne_ne []
Walk from NE edge back to NE edge.
static const WalkInformation _walk_ne_se []
Walk from NE edge to SE edge.
static const WalkInformation _walk_ne_sw []
Walk from NE edge to SW edge.
static const WalkInformation _walk_ne_nw []
Walk from NE edge to NW edge.
static const WalkInformation _walk_se_ne []
Walk from SE edge to NE edge.
static const WalkInformation _walk_se_se []
Walk from SE edge back to SE edge.
static const WalkInformation _walk_se_sw []
Walk from SE edge to SW edge.
static const WalkInformation _walk_se_nw []
Walk from SE edge to NW edge.
static const WalkInformation _walk_sw_ne []
Walk from SW edge to NE edge.
static const WalkInformation _walk_sw_se []
Walk from SW edge to SE edge.
static const WalkInformation _walk_sw_sw []
Walk from SW edge back to SW edge.
static const WalkInformation _walk_sw_nw []
Walk from SW edge to NW edge.
static const WalkInformation _walk_nw_ne []
Walk from NW edge to NE edge.
static const WalkInformation _walk_nw_se []
Walk from NW edge to SE edge.
static const WalkInformation _walk_nw_sw []
Walk from NW edge to SW edge.
static const WalkInformation _walk_nw_nw []
Walk from NW edge back to NW edge.
static const WalkInformation * _walk_path_tile [4][4]
Movement of one edge to another edge of a path tile.
static const WalkInformation _center_ne_ne []
Walk from NE edge back to centre NE edge.
static const WalkInformation _center_ne_se []
Walk from NE edge to centre SE edge.
static const WalkInformation _center_ne_sw []
Walk from NE edge to centre SW edge.
static const WalkInformation _center_ne_nw []
Walk from NE edge to centre NW edge.
static const WalkInformation _center_se_ne []
Walk from SE edge to centre NE edge.
static const WalkInformation _center_se_se []
Walk from SE edge back to centre SE edge.
static const WalkInformation _center_se_sw []
Walk from SE edge to centre SW edge.
static const WalkInformation _center_se_nw []
Walk from SE edge to centre NW edge.
static const WalkInformation _center_sw_ne []
Walk from SW edge to centre NE edge.
static const WalkInformation _center_sw_se []
Walk from SW edge to centre SE edge.
static const WalkInformation _center_sw_sw []
Walk from SW edge back to centre SW edge.
static const WalkInformation _center_sw_nw []
Walk from SW edge to centre NW edge.
static const WalkInformation _center_nw_ne []
Walk from NW edge to centre NE edge.
static const WalkInformation _center_nw_se []
Walk from NW edge to centre SE edge.
static const WalkInformation _center_nw_sw []
Walk from NW edge to centre SW edge.
static const WalkInformation _center_nw_nw []
Walk from NW edge back to centre NW edge.
static const WalkInformation * _center_path_tile [4][4]
Movement of one edge to another centre edge of a path tile.
static const int WASTE_STOP_BUYING_FOOD = 150
Waste level where the guest stop buying food.
static const int WASTE_MAY_TOILET = 100
Minimal level of waste before desiring to visit a toilet at all.
static const int WASTE_MUST_TOILET = 200
Level of waste before really needing to visit a toilet.
static const int NAUSEA_MUST_FIRST_AID = 200
Level of nausea before really needing help in reducing nausea.
Detailed Description
Person-related functions.
Definition in file person.cpp.
Function Documentation
PersonTypeData& ModifyPersonTypeData (PersonType pt)
Get the data about a person type with the intention to change it.
Parameters
pt Type of person queried.
Returns
Reference to the data of the queried person type.
Note
Use GetPersonTypeData if the data is only read.
Definition at line 47 of file person.cpp.
References lengthof.
Referenced by GetPersonTypeData(), and LoadPRSG().
bool LoadPRSG (RcdFileReader * rcd_file)
Load graphics settings of person types from an RCD file.
Parameters
rcd_file RCD file to read, pointing at the start of the PRSG block data (behind the header information).
Returns
Loading was a success.
Definition at line 58 of file person.cpp.
References RcdFileReader::GetUInt32(), RcdFileReader::GetUInt8(), PersonTypeData::graphics, ModifyPersonTypeData(), PERSON_ENTERTAINER, PERSON_GUARD, PERSON_GUEST, PERSON_HANDYMAN, PERSON_INVALID, PERSON_MECHANIC, PersonTypeGraphics::recolours, Recolouring::Reset(), Recolouring::Set(), RcdFileReader::size, and RcdFileReader::version.
Referenced by SpriteManager::Load().
static int16 GetZHeight (const XYZPoint16 & vox, int16 x_pos, int16 y_pos) static
Compute the height of the path in the given voxel, at the given x/y position.
Parameters
vox Coordinates of the voxel.
x_pos X position in the voxel.
y_pos Y position in the voxel.
Returns
Z height of the path in the voxel at the give position.
Todo:
Make it work at sloped surface too, in case the person ends up at path-less land.
Todo:
No path here!
Definition at line 152 of file person.cpp.
References _world, GetImplodedPathSlope(), VoxelWorld::GetVoxel(), HasValidPath(), NOT_REACHED, PATH_FLAT_COUNT, PATH_RAMP_NE, PATH_RAMP_NW, PATH_RAMP_SE, and PATH_RAMP_SW.
Referenced by Person::Activate(), and Person::OnAnimate().
static TileEdge GetParkEntryDirection (const XYZPoint16 & pos) static
From a junction, find the direction that leads to an entrance of the park.
Parameters
pos Current position.
Returns
Edge to go to to go to an entrance of the park, or INVALID_EDGE if no path could be found.
Definition at line 532 of file person.cpp.
References _world, PathSearcher::AddStart(), VoxelStack::base, WalkedPosition::cur_vox, PathSearcher::dest_pos, EDGE_NE, EDGE_NW, EDGE_SE, EDGE_SW, GetAdjacentEdge(), VoxelStack::GetGroundOffset(), GetImplodedPathSlope(), GetPathExits(), VoxelWorld::GetStack(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), HasValidPath(), INVALID_EDGE, OWN_PARK, VoxelStack::owner, PATH_FLAT_COUNT, WalkedPosition::prev_pos, PathSearcher::Search(), VoxelStack::voxels, XYZPoint< CT >::x, and XYZPoint< CT >::y.
Referenced by Guest::WalkForActivity().
static TileEdge GetGoHomeDirection (const XYZPoint16 & pos) static
From a junction, find the direction that leads to the 'go home' tile.
Parameters
pos Current position.
Returns
Edge to go to to go to the 'go home' tile, or INVALID_EDGE if no path could be found.
Definition at line 586 of file person.cpp.
References _guests, _world, PathSearcher::AddStart(), WalkedPosition::cur_vox, PathSearcher::dest_pos, GetAdjacentEdge(), VoxelWorld::GetGroundHeight(), INVALID_EDGE, WalkedPosition::prev_pos, PathSearcher::Search(), Guests::start_voxel, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, and XYZPoint< CT >::y.
Referenced by Guest::WalkForActivity().
static int GetDesiredEdgeIndex (TileEdge desired_edge, uint8 exits) static
Get the index of the exit edge to use.
Parameters
desired_edge Edge to use for leaving.
exits Available exits.
Returns
Index of the desired edge in the available edges, or -1
Definition at line 609 of file person.cpp.
References EDGE_BEGIN, EDGE_COUNT, and GB().
Referenced by Guest::WalkForActivity().
assert_compile (WASTE_STOP_BUYING_FOOD , WASTE_MAY_TOILET)
Ensure that guests have a desire to visit a toilet before stopping to buy more food (and thus stop raising the waste level).
Variable Documentation
const WalkInformation _walk_ne_ne[] static
Initial value:
= {
        {ANIM_WALK_SW, WLM_HIGH_X}, {ANIM_WALK_SE, WLM_HIGH_Y}, {ANIM_WALK_NE, WLM_NE_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NE edge back to NE edge.
Definition at line 211 of file person.cpp.
const WalkInformation _walk_ne_se[] static
Initial value:
= {
        {ANIM_WALK_SW, WLM_HIGH_X}, {ANIM_WALK_SE, WLM_SE_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NE edge to SE edge.
Definition at line 215 of file person.cpp.
const WalkInformation _walk_ne_sw[] static
Initial value:
= {
        {ANIM_WALK_SW, WLM_SW_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NE edge to SW edge.
Definition at line 219 of file person.cpp.
const WalkInformation _walk_ne_nw[] static
Initial value:
= {
        {ANIM_WALK_SW, WLM_LOW_X},  {ANIM_WALK_NW, WLM_NW_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NE edge to NW edge.
Definition at line 223 of file person.cpp.
const WalkInformation _walk_se_ne[] static
Initial value:
= {
        {ANIM_WALK_NW, WLM_HIGH_Y}, {ANIM_WALK_NE, WLM_NE_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SE edge to NE edge.
Definition at line 228 of file person.cpp.
const WalkInformation _walk_se_se[] static
Initial value:
= {
        {ANIM_WALK_NW, WLM_LOW_Y},  {ANIM_WALK_SW, WLM_HIGH_X}, {ANIM_WALK_SE, WLM_SE_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SE edge back to SE edge.
Definition at line 232 of file person.cpp.
const WalkInformation _walk_se_sw[] static
Initial value:
= {
        {ANIM_WALK_NW, WLM_LOW_Y},  {ANIM_WALK_SW, WLM_SW_EDGE }, {ANIM_INVALID, WLM_INVALID}
}
Walk from SE edge to SW edge.
Definition at line 236 of file person.cpp.
const WalkInformation _walk_se_nw[] static
Initial value:
= {
        {ANIM_WALK_NW, WLM_NW_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SE edge to NW edge.
Definition at line 240 of file person.cpp.
const WalkInformation _walk_sw_ne[] static
Initial value:
= {
        {ANIM_WALK_NE, WLM_NE_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SW edge to NE edge.
Definition at line 245 of file person.cpp.
const WalkInformation _walk_sw_se[] static
Initial value:
= {
        {ANIM_WALK_NE, WLM_HIGH_X}, {ANIM_WALK_SE, WLM_SE_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SW edge to SE edge.
Definition at line 249 of file person.cpp.
const WalkInformation _walk_sw_sw[] static
Initial value:
= {
        {ANIM_WALK_NE, WLM_LOW_X},  {ANIM_WALK_NW, WLM_LOW_Y}, {ANIM_WALK_SW, WLM_SW_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SW edge back to SW edge.
Definition at line 253 of file person.cpp.
const WalkInformation _walk_sw_nw[] static
Initial value:
= {
{ANIM_WALK_NE, WLM_LOW_X},  {ANIM_WALK_NW, WLM_NW_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SW edge to NW edge.
Definition at line 257 of file person.cpp.
const WalkInformation _walk_nw_ne[] static
Initial value:
= {
        {ANIM_WALK_SE, WLM_HIGH_Y}, {ANIM_WALK_NE, WLM_NE_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NW edge to NE edge.
Definition at line 262 of file person.cpp.
const WalkInformation _walk_nw_se[] static
Initial value:
= {
        {ANIM_WALK_SE, WLM_SE_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NW edge to SE edge.
Definition at line 266 of file person.cpp.
const WalkInformation _walk_nw_sw[] static
Initial value:
= {
        {ANIM_WALK_SE, WLM_LOW_Y},  {ANIM_WALK_SW, WLM_SW_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NW edge to SW edge.
Definition at line 270 of file person.cpp.
const WalkInformation _walk_nw_nw[] static
Initial value:
= {
        {ANIM_WALK_SE, WLM_HIGH_Y}, {ANIM_WALK_NE, WLM_LOW_X}, {ANIM_WALK_NW, WLM_NW_EDGE}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NW edge back to NW edge.
Definition at line 274 of file person.cpp.
const WalkInformation* _walk_path_tile[4][4] static
Initial value:
= {
        {_walk_ne_ne, _walk_ne_se, _walk_ne_sw, _walk_ne_nw},
        {_walk_se_ne, _walk_se_se, _walk_se_sw, _walk_se_nw},
        {_walk_sw_ne, _walk_sw_se, _walk_sw_sw, _walk_sw_nw},
        {_walk_nw_ne, _walk_nw_se, _walk_nw_sw, _walk_nw_nw},
}
Movement of one edge to another edge of a path tile.
Definition at line 279 of file person.cpp.
const WalkInformation _center_ne_ne[] static
Initial value:
= {
        {ANIM_WALK_SW, WLM_HIGH_X}, {ANIM_WALK_SE, WLM_MID_Y}, {ANIM_WALK_NE, WLM_NE_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NE edge back to centre NE edge.
Definition at line 287 of file person.cpp.
const WalkInformation _center_ne_se[] static
Initial value:
= {
        {ANIM_WALK_SW, WLM_MID_X}, {ANIM_WALK_SE, WLM_SE_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NE edge to centre SE edge.
Definition at line 291 of file person.cpp.
const WalkInformation _center_ne_sw[] static
Initial value:
= {
        {ANIM_WALK_SW, WLM_SW_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NE edge to centre SW edge.
Definition at line 295 of file person.cpp.
const WalkInformation _center_ne_nw[] static
Initial value:
= {
        {ANIM_WALK_SW, WLM_MID_X},  {ANIM_WALK_NW, WLM_NW_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NE edge to centre NW edge.
Definition at line 299 of file person.cpp.
const WalkInformation _center_se_ne[] static
Initial value:
= {
        {ANIM_WALK_NW, WLM_MID_Y}, {ANIM_WALK_NE, WLM_NE_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SE edge to centre NE edge.
Definition at line 304 of file person.cpp.
const WalkInformation _center_se_se[] static
Initial value:
= {
        {ANIM_WALK_NW, WLM_LOW_Y},  {ANIM_WALK_SW, WLM_MID_X}, {ANIM_WALK_SE, WLM_SE_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SE edge back to centre SE edge.
Definition at line 308 of file person.cpp.
const WalkInformation _center_se_sw[] static
Initial value:
= {
        {ANIM_WALK_NW, WLM_MID_Y},  {ANIM_WALK_SW, WLM_SW_CENTER }, {ANIM_INVALID, WLM_INVALID}
}
Walk from SE edge to centre SW edge.
Definition at line 312 of file person.cpp.
const WalkInformation _center_se_nw[] static
Initial value:
= {
        {ANIM_WALK_NW, WLM_NW_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SE edge to centre NW edge.
Definition at line 316 of file person.cpp.
const WalkInformation _center_sw_ne[] static
Initial value:
= {
        {ANIM_WALK_NE, WLM_NE_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SW edge to centre NE edge.
Definition at line 321 of file person.cpp.
const WalkInformation _center_sw_se[] static
Initial value:
= {
        {ANIM_WALK_NE, WLM_MID_X}, {ANIM_WALK_SE, WLM_SE_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SW edge to centre SE edge.
Definition at line 325 of file person.cpp.
const WalkInformation _center_sw_sw[] static
Initial value:
= {
        {ANIM_WALK_NE, WLM_LOW_X},  {ANIM_WALK_NW, WLM_MID_Y}, {ANIM_WALK_SW, WLM_SW_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SW edge back to centre SW edge.
Definition at line 329 of file person.cpp.
const WalkInformation _center_sw_nw[] static
Initial value:
= {
{ANIM_WALK_NE, WLM_MID_X},  {ANIM_WALK_NW, WLM_NW_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from SW edge to centre NW edge.
Definition at line 333 of file person.cpp.
const WalkInformation _center_nw_ne[] static
Initial value:
= {
        {ANIM_WALK_SE, WLM_MID_Y}, {ANIM_WALK_NE, WLM_NE_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NW edge to centre NE edge.
Definition at line 338 of file person.cpp.
const WalkInformation _center_nw_se[] static
Initial value:
= {
        {ANIM_WALK_SE, WLM_SE_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NW edge to centre SE edge.
Definition at line 342 of file person.cpp.
const WalkInformation _center_nw_sw[] static
Initial value:
= {
        {ANIM_WALK_SE, WLM_MID_Y},  {ANIM_WALK_SW, WLM_SW_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NW edge to centre SW edge.
Definition at line 346 of file person.cpp.
const WalkInformation _center_nw_nw[] static
Initial value:
= {
        {ANIM_WALK_SE, WLM_HIGH_Y}, {ANIM_WALK_NE, WLM_MID_X}, {ANIM_WALK_NW, WLM_NW_CENTER}, {ANIM_INVALID, WLM_INVALID}
}
Walk from NW edge back to centre NW edge.
Definition at line 350 of file person.cpp.
const WalkInformation* _center_path_tile[4][4] static
Initial value:
= {
        {_center_ne_ne, _center_ne_se, _center_ne_sw, _center_ne_nw},
        {_center_se_ne, _center_se_se, _center_se_sw, _center_se_nw},
        {_center_sw_ne, _center_sw_se, _center_sw_sw, _center_sw_nw},
        {_center_nw_ne, _center_nw_se, _center_nw_sw, _center_nw_nw},
}
Movement of one edge to another centre edge of a path tile.
Definition at line 355 of file person.cpp.