FreeRCT: rcdgen.cpp File Reference
rcdgen.cpp File Reference
Main program of rcdgen.
#include "../stdafx.h"
#include "../getoptdata.h"
#include "scanner_funcs.h"
#include "ast.h"
#include "nodes.h"
#include "file_writing.h"
#include <cstdarg>
Functions
void error (const char *str,...)
Error handling for fatal non-user errors.
static void PrintUsage ()
Output online help.
int main (int argc, char *argv[])
The main program of rcdgen.
Variables
static const OptionData _options []
Command-line options of the program.
Detailed Description
Main program of rcdgen.
Definition in file rcdgen.cpp.
Function Documentation
void error (const char * str, ...)
Error handling for fatal non-user errors.
Parameters
str the string to print.
Note
Never returns.
Definition at line 25 of file rcdgen.cpp.
static void PrintUsage () static
Output online help.
Definition at line 47 of file rcdgen.cpp.
Referenced by main().
int main (int argc, char * argv[])
The main program of rcdgen.
Parameters
argc Number of argument given to the program.
argv Argument texts.
Returns
Exit code.
Definition at line 77 of file rcdgen.cpp.
References GetOptData::argv, CheckTree(), FileNodeList::files, GenerateStringsCodeFile(), GenerateStringsHeaderFile(), GetOptData::GetOpt(), LoadFile(), GetOptData::numleft, GetOptData::opt, PrintUsage(), and FileWriter::WriteFile().
Variable Documentation
const OptionData _options[] static
Initial value:
= {
        GETOPT_NOVAL('h', "--help"),
        GETOPT_VALUE('d', "--header"),
        GETOPT_VALUE('c', "--code"),
        GETOPT_VALUE('b', "--base"),
        GETOPT_VALUE('p', "--prefix"),
}
Command-line options of the program.
Definition at line 37 of file rcdgen.cpp.