FreeRCT: ride_type.h File Reference
ride_type.h File Reference
Available types of rides.
#include "palette.h"
#include "money.h"
#include "random.h"
Classes
class RideType
Base class of ride types.
class RideInstance
A ride in the park.
class RidesManager
Storage of available ride types.
Enumerations
enum RideTypeKind {
RTK_SHOP, RTK_GENTLE, RTK_WET, RTK_COASTER,
RTK_RIDE_KIND_COUNT
}
Kinds of ride types.
enum ShopFlags {
SHF_NE_ENTRANCE = 1 << EDGE_NE, SHF_SE_ENTRANCE = 1 << EDGE_SE, SHF_SW_ENTRANCE = 1 << EDGE_SW, SHF_NW_ENTRANCE = 1 << EDGE_NW,
SHF_ENTRANCE_BITS = (SHF_NE_ENTRANCE | SHF_SE_ENTRANCE | SHF_SW_ENTRANCE | SHF_NW_ENTRANCE)
}
Flags describing properties the shop type.
enum ItemType {
ITP_NOTHING = 0, ITP_DRINK = 8, ITP_ICE_CREAM = 9, ITP_NORMAL_FOOD = 16,
ITP_SALTY_FOOD = 24, ITP_UMBRELLA = 32, ITP_BALLOON = 33, ITP_PARK_MAP = 40,
ITP_SOUVENIR = 41, ITP_MONEY = 48, ITP_TOILET = 49, ITP_FIRST_AID = 50
}
Type of items that can be bought.
enum RideInstanceState {
RIS_ALLOCATED, RIS_BUILDING, RIS_TESTING, RIS_CLOSED,
RIS_OPEN
}
State of a ride instance.
enum RideInstanceFlags { RIF_MONTHLY_PAID = 0, RIF_OPENED_PAID = 1 }
Flags of the ride instance.
enum BreakdownState { BDS_BROKEN, BDS_WILL_BREAK, BDS_NEEDS_NEW_CTR, BDS_UNOPENED }
Breakdown states which determine if and how a ride will break in a given day.
enum RideEntryResult { RER_REFUSED, RER_ENTERED, RER_DONE }
Answers of RideInstance::EnterRide.
Functions
RideInstance * RideExistsAtBottom (XYZPoint16 pos, TileEdge edge)
Does a ride entrance exists at/to the bottom the given voxel in the neighbouring voxel?
Variables
static const int MAX_NUMBER_OF_RIDE_TYPES = 64
Maximal number of types of rides.
static const int MAX_NUMBER_OF_RIDE_INSTANCES = 64
Maximal number of ride instances (limit is uint16 in the map).
static const uint16 INVALID_RIDE_INSTANCE = 0xFFFF
Value representing 'no ride instance found'.
static const int NUMBER_ITEM_TYPES_SOLD = 2
Number of different items that a ride can sell.
static const int BREAKDOWN_GRACE_PERIOD = 30
Number of days to wait before random breakdowns after first time opening ride.
RidesManager _rides_manager
Storage and retrieval of ride types and rides in the park.
Detailed Description
Available types of rides.
Definition in file ride_type.h.
Enumeration Type Documentation
enum RideTypeKind
Kinds of ride types.
Todo:
Split coasters into different kinds??
Enumerator
RTK_SHOP
Ride type allows buying useful stuff.
RTK_GENTLE
Gentle kind of ride.
RTK_WET
Ride type uses water.
RTK_COASTER
Ride type is a coaster.
RTK_RIDE_KIND_COUNT
Number of kinds of ride types.
Definition at line 33 of file ride_type.h.
enum ShopFlags
Flags describing properties the shop type.
Enumerator
SHF_NE_ENTRANCE
Entrance in NE direction (unrotated).
SHF_SE_ENTRANCE
Entrance in SE direction (unrotated).
SHF_SW_ENTRANCE
Entrance in SW direction (unrotated).
SHF_NW_ENTRANCE
Entrance in NW direction (unrotated).
SHF_ENTRANCE_BITS
Bit mask for the entrances.
Definition at line 43 of file ride_type.h.
enum ItemType
Type of items that can be bought.
Enumerator
ITP_NOTHING
Dummy item to denote nothing can be bought.
ITP_DRINK
A drink in a cup.
ITP_ICE_CREAM
Ice cream (a drink that can be eaten).
ITP_NORMAL_FOOD
'plain' food.
ITP_SALTY_FOOD
'salty' food, makes thirsty.
ITP_UMBRELLA
Umbrella against the rain.
ITP_BALLOON
Balloon.
ITP_PARK_MAP
Map of the park, may improve finding the attractions.
ITP_SOUVENIR
Souvenir of the park.
ITP_MONEY
Money for more spending (i.e. an ATM).
ITP_TOILET
Dropping of waste.
ITP_FIRST_AID
Nausea treatment.
Definition at line 53 of file ride_type.h.
enum RideInstanceState
State of a ride instance.
Enumerator
RIS_ALLOCATED
Ride instance is allocated but not yet in play.
RIS_BUILDING
Ride instance is being constructed.
RIS_TESTING
Ride instance is being tested.
RIS_CLOSED
Ride instance is available, but closed for the public.
RIS_OPEN
Ride instance is open for use by the public.
Definition at line 101 of file ride_type.h.
enum RideInstanceFlags
Flags of the ride instance.
Enumerator
RIF_MONTHLY_PAID
Bit number of the flags indicating the monthly presence costs have been paid.
RIF_OPENED_PAID
Bit number of the flags indicating the open costs have been paid this month.
Definition at line 110 of file ride_type.h.
enum BreakdownState
Breakdown states which determine if and how a ride will break in a given day.
Enumerator
BDS_BROKEN
Ride is currently broken.
BDS_WILL_BREAK
Ride will break at some point in the future.
BDS_NEEDS_NEW_CTR
Ride needs a new value for RideInstance::breakdown_ctr.
BDS_UNOPENED
The ride has never been opened and thus is immune from breakdown.
Definition at line 116 of file ride_type.h.
enum RideEntryResult
Answers of RideInstance::EnterRide.
Enumerator
RER_REFUSED
Entry is refused.
RER_ENTERED
Entry is given, the guest is staying inside the ride.
RER_DONE
Entry is given, and visit is immediately done.
Definition at line 124 of file ride_type.h.
Function Documentation
RideInstance* RideExistsAtBottom (XYZPoint16 pos, TileEdge edge)
Does a ride entrance exists at/to the bottom the given voxel in the neighbouring voxel?
Parameters
pos Coordinate of the voxel.
edge Direction to move to get the neighbouring voxel.
Precondition
voxel coordinate must be valid in the world.
Returns
The ride at the neighbouring voxel, if available (else nullptr is returned).
Definition at line 619 of file ride_type.cpp.
References _tile_dxy, _world, Voxel::GetInstance(), RidesManager::GetRideInstance(), VoxelWorld::GetVoxel(), IsVoxelstackInsideWorld(), SRI_FULL_RIDES, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by Guest::ComputeExitDesire().