FreeRCT: ride_type.cpp File Reference
ride_type.cpp File Reference
Ride type storage and retrieval.
#include "stdafx.h"
#include "string_func.h"
#include "sprite_store.h"
#include "language.h"
#include "map.h"
#include "fileio.h"
#include "ride_type.h"
#include "bitmath.h"
#include "gamelevel.h"
#include "window.h"
#include "finances.h"
#include "person.h"
#include "people.h"
#include "random.h"
Functions
RideInstance * RideExistsAtBottom (XYZPoint16 pos, TileEdge edge)
Does a ride entrance exists at/to the bottom the given voxel in the neighbouring voxel?
Variables
RidesManager _rides_manager
Storage and retrieval of ride types and rides in the park.
Detailed Description
Ride type storage and retrieval.
Definition in file ride_type.cpp.
Function Documentation
RideInstance* RideExistsAtBottom (XYZPoint16 pos, TileEdge edge)
Does a ride entrance exists at/to the bottom the given voxel in the neighbouring voxel?
Parameters
pos Coordinate of the voxel.
edge Direction to move to get the neighbouring voxel.
Precondition
voxel coordinate must be valid in the world.
Returns
The ride at the neighbouring voxel, if available (else nullptr is returned).
Definition at line 619 of file ride_type.cpp.
References _tile_dxy, _world, Voxel::GetInstance(), RidesManager::GetRideInstance(), VoxelWorld::GetVoxel(), IsVoxelstackInsideWorld(), SRI_FULL_RIDES, Point< CT >::x, XYZPoint< CT >::x, Point< CT >::y, XYZPoint< CT >::y, and XYZPoint< CT >::z.
Referenced by Guest::ComputeExitDesire().