FreeRCT: shop_gui.cpp File Reference
shop_gui.cpp File Reference
Window for inter-acting with shops.
#include "stdafx.h"
#include "math_func.h"
#include "window.h"
#include "money.h"
#include "language.h"
#include "sprite_store.h"
#include "shop_type.h"
Classes
class ShopManagerWindow
GUI window for interacting with a shop instance.
Enumerations
enum ShopManagerWidgets {
SMW_TITLEBAR, SMW_ITEM1_HEAD, SMW_ITEM2_HEAD, SMW_ITEM1_COST,
SMW_ITEM2_COST, SMW_ITEM1_SELL, SMW_ITEM2_SELL, SMW_ITEM1_PROFIT,
SMW_ITEM2_PROFIT, SMW_ITEM1_COUNT, SMW_ITEM2_COUNT, SMW_SELL_PROFIT,
SMW_SHOP_COST, SMW_TOTAL_PROFIT, SMW_SHOP_OPENED, SMW_SHOP_OPENED_TEXT,
SMW_SHOP_CLOSED, SMW_SHOP_CLOSED_TEXT, SMW_RECOLOUR1, SMW_RECOLOUR2,
SMW_RECOLOUR3
}
Widgets of the shop management window.
Functions
assert_compile (MAX_RECOLOUR >=3)
Check that the 3 recolourings of a shop fit in the Recolouring::entries array.
void ShowShopManagementGui (uint16 number)
Open a window to manage a given shop.
Variables
static const WidgetPart _shop_manager_gui_parts []
Widget parts of the ShopManagerWindow.
Detailed Description
Window for inter-acting with shops.
Definition in file shop_gui.cpp.
Enumeration Type Documentation
enum ShopManagerWidgets
Widgets of the shop management window.
Enumerator
SMW_TITLEBAR
Title bar widget.
SMW_ITEM1_HEAD
Name of the first item being sold.
SMW_ITEM2_HEAD
Name of the second item being sold.
SMW_ITEM1_COST
Cost of the first item.
SMW_ITEM2_COST
Cost of the second item.
SMW_ITEM1_SELL
Selling price of the first item.
SMW_ITEM2_SELL
Selling price of the second item.
SMW_ITEM1_PROFIT
Profit of a first item.
SMW_ITEM2_PROFIT
Profit of a second item.
SMW_ITEM1_COUNT
Number of first items sold in total.
SMW_ITEM2_COUNT
Number of second items sold in total.
SMW_SELL_PROFIT
Total selling profit.
SMW_SHOP_COST
Shop maintenance/personnel costs.
SMW_TOTAL_PROFIT
Total shop profit.
SMW_SHOP_OPENED
Radio button of 'shop is open'.
SMW_SHOP_OPENED_TEXT
'shop is open' text label.
SMW_SHOP_CLOSED
Radio button of 'shop is closed'.
SMW_SHOP_CLOSED_TEXT
'shop is closed' text label.
SMW_RECOLOUR1
First recolour dropdown.
SMW_RECOLOUR2
Second recolour dropdown.
SMW_RECOLOUR3
Third recolour dropdown.
Definition at line 21 of file shop_gui.cpp.
Function Documentation
void ShowShopManagementGui (uint16 number)
Open a window to manage a given shop.
Parameters
number Shop to manage.
Definition at line 239 of file shop_gui.cpp.
References _rides_manager, RideInstance::GetKind(), RidesManager::GetRideInstance(), HighlightWindowByType(), RTK_SHOP, and WC_SHOP_MANAGER.
Referenced by SelectMouseMode::OnMouseButtonEvent().
Variable Documentation
const WidgetPart _shop_manager_gui_parts[] static
Widget parts of the ShopManagerWindow.
Definition at line 46 of file shop_gui.cpp.