FreeRCT: sprite_store.cpp File Reference
sprite_store.cpp File Reference
Sprite storage functions.
#include "stdafx.h"
#include "sprite_store.h"
#include "sprite_data.h"
#include "rcdfile.h"
#include "fileio.h"
#include "math_func.h"
#include "shop_type.h"
#include "coaster.h"
#include "gui_sprites.h"
#include "generated/gui_strings.cpp"
Functions
static int DecodeUtf8Char (uint8 *data, size_t length, uint32 *codepoint)
Decode an UTF-8 character.
static bool ReadUtf8Text (RcdFileReader *rcd_file, size_t expected_length, uint8 *buffer, size_t buf_length, size_t *used_size)
Check an UTF-8 string.
bool LoadSpriteFromFile (RcdFileReader *rcd_file, const ImageMap &sprites, ImageData **spr)
Get a sprite reference from the rcd_file, retrieve the corresponding sprite, and put it in the spr destination.
bool LoadTextFromFile (RcdFileReader *rcd_file, const TextMap &texts, TextData **txt)
Get a text reference from the rcd_file, retrieve the corresponding text data, and put it in the txt destination.
static PersonType DecodePersonType (uint8 pt)
Decode a read value to the internal representation of a person type.
Rectangle16 GetSpriteSize (const ImageData *imd)
Get the size of an image including its origin.
Variables
SpriteManager _sprite_manager
Sprite manager.
GuiSprites _gui_sprites
GUI sprites.
static const int MAX_NUM_TEXT_STRINGS = 512
Maximal number of strings in a TEXT data block.
const uint8 _slope_rotation [NUM_SLOPE_SPRITES][4]
Sprite indices of ground/surface sprites after rotation of the view.
Detailed Description
Sprite storage functions.
Definition in file sprite_store.cpp.
Function Documentation
static int DecodeUtf8Char (uint8 * data, size_t length, uint32 * codepoint) static
Decode an UTF-8 character.
Parameters
data Pointer to the start of the data.
length Length of the data buffer.
[out] codepoint If decoding was successful, the value of the decoded character.
Returns
Number of bytes read to decode the character, or 0 if reading failed.
Definition at line 95 of file sprite_store.cpp.
Referenced by ReadUtf8Text().
static bool ReadUtf8Text (RcdFileReader * rcd_file, size_t expected_length, uint8 * buffer, size_t buf_length, size_t * used_size) static
Check an UTF-8 string.
Parameters
rcd_file Input file.
expected_length Expected length of the string in bytes, including terminating NUL byte.
buffer Buffer to copy the string into.
buf_length Length of the buffer
[out] used_size Length of the used part of the buffer, only updated on successful reading of the string.
Returns
Reading the string was a success.
Definition at line 143 of file sprite_store.cpp.
References DecodeUtf8Char(), and RcdFileReader::GetBlob().
Referenced by TextData::Load().
bool LoadSpriteFromFile (RcdFileReader * rcd_file, const ImageMap & sprites, ImageData ** spr)
Get a sprite reference from the rcd_file, retrieve the corresponding sprite, and put it in the spr destination.
Parameters
rcd_file File to load from.
sprites Sprites already loaded from this file.
[out] spr Pointer to write the loaded sprite to.
Returns
Loading was successful.
Definition at line 256 of file sprite_store.cpp.
References RcdFileReader::GetUInt32().
Referenced by ShopType::Load(), TrackVoxel::Load(), CarType::Load(), Fence::Load(), AnimationSprites::Load(), SpriteManager::LoadBDIR(), LoadCoasterPlatform(), SpriteManager::LoadFUND(), GuiSprites::LoadGBOR(), GuiSprites::LoadGCHK(), GuiSprites::LoadGSCL(), GuiSprites::LoadGSLI(), GuiSprites::LoadGSLP(), SpriteManager::LoadPATH(), SpriteManager::LoadPLAT(), SpriteManager::LoadSUPP(), SpriteManager::LoadSURF(), SpriteManager::LoadTCOR(), and SpriteManager::LoadTSEL().
bool LoadTextFromFile (RcdFileReader * rcd_file, const TextMap & texts, TextData ** txt)
Get a text reference from the rcd_file, retrieve the corresponding text data, and put it in the txt destination.
Parameters
rcd_file File to load from.
texts Texts already loaded from this file.
[out] txt Pointer to write the loaded text data reference to.
Returns
Loading was successful.
Definition at line 276 of file sprite_store.cpp.
References RcdFileReader::GetUInt32().
Referenced by ShopType::Load(), CoasterType::Load(), and GuiSprites::LoadGSLP().
static PersonType DecodePersonType (uint8 pt) static
Decode a read value to the internal representation of a person type.
Parameters
pt Value read from the file.
Returns
Decoded person type, or PERSON_INVALID when decoding fails.
Definition at line 604 of file sprite_store.cpp.
References PERSON_ANY, PERSON_EARTH, PERSON_INVALID, and PERSON_PILLAR.
Referenced by Animation::Load(), and AnimationSprites::Load().
Rectangle16 GetSpriteSize (const ImageData * imd)
Get the size of an image including its origin.
Parameters
imd Image to inspect.
Returns
Size of the image, including its origin.
Definition at line 1443 of file sprite_store.cpp.
References Rectangle< PT, SZ >::AddPoint(), ImageData::height, ImageData::width, ImageData::xoffset, and ImageData::yoffset.
Referenced by SpriteManager::GetTableSpriteSize(), and SpriteManager::SetSpriteSize().