FreeRCT: sprite_data.h File Reference
sprite_data.h File Reference
Code for sprite data.
Classes
class ImageData
Image data of 8bpp images.
Enumerations
enum ImageFlags { IFG_IS_8BPP = 0 }
Flags of an image in ImageData.
Functions
ImageData * LoadImage (RcdFileReader *rcd_file)
Load 8bpp or 32bpp sprite block from the rcd_file.
void InitImageStorage ()
Initialize image storage.
void DestroyImageStorage ()
Clear all memory.
Variables
static const uint32 INVALID_JUMP = UINT32_MAX
Invalid jump destination in image data.
Detailed Description
Code for sprite data.
Declarations for sprite data.
Definition in file sprite_data.h.
Enumeration Type Documentation
enum ImageFlags
Flags of an image in ImageData.
Enumerator
IFG_IS_8BPP
Bit number used for the image type.
Definition at line 20 of file sprite_data.h.
Function Documentation
ImageData* LoadImage (RcdFileReader * rcd_file)
Load 8bpp or 32bpp sprite block from the rcd_file.
Parameters
rcd_file File being loaded.
Returns
Loaded sprite, if loading was successful, else nullptr.
Definition at line 265 of file sprite_data.cpp.
References ImageData::flags, IFG_IS_8BPP, ImageData::Load32bpp(), ImageData::Load8bpp(), RcdFileReader::name, RcdFileReader::size, and RcdFileReader::version.
Referenced by SpriteManager::Load().
void InitImageStorage ()
Initialize image storage.
Definition at line 282 of file sprite_data.cpp.
Referenced by freerct_main().
void DestroyImageStorage ()
Clear all memory.
Definition at line 288 of file sprite_data.cpp.
Referenced by freerct_main().