FreeRCT: sprite_store.h File Reference
sprite_store.h File Reference
Sprite storage data structure.
#include "orientation.h"
#include "path.h"
#include "tile.h"
#include "fence.h"
#include "person_type.h"
#include "language.h"
#include "track_piece.h"
#include "weather.h"
#include <map>
Classes
class RcdBlock
Block of data from a RCD file.
class TextData
Texts of objects.
class SurfaceData
A surface in all orientations.
class TileCorners
Highlight the currently selected corner of a ground tile with a corner selection sprite.
class Fence
Fence sprites.
class Path
Path sprites.
class PathDecoration
Path decoration sprites.
class Foundation
Foundation sprites.
class Platform
Platform sprites.
class Support
Support sprites.
class DisplayedObject
Displayed object.
struct AnimationFrame
One frame in an animation.
class Animation
Data structure holding a single animation.
class AnimationSprites
Data structure holding sprite of an animation.
struct BorderSpriteData
Sprite data of a border.
struct CheckableWidgetSpriteData
Sprite data of a checkable sprite.
struct SliderSpriteData
Sprite data of a slider bar.
struct ScrollbarSpriteData
Sprite data of a scrollbar.
struct GuiSprites
Sprites of the gui.
class SpriteStorage
Storage of all sprites for a single tile size.
class SpriteManager
Storage and management of all sprites.
Typedefs
typedef std::map< uint32,
ImageData * > ImageMap
Map of loaded image data blocks.
typedef std::map< uint32,
TextData * > TextMap
Map of loaded text blocks.
typedef std::multimap
< AnimationType, Animation * > AnimationsMap
Multi-map of available animations.
typedef std::multimap
< AnimationType,
AnimationSprites * > AnimationSpritesMap
Multi-map of available animation sprites.
Enumerations
enum AnimationType {
ANIM_WALK_NE = 1, ANIM_WALK_SE = 2, ANIM_WALK_SW = 3, ANIM_WALK_NW = 4,
ANIM_BEGIN = ANIM_WALK_NE, ANIM_LAST = ANIM_WALK_NW, ANIM_INVALID = 0xFF
}
Available animations.
enum WidgetBorderSprites {
WBS_TOP_LEFT, WBS_TOP_MIDDLE, WBS_TOP_RIGHT, WBS_MIDDLE_LEFT,
WBS_MIDDLE_MIDDLE, WBS_MIDDLE_RIGHT, WBS_BOTTOM_LEFT, WBS_BOTTOM_MIDDLE,
WBS_BOTTOM_RIGHT, WBS_COUNT
}
Sprites of a border.
enum WidgetCheckableSprites {
WCS_EMPTY, WCS_CHECKED, WCS_EMPTY_PRESSED, WCS_CHECKED_PRESSED,
WCS_SHADED_EMPTY, WCS_SHADED_CHECKED, WCS_COUNT
}
Sprites of checkable sprites, like checkbox or radio button.
enum WidgetSliderSprites {
WSS_LEFT_BED, WSS_MIDDLE_BED, WSS_RIGHT_BED, WSS_BUTTON,
WSS_COUNT
}
Slider sprites.
enum WidgetScrollbarSprites {
WLS_LEFT_BUTTON, WLS_RIGHT_BUTTON, WLS_LEFT_PRESSED_BUTTON, WLS_RIGHT_PRESSED_BUTTON,
WLS_LEFT_BED, WLS_MIDDLE_BED, WLS_RIGHT_BED, WLS_LEFT_SLIDER,
WLS_MIDDLE_SLIDER, WLS_RIGHT_SLIDER, WLS_LEFT_PRESSED_SLIDER, WLS_MIDDLE_PRESSED_SLIDER,
WLS_RIGHT_PRESSED_SLIDER, WLS_COUNT
}
Scrollbar sprites.
enum LightRedOrangeGreen { LROG_RED, LROG_ORANGE, LROG_GREEN, LROG_NONE }
Red/orange/green light sprites.
enum LightRedGreen { LRG_RED, LRG_GREEN, LRG_NONE }
Red/green light sprites.
Functions
bool LoadSpriteFromFile (RcdFileReader *rcd_file, const ImageMap &sprites, ImageData **spr)
Get a sprite reference from the rcd_file, retrieve the corresponding sprite, and put it in the spr destination.
bool LoadTextFromFile (RcdFileReader *rcd_file, const TextMap &texts, TextData **txt)
Get a text reference from the rcd_file, retrieve the corresponding text data, and put it in the txt destination.
Rectangle16 GetSpriteSize (const ImageData *imd)
Get the size of an image including its origin.
Variables
const uint8 _slope_rotation [NUM_SLOPE_SPRITES][4]
Sprite indices of ground/surface sprites after rotation of the view.
SpriteManager _sprite_manager
Sprite manager.
GuiSprites _gui_sprites
GUI sprites.
Detailed Description
Sprite storage data structure.
Definition in file sprite_store.h.
Enumeration Type Documentation
enum AnimationType
Available animations.
Enumerator
ANIM_WALK_NE
Walk in north-east direction.
ANIM_WALK_SE
Walk in south-east direction.
ANIM_WALK_SW
Walk in south-west direction.
ANIM_WALK_NW
Walk in north-west direction.
ANIM_BEGIN
First animation.
ANIM_LAST
Last animation.
ANIM_INVALID
Invalid animation.
Definition at line 195 of file sprite_store.h.
enum LightRedOrangeGreen
Red/orange/green light sprites.
Enumerator
LROG_RED
Red light of the red/orange/green light.
LROG_ORANGE
Orange light of the red/orange/green light.
LROG_GREEN
Green light of the red/orange/green light.
LROG_NONE
No light of the red/orange/green light.
Definition at line 385 of file sprite_store.h.
enum LightRedGreen
Red/green light sprites.
Enumerator
LRG_RED
Red light of the red/green light.
LRG_GREEN
Green light of the red/green light.
LRG_NONE
No light of the red/green light.
Definition at line 393 of file sprite_store.h.
Function Documentation
bool LoadSpriteFromFile (RcdFileReader * rcd_file, const ImageMap & sprites, ImageData ** spr)
Get a sprite reference from the rcd_file, retrieve the corresponding sprite, and put it in the spr destination.
Parameters
rcd_file File to load from.
sprites Sprites already loaded from this file.
[out] spr Pointer to write the loaded sprite to.
Returns
Loading was successful.
Definition at line 256 of file sprite_store.cpp.
References RcdFileReader::GetUInt32().
Referenced by ShopType::Load(), TrackVoxel::Load(), CarType::Load(), Fence::Load(), AnimationSprites::Load(), SpriteManager::LoadBDIR(), LoadCoasterPlatform(), SpriteManager::LoadFUND(), GuiSprites::LoadGBOR(), GuiSprites::LoadGCHK(), GuiSprites::LoadGSCL(), GuiSprites::LoadGSLI(), GuiSprites::LoadGSLP(), SpriteManager::LoadPATH(), SpriteManager::LoadPDEC(), SpriteManager::LoadPLAT(), SpriteManager::LoadSUPP(), SpriteManager::LoadSURF(), SpriteManager::LoadTCOR(), and SpriteManager::LoadTSEL().
bool LoadTextFromFile (RcdFileReader * rcd_file, const TextMap & texts, TextData ** txt)
Get a text reference from the rcd_file, retrieve the corresponding text data, and put it in the txt destination.
Parameters
rcd_file File to load from.
texts Texts already loaded from this file.
[out] txt Pointer to write the loaded text data reference to.
Returns
Loading was successful.
Definition at line 276 of file sprite_store.cpp.
References RcdFileReader::GetUInt32().
Referenced by ShopType::Load(), CoasterType::Load(), and GuiSprites::LoadGSLP().
Rectangle16 GetSpriteSize (const ImageData * imd)
Get the size of an image including its origin.
Parameters
imd Image to inspect.
Returns
Size of the image, including its origin.
Definition at line 1578 of file sprite_store.cpp.
References Rectangle< PT, SZ >::AddPoint(), ImageData::height, ImageData::width, ImageData::xoffset, and ImageData::yoffset.
Referenced by SpriteManager::GetTableSpriteSize(), and SpriteManager::SetSpriteSize().