FreeRCT: string_func.cpp File Reference
string_func.cpp File Reference
Safe string functions.
#include "stdafx.h"
#include "string_func.h"
Functions
char * SafeStrncpy (char *dest, const char *src, int size)
Safe string copy (as in, the destination is always terminated).
uint8 * SafeStrncpy (uint8 *dest, const uint8 *src, int size)
Safe string copy (as in, the destination is always terminated).
char * StrDup (const char *src)
Duplicate a string.
uint8 * StrECpy (uint8 *dest, uint8 *end, const uint8 *src)
String copy up to an end-point of the destination.
size_t StrBytesLength (const uint8 *str)
Get the length of an utf-8 string in bytes.
bool StrEqual (const uint8 *s1, const uint8 *s2)
Are the two strings equal?
bool StrEndsWith (const char *str, const char *end, bool case_sensitive)
Test whether str ends with end.
Detailed Description
Safe string functions.
Definition in file string_func.cpp.
Function Documentation
char* SafeStrncpy (char * dest, const char * src, int size)
Safe string copy (as in, the destination is always terminated).
Parameters
dest Destination of the string.
src Source of the string.
size Number of bytes (including terminating 0) from src.
Returns
Copied string.
Note
The SafeStrncpy(uint8 *dest, const uint8 *src, int size) function is preferred.
Definition at line 23 of file string_func.cpp.
Referenced by MoneyStrFmt(), UnixDirectoryReader::OpenPath(), and StrDup().
uint8* SafeStrncpy (uint8 * dest, const uint8 * src, int size)
Safe string copy (as in, the destination is always terminated).
Parameters
dest Destination of the string.
src Source of the string.
size Number of bytes (including terminating 0) from src.
Returns
Copied string.
Definition at line 39 of file string_func.cpp.
char* StrDup (const char * src)
Duplicate a string.
Parameters
src Source string.
Returns
Copy of the string in its own memory.
Note
String must be deleted later!
Definition at line 54 of file string_func.cpp.
References SafeStrncpy().
Referenced by ConfigItem::ConfigItem(), and ConfigSection::ConfigSection().
uint8* StrECpy (uint8 * dest, uint8 * end, const uint8 * src)
String copy up to an end-point of the destination.
Parameters
dest Start of destination buffer.
end End of destination buffer (*end is never written).
src Source string.
Returns
dest.
Definition at line 70 of file string_func.cpp.
Referenced by TemperatureStrFormat().
size_t StrBytesLength (const uint8 * str)
Get the length of an utf-8 string in bytes.
Parameters
str String to inspect.
Returns
Length of the given string in bytes.
Definition at line 88 of file string_func.cpp.
Referenced by MoneyStrFmt().
bool StrEqual (const uint8 * s1, const uint8 * s2)
Are the two strings equal?
Parameters
s1 First string to compare.
s2 Second string to compare.
Returns
strings are exactly equal.
Definition at line 99 of file string_func.cpp.
Referenced by RidesManager::FindRideByName().
bool StrEndsWith (const char * str, const char * end, bool case_sensitive)
Test whether str ends with end.
Parameters
str String to check.
end Expected end text.
case_sensitive Compare case sensitively.
Returns
str ends with the given end possibly after changing case.
Definition at line 116 of file string_func.cpp.
Referenced by RcdFileCollection::ScanDirectories().