FreeRCT: GroundData Struct Reference
GroundData Struct Reference
World map data and code
Ground data + modification storage.
#include <terraform.h>
Public Member Functions
GroundData (uint8 height, uint8 orig_slope)
Construct a GroundData structure.
uint8 GetOrigHeight (TileCorner corner) const
Get original height (before changing).
bool GetCornerModified (TileCorner corner) const
Return whether the given corner is modified or not.
void SetCornerModified (TileCorner corner)
Set the given corner as modified.
Public Attributes
uint8 height
Height of the voxel with ground.
uint8 orig_slope
Original slope data.
uint8 modified
Raised or lowered corners.
Detailed Description
Ground data + modification storage.
Definition at line 21 of file terraform.h.
Constructor & Destructor Documentation
GroundData::GroundData (uint8 height, uint8 orig_slope)
Construct a GroundData structure.
Parameters
height Height of the voxel containing the surface (for steep slopes, the base height).
orig_slope Original slope (that is, before the raise or lower).
Definition at line 60 of file terraform.cpp.
References height, modified, and orig_slope.
Member Function Documentation
uint8 GroundData::GetOrigHeight (TileCorner corner) const
Get original height (before changing).
Parameters
corner Corner to get height.
Returns
Original height of the indicated corner.
Definition at line 72 of file terraform.cpp.
References height, orig_slope, TC_END, TC_NORTH, and TSB_STEEP.
Referenced by TerrainChanges::ChangeCorner(), TerrainChanges::ChangeVoxel(), and TerrainChanges::UpdatelevellingHeight().
bool GroundData::GetCornerModified (TileCorner corner) const
Return whether the given corner is modified or not.
Parameters
corner Corner to test.
Returns
corner is modified.
Definition at line 102 of file terraform.cpp.
References modified, TC_END, and TC_NORTH.
Referenced by TerrainChanges::ChangeCorner().
void GroundData::SetCornerModified (TileCorner corner)
Set the given corner as modified.
Parameters
corner Corner to set.
Returns
corner is modified.
Definition at line 91 of file terraform.cpp.
References modified, TC_END, and TC_NORTH.
Referenced by TerrainChanges::ChangeCorner().
The documentation for this struct was generated from the following files:
terraform.h
terraform.cpp