FreeRCT: StringParameters Struct Reference
StringParameters Struct Reference
All string parameters.
#include <language.h>
Public Member Functions
void SetNone (int num)
Mark string parameter num as 'unused'.
void SetStrID (int num, StringID strid)
Mark string parameter num to contain a parameter-less string.
void SetNumber (int num, int64 number)
Mark string parameter num to contain a number.
void SetMoney (int num, const Money &amount)
Mark string parameter num to contain an amount of money.
void SetDate (int num, const Date &date)
Mark string parameter num to contain a date.
void SetTemperature (int num, int value)
Mark string parameter num to contain a temperature.
void SetUint8 (int num, const uint8 *text)
Mark string parameter num to contain a C-style UTF-8 string.
void Clear ()
Clear all data from the parameters.
Public Attributes
bool set_mode
When not in set-mode, all parameters are cleared on first use of a Set function.
StringParameterData parms [16]
Parameters of the string, arbitrary limit.
Detailed Description
All string parameters.
Definition at line 124 of file language.h.
Member Function Documentation
void StringParameters::SetNone (int num)
Mark string parameter num as 'unused'.
Parameters
num Number of the parameter to set (1-based).
Definition at line 87 of file language.cpp.
References lengthof, StringParameterData::parm_type, parms, and SPT_NONE.
Referenced by Clear().
void StringParameters::SetStrID (int num, StringID strid)
Mark string parameter num to contain a parameter-less string.
Parameters
num Number of the parameter to set (1-based).
strid String id of the parameter.
Definition at line 99 of file language.cpp.
References Clear(), lengthof, StringParameterData::parm_type, parms, set_mode, SPT_STRID, StringParameterData::str, and StringParameterData::u.
Referenced by RidesManager::NewInstanceAdded(), SettingWindow::SetWidgetStringParameters(), ToolbarWindow::SetWidgetStringParameters(), ErrorMessageWindow::SetWidgetStringParameters(), GuestInfoWindow::SetWidgetStringParameters(), and ToolbarWindow::UpdateWidgetSize().
void StringParameters::SetNumber (int num, int64 number)
Mark string parameter num to contain a number.
Parameters
num Number of the parameter to set (1-based).
number Number value of the parameter.
Definition at line 114 of file language.cpp.
References Clear(), lengthof, StringParameterData::number, StringParameterData::parm_type, parms, set_mode, SPT_NUMBER, and StringParameterData::u.
Referenced by RidesManager::NewInstanceAdded(), SettingWindow::OnClick(), SettingWindow::SetWidgetStringParameters(), GuestInfoWindow::SetWidgetStringParameters(), ShopManagerWindow::SetWidgetStringParameters(), and BottomToolbarWindow::UpdateWidgetSize().
void StringParameters::SetMoney (int num, const Money & amount)
Mark string parameter num to contain an amount of money.
Parameters
num Number of the parameter to set (1-based).
amount Amount of money to output.
Definition at line 129 of file language.cpp.
References Clear(), lengthof, StringParameterData::number, StringParameterData::parm_type, parms, set_mode, SPT_MONEY, and StringParameterData::u.
Referenced by FinancesManager::CashToStrParams(), FinancesGui::SetWidgetStringParameters(), GuestInfoWindow::SetWidgetStringParameters(), and ShopManagerWindow::SetWidgetStringParameters().
void StringParameters::SetDate (int num, const Date & date)
Mark string parameter num to contain a date.
Parameters
num Number of the parameter to set (1-based).
date Date to output.
Definition at line 159 of file language.cpp.
References Clear(), Date::Compress(), StringParameterData::dmy, lengthof, StringParameterData::parm_type, parms, set_mode, SPT_DATE, and StringParameterData::u.
Referenced by BottomToolbarWindow::SetWidgetStringParameters().
void StringParameters::SetTemperature (int num, int value)
Mark string parameter num to contain a temperature.
Parameters
num Number of the parameter to set (1-based).
value Temperature value in 1/10 degrees Celcius.
Definition at line 144 of file language.cpp.
References Clear(), lengthof, StringParameterData::number, StringParameterData::parm_type, parms, set_mode, SPT_TEMPERATURE, and StringParameterData::u.
Referenced by BottomToolbarWindow::SetWidgetStringParameters(), and BottomToolbarWindow::UpdateWidgetSize().
void StringParameters::SetUint8 (int num, const uint8 * text)
Mark string parameter num to contain a C-style UTF-8 string.
Parameters
num Number of the parameter to set (1-based).
text UTF-8 string. Is not released after use.
Definition at line 174 of file language.cpp.
References Clear(), lengthof, StringParameterData::parm_type, parms, set_mode, SPT_UINT8, text, StringParameterData::text, and StringParameterData::u.
Referenced by SettingWindow::OnClick(), CoasterInstanceWindow::SetWidgetStringParameters(), GuestInfoWindow::SetWidgetStringParameters(), ShopManagerWindow::SetWidgetStringParameters(), and CoasterBuildWindow::SetWidgetStringParameters().
void StringParameters::Clear ()
Clear all data from the parameters.
Does not free memory.
Definition at line 185 of file language.cpp.
References lengthof, parms, set_mode, and SetNone().
Referenced by SetDate(), SetMoney(), SetNumber(), SetStrID(), SetTemperature(), and SetUint8().
The documentation for this struct was generated from the following files:
language.h
language.cpp