FreeRCT: ScrollbarSpriteData Struct Reference
ScrollbarSpriteData Struct Reference
Sprites and sprite handling » GUI sprites and sprite handling
Sprite data of a scrollbar.
#include <sprite_store.h>
Public Member Functions
void Clear ()
Clear the scrollbar sprite data.
bool IsLoaded () const
Check whether the scrollbar sprite data is actually loaded.
Public Attributes
uint16 min_length_all
Total minimal length of the bar.
uint16 min_length_slider
Minimal length of the slider.
uint8 stepsize_bar
Length increment of the slider underground.
uint8 stepsize_slider
Length increment of the slider.
uint16 height
Height/width of the entire bar.
ImageData * normal [WLS_COUNT]
Sprites for a normal scrollbar.
ImageData * shaded [WLS_COUNT]
Sprites for a shaded scrollbar.
Detailed Description
Sprite data of a scrollbar.
Definition at line 369 of file sprite_store.h.
Member Function Documentation
void ScrollbarSpriteData::Clear ()
Clear the scrollbar sprite data.
Definition at line 1014 of file sprite_store.cpp.
References height, min_length_all, min_length_slider, normal, shaded, stepsize_bar, stepsize_slider, and WLS_COUNT.
Referenced by GuiSprites::Clear().
bool ScrollbarSpriteData::IsLoaded () const
Check whether the scrollbar sprite data is actually loaded.
Returns
Whether the sprite data is loaded.
Definition at line 1032 of file sprite_store.cpp.
References height, and min_length_all.
Referenced by ScrollbarWidget::Draw(), and GuiSprites::HasSufficientGraphics().
The documentation for this struct was generated from the following files:
sprite_store.h
sprite_store.cpp