FreeRCT: Scenario Struct Reference
Scenario Struct Reference
Scenario settings.
#include <gamelevel.h>
Public Member Functions
Scenario ()
Scenario default constructor.
void SetDefaultScenario ()
Default scenario settings.
uint GetSpawnProbability (int popularity)
Get probability of spawning a new guest.
Public Attributes
uint16 spawn_lowest
Guest spawn probability at lowest popularity (0..1024).
uint16 spawn_highest
Guest spawn probability at highest popularity (0..1024).
uint16 max_guests
Maximal number of guests.
Money inital_money
Initial amount of money of the player.
Money lowest_money
Lowest amount of money of the player.
uint8 interest
Interest rate in 0.1 percent over the negative amount.
Detailed Description
Scenario settings.
Definition at line 18 of file gamelevel.h.
Constructor & Destructor Documentation
Scenario::Scenario ()
Scenario default constructor.
Definition at line 18 of file gamelevel.cpp.
References SetDefaultScenario().
Member Function Documentation
void Scenario::SetDefaultScenario ()
Default scenario settings.
Default settings are useful for debugging, and unlikely to be of use for a 'real' game.
Definition at line 27 of file gamelevel.cpp.
References inital_money, interest, lowest_money, max_guests, spawn_highest, and spawn_lowest.
Referenced by Scenario().
uint Scenario::GetSpawnProbability (int popularity)
Get probability of spawning a new guest.
Parameters
popularity Current popularity of the park (0..1024).
Returns
Spawning popularity between 0 and 1023 (inclusive).
Definition at line 42 of file gamelevel.cpp.
References spawn_highest, and spawn_lowest.
Referenced by Guests::OnNewDay().
The documentation for this struct was generated from the following files:
gamelevel.h
gamelevel.cpp