FreeRCT: RecolourEntry Struct Reference
RecolourEntry Struct Reference
A recolour entry, defining a source colour range to replace with the dest colour range, where dest must be in dest_set.
#include <palette.h>
Public Member Functions
RecolourEntry ()
Default constructor.
RecolourEntry (uint32 recol)
Constructor for an encoded recolour entry.
RecolourEntry (ColourRange source, ColourRange dest)
Recolour entry mapping a source range directly to a dest range.
RecolourEntry (ColourRange source, uint32 dest_set, ColourRange dest)
Constructor with all data members.
RecolourEntry (const RecolourEntry &orig)
Copy constructor.
RecolourEntry & operator= (const RecolourEntry &orig)
Assignment operator.
void AssignDest (ColourRange dest)
Assign a destination colour range to the entry.
bool IsValid () const
Test whether the entry is filled and ready for use.
Public Attributes
ColourRange source
Source colour range to replace. Only used for 8bpp images, the value COL_RANGE_INVALID means the entry is not used.
ColourRange dest
Destination colour range to use instead. The value COL_RANGE_INVALID means no choice has been made yet.
uint32 dest_set
Bit set of destination colour ranges to chose from.
Detailed Description
A recolour entry, defining a source colour range to replace with the dest colour range, where dest must be in dest_set.
Definition at line 271 of file palette.h.
Constructor & Destructor Documentation
RecolourEntry::RecolourEntry ()
Default constructor.
Definition at line 19 of file palette.cpp.
RecolourEntry::RecolourEntry (uint32 value)
Constructor for an encoded recolour entry.
Parameters
value Encoded recolouring.
Definition at line 27 of file palette.cpp.
References COL_RANGE_COUNT, COL_RANGE_INVALID, dest, dest_set, and source.
RecolourEntry::RecolourEntry (ColourRange source, ColourRange dest)
Recolour entry mapping a source range directly to a dest range.
Parameters
source Source colour range to convert.
dest Replacement colour range.
Definition at line 40 of file palette.cpp.
References COL_RANGE_COUNT, dest, dest_set, and source.
RecolourEntry::RecolourEntry (ColourRange source, uint32 dest_set, ColourRange dest)
Constructor with all data members.
Parameters
source Source range of the entry.
dest_set Bit set of allowed destination ranges (bits 0 to 17 inclusive).
dest Destination range (if provided, else COL_RANGE_INVALID).
Definition at line 56 of file palette.cpp.
RecolourEntry::RecolourEntry (const RecolourEntry & orig)
Copy constructor.
Parameters
orig Existing value to copy.
Definition at line 64 of file palette.cpp.
References dest, dest_set, and source.
Member Function Documentation
RecolourEntry & RecolourEntry::operator= (const RecolourEntry & orig)
Assignment operator.
Parameters
orig Existing value to copy.
Returns
The assigned value.
Definition at line 76 of file palette.cpp.
References dest, dest_set, and source.
void RecolourEntry::AssignDest (ColourRange dest)
Assign a destination colour range to the entry.
Parameters
dest Destination colour range to use.
Definition at line 90 of file palette.cpp.
References COL_RANGE_COUNT, COL_RANGE_INVALID, dest, dest_set, GB(), and source.
Referenced by Recolouring::AssignRandomColours().
bool RecolourEntry::IsValid () const inline
Test whether the entry is filled and ready for use.
Returns
Whether the entry is ready for use.
Definition at line 285 of file palette.h.
References COL_RANGE_COUNT.
Referenced by ShopManagerWindow::OnClick(), and ShopManagerWindow::ShopManagerWindow().
The documentation for this struct was generated from the following files:
palette.h
palette.cpp