FreeRCT: Voxel Struct Reference
Voxel Struct Reference
World map data and code
One voxel cell in the world.
#include <map.h>
Public Member Functions
SmallRideInstance GetInstance () const
Get the ride instance at this voxel.
void SetInstance (SmallRideInstance instance)
Set the ride instance at this voxel.
bool CanPlaceInstance () const
Can a ride instance be placed here?
void ClearInstances ()
Remove all instances from this voxel.
uint16 GetInstanceData () const
Get the data associated with the ride instance in this voxel.
void SetInstanceData (uint16 instance_data)
Set the data associated with the ride instance in this voxel.
FenceType GetFenceType (TileEdge edge) const
Set the fence type of one of the four edges.
void SetFenceType (TileEdge edge, FenceType fence_type)
Set the fence type of one of the four edges.
uint8 GetFoundationSlope () const
Get the foundation slope of a surface voxel.
FoundationType GetFoundationType () const
Get the foundation type of a surface voxel.
void SetFoundationSlope (uint8 fnd_slope)
Set the foundation slope of a surface voxel.
void SetFoundationType (FoundationType fnd_type)
Set the foundation type of a surface voxel.
uint8 GetGroundSlope () const
Get the imploded ground slope of a surface voxel.
GroundType GetGroundType () const
Get the ground type of a surface voxel.
uint8 GetGrowth () const
Get the growth.
void SetGroundSlope (uint8 gnd_slope)
Set the imploded ground slope of a surface voxel.
void SetGroundType (GroundType gnd_type)
Set the ground type of a surface voxel.
void SetGrowth (uint8 growth)
Set the growth.
bool IsEmpty () const
Is the voxel empty?
void ClearVoxel ()
Make the voxel empty.
bool HasVoxelObjects () const
Does the voxel have any voxel objects currently?
void Save (Saver &svr) const
Write a voxel to the save game.
void Load (Loader &ldr, uint32 version)
Load a voxel from the save game.
Public Attributes
uint8 instance
Ride instances that uses this voxel.
uint16 instance_data
Voxel data of the instance stored here.
uint16 fence
4 bits used for each edge. EDGE_NE..EDGE_NW. Gives the fence type or FENCE_TYPE_INVALID if the voxel has no fence for this edge.
uint32 ground
Ground and foundations.
VoxelObject * voxel_objects
First voxel object in this voxel.
Detailed Description
One voxel cell in the world.
A voxel consists of four parts and the ground data. Each part covers one corner. They are numbered using the TileCorner values. A part consists of
The instance number of the ride that uses the part.
The voxel definition of the ride. This defines what sprite to draw. A ride may attach other meaning to the number, for example use some bits to display variations. The ground data contains the foundations, and the ground (grass).
Definition at line 63 of file map.h.
Member Function Documentation
SmallRideInstance Voxel::GetInstance () const inline
Get the ride instance at this voxel.
Returns
Ride instance at this voxel.
Definition at line 72 of file map.h.
References instance.
Referenced by BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), CanPlaceInstance(), ShopPlacementManager::CanPlaceShop(), SpriteCollector::CollectVoxel(), PixelFinder::CollectVoxel(), ExamineNeighbourPathEdge(), GetPathExits(), IsEmpty(), Viewport::MarkVoxelDirty(), Person::OnAnimate(), RemovePath(), CoasterInstance::RemoveTrackPieceInAdditions(), RideExistsAtBottom(), SetUpperBoundary(), and SpriteCollector::SetupSupports().
void Voxel::SetInstance (SmallRideInstance instance) inline
Set the ride instance at this voxel.
Parameters
instance Ride instance at this voxel.
Definition at line 81 of file map.h.
References instance.
Referenced by BuildPathAtTile(), ClearInstances(), CoasterInstance::PlaceTrackPieceInAdditions(), RemovePathAtTile(), and CoasterInstance::RemoveTrackPieceInAdditions().
bool Voxel::CanPlaceInstance () const inline
Can a ride instance be placed here?
Returns
true if the instance can be placed, false if not.
Definition at line 90 of file map.h.
References GetInstance(), and SRI_FREE.
Referenced by PositionedTrackPiece::CanBePlaced(), and ShopPlacementManager::CanPlaceShop().
void Voxel::ClearInstances () inline
Remove all instances from this voxel.
Definition at line 96 of file map.h.
References SetInstance(), and SRI_FREE.
Referenced by ClearVoxel(), and VoxelWorld::MakeFlatWorld().
uint16 Voxel::GetInstanceData () const inline
Get the data associated with the ride instance in this voxel.
Returns
Voxel data stored in this voxel.
Definition at line 105 of file map.h.
References instance_data.
Referenced by SpriteCollector::CollectVoxel(), PixelFinder::CollectVoxel(), ExamineNeighbourPathEdge(), Guest::GetExitDirections(), GetPathExits(), RemovePath(), and TravelQueuePath().
void Voxel::SetInstanceData (uint16 instance_data) inline
Set the data associated with the ride instance in this voxel.
Parameters
instance_data The voxel data stored in this voxel.
Definition at line 114 of file map.h.
References instance_data.
Referenced by AddRemovePathEdges(), BuildPathAtTile(), CoasterInstance::PlaceTrackPieceInAdditions(), RemovePathAtTile(), and CoasterInstance::RemoveTrackPieceInAdditions().
FenceType Voxel::GetFenceType (TileEdge edge) const inline
Set the fence type of one of the four edges.
Parameters
edge The edge to modify EDGE_NE..EDGE_NW
Returns
The fence type or FENCE_TYPE_INVALID if the edge has no fence
Note
For steep slope all fences are stored in the top voxel. For non-steep slope that have both corners raised, the fence type is stored in the voxel above. This method will get what is stored in this voxel. You need to make sure to call this method for the right voxel in the voxel stack.
Definition at line 130 of file map.h.
References GB().
Referenced by SpriteCollector::CollectVoxel(), TerrainChanges::ModifyWorld(), and UpdateLandBorderFence().
void Voxel::SetFenceType (TileEdge edge, FenceType fence_type) inline
Set the fence type of one of the four edges.
Parameters
edge The edge to modify EDGE_NE..EDGE_NW
fence_type The fence type to use or FENCE_TYPE_INVALID to disable fence of this edge
Note
For steep slope all fences should be stored in the top voxel. For non-steep slope that have both corners raised, the fence type should be stored in the voxel above. This method will set the fence type of the given voxel. You need to make sure to call this method for the right voxel in the voxel stack.
Definition at line 144 of file map.h.
References FENCE_TYPE_COUNT, FENCE_TYPE_INVALID, and SB().
Referenced by ClearVoxel(), TerrainChanges::ModifyWorld(), FenceBuildManager::OnMouseButtonEvent(), and UpdateLandBorderFence().
uint8 Voxel::GetFoundationSlope () const inline
Get the foundation slope of a surface voxel.
Returns
The foundation slope.
Definition at line 174 of file map.h.
References GB().
Referenced by AddFoundations(), SpriteCollector::CollectVoxel(), and SetFoundations().
FoundationType Voxel::GetFoundationType () const inline
Get the foundation type of a surface voxel.
Returns
The foundation type.
Definition at line 183 of file map.h.
References GB().
Referenced by AddFoundations(), BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), SpriteCollector::CollectVoxel(), IsEmpty(), TerrainChanges::ModifyWorld(), and SetFoundations().
void Voxel::SetFoundationSlope (uint8 fnd_slope) inline
Set the foundation slope of a surface voxel.
Parameters
fnd_slope The new foundation slope.
Definition at line 193 of file map.h.
References SB().
Referenced by AddFoundations(), TerrainChanges::ModifyWorld(), and SetFoundations().
void Voxel::SetFoundationType (FoundationType fnd_type) inline
Set the foundation type of a surface voxel.
Parameters
fnd_type The foundation type.
Definition at line 202 of file map.h.
References FDT_COUNT, FDT_INVALID, and SB().
Referenced by AddFoundations(), ClearVoxel(), VoxelWorld::MakeFlatWorld(), TerrainChanges::ModifyWorld(), and SetFoundations().
uint8 Voxel::GetGroundSlope () const inline
Get the imploded ground slope of a surface voxel.
Steep slopes are two voxels high (a bottom and a top part).
Returns
The imploded ground slope.
Definition at line 215 of file map.h.
References GB().
Referenced by BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), ShopPlacementManager::CanPlaceShop(), SpriteCollector::CollectVoxel(), PixelFinder::CollectVoxel(), TerrainChanges::GetGroundData(), VoxelStack::GetGroundOffset(), GetPathAttachPoints(), Viewport::MarkVoxelDirty(), TerrainChanges::ModifyWorld(), PathBuildManager::MoveCursor(), FenceBuildManager::OnMouseButtonEvent(), PathBuildManager::SelectMovement(), FenceBuildManager::SetCursors(), SpriteCollector::SetupSupports(), SetXFoundations(), SetYFoundations(), and UpdateLandBorderFence().
GroundType Voxel::GetGroundType () const inline
Get the ground type of a surface voxel.
Returns
The ground type.
Definition at line 224 of file map.h.
References GB().
Referenced by BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), ShopPlacementManager::CanPlaceShop(), SpriteCollector::CollectVoxel(), PixelFinder::CollectVoxel(), TerrainChanges::GetGroundData(), VoxelStack::GetGroundOffset(), GetPathAttachPoints(), IsEmpty(), Viewport::MarkVoxelDirty(), TerrainChanges::ModifyWorld(), PathBuildManager::MoveCursor(), PathBuildManager::SelectMovement(), SetUpperBoundary(), SpriteCollector::SetupSupports(), SetXFoundations(), SetYFoundations(), and UpdateLandBorderFence().
uint8 Voxel::GetGrowth () const inline
Get the growth.
Returns
The growth of the grass.
Todo:
Increment this value and (change ground type to other grass kinds) regularly to simulate grass growth.
Definition at line 235 of file map.h.
References GB().
void Voxel::SetGroundSlope (uint8 gnd_slope) inline
Set the imploded ground slope of a surface voxel.
Steep slopes are two voxels high (a bottom and a top part).
Parameters
gnd_slope The new imploded ground slope.
Definition at line 245 of file map.h.
References SB().
Referenced by VoxelWorld::MakeFlatWorld(), and TerrainChanges::ModifyWorld().
void Voxel::SetGroundType (GroundType gnd_type) inline
Set the ground type of a surface voxel.
Parameters
gnd_type The ground type.
Definition at line 255 of file map.h.
References GTP_COUNT, GTP_INVALID, and SB().
Referenced by ClearVoxel(), VoxelWorld::MakeFlatWorld(), and TerrainChanges::ModifyWorld().
void Voxel::SetGrowth (uint8 growth) inline
Set the growth.
Parameters
growth New growth value.
Todo:
Increment this value and (change ground type to other grass kinds) regularly to simulate grass growth.
Definition at line 266 of file map.h.
References SB().
Referenced by ClearVoxel().
bool Voxel::IsEmpty () const inline
Is the voxel empty?
Returns
true if it is empty, false otherwise.
Definition at line 276 of file map.h.
References FDT_INVALID, GetFoundationType(), GetGroundType(), GetInstance(), GTP_INVALID, and SRI_FREE.
Referenced by BuildDownwardPath(), BuildFlatPath(), BuildUpwardPath(), VoxelStack::MoveStack(), and SetUpperBoundary().
void Voxel::ClearVoxel () inline
Make the voxel empty.
Definition at line 282 of file map.h.
References ClearInstances(), EDGE_BEGIN, EDGE_COUNT, FDT_INVALID, FENCE_TYPE_INVALID, GTP_INVALID, SetFenceType(), SetFoundationType(), SetGroundType(), and SetGrowth().
Referenced by BuildPathAtTile(), and Load().
bool Voxel::HasVoxelObjects () const inline
Does the voxel have any voxel objects currently?
Returns
Whether it has any voxel objects (false means it has no voxel objects).
Definition at line 299 of file map.h.
Referenced by VoxelStack::MoveStack().
void Voxel::Save (Saver & svr) const
Write a voxel to the save game.
Parameters
svr Output stream to write.
Definition at line 100 of file map.cpp.
References ground, instance, instance_data, Saver::PutByte(), Saver::PutLong(), Saver::PutWord(), SRI_FREE, SRI_FULL_RIDES, and SRI_RIDES_START.
void Voxel::Load (Loader & ldr, uint32 version)
Load a voxel from the save game.
Parameters
ldr Input stream to read.
version Version to load.
Todo:
Check sanity of the data.
Definition at line 77 of file map.cpp.
References ClearVoxel(), Loader::GetByte(), Loader::GetLong(), Loader::GetWord(), ground, instance, instance_data, Loader::SetFailMessage(), SRI_FREE, SRI_FULL_RIDES, and SRI_RIDES_START.
Member Data Documentation
uint32 Voxel::ground
Ground and foundations.
bit 0.. 3 (4): Type of foundation.
See also
FoundationType
bit 4.. 7 (4): Ground type.
See also
GroundType
bit 8..15 (8): Foundation slopes:
bit 8: Northern corner of NE edge is up.
bit 9: Eastern corner of NE edge is up.
bit 10: Eastern corner of SE edge is up.
bit 11: Southern corner of SE edge is up.
bit 12: Southern corner of SW edge is up.
bit 13: Western corner of SW edge is up.
bit 14: Western corner of NW edge is up.
bit 15: Northern corner of NW edge is up.
bit 16..20 (5): Imploded ground slope.
See also
ExpandTileSlope
bit 21..23 (3): Growth of the tile grass.
Definition at line 166 of file map.h.
Referenced by CopyVoxel(), Load(), and Save().
The documentation for this struct was generated from the following files:
map.h
map.cpp