FreeRCT: Rectangle< PT, SZ > Struct Template Reference
Rectangle< PT, SZ > Struct Template Reference
An area in 2D.
#include <geometry.h>
Public Member Functions
Rectangle ()
Default constructor.
Rectangle (typename PT::CoordType x, typename PT::CoordType y, SZ w, SZ h)
Construct a rectangle with the given data.
Rectangle (const Rectangle< PT, SZ > &rect)
Copy constructor.
Rectangle & operator= (const Rectangle< PT, SZ > &rect)
Assignment operator.
bool Intersects (const Rectangle< PT, SZ > &rect) const
Do the rectangles intersect with each other?
template<typename CT >
bool IsPointInside (const Point< CT > &pt)
Is a given coordinate inside the rectangle?
template<typename CT >
void AddPoint (const Point< CT > &pt)
Change the rectangle coordinates such that the given point is inside the rectangle.
void AddPoint (typename PT::CoordType xpos, typename PT::CoordType ypos)
Change the rectangle coordinates such that the given point is inside the rectangle.
void RestrictTo (const Rectangle< PT, SZ > &rect)
Restrict the rectangle to the given area (this is, ensure it is completely inside the provided area).
void RestrictTo (typename PT::CoordType startx, typename PT::CoordType starty, SZ w, SZ h)
Restrict the rectangle to the given area (this is, ensure it is completely inside the provided area).
void MergeArea (const Rectangle< PT, SZ > &rect)
Merge the area of the provided rectangle with this rectangle, so both areas are included.
void MergeArea (typename PT::CoordType startx, typename PT::CoordType starty, SZ w, SZ h)
Merge the area of the provided rectangle coordinates with this rectangle, so both areas are included.
Public Attributes
PT base
Base coordinate.
SZ width
Width of the rectangle.
SZ height
Height of the rectangle.
Detailed Description
template<typename PT, typename SZ>
struct Rectangle< PT, SZ >
An area in 2D.
Template Parameters
PT Base point type.
SZ Size type.
Definition at line 177 of file geometry.h.
Constructor & Destructor Documentation
template<typename PT, typename SZ> Rectangle< PT, SZ >::Rectangle () inline
Default constructor.
Definition at line 179 of file geometry.h.
template<typename PT, typename SZ> Rectangle< PT, SZ >::Rectangle (typename PT::CoordType x, typename PT::CoordType y, SZ w, SZ h) inline
Construct a rectangle with the given data.
Parameters
x X position of the top-left edge.
y Y position of the top-left edge.
w Width of the rectangle.
h Height of the rectangle.
Definition at line 194 of file geometry.h.
template<typename PT, typename SZ> Rectangle< PT, SZ >::Rectangle (const Rectangle< PT, SZ > & rect) inline
Copy constructor.
Parameters
rect Rectangle to copy.
Definition at line 206 of file geometry.h.
Member Function Documentation
template<typename PT, typename SZ> Rectangle& Rectangle< PT, SZ >::operator= (const Rectangle< PT, SZ > & rect) inline
Assignment operator.
Parameters
rect Rectangle to copy.
Returns
The assigned value.
Definition at line 219 of file geometry.h.
template<typename PT, typename SZ> bool Rectangle< PT, SZ >::Intersects (const Rectangle< PT, SZ > & rect) const inline
Do the rectangles intersect with each other?
Parameters
rect Other rectangle.
Returns
Rectangles intersect with each other.
Definition at line 235 of file geometry.h.
template<typename PT, typename SZ> template<typename CT > bool Rectangle< PT, SZ >::IsPointInside (const Point< CT > & pt) inline
Is a given coordinate inside the rectangle?
Parameters
pt Point to test.
Template Parameters
CT Coordinate type of the point (implicit).
Returns
The given coordinate is inside the rectangle.
Definition at line 251 of file geometry.h.
Referenced by WindowManager::FindWindowByPosition(), MultiCursor::GetCursor(), MultiCursor::GetMaxCursorHeight(), BaseWidget::GetWidgetByPosition(), BackgroundWidget::GetWidgetByPosition(), IntermediateWidget::GetWidgetByPosition(), WindowManager::MouseButtonEvent(), WindowManager::RepositionAllWindows(), MultiCursor::ResetZPosition(), and WindowManager::StartWindowMove().
template<typename PT, typename SZ> template<typename CT > void Rectangle< PT, SZ >::AddPoint (const Point< CT > & pt) inline
Change the rectangle coordinates such that the given point is inside the rectangle.
Parameters
pt Point to add.
Definition at line 263 of file geometry.h.
Referenced by Rectangle< Point16, uint16 >::AddPoint(), GetSpriteSize(), and Rectangle< Point16, uint16 >::MergeArea().
template<typename PT, typename SZ> void Rectangle< PT, SZ >::AddPoint (typename PT::CoordType xpos, typename PT::CoordType ypos) inline
Change the rectangle coordinates such that the given point is inside the rectangle.
Parameters
xpos X position of the point to add.
ypos Y position of the point to add.
Definition at line 273 of file geometry.h.
template<typename PT, typename SZ> void Rectangle< PT, SZ >::RestrictTo (const Rectangle< PT, SZ > & rect) inline
Restrict the rectangle to the given area (this is, ensure it is completely inside the provided area).
Parameters
rect Rectangle to restrict to.
Definition at line 300 of file geometry.h.
Referenced by OverlayShaded(), Rectangle< Point16, uint16 >::RestrictTo(), and MultiCursor::SetCursor().
template<typename PT, typename SZ> void Rectangle< PT, SZ >::RestrictTo (typename PT::CoordType startx, typename PT::CoordType starty, SZ w, SZ h) inline
Restrict the rectangle to the given area (this is, ensure it is completely inside the provided area).
Parameters
startx Base X coordinate of the area to restrict to.
starty Base Y coordinate of the area to restrict to.
w Horizontal length of the area to restrict to.
h Vertical length of the area to restrict to.
Definition at line 312 of file geometry.h.
template<typename PT, typename SZ> void Rectangle< PT, SZ >::MergeArea (const Rectangle< PT, SZ > & rect) inline
Merge the area of the provided rectangle with this rectangle, so both areas are included.
Parameters
rect Rectangle to merge.
Definition at line 331 of file geometry.h.
Referenced by Rectangle< Point16, uint16 >::MergeArea(), and SpriteManager::SetSpriteSize().
template<typename PT, typename SZ> void Rectangle< PT, SZ >::MergeArea (typename PT::CoordType startx, typename PT::CoordType starty, SZ w, SZ h) inline
Merge the area of the provided rectangle coordinates with this rectangle, so both areas are included.
Parameters
startx Base X coordinate of the area to merge.
starty Base Y coordinate of the area to merge.
w Horizontal length of the area to merge.
h Vertical length of the area to merge.
Definition at line 343 of file geometry.h.
The documentation for this struct was generated from the following file:
geometry.h