FreeRCT: GuiSprites Struct Reference
GuiSprites Struct Reference
Sprites and sprite handling » GUI sprites and sprite handling
Sprites of the gui.
#include <sprite_store.h>
Public Member Functions
GuiSprites ()
Default constructor.
void Clear ()
Clear all GUI sprite data.
bool LoadGBOR (RcdFileReader *rcd_file, const ImageMap &sprites)
Load sprites of a GUI widget border.
bool LoadGCHK (RcdFileReader *rcd_file, const ImageMap &sprites)
Load checkbox and radio button GUI sprites.
bool LoadGSLI (RcdFileReader *rcd_file, const ImageMap &sprites)
Load slider bar sprite data.
bool LoadGSCL (RcdFileReader *rcd_file, const ImageMap &sprites)
Load scroll bar sprite data.
bool LoadGSLP (RcdFileReader *rcd_file, const ImageMap &sprites, const TextMap &texts)
Load GUI slope selection sprites.
bool HasSufficientGraphics () const
Have essential GUI sprites been loaded to be used in a display.
Public Attributes
BorderSpriteData titlebar
Title bar sprite data.
BorderSpriteData button
Normal button sprite data.
BorderSpriteData left_tabbar
Sprite data of the left filler of a tab bar row.
BorderSpriteData tab_tabbar
Sprite data of the tab in the tab bar row.
BorderSpriteData right_tabbar
Sprite data of the right filler of a tab bar row.
BorderSpriteData tabbar_panel
Sprite data of the panel below a tab bar row.
BorderSpriteData panel
Sprite data of the normal panel.
CheckableWidgetSpriteData checkbox
Check box sprite data.
CheckableWidgetSpriteData radio_button
Radio button sprite data.
SliderSpriteData hor_slider
Horizontal slider bar sprite data.
SliderSpriteData vert_slider
Vertical slider bar sprite data.
ScrollbarSpriteData hor_scroll
Horizontal scroll bar sprite data.
ScrollbarSpriteData vert_scroll
Vertical scroll bar sprite data.
ImageData * slope_select [TSL_COUNT_VERTICAL]
Slope selection sprites.
ImageData * bend_select [TBN_COUNT]
Bend selection sprites.
ImageData * bank_select [TPB_COUNT]
Banking selection sprites.
ImageData * platform_select [2]
Platform selection sprites.
ImageData * power_select [2]
Power selection sprites.
ImageData * triangle_left
Triangular arrow to the left.
ImageData * triangle_right
Triangular arrow to the right.
ImageData * triangle_up
Triangular upward arrow.
ImageData * triangle_down
Triangular downward arrow.
ImageData * disabled
Overlay sprite over disabled buttons.
ImageData * rot_2d_pos
2D rotation positive direction.
ImageData * rot_2d_neg
2D rotation negative direction.
ImageData * rot_3d_pos
3D rotation positive direction.
ImageData * rot_3d_neg
3D rotation negative direction.
ImageData * close_sprite
Close window button.
ImageData * dot_sprite
'Dot' in the terraform window, represents an area of (0, 0) tiles.
ImageData * bulldozer
Bulldozer sprite.
ImageData * compass [TC_END]
Viewing direction sprites.
ImageData * weather [WTP_COUNT]
Weather sprites.
ImageData * lights_rog [4]
Red/orange/green light.
ImageData * lights_rg [3]
Red/green light.
TextData * text
Texts of the GUI.
Detailed Description
Sprites of the gui.
Todo:
Add widget for rounded_button
Add widget for inset_frame
Add widget for checkbox
Add widget for radio_button
Add widget for hor_slider
Add widget for vert_slider
Add sprites for resize box (currently a button)
Add sprites for close box (currently a button)
Definition at line 411 of file sprite_store.h.
Constructor & Destructor Documentation
GuiSprites::GuiSprites ()
Default constructor.
Definition at line 1161 of file sprite_store.cpp.
References Clear().
Member Function Documentation
void GuiSprites::Clear ()
Clear all GUI sprite data.
Definition at line 1167 of file sprite_store.cpp.
References bank_select, bend_select, bulldozer, button, checkbox, BorderSpriteData::Clear(), CheckableWidgetSpriteData::Clear(), SliderSpriteData::Clear(), ScrollbarSpriteData::Clear(), close_sprite, compass, disabled, dot_sprite, hor_scroll, hor_slider, left_tabbar, lengthof, lights_rg, lights_rog, panel, platform_select, power_select, radio_button, right_tabbar, rot_2d_neg, rot_2d_pos, rot_3d_neg, rot_3d_pos, slope_select, tab_tabbar, tabbar_panel, TBN_COUNT, TC_END, titlebar, TPB_COUNT, triangle_down, triangle_left, triangle_right, triangle_up, vert_scroll, vert_slider, weather, and WTP_COUNT.
Referenced by GuiSprites(), SpriteManager::SpriteManager(), and SpriteManager::~SpriteManager().
bool GuiSprites::LoadGBOR (RcdFileReader * rcd_file, const ImageMap & sprites)
Load sprites of a GUI widget border.
Parameters
rcd_file RCD file being loaded.
sprites Sprites loaded from this file.
Returns
Load was successful.
Definition at line 852 of file sprite_store.cpp.
References BorderSpriteData::border_bottom, BorderSpriteData::border_left, BorderSpriteData::border_right, BorderSpriteData::border_top, button, RcdFileReader::GetUInt16(), RcdFileReader::GetUInt8(), BorderSpriteData::hor_stepsize, left_tabbar, LoadSpriteFromFile(), BorderSpriteData::min_height, BorderSpriteData::min_width, BorderSpriteData::normal, panel, BorderSpriteData::pressed, right_tabbar, RcdFileReader::size, tab_tabbar, tabbar_panel, titlebar, RcdFileReader::version, BorderSpriteData::vert_stepsize, and WBS_COUNT.
Referenced by SpriteManager::Load().
bool GuiSprites::LoadGCHK (RcdFileReader * rcd_file, const ImageMap & sprites)
Load checkbox and radio button GUI sprites.
Parameters
rcd_file RCD file being loaded.
sprites Sprites loaded from this file.
Returns
Load was successful.
Todo:
Load width and height from the RCD file too.
Definition at line 920 of file sprite_store.cpp.
References checkbox, RcdFileReader::GetUInt16(), ImageData::height, CheckableWidgetSpriteData::height, LoadSpriteFromFile(), radio_button, RcdFileReader::size, CheckableWidgetSpriteData::sprites, RcdFileReader::version, WCS_COUNT, ImageData::width, and CheckableWidgetSpriteData::width.
Referenced by SpriteManager::Load().
bool GuiSprites::LoadGSLI (RcdFileReader * rcd_file, const ImageMap & sprites)
Load slider bar sprite data.
Parameters
rcd_file RCD file being loaded.
sprites Sprites loaded from this file.
Returns
Load was successful.
Todo:
Move widget_type further to the top in the RCD file block.
Definition at line 978 of file sprite_store.cpp.
References RcdFileReader::GetUInt16(), RcdFileReader::GetUInt8(), SliderSpriteData::height, hor_slider, LoadSpriteFromFile(), SliderSpriteData::min_bar_length, SliderSpriteData::normal, SliderSpriteData::shaded, RcdFileReader::size, SliderSpriteData::stepsize, RcdFileReader::version, vert_slider, and WSS_COUNT.
Referenced by SpriteManager::Load().
bool GuiSprites::LoadGSCL (RcdFileReader * rcd_file, const ImageMap & sprites)
Load scroll bar sprite data.
Parameters
rcd_file RCD file being loaded.
sprites Sprites loaded from this file.
Returns
Load was successful.
Todo:
Move widget_type further to the top in the RCD file block.
Add width of the scrollbar in the RCD file block.
Definition at line 1045 of file sprite_store.cpp.
References RcdFileReader::GetUInt16(), RcdFileReader::GetUInt8(), ImageData::height, ScrollbarSpriteData::height, hor_scroll, LoadSpriteFromFile(), ScrollbarSpriteData::min_length_all, ScrollbarSpriteData::min_length_slider, ScrollbarSpriteData::normal, ScrollbarSpriteData::shaded, RcdFileReader::size, ScrollbarSpriteData::stepsize_bar, ScrollbarSpriteData::stepsize_slider, RcdFileReader::version, vert_scroll, ImageData::width, and WLS_COUNT.
Referenced by SpriteManager::Load().
bool GuiSprites::LoadGSLP (RcdFileReader * rcd_file, const ImageMap & sprites, const TextMap & texts)
Load GUI slope selection sprites.
Parameters
rcd_file RCD file being loaded.
sprites Sprites loaded from this file.
texts Texts loaded from this file.
Returns
Load was successful.
Definition at line 1102 of file sprite_store.cpp.
References _language, bank_select, bend_select, bulldozer, close_sprite, compass, disabled, dot_sprite, lengthof, lights_rg, lights_rog, LoadSpriteFromFile(), LoadTextFromFile(), platform_select, power_select, Language::RegisterStrings(), rot_2d_neg, rot_2d_pos, rot_3d_neg, rot_3d_pos, RcdFileReader::size, slope_select, STR_GUI_START, TBN_COUNT, TC_END, text, TPB_COUNT, triangle_down, triangle_left, triangle_right, triangle_up, TSL_DOWN, TSL_FLAT, TSL_STEEP_DOWN, TSL_STEEP_UP, TSL_STRAIGHT_DOWN, TSL_STRAIGHT_UP, TSL_UP, RcdFileReader::version, weather, and WTP_COUNT.
Referenced by SpriteManager::Load().
bool GuiSprites::HasSufficientGraphics () const
Have essential GUI sprites been loaded to be used in a display.
This is the minimum number of sprites needed to display an error message.
Returns
Sufficient data has been loaded.
Definition at line 1214 of file sprite_store.cpp.
References button, checkbox, close_sprite, hor_scroll, BorderSpriteData::IsLoaded(), CheckableWidgetSpriteData::IsLoaded(), ScrollbarSpriteData::IsLoaded(), left_tabbar, panel, radio_button, right_tabbar, tab_tabbar, tabbar_panel, titlebar, and vert_scroll.
Referenced by freerct_main().
Member Data Documentation
ImageData* GuiSprites::lights_rog[4]
Red/orange/green light.
See also
LightRedOrangeGreen
Definition at line 459 of file sprite_store.h.
Referenced by Clear(), SpriteManager::GetTableSprite(), and LoadGSLP().
ImageData* GuiSprites::lights_rg[3]
Red/green light.
See also
LightRedGreen
Definition at line 460 of file sprite_store.h.
Referenced by Clear(), SpriteManager::GetTableSprite(), and LoadGSLP().
The documentation for this struct was generated from the following files:
sprite_store.h
sprite_store.cpp