FreeRCT: RowColData Struct Reference
RowColData Struct Reference
Widgets and supporting functions of the program
Data about a row or a column.
#include <widget.h>
Public Member Functions
void InitRowColData ()
Initialize the row/column data.
void Merge (uint16 min_size, uint16 fill, uint16 resize)
Merge a new minimal size, fill step, and resize step into the data.
Public Attributes
uint16 min_size
Minimal size.
uint16 fill
Fill step.
uint16 resize
Resize step.
Detailed Description
Data about a row or a column.
Definition at line 291 of file widget.h.
Member Function Documentation
void RowColData::InitRowColData ()
Initialize the row/column data.
Definition at line 985 of file widget.cpp.
References fill, min_size, and resize.
Referenced by IntermediateWidget::SetupMinimalSize().
void RowColData::Merge (uint16 min_size, uint16 fill, uint16 resize)
Merge a new minimal size, fill step, and resize step into the data.
Parameters
min_size Minimal size to merge.
fill Fill step to merge.
resize Resize step to merge.
Definition at line 998 of file widget.cpp.
References LeastCommonMultiple().
Referenced by IntermediateWidget::SetupMinimalSize().
The documentation for this struct was generated from the following files:
widget.h
widget.cpp