FreeRCT: GuestBatch Struct Reference
GuestBatch Struct Reference
A batch (a group) of guests riding together.
#include <guest_batches.h>
Public Member Functions
bool IsEmpty () const
Return whether the batch is entirely empty.
void Configure (int batch_size)
Configure a batch of guests.
bool AddGuest (int guest, TileEdge entry)
Try to add a guest into the batch.
void Start (int ride_time)
Start the ride (make it BST_RUNNING).
void OnAnimate (int delay)
Update the state of the ride due to passage of time.
Public Attributes
std::vector< GuestData > guests
Guests in the batch.
BatchState state
State of the batch.
int remaining
Amount of time until the end of the ride (in milli-seconds).
int gate
Gate used by the guests to enter the ride (or for any other purpose as the ride sees fit).
Detailed Description
A batch (a group) of guests riding together.
Definition at line 54 of file guest_batches.h.
Member Function Documentation
bool GuestBatch::IsEmpty () const
Return whether the batch is entirely empty.
Returns
Whether the batch is entirely empty.
Definition at line 45 of file guest_batches.cpp.
References guests.
Referenced by Configure().
void GuestBatch::Configure (int batch_size)
Configure a batch of guests.
Parameters
batch_size Number of guests in a batch.
Definition at line 55 of file guest_batches.cpp.
References BST_EMPTY, gate, guests, IsEmpty(), remaining, and state.
bool GuestBatch::AddGuest (int guest, TileEdge entry)
Try to add a guest into the batch.
Parameters
guest Guest number.
entry Entry direction of the guest into the ride.
Returns
Whether the guest could be added.
Definition at line 73 of file guest_batches.cpp.
References guests.
Referenced by ShopInstance::EnterRide().
void GuestBatch::Start (int ride_time)
Start the ride (make it BST_RUNNING).
Parameters
ride_time Length of the ride in milli-seconds.
Definition at line 88 of file guest_batches.cpp.
References BST_RUNNING, remaining, and state.
Referenced by ShopInstance::EnterRide().
void GuestBatch::OnAnimate (int delay)
Update the state of the ride due to passage of time.
Parameters
delay Amount of time that has passed (milli-seconds).
Definition at line 98 of file guest_batches.cpp.
References BST_FINISHED, BST_RUNNING, remaining, and state.
Member Data Documentation
int GuestBatch::remaining
Amount of time until the end of the ride (in milli-seconds).
Positive means time is running, 0 means the batch has reached the end.
Definition at line 57 of file guest_batches.h.
Referenced by Configure(), OnAnimate(), and Start().
The documentation for this struct was generated from the following files:
guest_batches.h
guest_batches.cpp