FreeRCT: GuestData Struct Reference
GuestData Struct Reference
Data of a guest in a ride.
#include <guest_batches.h>
Public Member Functions
bool IsEmpty () const
Is the entry in use?
void Clear ()
Clear the guest information, making the entry free for next use.
void Set (int guest, TileEdge entry)
Store the guest information into the entry.
Public Attributes
int guest
Number of the guest.
TileEdge entry
Direction of entry of the guest at the ride, INVALID_EDGE for a non-used entry.
Detailed Description
Data of a guest in a ride.
Definition at line 24 of file guest_batches.h.
Member Function Documentation
bool GuestData::IsEmpty () const inline
Is the entry in use?
Returns
Whether the entry is currently empty.
Definition at line 34 of file guest_batches.h.
References INVALID_EDGE.
Referenced by ShopInstance::OnAnimate(), ShopInstance::RemoveAllPeople(), and Set().
void GuestData::Clear ()
Clear the guest information, making the entry free for next use.
Definition at line 21 of file guest_batches.cpp.
References entry, guest, and INVALID_EDGE.
Referenced by ShopInstance::OnAnimate(), and ShopInstance::RemoveAllPeople().
void GuestData::Set (int guest, TileEdge entry)
Store the guest information into the entry.
Parameters
guest Guest number.
entry Entry direction of the guest into the ride.
Definition at line 32 of file guest_batches.cpp.
References entry, guest, INVALID_EDGE, and IsEmpty().
The documentation for this struct was generated from the following files:
guest_batches.h
guest_batches.cpp