FreeRCT: terraform.cpp File Reference
terraform.cpp File Reference
Terraforming code.
#include "stdafx.h"
#include "map.h"
#include "viewport.h"
#include "terraform.h"
#include "gamemode.h"
#include "math_func.h"
#include "memory.h"
Classes
struct VoxelCorner
Structure describing a corner at a voxel stack.
struct CornerNeighbours
Description of neighbouring corners of a corner at a ground tile.
Functions
static void SetUpperBoundary (const Voxel *v, uint8 height, uint8 *bounds)
Set an upper boundary of the height of each tile corner based on the contents of a voxel.
static void SetFoundations (VoxelStack *stack, uint8 my_first, uint8 my_second, uint8 other_first, uint8 other_second, uint8 first_bit, uint8 second_bit)
Set foundations in a stack.
static void SetXFoundations (int xpos, int ypos)
Update the foundations in two _additions voxel stacks along the SW edge of the first stack and the NE edge of the second stack.
static void SetYFoundations (int xpos, int ypos)
Update the foundations in two _additions voxel stacks along the SE edge of the first stack and the NW edge of the second stack.
static void ChangeTileCursorMode (Viewport *vp, bool levelling, int direction, bool dot_mode)
Change the terrain while in 'dot' mode (i.e.
static void ChangeAreaCursorMode (Viewport *vp, bool levelling, int direction)
Change the terrain while in 'area' mode (i.e.
Variables
TileTerraformMouseMode _terraformer
Terraform coordination object.
static const CornerNeighbours neighbours [4]
Neighbouring corners of each corner.
Detailed Description
Terraforming code.
Definition in file terraform.cpp.
Function Documentation
static void SetUpperBoundary (const Voxel * v, uint8 height, uint8 * bounds) static
Set an upper boundary of the height of each tile corner based on the contents of a voxel.
Parameters
v Voxel to examine.
height Height of the voxel.
bounds [inout] Updated constraints.
Note
Length of the bounds array should be 4.
Definition at line 253 of file terraform.cpp.
References Voxel::GetGroundType(), GetImplodedPathSlope(), Voxel::GetInstance(), GTP_INVALID, HasValidPath(), Voxel::IsEmpty(), PATH_FLAT_COUNT, PATH_RAMP_NE, PATH_RAMP_NW, PATH_RAMP_SE, PATH_RAMP_SW, SRI_FULL_RIDES, SRI_RIDES_START, TC_EAST, TC_NORTH, TC_SOUTH, and TC_WEST.
Referenced by TerrainChanges::ModifyWorld().
static void SetFoundations (VoxelStack * stack, uint8 my_first, uint8 my_second, uint8 other_first, uint8 other_second, uint8 first_bit, uint8 second_bit) static
Set foundations in a stack.
Parameters
stack Voxel stack to change (may be nullptr).
my_first Height of my first corner.
my_second Height of my second corner.
other_first Height of corner opposite to my_first.
other_second Height of corner opposite to my_second.
first_bit Bit value to use for a raised foundation at the first corner.
second_bit Bit value to use for a raised foundation at the second corner.
Definition at line 307 of file terraform.cpp.
References VoxelStack::base, FDT_GROUND, FDT_INVALID, VoxelStack::GetCreate(), Voxel::GetFoundationSlope(), Voxel::GetFoundationType(), VoxelStack::height, Voxel::SetFoundationSlope(), and Voxel::SetFoundationType().
Referenced by SetXFoundations(), and SetYFoundations().
static void SetXFoundations (int xpos, int ypos) static
Update the foundations in two _additions voxel stacks along the SW edge of the first stack and the NE edge of the second stack.
Parameters
xpos X position of the first voxel stack.
ypos Y position of the first voxel stack.
Note
The first or the second voxel stack may be off-world.
Definition at line 353 of file terraform.cpp.
References _additions, _world, VoxelStack::base, ComputeCornerHeight(), ExpandTileSlope(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), WorldAdditions::GetModifyStack(), VoxelWorld::GetXSize(), GTP_INVALID, VoxelStack::height, SetFoundations(), TC_EAST, TC_NORTH, TC_SOUTH, TC_WEST, and VoxelStack::voxels.
Referenced by TerrainChanges::ModifyWorld().
static void SetYFoundations (int xpos, int ypos) static
Update the foundations in two _additions voxel stacks along the SE edge of the first stack and the NW edge of the second stack.
Parameters
xpos X position of the first voxel stack.
ypos Y position of the first voxel stack.
Note
The first or the second voxel stack may be off-world.
Definition at line 398 of file terraform.cpp.
References _additions, _world, VoxelStack::base, ComputeCornerHeight(), ExpandTileSlope(), Voxel::GetGroundSlope(), Voxel::GetGroundType(), WorldAdditions::GetModifyStack(), VoxelWorld::GetYSize(), GTP_INVALID, VoxelStack::height, SetFoundations(), TC_EAST, TC_NORTH, TC_SOUTH, TC_WEST, and VoxelStack::voxels.
Referenced by TerrainChanges::ModifyWorld().
static void ChangeTileCursorMode (Viewport * vp, bool levelling, int direction, bool dot_mode) static
Change the terrain while in 'dot' mode (i.e.
a single corner or a single tile changing the entire world).
Parameters
vp Viewport displaying the world.
levelling If true, use levelling mode (only change the lowest/highest corners of a tile), else move every corner.
direction Direction of change.
dot_mode Using dot-mode (infinite world changes).
Definition at line 690 of file terraform.cpp.
References _additions, _game_mode_mgr, _world, TerrainChanges::ChangeCorner(), TerrainChanges::changes, TerrainChanges::ChangeVoxel(), WorldAdditions::Clear(), CUR_TYPE_EAST, CUR_TYPE_NORTH, CUR_TYPE_SOUTH, CUR_TYPE_TILE, CUR_TYPE_WEST, VoxelWorld::GetGroundHeight(), VoxelWorld::GetTileOwner(), VoxelWorld::GetXSize(), VoxelWorld::GetYSize(), GameModeManager::InPlayMode(), Viewport::MarkVoxelDirty(), TerrainChanges::ModifyWorld(), NOT_REACHED, OWN_PARK, Viewport::tile_cursor, BaseCursor::type, TerrainChanges::UpdatelevellingHeight(), WORLD_Z_SIZE, Point< CT >::x, Cursor::xpos, Point< CT >::y, Cursor::ypos, and Cursor::zpos.
Referenced by TileTerraformMouseMode::OnMouseMoveEvent(), and TileTerraformMouseMode::OnMouseWheelEvent().
static void ChangeAreaCursorMode (Viewport * vp, bool levelling, int direction) static
Change the terrain while in 'area' mode (i.e.
a rectangle of tiles that changes).
Parameters
vp Viewport displaying the world.
levelling If true, use levelling mode (only change the lowest/highest corners of a tile), else move every corner.
direction Direction of change.
Definition at line 754 of file terraform.cpp.
References _additions, _game_mode_mgr, _world, Viewport::area_cursor, Rectangle< PT, SZ >::base, TerrainChanges::changes, TerrainChanges::ChangeVoxel(), WorldAdditions::Clear(), VoxelWorld::GetTileOwner(), Rectangle< PT, SZ >::height, GameModeManager::InEditorMode(), Viewport::MarkVoxelDirty(), TerrainChanges::ModifyWorld(), OWN_PARK, MultiCursor::rect, MultiCursor::ResetZPosition(), TerrainChanges::UpdatelevellingHeight(), Rectangle< PT, SZ >::width, WORLD_Z_SIZE, Point< CT >::x, and Point< CT >::y.
Referenced by TileTerraformMouseMode::OnMouseMoveEvent(), and TileTerraformMouseMode::OnMouseWheelEvent().