FreeRCT: tile_func.cpp File Reference
tile_func.cpp File Reference
Tile functions.
#include "stdafx.h"
#include "tile.h"
Functions
void ComputeCornerHeight (TileSlope slope, uint8 base_height, uint8 *output)
Compute the height of the corners of an expanded ground tile.
void ComputeSlopeAndHeight (uint8 *corners, TileSlope *slope, uint8 *base)
Compute a tile slope and a base height from the height of the four corners.
bool MayHaveGroundFenceInVoxelAbove (TileSlope slope)
For some ground slopes, the fence type is stored in the voxel above.
bool StoreFenceInUpperVoxel (TileSlope slope, TileEdge edge)
For some ground slopes, the fence type is stored in the voxel above.
TileEdge GetAdjacentEdge (int x1, int y1, int x2, int y2)
Find the outgoing edge of tile x1, y1) to arrive at adjacent tile (x2, y2).
Variables
const uint8 _corners_at_edge [EDGE_COUNT]
Tile corners adjacent to an edge.
const Point16 _corner_dxy [4]
Corner dx/dy (relative to northern corner) of a corner of a tile.
const Point16 _tile_dxy [EDGE_COUNT]
Tile dx/dy of the tile connected to the given edge.
Detailed Description
Tile functions.
Definition in file tile_func.cpp.
Function Documentation
void ComputeCornerHeight (TileSlope slope, uint8 base_height, uint8 * output)
Compute the height of the corners of an expanded ground tile.
Parameters
slope Expanded slope.
base_height Height of the voxel containing the ground.
output [out] Height of the four corners of the slope.
Definition at line 45 of file tile_func.cpp.
References TC_END, TC_NORTH, TSB_STEEP, and TSB_TOP.
Referenced by SpriteCollector::CollectVoxel(), SpriteStorage::GetFenceSprite(), TerrainChanges::ModifyWorld(), SetXFoundations(), and SetYFoundations().
void ComputeSlopeAndHeight (uint8 * corners, TileSlope * slope, uint8 * base)
Compute a tile slope and a base height from the height of the four corners.
Parameters
corners [in] Array with the corner heights.
slope [out] Computed slope. For steep slopes, the base value is given.
base [out] Base height of the slope.
Definition at line 73 of file tile_func.cpp.
References ImplodeTileSlope(), SL_FLAT, TC_EAST, TC_NORTH, TC_SOUTH, TC_WEST, TSB_EAST, TSB_NORTH, TSB_SOUTH, TSB_STEEP, and TSB_WEST.
Referenced by TerrainChanges::ModifyWorld().
bool MayHaveGroundFenceInVoxelAbove (TileSlope slope)
For some ground slopes, the fence type is stored in the voxel above.
Check if this is the case for a voxel with the given exploded slope.
Parameters
slope Exploded slope
Returns
true if one or more edges of a voxel with given slope will have the fence stored in the voxel above.
Definition at line 105 of file tile_func.cpp.
References TSB_STEEP.
Referenced by TerrainChanges::ModifyWorld().
bool StoreFenceInUpperVoxel (TileSlope slope, TileEdge edge)
For some ground slopes, the fence type is stored in the voxel above.
Check if this is the case for given edge of a voxel with the given slope.
Parameters
slope Exploded slope.
edge Edge to inspect.
Returns
true if one or more edges of a voxel with given slope will have the fence stored in the voxel above.
Definition at line 122 of file tile_func.cpp.
References TSB_STEEP.
Referenced by TerrainChanges::ModifyWorld(), and UpdateLandBorderFence().
TileEdge GetAdjacentEdge (int x1, int y1, int x2, int y2)
Find the outgoing edge of tile x1, y1) to arrive at adjacent tile (x2, y2).
Parameters
x1 X coordinate first tile.
y1 Y coordinate first tile.
x2 X coordinate second tile.
y2 Y coordinate second tile.
Returns
Outgoing edge of the first tile to reach the second tile, or INVALID_EDGE if no valid edge could be found.
Definition at line 137 of file tile_func.cpp.
References EDGE_BEGIN, EDGE_COUNT, and INVALID_EDGE.
Referenced by GetParkEntryDirection().
Variable Documentation
const uint8 _corners_at_edge[EDGE_COUNT]
Initial value:
= {
        TSB_NORTHEAST,
        TSB_SOUTHEAST,
        TSB_SOUTHWEST,
        TSB_NORTHWEST,
}
Tile corners adjacent to an edge.
Definition at line 16 of file tile_func.cpp.
Referenced by BuildDownwardPath(), BuildUpwardPath(), GetPathAttachPoints(), and PathBuildManager::SelectMovement().
const Point16 _corner_dxy[4]
Initial value:
= {
        {0, 0},
        {0, 1},
        {1, 1},
        {1, 0},
}
Corner dx/dy (relative to northern corner) of a corner of a tile.
Definition at line 24 of file tile_func.cpp.
Referenced by Viewport::MarkVoxelDirty().
const Point16 _tile_dxy[EDGE_COUNT]
Initial value:
= {
        {-1,  0},
        { 0,  1},
        { 1,  0},
        { 0, -1},
}
Tile dx/dy of the tile connected to the given edge.
Definition at line 32 of file tile_func.cpp.
Referenced by AddRemovePathEdges(), CanBuildPathFromEdge(), PathBuildManager::ComputeArrowCursorPosition(), Guest::ComputeExitDesire(), PathBuildManager::ComputeNewLongPath(), Guest::DecideMoveDirection(), GetPathAttachPoints(), PathBuildManager::MoveCursor(), PathExistsAtBottomEdge(), RideExistsAtBottom(), PathSearcher::Search(), TravelQueuePath(), and UpdateLandBorderFence().