FreeRCT: tile.h File Reference
tile.h File Reference
Tile definition.
#include "enum_type.h"
#include "geometry.h"
Enumerations
enum TileCorner {
TC_NORTH = 0, TC_EAST, TC_SOUTH, TC_WEST,
TC_END, TCB_NORTH = 1 << TC_NORTH, TCB_EAST = 1 << TC_EAST, TCB_SOUTH = 1 << TC_SOUTH,
TCB_WEST = 1 << TC_WEST
}
Corners of a tile.
enum TileSlope {
SL_FLAT = 0, TS_NORTH = TC_NORTH, TS_EAST = TC_EAST, TS_SOUTH = TC_SOUTH,
TS_WEST = TC_WEST, TS_STEEP = TC_END, TS_TOP = TC_END + 1, TSB_NORTH = 1 << TS_NORTH,
TSB_EAST = 1 << TS_EAST, TSB_SOUTH = 1 << TS_SOUTH, TSB_WEST = 1 << TS_WEST, TSB_STEEP = 1 << TS_STEEP,
TSB_TOP = 1 << TS_TOP, TSB_NORTHEAST = TSB_NORTH | TSB_EAST, TSB_NORTHWEST = TSB_NORTH | TSB_WEST, TSB_SOUTHEAST = TSB_SOUTH | TSB_EAST,
TSB_SOUTHWEST = TSB_SOUTH | TSB_WEST
}
Slope description of a surface tile.
enum SupportSprites {
SPP_S_NS, SPP_S_EW, SPP_D_NS, SPP_D_EW,
SPP_P_NS, SPP_P_EW, SPP_N, SPP_E,
SPP_NE, SPP_S, SPP_NS, SPP_ES,
SPP_NES, SPP_W, SPP_NW, SPP_EW,
SPP_NEW, SPP_SW, SPP_NSW, SPP_ESW,
SPP_STEEP_N, SPP_STEEP_E, SPP_STEEP_S, SPP_STEEP_W,
SPP_COUNT, SSP_FLAT_SINGLE_NS, SSP_FLAT_SINGLE_EW, SSP_FLAT_DOUBLE_NS,
SSP_FLAT_DOUBLE_EW, SSP_FLAT_PATH_NS, SSP_FLAT_PATH_EW, SSP_N,
SSP_E, SSP_NE, SSP_S, SSP_NS,
SSP_ES, SSP_NES, SSP_W, SSP_NW,
SSP_EW, SSP_NEW, SSP_SW, SSP_NSW,
SSP_ESW, SSP_STEEP_N, SSP_STEEP_E, SSP_STEEP_S,
SSP_STEEP_W, SSP_COUNT, SSP_NONFLAT_BASE = SSP_FLAT_PATH_EW
}
Sprites for supports available for use.
enum TileEdge {
EDGE_BEGIN, EDGE_NE = EDGE_BEGIN, EDGE_SE, EDGE_SW,
EDGE_NW, EDGE_COUNT, EDGE_ALL = 0xF, INVALID_EDGE = 0xFF
}
Edges of a tile, starts at NE direction, and rotates clockwise.
enum GroundType {
GTP_GRASS0, GTP_GRASS1, GTP_GRASS2, GTP_GRASS3,
GTP_UNDERGROUND, GTP_DESERT, GTP_CURSOR_TEST, GTP_CURSOR_EDGE_TEST,
GTP_COUNT, GTP_INVALID = 0xF
}
Available ground types.
enum FoundationType {
FDT_GROUND, FDT_WOOD, FDT_BRICK, FDT_COUNT,
FDT_INVALID = 0xF
}
Types of foundations.
enum TrackSlope {
TSL_BEGIN, TSL_DOWN = TSL_BEGIN, TSL_FLAT, TSL_UP,
TSL_COUNT_GENTLE, TSL_STEEP_DOWN = TSL_COUNT_GENTLE, TSL_STEEP_UP, TSL_COUNT_STEEP,
TSL_STRAIGHT_DOWN = TSL_COUNT_STEEP, TSL_STRAIGHT_UP, TSL_COUNT_VERTICAL, TSL_INVALID = 0xFF
}
Path and track slopes.
Functions
static bool IsImplodedSteepSlope (uint8 ts)
Does the imploded tile slope represent a steep slope?
static bool IsImplodedSteepSlopeTop (uint8 ts)
Does the imploded tile slope represent the top of a steep slope?
static TileSlope ExpandTileSlope (uint8 v)
Expand a slope sprite number to its bit-encoded form for easier manipulating.
static uint8 ImplodeTileSlope (TileSlope s)
Implode an expanded slope back to its sprite number.
void ComputeCornerHeight (TileSlope slope, uint8 base_height, uint8 *output)
Compute the height of the corners of an expanded ground tile.
void ComputeSlopeAndHeight (uint8 *corners, TileSlope *slope, uint8 *base)
Compute a tile slope and a base height from the height of the four corners.
bool MayHaveGroundFenceInVoxelAbove (TileSlope slope)
For some ground slopes, the fence type is stored in the voxel above.
bool StoreFenceInUpperVoxel (TileSlope slope, TileEdge edge)
For some ground slopes, the fence type is stored in the voxel above.
TileEdge GetAdjacentEdge (int x1, int y1, int x2, int y2)
Find the outgoing edge of tile x1, y1) to arrive at adjacent tile (x2, y2).
Variables
static const uint8 NUM_SLOPE_SPRITES = 15 + 4 + 4
Number of sprites for defining a surface tile.
const uint8 _corners_at_edge [EDGE_COUNT]
Tile corners adjacent to an edge.
const Point16 _corner_dxy [4]
Corner dx/dy (relative to northern corner) of a corner of a tile.
const Point16 _tile_dxy [EDGE_COUNT]
Tile dx/dy of the tile connected to the given edge.
const Point16 _exit_dxy [EDGE_COUNT]
Pixel position for a guest exiting a ride exit, relative to the base position of the exit voxel of the ride.
Detailed Description
Tile definition.
A tile is defined as follows
*      N     North corner is at the top,
*     / \    west corner at the left, and east
*    /   \   corner at the right. South corner
*   W     E  is at the bottom of the tile.
*    \   /
*     \ /
*      S
*
Definition in file tile.h.
Enumeration Type Documentation
enum TileCorner
Corners of a tile.
Enumerator
TC_NORTH
North corner.
TC_EAST
East corner.
TC_SOUTH
South corner.
TC_WEST
West corner.
TC_END
End of all corners.
TCB_NORTH
Bit denoting north corner.
TCB_EAST
Bit denoting east corner.
TCB_SOUTH
Bit denoting south corner.
TCB_WEST
Bit denoting west corner.
Definition at line 32 of file tile.h.
enum SupportSprites
Sprites for supports available for use.
Enumerator
SPP_S_NS
Single height for flat terrain, north and south view.
SPP_S_EW
Single height for flat terrain, east and west view.
SPP_D_NS
Double height for flat terrain, north and south view.Double height for flat terrain, east and west view.
SPP_D_EW
Double height for flat terrain, east and west view.
SPP_P_NS
Double height for paths, north and south view.
SPP_P_EW
Double height for paths, east and west view.
SPP_N
Single height, north leg up.
SPP_E
Single height, east leg up.
SPP_NE
Single height, north, east legs up.
SPP_S
Single height, south leg up.
SPP_NS
Single height, north, south legs up.
SPP_ES
Single height, east, south legs up.
SPP_NES
Single height, north, east, south legs up.
SPP_W
Single height, west leg up.
SPP_NW
Single height, west, north legs up.
SPP_EW
Single height, west, east legs up.
SPP_NEW
Single height, west, north, east legs up.
SPP_SW
Single height, west, south legs up.
SPP_NSW
Single height, west, north, south legs up.
SPP_ESW
Single height, west, east, south legs up.
SPP_STEEP_N
Double height for steep north slope.
SPP_STEEP_E
Double height for steep east slope.
SPP_STEEP_S
Double height for steep south slope.
SPP_STEEP_W
Double height for steep west slope.
SPP_COUNT
Number of support sprites.
SSP_FLAT_SINGLE_NS
Single height for flat terrain, north and south view.
SSP_FLAT_SINGLE_EW
Single height for flat terrain, east and west view.
SSP_FLAT_DOUBLE_NS
Double height for flat terrain, north and south view.
SSP_FLAT_DOUBLE_EW
Double height for flat terrain, east and west view.
SSP_FLAT_PATH_NS
Double height for paths, north and south view.
SSP_FLAT_PATH_EW
Double height for paths, east and west view.
SSP_N
Single height, north leg up.
SSP_E
Single height, east leg up.
SSP_NE
Single height, north, east legs up.
SSP_S
Single height, south leg up.
SSP_NS
Single height, north, south legs up.
SSP_ES
Single height, east, south legs up.
SSP_NES
Single height, north, east, south legs up.
SSP_W
Single height, west leg up.
SSP_NW
Single height, west, north legs up.
SSP_EW
Single height, west, east legs up.
SSP_NEW
Single height, west, north, east legs up.
SSP_SW
Single height, west, south legs up.
SSP_NSW
Single height, west, north, south legs up.
SSP_ESW
Single height, west, east, south legs up.
SSP_STEEP_N
Double height for steep north slope.
SSP_STEEP_E
Double height for steep east slope.
SSP_STEEP_S
Double height for steep south slope.
SSP_STEEP_W
Double height for steep west slope.
SSP_COUNT
Number of support sprites.
SSP_NONFLAT_BASE
Base sprite for non-flat ground slopes.
Definition at line 83 of file tile.h.
Function Documentation
static bool IsImplodedSteepSlope (uint8 ts) inline static
Does the imploded tile slope represent a steep slope?
Parameters
ts Imploded tile slope to examine.
Returns
true if the given slope is a steep slope, false otherwise.
Definition at line 137 of file tile.h.
Referenced by Viewport::MarkVoxelDirty(), and PathBuildManager::MoveCursor().
static bool IsImplodedSteepSlopeTop (uint8 ts) inline static
Does the imploded tile slope represent the top of a steep slope?
Parameters
ts Imploded tile slope to examine.
Returns
true if the given slope is the top of a steep slope, false otherwise.
Definition at line 147 of file tile.h.
Referenced by VoxelStack::GetGroundOffset().
void ComputeCornerHeight (TileSlope slope, uint8 base_height, uint8 * output)
Compute the height of the corners of an expanded ground tile.
Parameters
slope Expanded slope.
base_height Height of the voxel containing the ground.
output [out] Height of the four corners of the slope.
Definition at line 53 of file tile_func.cpp.
References TC_END, TC_NORTH, TSB_STEEP, and TSB_TOP.
Referenced by SpriteCollector::CollectVoxel(), SpriteStorage::GetFenceSprite(), TerrainChanges::ModifyWorld(), SetXFoundations(), and SetYFoundations().
void ComputeSlopeAndHeight (uint8 * corners, TileSlope * slope, uint8 * base)
Compute a tile slope and a base height from the height of the four corners.
Parameters
corners [in] Array with the corner heights.
slope [out] Computed slope. For steep slopes, the base value is given.
base [out] Base height of the slope.
Definition at line 81 of file tile_func.cpp.
References ImplodeTileSlope(), SL_FLAT, TC_EAST, TC_NORTH, TC_SOUTH, TC_WEST, TSB_EAST, TSB_NORTH, TSB_SOUTH, TSB_STEEP, and TSB_WEST.
Referenced by TerrainChanges::ModifyWorld().
bool MayHaveGroundFenceInVoxelAbove (TileSlope slope)
For some ground slopes, the fence type is stored in the voxel above.
Check if this is the case for a voxel with the given exploded slope.
Parameters
slope Exploded slope
Returns
true if one or more edges of a voxel with given slope will have the fence stored in the voxel above.
Definition at line 113 of file tile_func.cpp.
References TSB_STEEP.
Referenced by TerrainChanges::ModifyWorld().
bool StoreFenceInUpperVoxel (TileSlope slope, TileEdge edge)
For some ground slopes, the fence type is stored in the voxel above.
Check if this is the case for given edge of a voxel with the given slope.
Parameters
slope Exploded slope.
edge Edge to inspect.
Returns
true if one or more edges of a voxel with given slope will have the fence stored in the voxel above.
Definition at line 130 of file tile_func.cpp.
References TSB_STEEP.
Referenced by TerrainChanges::ModifyWorld(), and UpdateLandBorderFence().
TileEdge GetAdjacentEdge (int x1, int y1, int x2, int y2)
Find the outgoing edge of tile x1, y1) to arrive at adjacent tile (x2, y2).
Parameters
x1 X coordinate first tile.
y1 Y coordinate first tile.
x2 X coordinate second tile.
y2 Y coordinate second tile.
Returns
Outgoing edge of the first tile to reach the second tile, or INVALID_EDGE if no valid edge could be found.
Definition at line 145 of file tile_func.cpp.
References EDGE_BEGIN, EDGE_COUNT, and INVALID_EDGE.
Referenced by GetGoHomeDirection(), and GetParkEntryDirection().
Variable Documentation
const uint8 _corners_at_edge[EDGE_COUNT]
Tile corners adjacent to an edge.
Definition at line 16 of file tile_func.cpp.
Referenced by BuildDownwardPath(), BuildUpwardPath(), GetPathAttachPoints(), and PathBuildManager::SelectMovement().
const Point16 _corner_dxy[4]
Corner dx/dy (relative to northern corner) of a corner of a tile.
Definition at line 24 of file tile_func.cpp.
Referenced by Viewport::MarkVoxelDirty().
const Point16 _tile_dxy[EDGE_COUNT]
Tile dx/dy of the tile connected to the given edge.
Definition at line 32 of file tile_func.cpp.
Referenced by AddRemovePathEdges(), CanBuildPathFromEdge(), PathBuildManager::ComputeArrowCursorPosition(), Guest::ComputeExitDesire(), PathBuildManager::ComputeNewLongPath(), Person::GetInparkDirections(), GetPathAttachPoints(), PathBuildManager::MoveCursor(), PathExistsAtBottomEdge(), RideExistsAtBottom(), PathSearcher::Search(), TravelQueuePath(), and UpdateLandBorderFence().
const Point16 _exit_dxy[EDGE_COUNT]
Pixel position for a guest exiting a ride exit, relative to the base position of the exit voxel of the ride.
Definition at line 40 of file tile_func.cpp.
Referenced by ShopInstance::GetExit().