FreeRCT: toolbar_gui.cpp File Reference
toolbar_gui.cpp File Reference
Main toolbar window code.
#include "stdafx.h"
#include "freerct.h"
#include "window.h"
#include "video.h"
#include "language.h"
#include "finances.h"
#include "dates.h"
#include "math_func.h"
#include "sprite_store.h"
#include "gui_sprites.h"
#include "viewport.h"
#include "gamemode.h"
#include "weather.h"
Classes
class ToolbarWindow
Top toolbar.
class BottomToolbarWindow
Bottom toolbar.
class QuitProgramWindow
Window to ask confirmation for ending the program.
Enumerations
enum ToolbarGuiWidgets {
TB_GUI_QUIT, TB_GUI_SETTINGS, TB_GUI_GAME_MODE, TB_GUI_PATHS,
TB_GUI_SAVE, TB_GUI_LOAD, TB_GUI_RIDE_SELECT, TB_GUI_FENCE,
TB_GUI_TERRAFORM, TB_GUI_FINANCES
}
Widget numbers of the toolbar GUI.
enum BottomToolbarGuiWidgets {
BTB_STATUS, BTB_WEATHER, BTB_TEMPERATURE, BTB_SPACING,
BTB_VIEW_DIRECTION, BTB_DATE
}
Widget numbers of the bottom toolbar GUI.
enum QuitProgramWidgets { QP_MESSAGE, QP_YES, QP_NO }
Widget numbers of the quit-program window.
Functions
void ShowQuitProgram ()
Ask the user whether the program should be stopped.
StringID GetSwitchGameModeString ()
Determines the string ID of the string to display for the switch game mode button.
void ShowToolbar ()
Open the main toolbar window.
void ShowBottomToolbar ()
Open the bottom toolbar window.
Variables
static const WidgetPart _toolbar_widgets []
Widget parts of the toolbar GUI.
static const uint32 BOTTOM_BAR_HEIGHT = 35
Minimum Y-coord size of the bottom toolbar (BTB) panel.
static const uint32 BOTTOM_BAR_POSITION_X = 75
Separation of the toolbar from the edge of the window.
static const WidgetPart _bottom_toolbar_widgets []
Widget parts of the bottom toolbar GUI.
static const WidgetPart _quit_program_widgets []
Window definition of the quit program GUI.
Detailed Description
Main toolbar window code.
Definition in file toolbar_gui.cpp.
Function Documentation
void ShowQuitProgram ()
Ask the user whether the program should be stopped.
Definition at line 454 of file toolbar_gui.cpp.
References _window_manager, ALL_WINDOWS_OF_TYPE, WindowManager::DeleteWindow(), GetWindowByType(), and WC_QUIT.
Referenced by ToolbarWindow::OnClick().
StringID GetSwitchGameModeString ()
Determines the string ID of the string to display for the switch game mode button.
Returns
String id of the string to display.
Definition at line 95 of file toolbar_gui.cpp.
References _game_mode_mgr, GameModeManager::GetGameMode(), GM_EDITOR, GM_NONE, GM_PLAY, NOT_REACHED, and STR_NULL.
Referenced by ToolbarWindow::SetWidgetStringParameters().
Variable Documentation
const WidgetPart _quit_program_widgets[] static
Initial value:
= {
        Intermediate(0, 1),
                Intermediate(1, 0),
                        Widget(WT_TITLEBAR, INVALID_WIDGET_INDEX, COL_RANGE_RED), SetData(GUI_QUIT_CAPTION, GUI_TITLEBAR_TIP),
                        Widget(WT_CLOSEBOX, INVALID_WIDGET_INDEX, COL_RANGE_RED),
                EndContainer(),
                Widget(WT_PANEL, INVALID_WIDGET_INDEX, COL_RANGE_RED),
                        Intermediate(2,0),
                                Widget(WT_CENTERED_TEXT, QP_MESSAGE, COL_RANGE_RED),
                                                SetData(GUI_QUIT_MESSAGE, STR_NULL), SetPadding(5, 5, 5, 5),
                        EndContainer(),
                        Intermediate(1, 5), SetPadding(0, 0, 3, 0),
                                Widget(WT_EMPTY, INVALID_WIDGET_INDEX, COL_RANGE_INVALID), SetFill(1, 0),
                                Widget(WT_TEXT_PUSHBUTTON, QP_NO, COL_RANGE_YELLOW), SetData(GUI_QUIT_NO, STR_NULL),
                                Widget(WT_EMPTY, INVALID_WIDGET_INDEX, COL_RANGE_INVALID), SetFill(1, 0),
                                Widget(WT_TEXT_PUSHBUTTON, QP_YES, COL_RANGE_YELLOW), SetData(GUI_QUIT_YES, STR_NULL),
                                Widget(WT_EMPTY, INVALID_WIDGET_INDEX, COL_RANGE_INVALID), SetFill(1, 0),
                        EndContainer(),
}
Window definition of the quit program GUI.
Definition at line 413 of file toolbar_gui.cpp.