FreeRCT: track_piece.cpp File Reference
track_piece.cpp File Reference
Functions of the track pieces.
#include "stdafx.h"
#include "sprite_store.h"
#include "fileio.h"
#include "track_piece.h"
#include "map.h"
Macros
#define ENSURE_LENGTH(x) do { if (*length < (x)) { *curve = nullptr; return false; } *length -= (x); } while(false)
Make sure the RCD file being loaded has at least x bytes of data left.
Functions
static CubicBezier LoadBezier (RcdFileReader *rcdfile)
Load the data of a Bezier spline into a BezierTrackCurve.
static bool LoadTrackCurve (RcdFileReader *rcdfile, TrackCurve **curve, uint32 *length)
Load a track curve.
Detailed Description
Functions of the track pieces.
Definition in file track_piece.cpp.
Macro Definition Documentation
ENSURE_LENGTH (x) do { if (*length < (x)) { *curve = nullptr; return false; } *length -= (x); } while(false)
Make sure the RCD file being loaded has at least x bytes of data left.
Parameters
x Minimal number of bytes required.
Referenced by LoadTrackCurve().
Function Documentation
static CubicBezier LoadBezier (RcdFileReader * rcdfile) static
Load the data of a Bezier spline into a BezierTrackCurve.
Parameters
rcdfile Data file to load from. Caller must ensure there is enough data available at the stream.
Returns
The Loaded Bezier spline.
Definition at line 97 of file track_piece.cpp.
References RcdFileReader::GetInt16(), and RcdFileReader::GetUInt32().
Referenced by LoadTrackCurve().
static bool LoadTrackCurve (RcdFileReader * rcdfile, TrackCurve ** curve, uint32 * length) static
Load a track curve.
Parameters
rcdfile Data file being loaded.
curve [out] The loaded track curve, may be nullptr (which indicates a not supplied track curve).
length [inout] Length of the block that is not loaded yet.
Returns
Reading was a success (might have failed due to not enough data).
Definition at line 121 of file track_piece.cpp.
References BezierTrackCurve::curve, ENSURE_LENGTH, RcdFileReader::GetInt16(), RcdFileReader::GetUInt8(), and LoadBezier().
Referenced by TrackPiece::Load().