FreeRCT: utils.cpp File Reference
utils.cpp File Reference
Support code for rcdgen.
#include "../stdafx.h"
#include <cassert>
#include "ast.h"
#include "utils.h"
Functions
static HorVert AddHor (HorVert hv)
Add 'horizontal seen' to the set of seen parameters.
static HorVert AddVert (HorVert hv)
Add 'vertical seen' to the set of seen parameters.
static int ReadNumber (const char **p)
Parse the number at *p.
void CheckIsSingleName (const std::string &name, const Position &pos)
Check that the given name does not contain {hor(a..b)} or {vert(a..b)} strings.
Detailed Description
Support code for rcdgen.
Definition in file utils.cpp.
Function Documentation
static HorVert AddHor (HorVert hv) static
Add 'horizontal seen' to the set of seen parameters.
Parameters
hv Parameters seen up to now.
Returns
The updated parameter set.
Definition at line 63 of file utils.cpp.
References HV_BOTH, HV_HOR, HV_NONE, and HV_VERT.
Referenced by ParameterizedName::DecodeName().
static HorVert AddVert (HorVert hv) static
Add 'vertical seen' to the set of seen parameters.
Parameters
hv Parameters seen up to now.
Returns
The updated parameter set.
Definition at line 75 of file utils.cpp.
References HV_BOTH, HV_HOR, HV_NONE, and HV_VERT.
Referenced by ParameterizedName::DecodeName().
static int ReadNumber (const char ** p) static
Parse the number at *p.
Parameters
p [inout] Pointer to number text to parse. Gets updated to point after the last read digit after the number.
Returns
Value of the parsed number.
Precondition
Text should point to the first digit of the number to read.
Definition at line 88 of file utils.cpp.
Referenced by ParameterizedName::DecodeName().
void CheckIsSingleName (const std::string & name, const Position & pos)
Check that the given name does not contain {hor(a..b)} or {vert(a..b)} strings.
Parameters
name Name to check.
pos Position to report an error.
Definition at line 204 of file utils.cpp.
References ParameterizedName::HasNoParameters(), and Position::line.
Referenced by AssignNames().