FreeRCT: video.h File Reference
video.h File Reference
Video handling.
#include <set>
#include <SDL.h>
#include <SDL_ttf.h>
#include "geometry.h"
#include "palette.h"
Classes
class ClippedRectangle
Clipped rectangle.
class VideoSystem
Class representing the video system.
Enumerations
enum Alignment { ALG_LEFT, ALG_CENTER, ALG_RIGHT }
How to align text during drawing.
Functions
void QuitProgram ()
End the program.
Variables
VideoSystem _video
Video sub-system.
const uint32 _icon_data [32][32]
Taskbar icon in numeric form.
Detailed Description
Video handling.
Definition in file video.h.
Enumeration Type Documentation
enum Alignment
How to align text during drawing.
Enumerator
ALG_LEFT
Align to the left edge.
ALG_CENTER
Centre the text.
ALG_RIGHT
Align to the right edge.
Definition at line 47 of file video.h.
Function Documentation
void QuitProgram ()
End the program.
Definition at line 29 of file video.cpp.
References _finish.
Referenced by VideoSystem::HandleEvent(), HandleKeyInput(), and QuitProgramWindow::OnClick().
Variable Documentation
const uint32 _icon_data[32][32]
Taskbar icon in numeric form.
Definition at line 16 of file icon.cpp.
Referenced by VideoSystem::Initialize().