FreeRCT: video.cpp File Reference
video.cpp File Reference
Video handling.
#include "stdafx.h"
#include "video.h"
#include "sprite_data.h"
#include "palette.h"
#include "math_func.h"
#include "bitmath.h"
#include "rev.h"
#include "freerct.h"
#include "gamecontrol.h"
#include "window.h"
#include "viewport.h"
#include <string>
Typedefs
typedef uint8(* ShiftFunc)(uint8)
Type of the gradient shift function.
Functions
void QuitProgram ()
End the program.
static void UpdateMousePosition (int16 x, int16 y)
Update the mouse position in the program.
static uint8 ShiftGradientNight (uint8 col)
Gradient shift function for GS_NIGHT.
static uint8 ShiftGradientVeryDark (uint8 col)
Gradient shift function for GS_VERY_DARK.
static uint8 ShiftGradientDark (uint8 col)
Gradient shift function for GS_DARK.
static uint8 ShiftGradientSlightlyDark (uint8 col)
Gradient shift function for GS_SLIGHTLY_DARK.
static uint8 ShiftGradientNormal (uint8 col)
Gradient shift function for GS_NORMAL.
static uint8 ShiftGradientSlightlyLight (uint8 col)
Gradient shift function for GS_SLIGHTLY_LIGHT.
static uint8 ShiftGradientLight (uint8 col)
Gradient shift function for GS_LIGHT.
static uint8 ShiftGradientVeryLight (uint8 col)
Gradient shift function for GS_VERY_LIGHT.
static uint8 ShiftGradientDay (uint8 col)
Gradient shift function for GS_DAY.
static ShiftFunc GetGradientShiftFunc (GradientShift shift)
Select gradient shift function based on the shift.
static void BlitPixel (const ClippedRectangle &cr, uint32 *scr_base, int32 xmin, int32 ymin, uint16 numx, uint16 numy, uint16 width, uint16 height, uint32 colour)
Blit a pixel to an area of numx times numy sprites.
static void Blit8bppImages (const ClippedRectangle &cr, int32 x_base, int32 y_base, const ImageData *spr, uint16 numx, uint16 numy, const uint8 *recoloured)
Blit 8bpp images to the screen.
static void Blit32bppImages (const ClippedRectangle &cr, int32 x_base, int32 y_base, const ImageData *spr, uint16 numx, uint16 numy, const Recolouring &recolour, GradientShift shift)
Blit 32bpp images to the screen.
Variables
VideoSystem _video
Video sub-system.
static bool _finish
Finish execution of the main loop (and program).
static const int STEP_SIZE = 18
Amount of colour shift for each gradient step.
Detailed Description
Video handling.
Definition in file video.cpp.
Function Documentation
void QuitProgram ()
End the program.
Definition at line 29 of file video.cpp.
References _finish.
Referenced by VideoSystem::HandleEvent(), and QuitProgramWindow::OnClick().
static void UpdateMousePosition (int16 x, int16 y) static
Update the mouse position in the program.
Parameters
x New x position of the mouse.
y New y position of the mouse.
Definition at line 337 of file video.cpp.
References _manager, and WindowManager::MouseMoveEvent().
Referenced by VideoSystem::HandleEvent().
static uint8 ShiftGradientNight (uint8 col) static
Gradient shift function for GS_NIGHT.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 528 of file video.cpp.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientVeryDark (uint8 col) static
Gradient shift function for GS_VERY_DARK.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 538 of file video.cpp.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientDark (uint8 col) static
Gradient shift function for GS_DARK.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 548 of file video.cpp.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientSlightlyDark (uint8 col) static
Gradient shift function for GS_SLIGHTLY_DARK.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 558 of file video.cpp.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientNormal (uint8 col) static
Gradient shift function for GS_NORMAL.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 568 of file video.cpp.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientSlightlyLight (uint8 col) static
Gradient shift function for GS_SLIGHTLY_LIGHT.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 578 of file video.cpp.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientLight (uint8 col) static
Gradient shift function for GS_LIGHT.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 588 of file video.cpp.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientVeryLight (uint8 col) static
Gradient shift function for GS_VERY_LIGHT.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 598 of file video.cpp.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static uint8 ShiftGradientDay (uint8 col) static
Gradient shift function for GS_DAY.
Parameters
col Input colour.
Returns
Shifted result colour.
Definition at line 608 of file video.cpp.
References STEP_SIZE.
Referenced by GetGradientShiftFunc().
static ShiftFunc GetGradientShiftFunc (GradientShift shift) static
Select gradient shift function based on the shift.
Parameters
shift Desired amount of gradient shift.
Returns
Recolour function implementing the shift.
Definition at line 618 of file video.cpp.
References GS_DARK, GS_DAY, GS_LIGHT, GS_NIGHT, GS_NORMAL, GS_SLIGHTLY_DARK, GS_SLIGHTLY_LIGHT, GS_VERY_DARK, GS_VERY_LIGHT, NOT_REACHED, ShiftGradientDark(), ShiftGradientDay(), ShiftGradientLight(), ShiftGradientNight(), ShiftGradientNormal(), ShiftGradientSlightlyDark(), ShiftGradientSlightlyLight(), ShiftGradientVeryDark(), and ShiftGradientVeryLight().
Referenced by Blit32bppImages().
static void BlitPixel (const ClippedRectangle & cr, uint32 * scr_base, int32 xmin, int32 ymin, uint16 numx, uint16 numy, uint16 width, uint16 height, uint32 colour) static
Blit a pixel to an area of numx times numy sprites.
Parameters
cr Clipped rectangle.
scr_base Base address of the screen array.
xmin Minimal x position.
ymin Minimal y position.
numx Number of horizontal count.
numy Number of vertical count.
width Width of an image.
height Height of an image.
colour Pixel value to blit.
Note
Function does not handle alpha blending of the new pixel with the background.
Definition at line 660 of file video.cpp.
References ClippedRectangle::height, ClippedRectangle::pitch, and ClippedRectangle::width.
Referenced by Blit32bppImages(), and Blit8bppImages().
static void Blit8bppImages (const ClippedRectangle & cr, int32 x_base, int32 y_base, const ImageData * spr, uint16 numx, uint16 numy, const uint8 * recoloured) static
Blit 8bpp images to the screen.
Parameters
cr Clipped rectangle to draw to.
x_base Base X coordinate of the sprite data.
y_base Base Y coordinate of the sprite data.
spr The sprite to blit.
numx Number of sprites to draw in horizontal direction.
numy Number of sprites to draw in vertical direction.
recoloured Shifted palette to use.
Definition at line 694 of file video.cpp.
References _palette, ClippedRectangle::address, BlitPixel(), ImageData::data, ImageData::height, INVALID_JUMP, ClippedRectangle::pitch, ImageData::table, and ImageData::width.
Referenced by VideoSystem::BlitImages().
static void Blit32bppImages (const ClippedRectangle & cr, int32 x_base, int32 y_base, const ImageData * spr, uint16 numx, uint16 numy, const Recolouring & recolour, GradientShift shift) static
Blit 32bpp images to the screen.
Parameters
cr Clipped rectangle to draw to.
x_base Base X coordinate of the sprite data.
y_base Base Y coordinate of the sprite data.
spr The sprite to blit.
numx Number of sprites to draw in horizontal direction.
numy Number of sprites to draw in vertical direction.
recolour Sprite recolouring definition.
shift Gradient shift.
Definition at line 738 of file video.cpp.
References ClippedRectangle::address, BlitPixel(), ImageData::data, GetB(), GetG(), GetGradientShiftFunc(), GetR(), Recolouring::GetRecolourTable(), ImageData::height, MakeRGBA(), OPAQUE, ClippedRectangle::pitch, and ImageData::width.
Referenced by VideoSystem::BlitImages().