FreeRCT: viewport.cpp File Reference
viewport.cpp File Reference
Viewport window code.
#include "stdafx.h"
#include "math_func.h"
#include "viewport.h"
#include "map.h"
#include "video.h"
#include "palette.h"
#include "sprite_store.h"
#include "sprite_data.h"
#include "path_build.h"
#include "shop_placement.h"
#include "coaster_build.h"
#include "shop_type.h"
#include "terraform.h"
#include "select_mode.h"
#include "person.h"
#include "weather.h"
#include "fence.h"
#include "fence_build.h"
#include <set>
Classes
class VoxelCollector
Search the world for voxels to render.
struct DrawData
Data temporary needed for ordering sprites and blitting them to the screen.
class SpriteCollector
Collect sprites to draw in a viewport.
class PixelFinder
Find the sprite and pixel under the mouse cursor.
Typedefs
typedef std::multiset< DrawData > DrawImages
Collection of sprites to render to the screen.
Functions
void EnableWorldAdditions ()
Enable flashing display of showing proposed game world additions to the player.
void DisableWorldAdditions ()
Disable flashing display of showing proposed game world additions to the player.
static int32 ComputeXFunction (int32 x, int32 y, ViewOrientation orient, uint16 width)
Convert 3D position to the horizontal 2D position.
static int32 ComputeYFunction (int32 x, int32 y, int32 z, ViewOrientation orient, uint16 width, uint16 height)
Convert 3D position to the vertical 2D position.
bool operator< (const DrawData &dd1, const DrawData &dd2)
Sort predicate of the draw data.
static int DrawRide (int32 slice, int zpos, int32 basex, int32 basey, ViewOrientation orient, uint16 number, uint16 voxel_number, DrawData *dd, uint8 *platform)
Prepare to add the sprite for a ride.
Viewport * GetViewport ()
Get the address of the viewport window.
void MarkVoxelDirty (const XYZPoint16 &voxel_pos, int16 height)
Mark a voxel as in need of getting painted.
void ShowMainDisplay (const XYZPoint32 &view_pos)
Open the main isometric display window.
void InitMouseModes ()
Initialize the mouse modes.
Variables
WorldAdditions _additions
Proposed additions to the game world.
MouseModes _mouse_modes
Mouse modes in the game.
static const int ADDITIONS_TIMEOUT_LENGTH = 15
Length of the time interval of displaying or not displaying world additions.
Detailed Description
Viewport window code.
Definition in file viewport.cpp.
Function Documentation
void EnableWorldAdditions ()
Enable flashing display of showing proposed game world additions to the player.
Definition at line 101 of file viewport.cpp.
References Viewport::EnableWorldAdditions(), and GetViewport().
Referenced by ShopPlacementManager::ActivateMode(), and CoasterBuildMode::UpdateDisplay().
void DisableWorldAdditions ()
Disable flashing display of showing proposed game world additions to the player.
Definition at line 108 of file viewport.cpp.
References Viewport::DisableWorldAdditions(), and GetViewport().
Referenced by PathBuildManager::LeaveMode(), ShopPlacementManager::LeaveMode(), ShopPlacementManager::OnMouseButtonEvent(), PathBuildManager::PathBuildManager(), ShopPlacementManager::SetSelection(), CoasterBuildMode::UpdateDisplay(), and PathBuildManager::UpdateState().
static int32 ComputeXFunction (int32 x, int32 y, ViewOrientation orient, uint16 width) inline static
Convert 3D position to the horizontal 2D position.
Parameters
x X position in the game world.
y Y position in the game world.
orient Orientation.
width Tile width in pixels.
Returns
X position in 2D.
Definition at line 122 of file viewport.cpp.
References NOT_REACHED, VOR_EAST, VOR_NORTH, VOR_SOUTH, and VOR_WEST.
Referenced by VoxelCollector::ComputeX(), and Viewport::ComputeX().
static int32 ComputeYFunction (int32 x, int32 y, int32 z, ViewOrientation orient, uint16 width, uint16 height) inline static
Convert 3D position to the vertical 2D position.
Parameters
x X position in the game world.
y Y position in the game world.
z Z position in the game world.
orient Orientation.
width Tile width in pixels.
height Tile height in pixels.
Returns
Y position in 2D.
Definition at line 143 of file viewport.cpp.
References NOT_REACHED, VOR_EAST, VOR_NORTH, VOR_SOUTH, and VOR_WEST.
Referenced by VoxelCollector::ComputeY(), and Viewport::ComputeY().
bool operator< (const DrawData & dd1, const DrawData & dd2) inline
Sort predicate of the draw data.
Parameters
dd1 First value to compare.
dd2 Second value to compare.
Returns
true if dd1 should be drawn before dd2.
Definition at line 242 of file viewport.cpp.
References DrawData::base, DrawData::level, DrawData::order, Point< CT >::y, and DrawData::z_height.
static int DrawRide (int32 slice, int zpos, int32 basex, int32 basey, ViewOrientation orient, uint16 number, uint16 voxel_number, DrawData * dd, uint8 * platform) static
Prepare to add the sprite for a ride.
Parameters
slice Depth of this sprite.
zpos Z position of the voxel being drawn.
basex X position of the sprite in the screen.
basey Y position of the sprite in the screen.
orient View orientation.
number Ride instance number.
voxel_number Number of the voxel.
dd [out] Data to draw (4 entries).
platform [out] Shape of the support platform, if needed.
See also
PathSprites
Returns
The number of dd entries filled.
Definition at line 829 of file viewport.cpp.
References _rides_manager, DrawData::base, RideInstance::GetKind(), RidesManager::GetRideInstance(), RideInstance::GetSprites(), DrawData::level, DrawData::order, PATH_INVALID, DrawData::recolour, RideInstance::recolours, RTK_SHOP, SO_PLATFORM_BACK, SO_PLATFORM_FRONT, SO_RIDE, SO_RIDE_FRONT, DrawData::sprite, Point< CT >::x, Point< CT >::y, and DrawData::z_height.
Referenced by SpriteCollector::CollectVoxel(), and PixelFinder::CollectVoxel().
Viewport* GetViewport ()
Get the address of the viewport window.
Returns
Address of the viewport.
Note
Function may return nullptr.
Definition at line 1688 of file viewport.cpp.
References MouseModes::main_display.
Referenced by ShopPlacementManager::CanPlaceShop(), PathBuildManager::ComputeNewLongPath(), ShopPlacementManager::ComputeShopVoxel(), DisableWorldAdditions(), BottomToolbarWindow::DrawWidget(), EnableWorldAdditions(), SpriteCollector::GetCursorSpriteAtPos(), HandleKeyInput(), FenceBuildManager::LeaveMode(), TileTerraformMouseMode::LeaveMode(), MarkVoxelDirty(), PathBuildGui::OnClick(), CoasterBuildMode::OnMouseMoveEvent(), ShopPlacementManager::PlaceShop(), WindowManager::RepositionAllWindows(), PathBuildGui::SetButtons(), FenceBuildManager::SetCursors(), TileTerraformMouseMode::SetCursors(), PathBuildManager::SetPathGuiState(), VideoSystem::SetResolution(), CoasterBuildMode::UpdateDisplay(), and PathBuildManager::UpdateState().
void MarkVoxelDirty (const XYZPoint16 & voxel_pos, int16 height)
Mark a voxel as in need of getting painted.
Parameters
voxel_pos Position of the voxel.
height Number of voxels to mark above the specified coordinate (0 means inspect the voxel itself).
Definition at line 1698 of file viewport.cpp.
References GetViewport(), and Viewport::MarkVoxelDirty().
Referenced by AddRemovePathEdges(), BuildPathAtTile(), ChangePathAtTile(), VoxelObject::MarkDirty(), and RemovePathAtTile().
void InitMouseModes ()
Initialize the mouse modes.
Definition at line 1788 of file viewport.cpp.
References _coaster_builder, _fence_builder, _path_builder, _select_mousemode, _shop_placer, _terraformer, and MouseModes::RegisterMode().
Referenced by freerct_main().
Variable Documentation
WorldAdditions _additions
Proposed additions to the game world.
Not part of the game itself, but they are displayed by calling EnableWorldAdditions (and stopped being displayed with DisableWorldAdditions). The additions will flash on and off to show they are not decided yet.
Definition at line 95 of file viewport.cpp.
Referenced by BuildPathAtTile(), CoasterBuildWindow::BuildTrackPiece(), ChangeAreaCursorMode(), ChangePathAtTile(), ChangeTileCursorMode(), PathBuildManager::ComputeNewLongPath(), ExamineNeighbourPathEdge(), TerrainChanges::ModifyWorld(), CoasterBuildWindow::OnClick(), PathBuildManager::OnMouseButtonEvent(), ShopPlacementManager::OnMouseButtonEvent(), ShopPlacementManager::PlaceShop(), CoasterInstance::PlaceTrackPieceInAdditions(), RemovePathAtTile(), CoasterInstance::RemoveTrackPieceInAdditions(), PathBuildManager::SelectBuyRemove(), SetXFoundations(), SetYFoundations(), PathBuildManager::TileClicked(), CoasterBuildMode::UpdateDisplay(), and PathBuildManager::UpdateState().