FreeRCT: viewport.h File Reference
viewport.h File Reference
Main display data.
#include "window.h"
Classes
class FinderData
Data found by Viewport::ComputeCursorPosition.
class BaseCursor
Base class of a viewport cursor.
class Cursor
Single tile cursor.
class MultiCursor
Cursor consisting of one or more tiles.
class EdgeCursor
Single tile edge cursor.
class Viewport
Class for displaying parts of the world.
class MouseMode
A single mouse mode.
class DefaultMouseMode
Default mouse mode, selected when no other mouse mode is available.
class MouseModes
All mouse modes.
Enumerations
enum ViewportMouseMode {
MM_INACTIVE, MM_OBJECT_SELECT, MM_TILE_TERRAFORM, MM_PATH_BUILDING,
MM_SHOP_PLACEMENT, MM_COASTER_BUILD, MM_FENCE_BUILDING, MM_COUNT
}
Known mouse modes.
enum CursorType {
CUR_TYPE_NORTH, CUR_TYPE_EAST, CUR_TYPE_SOUTH, CUR_TYPE_WEST,
CUR_TYPE_TILE, CUR_TYPE_ARROW_NE, CUR_TYPE_ARROW_SE, CUR_TYPE_ARROW_SW,
CUR_TYPE_ARROW_NW, CUR_TYPE_EDGE_NE, CUR_TYPE_EDGE_SE, CUR_TYPE_EDGE_SW,
CUR_TYPE_EDGE_NW, CUR_TYPE_INVALID = 0xFF
}
Available cursor types.
enum ClickableSprite {
CS_NONE = 0, CS_GROUND = 1 << 0, CS_GROUND_EDGE = 1 << 1, CS_PATH = 1 << 2,
CS_RIDE = 1 << 3, CS_PERSON = 1 << 4, CS_LENGTH = 8, CS_MASK = 0x1f
}
Sprites that trigger an action when clicked on.
enum SpriteOrder {
SO_NONE = 0, SO_FOUNDATION = (1 << CS_LENGTH), SO_GROUND = (2 << CS_LENGTH) | CS_GROUND, SO_GROUND_EDGE = (3 << CS_LENGTH) | CS_GROUND_EDGE,
SO_FENCE_BACK = (4 << CS_LENGTH), SO_SUPPORT = (5 << CS_LENGTH), SO_PLATFORM = (6 << CS_LENGTH) | CS_RIDE, SO_PATH = (7 << CS_LENGTH) | CS_PATH,
SO_PLATFORM_BACK = (8 << CS_LENGTH) | CS_RIDE, SO_RIDE = (9 << CS_LENGTH) | CS_RIDE, SO_RIDE_CARS = (10 << CS_LENGTH) | CS_RIDE, SO_RIDE_FRONT = (11 << CS_LENGTH) | CS_RIDE,
SO_PLATFORM_FRONT = (12 << CS_LENGTH) | CS_RIDE, SO_PERSON = (13 << CS_LENGTH) | CS_PERSON, SO_FENCE_FRONT = (14 << CS_LENGTH), SO_CURSOR = (15 << CS_LENGTH)
}
Order of blitting sprites in a single voxel (earlier in the list is sooner).
enum GroundTilePart { FW_TILE, FW_CORNER, FW_EDGE }
Part of a ground tile to select.
Functions
void EnableWorldAdditions ()
Enable flashing display of showing proposed game world additions to the player.
void DisableWorldAdditions ()
Disable flashing display of showing proposed game world additions to the player.
Viewport * GetViewport ()
Get the address of the viewport window.
void MarkVoxelDirty (const XYZPoint16 &voxel_pos, int16 height=0)
Mark a voxel as in need of getting painted.
Variables
MouseModes _mouse_modes
Mouse modes in the game.
Detailed Description
Main display data.
Definition in file viewport.h.
Enumeration Type Documentation
enum ClickableSprite
Sprites that trigger an action when clicked on.
Enumerator
CS_NONE
No valid sprite.
CS_GROUND
Ground sprite.
CS_GROUND_EDGE
Ground edge sprite.
CS_PATH
Path sprite.
CS_RIDE
Ride sprite.
CS_PERSON
Person sprite.
CS_LENGTH
Bitlength of the enum.
CS_MASK
Used for converting between this and SpriteOrder.
Definition at line 62 of file viewport.h.
enum SpriteOrder
Order of blitting sprites in a single voxel (earlier in the list is sooner).
The number shifted by CS_LENGTH denotes the order, the lower bits are used to denote the kind of sprite being plotted, for mouse-click detection.
See also
PixelFinder, Viewport::ComputeCursorPosition
Enumerator
SO_NONE
No drawing.
SO_FOUNDATION
Draw foundation sprites.
SO_GROUND
Draw ground sprites.
SO_GROUND_EDGE
Used for ground edge detection.
SO_FENCE_BACK
Draw fence on the back edges.
SO_SUPPORT
Draw support sprites.
SO_PLATFORM
Draw platform sprites.
SO_PATH
Draw path sprites.
SO_PLATFORM_BACK
Background behind the ride (platform background).
SO_RIDE
Draw ride sprites.
SO_RIDE_CARS
Cars at a ride.
SO_RIDE_FRONT
Ride sprite to draw after drawing the cars.
SO_PLATFORM_FRONT
Front of platform.
SO_PERSON
Draw person sprites.
SO_FENCE_FRONT
Draw fence on the front edges.
SO_CURSOR
Draw cursor sprites.
Definition at line 81 of file viewport.h.
enum GroundTilePart
Part of a ground tile to select.
Enumerator
FW_TILE
Find whole tile only.
FW_CORNER
Find whole tile or corner.
FW_EDGE
Find tile edge.
Definition at line 101 of file viewport.h.
Function Documentation
void EnableWorldAdditions ()
Enable flashing display of showing proposed game world additions to the player.
Definition at line 101 of file viewport.cpp.
References Viewport::EnableWorldAdditions(), and GetViewport().
void DisableWorldAdditions ()
Disable flashing display of showing proposed game world additions to the player.
Definition at line 108 of file viewport.cpp.
References Viewport::DisableWorldAdditions(), and GetViewport().
Viewport* GetViewport ()
Get the address of the viewport window.
Returns
Address of the viewport.
Note
Function may return nullptr.
Definition at line 1688 of file viewport.cpp.
References MouseModes::main_display.
Referenced by ShopPlacementManager::CanPlaceShop(), PathBuildManager::ComputeNewLongPath(), ShopPlacementManager::ComputeShopVoxel(), DisableWorldAdditions(), BottomToolbarWindow::DrawWidget(), EnableWorldAdditions(), SpriteCollector::GetCursorSpriteAtPos(), HandleKeyInput(), FenceBuildManager::LeaveMode(), TileTerraformMouseMode::LeaveMode(), MarkVoxelDirty(), PathBuildGui::OnClick(), CoasterBuildMode::OnMouseMoveEvent(), ShopPlacementManager::PlaceShop(), WindowManager::RepositionAllWindows(), PathBuildGui::SetButtons(), FenceBuildManager::SetCursors(), TileTerraformMouseMode::SetCursors(), PathBuildManager::SetPathGuiState(), VideoSystem::SetResolution(), CoasterBuildMode::UpdateDisplay(), and PathBuildManager::UpdateState().
void MarkVoxelDirty (const XYZPoint16 & voxel_pos, int16 height)
Mark a voxel as in need of getting painted.
Parameters
voxel_pos Position of the voxel.
height Number of voxels to mark above the specified coordinate (0 means inspect the voxel itself).
Definition at line 1698 of file viewport.cpp.
References GetViewport(), and Viewport::MarkVoxelDirty().
Referenced by AddRemovePathEdges(), BuildPathAtTile(), VoxelObject::MarkDirty(), and RemovePathAtTile().