FreeRCT: window.cpp File Reference
window.cpp File Reference
Window handling functions.
#include "stdafx.h"
#include "window.h"
#include "video.h"
#include "math_func.h"
#include "palette.h"
#include "sprite_store.h"
#include "ride_type.h"
#include "viewport.h"
Classes
class ComputeInitialPosition
Compute the initial position of a window.
Functions
static uint GetWindowZPriority (WindowTypes wt)
Get the z-priority of a window type (higher number means further up in the window stack).
bool IsLeftClick (uint8 state)
Does the mouse button state express a left-click?
static int GetDistanceToMouse (const Point32 &pt)
Get distance of a position to the mouse.
void UpdateWindows ()
Redraw (parts of) the windows.
Window * GetWindowByType (WindowTypes wtype, WindowNumber wnumber)
Find an opened window by window type.
void NotifyChange (WindowTypes wtype, WindowNumber wnumber, ChangeCode code, uint32 parameter)
Notify the window of the given type of the change with the specified number.
bool HighlightWindowByType (WindowTypes wtype, WindowNumber wnumber)
Highlight and raise a window of a given type.
Variables
WindowManager _manager
Window manager.
Detailed Description
Window handling functions.
Todo:
[low] Consider the case where we don't have a video system.
Definition in file window.cpp.
Function Documentation
static int GetDistanceToMouse (const Point32 & pt) static
Get distance of a position to the mouse.
Parameters
pt Queried point.
Returns
Estimated distance.
Todo:
[easy] Estimate is pretty stupid, and can be improved. (Partly diagonal + partly horizontal or vertical suffices.)
Definition at line 136 of file window.cpp.
References WindowManager::GetMousePosition(), Point< CT >::x, and Point< CT >::y.
Referenced by ComputeInitialPosition::FindPosition().
void NotifyChange (WindowTypes wtype, WindowNumber wnumber, ChangeCode code, uint32 parameter)
Notify the window of the given type of the change with the specified number.
Parameters
wtype Window type to look for.
wnumber Window number to look for (use ALL_WINDOWS_OF_TYPE for any window of type wtype).
code Unique change number.
parameter Parameter of the change number
Definition at line 1043 of file window.cpp.
References GetWindowByType(), and Window::OnChange().
Referenced by Guest::ChangeHappiness(), ShopPlacementManager::LeaveMode(), FinancesManager::NotifyGui(), DropdownMenuWindow::OnClick(), ShopPlacementManager::OnMouseButtonEvent(), CoasterBuildStateMouse::OnMouseButtonEvent(), OnNewDay(), RideInstance::OnNewMonth(), RideInstance::OpenRide(), Viewport::Rotate(), RideInstance::SellItem(), GameModeManager::SetGameMode(), and PathBuildManager::UpdateState().