FreeRCT: window.h File Reference
window.h File Reference
Window handling data structures.
#include "geometry.h"
#include "orientation.h"
#include "widget.h"
#include <vector>
Classes
class DropdownItem
An item in a dropdown list.
class Window
Window base class.
class GuiWindow
Base class for windows with a widget tree.
class WindowManager
Window manager class, manages the window stack.
Typedefs
typedef std::vector< DropdownItem > DropdownList
A dropdown list is a collection of DropdownItem items.
typedef uint32 WindowNumber
Type of a window number.
Enumerations
enum WindowTypes {
WC_MAINDISPLAY, WC_TOOLBAR, WC_BOTTOM_TOOLBAR, WC_QUIT,
WC_ERROR_MESSAGE, WC_GUEST_INFO, WC_COASTER_MANAGER, WC_COASTER_BUILD,
WC_PATH_BUILDER, WC_RIDE_SELECT, WC_SHOP_MANAGER, WC_FENCE,
WC_TERRAFORM, WC_FINANCES, WC_SETTING, WC_DROPDOWN,
WC_NONE
}
Available types of windows.
enum ChangeCode {
CHG_UPDATE_BUTTONS, CHG_VIEWPORT_ROTATED, CHG_MOUSE_MODE_LOST, CHG_DISPLAY_OLD,
CHG_PIECE_POSITIONED, CHG_DROPDOWN_RESULT
}
Codes of the NotifyChange function, which gets forwarded through the Window::OnChange method.
enum WindowFlags { WF_HIGHLIGHT = 1 << 0 }
Various state flags of the Window.
enum MouseButtons {
MB_LEFT = 1, MB_MIDDLE = 2, MB_RIGHT = 4, MB_CURRENT = 0x07,
MB_PREVIOUS = 0x70, MB_PREV_SHIFT = 4
}
Known mouse buttons.
enum WmMouseEvent { WMME_NONE, WMME_CLOSE_WINDOW, WMME_MOVE_WINDOW }
Mouse events of the window manager.
enum WmKeyCode {
WMKC_CURSOR_UP, WMKC_CURSOR_LEFT, WMKC_CURSOR_RIGHT, WMKC_CURSOR_DOWN,
WMKC_BACKSPACE, WMKC_DELETE, WMKC_CANCEL, WMKC_CONFIRM,
WMKC_SYMBOL
}
Key codes of the window manager.
enum WmMouseModes { WMMM_PASS_THROUGH, WMMM_MOVE_WINDOW }
Available mouse modes of the window manager.
Functions
bool IsLeftClick (uint8 state)
Does the mouse button state express a left-click?
void UpdateWindows ()
Redraw (parts of) the windows.
Window * GetWindowByType (WindowTypes wtype, WindowNumber wnumber)
Find an opened window by window type.
bool HighlightWindowByType (WindowTypes wtype, WindowNumber wnumber)
Highlight and raise a window of a given type.
void NotifyChange (WindowTypes wtype, WindowNumber wnumber, ChangeCode code, uint32 parameter)
Notify the window of the given type of the change with the specified number.
void ShowMainDisplay (const XYZPoint32 &view_pos)
Open the main isometric display window.
void ShowToolbar ()
Open the main toolbar window.
void ShowBottomToolbar ()
Open the bottom toolbar window.
void ShowGuestInfoGui (const Person *person)
Open a window to view a given guest's info.
void ShowPathBuildGui ()
Open the path build GUI.
void ShowRideSelectGui ()
Open the ride selection GUI.
void ShowShopManagementGui (uint16 ri)
Open a window to manage a given shop.
void ShowFenceGui ()
Open the fence GUI.
void ShowTerraformGui ()
Open the terraform window (or if it is already opened, highlight and raise it).
void ShowFinancesGui ()
Open the finances window (or if it is already opened, highlight and raise it).
void ShowCoasterManagementGui (RideInstance *coaster)
Open a roller coaster management window for the given roller coaster ride.
void ShowCoasterBuildGui (CoasterInstance *coaster)
Open a roller coaster build/edit window for the given roller coaster.
void ShowErrorMessage (StringID strid)
Open an error message window.
void ShowSettingGui ()
Open the settings window.
Variables
static const WindowNumber ALL_WINDOWS_OF_TYPE = UINT32_MAX
Window number parameter meaning 'all windows of the window type'.
WindowManager _window_manager
Window manager.
Detailed Description
Window handling data structures.
Definition in file window.h.
Typedef Documentation
typedef std::vector<DropdownItem> DropdownList
A dropdown list is a collection of DropdownItem items.
Definition at line 34 of file window.h.
Enumeration Type Documentation
enum ChangeCode
Codes of the NotifyChange function, which gets forwarded through the Window::OnChange method.
Enumerator
CHG_UPDATE_BUTTONS
Recompute the state of the buttons.
CHG_VIEWPORT_ROTATED
Viewport rotated.
CHG_MOUSE_MODE_LOST
Lost the mouse mode.
CHG_DISPLAY_OLD
Displayed data is old.
CHG_PIECE_POSITIONED
The track piece is at the correct position.
CHG_DROPDOWN_RESULT
The selection of a dropdown window.
Definition at line 62 of file window.h.
enum WindowFlags
Various state flags of the Window.
Enumerator
WF_HIGHLIGHT
Window edge is highlighted.
Definition at line 72 of file window.h.
Function Documentation
void NotifyChange (WindowTypes wtype, WindowNumber wnumber, ChangeCode code, uint32 parameter)
Notify the window of the given type of the change with the specified number.
Parameters
wtype Window type to look for.
wnumber Window number to look for (use ALL_WINDOWS_OF_TYPE for any window of type wtype).
code Unique change number.
parameter Parameter of the change number
Definition at line 1054 of file window.cpp.
References GetWindowByType(), and Window::OnChange().
Referenced by Guest::ChangeHappiness(), ShopPlacementManager::LeaveMode(), FinancesManager::NotifyGui(), DropdownMenuWindow::OnClick(), ShopPlacementManager::OnMouseButtonEvent(), CoasterBuildStateMouse::OnMouseButtonEvent(), OnNewDay(), RideInstance::OnNewMonth(), RideInstance::OpenRide(), Viewport::Rotate(), RideInstance::SellItem(), GameModeManager::SetGameMode(), and PathBuildManager::UpdateState().
void ShowGuestInfoGui (const Person * person)
Open a window to view a given guest's info.
Parameters
person Person to view.
Definition at line 126 of file person_gui.cpp.
References HighlightWindowByType(), Person::id, and WC_GUEST_INFO.
Referenced by SelectMouseMode::OnMouseButtonEvent().
void ShowShopManagementGui (uint16 number)
Open a window to manage a given shop.
Parameters
number Shop to manage.
Definition at line 239 of file shop_gui.cpp.
References _rides_manager, RideInstance::GetKind(), RidesManager::GetRideInstance(), HighlightWindowByType(), RTK_SHOP, and WC_SHOP_MANAGER.
Referenced by SelectMouseMode::OnMouseButtonEvent().
void ShowTerraformGui ()
Open the terraform window (or if it is already opened, highlight and raise it).
Definition at line 222 of file terraform_gui.cpp.
References ALL_WINDOWS_OF_TYPE, HighlightWindowByType(), and WC_TERRAFORM.
Referenced by ToolbarWindow::OnClick().
void ShowFinancesGui ()
Open the finances window (or if it is already opened, highlight and raise it).
Definition at line 123 of file finances_gui.cpp.
References ALL_WINDOWS_OF_TYPE, HighlightWindowByType(), and WC_FINANCES.
Referenced by ToolbarWindow::OnClick().
void ShowCoasterManagementGui (RideInstance * coaster)
Open a roller coaster management window for the given roller coaster ride.
Parameters
coaster Coaster instance to display.
Definition at line 86 of file coaster_gui.cpp.
References CoasterInstance::DecideRideState(), RideInstance::GetIndex(), RideInstance::GetKind(), HighlightWindowByType(), RIS_CLOSED, RIS_OPEN, RIS_TESTING, RTK_COASTER, ShowCoasterBuildGui(), and WC_COASTER_MANAGER.
Referenced by RideSelectGui::OnClick(), and SelectMouseMode::OnMouseButtonEvent().
void ShowCoasterBuildGui (CoasterInstance * coaster)
Open a roller coaster build/edit window for the given roller coaster.
Parameters
coaster Coaster instance to modify.
Definition at line 613 of file coaster_gui.cpp.
References RideInstance::GetIndex(), RideInstance::GetKind(), HighlightWindowByType(), RTK_COASTER, and WC_COASTER_BUILD.
Referenced by ShowCoasterManagementGui().